openshift/ci-tools

pkg/controller/test-images-distributor/test_images_distributor.go

In the last 12 hours: 99 hits in total where 2 of them are in upsert function.

test-images-distributor: ingore logging IsConflict errors

---

cmd/release-job-migrator/main.go
test/integration/release-job-migrator/expected/ci-operator/openshift/release/openshift-release-master__okd-4.7.yaml
test/integration/release-job-migrator/expected/ci-operator/openshift/release/openshift-release-master__origin-4.4-nightly-to-4.4-nightly.yaml
test/integration/release-job-migrator/expected/ci-operator/openshift/release/openshift-release-master__origin-4.5-stable-to-4.6-ci.yaml
test/integration/release-job-migrator/expected/ci-operator/openshift/release/openshift-release-master__origin-4.6-to-4.7.yaml
test/integration/release-job-migrator/expected/ci-operator/openshift/release/openshift-release-master__origin-4.6.yaml
test/integration/release-job-migrator/expected/ci-operator/openshift/release/openshift-release-master__origin-4.7.yaml

The `base` image shouldn't really be necessary for tests, so it
shouldn't be added by default.

release-job-migrator: don't add `base` to `base_images`

---

pkg/defaults/defaults.go
pkg/defaults/defaults_test.go

Multi-stage tests can add the same input image to the graph several
times, resulting in duplicate work:
```
$ ci-operator --config openshift/origin/openshift-origin-master.yaml --registry ci-operator/step-registry --target e2e-aws --print-graph > /dev/null
2020/12/18 17:26:52 unset version 0
2020/12/18 17:26:52 Resolved source https://github.com/openshift/origin to master@4f87b290, merging: #25762 615c1e80 @bbguimaraes
2020/12/18 17:26:53 Resolved openshift/release:golang-1.14 to sha256:b208e61f91c728fb0f4c7a17b7a5cc9176444daed9c8092d4e5ed6ef397214cf
2020/12/18 17:26:54 Resolved ocp/4.7:base to sha256:561f60ffd5df5b6cfd153f4c4389c997f569faae64a9489bd8c9e8fb516d9bd9
2020/12/18 17:26:54 Resolved ocp/builder:golang-1.13 to sha256:5203eafca990af755122d5274149eb5557fc6873a7b50c3152f31a2603ef00d …
```

pkg/defaults: deduplicate input images

---

pkg/api/types.go
pkg/defaults/defaults.go
pkg/steps/release/promote.go
pkg/steps/release/promote_test.go
pkg/steps/release/release_images.go
pkg/webreg/zz_generated.ci_operator_reference.go

Searching git history in openshift/release shows this is not used (and never was):
```console
$ git grep name_prefix
$ git log -G '.*name_prefix:.*'
```
So why bother carrying it...
/cc @stevekuznetsov @smarterclayton  
WDYT?

ci-operator: remove name_prefix fields

---

pkg/steps/release/promote.go
pkg/steps/release/promote_test.go
pkg/steps/release/testdata/zz_fixture_TestGetPromotionPod_basic_case.yaml

The `oc image mirror` ~occasionally~ regularly fails for random reasons, like e.G. here: https://prow.ci.openshift.org/view/gs/origin-ci-test/logs/branch-ci-openshift-ci-tools-master-images/1341157780760825856
Looking at https://prow.ci.openshift.org/job-history/gs/origin-ci-test/logs/branch-ci-openshift-ci-tools-master-images this seems to be happening very frequently (~50%-66% of runs) and its always due to errors when running `oc image mirror`
This PR adds some nice bash-based retrying to it.

Retry oc image mirror when promoting

---

pkg/steps/release/promote.go
pkg/steps/release/testdata/zz_fixture_TestGetPromotionPod_basic_case.yaml

Or we will fail like this: https://prow.ci.openshift.org/view/gs/origin-ci-test/logs/branch-ci-openshift-ci-tools-master-images/1341456330409381888#1:build-log.txt%3A159

Promotion retrying: Remove wrong shift

---

cmd/ci-secret-bootstrap/main.go
cmd/ci-secret-bootstrap/main_test.go
pkg/bitwarden/bitwarden.go
pkg/bitwarden/cli_test.go

Avoid tripping dptp-triage alert about unused secrets when working with
secrets. Allows setting up BW items with bootsrap config followups.

ci-secret-bootstrap: tolerate unused secrets for 7 days after modification

---

Makefile
pkg/steps/release/create_release.go
pkg/steps/release/import_release.go
test/e2e/framework/framework.go
test/e2e/simple/e2e_test.go

The image reference field in the image import API is documented as being
the correct place from which to pull the imported image, but from
experience we see that it's just the image reference in the stream,
pointing to the image that was imported. As the mechanisms for
authenticating the import are different from the mechanisms used for
using the image directly, it's possible (and likely) that a client that
may import the image may not be able to use it directly. Furthermore,
there's no utility to using the image reference, without a direct pull,
as that is the entire point in doing the import in the first place. By
using out image reference resolution code we can make sure that the
fully resolved pull-spec that we end up using is a local reference and
the kubelet will be able to pull it …

ci-operator: resolve imported release image pullspec better

---

test/e2e/framework/framework.go

```
$ KUBECONFIG=~/.kube/config make install local-e2e
go install ./cmd/...
oc config use-context "build01"
Switched to context "build01".
make[1]: Entering directory '/home/stevekuznetsov/code/openshift/ci-tools/src/github.com/openshift/ci-tools'
PACKAGES="./test/e2e/..." TESTFLAGS=" -tags e2e -timeout 40m -parallel 100" hack/test-go.sh
+ gotestsum -- ./test/e2e/... -race -tags e2e -timeout 40m -parallel 100
∅  test/e2e/framework
✓  test/e2e/multi-stage (4m21.69s)
✓  test/e2e/simple (20m54.12s)
DONE 26 tests in 1254.995s
```

e2e: idk what i am doing

---

pkg/steps/release/import_release.go

We want users to refer to images after import with their location on the
registry they just got imported to.

ci-operator: use local tag reference policy

---

pkg/steps/release/promote.go
pkg/steps/release/testdata/zz_fixture_TestGetPromotionPod_basic_case.yaml

Instead of running each promotion serially, allow one mirror command to
push up to 20 images at once. Ensure that it continues on error, and
retry the total push if anything fails.

ci-operator: be more performant on promotion

---

pkg/steps/release/import_release.go

The default pull secret is always $HOME/.docker/config.json, there
is no need for registry config.

steps/import_release: Always use the correct pull configuration

---

pkg/controller/serviceaccount_secret_refresher/serviceaccount_secret_refresher.go
pkg/controller/serviceaccount_secret_refresher/serviceaccount_secret_refresher_test.go

Currently, we use the same interval to create a new secret and delete
the old one. This doesn't give consumers a window to rotate their
secret. This change adds such a window and only deletes secrets after 2x
staleness time (60 days).

ServiceAccountSecretRefresher: Add graceperiod beetween creation and deletion

---

cmd/determinize-ci-operator/main.go
cmd/determinize-ci-operator/main_test.go
test/integration/release-job-migrator/expected/ci-operator/openshift/release/openshift-release-master__origin-4.6-to-4.7.yaml
test/integration/release-job-migrator/input/jobs/openshift-release-release-4.7-periodics.yaml

The openshift-e2e-test step is changing to focus on test types
(upgrade, upgrade then test, multiple upgrades) and TEST_COMMAND
is no longer the appropriate mapping for an upgrade test. Update
the migrator to take that into account.

determinize-ci-operator: Use TEST_TYPE instead of TEST_COMMAND

---

cmd/applyconfig/applyconfig.go
cmd/applyconfig/applyconfig_test.go
go.mod
go.sum
vendor/github.com/hashicorp/go-version/LICENSE
vendor/github.com/hashicorp/go-version/README.md
vendor/github.com/hashicorp/go-version/constraint.go
vendor/github.com/hashicorp/go-version/go.mod
vendor/github.com/hashicorp/go-version/version.go
vendor/github.com/hashicorp/go-version/version_collection.go
vendor/modules.txt

Make applyconfig run `oc version` to detect the version of OpenShift we
run against, and select the set of parameters used for dry run based on
the version (it can be overriden by the `--dry-run-method` parameter).
The tool prefers stricter, server-side validation so it is intentionally
selected on various detection errors.
Initially, the detection is opt-in and client dry-run is selected by
default, because our manifests currently do not pass stricter
validation. I want to fix our manifests by running rehearsal with the
auto mode enabled, then we can switch the auto mode to be the default,
without the need to change the actual jobs.

applyconfig: optionally allow server-side dry-runs with validation

---

pkg/steps/source.go
pkg/steps/testdata/zz_fixture_TestCreateBuild_basic_options_for_a_presubmit.yaml
pkg/steps/testdata/zz_fixture_TestCreateBuild_with_OAuth_token.yaml
pkg/steps/testdata/zz_fixture_TestCreateBuild_with_a_path_alias.yaml
pkg/steps/testdata/zz_fixture_TestCreateBuild_with_a_pull_secret.yaml
pkg/steps/testdata/zz_fixture_TestCreateBuild_with_extra_refs.yaml
pkg/steps/testdata/zz_fixture_TestCreateBuild_with_extra_refs_setting_workdir_and_path_alias.yaml
pkg/steps/testdata/zz_fixture_TestCreateBuild_with_ssh_key.yaml

When CI went down yesterday it took some time to figure out how to set
the log level for builds, as that is not part of any spec. This changes
includes the responsible env var together with the default value to make
finding this setting easier in the future.

Builds: Include the log level env var for documentation

---

cmd/release-job-migrator/main.go
test/integration/release-job-migrator.sh
test/integration/release-job-migrator/expected/_allow-list.yaml
test/integration/release-job-migrator/input/_allow-list.yaml

This PR adds support for updating the testgrid allowlist for migrated
jobs, which is necessary to allow the jobs to continue appearing on
testgrid with their new names.

release-job-migrator: support updating testgrid allowlist

---

cmd/registry-replacer/main.go
cmd/registry-replacer/main_test.go

To achieve https://github.com/openshift/release/pull/14724
/hold
Should go together with openshift/ocp-build-data#796

registry-replacer: use app.ci'registry in ci-op's configs

---

pkg/api/ocpbuilddata/types.go
pkg/api/ocpbuilddata/types_test.go

Missed in https://github.com/openshift/ci-tools/pull/1587
I just realized that https://github.com/openshift/ci-tools/pull/1587 has nothing to do with the registry hostname used in `config.images.input[key].as`.
The expecting replacement took place already before merging the PR, for example, https://github.com/openshift/release/pull/14786/files.
The impact of https://github.com/openshift/ci-tools/pull/1587 is
* the PR message 
* `config.images.ContextDir` and `config.images.DockerfilePath`: The current PR is needed for those fields to be calculated correctly.

ocpbuilddata api: use app.ci's registry

---

pkg/steps/run.go
pkg/steps/run_test.go

In this example [job](https://prow.ci.openshift.org/view/gs/origin-ci-test/pr-logs/pull/eclipse_che-operator/553/pull-ci-eclipse-che-operator-master-v4-che-operator-update/1332264893667086336#1:build-log.txt%3A34) the ci-operator reports the cancelled context error from all of the interrupted steps. 
This PR changes this logic and allows only the `interrupted` error to be reported in the results server.

[DPTP-1789] Ignore context cancelled errors from steps when the job is interrupted

---

cmd/ci-operator/main.go

Otherwise a loss of the watcher results in an infinite loop.

ci-operator: recreate ns watcher when necessary

---

pkg/webreg/webreg.go
pkg/webreg/webreg_test.go

Resolves: [DPTP-1652](https://issues.redhat.com/browse/DPTP-1652)
Expose dependencies of the steps involved in the workflows and chains together with the envvars that expose them to tests. The workflow view also shows whether the value is set by the workflow or the step. The data structure for the presentation is a bit complicated because the same dependency can be exposed under different names in multiple steps.
Examples:
- Workflow: https://server-ci-tools-1600.apps.ci.l2s4.p1.openshiftapps.com/workflow/openshift-upgrade-gcp#dependencies
- Chain: https://server-ci-tools-1600.apps.ci.l2s4.p1.openshiftapps.com/chain/ipi-install-stableinitial#dependencies
The code needs a bit more polishing to be mergeable but I am interested in the feedback for how the data is presented before I do that. …

webreg: collect and expose workflow/chain dependencies in UI

---

cmd/repo-init/main.go
cmd/repo-init/main_test.go
test/integration/repo-init/expected/core-services/prow/02_config/_config.yaml
test/integration/repo-init/input/core-services/prow/02_config/_config.yaml

o/origin is now a snowflake (its newer branches do not participate in
the OCP process) so we should no longer use it as an anchor for adding
new repos.

repo-init: copycat CVO merge criteria instead of origin

---

go.mod
pkg/api/types.go
pkg/prowgen/prowgen.go
pkg/prowgen/prowgen_test.go
pkg/prowgen/testdata/zz_fixture_TestGeneratePeriodicForTest_periodic_for_specific_release_using_interval.yaml
pkg/validation/test.go
pkg/validation/test_test.go
pkg/webreg/zz_generated.ci_operator_reference.go
test/integration/ci-operator-prowgen/input/config/super/duper/super-duper-master.yaml
test/integration/ci-operator-prowgen/output/jobs/super/duper/super-duper-master-periodics.yaml
vendor/modules.txt

This PR adds support for using the `interval` field for periodics
instead of `cron`. This allows users to set intervals for running jobs
more easily than `cron` without having to use `@every duration` in,
which would result in the job getting triggered every time horologium
restarts.

ci-operator: add support for interval field

---

cmd/release-job-migrator/main.go
test/integration/release-job-migrator.sh
test/integration/release-job-migrator/expected/jobs/openshift-release-release-4.8-periodics.yaml
test/integration/release-job-migrator/expected/jobs/openshift-release-release-4.9-periodics.yaml
test/integration/release-job-migrator/input/jobs/openshift-release-release-4.8-periodics.yaml
test/integration/release-job-migrator/input/jobs/openshift-release-release-4.9-periodics.yaml

This PR adds a new flag to the release-job-migrator that allows the user
to ignore a specified release (or multiple releases). This will be
useful to make sure that the migration doesn't cause any issues for
releases that are close to freeze (currently 4.7).

release-job-migrate: add ignore-release flag

---

cmd/ci-secret-bootstrap/main.go
cmd/ci-secret-bootstrap/main_test.go

The current error is pretty much useless for finding the offending item

Secret bootstrapper: Allow finding config entry for faulty dockercfg

---

pkg/api/types.go
pkg/steps/pod.go
pkg/steps/pod_test.go
pkg/steps/testdata/zz_fixture_mountsTestGetPodObjectMounts_with_artifacts__multiple_secrets_and_path_results_in_multiple_mounts.yaml
pkg/steps/testdata/zz_fixture_mountsTestGetPodObjectMounts_with_artifacts__multiple_secrets_and_path_results_with_unspecified_mounts.yaml
pkg/steps/testdata/zz_fixture_volumesTestGetPodObjectMounts_with_artifacts__multiple_secrets_and_path_results_in_multiple_mounts.yaml
pkg/steps/testdata/zz_fixture_volumesTestGetPodObjectMounts_with_artifacts__multiple_secrets_and_path_results_with_unspecified_mounts.yaml
pkg/steps/testdata/zz_fixture_volumesTestGetPodObjectMounts_with_secret_name_and_path_results_in_mounted_secret_with_custom_path.yaml
pkg/steps/testdata/zz_fixture_volumesTestGetPodObjectMounts_with_secret_name_results_in_secret_mounted_with_default_path.yaml
pkg/webreg/zz_generated.ci_operator_reference.go

Example:
could not run steps: step launch failed: failed to create or restart test pod: unable to create pod: Pod "launch" is invalid: spec.volumes[1].name: Duplicate value: "test-secret"

Multiple secrets: causes spec.volumes[].name duplication

---

cmd/release-job-migrator/main.go
test/integration/release-job-migrator/expected/ci-operator/openshift/release/openshift-release-master__ocp-4.7.yaml
test/integration/release-job-migrator/expected/ci-operator/openshift/release/openshift-release-master__okd-4.7.yaml
test/integration/release-job-migrator/expected/ci-operator/openshift/release/openshift-release-master__origin-4.6.yaml
test/integration/release-job-migrator/expected/ci-operator/openshift/release/openshift-release-master__origin-4.7.yaml

This PR updates the release-job-migrator to use the recently added
interval field for ci-operator defined tests instead of converting job
intervals to `@every interval` crons.

release-job-migrator: support interval

---

pkg/api/types.go
pkg/prowgen/prowgen.go

Add an additional Azure profile for clusters with the Arc-enabled
Kubernetes feature.
For CI purposes, Arc-enabled clusters have absolutely no difference
when compared to other `azure4` clusters and are created the same way,
however they [must run in specific Azure regions](https://docs.microsoft.com/en-us/azure/azure-arc/kubernetes/connect-cluster#supported-regions) where that feature is
already provided.
In this PR we create a new cluster profile to allow us to have a
separate Boskos quota slice only with the supported regions, but
everything else (cluster installation, etc) must work like a regular 
`azure4` cluster.
Related to: https://github.com/openshift/release/pull/14798

Add azure-arc cluster profile

---

pkg/api/types.go

We would like to stand-up temporary OSD clusters from cluster-bot. This establishes a cluster-type for the new quota.

Establish osd-ephemeral cluster type for SDE-791

---

cmd/ci-secret-bootstrap/main.go
cmd/ci-secret-bootstrap/main_test.go
pkg/controller/secretsyncer/secretsyncer.go

Follow up https://github.com/openshift/ci-tools/pull/1601#discussion_r557520722

Use the same label for CRs created by ci-tools

---

pkg/steps/release/create_release.go
pkg/steps/release/import_release.go

When we create artifacts in these steps, we should honor the environment
variable that tells us where to put them instead of guessing as to where
the literal artifact dir may end up being.
/assign @alvaroaleman @smarterclayton

ci-operator: releases: use artifact dir env

---

pkg/steps/release/create_release.go
pkg/steps/release/import_release.go

In order to not rely on the artifact gathering code, we can take
advantage of the fact that we are running as the `ci-operator` service
account in the release `Pod` and we have access to the `oc` CLI by putting
the data we need into a `ConfigMap` and reading it out of that.
Part of [DPTP-1819](https://issues.redhat.com/browse/DPTP-1819)
Depends on https://github.com/openshift/ci-tools/pull/1620

ci-operator: release: use a configmap for data transfer

---

pkg/steps/release/create_release.go
pkg/steps/release/import_release.go

Revert "Merge pull request #1628 from droslean/revert-1621-skuznets/disseminate-using-secrets"
This reverts commit f2307ee0c2a97a32ff2be8b406e8f5f722a8fbc8, reversing
changes made to 39b561df7c221cabcd6be6a13d993985cef266b3.
---
ci-operator: release: delete configmap if it exists
---
/assign @petr-muller @alvaroaleman

Try creating ConfigMaps again

---

pkg/github/prcreation/prcreation.go

This PR fixes the `UpsertPR` function, used by `autotestgridgenerator`
and `ocp-build-data-enforcer`, which was broken due to the
`openshift-bot`'s name changing and the function using the name instead
of the login, as well as changes to the test-infra's `UpdatePullRequest`
functions.

pkg/github: fix UpsertPR

---

pkg/validation/test.go

Add Azure Arc cluster profile validation. This was missing in https://github.com/openshift/ci-tools/pull/1611.

Add Azure Arc cluster profile validation

---

cmd/ci-secret-bootstrap/main.go
cmd/ci-secret-bootstrap/main_test.go

When `--force` is used and an immutable field needs to be changed, we allow recreating the secret

[DPTP-1836] ci-secret-bootstrap: allow recreating secrets on `--force` when an immutable field changes

---

pkg/api/types.go

Minor fix, quota slices have the `-quota-slice` suffix.

Fixes Azure Arc quota slice

---

cmd/publicize/server.go

/assign @droslean 
Ref https://issues.redhat.com/browse/DPTP-1882

Fix TestMergeAndPushToRemote to work when git has gpg signing enabled

---

cmd/ci-secret-generator/main.go

This helps debugging invalid commands
Ref https://issues.redhat.com/browse/DPTP-1859

Secret generator: Refuse empty and 'null' as command output

---

hack/test-go.sh

Reverts openshift/ci-tools#1575
It generates excessively large (~60MB) files:
https://gcsweb-ci.apps.ci.l2s4.p1.openshiftapps.com/gcs/origin-ci-test/pr-logs/pull/openshift_ci-tools/1640/pull-ci-openshift-ci-tools-master-unit/1354157004817436672/artifacts/test/artifacts/

Revert "test: write out test JSON"

---

pkg/api/config.go
pkg/config/load.go
pkg/prowgen/prowgen.go
pkg/prowgen/prowgen_test.go
pkg/prowgen/testdata/zz_fixture_TestGeneratePodSpecMultiStage_aws_cluster_profile.yaml
pkg/prowgen/testdata/zz_fixture_TestGeneratePodSpecMultiStage_aws_cpaas_cluster_profile.yaml
test/integration/ci-operator-config-mirror/output-only-super/super-priv/duper/super-priv-duper-master.yaml
test/integration/ci-operator-config-mirror/output-only-super/super-priv/trooper/super-priv-trooper-master.yaml
test/integration/ci-operator-config-mirror/output/super-priv/barry-white/super-priv-barry-white-master.yaml
test/integration/ci-operator-config-mirror/output/super-priv/barry-white/super-priv-barry-white-official.yaml
test/integration/ci-operator-config-mirror/output/super-priv/duper/super-priv-duper-master.yaml
test/integration/ci-operator-config-mirror/output/super-priv/trooper/super-priv-trooper-master.yaml
test/integration/config-brancher/expected/org/bump/org-bump-master.yaml
test/integration/config-brancher/expected/org/bump/org-bump-release-4.5.yaml
test/integration/config-brancher/expected/org/bump/org-bump-release-4.6.yaml
test/integration/config-brancher/expected/org/existing/org-existing-master.yaml
test/integration/config-brancher/expected/org/existing/org-existing-release-4.5.yaml
test/integration/config-brancher/expected/org/existing/org-existing-release-4.6.yaml
test/integration/config-brancher/expected/org/new/org-new-release-4.5.yaml
test/integration/config-brancher/expected/org/new/org-new-release-4.6.yaml
test/integration/pj-rehearse/expected.yaml
test/integration/release-job-migrator/expected/ci-operator/openshift/release/openshift-release-master__ocp-4.7.yaml
test/integration/repo-init/expected/ci-operator/config/org/other/org-other-nonstandard.yaml
test/integration/repo-init/expected/ci-operator/config/org/repo/org-repo-master.yaml
test/integration/repo-init/expected/ci-operator/config/org/third/org-third-nonstandard.yaml

There's one major difference between the current artifact gathering code
and using the Prow pod utilities: the former allows for users to
configure their artifact directory, whereas the latter expects to be
declarative itself and for the user to simply consume the directory as
an environment variable. As we work to make the latter approach default,
we first need to opt-out if we notice a user is setting their directory
to something non-standard.

prowgen: explicitly opt out of pod-utils with artifact dir

---

pkg/steps/pod.go

When the pod utils are being used to push artifacts up, we should not
bother grabbing them manually, especially since we do not know from
where to do so.
/assign @alvaroaleman @bbguimaraes

ci-operator: gather artifacts only when needed

---

cmd/ci-secret-generator/main.go
pkg/bitwarden/bitwarden.go
pkg/bitwarden/cli.go
pkg/bitwarden/cli_test.go
pkg/bitwarden/fake.go

Previously, when `ci-secret-generator` created a brand new BW record (entire record, not just an item), it did not set the record's organization and it set no collections. I understand that it was basically creating its personal secrets :)
Creating BW records is an internal detail of the BW client (it creates secrets when it is supposed to update an item or attachment on a record that does not exist  yet). I did not want to hardcode these values into the client nor did I want to refactor the client for the creation logic to not be an internal detail, so I decided to implement an `OnCreate` callback that the callsites can use to provide a defaulting logic. I'm not convinced it's the best solution of them all but it is reasoably simple, IMO.
I included a separate commits with some …

secret generator: set default org and collections on create

---

cmd/ci-operator-checkconfig/main.go

```
$ git rev-parse --short HEAD
734de06838
$ time ci-operator-checkconfig --config-dir config/ --registry step-registry/
real    0m1.396s
user    0m1.984s
sys     0m0.136s
$ sed -i '/steps/a\    env: {"INVALID": "invalid"}' config/openshift/ci-tools/openshift-ci-tools-master.yaml
$ ci-operator-checkconfig --config-dir config/ --registry step-registry/
ERRO[0000] Failed to execute callback                    error="Failed resolve MultiStageTestConfiguration: e2e: no step declares parameter \"INVALID\"" source-file=/home/bbguimaraes/src/release/ci-operator/config/openshift/ci-tools/openshift-ci-tools-master.yaml
error validating configuration files: Failed resolve MultiStageTestConfiguration: e2e: no step declares parameter "INVALID"
```

checkconfig: resolve configurations

---

cmd/publicize/main.go
cmd/publicize/server.go
cmd/publicize/server_test.go

Prow will, by default, run a censor for all data in the secret agent on
all log lines from logrus as well as all output bytes sent to GitHub.
There's no need to do any of this manually.
/assign @droslean @alvaroaleman

publicize: use default censoring

---

cmd/backport-verifier/server.go
cmd/backport-verifier/server_test.go

Apparently the SHA field in the GitCommit is no longer filled by GitHub
API responses, so we need to use the top-level SHA field. Cool.
Part of [DPTP-1842](https://issues.redhat.com/browse/DPTP-1842)

backport-verifier: use correct SHA field

---

pkg/prowgen/prowgen.go
test/integration/repo-init/expected/ci-operator/jobs/openshift/ci-tools/openshift-ci-tools-master-postsubmits.yaml
test/integration/repo-init/expected/ci-operator/jobs/openshift/ci-tools/openshift-ci-tools-master-presubmits.yaml

Using pod-utils for artifacts is now the default.
part of [DPTP-1819](https://issues.redhat.com/browse/DPTP-1819)
release counterpart:  https://github.com/openshift/release/pull/15378

ci-operator-prowgen: stop special-casing ci-tools

---

pkg/validation/test.go

Allow osd-ephemeral (https://github.com/openshift/ci-tools/pull/1615) to participate in step registry cluster_profiles.

Add osd-ephemeral to cluster_profile list

---

pkg/controller/test-images-distributor/test_images_distributor.go

This reverts commit 51ad77d68d8d52b6a9f6293b1fc3822dcb2296ad.
Follow up https://github.com/openshift/release/pull/15506

Revert "test-images-distributor: no distribution to api.ci"

---

pkg/steps/clusterinstall/template.go

Update it to the latest state which contains important fixes for
some upgrade environments and gather data on teardown.

steps/clusterinstall: Upgrade template is out of date

---

cmd/backport-verifier/server.go
cmd/backport-verifier/server_test.go

Turns out the GitHub Git API does not make a distinction between a
commit's title and the full message, so we need to selectively show only
the first line.
/assign @sttts

backport-verifier: only use the first line of a commit

---

pkg/steps/multi_stage.go

Allow step serviceaccount to create roles. This will enable a step to,
for example, expose a resource within its namespace to another
serviceaccount.
The first use case is to enable a registry step which allows cluster-bot
to monitor a secrets within a launched cluster namespace and
extract the kubeconfig when a cluster is available. This kubeconfig
is shared back to the slack user who requested the cluster.

Allow steps to create roles

---

cmd/applyconfig/applyconfig.go
cmd/applyconfig/applyconfig_test.go
cmd/ci-operator/main.go
pkg/api/nsttl/const.go

This is an unpolished shot to make `applyconfig` handle nonexistent namespaces in dry-runs better. Currently, server-side dry-runs (default on non-api.ci clusters) fails on PRs that add manifests for both the namespace and the resources in it. Server-side dry-run will fail for the resources, because they are applied into a namespace that does not exist on the cluster yet, but the actual non-dry run would succeed because the namespace manifest would be applied previously.
The solution space has several kinks:
- We could ask people to add namespaces in separate PRs, to be merged first (works but terrible UX)
- We could ignore these errors, but then we lose all validation for newly added manifests (can cause triage alerts)
- We could proactively create the missing namespaces and retry. This …

applyconfig: handle nonexisting namespaces in server-side dry-run

---

cmd/ci-secret-bootstrap/main.go

https://github.com/openshift/ci-tools/pull/1677 fixed logging for unused
secrets' individual fields and attachments, but added the "is allowed"
checks too late, after the empty "wrongly unused secrets" (=`comparable`
instances) were already created in the `unused` map, resulting in
spurious errors like these:
```
Unused bw item: 'AWS ci-longlivedcluster-bot' with , Unused bw item: 'build_farm_02_cluster' with ,
...
```
(see
https://deck-internal-ci.apps.ci.l2s4.p1.openshiftapps.com/view/gs/origin-ci-private/logs/periodic-ci-secret-bootstrap/1361269747353653248#1:build-log.txt%3A28
for occurrences)
The diff looks more complicated than the change actually is, the operatios are just reordered, nothing else.
/cc @droslean

ci-secret-bootstrap: process allowed unused records soon enough

---

Makefile
cmd/ci-operator/main.go
cmd/ci-operator/main_test.go
test/e2e/framework/framework.go

The removed flags are replaced with `--boskos-credentials-file`.
https://issues.redhat.com/browse/DPTP-1913
/hold
require https://github.com/openshift/release/pull/15825

ci-operator: remove boskos username and password-file flags

---

cmd/ci-operator-configresolver/main.go

Required so that logs are collected and stored in CloudWatch:
https://github.com/openshift/release/blob/master/clusters/app.ci/assets/logging.yaml
Before:
```
INFO[0000] Configs reloaded                              duration=444.131131ms
INFO[0000] Registry reloaded                             duration=48.632878ms
^CINFO[0001] Received signal.                              signal=interrupt
INFO[0001] Server shutting down...
INFO[0001] Interrupt received.
INFO[0001] Server shutting down...
INFO[0001] Server shutting down...
INFO[0001] Server exited.                                error="http: Server closed"
INFO[0001] Server shutting down...
INFO[0001] Server exited.                                error="http: Server closed"
INFO[0001] Server exited. …
```

configresolver: output log as JSON

---

cmd/blocking-issue-creator/main.go

Avoid this:
openshift-merge-robot changed the title ~Future Release Branches Frozen For Merging | branch:release-4.9 branch:release-4.8~ Future Release Branches Frozen For Merging | branch:release-4.8 branch:release-4.9 9 hours ago
openshift-merge-robot changed the title ~Future Release Branches Frozen For Merging | branch:release-4.8 branch:release-4.9~ Future Release Branches Frozen For Merging | branch:release-4.9 branch:release-4.8 8 hours ago 
https://github.com/openshift/cluster-capacity/issues/26#event-4345576341

blocking-issue-creator: sort branch tokens

---

pkg/api/types.go
pkg/steps/git_source.go
pkg/steps/project_image.go
pkg/validation/config.go
pkg/validation/config_test.go
pkg/webreg/zz_generated.ci_operator_reference.go

This is very useful for trivial dockerfiles like "copy one thing from a
different image" or "install one package"

Add DockerfileLiteral option to images

---

cmd/blocking-issue-creator/main.go

In the earlier fix I missed the second iteration over branches, used to
build the list in the body. Restructure the code so that the branches
are only iterated once.

blocking-issue-creator: sort branches everywhere

---

pkg/steps/multi_stage.go
pkg/steps/multi_stage_test.go
test/e2e/multi-stage/e2e_test.go
test/e2e/multi-stage/names.yaml

This is the same way we process user input references in other fields
like in dependencies, etc, not sure why we were not already doing this
processing for the `from` field.
fixes [DPTP-2002](https://issues.redhat.com/browse/DPTP-2002)

ci-operator: handle explicit imagestreams in step from

---

pkg/api/types.go
pkg/load/load.go
pkg/steps/multi_stage.go
pkg/webreg/zz_generated.ci_operator_reference.go
test/e2e/multi-stage/e2e_test.go
test/e2e/multi-stage/registry/timeout/timeout-ref.yaml

Today, timeouts and grace periods are in theory possible for test steps
in a multi-stage workflow. However, there are two major drawbacks with
the implementation:
- pod.spec.activeDeadlineSeconds constrains the "active time" of a Pod
on a node, which *includes* the time to mount volumes, pull images,
set up the sandbox, etc. The implication is therefore that a user's
setting for "timeout" may expire without the process they wish to
constrain ever even starting. As we allow a 15 minute image pull
timeout, no setting of active deadline shorter than that is
guaranteed to be applied sensibly.
- pod.spec.terminationGracePeriodSeconds constrains the full window
between the Pod being asked to delete (and getting SIGTERM) and the
time at which the kubelet sends SIGKILL. Test steps often execute …

ci-operator: improve user experience for timeouts

---

test/e2e/multi-stage/registry/timeout/timeout-ref.yaml

Follows up on https://github.com/openshift/ci-tools/pull/1715
Part of [DPTP-1668](https://issues.redhat.com/browse/DPTP-1668)

ci-operator: show that new timeout fields work

---

pkg/api/types.go
pkg/load/load.go
pkg/webreg/webreg.go
pkg/webreg/zz_generated.ci_operator_reference.go

These are now unused, all users were migrated.
Follows up on https://github.com/openshift/ci-tools/pull/1715
Part of [DPTP-1668](https://issues.redhat.com/browse/DPTP-1668)

ci-operator: remove old timing fields

---

pkg/steps/multi_stage.go
pkg/steps/testdata/zz_fixture_TestGeneratePodReadonly.yaml
pkg/steps/testdata/zz_fixture_TestGeneratePods.yaml

The functions that this bash did for us are now done in the
secret-wrapper utility, so there's no need for this mess.
/assign @bbguimaraes @alvaroaleman

ci-operator: stop munging bash

---

cmd/release-job-migrator/main.go
test/integration/release-job-migrator.sh
test/integration/release-job-migrator/expected2.txt
test/integration/release-job-migrator/expected2/_allow-list.yaml
test/integration/release-job-migrator/expected2/ci-operator/openshift/release/openshift-release-master__ocp-4.7.yaml
test/integration/release-job-migrator/expected2/ci-operator/openshift/release/openshift-release-master__okd-4.7.yaml
test/integration/release-job-migrator/expected2/ci-operator/openshift/release/openshift-release-master__origin-4.6.yaml
test/integration/release-job-migrator/expected2/ci-operator/openshift/release/openshift-release-master__origin-4.7.yaml
test/integration/release-job-migrator/expected2/config.yaml
test/integration/release-job-migrator/expected2/jobs/openshift-release-master-periodics.yaml
test/integration/release-job-migrator/expected2/jobs/openshift-release-release-4.4-periodics.yaml
test/integration/release-job-migrator/expected2/jobs/openshift-release-release-4.6-periodics.yaml
test/integration/release-job-migrator/expected2/jobs/openshift-release-release-4.7-periodics.yaml
test/integration/release-job-migrator/expected2/jobs/openshift-release-release-4.8-periodics.yaml
test/integration/release-job-migrator/expected2/jobs/openshift-release-release-4.9-periodics.yaml
test/integration/release-job-migrator/expected2/releases/release-ocp-4.7.json
test/integration/release-job-migrator/expected2/releases/release-origin-4.7.json

The PR adds a flag to allow a user to ignore jobs that use
`UNRESOLVED_CONFIG` and only migrate jobs specified in the config file.

release-job-migrated: add ignore-unresolved flag

---

cmd/prow-job-dispatcher/main.go
cmd/prow-job-dispatcher/main_test.go

```
FATA[0020] Failed to check if the config can determinize jobs  error="path ci-operator/jobs/kubevirt/kubevirt-ssp-operator/kubevirt-kubevirt-ssp-operator-master-presubmits.yaml matches more than 1 regex: [.*kubevirt-kubevirt-ssp-operator-master-presubmits.yaml$ .*kubevirt-ssp-operator-master-presubmits.yaml$]"
```
org kubevirt there are 2 repos: `ssp-operator` and `kubevirt-ssp-operator`
https://github.com/openshift/release/tree/master/ci-operator/jobs/kubevirt
Preaction of https://issues.redhat.com/browse/DPTP-1984

Add / to regex generated by dispatcher

---

cmd/testgrid-config-generator/main.go
test/integration/testgrid-config-generator/expected/redhat-openshift-informing.yaml

Release periodics are all informing, and testgrid visibility is a key part of TRT automation. Jobs that match the standard pattern should appear in testgrid unless there is a reason. We would never allow a release periodic in the standard set that do not benefit our ability to understand what is in the release. Whether a job is old or new is irrelevant, it's input to our decision processes.
This commit allows the allow list to simply become an override of which dashboard a small set of jobs should appear in. After this change the allow list should be a very, very small set.

cmd/testgrid-config-generator: All release periodics should appear in testgrid

---

cmd/prow-job-dispatcher/main.go

Otherwise, Finalize could error out if we do not provide token path.

dispatcher: Run PRCreationOptions.Finalize when needed

---

pkg/vaultclient/types.go
pkg/vaultclient/vaultclient.go
pkg/vaultclient/vaultclient_test.go

This change adds a vaultclient because the upstream one has a couple of
shortcomings:
* It mostly has a "logical" api that always returns a
map[string]interface{} instead of proper types and expects the user
do know vault api paths
* It swallows 404s, which only makes sense for list requests
* A coupple of things can only be found out via multiple API calls, add
simple helpers for those
Extracted from https://github.com/openshift/ci-tools/pull/1734
ref https://issues.redhat.com/browse/DPTP-1891

Add a vault client

---

pkg/testhelper/accessory.go
test/e2e/framework/framework.go
test/e2e/framework/test.go

Moves the Accessory from test/e2e/framework into pkg/testhelper, so it
can be used in unit tests.
Wanted for testing https://issues.redhat.com/browse/DPTP-1891

Allow using Accessory in normal unit tests

---

cmd/prow-job-dispatcher/main.go
cmd/prow-job-dispatcher/main_test.go
cmd/sanitize-prow-jobs/main.go
cmd/sanitize-prow-jobs/main_test.go
pkg/dispatcher/config.go
pkg/dispatcher/config_test.go
pkg/dispatcher/prometheus_test.go
pkg/dispatcher/testdata/TestLoadConfig/good_config.yaml
pkg/dispatcher/testdata/TestLoadConfig/good_config_with_build_farm_with_jobs.yaml

https://issues.redhat.com/browse/DPTP-1984
We have 3 places to use the config:
- `sanitize`: read the config as input (run in a presubmit)
- `dispatcher`: read the config as input, query promotheus and then output the config (run in a periodic)
- us: change the config to move jobs
We ensure
- no job name will occur more than once in the config.
- no path of the job yaml matches more than one regex in the config

Check sanitize's config if it can dispatch jobs determinically

---

Makefile

Some integration test or something clobbers the data in
`/tmp/.kubeconfig` which is irritating.

make: update location of kubeconfig

---

cmd/pj-rehearse/main.go
cmd/pj-rehearse/main_test.go
pkg/config/jobs.go
pkg/config/jobs_test.go
pkg/diffs/diffs.go
pkg/diffs/diffs_test.go
pkg/rehearse/jobs.go
test/integration/pj-rehearse/expected.yaml

Currently, the design of the tool is really fragile when picking all the presubmits to rehearse. In the effort of avoiding bad refactoring, this PR introduces a new label `pj-rehearse.openshift.io/source-type` that is injected in all rehearsals, and based on its value the tool will sophisticated choose a subset of the jobs to be rehearsed when the jobs are more than the rehearsal limit. 
Pros: We can use this label to gather Prometheus metrics from the rehearsals and create grafana dashboard to have a clear picture of which changes are triggering rehearsals. 

[DPTP-1969] Implement a more sophisticated way to chooses a subset of jobs when there is a rehearsal limit

---

cmd/blocking-issue-creator/main.go
cmd/blocking-issue-creator/main_test.go
go.mod
vendor/modules.txt

The old implementation creates flakes like [job](https://prow.ci.openshift.org/view/gs/origin-ci-test/logs/periodic-openshift-release-merge-blockers/1364198484130926592)
This PR refactors the `blocking-issue-creator` tool to use the Prow's GitHub client
follow-up https://github.com/openshift/release/pull/16280

[DPTP-2014] Refactor blocking-issue-creator to use the prow github client

---

pkg/controller/test-images-distributor/test_images_distributor.go

This reverts commit 77c9006a9707a091617db652b859a93c587d8db4.
https://issues.redhat.com/browse/DPTP-1981

Revert "Revert "test-images-distributor: no distribution to api.ci""

---

cmd/registry-replacer/main.go
cmd/registry-replacer/main_test.go
cmd/registry-replacer/testdata/zz_fixture_TestReplacer_OCP_builder_pruning_happens.yaml

Full context: https://coreos.slack.com/archives/CBN38N3MW/p1614952333017200

Ignore ocp/builder constraint in unpromoted configs

---

Makefile
cmd/vault-secret-collection-manager/index.template.html
cmd/vault-secret-collection-manager/index.ts
cmd/vault-secret-collection-manager/style.css
cmd/vault-secret-collection-manager/tsconfig.json

This change adds the frontend part to allow secret collection deletion, ref: https://issues.redhat.com/browse/DPTP-1891
Also includes a couple of refactoring:
* Rename the modal, its main content div and the error div to clarify that it's not only used to create a secret collection but
* Move hiding of the modal into a func that will hide the modal, the error and content sub-div and all children of the latter, so that funcs that put something into there do not first need to do that (and know about everything else that could put content in there)
* Fix the http requests to not always create a modal error when there is any body and to use exception handling for both "request fails entirely" and "request didn't get a 2XX status", rather than only for the first
* Fix …

Vault secret manager: Add frontend for deletions

---

pkg/steps/artifacts.go
pkg/steps/artifacts_test.go
pkg/steps/multi_stage.go
pkg/steps/multi_stage_test.go
pkg/steps/pod.go
pkg/steps/testdata/zz_fixture_TestAddPodUtils.yaml
pkg/steps/testdata/zz_fixture_TestGeneratePods.yaml

The Prow pod utilities can now censor secret data before uploading
anything to the cloud, both in plain-text files and in archives that the
user creates during a test run. We know that the set of sensitive data
available to test Pods for a job is limited to the set of Secrets in the
Namespace that ci-operator created for the job, so by mounting them all
into the test Pods we can effectively guard against all secret leaks in
the future.
---
/assign @petr-muller @alvaroaleman @bbguimaraes

ci-operator: censor all secret data in sidecar

---

pkg/defaults/defaults.go
pkg/defaults/defaults_test.go
pkg/steps/release/promote.go

Nobody uses this path any longer, we do not need to support it.

ci-operator: remove support for legacy promotion

---

pkg/steps/release/promote.go
pkg/steps/release/promote_test.go

There's no reason that the logic for choosing which images are promoted
and how they are mapped to the outputs should vary between different
parts of our codebase.
Depends on #1773 
Part of [DPTP-2051](https://issues.redhat.com/browse/DPTP-2051)
/assign @alvaroaleman @hongkailiu

ci-operator: unite the logic for choosing images to promote

---

pkg/steps/release/promote.go
pkg/steps/release/promote_test.go

This reverts commit 9ba1c998b7b6bc924f3f26fe56476c0a8e5649b4, reversing
changes made to 190702e34c11619b0d763a35490e6dfd61ab3c2d.
`ci-operator-checkconfig` started rejecting `openshift/release@master`
after the merge:
https://prow.ci.openshift.org/view/gs/origin-ci-test/logs/branch-ci-openshift-ci-tools-master-images/1370330368489558016
https://prow.ci.openshift.org/job-history/gs/origin-ci-test/pr-logs/directory/pull-ci-openshift-release-master-ci-operator-config
```
$ git checkout -q 9ba1c998b^
$ go run ./cmd/ci-operator-checkconfig --config-dir $release/ci-operator/config --registry $release/ci-operator/step-registry
$ git checkout -q 9ba1c998b
$ go run ./cmd/ci-operator-checkconfig --config-dir $release/ci-operator/config --registry $release/ci-operator/step-registry
non-unique image …
```

Revert "Merge pull request #1774 from stevekuznetsov/skuznets/unify-promotion-lists"

---

pkg/steps/run.go

@openshift/openshift-team-developer-productivity-test-platform @petr-muller 
`out.err` is a [results.Error](https://github.com/openshift/ci-tools/blob/master/pkg/results/error.go#L14) wrapped in an original golang error while [context.Canceled](https://go.googlesource.com/go/+/go1.16/src/context/context.go#157) is not. This makes the comparison fail. since the `out.err` contains also other elements. 
The current code was ignoring passing that check when the context was canceled. The change in this PR, just makes sure that we compare only the error message.

DPTP-2006 check in the step execution error if the context is cancelled properly 

---

cmd/ci-operator/main_test.go
pkg/api/types.go
pkg/api/types_test.go
pkg/defaults/defaults.go
pkg/defaults/defaults_test.go
pkg/prowgen/prowgen.go
pkg/steps/index_generator.go
pkg/steps/index_generator_test.go
pkg/steps/project_image.go
pkg/validation/config.go
pkg/validation/config_test.go
pkg/validation/test.go
pkg/validation/test_test.go
pkg/webreg/zz_generated.ci_operator_reference.go
test/e2e/simple/e2e_test.go
test/e2e/simple/optional-operators.yaml
test/integration/ci-operator-prowgen/input/config/super/duper/super-duper-master.yaml
test/integration/ci-operator-prowgen/output/jobs/super/duper/super-duper-master-presubmits.yaml
test/manifests/bundle.Dockerfile
test/manifests/metadata/annotations.yaml

This PR adds support for testing optional operator upgrades in openshift
CI.
To allow optional operator upgrade tests, 3 fields have been added to
the bundle definition field (`operator.bundles`). They are:
- `as`: the name of the bundle image. If this is set, the built bundle
will be tagged as `pipeline:as` and a corresponding index will be
built called `pipeline:ci-index-as`. This will also be useful for
future multistage tests that will pass the bundle pullspec directly
to the `operator-sdk` command
- `base_index`: define an existing index to add the new bundle to for
the test instead of creating a new index
- `update_graph`: define the mode to add the built bundle to the index.
Can be `semver`, `semver-skippatch`, or `replaces`
Any tests that had to be changed and did not follow our …

ci-operator: add support for operator upgrade tests

---

pkg/defaults/defaults.go
pkg/steps/release/promote.go
pkg/steps/release/promote_test.go

Lots of valuable work is done when binaries are built from the source
code in a test. We can promote the resulting image to a build cache
repository and use it as the `build_root` for subsequent jobs (if the
underlying `build_root` that we originate from has not changed) and
thereby save enormous amounts of time in both incremental cloning and
incremental compilation.
Depends on #1774 
Part of [DPTP-2051](https://issues.redhat.com/browse/DPTP-2051)

ci-operator: always promote the build cache

---

pkg/controller/test-images-distributor/test_images_distributor.go
pkg/controller/test-images-distributor/test_images_distributor_test.go

The goal is to pull through `app.ci` instead of `api.ci`.
Reimport the images if the image on build farm is current pointing to `api.ci` and the new target is locally stored in `app.ci`.

image-distributor: replace api.ci images with app.ci ones

---

cmd/ci-operator/main_test.go
pkg/defaults/defaults.go
pkg/defaults/defaults_test.go
pkg/steps/artifacts.go
pkg/steps/artifacts_test.go
pkg/steps/bundle_source_test.go
pkg/steps/index_generator_test.go
pkg/steps/input_image_tag_test.go
pkg/steps/loggingclient/loggingclient.go
pkg/steps/multi_stage_test.go
pkg/steps/output_image_tag_test.go
pkg/steps/pod_test.go
pkg/util/watchingclient/client_cache.go
pkg/util/watchingclient/fake/fake.go
pkg/util/watchingclient/watchingclient.go
vendor/k8s.io/client-go/tools/watch/informerwatcher.go
vendor/k8s.io/client-go/tools/watch/retrywatcher.go
vendor/k8s.io/client-go/tools/watch/until.go
vendor/modules.txt

Essentially https://github.com/openshift/ci-tools/pull/1784 + a wrapper around the c-r client so it can watch.
Obsoletes and closes https://github.com/openshift/ci-tools/pull/1784
Obsoletes and closes https://github.com/openshift/ci-tools/pull/1785

Add watching ctrlruntimeclient wrapper and use it to wait for pods

---

cmd/ci-operator/main_test.go
pkg/api/types.go
pkg/api/types_test.go
pkg/defaults/defaults.go
pkg/defaults/defaults_test.go
pkg/prowgen/prowgen.go
pkg/steps/index_generator.go
pkg/steps/index_generator_test.go
pkg/steps/project_image.go
pkg/validation/config.go
pkg/validation/config_test.go
pkg/validation/test.go
pkg/validation/test_test.go
pkg/webreg/zz_generated.ci_operator_reference.go
test/e2e/simple/e2e_test.go
test/e2e/simple/optional-operators.yaml
test/integration/ci-operator-prowgen/input/config/super/duper/super-duper-master.yaml
test/integration/ci-operator-prowgen/output/jobs/super/duper/super-duper-master-presubmits.yaml
test/manifests/bundle.Dockerfile
test/manifests/metadata/annotations.yaml

Reverts openshift/ci-tools#1748
Broke existing operator tests with:
```
2021/03/15 16:17:50 step <*steps.leaseStep> is missing dependencies: <&api.internalImageStreamTagLink{name:"pipeline", tag:"", unsatisfiableError:""}>
```
such as https://prow.ci.openshift.org/view/gs/origin-ci-test/pr-logs/pull/kubevirt_hyperconverged-cluster-operator/1180/pull-ci-kubevirt-hyperconverged-cluster-operator-master-okd-hco-e2e-image-index-aws/1371495842573193216#1:build-log.txt%3A11
Pinpointed using job history https://prow.ci.openshift.org/job-history/gs/origin-ci-test/pr-logs/directory/pull-ci-kubevirt-hyperconverged-cluster-operator-master-okd-hco-e2e-image-index-aws
Reported in https://coreos.slack.com/archives/CBN38N3MW/p1615883791001400
FYI @AlexNPavel

Revert "ci-operator: add support for operator upgrade tests"

---

cmd/ci-secret-bootstrap/main.go
cmd/ci-secret-bootstrap/main_test.go
cmd/ci-secret-bootstrap/vault.go
pkg/vaultclient/vaultclient.go

This is very straightforward except for the getUnusedBWItems check. That
check verifies that all of fields, attachments and password are used, if
present. As Vault just has a k-v map and doesn't know to what bitwarden
type a field maps we do the following:
* We store all keys vault has
* For all of field/attachment/password in the config file, we ask the
secret provider if it has them
* This will make the vault provider mark those fields as in-use
* At the end, we add another check, "superfluous fields". The Vault
implementation will use that to report all fields it didn't get asked
about
This allows us to re-use all tests and thus be confident that it works
for Vault as well. The error message however is slightly different for
Vault.
It is recommended to review this PR with whitespace …

Add vault support to secret bootstrapper

---

cmd/testgrid-config-generator/main.go
test/integration/testgrid-config-generator/expected/redhat-openshift-ocp-release-4.1-blocking.yaml
test/integration/testgrid-config-generator/expected/redhat-openshift-ocp-release-4.1-informing.yaml
test/integration/testgrid-config-generator/expected/redhat-openshift-ocp-release-4.2-blocking.yaml
test/integration/testgrid-config-generator/expected/redhat-openshift-ocp-release-4.2-informing.yaml

The move to allow list was suppressing defaulting that we still wish
to do (we try to get 100 results on any testgrid page, and 24h interval
tests were only showing 7 which impacts our ability to track trends).

testgrid-config-generator: Store more historical results

---

cmd/ci-operator-checkconfig/main.go
cmd/registry-replacer/main.go
pkg/api/types.go
pkg/controller/promotionreconciler/reconciler.go
pkg/defaults/defaults.go
pkg/steps/input_image_tag.go
pkg/steps/output_image_tag.go
pkg/steps/release/promote.go
pkg/steps/release/promote_test.go
pkg/webreg/webreg.go

This re-introduces the previous PRs and adds fixes + unit tests for all the cases that failed in the past. `ci-operator-checkconfig` is now happy.

Reintroduce Build Cache

---

cmd/ci-operator-checkconfig/main.go
pkg/api/types.go
pkg/steps/release/promote.go
pkg/steps/release/promote_test.go
pkg/webreg/zz_generated.ci_operator_reference.go

This is a useful feature for the ci-chat-bot when working with multiple
PRs. It is not, however, actually useful to normal test flows, so we
document it as such and validate that checked-in configuration does not
set it.
---
Depends on #1775 

ci-operator: allow overriding registry for promotions

---

pkg/api/types.go
pkg/steps/release/promote.go
pkg/steps/release/promote_test.go

In general it is true that if a `ci-operator` instance is running with
promotion, it is running after a merge happened and in an isntance where
publishing the build cache is valuable. The CI chat bot breaks this
assumption and needs an opt-out.

ci-operator: allow opting out of build cache promotion

---

pkg/steps/bundle_source.go
pkg/steps/git_source.go
pkg/steps/index_generator.go
pkg/steps/pipeline_image_cache.go
pkg/steps/project_image.go
pkg/steps/rpm_injection.go
pkg/steps/source.go
pkg/steps/source_test.go
pkg/steps/testdata/zz_fixture_TestCreateBuild_basic_options_for_a_presubmit.yaml
pkg/steps/testdata/zz_fixture_TestCreateBuild_with_OAuth_token.yaml
pkg/steps/testdata/zz_fixture_TestCreateBuild_with_a_path_alias.yaml
pkg/steps/testdata/zz_fixture_TestCreateBuild_with_a_pull_secret.yaml
pkg/steps/testdata/zz_fixture_TestCreateBuild_with_extra_refs.yaml
pkg/steps/testdata/zz_fixture_TestCreateBuild_with_extra_refs_setting_workdir_and_path_alias.yaml
pkg/steps/testdata/zz_fixture_TestCreateBuild_with_ssh_key.yaml
test/e2e/simple/e2e_test.go

In the future, `ci-operator` will optionally re-use a `bin` image to get
access to the clone and build cache that is stored there after the image
is built. In order to be able to tell that a cached image is
out-of-date, we need to label the version of the root it's built on top
of and check that against the version of the root we resolved at
runtime.
part of [DPTP-2051](https://issues.redhat.com/browse/DPTP-2051)

ci-operator: label digest of image we built on top of

---

cmd/entrypoint-wrapper/main.go
test/entrypoint-wrapper-integration.sh

Instead of modifying the script that a multistage step runs in order to
update the `PATH` to point to the copied CLI, `entrypoint-wrapper`
checks for the `CLI_DIR` env var and, if it exists, appends that to the
`PATH` for the wrapped entrypoint.

multi_stage: update PATH for cli using entrypoint-wrapper

---

pkg/steps/multi_stage.go

Now that `entrypoint-wrapper` sets the updated `PATH` including the cli,
stop setting it in the multistage step.

multi_stage: stop setting path in multi_stage.go

---

pkg/api/types.go

We need this field in the struct so that we may use it in rehearsals.

ci-operator: allow loading cache field

---

pkg/defaults/defaults.go
pkg/defaults/defaults_test.go
pkg/validation/config.go

ci-operator: validate that build_root ISTags are fully formed
---
ci-operator: clean up build root step generation
There's no place where any of the weird "test-base" stuff is used and
the previous commit validates as much. I'm not sure what it was for and
it's not documented anywhere. I removed that handler and fixed the git
base / project build options to pass through the full struct, instead of
cherry-picking some options and silently dropping the rest.
---
/assign @alvaroaleman @petr-muller 
I've checked that the `ci-operator-checkconfig` update has no impact on `openshift/release`. I've spoken with Clayton about this implicit test root mechanism, since he added it, but he has no …

Clean up root image tech-debt

---

pkg/api/types.go
pkg/steps/multi_stage.go
pkg/steps/multi_stage_test.go
pkg/steps/testdata/zz_fixture_TestGeneratePods.yaml
pkg/webreg/zz_generated.ci_operator_reference.go
test/e2e/multi-stage/config.yaml
test/e2e/multi-stage/e2e_test.go

Instead of running commands directly with `bash` when running multistage
tests, `ci-operator` should instead execute the script directly so that
the shebang specifying what shell to use is followed (it is ignored when
run directly by the shell) and to remove the multistage test steps'
dependance on `bash`, which does not exist in certain images, usually
alpine based.
This PR now runs commands by creating a configmap and mounting it to a
known location in the pod. Then, the script is executed by doing
`/bin/sh -c /path/to/script.sh`. At a bare minimum, all images should
have a `/bin/sh`, and in order to continue supporting injecting the cli
binary into images, the ci-operator needs to execute commands via
`/bin/sh` so the `$PATH` env var can be updated to include the path to
the cli before …

[DPTP-2057] multi_stage: write commands.sh to configmap

---

cmd/ci-operator/main.go
pkg/api/helper/imageextraction.go
pkg/api/helper/imageextraction_test.go
pkg/api/metadata.go
pkg/defaults/defaults.go
pkg/defaults/defaults_test.go
pkg/steps/release/promote.go
pkg/steps/release/promote_test.go
pkg/steps/source.go

ci-operator: validate that build_root ISTags are fully formed
---
ci-operator: clean up build root step generation
There's no place where any of the weird "test-base" stuff is used and
the previous commit validates as much. I'm not sure what it was for and
it's not documented anywhere. I removed that handler and fixed the git
base / project build options to pass through the full struct, instead of
cherry-picking some options and silently dropping the rest.
---
ci-operator: optionally use build cache for the root
When the user asks us to, we can determine if the build cache we have
published for the repo is up-to-date. If it is, we should use it for our
build root instead of the build …

ci-operator: optionally use build cache for the root

---

pkg/steps/release/promote.go
pkg/steps/release/testdata/zz_fixture_TestGetPromotionPod_basic_case.yaml

We had issues in promotion and use [retries](https://github.com/openshift/ci-tools/pull/1555/commits/fbd752b0ea26533c455afaf88fb456ad36c22118) in our bash to work it around. The [potential fix](https://github.com/openshift/oc/pull/706) has been merged  for some time. @ricardomaraschini asked me if it helped. I am going to revert the retries (which hides the underlying problem) and provide him our answer. I tried to reproduce it locally at the time. 4.6 reproduced. Not 4.7, master at the time, even before the fix was merged. We are using 4.8:cli in promotion pod. I feel it is relatively safe.

Stop retries in promotion

---

pkg/steps/release/promote.go
pkg/steps/release/testdata/zz_fixture_TestGetPromotionPod_basic_case.yaml

This reverts commit 327f4487b0038819f3314a33f131fea5736e7678.
It broke our promotion.
https://coreos.slack.com/archives/CBN38N3MW/p1616617111239800

Revert "Stop retries in promotion"

---

pkg/steps/artifacts.go

We need these to debug build phases.

ci-operator: show timestamps on build log lines

---

pkg/steps/source.go
pkg/steps/testdata/zz_fixture_TestCreateBuild_basic_options_for_a_presubmit.yaml
pkg/steps/testdata/zz_fixture_TestCreateBuild_with_OAuth_token.yaml
pkg/steps/testdata/zz_fixture_TestCreateBuild_with_a_path_alias.yaml
pkg/steps/testdata/zz_fixture_TestCreateBuild_with_a_pull_secret.yaml
pkg/steps/testdata/zz_fixture_TestCreateBuild_with_extra_refs.yaml
pkg/steps/testdata/zz_fixture_TestCreateBuild_with_extra_refs_setting_workdir_and_path_alias.yaml
pkg/steps/testdata/zz_fixture_TestCreateBuild_with_ssh_key.yaml

We want to investigate why a build takes so long. Today, the default log
level does not give us enough verbosity to tell.

ci-operator: set higher build loglevel

---

test/e2e/simple/e2e_test.go
test/e2e/simple/optional-operators.yaml

This PR adds a content test for the operator indices built by the
optional-operators e2e test. The way it is done is by running the
serving the opm registry in the index image and then using `grpcurl` to
identify whether certain CSVs exist. For the `ci-index-named-bundle`
image which has a `base_index`, we verify that both existing bundles and
the new bundle exist in the index. For the unnamed bundle, we verify
that the new bundle is in the index and a bundle that exists in the
`base_index` used for the other index image does not.
Due to a permission error that occurs during the test that doesn't occur
when the index image is actually run in the cluster, the `index.db` file
has to be moved to the `$HOME` directory, otherwise a permissions error
occurs when the database is being read.

test: add index content test for optional operator e2e

---

pkg/steps/multi_stage.go

Noted this condition with the current implementation:
```
$ oc get pods -n ci-op-bn8cmi7b
NAME                                READY   STATUS        RESTARTS   AGE
launch-openshift-cluster-bot-rbac   0/2     Completed     0          7m5s
launch-osd-create-create            2/2     Terminating   0          6m55s
launch-osd-delete-delete            0/2     Completed     0          60s
```

Wait for pod deletion during cleanup

---

cmd/ci-operator/main.go
pkg/defaults/defaults.go
pkg/steps/secretrecordingclient/client.go
vendor/github.com/sirupsen/logrus/hooks/writer/README.md
vendor/github.com/sirupsen/logrus/hooks/writer/writer.go
vendor/modules.txt

Default censoring that is provided by `sidecar` has one draw-back: the
set of secrets that must be censored is loaded at start-up and must be
known ahead of time in order to be provided to the process. Inside of
the `ci-operator`, we routinely touch secret values via the Kubernetes
API at runtime. This means that the total set of secret values we may
possibly leak grows over time. Due to this, we cannot solely rely on the
censoring implemenation that runs out-of-process.
Also, today the `ci-operator` uses the `log` library for logging, in
contrast to pretty must every other part of the codebase and larger
ecosystem (Prow, Boskos, etc...). Censoring for the `logrus` library is
implemented, tried, and tested in production for a long time. We are
better off by migrating to `logrus` over time …

ci-operator: initialize a more intelligent logger

---

cmd/vault-subpath-proxy/kv_key_validator.go
cmd/vault-subpath-proxy/main.go
cmd/vault-subpath-proxy/main_test.go
pkg/api/vault/vault.go

We need to make sure that the vault secret keys are valid kube secret keys or the marker key for the target namespace/name. In the latter case, the value must be a valid namespace/name, respectively.
Ref https://issues.redhat.com/browse/DPTP-2070

Vault subpath proxy: Verify keys to be valid kube secret keys

---

cmd/entrypoint-wrapper/main.go
test/entrypoint-wrapper-integration.sh

We do not read/update/write the shared directory secret in the
entrypoint wrapper, we just create it from the values on disk since that
is technically authoritative for the data. It causes us to lose the
labels, though, so we need to set the censoring skip label here as well
or we will end up censoring random data that's useful to users.

entrypoint-wrapper: label secret to be ignored in censor

---

pkg/results/report.go
pkg/steps/source.go
pkg/steps/testdata/zz_fixture_TestCreateBuild_basic_options_for_a_presubmit.yaml
pkg/steps/testdata/zz_fixture_TestCreateBuild_with_OAuth_token.yaml
pkg/steps/testdata/zz_fixture_TestCreateBuild_with_a_path_alias.yaml
pkg/steps/testdata/zz_fixture_TestCreateBuild_with_a_pull_secret.yaml
pkg/steps/testdata/zz_fixture_TestCreateBuild_with_extra_refs.yaml
pkg/steps/testdata/zz_fixture_TestCreateBuild_with_extra_refs_setting_workdir_and_path_alias.yaml
pkg/steps/testdata/zz_fixture_TestCreateBuild_with_ssh_key.yaml

ci-operator: hide reporting log line
This isn't something users ever need to see.
---
Revert "ci-operator: set higher build loglevel"
This reverts commit 85a8cf5ef823bfbe122f8bd7593280acd4965450.
---
I'm reverting the build log level as we 1) have loads of logs to look at in GCS now and 2) it is SO VERBOSE

Minor Output Tweaks

---

test/integration/pj-rehearse/candidate/ci-operator/jobs/super/duper/super-duper-ciop-cfg-change-presubmits.yaml
test/integration/pj-rehearse/candidate/ci-operator/jobs/super/duper/super-duper-master-presubmits.yaml
test/integration/pj-rehearse/candidate/ci-operator/jobs/super/trooper/super-trooper-master-presubmits.yaml
test/integration/pj-rehearse/expected.yaml
test/integration/pj-rehearse/master/ci-operator/jobs/super/duper/super-duper-ciop-cfg-change-presubmits.yaml
test/integration/pj-rehearse/master/ci-operator/jobs/super/duper/super-duper-cluster-profile-presubmits.yaml
test/integration/pj-rehearse/master/ci-operator/jobs/super/duper/super-duper-master-presubmits.yaml
test/integration/pj-rehearse/master/ci-operator/jobs/super/duper/super-duper-periodics.yaml
test/integration/pj-rehearse/master/ci-operator/jobs/super/trooper/super-trooper-master-presubmits.yaml

Make adding new tests easier by refreshing generated jobs with current
prowgen. The change is expected to only change the definitions of
rehearsed jobs, it does not change the selected set or rehearsal
reasons.
```console
$ ci-operator-prowgen --from-dir test/integration/pj-rehearse/master/ci-operator/config/ --to-dir test/integration/pj-rehearse/master/ci-operator/jobs/
$ ci-operator-prowgen --from-dir test/integration/pj-rehearse/candidate/ci-operator/config/ --to-dir test/integration/pj-rehearse/candidate/ci-operator/jobs/
$ make integration SUITE=integration/pj-rehearse UPDATE=true
```
Part of [DPTP-2108](https://issues.redhat.com/browse/DPTP-2108)

rehearse: refresh integration tests

---

cmd/pj-rehearse/main.go
cmd/pj-rehearse/main_test.go

Previously, pj-rehearse created testimagestreamtagimports on app.ci and the controller choked on them:
```json
{
"cluster":"app.ci",
"component":"dptp-controller-manager",
"controller":"test_images_distributor",
"error":"no client for cluster app.ci available",
"file":"/go/src/github.com/openshift/ci-tools/pkg/controller/test-images-distributor/test_images_distributor.go:177",
"func":"github.com/openshift/ci-tools/pkg/controller/test-images-distributor.(*reconciler).Reconcile",
"kubernetes":{
"container_image":"image-registry.openshift-image-registry.svc:5000/ci/dptp-controller-manager@sha256:87c24b0df1bbf6c62631c38f4fd87dc3962a02c87956b0cc62d3627c95b59c37",
"container_name":"dptp-controller-manager",
"pod_ip":"10.129.3.74",
"pod_ips":[
"10.129.3.74"
],
"pod_labels":{ …
```

rehearse: do not create imports on app.ci

---

cmd/ci-secret-bootstrap/main.go
cmd/ci-secret-bootstrap/main_test.go
pkg/api/secretbootstrap/secretboostrap.go
pkg/api/vault/vault.go
pkg/bitwarden/fake.go
pkg/secrets/bitwarden.go
pkg/secrets/client.go
pkg/secrets/vault.go

This change adds support to the secret bootstrapper to sync user secrets
from Vault. It will use specific keys in the Vault secret to figure out
the namespace/name it should sync to. The clusters need to be explicitly
configured. It is allowed to have secrets that contain both data from
the secret bootstrap config (owned by dptp) and user secrets but dptp
data takes precedence and we will error if an attempt to overwrite it is
made.
Ref https://issues.redhat.com/browse/DPTP-2070

CI-Secret-Bootstrap: Sync user secrets from Vault

---

cmd/generate-registry-metadata/main_test.go
cmd/pj-rehearse/main.go
pkg/load/load_test.go
test/integration/pj-rehearse/candidate/ci-operator/config/super/trooper/super-trooper-master.yaml
test/integration/pj-rehearse/candidate/ci-operator/jobs/super/trooper/super-trooper-master-periodics.yaml
test/integration/pj-rehearse/expected.yaml
test/integration/pj-rehearse/master/ci-operator/config/super/trooper/super-trooper-master.yaml
test/integration/pj-rehearse/master/ci-operator/jobs/super/trooper/super-trooper-master-periodics.yaml
test/multistage-registry/registry/ipi-changed/OWNERS
test/multistage-registry/registry/ipi-changed/ipi-changed-workflow.metadata.json
test/multistage-registry/registry/ipi-changed/ipi-changed-workflow.yaml
test/multistage-registry/registry2/ipi-changed/OWNERS
test/multistage-registry/registry2/ipi-changed/ipi-changed-workflow.metadata.json
test/multistage-registry/registry2/ipi-changed/ipi-changed-workflow.yaml

/hold
Needs https://github.com/openshift/ci-tools/pull/1846
Deduplication happens on `main()`-level so adding a new integration test (which fails with the original version), for which I needed to add some test registry content to be changed.
Fixes: [DPTP-2108](https://issues.redhat.com/browse/DPTP-2108)

rehearse: properly deduplicate rehearsed periodics

---

cmd/vault-subpath-proxy/kv_key_validator.go
cmd/vault-subpath-proxy/main_test.go

The current validation is way too strict and not what kube itself does.

Vault subpath proxy: Fix secret key validation

---

cmd/ci-operator/main.go
pkg/api/job_spec.go
pkg/steps/multi_stage.go
pkg/steps/multi_stage_test.go
pkg/steps/pod.go
pkg/steps/pod_test.go
pkg/steps/rpm_server.go
pkg/steps/source.go
pkg/steps/source_test.go
pkg/steps/testdata/zz_fixture_TestCreateBuild_basic_options_for_a_presubmit.yaml
pkg/steps/testdata/zz_fixture_TestCreateBuild_with_OAuth_token.yaml
pkg/steps/testdata/zz_fixture_TestCreateBuild_with_a_path_alias.yaml
pkg/steps/testdata/zz_fixture_TestCreateBuild_with_a_pull_secret.yaml
pkg/steps/testdata/zz_fixture_TestCreateBuild_with_extra_refs.yaml
pkg/steps/testdata/zz_fixture_TestCreateBuild_with_extra_refs_setting_workdir_and_path_alias.yaml
pkg/steps/testdata/zz_fixture_TestCreateBuild_with_ssh_key.yaml
pkg/steps/testdata/zz_fixture_TestGeneratePods.yaml
pkg/steps/testdata/zz_fixture_TestPodStepExecution_Pod_run_by_PodStep_fails_so_PodStep_terminates_and_returns_an_error.yaml
pkg/steps/testdata/zz_fixture_TestPodStepExecution_Pod_run_by_PodStep_succeeds_so_PodStep_terminates_and_returns_no_error.yaml

The intent of adding labels to the Pods we create was always two-fold:
first, help administrators identify Pods as they relate to jobs and
steps. Second, allow for the labels to end up in Prometheus to help us
track metrics across job runs. Unfortunately, the previous label set
fell short in the second case:
- we added the full job name as a label, which was trimmed to fit in
most cases and in some cases the trimming left only the org/repo/etc
parts, making it not actually useful as an identifier
- we did not label the target that ci-operator executed, just fields
like the full job name which might include it as a suffix
- we did not label the multi-stage step name, now allowing us to
discern individual usage metrics
- we labeled the build and Prow job IDs, which are unique and not …

ci-operator: update the label set we use on Pods

---

cmd/autobumper/main.go

As it has references like this one: https://github.com/openshift/release/blob/79ab2207d6e19264092f661c3f03409fd2e1ff9d/Makefile#L58

Bumper: Bump Makefile as well

---

pkg/steps/secretrecordingclient/client.go

This was somehow lost from the previous commits which handled this case.
There is no world in which the Namespace in which we work is secret, as
we create it for the test and it's entirely a derivative value from our
inputs. This is a silly hack but there's no real better way of ignoring
it.

ci-operator: don't record SA namespaces for censoring

---

cmd/ci-operator/main.go
cmd/ci-operator/main_test.go
pkg/api/env.go
pkg/steps/secretrecordingclient/client.go
test/e2e/multi-stage/config.yaml
test/e2e/multi-stage/e2e_test.go

ci-operator: add a utility to write censored artifacts
We want to make sure that we censor anything we're writing to artifacts
from this process as we often interact with secrets during runtime for
the first time, so we can't be certain that out-of-process censoring
will do anything sensible. A helper makes it easier for an engineer to
do the right thing.
---
Revert "CI-Operator: Stop writing step graph out"
This reverts commit 4b978f02018eb00ed5dccb1850a8f295d57bd4d9.
---
ci-operator: use the artifacts helper to write the graph
---
Tested locally, produces output like this:
```
$ cat /tmp/artifacts/TestMultiStage_step_with_credentials/ci-operator-step-graph.json …
```

Revert "CI-Operator: Stop writing step graph out"

---

cmd/ci-operator/main.go
pkg/api/graph.go
pkg/defaults/defaults.go
pkg/steps/cluster_claim.go
pkg/steps/multi_stage.go
pkg/steps/pod.go

Follow up https://github.com/openshift/ci-tools/pull/1837#discussion_r612310131
- Add an identifier to `ClusterClaimLink` to make the implementation more robust
- Postpone the nil check on the hive client to step's `Validate()` method
/cc @bbguimaraes

Fix the graph issues from a cluster_claim step

---

cmd/determinize-prow-config/main.go
cmd/determinize-prow-config/main_test.go
pkg/config/release.go

This PR makes determinize-prow-config shard by org repo. It is written
under the assumption that we will add a knob upstream to make the
filename for the supplemental files configurable because:
* We want both Prow and plugin configs in there
* We want to add the basedir as an additional folder, but we do not want
the main config to be considered a supplemental config, as that will
fail the merging. Not adding the basedir would mean to add each org
folder seperately.

Determinize Prow config: Shard prow config

---

pkg/api/graph.go
pkg/defaults/defaults.go
pkg/defaults/defaults_test.go
pkg/steps/cluster_claim.go
pkg/steps/multi_stage_test.go
pkg/steps/pod.go
pkg/steps/pod_test.go

Fix https://prow.ci.openshift.org/view/gs/origin-ci-test/pr-logs/pull/openshift_release/17645/rehearse-17645-pull-ci-openshift-ci-ns-ttl-controller-master-e2e/1382050151790546944
The problem is that the name of cluster step is different from the one of multi-stage step and the one of pod step.
/cc @bbguimaraes

Fix the identifier of clusterClaimLink

---

pkg/prowgen/prowgen.go
pkg/prowgen/prowgen_test.go
pkg/prowgen/testdata/zz_fixture_TestGeneratePodSpecMultiStage_cluster_claim.yaml

Currently, multistage tests only include `ci-pull-credentials` if the
`configSpec` has a release. It should also include the credentials if
the test specifies a cluster claim.

prowgen: incldue ci-pull-credentials for tests with cluster-claim

---

pkg/defaults/defaults_test.go
pkg/steps/cluster_claim.go

To avoid the confusion what is going on with the job In case like https://prow.ci.openshift.org/view/gs/origin-ci-test/pr-logs/pull/openshift_release/17734/rehearse-17734-periodic-ci-redhat-operator-ecosystem-cvp-ocp-4.7-fast-as-heck-aws/1382319773408301056#1:build-log.txt%3A10

Improve the logs for the cluster_claim step

---

cmd/ci-operator/main.go
cmd/ci-operator/main_test.go
pkg/steps/run.go

DPTP-2145 allow step run to gather the context cancelation errors but don't report them

---

cmd/ci-operator/main.go

Prowjobs with `extra_refs` do not contain SHAs (periodics and
rehearsals, among others), so we end up using an empty string as a hash
input ([example](https://prow.ci.openshift.org/view/gs/origin-ci-test/logs/periodic-ci-openshift-odo-master-v4.5-integration-e2e-periodic/1383118121950253056#1:build-log.txt%3A3)) and sometimes hit cache when we should not.
We can use time as an artificial input in such case, effectively
disabling the cache.
Alternatively, we could fix up Prowjob producers to always resolve SHAs
for refs, but even in that case this chance protects us from silently
doing the wrong thing on empty input.

ci-operator: disable caching on empty input SHAs

---

pkg/steps/multi_stage.go
pkg/steps/multi_stage_test.go

To fix https://prow.ci.openshift.org/view/gs/origin-ci-test/pr-logs/pull/openshift_release/17833/rehearse-17833-pull-ci-openshift-ci-tools-master-e2e/1384131862435205120#1:build-log.txt%3A18

Replace the dots in secret name when used as volume name

---

cmd/ci-secret-bootstrap/main.go

The current method appears to be subtly changing the original encoded string just enough to make the resultant file not be recognized as `binary` and ultimately it fails to load via openpgp.  Switching to the `DecodeString` method produces the exact same output as the string value that is stored in Vault.

Switching to base64.StdEncoding.DecodeString() for decoding binary file content

---

cmd/dptp-controller-manager/main.go

We are throttled most of the time with 20+ delays, after moving dptp-cm
to GH Apps we should have enough token budget for the bump.

dptp-cm: bump GH API budget 300->600

---

cmd/autoowners/main.go
cmd/autoowners/main_test.go

We need to place OWNERS also into the sharded Prow configuration
directory tree, so we can now pass the base of this tree to the
autoowners tool to do so.

autoowners: allow placing OWNERS files in other dirs

---

cmd/vault-secret-collection-manager/main.go
cmd/vault-secret-collection-manager/main_test.go
pkg/vaultclient/vaultclient.go

Right now, ppl do not see their own collections in the Vault UI or CLI
because there is no data in it. This change makes the collection manager
create an index file so that the collection will appear.
Noticed when working on https://issues.redhat.com/browse/DPTP-2068

Vault secret collection manager: Show collection through index file

---

cmd/ci-secret-generator/main_test.go
cmd/vault-secret-collection-manager/main_test.go
cmd/vault-subpath-proxy/main_test.go
pkg/testhelper/accessory.go
pkg/testhelper/vault.go
pkg/vaultclient/vaultclient.go
pkg/vaultclient/vaultclient_test.go
test/e2e/framework/test.go
test/e2e/secret-generator/e2e_test.go

testhelpers.T must be run from the testframeworks Run method to ensure
proper synchronization, otherwise it will not wait correctly and swallow
Errorf and Fatalf calls, making failing tests appear as if they
succeeded.
This changes the accessory to also allow testing.T, and adds a strongly
worded warning when using testhelper.T. The main drawback is that
failures in the accessory can not Fatalf the test anymore, as that is
not allowed from a distinct goroutine. In all practical terms this is of
little relevance for tests that have a runtime of <10 seconds like the
Vault tests.

Vault accessory: Use testing.T instead of testhelper.T

---

pkg/steps/multi_stage.go

Currently:
```
INFO[2021-04-16T12:43:27Z] Step e2e-vsphere-csi-ipi-conf-vsphere-check succeeded after 10.046449097s.
…
INFO[2021-04-16T13:48:38Z] Ran for 2h31m6s
```
Hopefully no one is using the 13 orders of magnitude and we'll be fine
with just 4 =)

ci-operator multi-stage: truncate duration message

---

cmd/pod-scaler/main.go

Someone, somewhere, is binding flags to the global set. I don't really care who it is or why, but I just want this tool to work in it's own space:
```
$ pod-scaler
pod-scaler flag redefined: kubeconfig
panic: pod-scaler flag redefined: kubeconfig
goroutine 1 [running]:
flag.(*FlagSet).Var(0xc0001b48a0, 0x21f09e0, 0xc00030f580, 0x1ed03a0, 0xa, 0x1f5c63f, 0x6e)
/usr/local/go/src/flag/flag.go:871 +0x485
flag.(*FlagSet).StringVar(...)
/usr/local/go/src/flag/flag.go:760
main.bindOptions(0xc0001b48a0, 0xc000076720)
/home/stevekuznetsov/code/openshift/ci-tools/src/github.com/openshift/ci-tools/cmd/pod-scaler/main.go:51 +0xf7
main.main()
/home/stevekuznetsov/code/openshift/ci-tools/src/github.com/openshift/ci-tools/cmd/pod-scaler/main.go:96 +0x3f
```
Signed-off-by: Steve Kuznetsov …

pod-scaler: use our own flag set

---

pkg/steps/pod.go
pkg/steps/release/create_release.go
pkg/steps/release/import_release.go
pkg/steps/release/release_images.go
pkg/steps/source.go

Release pods vary only by the CI Operator configuration, not the
specific target that ends up running them. It is important to be able to
detect that a Pod is being run for a release, in some manner that's less
fragile than searching for a prefix on the Pod name.

ci-operator: label release pods with their release name

---

cmd/pod-scaler/admission.go
go.mod
go.sum
vendor/modules.txt
vendor/sigs.k8s.io/controller-runtime/pkg/webhook/admission/webhook.go

vendor: bump sigs.k8s.io/controller-runtime
---
pod-scaler: use standalone webhook handlers
It seems like the standalone *server* requires that certificate
authentication is used, which does not really apply for in-cluster
servers, which can either run without TLS over the service network or
can have TLS terminated by the routing layer.
---
Part of [DPTP-1822](https://issues.redhat.com/browse/DPTP-1822)

pod-scaler: use standalone webhook handlers

---

pkg/testhelper/accessory.go

The Go reference [1] says:
> If multiple packages import a package, the imported package will be
> initialized only once.
However, something seems wrong with this. It may be the case that the
map in this helper package is being initialized more than once. Perhaps
doing it in an `init()` will help?
[1] https://golang.org/ref/spec#Package_initialization

testhelper: attempt to make global map global

---

pkg/testhelper/accessory.go

This should help us understand if we're racing with something else
in-process for this port or not.
For [DPTP-2159](https://issues.redhat.com/browse/DPTP-2159)

test/e2e: log ports we acquire for debugging

---

cmd/testgrid-config-generator/main.go
test/integration/testgrid-config-generator/expected/redhat-openshift-informing.yaml
test/integration/testgrid-config-generator/expected/redhat-openshift-ocp-release-4.1-blocking.yaml
test/integration/testgrid-config-generator/expected/redhat-openshift-ocp-release-4.1-informing.yaml
test/integration/testgrid-config-generator/expected/redhat-openshift-ocp-release-4.2-blocking.yaml
test/integration/testgrid-config-generator/expected/redhat-openshift-ocp-release-4.2-informing.yaml
test/integration/testgrid-config-generator/expected/redhat-openshift-ocp-release-4.3-broken.yaml

Ref https://github.com/kubernetes/test-infra/issues/21793 although the old links will keep working

Use gs-prefixed link rather than gcs in testgrid-generator

---

pkg/api/graph.go
pkg/defaults/defaults.go
pkg/defaults/defaults_test.go
pkg/steps/cluster_claim.go
pkg/steps/cluster_claim_test.go
pkg/steps/multi_stage.go
pkg/steps/multi_stage_test.go
pkg/steps/pod.go
pkg/steps/pod_test.go

This PR adds deletion functionality for cluster claims to be deleted
when a test using one ends. This is handled in the same way as leases,
where the test step is wrapped in the cluster claim step. This allows
the cluster claim step to delete the claim after the test ends.

[DPTP-2119] steps: clean up cluster claims when test ends

---

pkg/api/types.go
pkg/jobconfig/files.go
pkg/prowgen/prowgen.go
pkg/prowgen/prowgen_test.go
pkg/prowgen/testdata/zz_fixture_TestGeneratePeriodicForTest_release_controller_job.yaml
pkg/validation/test.go
pkg/validation/test_test.go
test/integration/ci-operator-prowgen/input/config/super/duper/super-duper-master.yaml
test/integration/ci-operator-prowgen/output/jobs/super/duper/super-duper-master-periodics.yaml

This PR adds support for defining jobs as release-informing to prevent
confusion when a periodic job is configured via release-controller
instead of a prowjob or ci-operator config. A `release-controller` PR
will be created to validate that all jobs defined in the
release-controller periodics are appropriately labelled as release
informers and that all jobs with the label are in the release-controller
periodics configs.

prowgen: add release-informing job type

---

cmd/vault-secret-collection-manager/main.go
pkg/vaultclient/vaultclient.go

It's only valid for one hour, so long-running applications like the
secret manager currently just stop working :grimace:

Vaultclient: Refresh token when using kubernetes auth

---

cmd/ci-operator/main.go
pkg/api/constant.go

A mutating admission webhook in the critical path for Pods can cause
some serious issues when it misbehaves, so we want to select the
namespaces for which our Pod auto-scaler runs. We can label job
namespaces to allow for this.
Part of [DPTP-1822](https://issues.redhat.com/browse/DPTP-1822)

ci-operator: label namespaces for auto-scaling pods

---

pkg/results/report.go

Fixes 
```
{"level":"trace","msg":"response for report was not 200: [99 108 117 115 116 101 114 32 102 105 101 108 100 32 105 110 32 114 101 113 117 101 115 116 32 105 115 32 101 109 112 116 121]","time":"2021-04-27T21:47:52Z"}
```
@openshift/openshift-team-developer-productivity-test-platform

ci-operator: better report error

---

pkg/defaults/defaults_test.go
pkg/release/official/client.go
pkg/release/official/client_test.go

With this commit, we extend that support to allow explicit version choices like:
```yaml
releases:
firstz:
release:
channel: stable
version: 4.7.0
latest:
candidate:
product: ocp
stream: nightly
version: "4.7"
```
to allow for tests updating between 4.7.0 and the most recent 4.7 nightly.  These tests will in turn alert us to issues like "something new has landed in recent 4.7 nightlies that breaks rollbacks to 4.7.0".
For reasons that are not clear to me, 33c2eaa49b (#839) did not just pass the configured channel along to Cincinnati, but instead appended the major/minor from the requested version.  Before this commit, that logic assumed that the requested version was just a major.minor, and then selected the largest SemVer version from that channel.  So this commit jumps through some …

pkg/release/official: Allow explicit version choices

---

pkg/rehearse/jobs.go
pkg/rehearse/jobs_test.go
pkg/rehearse/testdata/zz_fixture_TestMakeRehearsalPresubmit_hidden_job_that_belong_to_the_same_org_repo_with_refs.yaml
pkg/rehearse/testdata/zz_fixture_TestMakeRehearsalPresubmit_job_that_belong_to_different_org_repo_than_refs.yaml
pkg/rehearse/testdata/zz_fixture_TestMakeRehearsalPresubmit_job_that_belong_to_different_org_repo_than_refs_with_custom_config.yaml
pkg/rehearse/testdata/zz_fixture_TestMakeRehearsalPresubmit_job_that_belong_to_the_same_org_but_different_repo_than_refs.yaml
pkg/rehearse/testdata/zz_fixture_TestMakeRehearsalPresubmit_job_that_belong_to_the_same_org_repo_with_refs.yaml
test/integration/pj-rehearse/expected.yaml

When a user looks at a Pod created by this tool, they cannot
programmatically get the context which the rehearsed job would have
triggered, as we change the context to prepend a rehearsal prefix, etc.
This change exposes the value of the context through labels.

rehearsal: label the context we're rehearsing

---

pkg/steps/output_image_tag.go

https://github.com/openshift/ci-tools/pull/1928 assumed we do not need to handle already exists but we do ([example](https://prow.ci.openshift.org/view/gs/origin-ci-test/pr-logs/pull/openshift-knative_serverless-operator/920/pull-ci-openshift-knative-serverless-operator-main-4.7-images/1387735829668958208))

ci-op: swallow AlreadyExists errors on upserting ists

---

cmd/determinize-prow-config/main.go
cmd/determinize-prow-config/main_test.go

Ref https://issues.redhat.com/browse/DPTP-2110
There were two issues with the initial version:
* The tool didn't load the additional config, so any pre-existing
additional config was always overwritten if new config for the same
org or repo was sharded out
* There was an off-by-one when splitting an org/repo string in the tide
merge method sharding, which resulted in org//repo strings, which got
silently sanitized on write, which resulted in only one of merge
method or branchproteciton config being written out (which one depends
on map order, which is random)
This change produces https://github.com/openshift/release/pull/18171 which seems correct.

Re-add tide merge method sharding

---

cmd/ci-secret-bootstrap/main.go
cmd/ci-secret-bootstrap/main_test.go
pkg/api/secretbootstrap/secretboostrap.go
pkg/api/secretbootstrap/secretboostrap_test.go

There were two issues:
* We had a Config struct in our options, but didn't unmarshal into that
but into a different var, then filter the secrets, the copy only the
secrets property in our config in the options, dropping all other
settings including the UserSecretsTargetClusters along the way
* We operate under a prefix, but the user secrets are elsewhere. This
adds a new option for a dptp prefix that gets appended to the normal
prefix, which allows us to set the normal prefix to the basepath of
the kv store
completed by https://github.com/openshift/release/pull/18216

Fix ci-secret-bootstrap user sync

---

pkg/steps/lease.go
test/e2e/lease/e2e_test.go

Partially rolling back ef63f31f5b (#1834).  This gets the "which resource type?" and "which acquired name?" information up into the build log, so we can see which jobs are running in which AWS regions and such, instead of having to drop down from [the job][1]:
INFO[2021-04-16T19:55:46Z] Acquiring leases for test launch
INFO[2021-04-16T19:55:47Z] Running multi-stage test launch
into [ci-operator assets][2]:
{"level":"debug","msg":"Acquired lease(s) for osd-ephemeral-quota-slice: [9096423b-d59e-491d-8ee2-f7de51139df1]","time":"2021-04-16T19:55:47Z"}
[1]: https://prow.ci.openshift.org/view/gs/origin-ci-test/logs/release-openshift-origin-installer-launch-osd-ephemeral/1383146668190339072#1:build-log.txt%3A12
[2]: https://gcsweb-ci.apps.ci.l2s4.p1.openshiftapps.com/gcs/origin-ci-test/logs/relea …

pkg/steps/lease: Log acquired leases at info level

---

cmd/ci-secret-generator/main.go
cmd/ci-secret-generator/main_test.go

The deserialization prepends it to the path, so we have to strip it
prior to comparing as the generator operates directly on the dptp vault
path.

Fix secret-generator validation to still work with vault_dptp_prefix

---

cmd/ci-secret-bootstrap/main.go
cmd/ci-secret-bootstrap/main_test.go
pkg/secrets/bitwarden.go
pkg/secrets/client.go
pkg/secrets/vault.go

The previous change of stripping the prefix is plain wrong. We simply have to add `dptp` to the `--allow-unused` arg, as its relativ to the root, ref:  https://github.com/openshift/release/pull/18279
The second commit makes us only check dptps items rather than everything.

Ci-Secret-Bootstrap: Fix validation

---

cmd/pj-rehearse/main.go
cmd/pj-rehearse/main_test.go

When the source sets were unbalanced by size in a way that one source
set would fit into its part of the quota and the other would not, we
would actually *not* include the smaller set in the final rehearsal set.
The whole set would be eventually backfilled from dropped jobs, which
only come from the originally larger source sets, entirelly pressing the
smaller (and usually more important) source sets from rehearsals.
/cc @droslean @stevekuznetsov

rehearse: fix buggy subset selection

---

pkg/steps/release/create_release.go

CVO does not support upgrading between two releases that have the
same version number because cluster-operators require a unique
version number to reach level. In CI we can very rarely create
both the initial and latest releases at the same timestamp (cluster
bot, rollback tests, some periodics), and so when ci-operator
generates versions it should clearly separate by the release name
(initial and latest).
Example: 
this cluster-bot job https://prow.ci.openshift.org/view/gs/origin-ci-test/logs/release-openshift-origin-installer-launch-gcp/1389581141689765888 tests upgrading from a given PR to the same PR.  The two release images are created at the exact same time:
```
[36mINFO[0m[2021-05-04T14:08:07Z] Creating release image registry.build01.ci.openshift.org/ci-ln-l9w46sb/release:initial. …
```

steps/release: Create release should qualify version

---

pkg/steps/cluster_claim.go
pkg/steps/cluster_claim_test.go

The current code immediately exits with an error if the `acquireClaim`
function fails without deleting the created claim. This PR makes the
`acquireClaim` function always return the claim if one is made, even on
error, and the `releaseCluster` function is run even when `aquireClaim`
fails.

cluster_claim: always delete claim

---

cmd/vault-subpath-proxy/kv_key_validator.go
pkg/api/secretbootstrap/secretboostrap.go
pkg/api/secretbootstrap/secretboostrap_test.go
pkg/steps/multi_stage.go

https://issues.redhat.com/browse/DPTP-2065
The namespace and name of a secret used in a step's `credentials` are use to compose the volume's name in the pod of the step.
We have 2 sources of secrets:
- secret-bootstrap: validate its targeting secrets in the tools' config.
- self-service: validate in the proxy (the original validate is not enough because it check each of ns and name, we check here the 2 combined).

Check the length of secret names

---

cmd/vault-secret-collection-manager/docker-compose.yaml
cmd/vault-secret-collection-manager/main.go
cmd/vault-secret-collection-manager/main_test.go
pkg/vaultclient/vaultclient.go

Currently, users have to first log into vault and then into the secret
collection manager, otherwise it will fail as the user doesn't exist.
This fixes that.
Ref https://issues.redhat.com/browse/DPTP-2196

Vault secret collection manager: Create users if they dont exist

---

pkg/steps/cluster_claim.go

Noticed while executing unit tests locally, where `Poll` adds an
unconditional, uninterruptible 15s delay.
```
$ time go test --count 1 ./pkg/steps
^C
ok      github.com/openshift/ci-tools/pkg/steps 16.138s
real    0m18.531s
user    0m6.471s
sys     0m0.708s
```
```
time="2021-05-11T14:02:56Z" level=info msg="Waiting for the claimed cluster to be ready."
time="2021-05-11T14:03:11Z" level=info msg="The claimed cluster is ready."
```
With this change:
```
$ time go test --count 1 ./pkg/steps
ok      github.com/openshift/ci-tools/pkg/steps 1.137s
real    0m3.119s
user    0m5.136s
sys     0m0.573s
```

pkg/steps/cluster_claim: use `PollImmediate`

---

pkg/steps/multi_stage.go
pkg/steps/testdata/zz_fixture_TestGeneratePods.yaml

When a workflow wants to expose a $KUBECONFIG via the $SHARED_DIR
without having to rely on cluster_profile, it should be able to.
/assign @petr-muller @bbguimaraes

ci-operator: set $KUBECONFIG regardless of cluster_profile

---

pkg/steps/bundle_source_test.go

The tests leak a directory in `/tmp`:
```
$ find /tmp -name another-manifest.yml 2> /dev/null
/tmp/960074342/4.6/another-manifest.yml
/tmp/683052059/4.6/another-manifest.yml
/tmp/231724004/4.6/another-manifest.yml
/tmp/832461060/4.6/another-manifest.yml
/tmp/026997805/4.6/another-manifest.yml
…
```

pkg/steps/bundle_source: use `testing.TempDir`

---

cmd/publicize/server_test.go

The test creates two repositories using `test-infra`'s
`LocalGit::MakeFakeRepo` and attempts to use them as an
upstream/downstream pair.  However, if a change of the seconds on the
clock happens between the creation of each, the hashes of the generated
commits will not match, resulting in `git` errors due to incompatible
histories.
Adding a 1-second `sleep` call between the creation of the repositories
reproduces the failure consistently.
Sample failure:
```
time="2021-05-12T19:22:55Z" level=info msg="Creating a mirror of the repo at /tmp/gitcache624379900/openshift/test" client=git org=openshift repo=test
time="2021-05-12T19:22:55Z" level=info msg="Creating a mirror of the repo at /tmp/gitcache624379900/openshift/test" client=git org=openshift repo=test
time="2021-05-12T19:22:55Z" …
```

cmd/publicize: fix temporal test failure

---

pkg/rehearse/jobs.go
pkg/rehearse/jobs_test.go
pkg/rehearse/testdata/zz_fixture_TestMakeRehearsalPresubmit_reporting_configuration_is_stripped_from_rehearsals_to_avoid_polluting.yaml

Jobs are rehearsed for various reasons all the time, polluting the
channels where the original (usually important) jobs report their
results.
Resolves: [DPTP-2190](https://issues.redhat.com/browse/DPTP-2190)

rehearse: strip reporter_config from rehearsals

---

cmd/ci-secret-bootstrap/main.go
cmd/ci-secret-bootstrap/main_test.go

Resolves failures such as [this one](https://deck-internal-ci.apps.ci.l2s4.p1.openshiftapps.com/view/gs/origin-ci-private/logs/periodic-ci-secret-bootstrap/1391791192831692800#1:build-log.txt%3A3866):
```
failed to update secrets: [error creating secret api.**:grafana-loki/grafana-config: namespaces \"grafana-loki\" not found ...
```
I'm convinced that creating namespaces is the right thing to do for this automation b/c we have no other way how to enforce a presence of certain namespace on all clusters.
I added a test to describe that this is an intentional behavior, but unfortunately the test passes even if I comment the new code out: the underlying fake client do not seem to be able to fake an error like that (or I did not find a way to coerce it).

secret bootstrap: create nonexistent namespaces

---

pkg/defaults/defaults.go
pkg/steps/artifacts.go
pkg/steps/artifacts_test.go
pkg/steps/cluster_claim.go
pkg/steps/cluster_claim_test.go

cluster claim: use watch API

---

cmd/ci-operator/main_test.go
pkg/results/error.go
pkg/results/error_test.go
pkg/results/report.go
pkg/steps/lease.go
pkg/steps/lease_test.go
pkg/steps/run_test.go
pkg/testhelper/testhelper.go
test/e2e/lease/e2e_test.go

The `Aggregate` error type from `apimachinery` explicitly does not support
`Errors.As`:
```go
// Errors.As() is not supported, because the caller presumably cares
// about a specific error of potentially multiple that match the given
// type.
```
This breaks the causal chain in the `FullReason` method.  This change adds
a function that flattens trees of arbitrarily-nested
`results.Error` and `Aggregate`-like errors into a list while preserving
the hierarchy, so that all errors reported have the correct reason.
https://issues.redhat.com/browse/DPTP-2214

pkg/results: flatten error trees

---

test/e2e/framework/ci-operator.go

Seen in:
https://prow.ci.openshift.org/view/gs/origin-ci-test/pr-logs/pull/openshift_ci-tools/1989/pull-ci-openshift-ci-tools-master-e2e/1394666825530216448
Before:
```
ERRO[2021-05-18T15:51:07Z]   * could not run steps: step invalid-lease failed: failed to acquire lease for "azure4-quota-slice": resources not found
test.go:87: invalid lease fails: could not find line "step invalid-lease failed: failed to acquire lease for \"azure4-quota-slice\": resources not found" in output; output:
…
{"level":"error","msg":"  * could not run steps: step invalid-lease failed: failed to acquire lease for \"azure4-quota-slice\": resources not found","time":"2021-05-18T15:51:07Z"}
```
After:
```
ERRO[2021-05-18T15:57:32Z]   * could not run steps: step invalid-lease failed: failed to acquire lease for …
```

test/e2e: do not escape expected string

---

pkg/steps/artifacts_test.go

To avoid https://prow.ci.openshift.org/view/gs/origin-ci-test/pr-logs/pull/openshift_ci-tools/1990/pull-ci-openshift-ci-tools-master-unit/1394706077567684608

Fix a flaky test TestWaitForConditionOnObject

---

pkg/steps/multi_stage.go
pkg/steps/multi_stage_test.go
pkg/steps/optional_operators.go

The `OO_*` variables were only propagated to Pods in the presence of a cluster profile. For no good reason. :facepalm: 
/cc @dirgim @stevekuznetsov

ci-operator: expose OO_* variables even without cluster profile

---

cmd/ci-secret-bootstrap/main.go
cmd/ci-secret-bootstrap/main_test.go
pkg/api/secretgenerator/secretgenerator.go

We insert the VaultDPTPPrefix into all item names during deserialization
in the bootstrapper and give the generator the same prefix as CLI arg.
This means that the generator config has the items without that prefix
so we need to strip it before we check in the generator config if it
exists.
/cc @droslean @petr-muller 
Responsible for e.G. the incorrect failure here: https://github.com/openshift/release/pull/18643

Bootstrap item validation: Correctly strip prefix

---

cmd/ci-operator/main.go
cmd/ci-operator/main_test.go
pkg/api/types.go
pkg/steps/multi_stage.go

Allow a pull spec to be passed in to the ci-operator. This pull spec will override any dependency that matches the environment variable name. For example:
`--dependency-override-param=OO_INDEX=registry.mystuff.com:5000/pushed/myimage`
would override the `OO_INDEX` env param in any test step with the value `registry.mystuff.com:5000/pushed/myimage`. It is then up to the job to use that pull spec appropriately.

DPTP-2200: Support overriding a dependency with an external pull spec.

---

pkg/api/types.go
pkg/api/types_test.go
pkg/defaults/defaults.go
pkg/defaults/defaults_test.go

Improves [DPTP-1463](https://issues.redhat.com/browse/DPTP-1463)
https://github.com/openshift/ci-tools/pull/1962 added better logging for imported images, but it only logs that an image is a base image, but not under which name does it figure in the ci-op config.
/cc @emilvberglind

ci-operator: log aliases of imported images

---

cmd/determinize-prow-config/main.go
cmd/determinize-prow-config/main_test.go
pkg/config/release.go

The config is behind a new flag so this doesn't get triggered per default. We still need to update the flags for our components.
Ref https://issues.redhat.com/browse/DPTP-2112

Determinize-Prow-Config: Add plugin config sharding

---

pkg/steps/input_image_tag.go
pkg/steps/output_image_tag.go

Inspired by https://prow.ci.openshift.org/view/gs/origin-ci-test/pr-logs/pull/openshift_release/18238/rehearse-18238-promote-release-openshift-okd-machine-os-content-e2e-aws-4.8/1397096765055832064
The error log is not clear enough, so the user wasn't able to determine if his env var was resolved or not.

add namespace and name in error log when failing to resolve an image

---

pkg/steps/source_test.go
pkg/steps/testdata/zz_fixture_TestBuildFromSource_build_args__value.yaml
pkg/steps/testdata/zz_fixture_TestBuildFromSource_build_args__valueFrom.yaml

https://issues.redhat.com/browse/DPTP-2247

set namespace in source unittests to avoid stack traces

---

test/validate-prowgen-breaking-changes.sh

Make the breaking-changes job to respect config shrading

---

pkg/controller/test-images-distributor/test_images_distributor.go

So far we only logged namespace and name as part of the request but the
request is in clusterName_namespace/name notation, which is confusing to
filter for.

Test images distributor: Log namespace and name

---

cmd/dptp-controller-manager/main.go
pkg/controller/testimagestreamimportcleaner/README.md
pkg/controller/testimagestreamimportcleaner/testimagestreamimportcleaner.go
pkg/controller/testimagestreamimportcleaner/testimagestreamimportcleaner_test.go

This change adds a small controller that will delete all
testimagestreamtagimport custom resources that are seven days or older
old. This prevents us from importing images indefinitely just because
one test once needed them.
Ref https://issues.redhat.com/browse/DPTP-1640

Clean up testimagestreamtagimport CRs after seven days

---

cmd/ci-secret-bootstrap/main.go
cmd/ci-secret-bootstrap/main_test.go
pkg/secrets/vault.go
pkg/vaultclient/vaultclient.go
pkg/vaultclient/vaultclient_test.go

If the active vault replica goes down, the two retries the vault client
does by default are almost never enough. This change increases them to
eight, which made me unable to reproduce the EOF errors we regularly saw
in CI before
Ref https://issues.redhat.com/browse/DPTP-2224

Vault: Retry more to account for temporary down single active replica

---

pkg/api/testimagestreamtagimport/v1/types.go
pkg/controller/test-images-distributor/test_images_distributor.go
pkg/controller/test-images-distributor/test_images_distributor_test.go
pkg/defaults/defaults.go
pkg/defaults/defaults_test.go

Based on top of https://github.com/openshift/ci-tools/pull/2006, please review that one first and only the second commit here.
Makes the TestImageDistributor react to testImageStreamImports in all clusters rather than just the ones in app.ci
Ref https://issues.redhat.com/browse/DPTP-1640

Test Image distributor: Consider TestImageImports from all clusters

---

cmd/vault-secret-collection-manager/index.template.html
cmd/vault-secret-collection-manager/index.ts

This changes the secret collection manager to use a datalist for the all
members field instead of a multiselect. This allows ppl to either see
all entries as a suggestion or to just start typing which is useful in
our production case where there are lots of users.
Ref https://issues.redhat.com/browse/DPTP-2192

Vault Secret Collection Manager Edit Members: Allow filtering

---

cmd/autoconfigbrancher/main.go

1. `determinize-prow-config` needs to run with shard-aware options
2. We need to temporarily disable `private-prow-configs-mirror` b/c it does not
respect shards and unshards plugin config when it runs. Filed [DPTP-2256](https://issues.redhat.com/browse/DPTP-2256) to
address this.
/cc @AlexNPavel @alvaroaleman

autoconfigbrancher: respect prow config sharding

---

pkg/api/testimagestreamtagimport/v1/types.go
pkg/controller/test-images-distributor/test_images_distributor.go
pkg/controller/test-images-distributor/test_images_distributor_test.go
pkg/defaults/defaults_test.go

Label values can not contain colons, thus the testimagestreamtagimport
creation currenty always fails.
Ref https://issues.redhat.com/browse/DPTP-1640
Sample where this failed due to the colons: https://prow.ci.openshift.org/view/gs/origin-ci-test/logs/release-openshift-origin-installer-launch-gcp/1400066650719391744#1:build-log.txt%3A12

Testimagestreamtagimport: Replace colons in label values

---

cmd/determinize-prow-config/main.go

Before this change, we looked at`filepath.Dir(config.PluginConfigFile)`
for additional plugin configs. Since `config.PluginConfigFile` is just a
filename, this resolves to `.` which is wrong (but happens to include
the correct files, as they are in a subdir) and always fails in Docker
with an error like `failed to walk .: lstat proc/1/fd/6: no such file or directory"`.
This changes it to correctly look at the dir of the entire plugin config
file path instead, which fixes above error.
Noticed in https://coreos.slack.com/archives/CBN38N3MW/p1622664617007600

Determinize Prow config: Fix dir for additional plugin configs

---

cmd/ci-operator-yaml-creator/README.md
cmd/ci-operator-yaml-creator/main.go
cmd/ci-operator-yaml-creator/main_test.go

This change makes the CI-Operator-Yaml-Creator also update the release
repo config if the .ci-operator.yaml is already current. I initially
planned to write a second tool for this but realized it is much easier
to just add it here.
Ref https://issues.redhat.com/browse/DPTP-2245
/assign @jupierce 
Is this intended to be run as an one-off btw or should it run periodically?

CI-Operator-Yaml-Creator: Set build_root.from_repository if config is current

---

cmd/ci-operator/main.go
cmd/generate-registry-metadata/main.go
cmd/ldap-users-from-github-owners-files/main.go
cmd/prow-job-dispatcher/main.go
cmd/release-job-migrator/main.go
cmd/sanitize-prow-jobs/main.go
cmd/testgrid-config-generator/main.go
pkg/api/ocpbuilddata/types.go
pkg/config/load.go
pkg/jobconfig/files.go
pkg/load/load.go
pkg/rehearse/configmaps.go

The latter calls stat for every single file so it is vastly less
efficient.

Use filepath.WalkDir instead of filepath.Walk

---

cmd/pod-scaler/main.go
cmd/pod-scaler/producer.go
cmd/pod-scaler/storage.go

pod-scaler: support http for prometheus
---
pod-scaler: close over different not exists errors
---
pod-scaler: create directory for cache when necessary
---
pod-scaler: query serially
We don't *need* to send off all of our requests all at once to every
single build farm at the same time, since we have no real requirement to
have the most up-to-date data at any point. In that vein, if we query
sequentially we can reduce the overall memory footprint of the producer
by only loading one dataset into memory at once.
---
/assign …

Misc updates to the pod-scaler

---

cmd/cvp-trigger/main.go
cmd/cvp-trigger/main_test.go
test/integration/cvp-trigger/periodic-ipi-deprovision.expected

With [DPTP-2266](https://issues.redhat.com/browse/DPTP-2266) we're taking the first step towards removing special logic from the CVP jobs by passing the OO_ params as multi-stage-param entries to the ci-operator.

DPTP-2266: Pass OO_ params to ci-operator as multi-stage-param.

---

cmd/pod-scaler/main.go
cmd/pod-scaler/producer.go

pod-scaler: allow bounding query upper time limit
With --ignore-latest <duration> the pod scaler can now ignore the latest
<duration> of data from Prometheus. This may be useful in production to
not read data from tests still in progress, but is more useful in tests
to configure which data should be read in any one execution.
---
pod-scaler: allow producing just once
Running through all the queries and writing out the cached data just
once instead of on an interval is useful in testing.
---

pod-scaler: misc flag improvements

---

cmd/ci-operator/main.go
pkg/steps/template.go

Originally, multi-line errors were expanded to allow for readable output
when using JSON-formatted logs. However, we've since changed to use more
human-friendly formatting anyway, so we don't need to split this
manually any longer. By splitting, we made it impossible for the censor
to work on ci-operator output.

ci-operator: log multi-line together

---

cmd/autoowners/main.go

Using `--pr-base-branch=main` one now can override the base branch for the
PR created.

Add flag for base branch

---

cmd/prow-job-dispatcher/main.go
cmd/prow-job-dispatcher/main_test.go
pkg/dispatcher/config.go
pkg/dispatcher/config_test.go
pkg/dispatcher/testdata/TestLoadConfig/good_config_with_build_farm_with_jobs.yaml

Follow up https://coreos.slack.com/archives/GB7NB0CUC/p1623442582036900
TL;TR
The sanitize tool is slow because for each file (we have lots of them), we have to match the regex under `build_farm` in the config file. We do not need the regex match feature at all there. So we replace them with `sets.String.has()`.
This is a breaking change. We need a PR on the config file in release repo too.
Before the PR,
```console
time sanitize-prow-jobs --prow-jobs-dir ./ci-operator/jobs --config-path ./core-services/sanitize-prow-jobs/_config.yaml
sanitize-prow-jobs --prow-jobs-dir ./ci-operator/jobs --config-path   856.36s user 10.49s system 964% cpu 1:29.89 total
```
After,
```console
$ time sanitize-prow-jobs --prow-jobs-dir ./ci-operator/jobs --config-path …
```

Optimize the sanitize tool

---

go.mod
go.sum
vendor/github.com/google/go-cmp/cmp/path.go
vendor/github.com/google/go-cmp/cmp/report_compare.go
vendor/github.com/google/go-cmp/cmp/report_reflect.go
vendor/github.com/google/go-cmp/cmp/report_slices.go
vendor/modules.txt

After a patch like this:
```
diff --git a/pkg/api/secretbootstrap/secretboostrap_test.go b/pkg/api/secretbootstrap/secretboostrap_test.go
index 80e8e1aa5..2e61f2e29 100644
--- a/pkg/api/secretbootstrap/secretboostrap_test.go
+++ b/pkg/api/secretbootstrap/secretboostrap_test.go
@@ -140,7 +140,7 @@ func TestResolving(t *testing.T) {
return
}
-                       if diff := cmp.Diff(tc.expectedConfig, tc.config); diff != "" {
+                       if diff := cmp.Diff(tc.expectedConfig, nil); diff != "" {
t.Errorf("expected config differs from actual config: %s", diff)
}
})
```
the upstream cmp version produces this diff:
```
$ go test ./pkg/api/secretbootstrap/
--- FAIL: TestResolving (0.00s)
--- FAIL: TestResolving/Cluster_groups_get_resolved (0.00s)
secretboostrap_test.go:144: …
```

Use forked cmp version that does not trim the diff

---

pkg/steps/multi_stage.go
pkg/steps/pod.go
pkg/steps/template.go

It is not clear why these were never propagated in the first place. We
use the central context in normal flows and the cleanup context in
post-interrupt code.

ci-operator: propagate contexts as necessary

---

pkg/controller/test-images-distributor/test_images_distributor.go
pkg/controller/test-images-distributor/test_images_distributor_test.go
pkg/load/agents/configAgent.go
pkg/load/agents/configAgent_test.go

This change makes the test-image-distributor distribute images for new config as soon as new config is present, rather than just allowlisting the image in the filter, but not actually distributing it until it changes or the controller is restarted. It is divided in two commits:
* The first commit extends the ci-operator config agent to allow to subscribe to index changes
* The second commit makes the controller subscribe to changes go its index and trigger a reconciliation of all images for new config
Ref https://issues.redhat.com/browse/DPTP-2218

Test-Image-Distributor: Distribute images for new config

---

pkg/controller/test-images-distributor/test_images_distributor.go
pkg/controller/test-images-distributor/test_images_distributor_test.go
pkg/load/agents/configAgent.go
pkg/load/agents/configAgent_test.go

Ref https://issues.redhat.com/browse/DPTP-2218
Re-adds https://github.com/openshift/ci-tools/pull/2057 which was reverted in https://github.com/openshift/ci-tools/pull/2061
The second commit fixes the issue which made us panic.

Re-Add test-image-distributor distributes images from new config instantly

---

cmd/ci-operator-yaml-creator/main.go
cmd/ci-operator-yaml-creator/main_test.go

Not doing this makes us race when a variant is present and update the PR
with the first variant and then the second on, visible e.G. on
https://github.com/openshift/origin/pull/26227

ci-operator-yaml-creator: Ignore variants

---

cmd/registry-replacer/main.go
cmd/registry-replacer/main_test.go
cmd/registry-replacer/testdata/zz_fixture_TestReplacer_Unused_base_images_are_pruned.yaml

With [DPTP-2244](https://issues.redhat.com/browse/DPTP-2244) we want to expand the registry-replacer so it'll also prune unused base images. In order to do this we need to resolve the full config so we can verify if a specific base image is used in any of the tests

DPTP-2244: Registry-replacer should also prune unused base images.

---

pkg/api/types.go
pkg/prowgen/prowgen.go
pkg/validation/test.go

We added a new OSP cloud that will be used in our CI, so we need this
new profile to be added into ci-tools.

Add cluster profile for openstack-vh-mecha

---

pkg/jobconfig/files.go
test/integration/ci-operator-prowgen/input/jobs/super/duper/super-duper-master-presubmits.yaml
test/integration/ci-operator-prowgen/output/jobs/super/duper/super-duper-master-presubmits.yaml
test/integration/repo-init/expected/core-services/prow/02_config/_config.yaml

Like `run_if_changed`, allow `skip_if_only_changed` to be specified directly in job configs without being overwritten by `make jobs`.

Allow `skip_if_only_changed` in jobs

---

cmd/ci-operator/main.go
cmd/ci-operator/main_test.go
pkg/api/types.go
pkg/registry/resolver.go
pkg/webreg/zz_generated.ci_operator_reference.go

[DPTP-2269](https://issues.redhat.com/browse/DPTP-2269) allows steps to override dependencies with fully-qualified pullspecs. This is needed for rehearsals.

DPTP-2269: Add dependency overrides at test level.

---

pkg/steps/cluster_claim.go

We log _"Build X succeeded after XmYs"_ so we may as well log claim durations for bragging and comparison to full installs

claims: log duration for the successful claim

---

cmd/autoconfigbrancher/main.go

Reverts openshift/ci-tools#2073 as a followup to https://github.com/openshift/ci-tools/pull/2076
Temporary revert to fix https://prow.ci.openshift.org/view/gs/origin-ci-test/logs/periodic-prow-auto-config-brancher/1405490361786175488#1:build-log.txt%3A62

Revert "DPTP-2244: Modify autoconfigbrancher to provide registry dir to registry-replacer."

---

cmd/ci-operator/main.go
pkg/api/env.go
pkg/junit/censor.go
pkg/junit/censor_test.go
pkg/junit/testdata/zz_fixture_TestCensorTestSuite.yaml

When user secrets end up in our output files *and* they include
characters that are invalid in the encoding we're going to use to write
those files (like JSON or XML), we end up not censoring anything since
the encoded content we run the censorer over does not contain the actual
secret data. Pre-censoring fields in these structs is fragile, but a
reasonable compromise to writing custom, complex and also fragile
reflection-based implementations that would attempt to operate over
different structs generically. When we use `api.SaveArtifact` we must
remember to pre-censor as necessary beforehand.

ci-operator: pre-censor fields before encoding output

---

cmd/private-org-sync/main.go

We're getting random errors like the following which are really not that helpful. Before we add retrying, it would be nice to know what is actually happening.
```
time="2021-06-23T09:13:55Z" level=error msg="Failed to determine branch HEADs in source" branch=origin-4.3-kubernetes-1.16.0-beta.1 destination=openshift-priv/kubernetes-apimachinery@origin-4.3-kubernetes-1.16.0-beta.1 error="ls-remote failed: (exit code=128)" local-repo=/tmp/934508300/openshift/kubernetes-apimachinery org=openshift repo=kubernetes-apimachinery source=openshift/kubernetes-apimachinery@origin-4.3-kubernetes-1.16.0-beta.1 source-file=openshift-kubernetes-apimachinery-origin-4.3-kubernetes-1.16.0-beta.1.yaml variant= 
```
/cc @droslean

private-org-sync: include output when git ls-remote fails

---

pkg/controller/test-images-distributor/test_images_distributor.go

Currently, if a ci-operator config change references a new imagestream,
we will get it and then distribute all tags in it. Sometimes ppl add
defunct config that references an inexistent stream, resulting in error
like this:
```
msg=Failed to get imagestream, error=ImageStream.image.openshift.io "4.9-priv" not found
```
This change supresses such error logs.

Test Image distributor: Don't log notfound in configchange handler

---

cmd/cvp-trigger/main.go
test/integration/cvp-trigger/periodic-ipi-deprovision.expected

This is the first phase of moving these over where we need to duplicate the params so we don't break existing CVP.

DPTP-2270: Make CVP produce OO_ params again as this will lessen the migration burden for ci workflows.

---

.ci-operator.yaml

Follow-up to https://github.com/openshift/release/pull/19698

build_root: use new image

---

pkg/steps/secretrecordingclient/client.go
pkg/steps/secretrecordingclient/client_test.go

We do this when we're mounting secrets into the individual steps, but we
incorrectly censored everything in ci-operator itself.

ci-operator: skip censoring for $SHARED_DIR secrets

---

Makefile
hack/lint.sh

We now have a run_if_changed presubmit to trigger on changes to the OO
code for those, and a postsubmit with an alert to give more confidence.

e2e: don't run OO e2e by default

---

pkg/validation/config.go
pkg/validation/config_test.go
pkg/validation/field.go
pkg/validation/test.go
pkg/validation/test_test.go

https://issues.redhat.com/browse/DPTP-2259
`ci-operator` currently has non-existent or inconsitent checks for whether the
`ImageStreamTag`s in the `pipeline` `ImageStream` conflict.  It is possible to
create configurations that result execution graphs with surprising and incorrect
behavior (see the Jira issue for examples).
A consistent set of validations is added, replacing existing ones where
appropriate, so that those configurations are not accepted.  Once we have proper
checking (see the task list below), the incorrect configuration presented in the
Jira issue will be rejected:
```
$ ci-operator-checkconfig --config-dir ci-operator/config --registry ci-operator/step-registry
ERRO[0000] Failed to load CI Operator configuration      error="invalid ci-operator config: invalid …
```

pkg/validation: validate all pipeline image inputs

---

cmd/pod-scaler/producer.go

Previously, we would double-count data that happened to be on an edge
between two queries. We can offset a query by 1s (smaller than the
Prometheus sampling interval) to remedy this.

pod-scaler: don't double count data on query edges

---

cmd/pod-scaler/producer.go

pod-scaler: correctly compute start of query range

---

cmd/pod-scaler/producer.go

Using == was doing a comparison on the pointers, which did end up
terminating but not until we sent a spurious 0-length query.

pod-scaler: correctly detect the end of query range

---

pkg/validation/config.go
pkg/validation/config_test.go
pkg/validation/test.go
pkg/validation/test_test.go

This reverts commit ddad6ec63d261b76a6c4c8926e5fb985b5b03a1b, partially
reverting https://github.com/openshift/ci-tools/pull/2062.
`from_image` needs special treatment as multiple entries in different steps can
alias each other.  I'll also look into why our validation did not catch this.

Revert "pkg/validation: also validate `from_image`"

---

cmd/cvp-trigger/main.go
test/integration/cvp-trigger/periodic-ipi-deprovision.expected

Since https://github.com/openshift/release/pull/19401 images are dependencies, not params, so `cvp-trigger` needs to set them as dep overrides, not params.
Testing run with the changes:
https://prow.ci.openshift.org/view/gs/origin-ci-test/logs/periodic-ci-redhat-operator-ecosystem-cvp-ocp-4.7-cvp-common-aws/1408394647914418176

cvp-trigger: pass index & bundle as dep overrides, not params

---

pkg/validation/config_test.go
pkg/validation/test.go

Dependency overrides are not taken into account when performing fail-fast test step dependency validations.

---

cmd/autoowners/main.go
cmd/autoowners/main_test.go

Seen in an `autoowners` call:
```console
$ go run ./cmd/autoowners -debug-mode -dry-run -target-dir ../origin -target-subdir test -config-subdir extended
...
INFO[0000] ListOrgMembers(openshift, all)                client=github
INFO[0002] handling repo ...                             orgRepo=util/image
INFO[0002] GetFile(util, image, OWNERS, )                client=github
DEBU[0002] GetFile(util, image, OWNERS, ) finished       client=github duration=574.249751ms
DEBU[0002] Not found file in the upstream repo           filename=OWNERS orgRepo=util/image
INFO[0002] GetFile(util, image, OWNERS_ALIASES, )        client=github
DEBU[0003] GetFile(util, image, OWNERS_ALIASES, ) finished  client=github duration=479.108876ms
DEBU[0003] Not found file in the upstream repo …
```

cmd/autoowners: Don't pull OWNERS_ALIASES when there is no OWNERS

---

images/ci-secret-bootstrap/Dockerfile
images/ci-secret-generator/Dockerfile

We do not sync with BitWarden.
The installation waste our time?
https://prow.ci.openshift.org/view/gs/origin-ci-test/pr-logs/pull/openshift_ci-tools/2130/pull-ci-openshift-ci-tools-master-images/1410333666898350080

Remove BitWarden cli in the built images

---

pkg/api/config.go
pkg/defaults/defaults.go
pkg/validation/config_test.go
pkg/validation/test.go
test/e2e/multi-stage/cluster-claim.yaml
test/e2e/multi-stage/e2e_test.go

The current support for overriding releases for tests using cluster
claims supports overriding release streams, but not release payloads.
This PR adds support for overriding release payload images as well.

cluster claims: override release payload images

---

Makefile
test/validate-checkconfig.sh

Based on `test/validate-prowgen-breaking-changes.sh`, with the
difference that this will be a required check.  Failures should always
be corrected prior to the introduction of new validations.

Add `checkconfig` validation script

---

test/validate-checkconfig.sh

`redhat-operator-ecosystem` has an empty `ci-operator/step-registry`.
Use the one from `openshift/release` in all checks.

validate-checkconfig: use `openshift` registry

---

pkg/steps/utils/clusterpool.go
pkg/steps/utils/clusterpool_test.go

Previously ci-op needed exactly single match when getting cluster pools
to satisfy a `cluster_claim`, which is problematic b/c there may be
multiple pools with same cluster specs except for e.g. the region (about
which most jobs do not care).
When there are more pools to satisfy the job, select the one which has
higher 1) ready clusters 2) size 3) maxsize.

ci-operator: select best pool when there are more

---

Makefile
cmd/pod-scaler/producer.go
cmd/pod-scaler/producer_test.go
go.mod
go.sum
test/e2e/pod-scaler/e2e_test.go
test/e2e/pod-scaler/kubernetes/kubernetes.go
test/e2e/pod-scaler/local/main.go
test/e2e/pod-scaler/prometheus/backfill.go
test/e2e/pod-scaler/prometheus/prometheus.go
test/e2e/pod-scaler/run/producer.go
test/images/e2e-bin/Dockerfile
vendor/github.com/prometheus/prometheus/LICENSE
vendor/github.com/prometheus/prometheus/NOTICE
vendor/github.com/prometheus/prometheus/pkg/value/value.go
vendor/modules.txt

pod-scaler: add e2e tests that use a real Prometheus
In these tests (and the local running mode for the pod-scaler in
general), we start by filling a Prometheus server with some fake data
using the new backfill command from `promtool`. Then, we run the
pod-scaler producer and assert something about the data we've fetched.
We cannot sensibly assert about the rates, so for now we just assert
about memory usage, but this should suffice as the content of a query
does not change how we get the data from Prometheus and store it. In the
time it took to write this e2e test, the following issues were resolved:
- the promtool utility is extremely slow, we use the latest possible
version now to take advantages of new patches I wrote to increase
the speed it runs by 100x
- there were two off-by-one …

pod-scaler: add an e2e test

---

pkg/steps/artifacts.go
pkg/steps/pod_test.go
pkg/steps/testdata/zz_fixture_TestPodStepExecution_Pod_run_by_PodStep_fails_so_PodStep_terminates_and_returns_an_error.yaml
pkg/steps/testdata/zz_fixture_TestPodStepExecution_Pod_run_by_PodStep_succeeds_so_PodStep_terminates_and_returns_no_error.yaml
pkg/steps/testdata/zz_fixture_TestPodStepExecution_Successful_pod_with_cloning.yaml
test/e2e/simple/e2e_test.go

Currently, the decoration config the ci-operator gets gets passsed on to
pods it creates. In many cases, it has skip_cloning: true set which
means the decoration utils code will create an empty clonerefs
container which currently leads to a NPD.
We only attempt to create a clonerefs container if we definitely want
cloning, so we need to overwrite that setting.
Sample failure: https://prow.ci.openshift.org/view/gs/origin-ci-test/logs/branch-ci-open-cluster-management-helloprow-go-main-fast-forward/1412433374051569664#1:build-log.txt%3A13

CI Operator: Make sure cloning is not disabled when cloning

---

cmd/sprint-automation/main.go
pkg/jira/issues.go

Currently looks like:
SVG based images for avatars hosted on Jira are not possible to display in Slack so we can't see what is a sub-task/bug/etc and users with icons anywhere but gravatar don't display, but /shrug

sprint-automation: digest issues ready for acceptance

---

cmd/dptp-controller-manager/main.go
hack/run-dptp-controller-manager.sh
pkg/api/helper/imageextraction.go
pkg/controller/test-images-distributor/test_images_distributor.go
pkg/defaults/defaults.go
pkg/load/agents/configAgent.go

dptp-controller-manager: update default registry cluster
---
dptp-controller-manager: fix bugs and typos in logs
---
dptp-controller-manager: distribute build caches even for in-repo config
---
hack: update the dptp-controller-manager runfile
---

dptp-controller-manager: distribute build caches even for repos with in-repo config

---

cmd/ci-operator-config-mirror/main.go
test/integration/ci-operator-config-mirror/input-to-clean/super/duper/super-duper-master.yaml
test/integration/ci-operator-config-mirror/input/super/duper/super-duper-master.yaml
test/integration/ci-operator-config-mirror/output-only-super/super/duper/super-duper-master.yaml
test/integration/ci-operator-config-mirror/output/super/duper/super-duper-master.yaml

This PR updates ci-operator to ignore cloning postsubmits and periodics
in the config mirror command.

DPTP-2347: do not mirror postsubmits and periodics

---

pkg/validation/config.go
pkg/validation/config_test.go
pkg/validation/test.go
pkg/validation/test_test.go

This reinstates the validation attempted in
https://github.com/openshift/ci-tools/pull/2062 which had to be reverted in
https://github.com/openshift/ci-tools/pull/2118.
The implementation now properly considers `from_image` fields across all steps
in all tests in the configuration.  The check which will be introduced in
https://github.com/openshift/ci-tools/pull/2134 will also guarantee that the
validation is correct.
/hold
for #2134

pkg/validation: also validate `from_image`

---

cmd/ci-operator-prowgen/testdata/zz_fixture_presubmit_TestFromCIOperatorConfigToProwYaml_Input_is_YAML_and_it_is_correctly_processed.yaml
cmd/ci-operator-prowgen/testdata/zz_fixture_presubmit_TestFromCIOperatorConfigToProwYaml_Using_a_variant_config__one_test_and_images__one_existing_job._Expect_one_presubmit__pre_post_submit_images_jobs._Existing_job_should_not_be_changed..yaml
cmd/ci-operator-prowgen/testdata/zz_fixture_presubmit_TestFromCIOperatorConfigToProwYaml_one_test_and_images__no_previous_jobs._Expect_test_presubmit__pre_post_submit_images_jobs.yaml
pkg/prowgen/prowgen.go
pkg/prowgen/testdata/zz_fixture_TestGenerateJobs_Promotion_configuration_causes_promote_job_with_unique_targets.yaml
pkg/prowgen/testdata/zz_fixture_TestGeneratePresubmitForTest_presubmit_for_a_test_in_a_variant_config.yaml
pkg/prowgen/testdata/zz_fixture_TestGeneratePresubmitForTest_presubmit_for_standard_test.yaml
pkg/prowgen/testdata/zz_fixture_TestGeneratePresubmitForTest_presubmit_with_job_release_specified.yaml
pkg/prowgen/testdata/zz_fixture_TestGeneratePresubmitForTest_presubmit_with_job_release_specified_and_clone.yaml
test/integration/ci-operator-prowgen/output/jobs/private-org/duper/private-org-duper-master-presubmits.yaml
test/integration/ci-operator-prowgen/output/jobs/private/duper/private-duper-master-presubmits.yaml
test/integration/ci-operator-prowgen/output/jobs/subdir/repo/subdir-repo-master-presubmits.yaml
test/integration/ci-operator-prowgen/output/jobs/super/duper/super-duper-master-presubmits.yaml
test/integration/ci-operator-prowgen/output/jobs/super/duper/super-duper-master-removed-promotion-presubmits.yaml
test/integration/ci-operator-prowgen/output/jobs/super/duper/super-duper-release-3.11-presubmits.yaml
test/integration/repo-init/expected/ci-operator/jobs/openshift/ci-tools/openshift-ci-tools-master-presubmits.yaml
test/integration/repo-init/expected/ci-operator/jobs/openshift/origin/openshift-origin-master-presubmits.yaml
test/integration/repo-init/expected/ci-operator/jobs/org/other/org-other-nonstandard-presubmits.yaml
test/integration/repo-init/expected/ci-operator/jobs/org/repo/org-repo-master-presubmits.yaml
test/integration/repo-init/expected/ci-operator/jobs/org/third/org-third-nonstandard-presubmits.yaml

In the past, we considered any `$branch$suffix` a feature branch of
"base" CI branch (e.g. PRs to `master-next` would receive presubmits
from `master` config). We need to make this convention stricter to not
break on `4.10`, because the current convention means that
`release-4.10` is a feature branch for `release-4.1`.
All generated presubmits now have two items in their `branches:` stanza.
One item that matches exactly the branch (`^branch$`), just like
postsubmits have, and one item that matches branches with `$base-`
prefix. Practically this means that we enforce exactly the `-` separator
for a branch to be considered a feature branch.

prowgen: generate stricter `branch:` stanzas for presubmits

---

cmd/ci-operator-prowgen/testdata/zz_fixture_presubmit_TestFromCIOperatorConfigToProwYaml_Input_is_YAML_and_it_is_correctly_processed.yaml
cmd/ci-operator-prowgen/testdata/zz_fixture_presubmit_TestFromCIOperatorConfigToProwYaml_Using_a_variant_config__one_test_and_images__one_existing_job._Expect_one_presubmit__pre_post_submit_images_jobs._Existing_job_should_not_be_changed..yaml
cmd/ci-operator-prowgen/testdata/zz_fixture_presubmit_TestFromCIOperatorConfigToProwYaml_one_test_and_images__no_previous_jobs._Expect_test_presubmit__pre_post_submit_images_jobs.yaml
pkg/prowgen/prowgen.go
pkg/prowgen/testdata/zz_fixture_TestGenerateJobs_Promotion_configuration_causes_promote_job_with_unique_targets.yaml
pkg/prowgen/testdata/zz_fixture_TestGeneratePresubmitForTest_presubmit_for_a_test_in_a_variant_config.yaml
pkg/prowgen/testdata/zz_fixture_TestGeneratePresubmitForTest_presubmit_for_standard_test.yaml
pkg/prowgen/testdata/zz_fixture_TestGeneratePresubmitForTest_presubmit_with_job_release_specified.yaml
pkg/prowgen/testdata/zz_fixture_TestGeneratePresubmitForTest_presubmit_with_job_release_specified_and_clone.yaml
test/integration/ci-operator-prowgen/output/jobs/private-org/duper/private-org-duper-master-presubmits.yaml
test/integration/ci-operator-prowgen/output/jobs/private/duper/private-duper-master-presubmits.yaml
test/integration/ci-operator-prowgen/output/jobs/subdir/repo/subdir-repo-master-presubmits.yaml
test/integration/ci-operator-prowgen/output/jobs/super/duper/super-duper-master-presubmits.yaml
test/integration/ci-operator-prowgen/output/jobs/super/duper/super-duper-master-removed-promotion-presubmits.yaml
test/integration/ci-operator-prowgen/output/jobs/super/duper/super-duper-release-3.11-presubmits.yaml
test/integration/repo-init/expected/ci-operator/jobs/openshift/ci-tools/openshift-ci-tools-master-presubmits.yaml
test/integration/repo-init/expected/ci-operator/jobs/openshift/origin/openshift-origin-master-presubmits.yaml
test/integration/repo-init/expected/ci-operator/jobs/org/other/org-other-nonstandard-presubmits.yaml
test/integration/repo-init/expected/ci-operator/jobs/org/repo/org-repo-master-presubmits.yaml
test/integration/repo-init/expected/ci-operator/jobs/org/third/org-third-nonstandard-presubmits.yaml

Reverts openshift/ci-tools#2136
This change generates jobs with multiple branches which broke the rehearse tool.
```yaml
branches:
- ^master$
- ^master-
```
follow-up https://github.com/openshift/release/pull/20014

Revert "prowgen: generate stricter `branch:` stanzas for presubmits"

---

pkg/defaults/defaults.go
pkg/release/official/client.go
pkg/steps/release/import_release.go
test/e2e/simple/dynamic-releases.yaml
test/e2e/simple/e2e_test.go

Ref https://issues.redhat.com/browse/DPTP-2265
Makes us use a harcoded y-stream version of the `oc` image when importing a non-amd64 release as we can not resolve the correct one because we can not run the `cluster-version-operator` as it will be for the wrong arch

Release: Fix importing for non-amd64 architectures

---

pkg/steps/artifacts_test.go

https://issues.redhat.com/browse/DPTP-2354
I can reproduce the failure and verify the fix with:
```
go test -race -count=100 -run TestWaitForConditionOnObject  ./pkg/steps/
ok  	github.com/openshift/ci-tools/pkg/steps	41.790s
```

[DPTP-2354] Fix flaky test TestWaitForConditionOnObject

---

pkg/controller/test-images-distributor/test_images_distributor.go
pkg/controller/test-images-distributor/test_images_distributor_test.go

If there is a testimagestreamtagimport on app.ci that doesn't have the
cluster set, we will currently fail with `no client for cluster  available`
which is impossible to understand without looking at the code.
Ref https://issues.redhat.com/browse/DPTP-2373

Testimagedistributor: Log error and ignore requestst w/o cluster in app.ci

---

pkg/validation/config.go
pkg/validation/config_test.go
pkg/validation/test.go
pkg/validation/test_test.go

As seen in:
https://github.com/openshift/release/blob/7babc432cc74ce456a0a3c41919d0c9095dcfedc/ci-operator/config/redhat-et/microshift/redhat-et-microshift-main.yaml#L76
```
$ go run ./cmd/ci-operator-checkconfig --config-dir redhat-et/
ERRO[0000] Failed to load CI Operator configuration      error="invalid ci-operator config: invalid configuration: tests[2].as: duplicated name \"test-smoke\" already declared in 'images'" source-file=redhat-et/microshift/redhat-et-microshift-main.yaml
ERRO[0000]                                               error="error reading configuration files: invalid ci-operator config: invalid configuration: tests[2].as: duplicated name \"test-smoke\" already declared in 'images'"
FATA[0000] error validating configuration files
exit status 1
```

pkg/validation: reject duplicated image/test name

---

test/e2e/pod-scaler/e2e_test.go
test/e2e/pod-scaler/prometheus/backfill.go

This allows us to know ahead of time given a seed what the values will
be in Prometheus and therefore in the pod-scaler.
/assign @emilvberglind

e2e: backfill data into prometheus in a deterministic order

---

cmd/ci-operator/main.go
pkg/util/client.go

When we have a flag for which we only ever expect to load one
kubeconfig, it is not useful to use a loader that can manage multiple
files and multiple contexts.

util: add a function to load one kubeconfig

---

cmd/registry-replacer/main.go
cmd/registry-replacer/main_test.go
cmd/registry-replacer/testdata/zz_fixture_TestReplacer_Unused_base_images_are_pruned.yaml
test/validate-checkconfig.sh

/hold
Round 2 of the registry replacer changes. I _think_ this should now account for all of the scenarios, including the ones that were previously missed. Let me know if I missed anything.

DPTP-2244, DPTP-2345: Registry-replacer should prune unused base images.

---

pkg/steps/template.go

Ultimately, our hard time-out on waiting for a Pod to reach the Running
phase was written to catch issues like ImagePullBackOff which do not
terminate the Pod but do cause it to hang forever waiting for e.g.
credentials. This is a defense mechanism to ensure that jobs finish
running and not time out themselves. We do not need it to be very
efficient. We are currently killing Pods that took a while to start the
Pod sandbox with an overly agressive timeout.

ci-operator: wait for 30min before giving up on Pods

---

cmd/vault-subpath-proxy/kv_update_transport.go
cmd/vault-subpath-proxy/main.go
cmd/vault-subpath-proxy/main_test.go

This change makes the vault proxy check for conflicts and error if one is found.
Sample in the UI:
Ref https://issues.redhat.com/browse/DPTP-2206

Vault proxy: Validate key conflicts

---

cmd/vault-subpath-proxy/kv_update_transport.go
cmd/vault-subpath-proxy/main_test.go

As that defaults to '/' as target, so this can easily produce conflicts.
We already skip those when updating the cache, but not when validating.
This can result in pre-existing secrets ending up in the cache.

Subpath proxy: Don't validate secrets with no target

---

cmd/pod-scaler/admission.go
cmd/pod-scaler/consumer.go
cmd/pod-scaler/main.go
cmd/pod-scaler/resources.go

We were not correctly managing concurrency when loading data. This
resulted in incomplete loaded state for the first reload tick when very
small (short) data loads occurred, as in end-to-end tests.

pod-scaler: de-race startup

---

cmd/determinize-prow-config/main.go

Several notes:
- OCP repos are identified by a presence of a `group-lead-approved`-guarded `release-4.8` branch query
- OCP repos exempt from feature freeze process are allowlisted, and follow what was manually set up for openshift/builder repository: overlapping queries that merge either on valid bugs (one query) or three approvals (second query)
- Non-exempt repositories simply add valid-bug requirement for their master/main branch
The resulting configuration is unfornunately not in the canonical ordering (as all the sorting etc is done *before* the config is sharded, but we modify it on shard writes. You need to run `make prow-config` again after running this.

Abuse determinize-prow-config to implement 4.9 FF (no merge)

---

test/e2e/multi-stage/e2e_test.go

Due to https://coreos.slack.com/archives/CE3ETN3J8/p1627493669210600?thread_ts=1626290803.340800&cid=CE3ETN3J8
Those tests are blocking merging on the repo.

Disable e2e tests with claims

---

pkg/testhelper/accessory.go

We need to use a global marker of state to share the intent to use ports
as the in-memory lock we had in the past could not handle the case where
tests were run in parallel in separate processes.
This should fix a number of flakes in e2e

testhelper: use a file to share port state

---

test/e2e/multi-stage/e2e_test.go

We currently skip them too late, so we effectively still attempt to run
the defunct part.

Actually skip hive testcases

---

cmd/pod-scaler/admission.go
cmd/pod-scaler/admission_test.go
cmd/pod-scaler/main.go
cmd/pod-scaler/testdata/zz_fixture_TestMutatePodResources_resources_to_add__limits_disabled.diff
test/e2e/pod-scaler/run/consumer.go

The server is already configured to only override resource requests when
the suggested value is *larger* than that present in the Pod, so we risk
nothing by turning on resource request suggestion. Limits, on the other
hand, can cause Pod eviction and require more thought.

pod-scaler: mutate resource requests by default

---

cmd/vault-subpath-proxy/kv_update_transport.go
cmd/vault-subpath-proxy/main_test.go

Currently, the proxy would refuse all changes where a key in a vault
entry targets a kube secret that is already targeted. This unfortuantely
included the case where the key from the same vault entry got another
key, making it impossible to add additional keys to vault entries.
This change fixes that.
Ref https://issues.redhat.com/browse/DPTP-2416

Vault subpath proxy: Allow adding new values to secrets

---

pkg/api/domain.go
pkg/controller/test-images-distributor/test_images_distributor.go
pkg/controller/test-images-distributor/test_images_distributor_test.go

Using `Image.DockerImageReference` can ocasionally refer to an invalid
image, update the construction of the pull spec as advised by the image
registry team.
Ref https://issues.redhat.com/browse/DPTP-2421
/assign @emilvberglind

Testimagedistributor: Fix pull spec construction from istag

---

cmd/cvp-trigger/README.md
cmd/cvp-trigger/main_test.go
test/validate-checkconfig.sh
test/validate-prowgen-breaking-changes.sh

- rename: redhat-operator-ecosystem -> redhat-openshift-ecosystem
- Stop checking r-o-e config in CI jobs
We no longer have any production config in that repository, and there are no
immediate plans to start using it again, so we may as well stop special-casing
it. If we start using it, it will need a ton of more work anyways.
https://github.com/openshift/release/pull/20857 is the companion PR in o/release

Stop running checks against roe/release

---

pkg/validation/config.go
pkg/validation/config_test.go

Hit this case in a rehearsal:
```yaml
build_root:
image_stream_tag:
name: release
namespace: openshift
tag: golang-1.15
promotion:
additional_images:
cluster-api-actuator-pkg: src
name: "4.10"
namespace: ocp
resources:
'*':
requests:
cpu: 100m
memory: 200Mi
tag_specification:
name: "4.10"
namespace: ocp
zz_generated_metadata:
branch: release-4.10
org: openshift
repo: cluster-api-actuator-pkg
```
In theory we should check if referenced names exist but I think that
goes beyond basic validation.

ci-op validation: allow not having tests/images when promoting additional images

---

cmd/autoconfigbrancher/main.go
cmd/autoconfigbrancher/main_test.go

If one command does a change that then gets reverted by another one,
the autoconfigbrancher will create empty PRs.
This change detecs that and aborts the PR creation if it happens.
Ref https://issues.redhat.com/browse/DPTP-2394

Autoconfigbrancher: Don't create empty PRs

---

cmd/promoted-image-governor/main.go

promoted-image-governor: init k8s client when needed

---

pkg/api/types.go
pkg/jobconfig/files.go
pkg/jobconfig/files_test.go
pkg/prowgen/prowgen.go
pkg/prowgen/prowgen_test.go
pkg/prowgen/testdata/zz_fixture_TestGeneratePresubmitForTest_presubmit_with_run_if_changed.yaml
pkg/prowgen/testdata/zz_fixture_TestGeneratePresubmitForTest_presubmit_with_skip_if_only_changed.yaml
pkg/validation/test.go
pkg/validation/test_test.go
pkg/webreg/zz_generated.ci_operator_reference.go

This change exposes run_if_changed/skip_if only_changed in the
ci-operator config.
Ref https://issues.redhat.com/browse/DPTP-2301

CI-Operator: Expose run_if_changed/skip_if only_changed

---

pkg/load/agents/configAgent.go
pkg/load/agents/configAgent_test.go
pkg/prowgen/prowgen.go

https://github.com/openshift/ci-tools/pull/2199 changed feature branches in Prowgen, but there is a similar capability in config-resolver that needs to be changed too.
Fixes the following error in https://prow.ci.openshift.org/?job=*-release-4.10-images
```
ERRO[2021-08-05T11:12:39Z] Failed to load arguments.                     error=failed to load configuration: got unexpected http 404 status code from configresolver: failed to get config: found more than one matching config for branch release-4.10 on repo openshift/node-feature-discovery
```

Respect stricter feature branch names in config resolver

---

pkg/controller/serviceaccount_secret_refresher/serviceaccount_secret_refresher.go

[DPTP-2426](https://issues.redhat.com/browse/DPTP-2426): Ignore ErrNotExist as there could be a race condition where something else has already deleted the secret.

DPTP-2426: Ignore ErrNotExist

---

pkg/api/types.go

Our OpenStack cloud used for CI, named `mecha`, has now two availability
zones so we would like to have two different cluster profiles and quota
slices.
For that, we are adding them as new profiles, but we'll remove the
deprecated `openstack-vh-mecha` profile once we have switched our jobs
to use the new ones.

openstack: split "mecha" into two profiles & slices

---

cmd/ci-operator-checkconfig/main.go
cmd/pj-rehearse/main.go
cmd/registry-replacer/main.go
pkg/load/agents/registryAgent.go
pkg/load/load.go
pkg/load/load_test.go
pkg/rehearse/jobs_test.go
pkg/webreg/graphviz_test.go

All uses of the registry outside the agent ignore these, there is no reason
to store them in the first place.

pkg/load: add flags to load registry docs/metadata

---

pkg/steps/release/promote.go
pkg/steps/release/promote_test.go

Detected by flaky https://prow.ci.openshift.org/view/gs/origin-ci-test/pr-logs/pull/openshift_release/21008/pull-ci-openshift-release-openshift-image-mirror-mappings/1424844803387953152#1:build-log.txt%3A188
We do have it in the config:
https://github.com/openshift/release/blob/05f7e2b3bfd374f43fe98fdb6612a06eaf99d28e/ci-operator/config/openshift/images/openshift-images-release-4.6.yaml#L59-L65

Fix PromotedTags function: many to one

---

cmd/ci-operator-configresolver/main.go
pkg/webreg/webreg.go
test/integration/ci-operator-configresolver.sh
test/integration/ci-operator-configresolver/configs/master/openshift-release-master__ci-4.9.yaml
test/integration/ci-operator-configresolver/configs/release-4.2/openshift-installer-release-4.2.yaml
test/integration/ci-operator-configresolver/expected/openshift-installer-release-4.2-injected.json

Builds over https://github.com/openshift/ci-tools/pull/2193 and adds a new `/configWithInjectedTest` endpoint that uses serves configs created by code https://github.com/openshift/ci-tools/pull/2193 . I was deciding between adding a new endpoint and just adding new set of query inputs to the existing `/config` one, but I think I will want to add more injection behavior in the future ("inject test with workflow X from the registry") so I think separate endpoint is better.

configresolver: add an endpoint to inject a test into a config

---

pkg/registry/graph.go

Catching up with dd11c766ed (#818).

pkg/registry/graph: Fix "set of strings" -> "set of nodes" typo

---

cmd/ci-operator-prowgen/main.go
cmd/ci-operator-prowgen/main_test.go
pkg/prowgen/prowgen.go
test/integration/ci-operator-prowgen.sh
test/integration/ci-operator-prowgen/input/config/super/duper/super-duper-master.yaml
test/integration/ci-operator-prowgen/input/registry/workflow/workflow-workflow.yaml
test/integration/ci-operator-prowgen/output/jobs/super/duper/super-duper-master-presubmits.yaml

`prowgen` needs to resolve the configurations it loads in order to make
decisions based on fields declared in the step registry.
Neither job generation nor execution time are affected for the
configuration in `openshift/release`.

ci-operator-prowgen: resolve configurations

---

cmd/ci-operator/main.go
cmd/ci-operator/main_test.go
pkg/api/metadata.go
pkg/load/load.go
pkg/load/load_test.go

`ResolverInfo` contains the same data with the same semantics, so using `api.Metadata` will allow using its helpders when working with resolver info

Embed `api.Metadata` in `ResolverInfo`

---

cmd/ci-operator/main.go
pkg/api/graph.go
pkg/defaults/defaults.go
pkg/defaults/defaults_test.go

Extract the static parts of the function which transforms the input
configuration into step configuration so it can be built and used for
validation.
Another subset of https://github.com/openshift/ci-tools/pull/2213.

pkg/defaults: split configuration parsing

---

cmd/ci-operator-checkconfig/main.go
cmd/ci-operator/main.go
pkg/validation/graph.go
pkg/validation/graph_test.go

One unfortunate aspect of the current static validation is that it is done
on the unprocessed input configuration.  This results in significant
duplication between validation and parsing code.  This change attempts to
move to a more tenable position by performing validation on the graph
configuration structures, which are much closer to the final execution
graph.
https://issues.redhat.com/browse/DPTP-2388 is implemented in this change as
well as a PoC.
---
Use the naming methods and graph configuration data added in the previous
commits to validate that all targets in a `ci-operator` configuration are
unique.
Add this validation to the configuration loading process in
`ci-operator` and make `checkconfig` build and validate the static portion
of the graph.
/hold
built on top of / includes …

pkg/validation: validate targets are unique

---

cmd/private-prow-configs-mirror/main.go
pkg/jobconfig/files.go
pkg/jobconfig/files_test.go
pkg/prowgen/prowgen.go
pkg/prowgen/testdata/zz_fixture_TestGeneratePresubmitForTest_presubmit_with_run_if_changed.yaml
pkg/prowgen/testdata/zz_fixture_TestGeneratePresubmitForTest_presubmit_with_skip_if_only_changed.yaml

Conditionally triggered jobs (ones with `run_if_changed` and `skipIfOnlyChanged`) need to be generated as `always_run: false` to beconsistent.
Followup to https://github.com/openshift/ci-tools/pull/2221

prowgen: generate conditionally triggered jobs correctly

---

images/ci-operator-checkconfig/Dockerfile
images/ci-operator-prowgen/Dockerfile
images/determinize-ci-operator/Dockerfile

follow-up of https://github.com/openshift/ci-tools/pull/2137
In order to use the new feature that was added in https://github.com/openshift/ci-tools/pull/2137, the images need to have the `git` command.

Add git command to determinize-ci-operator,ci-operator-prowgen,ci-operator-checkconfig images

---

cmd/pod-scaler/frontend.go
cmd/pod-scaler/frontend/webpack.common.js
test/e2e/pod-scaler/local/main.go

We need the default handler to always give the user our single-page app,
so that our React routing can handle the path. We prefix our static
content in Webpack and then un-prefix it in the server so that we know
which files should be coming from the embedded filesystem.
Fixes [DPTP-2447](https://issues.redhat.com/browse/DPTP-2447)
/assign @emilvberglind

pod-scaler: frontend: correctly serve content

---

cmd/registry-replacer/main.go
cmd/registry-replacer/main_test.go

Update the `registry-replacer` to take into account additional input images that were previously missed.

Take into account additional raw_steps that were missed.

---

pkg/api/types.go
pkg/prowgen/prowgen.go
pkg/validation/test.go

The cluster profile is not needed, since we merged:
https://github.com/openshift/release/pull/21073

Remove deprecated cluster_profile for OpenStackMecha

---

pkg/api/types.go
pkg/validation/test.go

We need to add new secrets for the Edge team Equinix/Packet accounts. The cluster type should still be the same and the leases should be shared.

Add Packet cluster profiles for the Edge team

---

pkg/prowgen/prowgen.go

exlude packet from mounting any cluster-profiles config map

---

cmd/sprint-automation/main.go

Once an issue left TODO, it is implicit that it was ready to work on.
Ref https://issues.redhat.com/browse/DPTP-2465

Sprint automation: Only consider TODO issues

---

pkg/vaultclient/vaultclient.go

For the refresh request we must not use a token. To achieve that, we
currently remove the token for the entire vault client during refresh,
even though it is still valid.
This change makes the refreshing construct its private client copy and
only manipulate that.
Ref https://issues.redhat.com/browse/DPTP-2462

Vault: Don't remove current token during refresh

---

pkg/config/release.go
pkg/load/load.go

2a31056baf (#1776) pivoted to directly executing command files allowing non-shell via shebangs.  But writing Python in a file with a `*.sh` extension isn't all that intuitive, and also confuses some editors.  This commit softens things to allow any extension.
Ideally we'd load the reference YAML and [pull commands out of there][1].  This would require some rewrites, since a bunch of these existing handlers are file-based, with `GetChangedRegistrySteps` logic like:
1. Get a set of changed files.
2. Iterate over the files to see if they seem to match a step.
3. Return any identified steps.
Instead we'd want:
1. Get a set of changed files.
2. Iterate over the nodes in the registry.
3. For each node, get the set of files consumed (e.g. both the ref YAML and command file for a reference step). …

pkg: Allow alternative reference-step command file extensions

---

cmd/dptp-controller-manager/main.go
cmd/dptp-pools-cm/main.go
cmd/promoted-image-governor/main.go

```
$ oc --context app.ci --namespace ci logs --selector app=dptp-controller-manager --tail=-1
flag provided but not defined: -github-endpoint
```
The fix is in the 2nd commit.

Fix not defined: -github-endpoint

---

pkg/validation/test.go
pkg/validation/test_test.go

- Validate `secret/secrets` usage on non-container tests
- ci-op validation: improve tests and fix nits

Disallow `secrets` in non-container tests, improve validation tests

---

pkg/jobconfig/files.go

Uses the same diamond fork-join pattern as `ci-operator-checkconfig`.
See https://github.com/openshift/ci-tools/pull/2304.

pkg/jobconfig: load in parallel

---

pkg/api/types.go
pkg/prowgen/prowgen.go

We actually need different secrets for the new packet cluster profiles.

Use different secrets and leases for new packet cluster profiles

---

hack/revert-any-ci-image.sh
hack/revert-ci-operator.sh

- Use to revert any image, not just ci-operator
- Execute the command directly instead of just printing it

Generalize image revert script

---

pkg/api/types.go

Seeing the following errors in boskos log:
```
msg=Acquire failed, error=resource type "packet-edge-qouta-slice" does not exist
```
The actual boskos config has this right:
https://github.com/openshift/release/blob/72dd5cea7b39ec1c03865000f2dce64cad1cc71e/core-services/prow/02_config/generate-boskos.py#L71-L73

Fix typo in packet-edge boskos slice name

---

cmd/pod-scaler/admission.go
cmd/pod-scaler/admission_test.go
pkg/testhelper/testhelper.go
pkg/testhelper/testhelper_test.go

With a better understanding of what is erroring we can determine when we
should just ignore this.
/assign @openshift/test-platform

pod-scaler: admission: improve error messages for rehearsals

---

cmd/pod-scaler/admission.go
cmd/pod-scaler/consumer.go
cmd/pod-scaler/frontend.go
cmd/pod-scaler/resources.go

In dptp-triage tooling, `component` is usually the high-level component that emitted an error, and e.g. `admission` is not high-level component. Alternatively, we could set `component` to `pod-scaler` in all these and use something like `subcomponent` but IMO this has better UX

pod-scaler: improve component labels in logs

---

Makefile
cmd/promoted-image-governor/main.go

Follow up https://issues.redhat.com/browse/DPTP-2472?focusedCommentId=18930981&page=com.atlassian.jira.plugin.system.issuetabpanels%3Acomment-tabpanel#comment-18930981
```
I0902 17:41:56.744282   56701 request.go:665] Waited for 1.137930975s due to client-side throttling, not priority and fairness, request: GET:https://api.ci.l2s4.p1.openshiftapps.com:6443/apis/hiveinternal.openshift.io/v1alpha1?timeout=32s
tag               explanation
ci/applyconfig:latest openshift/ci-tools@master
```
We still have the above log and i feel it is hard to remove that
```
rg "due to client-side throttling"
vendor/k8s.io/client-go/rest/request.go
593:            message = fmt.Sprintf("Waited for %v due to client-side throttling, not priority and fairness, request: %s:%s", latency, r.verb, …
```

promoted-image-governor: less verbose while explaining

---

cmd/clusterimageset-updater/main.go
test/integration/clusterimageset-updater/input/imagesets/ocp-release-4.5.40-x86_64-for-4.5.0-0-to-4.6.0-0_clusterimageset.yaml
test/integration/clusterimageset-updater/input/imagesets/ocp-release-sha256-2c22e1c56831935a24efb827d2df572855ccd555c980070f77c39729526037d5-for-4.5.0-to-4.6.0_clusterimageset.yaml
test/integration/clusterimageset-updater/input/pools/4-5-auto_clusterpool.yaml
test/integration/clusterimageset-updater/output/imagesets/ocp-release-4.5.41-x86_64-for-4.5.0-0-to-4.6.0-0_clusterimageset.yaml
test/integration/clusterimageset-updater/output/pools/4-5-auto_clusterpool.yaml

Since label values in k8s can only contain alphanumerics, '-', '_', and
'.', the previous `version_in` label used by the imageset updater
required invalid k8s objects. To solve this, this PR changes the updater
to use 2 labels instead, `version_lower` and `version_upper`. This fixes
the label issue and also somewhat simplifies the code.

clusterimaget-updater: change version labels

---

pkg/api/types.go
pkg/defaults/defaults.go
pkg/steps/project_image.go
pkg/steps/release/create_release.go
pkg/steps/release/snapshot.go
pkg/validation/release.go
pkg/validation/release_test.go
test/e2e/multi-stage/assembled-release-no-injection.yaml
test/e2e/multi-stage/assembled-release.yaml
test/e2e/multi-stage/e2e_test.go

Previously, we always did this for integration releases with the
`latest` name. This is hard(er) to document and annoying to reason
about, so we should expose this as an option.
/assign @bbguimaraes @petr-muller @emilvberglind

ci-operator: include images into release explicitly

---

images/clusterimageset-updater/Dockerfile

This PR adds the diffutils package to the `clusterimagset-updater` image
to allow the image to be used for validation presubmits.

clusterimageset-updater: add diffutils to image

---

cmd/pod-scaler/frontend.go
cmd/pod-scaler/main.go
test/e2e/pod-scaler/run/consumer.go

We don't need the speed of main memory for this, so just write things to
disk.

pod-scaler: ui: store data in files, not memory

---

pkg/jobconfig/files.go

If either of these is set on ci-operator level, *both* ones must not be manually changed in the job (otherwise we may end up with a job having both).

Tolerate neither of `skip_if/run_if` changes in jobs if one is set in ci-op config

---

pkg/validation/test.go
pkg/validation/test_test.go

>  The only requirement for mount paths is they should be absolute. That is tested correctly for credentials (validateCredentials in the same file) and is what should be done here too, IMO.
There's a test for absolute-ness of the mount path even for secrets (valid secret with invalid path), so the test just needs to be deleted, then.
Followup to https://github.com/openshift/ci-tools/pull/2293
/cc @bbguimaraes @stevekuznetsov

validate: remove wrong test and improve message

---

cmd/repo-init/main.go
cmd/repo-init/main_test.go
test/integration/repo-init/expected/ci-operator/config/org/other/org-other-nonstandard.yaml
test/integration/repo-init/expected/ci-operator/config/org/repo/org-repo-master.yaml
test/integration/repo-init/expected/ci-operator/jobs/org/repo/org-repo-master-presubmits.yaml

Part of [DPTP-2431](https://issues.redhat.com/browse/DPTP-2431)
/assign @emilvberglind

repo-init: use releases.integration instead of tag_spec

---

pkg/api/types.go
pkg/prowgen/prowgen.go
pkg/validation/test.go

vsphere use network segment as lease resource, in order to test disconnected ocp installation on vsphere (require machines in network segment unable to access to network), add new disconnected network segments as lease resources

Add ClusterProfileVSphereDiscon

---

cmd/branchingconfigmanagers/schedule-generator/main.go
cmd/branchingconfigmanagers/schedule-generator/main_test.go
cmd/branchingconfigmanagers/schedule-generator/testdata/schedules/4.1.yaml
cmd/branchingconfigmanagers/schedule-generator/testdata/schedules/4.2.yaml
cmd/branchingconfigmanagers/schedule-generator/testdata/schedules/4.3.yaml
cmd/branchingconfigmanagers/schedule-generator/testdata/zz_fixture_TestReadSchedules.yaml
cmd/branchingconfigmanagers/schedule-generator/types.go
cmd/branchingconfigmanagers/schedule-generator/types_test.go

This will run on the schedules provided by the PM team to generate the
data our tools expect to operate on, committing it to build farms in a
config map for easy loading.
/assign @petr-muller @alvaroaleman

branching: add a schedule generator utility

---

pkg/controller/test-images-distributor/test_images_distributor.go
pkg/controller/test-images-distributor/test_images_distributor_test.go

We have handled it in the reconcile function:
https://github.com/openshift/ci-tools/blob/f96d4cad19030ad3fb827b55966869a78dca0154/pkg/controller/test-images-distributor/test_images_distributor.go#L292-L295
However, the requests should not even be generated in the first place.

test-images-distributor: stop generating requests for disabled clusters

---

test/e2e/lease/config.yaml
test/e2e/multi-stage/assembled-release-no-injection.yaml
test/e2e/multi-stage/assembled-release.yaml
test/e2e/multi-stage/best-effort.yaml
test/e2e/multi-stage/cluster-claim.yaml
test/e2e/multi-stage/config.yaml
test/e2e/multi-stage/configs/master/..2019_11_15_19_57_20.547184898/test-test-master.yaml
test/e2e/multi-stage/dependencies.yaml
test/e2e/multi-stage/integration-releases.yaml
test/e2e/multi-stage/names.yaml
test/e2e/optional-operators/optional-operators.yaml
test/e2e/simple/config.yaml
test/e2e/simple/dynamic-releases.yaml
test/e2e/simple/template-config.yaml

Resource limits should not be set in ci-op configs. This PR removes the
resources limit from all ci-op configs used in the e2e tests.

test/e2e: remove resource limits in ci-op configs

---

cmd/pod-scaler/frontend.go
cmd/pod-scaler/frontend_test.go

We only want to show a minimal set of fields to the UI for selecting the
correct background data, allowing the views to omit things that are not
important in the context of a specific type of data (pods, RPMs, etc).
We need to ensure that all of these transforms round-trip correctly.

pod-scaler: fix a round-tripping bug in the UI

---

test/e2e/simple/artifacts/junit_operator.xml
test/e2e/simple/dynamic-releases.yaml
test/e2e/simple/e2e_test.go
test/e2e/simple/template-config.yaml

We are hitting a consistency problem in the 4.5 imagestream, likely caused by recent pruning of the images:
```
error: unable to create a release: operator "cluster-node-tuning-operator" contained an invalid image-references file: no input image tag named "cluster-node-tuned"
```
This also happens in r-c, see https://amd64.ocp.releases.ci.openshift.org/#4.5.0-0.ci
There is no reason why our PRs should be blocked on this, let's use a current version for our tests. 4.5 is EOL and apparently nobody even cares about this failure showing up in r-c for 4 weeks.

e2e: stop using obsolete OCP in simple tests

---

cmd/branchingconfigmanagers/README.md

This document attempts to describe the contract/conventions for all
config managers, so individual cards do not need to repeat the contract.
Not sure if this is the right place, I'll gladly move it somewhere else if needed.
[DPTP-2440](https://issues.redhat.com/browse/DPTP-2440)

Add a README for config manager authors

---

pkg/steps/run_test.go

https://issues.redhat.com/browse/DPTP-2351
This test case cannot be structured as it is because the code it tests
is based on a `select` statement:
https://github.com/openshift/ci-tools/blob/f8fac1599dad2eeb98b1771c9e4ced716d1f0364/pkg/steps/run.go#L49
In the (very unlikely, but seen repeatedly in CI) scenario that the
statement chooses to keep processing steps before acknowledging the
cancellation, the extra error will be reported.  This can be simulated
with the following code, which fails in the same manner 100% of the
time on my machine (it otherwise never fails):
```diff
var executionErrors []error
var stepDetails []api.CIOperatorStepDetails
for {
+		for i := 0; i < 5; i++ {
+			select {
+			case out := <-executionResults:
…
+			case <-done:
…
+			}
+		}
select {
case <-ctxDone: …
```

pkg/steps: remove unreliable test

---

pkg/jobrunaggregator/jobrunaggregatorapi/gcs_jobrun.go
pkg/jobrunaggregator/jobrunbigqueryloader/uploader.go

found as 
> jobRun/\"release-openshift-ocp-installer-e2e-metal-serial-4.10\"/\"1440877727593795584\" failed to upload to bigquery: error parsing junit for \"1440877727593795584\" \"logs/release-openshift-ocp-installer-e2e-metal-serial-4.10/1440877727593795584/artifacts/e2e-metal-serial/junit/junit_install_status.xml\": EOF
on the dpcr cluster.
/assign @dgoodwin

skip empty files for junit aggregation

---

pkg/jobrunaggregator/jobrunaggregatoranalyzer/analyzer.go
pkg/jobrunaggregator/jobrunaggregatoranalyzer/types.go

if job runs have timed out, we can ignore them for the purposes of aggregation.  This only becomes a practical problem if the jobs start running very very long.

ignore jobs we're aggregating that time out

---

pkg/jobrunaggregator/jobrunaggregatoranalyzer/pass_fail.go

the additional details of historical pass rate are helpful to humans inspecting the output.
/assign @bparees

provide more context on aggregated test success

---

cmd/bugzilla-backporter/main.go
pkg/backporter/backporter.go
pkg/backporter/backporter_test.go

https://issues.redhat.com/browse/DPTP-2524
The introduction of 4.10 means that string based sort was no longer
successfully sorting target_releases correctly. Versions are now
parsed and sorted according to semver.

Bugzilla backporter should sort semantically

---

cmd/sprint-automation/main.go

It's useful when I'm breaking something down into cards, top-down. I don't
necessarily want to do it all at once. This label means I take responsibility
to finalize the card for intake to review it.

sprint-automation: allow hiding issues from intake

---

OWNERS

This change will avoid selecting Steve, Alvaro and Alex from being assigned to PRs.

Set DPTP as exclusive reviewers

---

cmd/ci-operator/main.go

We have noticed that sometimes 31 seconds isn't enough , which can be
caused to some networking downtime, or just a service maintenance.
We think that 120s (2 min) is a good timeout value to wait for the
secrets to be available and after that raise an error.
We hope that this will cause less flaking errors in our CI jobs, when
pulling image secrets.
Example of the error:
```
[31mERRO[0m[2021-10-01T02:41:04Z] Timed out waiting for image pull secrets in the test namespace.
[36mINFO[0m[2021-10-01T02:41:04Z] Ran for 31s
[31mERRO[0m[2021-10-01T02:41:04Z] Some steps failed:
[31mERRO[0m[2021-10-01T02:41:04Z]
* could not initialize namespace: timed out waiting for image pull secrets
```

Increase timeout for pulling image secrets

---

pkg/jobrunaggregator/jobrunaggregatoranalyzer/pass_fail.go

This test is a side-effect of other tests.  For the purpose of aggregation, we can have each individual job run fail this test, but the aggregated output can be successful.

ignore aggregation result for generic upgrade test run

---

cmd/ci-operator/main.go
cmd/ci-operator/main_test.go

- remove the loop on authors: this bug should have been there before the group support feature. This should help https://coreos.slack.com/archives/CEKNRGF25/p1633445908185500
- handle the duplicated authors. https://gcsweb-ci.apps.ci.l2s4.p1.openshiftapps.com/gcs/origin-ci-test/logs/release-openshift-origin-installer-launch-gcp/1445412322951565312/artifacts/initial/ci-operator.log Not sure where the authors came from though.

ci-op: fix rolebinding/ci-op-author-access creating

---

cmd/testgrid-config-generator/main.go

We add QE's tests into `_allow-list.yaml` in https://github.com/openshift/release/pull/21706
but it is failing with `unrecognized release type in job` in https://prow.ci.openshift.org/log?job=periodic-prow-auto-testgrid-generator&id=1446264366310625280

Add QE's e2e tests into testgrid

---

cmd/cluster-init/main.go
cmd/cluster-init/update_bootstrap_secrets.go
test/integration/cluster-init/create/expected/core-services/ci-secret-bootstrap/_config.yaml
test/integration/cluster-init/create/input/core-services/ci-secret-bootstrap/_config.yaml
test/integration/cluster-init/update/expected/core-services/ci-secret-bootstrap/_config.yaml
test/integration/cluster-init/update/input/core-services/ci-secret-bootstrap/_config.yaml

Found the issue while working on https://github.com/openshift/release/pull/22861
```console
$ cluster=build03 make config_updater_vault_secret
...
{"component":"ci-secret-generator","error":"could not find context {build_farm sa.promoted-image-governor.build03.config [] false} in bootstrap config","file":"/go/src/github.com/openshift/ci-tools/cmd/ci-secret-generator/main.go:195","func":"main.main","level":"error","msg":"Invalid entry","severity":"error","time":"2021-10-20T13:14:19Z"}
```

cluster-init: updatePromotedImageGovernor

---

cmd/ci-operator/main.go
cmd/ci-operator/main_test.go
pkg/api/graph.go
pkg/api/graph_test.go
pkg/steps/run.go

pkg/api: introduce names for step lists
The `[]*StepNode` type is used in several places to mean either a graph
(list of root vertices) or a flat list (topologically sorted).  This
commits gives these two distinct types.
---
Revert "Avoid printing error for step whose dependency lacks a dependency"
This reverts commit c675c3c4d3b86ad47a368ccb9e98abf34e501d04.
---
ci-operator: move `TopologicalSort` to `pkg/api`
---
Includes https://github.com/openshift/ci-tools/pull/2435.
https://issues.redhat.com/browse/DPTP-2261

ci-operator: actually order topologically

---

cmd/ci-operator/main.go
cmd/ci-operator/main_test.go
pkg/api/graph.go
pkg/api/graph_test.go
pkg/steps/run.go

---
Some cases are already incidentally detected (from [DPTP-2261](https://issues.redhat.com/browse/DPTP-2261)):
```yaml
build_root:
image_stream_tag: {name: release, namespace: openshift, tag: golang-1.15}
images:
- {from: root, to: root}
resources: {'*': {requests: {cpu: 200m, memory: 200Mi}}}
```
```
$ ci-operator --unresolved-config config.yaml
INFO[2021-10-15T19:48:12Z] unset version 0
ERRO[2021-10-15T19:48:13Z] Failed to load arguments.                     error=invalid configuration: images[0]: duplicate image name 'root' (previously defined by field 'build_root')
```
But others are still possible:
```yaml
build_root:
image_stream_tag: {name: release, namespace: openshift, tag: golang-1.15}
images:
- {from: i2, to: i0}
- {from: i0, to: i1}
- {from: i1, to: i2}
resources: {'*': …
```

ci-operator: detect cycles in the execution graph

---

pkg/api/config.go
pkg/api/config_test.go

`releases.latest` serves as an installation or upgrade target, so we must respect its definition in the base in order to correctly build the ephemeral release including the images built in the tested PR

test injection: respect `releases.latest` in the base

---

cmd/branchingconfigmanagers/schedule-generator/main.go
cmd/branchingconfigmanagers/schedule-generator/main_test.go
cmd/branchingconfigmanagers/schedule-generator/testdata/schedules/4.1.yaml
cmd/branchingconfigmanagers/schedule-generator/testdata/schedules/4.2.yaml
cmd/branchingconfigmanagers/schedule-generator/testdata/schedules/4.3.yaml
cmd/branchingconfigmanagers/schedule-generator/testdata/zz_fixture_TestReadSchedules.yaml
cmd/branchingconfigmanagers/schedule-generator/types.go
cmd/branchingconfigmanagers/schedule-generator/types_test.go
pkg/api/ocplifecycle/ocplifecycle.go

This PR adds adds the ability in the tool to validate the schedule configuration. There is also some refactoring that removes the duplicated types and the mapping and uses the general types in ocplifestyle instead.
For better reviewing, enable `Hide whitespace` option.

[schedule-generator] add the ability to validate the schedule configuration

---

cmd/cvp-trigger/README.md
cmd/cvp-trigger/main.go
cmd/cvp-trigger/main_test.go

Add a new parameter "CUSTOM_SCORECARD_TEST" as a optional parmeter to the CVP trigger.

[CVP-2390] Add a new parameter CUSTOM_SCORECARD_TEST to CVP trigger.

---

cmd/clusterimageset-updater/main.go

The updater previously contained an optimization that avoided updating
pools when a matching `ClusterImageSet` is up-to-date. This optimization
also skips reconciling the pool when it should be using such
clusterimageset but is not for any reason.
Remove this optimization: worst case is reading and writing several manifest files.
This fixes not updating hypershift pools after https://github.com/openshift/release/pull/23027 :
```diff
diff --git a/clusters/hive/pools/hypershift/hypershift-ocp-4-8-0-amd64-aws-us-east-1_clusterpool.yaml b/clusters/hive/pools/hypershift/hypershift-ocp-4-8-0-amd64-aws-us-east-1_clusterpool.yaml
index 602ca3e18d..20f7c21388 100644
--- a/clusters/hive/pools/hypershift/hypershift-ocp-4-8-0-amd64-aws-us-east-1_clusterpool.yaml
+++ …
```

clusterimageset-updater: always reconcile pools

---

cmd/job-trigger-controller-manager/main.go
pkg/api/pullrequestpayloadqualification/v1/types.go
pkg/api/pullrequestpayloadqualification/v1/types_test.go
pkg/controller/prpqr_reconciler/pjstatussyncer/pjstatussyncer.go
pkg/controller/prpqr_reconciler/pjstatussyncer/pjstatussyncer_test.go
pkg/controller/prpqr_reconciler/prpqr_reconciler.go
pkg/controller/prpqr_reconciler/prpqr_reconciler_test.go

The tool includes two controllers. The `prpqr_reconciler` is responsible to watch create events for `prpqr` objects. It generates the corresponding `prowjobs` and updates the Status of the `prpqr` object.
The `prowjob_status_syncer` controller is responsible to watch `prowjobs` update events that hold the `pullrequestpayloadqualificationruns.ci.openshift.io` label, and updating the status in the corresponding `prpqr` object.

[DPTP-2541] Initial implementation of the job-trigger-controller-manager

---

pkg/api/constant.go
pkg/steps/multi_stage.go
pkg/steps/multi_stage_test.go
pkg/steps/testdata/zz_fixture_TestGeneratePods.yaml
pkg/validation/config.go
pkg/validation/config_test.go
test/e2e/multi-stage/config.yaml
test/e2e/multi-stage/e2e_test.go

Allowing for the increase in shm-size to facilitate passing Selenium tests for the QE effort.
Following the implementation details from: https://docs.google.com/document/d/1jfgIBqND5DtuzJY9nJG9G9FeHoDqqqqDl8H3ZU2QT7k/edit#heading=h.66y4kqbj468a

Allow for configurable shm-size

---

cmd/payload-testing-prow-plugin/filetestresolver.go
cmd/payload-testing-prow-plugin/filetestresolver_test.go
cmd/payload-testing-prow-plugin/main.go

With the agent, we get the reload for free upon the changes of configs on files which come from a configMap.

payload-testing-prow-plugin: use configAgent to load configs

---

cmd/cluster-init/main.go
cmd/cluster-init/update_jobs.go
pkg/jobconfig/files.go
pkg/load/agents/configAgent.go
pkg/prowgen/prowgen.go
test/integration/cluster-init/create/expected/ci-operator/jobs/openshift/release/openshift-release-master-postsubmits.yaml
test/integration/cluster-init/create/expected/ci-operator/jobs/openshift/release/openshift-release-master-presubmits.yaml
test/integration/cluster-init/update/expected/ci-operator/jobs/openshift/release/openshift-release-master-postsubmits.yaml
test/integration/cluster-init/update/expected/ci-operator/jobs/openshift/release/openshift-release-master-presubmits.yaml

- Extract brancher regex utility code from prowgen
- cluster-init: generate jobs with explicit branchers
Make cluster-init jobs to generate jobs with explicit brancher stanza, to be
consistent with prowgen jobs, and to allow enforcing explicit regex stanzas
everywhere.
xref: https://github.com/openshift/release/pull/23380

cluster-init: generate jobs with explicit branchers

---

pkg/jobrunaggregator/jobrunaggregatorapi/bypass_linter.go
pkg/jobrunaggregator/jobrunaggregatorapi/types.go
pkg/jobrunaggregator/jobrunaggregatorapi/types_row_backenddisruption.go
pkg/jobrunaggregator/jobrunaggregatorapi/types_row_jobrun.go
pkg/jobrunaggregator/jobrunaggregatorlib/big_query.go
pkg/jobrunaggregator/jobrunaggregatorlib/ci_data_client.go
pkg/jobrunaggregator/jobrunaggregatorlib/jobrun_locators.go
pkg/jobrunaggregator/jobrunbigqueryloader/cmd.go
pkg/jobrunaggregator/jobrunbigqueryloader/summarize_results.go
pkg/jobrunaggregator/jobrunbigqueryloader/types.go
pkg/jobrunaggregator/jobrunbigqueryloader/uploader.go

This allows us to treat the jobrun entry as authoritative during upload so that we avoid duplicate rows for job runs and become much more efficient.

move disruption job runs to its own table

---

cmd/sanitize-prow-jobs/main.go
test/validate-generation-breaking-changes.sh

Brancher items are (suprisingly) regexes that make jobs trigger on
submatch, which causes trouble e.g. by making a:
```yaml
branches:
- release-4.1
```
job to trigger on `release-4.10` branch PRs. We deal with this in
generated jobs by generating appropriate explicit brancher stanzas, but
handcrafted jobs flew under the radar.
We can use `sanitize-prow-jobs` to enforce this on handcrafted jobs,
too.
/cc @hongkailiu 
Needed for [DPTP-2605](https://issues.redhat.com/browse/DPTP-2605)
This is expected to break the `breaking-changes` job until https://github.com/openshift/release/pull/23380 is merged

sanitize-prow-jobs: enforce explicit regex branchers

---

pkg/jobrunaggregator/jobrunaggregatorapi/types_row_release.go
pkg/jobrunaggregator/releasebigqueryloader/changelog_parser.go
pkg/jobrunaggregator/releasebigqueryloader/changelog_parser_test.go
pkg/jobrunaggregator/releasebigqueryloader/cmd.go
pkg/jobrunaggregator/releasebigqueryloader/release_uploader.go
pkg/jobrunaggregator/releasebigqueryloader/types.go

This adds support for multi-arch (s390x and arm64), as well as
collecting the X.Y release in addition to the tag (for easier
use with Sippy).
Usage:
```
$ job-run-aggregator upload-releases --bigquery-dataset ci_data --google-service-account-credential-file <creds.json> --releases 4.10.0-0.nightly --releases 4.10.0-0.ci --releases 4.9.0-0.nightly --releases 4.9.0-0.ci --releases 4.8.0-0.nightly --releases 4.8.0-0.ci --architectures amd64 --architectures arm64 --architectures s390x
```

Collect additional info for release tables

---

pkg/prowgen/podspec.go
pkg/prowgen/podspec_test.go
pkg/prowgen/testdata/zz_fixture_TestCustomHashInput_custom_hash_input_is_added.yaml
pkg/prowgen/testdata/zz_fixture_TestCustomHashInput_custom_hash_inputs_are_added.yaml

Needed to be able to generate jobs that do not share namespaces on identical inputs

prowgen podspec builder: new `CustomHashInput()` method

---

cmd/testgrid-config-generator/main.go

Removing the need for manually adding multiarch jobs to the testgrid allow_list

Updating informing logic to include multiarch jobs

---

go.mod
pkg/jobrunaggregator/jobrunaggregatorapi/types_row_release.go
pkg/jobrunaggregator/releasebigqueryloader/release_uploader.go

- Add more comments
- Collect stream ("nightly", or "ci"), and timestamp for a release tag
- Remove bigquery types all together and use native go types for time and int

Collect some additional data in our bigquery release tables

---

pkg/registry/resolver.go
pkg/registry/resolver_test.go
pkg/registry/stack.go

This change makes validation accept a tricky corner case with workflows:
- a step declares a parameter (e.g. the `openshift-e2e-test` step
declares `TEST_SKIP`)
- a workflow sets a value for that parameter (e.g. the
`openshift-e2e-vsphere` workflow uses `TEST_SKIP` to always skip a
suite in vSphere tests)
- a test uses the workflow, but replaces the chain that contains the
step (e.g. the `e2e-vsphere-operator` uses `openshift-e2e-vsphere`
with its own `test` chain)
Currently, this results in a validation error since the resulting
configuration's `env` section, inherited from the workflow, contains a
parameter that is not declared in any step.  It cannot be cleared in the
test's `env` section since mapping fields are merged, not overridden,
during resolution.  The only solution is to …

pkg/registry: ignore errors for overridden chains

---

pkg/controller/prpqr_reconciler/pjstatussyncer/pjstatussyncer.go
pkg/controller/prpqr_reconciler/prpqr_reconciler.go

Regarding https://pkg.go.dev/k8s.io/client-go/util/retry#RetryOnConflict we need to get first the object before trying to update

[job-trigger-controller-manager] Get the prpqr objects before trying to update

---

cmd/payload-testing-ui/server.go

The URL in the status is filled by `plank` after the creation of the
`ProwJob`, so it may be empty while the test is scheduled.

payload-testing-ui: check presence of status URL

---

pkg/jobrunaggregator/jobrunaggregatoranalyzer/analyzer.go

some jobs we're aggregating are taking the full 4h to fail. This lets the aggregator wait longer.
Will be leveraged in https://github.com/openshift/release/pull/23559

base the aggregator wait time on the timeout and allow long durations

---

cmd/payload-testing-prow-plugin/server.go

We bumped logging to debug, and now we log every comment on everything. Downgrade logs that say 'this event is not interesting for this plugin' to `Trace`

prpqr plugin: downgrade several log events to `Trace`

---

pkg/defaults/defaults.go

Due to rare protocol errors, a standard HTTP client is exchanged with a retriable HTTP client. To keep compatibility, after creating a retriable client, it is converted to the standard client with a custom transport.
An alternative approach to this problem would be to inject a custom transport to the standard HTTP client (which is exactly what a retriable HTTP client does).
Logger is nulled similarly to pkg/github/github.go

Change http client to http client with retry options

---

pkg/jobrunaggregator/jobrunaggregatorapi/gcs_jobrun.go
pkg/jobrunaggregator/jobrunaggregatorapi/interfaces.go
pkg/jobrunaggregator/jobrunbigqueryloader/disruption.go

This lets us add disruption tests in origin and have them reported without change the code in the aggregator.
I left the old code in to gather data from pre-4.10 releases until we ship 4.10.  Then we can probably remove them

read backend disruption for aggregator from the raw data instead of the junit

---

pkg/jobrunaggregator/jobrunaggregatoranalyzer/cmd.go
pkg/jobrunaggregator/jobrunaggregatorlib/retrying_ci_data_client.go
pkg/jobrunaggregator/jobrunbigqueryloader/cmd.go
pkg/jobrunaggregator/jobtableprimer/cmd.go
pkg/jobrunaggregator/releasebigqueryloader/cmd.go

we see errors like
> time="2021-11-16T04:00:44Z" level=fatal msg="Command failed" error="failed to query aggregation table with \"\\nSELECT *\\nFROM openshift-ci-data-analysis.ci_data.BackendDisruption_JobRuns as JobRuns\\nWHERE JobRuns.JobName = @JobName\\nORDER BY JobRuns.Name DESC\\nLIMIT 1\\n\": googleapi: Error 400: Job exceeded rate limits: Your project_and_region exceeded quota for concurrent queries. For more information, see https://cloud.google.com/bigquery/docs/troubleshoot-quotas, jobRateLimitExceeded"
in our log, which cause retries.  This wraps our client to retry on a backoff.

retry on query quota rate exceeded

---

pkg/jobrunaggregator/releasebigqueryloader/release_uploader.go

There's no reason to fetch the tag again if it's in bigquery, this makes
it much faster to run this.
The code also previously assumed the only incomplete state was "Ready," but a
release can be pending as well. We are ONLY interested in releases that
are Accepted or Rejected (which indicates all jobs have been run), so we
explicitly check that instead.

Don't fetch release tag again if it's already in bigquery

---

cmd/dptp-controller-manager/main.go

`Union` returns a new set, it does not change the input sets. Therefore
the `registriesExceptAppCI` did not really propagate anywhere.
Noticed while looking into [DPTP-2626](https://issues.redhat.com/browse/DPTP-2626)
@hongkailiu , it looks like we were running *without* the forbidden registries for few days. What is the impact?

dptp-cm: fix forbidden registry handling

---

pkg/validation/test.go
pkg/validation/test_test.go

We missed the opportunity to make these numbers sensible and we have stupidly
long names in the repo already (which apparently work), hence stupid numbers.
Claims have stricter limits because they internally infer more things from the
name.
I also took the opportunity to remove some unused code.
[DPTP-2507](https://issues.redhat.com/browse/DPTP-2507)

ci-operator: validate test name lengths

---

pkg/jobrunaggregator/jobrunaggregatoranalyzer/analyzer.go
pkg/jobrunaggregator/jobrunaggregatoranalyzer/analyzer_disruption.go
pkg/jobrunaggregator/jobrunaggregatoranalyzer/cmd.go
pkg/jobrunaggregator/jobrunaggregatoranalyzer/junit.go
pkg/jobrunaggregator/jobrunaggregatorapi/gcs_jobrun.go
pkg/jobrunaggregator/jobrunaggregatorlib/gcs_client.go
pkg/jobrunaggregator/jobrunaggregatorlib/jobrun_locator.go
pkg/jobrunaggregator/jobrunaggregatorlib/jobrun_locator_per_pr_jobs.go
pkg/jobrunaggregator/jobrunaggregatorlib/jobrun_locator_release_jobs.go
pkg/jobrunaggregator/jobrunbigqueryloader/uploader.go

`./job-run-aggregator analyze-job-runs --google-service-account-credential-file='/home/deads/openshift-ci-bigquery-credentials.json' --job=periodic-ci-openshift-release-master-ci-4.10-e2e-azure-ovn-upgrade --aggregation-id=3796f19a-4860-11ec-9fdb-74d435fb2dc0 --explicit-gcs-prefix=logs/ovn-kubernetes-834-ci-4.10-e2e-azure-ovn-upgrade --job-start-time=2021-11-18T11:11:43Z`
this is a command to run the aggregator on the the PR jobs

add the capability to aggregate per-pr payload promotion jobs

---

pkg/controller/prpqr_reconciler/prpqr_reconciler.go
pkg/controller/prpqr_reconciler/prpqr_reconciler_test.go

part of https://issues.redhat.com/browse/DPTP-2541
This PR adds the following types of conditions:
1. `AllJobsStarted` when all jobs started without errors
2. `WithErrors` when not all jobs have been created. The errors are included.
/cc @bbguimaraes 

Include conditions when reconciling the prpqr resources

---

pkg/controller/prpqr_reconciler/prpqr_reconciler.go
pkg/controller/prpqr_reconciler/prpqr_reconciler_test.go

Names of the jobs are unsuitable label values because of their length.
PRPQR reconciler used labels with job names as a way to identify jobs
spawned for the given PRPQR, but because job names can be longer, this
was not reliable (if we just trim, we can get conflicts).
Hence, use the MD5 hash of the name as the value of the label. That way
it can be reliably used for searching without conflicts. Keep the full
job name in an annotation, instead.

prpqr reconciler: label ProwJobs with hashed names

---

pkg/controller/prpqr_reconciler/prpqr_reconciler.go
pkg/controller/prpqr_reconciler/prpqr_reconciler_test.go

Type is a mandatory field, updating the condition fails without it

prpqr reconciler: define condition type

---

pkg/api/domain.go
pkg/api/domain_test.go

Otherwise we had to recompile ci-tools for each new cluster.
If we forgot, then revert such as following happened.
https://github.com/openshift/release/pull/23929

make RegistryDomainForClusterName more generic

---

cmd/ci-secret-bootstrap/main.go
cmd/ci-secret-bootstrap/main_test.go

```console
{"cluster":"build03","component":"ci-secret-bootstrap","file":"/go/src/github.com/openshift/ci-tools/cmd/ci-secret-bootstrap/main.go:490","func":"main.updateSecrets","level":"debug","msg":"Syncing secrets for cluster","severity":"debug","time":"2021-11-23T22:16:23Z"}
{"cluster":"build03","component":"ci-secret-bootstrap","file":"/go/src/github.com/openshift/ci-tools/cmd/ci-secret-bootstrap/main.go:493","func":"main.updateSecrets","level":"debug","msg":"handling secret","name":"github-token","namespace":"test-credentials","severity":"debug","time":"2021-11-23T22:16:23Z","type":"Opaque"}
[signal SIGSEGV: segmentation violation code=0x1 addr=0x18 pc=0x18b29d9]
goroutine 1 [running]: …
```

ci-secret-bootstrap: fix the secret-names flag: another nil pointer

---

pkg/controller/prpqr_reconciler/prpqr_reconciler_test.go
pkg/controller/prpqr_reconciler/testdata/zz_fixture_prowjobs_TestReconcile_basic_case.yaml
pkg/controller/prpqr_reconciler/testdata/zz_fixture_prowjobs_TestReconcile_basic_case__prowjob_already_exists__no_updates.yaml
pkg/controller/prpqr_reconciler/testdata/zz_fixture_prowjobs_TestReconcile_multiple_case__one_of_the_prowjobs_already_exists.yaml
pkg/controller/prpqr_reconciler/testdata/zz_fixture_prpqr_TestReconcile_basic_case.yaml
pkg/controller/prpqr_reconciler/testdata/zz_fixture_prpqr_TestReconcile_basic_case__prowjob_already_exists__no_updates.yaml
pkg/controller/prpqr_reconciler/testdata/zz_fixture_prpqr_TestReconcile_multiple_case__one_of_the_prowjobs_already_exists.yaml

Most of our newer tests that work with more complex structures use data
fixtures instead of code: they are easier to maintain (running with
UPDATE=true updates them when needed) and they are also really good in
inspecting changes.
The only change in the actual tests is that *fewer* members are ignored.
Previously, the `Spec` was ignored when comparing Prowjobs for no
apparent reason, and not ignoring it will improve the tests for the
future when we change how the submitted Prowjobs exactly look like.

prpqr: base tests on data fixtures instead of code

---

pkg/prowgen/podspec.go
pkg/prowgen/testdata/zz_fixture_TestClusterProfile_aws.yaml
pkg/prowgen/testdata/zz_fixture_TestClusterProfile_aws_cpaas.yaml
pkg/prowgen/testdata/zz_fixture_TestClusterProfile_openstack.yaml
pkg/prowgen/testdata/zz_fixture_TestNewProwJobBaseBuilderForTest_OpenshiftAnsibleClusterTestConfiguration.yaml
pkg/prowgen/testdata/zz_fixture_TestNewProwJobBaseBuilderForTest_OpenshiftAnsibleCustomClusterTestConfiguration.yaml
pkg/prowgen/testdata/zz_fixture_TestNewProwJobBaseBuilderForTest_OpenshiftInstallerClusterTestConfiguration.yaml
pkg/prowgen/testdata/zz_fixture_TestNewProwJobBaseBuilderForTest_OpenshiftInstallerCustomTestImageClusterTestConfiguration.yaml
pkg/prowgen/testdata/zz_fixture_TestNewProwJobBaseBuilderForTest_OpenshiftInstallerUPIClusterTestConfiguration.yaml
pkg/prowgen/testdata/zz_fixture_TestNewProwJobBaseBuilderForTest_multi_stage_test_with_cluster_profile.yaml
pkg/prowgen/testdata/zz_fixture_TestReleaseRpms_envvar_additional_envvar_generated_for_template.yaml
pkg/prowgen/testdata/zz_fixture_TestTemplate_different_template_with_command.yaml
pkg/prowgen/testdata/zz_fixture_TestTemplate_template_with_a_custom_test_image.yaml
pkg/prowgen/testdata/zz_fixture_TestTemplate_template_with_command.yaml
pkg/prowgen/testdata/zz_fixture_TestTemplate_template_with_different_command.yaml
test/integration/ci-operator-prowgen/output/jobs/super/duper/super-duper-master-periodics.yaml
test/integration/ci-operator-prowgen/output/jobs/super/duper/super-duper-master-presubmits.yaml
test/integration/repo-init/expected/ci-operator/jobs/org/repo/org-repo-master-presubmits.yaml
test/integration/repo-init/expected/ci-operator/jobs/org/third/org-third-nonstandard-presubmits.yaml

Projected secrets are useful when we need multiple sources melded into a
single volume. In most cases, our cluster profiles are just a single
secret, so using secrets directly as a volume source saves a bunch of
YAML lines (and simplifies the config).
Expected to fail breaking-changes check, needs a followup PR
/hold

prowgen: do not use projected secrets unless needed

---

cmd/branchingconfigmanagers/schedule-generator/main.go

[schedule-generator] don't load kube configs when validate-only is specified

---

cmd/sprint-automation/main.go

Follow up
https://coreos.slack.com/archives/CHY2E1BL4/p1638180894165800?thread_ts=1638172838.165200&cid=CHY2E1BL4

sprint-automation: Use mark-down when pinging triage

---

cmd/applyconfig/README.md

I have some vague idea for a tool that would automatically generate an "inventory" document with links to various places for everything that we deploy in openshift/release, and for that I need some reasonable destinations. So I am working my way through small, unified `README.md` files for some of our tools.
/cc @jmguzik @openshift/test-platform

Update README.md for applyconfig

---

cmd/private-prow-configs-mirror/main.go

This tool loads and dumps `plugins.yaml`.
It is also a part of `auto-config-brancher`.
It explains why the changes in https://github.com/openshift/release/pull/24007/files
got reverted by
https://github.com/openshift/release/pull/24115/commits/0b2deef72a5d95dd8fcefcbba5c408360688818c
According to https://github.com/openshift/ci-tools/tree/master/cmd/private-prow-configs-mirror#prow-plugins
This tool does not touch config_updater's config.
Hence, it is OK to skip the resolving.

private-prow-configs-mirror: skipResolveConfigUpdater=true

---

cmd/blocking-issue-creator/main.go

Small change, long description.
There is a need to slow down blocking-issue-creator as it is not respecting GitHub API limits. The calls are run without any sleep so after firing up around 30 calls blocking-issue-creator waits 1 minute to regain the possibility to ask GitHub. It is visible in the logs:
`
time="2021-11-30T18:01:58Z" level=info msg="FindIssues(is:issue state:open label:\"tide/merge-blocker\" .....
time="2021-11-30T18:02:54Z" level=info msg="Current merge-blocker issue is up to date, no update.....`
The time difference is around 1 minute. Currently, there are around 240 calls fired by the tool. The minimal sleep time set not to abuse the limit is something above 2 seconds (as several additional calls can be fired when there is a need to create or delete the issue). The …

Slow down blocking-issue-creator to respect API limits

---

cmd/job-trigger-controller-manager/main.go

:facepalm: 
```
flag provided but not defined: -config-path
Usage of job-trigger-controller-manager:
-dry-run
Whether to run the controller-manager with dry-run (default true)
-namespace string
In which namespace the operation will take place (default "ci")
```

job-trigger-cm: fix options

---

pkg/controller/prpqr_reconciler/prpqr_reconciler.go
pkg/controller/prpqr_reconciler/testdata/zz_fixture_prpqr_TestReconcile_basic_case__prowjob_already_exists__no_updates.yaml

Previous code structure assumed `generateProwjobs` is a cheap operation
(it is not, each Prowjob is a call to ci-operator-configresolver) so it
first generated all prowjobs and then it processed them.
This PR changes the reconciliation algorithm to straightforward
iteration over all jobs that *should* exist and hence should be present
in the status. First the code checks whether there is evidence that they
already exists (or existed in the past): either by presence in the
status, or by presence in the cluster. If the job is not present, it is
created. For all jobs, we track our observation of what their status
should be in our PRPQR resource.
Finally, the status reconciling takes into account that the updated
PRPQR can have *better* information than what *we* have, and we only
update the …

job-trigger-cm: code structure refactor

---

pkg/api/types.go
pkg/prowgen/podspec.go
pkg/validation/test.go

The intention of this PR is to add a new cluster profile which will be used target specific CI jobs to a resource pool capable of running e2e tests in a multizone vSphere environment.

add cluster profile for multizone vSphere CI pool

---

pkg/jobrunaggregator/jobrunaggregatoranalyzer/analyzer_disruption.go
pkg/jobrunaggregator/jobrunaggregatoranalyzer/pass_fail.go
pkg/jobrunaggregator/jobrunaggregatorlib/disruption.go

```
CGO_ENABLED=0 go build github.com/openshift/ci-tools/cmd/job-run-aggregator && ./job-run-aggregator analyze-job-runs --google-service-account-credential-file=/home/deads/openshift-ci-bigquery-credentials.json --job=periodic-ci-openshift-release-master-ci-4.10-e2e-azure-ovn-upgrade --payload-tag=4.10.0-0.nightly-2021-12-01-120924 --job-start-time=2021-12-01T12:11:54Z
```

add disruption P95 cap

---

cmd/backport-verifier/server.go
cmd/backport-verifier/server_test.go

For users to see how to re-run checks when e.g. an upstream PR merges after a failed check.

Note /validate-backports in commit validation messages

---

pkg/api/config.go
pkg/api/config_test.go

Previously we errored out on the sole presence of a base image name in both files. We can easily tolerate that unless the imagestream references are actually different.
/cc @openshift/test-platform @deads2k

resolver: base images only conflict when different

---

cmd/prow-job-dispatcher/main.go
cmd/prow-job-dispatcher/main_test.go
pkg/api/constant.go
pkg/api/types.go
pkg/dispatcher/config.go
pkg/dispatcher/config_test.go
pkg/prowgen/jobbase.go
pkg/prowgen/testdata/zz_fixture_TestNewProwJobBaseBuilderForTest_multi_stage_test_with_cluster_profile.yaml
test/integration/ci-operator-prowgen/output/jobs/super/duper/super-duper-master-presubmits.yaml
test/integration/repo-init/expected/ci-operator/jobs/org/repo/org-repo-master-presubmits.yaml
test/integration/repo-init/expected/ci-operator/jobs/org/third/org-third-nonstandard-presubmits.yaml

Follow up https://coreos.slack.com/archives/GB7NB0CUC/p1637862410018500?thread_ts=1637860578.014800&cid=GB7NB0CUC
1. ProwGen generates the label for multistage test according to `cluster_profile`
2. This is going to be used by sanitizer to determine the cluster where the job runs.
[DPTP-2651](https://issues.redhat.com/browse/DPTP-2651)

Generate cloud label on Prow jobs

---

cmd/repo-init/api.go
cmd/repo-init/main.go
pkg/api/types.go
pkg/prowgen/jobbase_test.go
pkg/prowgen/podspec.go
pkg/prowgen/testdata/zz_fixture_TestNewProwJobBaseBuilderForTest_OpenshiftAnsibleClusterTestConfiguration.yaml
pkg/prowgen/testdata/zz_fixture_TestNewProwJobBaseBuilderForTest_OpenshiftAnsibleCustomClusterTestConfiguration.yaml
pkg/prowgen/testdata/zz_fixture_TestNewProwJobBaseBuilderForTest_OpenshiftInstallerClusterTestConfiguration.yaml
pkg/prowgen/testdata/zz_fixture_TestNewProwJobBaseBuilderForTest_OpenshiftInstallerCustomTestImageClusterTestConfiguration.yaml
pkg/prowgen/testdata/zz_fixture_TestNewProwJobBaseBuilderForTest_OpenshiftInstallerUPIClusterTestConfiguration.yaml
pkg/prowgen/testdata/zz_fixture_TestNewProwJobBaseBuilderForTest_multi_stage_test_with_cluster_profile.yaml
pkg/validation/test.go

To be consistent with naming I would like to rename the cluster_profile field to `alibabacloud`. This matches the installer and other OpenShift components.
Corresponding rename: https://github.com/openshift/release/pull/24347

Renaming cluster_profile for Alibaba to alibabacloud

---

pkg/jobrunaggregator/jobrunaggregatoranalyzer/analyzer_disruption.go

- force all disruption aggregation to skipped status while we re-gather unbugged data
- Fix lint issue.

skip disrupt tests

---

cmd/ci-operator-prowgen/testdata/zz_fixture_postsubmit_TestFromCIOperatorConfigToProwYaml_Custom_test_timeout.yaml
cmd/ci-operator-prowgen/testdata/zz_fixture_postsubmit_TestFromCIOperatorConfigToProwYaml_Input_is_YAML_and_it_is_correctly_processed.yaml
cmd/ci-operator-prowgen/testdata/zz_fixture_postsubmit_TestFromCIOperatorConfigToProwYaml_Using_a_variant_config__one_test_and_images__one_existing_job._Expect_one_presubmit__pre_post_submit_images_jobs._Existing_job_should_not_be_changed..yaml
cmd/ci-operator-prowgen/testdata/zz_fixture_postsubmit_TestFromCIOperatorConfigToProwYaml_one_test_and_images__no_previous_jobs._Expect_test_presubmit__pre_post_submit_images_jobs.yaml
pkg/prowgen/prowgen.go
pkg/prowgen/prowgen_test.go
pkg/prowgen/testdata/zz_fixture_TestGenerateJobs_Promotion_configuration_causes_promote_job.yaml
pkg/prowgen/testdata/zz_fixture_TestGenerateJobs_Promotion_configuration_causes_promote_job_with_unique_targets.yaml
pkg/prowgen/testdata/zz_fixture_TestGenerateJobs_cluster_label_for_postsubmit.yaml
pkg/prowgen/testdata/zz_fixture_TestGenerateJobs_two_tests_and_empty_Images_with_one_test_configured_as_a_postsubmit.yaml
pkg/prowgen/testdata/zz_fixture_TestGenerateJobs_two_tests_and_nonempty_Images_so_two_test_presubmits_and_images_pre_postsubmits_are_generated_.yaml
pkg/prowgen/testdata/zz_fixture_TestGeneratePostSubmitForTest_Uppercase_org__repo_and_branch.yaml
pkg/prowgen/testdata/zz_fixture_TestGeneratePostSubmitForTest_postsubmit_with_run_if_changed.yaml
pkg/prowgen/testdata/zz_fixture_TestGeneratePostSubmitForTest_postsubmit_with_skip_if_only_changed.yaml
test/integration/ci-operator-prowgen/output/jobs/private/duper/private-duper-master-postsubmits.yaml
test/integration/ci-operator-prowgen/output/jobs/super/duper/super-duper-master-postsubmits.yaml
test/integration/ci-operator-prowgen/output/jobs/super/duper/super-duper-release-3.11-postsubmits.yaml
test/integration/repo-init/expected/ci-operator/jobs/openshift/ci-tools/openshift-ci-tools-master-postsubmits.yaml
test/integration/repo-init/expected/ci-operator/jobs/openshift/origin/openshift-origin-master-postsubmits.yaml

We have a case to define a publish the image job with `skip_if_only_changed` or `run_if_changed`. we want to configure it in ci config, but ci-operator cannot generate `skip_if_only_changed` or `run_if_changed` in jobs.
Signed-off-by: clyang82 <chuyang@redhat.com>

Support runIfChanged and skipIfOnlyChanged for postsubmit

---

pkg/jobconfig/files.go
pkg/jobconfig/files_test.go

...except for images jobs for which do not have syntax in ci-operator config
Once we pull all manual changes to ci-operator configs, we can stop tolerating these changes. One step closer to fully generated Prowjob configuration.
Needs https://github.com/openshift/release/pull/24629 for breaking changes to pass (we only want to merge this once breaking changes passes)
/hold

prowgen: stop tolerating changes to `optional` fields

---

cmd/autoconfigbrancher/README.md

Addressing a review from  https://github.com/openshift/ci-tools/pull/2572 

autoconfigbrancher: use a permanent link in README

---

cmd/promoted-image-governor/main.go
cmd/promoted-image-governor/main_test.go
cmd/testgrid-config-generator/main.go
pkg/release/config/client.go
pkg/release/config/config.go

Found 3 tools use ReleaseControllers configuration.
This PR starts to use the configuration struct from one place instead of three.

Share ReleaseController's config

---

cmd/testgrid-config-generator/main.go
pkg/release/config/client.go
test/integration/testgrid-config-generator/config/_allow-list.yaml
test/integration/testgrid-config-generator/config/jobs/org/repo/org-repo-master-periodics.yaml
test/integration/testgrid-config-generator/config/release/ocp-4.10.json
test/integration/testgrid-config-generator/expected/groups.yaml
test/integration/testgrid-config-generator/expected/redhat-openshift-ocp-release-4.10-blocking.yaml
test/integration/testgrid-config-generator/expected/redhat-openshift-ocp-release-4.10-informing.yaml

Aggregating jobs are added to blocking dashboard of the corresponding release.
Release is determined by the aggregated job prow config.

Add aggregating job results to testgrid

---

cmd/testgrid-config-generator/main.go

Adding the OpenStack jobs which recently moved from release to
shiftstack directory.
This will add them to testgrid automatically.

Updating auto-include logic for OpenStack jobs

---

pkg/jobrunaggregator/jobrunaggregatoranalyzer/pass_fail.go

Fixes an out of range problem.  This has to merge until we get history built up.  I'm also planning to inject history manually if possible.

handle missing history for aggregated disruption

---

pkg/jobrunaggregator/jobrunaggregatoranalyzer/analyzer.go
pkg/jobrunaggregator/jobrunaggregatoranalyzer/pass_fail.go

This allows a controlled relaxing on history on a test we incorrectly marked perma-passing in the past.

allow correcting history without changing test name when we get criteria incorrect

---

pkg/steps/cluster_claim.go
pkg/steps/utils/clusterpool.go

Followup for [DPTP-2633](https://issues.redhat.com/browse/DPTP-2633)
/cc @hongkailiu @dirgim @samvarankashyap @openshift/test-platform

ci-operator: add logging for cluster pool selection

---

pkg/steps/cluster_claim.go

* Use the cleanupCtx for cleanup, as the default ctx gets cancelled
* Start a goroutine that does the cleanup, so it will happen even if the
wrapped step blocks
Ref https://issues.redhat.com/browse/DPTP-2706

Clusterclaim: Make sure cleanup always happens

---

pkg/jobrunaggregator/jobrunaggregatorapi/types_row_testrun.go
pkg/jobrunaggregator/jobrunaggregatorlib/big_query.go
pkg/jobrunaggregator/jobrunaggregatorlib/ci_data_client.go
pkg/jobrunaggregator/jobrunaggregatorlib/gcs_client.go
pkg/jobrunaggregator/jobrunbigqueryloader/test_run_uploader.go
pkg/jobrunaggregator/jobrunbigqueryloader/types.go
pkg/jobrunaggregator/jobtableprimer/cmd.go
pkg/jobrunaggregator/tablescreator/table_creator.go

Before merging this PR, we need to manually add a new column to "TestRuns" (or there will be a lot of errors due to missing field).
We need the TestSuite field to help distinguish test cases that have identical names.  For now, we'll collect the TestSuite name.  There should only be 1 TestSuite name but if there are more, we'll concatenate them to make a unique TestSuite.
I added some hints for debugging to facilitate testing of the code (on a smaller scale).  I confirmed there is an error (as expected) if we try to run this with a TestRuns table with no TestSuite column.  I also confirmed that if you manually add the column, and rerun, the error will go away and the TestSuite value will be populated.

Add command to create "TestRuns" table with TestSuite; insert TestSuite as new column

---

pkg/api/types.go
pkg/prowgen/podspec.go
pkg/validation/test.go

This PR adds a new cluster profile for `platform=none` clusters in VMC. Required to map `platform=none` clusters to specific ci-segments in VMC for Windows workload' ci jobs ([WINC-607](https://issues.redhat.com/browse/WINC-607)).

Register Cluster Profile for platform=none

---

pkg/jobrunaggregator/jobrunaggregatoranalyzer/pass_fail.go

Regarding: https://bugzilla.redhat.com/show_bug.cgi?id=2042956
For now we'll skip since it's been failing for a while but unnoticed (as it was mistakenly classified as a flake before [a separate testSuite name was added to distinguish them](https://github.com/openshift/origin/pull/26755/files)).

Skip [sig-network] test that was failing for a while but unnoticed

---

pkg/controller/prpqr_reconciler/prpqr_reconciler.go
pkg/controller/prpqr_reconciler/prpqr_reconciler_test.go
pkg/controller/prpqr_reconciler/testdata/zz_fixture_prowjobs_TestReconcile_basic_aggregated_case.yaml
pkg/controller/prpqr_reconciler/testdata/zz_fixture_prpqr_TestReconcile_basic_aggregated_case.yaml

https://issues.redhat.com/browse/DPTP-2598
These changes allow the controller to check if the job is aggregated by reading the [AggregatedCount](https://github.com/openshift/ci-tools/blob/master/pkg/api/pullrequestpayloadqualification/v1/types.go#L107) field.
If that number is more than 0, then the controller spawns the same prowjob X times including the `release.openshift.io/aggregation-id` label with the same UID. Then it spawns the aggregator analysis job.

[DPTP-2598] Support spawing aggregated jobs when its needed

---

pkg/api/types.go
pkg/prowgen/podspec.go
pkg/validation/test.go

As part of the reorganization of the Equinix accounts per team, this new cluster profile will be used by the Metal team for their CI jobs, instead of the `packet` cluster profile.
Once all the jobs will have been migrated to the new profile, the `packet` profile could be safely deleted
cc @derekhiggins @ardaguclu

add equinix-ocp-metal cluster profile

---

pkg/controller/prpqr_reconciler/prpqr_reconciler.go
pkg/controller/prpqr_reconciler/testdata/zz_fixture_prowjobs_TestReconcile_basic_aggregated_case.yaml

While testing it seems that the aggregator job was configured without the namespace provided, therefore the creation of the prowjob is failing.
follow-up of https://github.com/openshift/ci-tools/pull/2577
```
oc get prpqr 7a83bbe0-7d1d-11ec-954a-489fc0865c9b-0 -o yaml
....
jobs:
- jobName: aggregator-periodic-ci-openshift-release-master-ci-4.10-e2e-aws-ovn-upgrade
prowJob: ""
status:
description: 'failed to create prowjob: an empty namespace may not be set during
creation'
state: error
.....
```

Add namespace while creating the aggregator job

---

pkg/controller/prpqr_reconciler/prpqr_reconciler.go
pkg/controller/prpqr_reconciler/testdata/zz_fixture_prowjobs_TestReconcile_basic_aggregated_case.yaml

It turns out that the [analyze-job-runs](https://github.com/openshift/ci-tools/blob/master/pkg/jobrunaggregator/jobrunaggregatoranalyzer/cmd.go#L60) is a param instead of a flag.

Correction in the aggregator job arguments

---

pkg/controller/prpqr_reconciler/prpqr_reconciler.go
pkg/controller/prpqr_reconciler/testdata/zz_fixture_prowjobs_TestReconcile_basic_aggregated_case.yaml

The `job-run-aggregator` defaults to a working directory (see: [here](https://github.com/openshift/ci-tools/blob/master/pkg/jobrunaggregator/jobrunaggregatoranalyzer/cmd.go#L48)) which makes the job fail since it doesn't have permission to create the working directory in the root folder.
With this change we allow the job to mount an emptyDir and adds the `--working-dir` argument to point to that path.
Related error:
```console
time="2022-01-24T19:02:02Z" level=fatal msg="Command failed" error="error creating destination directory \"job-aggregator-working-dir/periodic-ci-openshift-release-master-ci-4.10-upgrade-from-stable-4.9-e2e-azure-upgrade\": mkdir job-aggregator-working-dir: permission denied"
```

Add an empty dir as a working directory for the aggregator job

---

cmd/payload-testing-prow-plugin/server.go

Someone doing `/payload` on a non-OCP repository is not an error state for our tools, it is a user-triggered action that we handle properly (by refusing). No reason to log an error or even a warning.

prpqr: downgrade log message to `Info`

---

pkg/controller/prpqr_reconciler/prpqr_reconciler.go
pkg/controller/prpqr_reconciler/testdata/zz_fixture_prowjobs_TestReconcile_basic_aggregated_case.yaml

This secret is already being used by the release controller. We assume that the service account has the required permissions.
see: https://github.com/openshift/release/blob/master/clusters/app.ci/release-controller/deploy-ci-signer.yaml#L57-L60

Change the gcs secret in the aggregator job

---

pkg/controller/prpqr_reconciler/prpqr_reconciler.go
pkg/controller/prpqr_reconciler/testdata/zz_fixture_prowjobs_TestReconcile_basic_aggregated_case.yaml

Reverts openshift/ci-tools#2613
Not the right secret, discussed in https://coreos.slack.com/archives/GB7NB0CUC/p1643055504202500

Revert "Change the gcs secret in the aggregator job"

---

cmd/github-ldap-user-group-creator/main.go
cmd/github-ldap-user-group-creator/main_test.go

It takes `2h` to sync user groups.
Now we start to sync rover groups.
Adding concurrency on group handling should help reduce the time on each run.

github-ldap-user-group-creator: add concurrency

---

cmd/sync-rover-groups/main.go

If a group is used in manifest, which is a renamed group of a rover group, we do not need to resolve the renamed one.
Resolving it anyway would probably lead to a not-found error which spams our log.

sync-rover-groups: skip resolving the renamed group

---

cmd/sync-rover-groups/main.go

Validate runs as a presubmit which does not have access to Red Hat Intranet.
It will fix
```
{"component":"sync-rover-groups","file":"/go/src/github.com/openshift/ci-tools/cmd/sync-rover-groups/main.go:106","func":"main.main","level":"fatal","msg":"LDAP Result Code 200 \"Network Error\": dial tcp: lookup ldap.corp.redhat.com on 172.30.0.10:53: no such host","severity":"fatal","time":"2022-01-25T18:49:38Z"}
```
from https://prow.ci.openshift.org/view/gs/origin-ci-test/pr-logs/pull/openshift_release/25614/rehearse-25614-pull-ci-openshift-release-sync-rover-groups/1486048399982596096#1:build-log.txt%3A1

sync-rover-groups: skip resolving groups while validateSubjects=true

---

cmd/github-ldap-user-group-creator/main.go
cmd/github-ldap-user-group-creator/main_test.go

We have in total 3387 github user-groups to sync on 7-8 clusters.
It is still too slow after https://github.com/openshift/ci-tools/pull/2620
The reason is that the concurrency there is inside one cluster and it is throttled:
```
I0125 22:36:55.445260      15 request.go:665] Waited for 11.970939214s due to client-side throttling, not priority and fairness, request: GET:https://api.build02.gcp.ci.openshift.org:6443/apis/user.openshift.io/v1/groups/REDACTED
```
---
This one is a run with the image built by this PR.
https://deck-internal-ci.apps.ci.l2s4.p1.openshiftapps.com/view/gs/origin-ci-private/logs/periodic-github-ldap-user-group-creator/1486149476094578688
Nice! Reduced to 23m from 3h.

github-ldap-user-group-creator: move concurrency onto clusters

---

pkg/steps/release/import_release.go
pkg/util/imagestream.go

As described in https://issues.redhat.com/browse/DPTP-2448, the
container created by the step should use the image indicated by
`cluster-version-operator image cli`.

pkg/steps/release: use correct CLI image reference

---

cmd/cluster-init/update_jobs.go
test/integration/cluster-init/create/expected/ci-operator/jobs/openshift/release/openshift-release-master-presubmits.yaml
test/integration/cluster-init/update/expected/ci-operator/jobs/openshift/release/openshift-release-master-presubmits.yaml

Make https://github.com/openshift/release/pull/25651 changes persistent even for newly added clusters.

cluster-init: make -dry jobs run only on changes in manifests

---

pkg/controller/prpqr_reconciler/prpqr_reconciler.go
pkg/controller/prpqr_reconciler/prpqr_reconciler_test.go
pkg/controller/prpqr_reconciler/testdata/zz_fixture_prowjobs_TestReconcile_basic_aggregated_case.yaml

Reviewer notes:
- Example of an aggregator periodic: [openshift/release/openshift-release-infra-periodics.yaml#L2270-L2356](https://github.com/openshift/release/blob/master/ci-operator/jobs/openshift/release/openshift-release-infra-periodics.yaml#L2270-L2356)
- Step [prpqr-aggregator/openshift-release-analysis-prpqr-aggregator](https://github.com/openshift/release/blob/master/ci-operator/step-registry/openshift/release/analysis/prpqr-aggregator/openshift-release-analysis-prpqr-aggregator-ref.yaml)

Refactor the aggregator job to be generated by an unresolved ci-op config

---

pkg/steps/source.go

Seen in failures due to the current autoscaler issue:
```
* could not run steps: step csi-livenessprobe failed: the build csi-livenessprobe failed with reason GenericBuildFailed: Generic Build failure - check logs for details.
```
https://prow.ci.openshift.org/view/gs/origin-ci-test/logs/branch-ci-openshift-csi-livenessprobe-release-4.11-images/1490635717557096448
Seems to be distinct enough from legitimate build failures:
```
* could not run steps: step crc failed: the build crc failed after 2m5s with reason DockerBuildFailed: Dockerfile build strategy has failed.
```
https://prow.ci.openshift.org/view/gs/origin-ci-test/pr-logs/pull/code-ready_crc/2984/pull-ci-code-ready-crc-dev-images/1490627156324126720

pkg/source: retry on `GenericBuildFailed`

---

cmd/autoowners/main.go
cmd/autoowners/main_test.go

Currently we put a [header like this](https://github.com/openshift/release/blob/08e400216f5d0fd121a517bc97512d7928f44c8f/ci-operator/config/openshift/ci-tools/OWNERS#L1-L2) to OWNERS files:
```
```
We can provide more information in there:
```
```

autoowners: include source and date feched in header comment

---

pkg/steps/source.go

`ci-operator` was already able to recognize infrastructure-failed builds
from previous runs and retry them. This is an attempt to reuse that code
to retry such failed builds immediately, with two attempts in an
exponential backoff. The backoff has an intentionally long starting
delay of 1 minute to give the infrastructure problem a chance to go
away. The way the code is structured makes it less optimal for the case
where we are retrying infra failures from the previous executions: it
will eat one of the backoff iterations, but such cases should be rare
because ci-op runs should not result in failures caused by
infrastructure failures anymore (because they are retried immediately).
/cc @bbguimaraes @jupierce @openshift/test-platform

ci-operator: retry infra-failed builds immediately

---

cmd/ci-operator-prowgen/main_test.go
test/integration/repo-init/input/ci-operator/config/openshift/ci-tools/openshift-ci-tools-master.yaml
test/integration/repo-init/input/ci-operator/config/openshift/origin/openshift-origin-master.yaml

These fields are ancient and have long been removed, but were still
unintentionally allowed due to the loading duplication we had, cf.:
https://github.com/openshift/ci-tools/pull/2627/files#diff-9d074e6d02129dc16ea4fb5dd423cfb7120791f74e477efa77e9424861a78960L169
https://github.com/openshift/ci-tools/blob/3c2360c044e5efa70394e6abcdc8be2c491c9f8f/pkg/config/load.go#L46
Required so `UnmarshalStrict` can be enabled for all tools which load
`ci-operator` configuration files.

Fix test data

---

pkg/config/load.go
pkg/util/sync.go
pkg/util/sync_test.go

This pattern is everywhere, implemented slightly differently each time.  Some
versions do not bound the maximum number of Go routines, causing file descriptor
exhaustion.
This change creates a small library that is as generic as I managed to make it
in Go and reimplements `ci-operator` configuration loading using it.  More to
come.
/hold
Based on https://github.com/openshift/ci-tools/pull/2627.
---
See also:

pkg/config: use generic pipeline function

---

pkg/registry/server/client.go

Retrying should mitigate the effect of the recent app.ci hiccups (https://search.ci.openshift.org/?search=failed+to+load+configuration%3A+failed+to+make+request+to+configresolver&maxAge=12h&context=1&type=bug%2Bjunit&name=&excludeName=&maxMatches=5&maxBytes=20971520&groupBy=job)

configresolver client: retry http requests

---

pkg/api/types.go

Originally all the cluster profiles associated with Equinix were expecting a cluster type to be `packet`. We are now deprecating the old `packet` cluster profile and cluster type. There was a requirement for the two cluster_profiles `packet-assisted` and `packet-sno` to use the same qouta. This updates the cluster type for those profiles to be `packet-edge`
See: https://github.com/openshift/release/pull/25952 where the jobs under `packet-assisted` and `packet-sno` are now being blocked from running.

Update cluster type to packet-edge for Assisted and SNO profiles

---

cmd/pj-rehearse/main.go
pkg/rehearse/jobs.go
pkg/rehearse/jobs_test.go
test/integration/pj-rehearse/candidate/core-services/prow/02_config/_config.yaml
test/integration/pj-rehearse/expected.yaml
test/integration/pj-rehearse/master/core-services/prow/02_config/_config.yaml

In order to allow for the correct Details link to be shared on the gh status for rehearsals for qe-private-deck repos (https://issues.redhat.com/browse/DPTP-2742) we can utilize the `DecorationConfig` where an existing override is in place: https://github.com/kubernetes/test-infra/blob/b800243aebae95801cec2b9f16950623c6a42497/prow/config/config.go#L820

override job_url_prefix for rehearsals

---

cmd/better-retester/main.go
cmd/better-retester/retester.go

Some notable changes:
- pwned the fan-out in querying: retest will not need to query in parallel and I immediately hit rate limiting when testing
- I removed the `!orgs.Has(org)` which I do not understand why it was added
- Added some logging
- Added a `status:failure` into the query to only search failing PRs (only ever makes sense to retest failing PRs)

Better retester: make a controller

---

pkg/load/agents/registryAgent.go

Experience suggests metrics are more useful when you populate them.
https://prometheus-prow-monitoring.apps.ci.l2s4.p1.openshiftapps.com/graph?g0.range_input=4w&g0.expr=configresolver_registry_reload_duration_seconds_bucket&g0.tab=1
https://prometheus-prow-monitoring.apps.ci.l2s4.p1.openshiftapps.com/graph?g0.range_input=4w&g0.expr=configresolver_registry_reload_duration_seconds_count&g0.tab=1
https://prometheus-prow-monitoring.apps.ci.l2s4.p1.openshiftapps.com/graph?g0.range_input=4w&g0.expr=configresolver_registry_reload_duration_seconds_sum&g0.tab=1

pkg/load: use correct registry metric

---

cmd/better-retester/main.go
cmd/better-retester/retester.go

Followup to https://github.com/openshift/ci-tools/pull/2675,
Removes a ton of useless Tide stuff and slightly reworks the logic. The deployment will need access to Prow *job* configuration.

Filter prs with failing required jobs

---

cmd/autoowners/main.go

fixes: https://prow.ci.openshift.org/view/gs/origin-ci-test/logs/periodic-prow-auto-owners/1494248760073523200#1:build-log.txt%3A2155
`body is too long (maximum is 65536 characters)`

[autoowners] trim body when it exceeds more than 65536 characters

---

test/e2e/pod-scaler/prometheus/prometheus.go

e2e: properly wait for Prometheus
https://github.com/openshift/ci-tools/pull/2632#issuecomment-1038948252
https://github.com/openshift/ci-tools/pull/2632#issuecomment-1039252732
---
e2e: reintroduce sleep
For some reason the readiness probe is not sufficient, I still see failures
even with this in the logs:
```
accessory.go:66: `prometheus` readiness probe error: Get "http://0.0.0.0:40275/-/ready": dial tcp 0.0.0.0:40275: connect: connection refused:
accessory.go:66: `prometheus` readiness probe: 503
accessory.go:66: `prometheus` readiness probe: 503
accessory.go:66: `prometheus` readiness probe: 503
accessory.go:66: `prometheus` readiness probe: 503
accessory.go:66: `prometheus` readiness probe: 503
accessory.go:66: `prometheus` readiness probe: 503
accessory.go:66: Prometheus is running …
```

e2e: properly wait for Prometheus

---

cmd/repo-init/api.go
cmd/repo-init/frontend.go

The logs aren't showing in CloudWatch. This should fix that by formatting in JSON.

use the logrusutil to set the component and formatter in repo-init-apiserver

---

cmd/better-retester/main.go

To fix
```console
$ oc logs -n ci better-retester-5d65875457-d2wfr
time="2022-02-17T17:00:33Z" level=fatal msg="could not parse cache record age" error="time: unknown unit \"d\" in duration \"7d\""
```
It does not support `days`.
https://github.com/golang/go/issues/17767

better-retester: fix the default value of cache-record-age

---

cmd/better-retester/retester.go

To fix:
```
time="2022-02-17T20:30:30Z" level=error msg="Error syncing" error="failed to save cache to disk: failed to rename file from /tmp/backoffCache2406905041 to /cache/backoff: rename /tmp/backoffCache2406905041 /cache/backoff: invalid cross-device link"
```
Got the idea from https://github.com/GoogleCloudPlatform/buildpacks/issues/135#issuecomment-839847373

better-retester: use the same dir for the temp file

---

cmd/repo-init/api.go
cmd/repo-init/repo_manager.go

The logic in `repo_manager` to keep track of the available and in-use repos was incorrect resulting in a proliferation of entries in each respective slice. There was also an instance of marking a repo in use, and never freeing it. Between these two changes the overall memory usage is cut down, and the app succeeds with multiple runs.

(repo-init-api) fix logic for locking and unlocking repos

---

cmd/github-ldap-user-group-creator/main.go
cmd/github-ldap-user-group-creator/main_test.go

https://issues.redhat.com/browse/DPTP-2659
The GitHub IDP has been removed on the clusters and thus the github users cannot login into the clusters any more.
We do not need the github user in the group.

github-id-group contains only kerberos_id

---

cmd/entrypoint-wrapper/main.go
test/integration/entrypoint-wrapper.sh

entrypoint-wrapper: improve integration tests
At some point tests started interfering with each other such that it is
no longer possible to execute them individually.  Make each use its own
environment.
---
entrypoint-wrapper: improve test output
Better identify failures, cf.:
<details>
```
--- /tmp/openshift/test-integration/out.log     2021-10-03 00:03:37.531198260 +0000
+++ /tmp/openshift/test-integration/secret.yaml 2021-10-03 00:03:31.456150623 +0000
@@ -0,0 +1 @@
+{"kind":"Secret","apiVersion":"v1","metadata":{"name":"test","creationTimestamp":null,"labels":{"ci.openshift.io/skip-censoring":"true"}},"data":{"test0.txt":"dGVzdDAK"},"type":"Opaque"}
```
https://prow.ci.openshift.org/view/gs/origin-ci-test/pr-logs/pull/openshift_ci-tools/2414/pull-ci-openshift-ci-tools-master-integratio …

entrypoint-wrapper: separate cmd. `Start`/`Wait`

---

cmd/autoowners/main.go
cmd/autoowners/main_test.go

Technically a nice idea, but it results in a daily super-churn: https://github.com/openshift/release/pull/26399/files
I considered to make the tool smarter (compare the existing OWNERS files and only change the header when the content fails) but because we have two types of OWNERS files, we need to handle cases like files missing and varius errors etc, I decided it is not worth the hassle. The information about when the file was last changed will be stored in `git` so putting it to header is just convenience.

autoowners: stop putting fetch time into header

---

cmd/repo-init/api.go
cmd/repo-init/frontend/src/app/Common/Messaging.tsx
cmd/repo-init/frontend/src/app/Generate/Generate.tsx
images/repo-init/Dockerfile

We need to generate the jobs prior to the commit/pr creation. I also thought of utilizing the the tools that `make jobs` runs inside the repo-init binary itself, but it is doing a lot and most of it would need to be refactored to be accessible here. Ultimately, I decided that the `make jobs` target is better to use as it will remain up to date and is the way that we currently onboard a new repo.
We also need to validate that the tests execute in an image that we have specified so that context needs to be built up for the validation.
Since `make jobs` takes some time I added an info message to make it more user friendly.

repo init ui: run 'make jobs' prior to commit

---

cmd/repo-init/api.go
images/repo-init/Dockerfile

Utilizing the tools that comprise `make jobs` directly following @petr-muller's comment here: https://github.com/openshift/ci-tools/pull/2688#discussion_r811449206.
I wasn't able to get this to work by just doing `make jobs` even when including `podman` and `make` in the image.

use tool binaries directly to mimic 'make jobs'

---

cmd/repo-init/README.md

In order to run this locally we need to configure a gh oauth app. This adds those steps to the README.

repo-init-ui: add info about gh oauth

---

cmd/determinize-prow-config/main.go

In order to not have a situation where running `make prow-config` causes us to silently lose configuration due to improper indentation or misnaming a key we should load the config in strict mode.
There is an existing function in test-infra to do this, but `agent.Start` doesn't utilize it. I considered adding a flag to that method to trigger that behavior, but we don't need to be using `agent.Start` here anyways. We can just load the config once, in strict mode, and then let the rest of the functionality follow as normal.

determinize-prow-config: use strict mode to fail when there is an unknown key

---

cmd/ci-operator/main.go
pkg/steps/run.go
test/e2e/simple/artifacts/junit_operator.xml

Way back in 12c1a0d704, it seemed like there might be a single suite, so clobbering the name with the writeJUnit argument was reasonable.  But 26ebc68367 (#1007) added sorting code that only makes sense if some JUnit may contain multiple suites.  Only clobbering the name on whichever suite happened to be first (before sorting!) doesn't seem like an internally-consistent approach.
With this commit, I'm pivoting to consistently trust the suite data to contain names, and I've updated any suites I've found in the code to declare those names as well.

cmd/ci-operator: Trust suite names in writeJUnit

---

pkg/release/prerelease/client.go
pkg/release/prerelease/client_test.go

Requires ${arch} -> `4-stable-${arch}` instead of `4-stable` for all architectures

Fixing prerelease support for multiarch

---

pkg/steps/multi_stage.go

d5ac60199f (#2697) added JUnit output for whether the phase passed or failed.  It also added logging to the start of the phase.  But it did not add logging around phase completion.  This commit adds that phase-completion logging.  Besides making the phase boundaries clearer to folks reading the logs, it also allows for CI-search queries like:
```console
$ curl -s 'https://search.ci.openshift.org/search?maxAge=24h&type=build log&search=test+pre+phase&search=test+test+phase&search=Using+namespace+https'
```
to combine information about the build cluster (currently only 'Using namespace https...' in the build log with no JUnit exposure) and the phase status (in JUnit since d5ac60199f, but going into the build log too with this commit).

pkg/steps/multi_stage: Log phase result

---

pkg/defaults/defaults.go
pkg/validation/config.go

Improve (make explicit) the error message given when `.ci-operator.yaml` is present and is a valid YAML, but not the yaml we expect

ci-operator: improve error message for invalid `.ci-operator.yaml`

---

cmd/sprint-automation/main.go

These dates will be helpful in the intake role to recognize issues that you have already viewed, but were recently updated and need another look.
They will be helpful in the "Cards Awaiting Acceptance" section so we have a good idea of how long the card has been waiting for by looking at the `Last updated`

sprint-automation: add created and last updated to the card digests

---

cmd/ci-operator-configresolver/main.go

These pages have long been moved to https://docs.ci.openshift.org and
are no longer served.

ci-operator-configresolver: remove defunct URLs

---

cmd/sprint-automation/README.md
cmd/sprint-automation/main.go
hack/local-sprint-automation.sh

This adds the role digest mentioned in [DPTP-2432](https://issues.redhat.com/browse/DPTP-2432).
It also adds an easy way to test using our testing slack, and a README describing `sprint-automation`.
I still want to follow up with an "on demand" view of upcoming on call role's, but that will use the `slack-bot` and be more complex.
Next up:
add a new job to `infra-periodics.yaml` that runs weekly on mondays using the new `week-start` flag. Also, will need to stop the current `periodic-sprint-automation` from running on mondays. I think the work I've done here will make it easier to fix [DPTP-2403](https://issues.redhat.com/browse/DPTP-2403) as well, by allowing us to query for active roles as of noon UTC on mondays.

sprint-automation: add a role digest for the following week

---

pkg/api/types.go
pkg/prowgen/podspec.go

Follow up https://github.com/openshift/ci-tools/pull/2720, after testing, my prow job is still using the `azure4` secrets, the installation did not land into QE dedicated cluster profiles.

provide different secrets for QE dedicated cluster profiles

---

pkg/prowgen/podspec.go

After https://github.com/openshift/ci-tools/pull/2721, my prow job failed with:
```
The pod could not start because it could not mount the volume "cluster-profile": configmap "cluster-profile-azure-qe" not found
```
This PR fix that.

only provide one secret for QE cluster profiles without configmap

---

pkg/jobrunaggregator/jobrunaggregatoranalyzer/pass_fail.go

These are not useful for aggregation results and should not fail
payloads.

Skip step graph tests in aggregation.

---

cmd/better-retester/main.go
cmd/better-retester/main_test.go
cmd/better-retester/retester.go

First part of changing retestOrBackoff. Option --enable-on-repo will create list of repositories. In this repos retestOrBackoff will be commenting instead of logging.
- I created option enable-on-repo, basic test for gaterOptions method.
- Edit option and retestController struct to contain the list of repositories.

Change retestOrBackoff functionality: Added option enable-on-repo

---

cmd/pod-scaler/admission.go
cmd/pod-scaler/admission_test.go
cmd/pod-scaler/testdata/zz_fixture_TestMutatePods_pod_marked_with_ignore_annotation.yaml

ci cost savings requires the ability to specify that a pod should be excluded from pod-scaler mutating its resources. This will be done using a new `ci-workload-autoscaler.openshift.io/scale` annotation. If the value of this is `false` or it is missing the pod-scaler will behave as normal. Otherwise, it will allow the admission without mutating anything.

pod-scaler: ignore pods with the `ci-workload-autoscaler.openshift.io/scale`=false annotation

---

pkg/prowgen/podspec.go

Cont. to https://github.com/openshift/ci-tools/pull/2727.
1. With the last PR, "ProjectedVolumeSource" is expected for the new cluster profile, but jobs using the profile would fail due to lack of the config-map "gcp-qe".
2. On considering that, the secrets data structures defined on [Vault](https://vault.ci.openshift.org/ui/vault/auth?with=oidc%2F) of different cloud providers are similar, I'd like to try "SecretVolumeSource" for the GCP profile and see if it can work. Or any suggestion? Thanks in advance!

Create QE dedicated GCP cluster profile "gcp-qe" (using "SecretVolumeSource")

---

cmd/ci-operator/main.go
pkg/results/report.go

Description of the problem:
If ci-operator fails to resolve the config from the config resolver, it tries to report the error and exit (see [ci-operator/main.go#L541-L543](https://github.com/openshift/ci-tools/blob/master/cmd/ci-operator/main.go#L541-L543)). This will generate another error while reporting the results to the results server: `response for the report was not 200: cluster field in request is empty` which is expected since by that time the cluster field is empty because it's being resolved later in the code.
This PR changes the resolving method while completing the options instead.

DPTP-2760 Resolve console host url while completing options

---

cmd/ci-operator/main.go
pkg/results/report.go

Reverts openshift/ci-tools#2735
Seeing `WARN[2022-03-30T09:46:19Z] Could not create client for accessing Routes. Will not resolve console URL.  error=must provide non-nil rest.Config to client.New` now, pretty sure the PR is the thing that broke this ([example](https://prow.ci.openshift.org/view/gs/origin-ci-test/pr-logs/pull/openstack-k8s-operators_osp-director-operator/551/pull-ci-openstack-k8s-operators-osp-director-operator-master-golint/1509104703160455168#1:build-log.txt%3A2))

Revert "DPTP-2760 Resolve console host url while completing options"

---

cmd/pod-scaler/producer.go

I was finally able to get `pod-scaler` to get through _all_ of the data by increasing the memory limit to `15Gi` manually (this has since been reverted). Now, the normal limit of `6Gi` is more than enough for it to get through everything with each run. This is due to how much less memory intensive it is to use the data from the bucket cache than to query Prometheus for it. To make sure that we don't run into this in the future we should decrease the interval in which we query Prometheus from `3` hours to `2`. This will result in 1/3rd less data being handled each time.
In a forthcoming PR I am also going to add an alert for `pod-scaler-producer` so that this is noticed more quickly if it occurs again.
For [DPTP-2804](https://issues.redhat.com/browse/DPTP-2804)

Pod Scaler: decrease the interval for querying

---

pkg/prowgen/podspec.go

Profiles without `ConfigMap`s are clearly the common case.  Invert the
filtering rules so that virtually every new profile does not have to
change this area.
Looking at `openshift/release`, the pattern here seems to be:
- GCP and oVirt profiles legitimately use a CM.
- The remaining AWS and Azure profiles in this list maybe do or do not
use CMs, but are only used in ancient 3.11 jobs anyway.

pkg/prowgen: invert profile `ConfigMap` list

---

pkg/api/types.go

This new platform will let us test OCP on OpenStack using OVS HW
offload.

Add new cluster type for OpenStack HW offload platform

---

pkg/jobrunaggregator/jobrunaggregatoranalyzer/pass_fail.go

For https://issues.redhat.com/browse/TRT-176
This test always fails on a failure in an aggregation test so no point in reporting it too.

During aggregation test, do not consider 'initialize' test as a failure

---

cmd/repo-init/api.go
cmd/repo-init/api_test.go
cmd/repo-init/main.go

This change addresses a number of problems:
- The PR used as an example in our documentation for adding cluster
profiles incorrectly added a profile to `repo-init`'s list, so others
have occasionally followed:
https://docs.ci.openshift.org/docs/how-tos/adding-a-cluster-profile/#registering-a-new-profile
- `repo-init` and its "frontend" unfortunately do not share most of
their code.
- As a result, they have used independent lists of profiles, which have
advanced inconsistently.
To that end, I've unified the list of profiles used by both programs.
Since https://github.com/openshift/ci-tools/pull/1509, this list has
been a very reduced subset of all available profiles, so I've restricted
it to those three profiles and added a clarifying comment to discourage
future additions.

repo-init: use correct list of cluster profiles

---

cmd/better-retester/main.go
cmd/better-retester/retester.go
cmd/better-retester/retester_test.go
vendor/k8s.io/test-infra/prow/github/fakegithub/fakegithub.go

Second part of changing retestOrBackoff. Option --enable-on-repo will create list of repositories. In this repos retestOrBackoff will be commenting instead of logging.
- I created method createComment.
- Edit retestOrBackoff funcionality to start commenting instead of logging on repositories from the list
Previous PR: https://github.com/openshift/ci-tools/pull/2729

Change retestOrBackoff functionality: Added method createComment, Edited retestOrBackoff funcionality

---

cmd/github-ldap-user-group-creator/main.go
cmd/github-ldap-user-group-creator/main_test.go
pkg/group/config.go
pkg/group/config_test.go
pkg/group/testdata/TestLoadConfig/openshift_priv_admins.yaml

https://issues.redhat.com/browse/DPTP-2811
Prevent https://github.com/openshift/release/pull/27455/files from happening in the future.

sync-rover-group: cannot use the group name openshift-priv-admins

---

pkg/jira/issues.go
pkg/slack/modals/consultation/view.go
pkg/slack/modals/consultation/view_test.go
pkg/slack/modals/incident/view.go
pkg/slack/modals/incident/view_test.go

`Incident` and `Request` Jira issue types will be deprecated. This PR just only changes those issue types into the `Story` type.

Deprecate Incident and Request issue jira types from slack-bot integration

---

cmd/prow-job-dispatcher/main.go
cmd/prow-job-dispatcher/main_test.go
pkg/dispatcher/config.go
pkg/dispatcher/config_test.go

Add:
- `--enable-cluster`
- `--disable-cluster`
- `--default-cluster`
These options should be helpful for failovers etc. The implementation of
`prow-job-dispatcher` is a little messy, so I ended up removing the
disabled clusters from the structure before the dispatching, and then I
return them back.
Part of: [DPTP-2064](https://issues.redhat.com/browse/DPTP-2064)
/cc @hongkailiu @jmguzik @openshift/test-platform

prow-job-dispatcher: add options for enabling/disabling clusters

---

pkg/steps/release/import_release.go

In https://github.com/openshift/ci-tools/pull/2634 we made this timeout after ~30s but this apparently still happens and @deads2k hates it. Let's try 5m timeout, there's no reason to not do that. When it succeeds, nobody cares about few minutes. When it fails, the failure is still sufficiently fast.
https://search.ci.openshift.org/chart?search=unable+to+wait+for+the+.*+image+in+the+stable+stream+to+populate&maxAge=48h&context=1&type=bug%2Bjunit&name=&excludeName=&maxMatches=5&maxBytes=20971520&groupBy=job
Slack thread: https://coreos.slack.com/archives/C01CQA76KMX/p1649352789006809

wait for five minutes for the cli image

---

pkg/slack/events/helpdesk/helpdesk-message.go
pkg/slack/events/router/router.go

Currently, after a user posts a message in forum-tesplatform slack channel, a public auto-response is generated. This PR adds an ephemeral message that is sent to the user.
[DPTP-2748](https://issues.redhat.com/browse/DPTP-2748)

Post ephemeral reply to the messaging user in forum-tesplatform channel

---

cmd/branchingconfigmanagers/bugzilla-config-manager/main.go

`bugzilla-config-manager` was suffering from a similar problem to [DPTP-2721](https://issues.redhat.com//browse/DPTP-2721) which was fixed in https://github.com/openshift/ci-tools/pull/2647: it expanded the clustergroup on save.

bugzilla-config-manager: do not resolve cluster groups

---

cmd/branchingconfigmanagers/bugzilla-config-manager/main.go
cmd/branchingconfigmanagers/bugzilla-config-manager/testdata/lifecycle_multiple_ga_410_bigger_49.yaml
cmd/branchingconfigmanagers/bugzilla-config-manager/testdata/zz_fixture_TestRun_lifecycle_multiple_ga_410_bigger_49.yaml.yaml
pkg/api/ocplifecycle/ocplifecycle.go

- bugzilla-config-manager: add test for wrong 4.9/4.10 sort
- bugzilla-config-manager: fix wrong 4.9/4.10 sort
The config manager was sorting versions using `String()` which resulted in a wrong sort of `4.9` and `4.10`, resulting in generating wrong configuration.

bugzilla-config-manager: fix 4.9/4.10 sorting issue

---

pkg/steps/multi_stage.go

```yaml
tests:
- as: test
literal_steps:
test:
- as: test0
from: root
commands: "true"
credentials:
- namespace: bbguimaraes
name: test
mount_path: /tmp/test
resources: # …
- # so on for test1 to test7
```
```console
$ ci-operator -v … &> log.txt
$ grep 'secrets/test 200 OK' log.txt
I0412 11:12:58.447473   60218 round_trippers.go:454] GET https://api.build01.ci.devcluster.openshift.com:6443/api/v1/namespaces/bbguimaraes/secrets/test 200 OK in 115 milliseconds
I0412 11:12:58.558331   60218 round_trippers.go:454] GET https://api.build01.ci.devcluster.openshift.com:6443/api/v1/namespaces/bbguimaraes/secrets/test 200 OK in 108 milliseconds
I0412 11:12:58.668861   60218 round_trippers.go:454] GET https://api.build01.ci.devcluster.openshift.com:6443/api/v1/namespaces/bbguimaraes/secrets/test …
```

ci-operator multi-stage: fetch credentials once

---

pkg/slack/events/helpdesk/helpdesk-message.go

Based on the limitations of ephemeral replies, I decided to change the auto-response from ephemeral to normal message reply that will be posted in a new thread.
[DPTP-2726](https://issues.redhat.com/browse/DPTP-2726)
/cc smg247

Change ephemeral reply to threaded reply

---

cmd/autopublicizeconfig/main.go
cmd/blocking-issue-creator/main.go
cmd/ci-operator-config-mirror/main.go
cmd/config-brancher/main.go
cmd/payload-testing-prow-plugin/server.go
cmd/private-org-peribolos-sync/main.go
cmd/private-org-sync/main.go
cmd/private-org-sync/main_test.go
cmd/private-prow-configs-mirror/main.go
cmd/repo-brancher/main.go
pkg/promotion/promotion.go
pkg/promotion/promotion_test.go
pkg/prowgen/prowgen.go

The motivation for this change is to include OKD in various release automation. From how the code looked like in the past, it seems that it was always the intent, but the code was not maintained and kept updated with how OKD configuration is structured: previously, the OKD check was `namespace == okdPromotionNamespace && name == okd40Imagestream`, but none of the existing ci-operator configs use these names.
Because the usage of `*OfficialImages` proliferated over time, some of the callsites expect the check to include OKD, and some callsites do not (notably, the `openshift-priv` tools are not needed to handle OKD and things actually break if they do). Therefore, I have added an explicit parameter to all these methods to control whether the caller wants to work also with OKD or not.
We …

promotion: treat promoting to `origin` as promoting official images

---

pkg/slack/events/helpdesk/helpdesk-message.go

Changed the string against which we check if (@)dptp-helpdesk was mentioned to a hopefully correct one, as the previous one was not working.
https://issues.redhat.com/browse/DPTP-2748
/cc smg247

update helpdesk mention string with a correct one

---

pkg/api/types.go

After discuss with DPP and Installer dev team, QE should use our dedicated cluster profiles.
release https://github.com/openshift/release/pull/28013
Profile | Profile String | Cloud Type
-- | -- | --
ClusterProfileAlibabaCloudQE | alibabacloud-qe | alibabacloud

Create QE dedicated Alibabacloud cluster profile "alibabacloud-qe"

---

pkg/results/report.go

Partially reverts b00a10669f79c36c8f6bd4d4e87eb3a905c6ede7.
While not generally of interest to the regular user, hiding this line
makes it impossible to find instances of a particular error reason using
https://search.ci.openshift.org.
The original messages were in the following format:
```
Reporting job state 'succeeded'
```
```
Reporting job state 'failed' with reason 'the:reason'
```
which is not terrible for a user-facing message, so I'm just reverting
the level back to `Info`.
In the future, we may finally work on presenting results in a better
format.  In the meantime, simply removing the message achieves very
little.
https://issues.redhat.com/browse/DPTP-2632

ci-operator: do not hide reporting log line

---

pkg/api/types.go

After discuss with DPP and Installer dev team, QE should use our dedicated cluster profiles.
_FYI Similar to https://github.com/openshift/ci-tools/pull/2781, but for another cluster profile (owned by QE) which is for Alibabacloud China-site accounts testing._
release https://github.com/openshift/release/pull/28090
Profile | Profile String | Cloud Type
-- | -- | --
ClusterProfileAlibabaCloudCNQE | alibabacloud-cn-qe | alibabacloud

Create QE dedicated Alibabacloud cluster profile "alibabacloud-cn-qe"

---

pkg/steps/lease.go

Before:
```
INFO[2022-04-27T13:28:52Z] Acquiring leases for test test
<pause>
INFO[2022-04-27T13:28:52Z] Acquired 1 lease(s) for nutanix-quota-slice: [nutanix-segment-01]
```
After:
```
INFO[2022-04-27T18:25:12Z] Acquiring leases for test test: [nutanix-quota-slice]
<pause>
INFO[2022-04-27T18:25:12Z] Acquired 1 lease(s) for nutanix-quota-slice: [nutanix-segment-01]
```
---
Had to debug this today and missed this information.

pkgs/steps/lease: log resources before acquiring

---

OWNERS

Blunderbuss keeps selecting Petr as a reviewer for my PRs. This is annoying as I end up with only one "active" reviewer and must `/cc` someone else manually.
I went ahead and removed Emil from approvers and reviewers as he has been gone from Red Hat for awhile now.

Remove Petr and Emil from OWNERS reviewers

---

pkg/steps/multi_stage/gen.go
pkg/steps/multi_stage/gen_test.go
pkg/steps/multi_stage/multi_stage.go
pkg/steps/multi_stage/run.go

`ci-tools` has a chronic problem with cryptic booleans everywhere.
More configuration options will be added here soon, add a flags member
in preparation.

ci-operator multi-stage: add flags member

---

pkg/steps/multi_stage/gen.go
pkg/steps/multi_stage/gen_test.go
pkg/steps/multi_stage/run.go

Return the set directly instead of a closure.
The set bound to the closure is only ever populated based on the input
configuration, there is no need to have dynamic behavior after
construction.
/hold
~Includes https://github.com/openshift/ci-tools/pull/2790 to use the new `flags` member.~

ci-operator multi-stage: simplify best-effort test

---

cmd/sprint-automation/main.go
go.mod
go.sum
pkg/jira/issues.go
vendor/k8s.io/test-infra/prow/apis/prowjobs/v1/types.go
vendor/k8s.io/test-infra/prow/git/git.go
vendor/k8s.io/test-infra/prow/git/v2/interactor.go
vendor/k8s.io/test-infra/prow/github/types.go
vendor/k8s.io/test-infra/prow/jira/jira.go
vendor/k8s.io/test-infra/prow/plugins/jira/jira.go
vendor/k8s.io/test-infra/prow/plugins/testfreeze/checker/checker.go
vendor/k8s.io/test-infra/prow/plugins/testfreeze/testfreeze.go
vendor/k8s.io/test-infra/prow/spyglass/README.md
vendor/modules.txt

We need an updated `test-infra` specifically to obtain the change in https://github.com/kubernetes/test-infra/pull/26214.
Note: the jira `JiraError` function name was changed to `HandleJiraError`.

Update `test-infra` dependency

---

cmd/ci-operator/main.go

This test has been redundant since the transition to the controller
runtime client in 41a6a7910267041b357177f47bf0c4810588a368.
Identified by `golangci-lint` v1.46:
```
cmd/ci-operator/main.go:1260:5: SA4031: this nil check is always true (staticcheck)
if is != nil {
^
cmd/ci-operator/main.go:1242:9: SA4031(related information): this is the value of is (staticcheck)
is := &imageapi.ImageStream{
^
```

ci-operator: remove useless check

---

cmd/testgrid-config-generator/main.go

QE would like to add several tests from openshift-tests and openshift-tests-private (both are under openshift/) to testgrid

Allow add tests from openshift-tests & openshift-tests-private to testgrid

---

pkg/jobrunaggregator/jobrunaggregatoranalyzer/analyzer_disruption.go
pkg/jobrunaggregator/jobrunaggregatoranalyzer/pass_fail.go

This leaves teh code that checks active, but sets the junit to skip.  This change allows future analysis

skip disruption check on azure

---

pkg/jobrunaggregator/jobrunaggregatoranalyzer/analyzer_disruption.go
pkg/jobrunaggregator/jobrunaggregatoranalyzer/pass_fail.go

This appears to catch the failures we've found in https://search.ci.openshift.org/?search=which+is+more+than+the+failureThreshold+of+the+weekly+historical+mean+from&maxAge=48h&context=1&type=junit&name=aggregator.*4.11&excludeName=&maxMatches=5&maxBytes=20971520&groupBy=job
We still want to see failures when we hit significant regressions.

relax disruption aggregation to five standard deviations

---

pkg/steps/multi_stage/gen.go
pkg/steps/multi_stage/gen_test.go
pkg/steps/multi_stage/init.go
pkg/steps/multi_stage/init_test.go
pkg/steps/multi_stage/multi_stage.go
pkg/steps/multi_stage/testdata/zz_fixture_TestSetSecurityContexts_empty.yaml
pkg/steps/multi_stage/testdata/zz_fixture_TestSetSecurityContexts_match.yaml
pkg/steps/multi_stage/testdata/zz_fixture_TestSetSecurityContexts_no_match.yaml

Initial implementation of VPN support as described in the
[design document](https://docs.google.com/document/d/1mPjrHVS1EvmLdq4kGhRazTpGu6xVZDyGpVAphVZhX4w/).
User documentation PR: https://github.com/openshift/ci-docs/pull/249.
Based on:
- https://github.com/openshift/ci-tools/pull/2790
- https://github.com/openshift/ci-tools/pull/2795

ci-operator multi-stage: add initial VPN support

---

cmd/config-shard-validator/main.go
cmd/config-shard-validator/main_test.go

We currently check 272 globs against 17642 paths.  This compiles 4798624 glob
matchers, 99.994% of which are unnecessary.  This PR eliminates that and other
inneficiencies, parallelizes the verification (configuration loading is already
implicitly done in parallel), and improves some errors messages while it's at
it.
```
master      c1481a757    ci-operator job
-----------------------------------------------------
real    4m1.932s    0m4.997s     0m3.145s    0m0.974s
user    7m35.714s   0m34.346s    0m20.285s   0m5.193s
sys     0m8.350s    0m0.763s     0m0.701s    0m0.244s
```
These are timings for the complete execution of builds from `master` and this
PR, and the time to load the `ci-operator` and job configuration exclusively.
This new version executes in 2.065% of the original time, …

config-shard-validator: compile globs once

---

pkg/jobrunaggregator/jobrunaggregatoranalyzer/analyzer_disruption.go

Work to bring back will be tracked in https://issues.redhat.com/browse/TRT-234

Disable aggregated disruption testing again.

---

.snyk

[DPTP-2823](https://issues.redhat.com//browse/DPTP-2823) We are adding this file to exclude `vendor/` and tests.

Fix DPTP-2823 Add .snyk file

---

go.mod
go.sum
pkg/prowconfigsharding/prowconfigsharding.go
vendor/k8s.io/test-infra/prow/flagutil/github.go
vendor/k8s.io/test-infra/prow/github/client.go
vendor/k8s.io/test-infra/prow/plugins/config.go
vendor/k8s.io/test-infra/prow/plugins/plugin-config-documented.yaml
vendor/k8s.io/test-infra/prow/plugins/testfreeze/testfreeze.go
vendor/k8s.io/test-infra/prow/plugins/welcome/welcome.go
vendor/modules.txt

Continuing work in kubernetes/test-infra#26343 with enabling all welcome plugin configuration to be sharded by organizations / repositories / etc. instead of only being defined globally.
Without this fix, one will get failure similar to this:
```
time="2022-05-19T17:26:20Z" level=fatal msg="could not update Prow
plugin configuration" error="could not load Prow plugin configuration:
failed to merge config from
/config/openshift-assisted/_pluginconfig.yaml into main config:
supplemental plugin configuration has config that doesn't support
merging:   &plugins.Configuration{\n  \t... // 26 identical fields\n
\tSize:     {},\n  \tTriggers: nil,\n- \tWelcome:
[]plugins.Welcome{{Repos: []string{\"openshift-assisted\"}}},\n+
\tWelcome:  nil,\n  \tOverride: {},\n  \tHelp:     {},\n  }\n"
```
In …

fix prow-config-sharding of welcome plugin

---

pkg/steps/multi_stage/gen.go
pkg/steps/multi_stage/testdata/zz_fixture_TestGeneratePods.yaml
pkg/steps/multi_stage/testdata/zz_fixture_TestSetSecurityContexts_match.yaml
pkg/steps/pod.go
pkg/steps/testdata/zz_fixture_TestPodStepExecution_Pod_run_by_PodStep_fails_so_PodStep_terminates_and_returns_an_error.yaml
pkg/steps/testdata/zz_fixture_TestPodStepExecution_Pod_run_by_PodStep_succeeds_so_PodStep_terminates_and_returns_no_error.yaml
pkg/steps/testdata/zz_fixture_TestPodStepExecution_Successful_pod_with_cloning.yaml

d31d564f0 started adding security contexts to multi-stage tests which
use VPN connections, but there is never a reason to execute containers
as UID 0 outside of that case.
Set a security context for all pods created during the execution of a
test.  This includes those that import releases etc. but not builds —
which are `privileged` anyway.
The settings in the `PodSecurityContext` propagate and are overridden by
those in the container's `SecurityContext`, so small changes are
required to the existing ones:
https://kubernetes.io/docs/tasks/configure-pod-container/security-context/#set-the-security-context-for-a-container
This will also make me less nervous when making changes to the VPN
implementation.
---
/hold
Let's not deploy things right before a holiday =)

ci-operator: always set security context

---

pkg/config/release.go

In the Paleolithic era, our images used CentOS 7 and `git` 1.8:
https://github.com/openshift/ci-operator-prowgen/pull/118#issuecomment-475582854
(note the repository URL for extra nostalgia)
We are no longer using stone tools, so change the `diff-filter` to
something more reasonable.  See:
https://git-scm.com/docs/git-diff#Documentation/git-diff.txt---diff-filterACDMRTUXB82308203

pkg/config: use newer `diff-filter` syntax

---

cmd/retester/main.go
cmd/retester/retester.go
cmd/retester/retester_test.go

The logic before this PR:
`enable`-checking takes place right before issuing the command on PRs:
Yes: issue `/retest` command
No: logging (The cache will count even this case).
The miscounting led to the fact that the PRs that come from a newly enabled repo/org have no comments because it reaches the limit in cache.
To fix this, the logic after this PR:
Filter out disabled PRs before checking if it has failures from required jobs.
Remove the logging for disabled PRs because each PR is enabled at that point.

retester: check if a PR is enabled earlier

---

cmd/github-ldap-user-group-creator/main.go

Found those (see `githubRobotIds`) in the logs.
/hold
Give DPP more time to confirm if https://github.com/RH-Cachito is a robot
https://coreos.slack.com/archives/CBUT43E94/p1653679694670849
1. Ignore those known robot accounts while logging
2. Error instead of warning if seeing more in the future
/cc @smg247

github-ldap-user-group-creator: whitelist github IDs for robots

---

cmd/check-gh-automation/main.go
cmd/check-gh-automation/main_test.go

From testing out the periodic in https://prow.ci.openshift.org/view/gs/origin-ci-test/pr-logs/pull/openshift_release/29112/rehearse-29112-periodic-check-gh-automation/1532421549770936320 it appears there will be some repos that we need to ignore in this check. I am reaching out to owners to confirm that they have valid reasons for not adding the automation, but in the meantime I want to add the ability to ignore some repos.

Add option to ignore repos in `check-gh-automation`

---

cmd/check-gh-automation/main.go
cmd/check-gh-automation/main_test.go

The periodic is getting rate limited due to having to check too many repos. We can entirely ignore the checks for `openshift` and `openshift-priv` as part of the process for setting up repos there include adding the bots team to the repo. I have also verified (by running the periodic rehearsal) that everything there is set up correctly.

modify to allow ignoring entire orgs in `check-gh-automation`

---

cmd/cluster-display/main.go

This reverts commit 7ae33072cab074a236eb260a1cf92debaf94b56f.
Ref. the implementation https://github.com/gin-gonic/gin/blob/f2182de38c8d19d35d4b4191749216f12512f59c/render/json.go#L119

template.JSEscapeString(callbackName)

---

cmd/check-gh-automation/main.go
pkg/config/release.go
pkg/config/release_test.go

We are running this check a lot, and since we now have a periodic to consistently verify that repos that are already a part of the CI are accessible by our automation we don't need the presubmit to check repos for which the configs have merely been modified.
I used https://git-scm.com/docs/git-diff-tree#Documentation/git-diff-tree.txt---diff-filterACDMRTUXB82308203 to only flag repos for which the configs were: added, moved, or renamed.

`check-gh-automation`: don't check repos where the config was simply modified

---

cmd/blocking-issue-creator/main.go
cmd/blocking-issue-creator/main_test.go

"Contact the Test Platform team" should never be the suggested first
step for more information.

blocking-issue-creator: direct users to docs

---

cmd/ci-operator-configresolver/main.go
pkg/load/agents/configAgent.go
pkg/load/agents/registryAgent.go
pkg/load/agents/utils.go

/cc @bbguimaraes @openshift/test-platform 
- Adds a `--release-repo-path` flag
- Start watcher for the release repo folder symlink destination
If the symlink of the release repo path will change, then the watcher starts watching the new destination and reload the configs once.

Introduce a watcher for a symlink release repo path

---

cmd/pod-scaler/admission.go
cmd/pod-scaler/admission_test.go
cmd/pod-scaler/main.go
cmd/pod-scaler/testdata/zz_fixture_TestMutatePodResources_resources_to_add.diff
cmd/pod-scaler/testdata/zz_fixture_TestMutatePodResources_resources_to_add__limits_disabled.diff
cmd/pod-scaler/testdata/zz_fixture_TestMutatePods_pod_associated_with_a_build_with_labels.yaml
test/e2e/pod-scaler/run/consumer.go

We need to cap the amount of memory that the `pod-scaler` requests to `20Gi`. I made this amount configurable and also made the existing `cpu-cap` configurable.
For: [DPTP-2928](https://issues.redhat.com/browse/DPTP-2928)

Pod Scaler: cap memory requests at 20Gi

---

cmd/sprint-automation/main.go

Notification for upgrading b02 should go to build-farms channel since it is about b02.
https://coreos.slack.com/archives/CHY2E1BL4/p1655452858675389

Use #alerts-testplatform-build-farms

---

cmd/check-gh-automation/main.go
cmd/check-gh-automation/main_test.go

If the bots are members of the org we don't need to check that they are collaborators on the repo.
For: [DPTP-2936](https://issues.redhat.com/browse/DPTP-2936)

Check GH Automation: check org membership as an alternative to repo collaborators

---

pkg/slack/events/helpdesk/helpdesk-message.go

In preparation for alerting that users should use the new workflows in #forum-testplatform I need to determine the best way to tell if a user is posting a direct message or is using a workflow. Since we can't add workflows to the dptp-robot-testing slack space due to it being a free plan I need some additional logging.

`slack-bot`: log user and bot_id fields in helpdesk-message handler

---

pkg/slack/events/helpdesk/helpdesk-message.go

I am not completely sure how it is happening, but it appears that the bot will post a top-level message that looks like
when a workflow is used.
From looking through the logs it was referencing a message with no `bot-id` **and** no `user`. We only need to do this auto-reply when the user is non-nil.

verify user is non-nil before posting reply

---

cmd/sprint-automation/main.go
cmd/sprint-automation/main_test.go

b02 is chosen as a cluster for OpenShift Next.
It will go closely with master tip.
https://issues.redhat.com/browse/DPTP-2854

Allow a greater version of b02 than b01

---

cmd/ci-operator-configresolver/main.go
cmd/dptp-controller-manager/main.go

Follow up https://coreos.slack.com/archives/CHY2E1BL4/p1657280723675739
```
{"component":"config-bootstrapper","configmap":{"cluster":"app.ci","name":"step-registry","namespace":"ci"},"error":"update config map err: ConfigMap \"step-registry\" is invalid: []: Too long: must have at most 1048576 bytes","file":"k8s.io/test-infra/prow/cmd/config-bootstrapper/main.go:155","func":"main.run","level":"error","msg":"failed to update config on cluster","severity":"error","time":"2022-07-08T11:43:11Z"}
```
`CM/step-registry` is too big.
After https://github.com/openshift/ci-tools/pull/2805, `dptp-cm` is the only component using it.
This PR enables the feature on it.

dptp-cm: use git-sync

---

Makefile
hack/pr-deploy.yaml

step-registry CM is removed in https://github.com/openshift/release/pull/30298. We can now use the standard git-sync for the configs like the deployed `configresolver` does.

use git-sync in pr-deploy-configresolver

---

pkg/api/constant.go

Creating jobs on arm01 cluster is failing due to missing config definition
https://issues.redhat.com/browse/DPTP-2913 

Support for ARM01 build cluster

---

cmd/pod-scaler/admission.go
cmd/pod-scaler/admission_test.go
cmd/pod-scaler/consumer.go
cmd/pod-scaler/resources.go
cmd/pod-scaler/testdata/zz_fixture_TestMutatePodResources_resources_to_add.diff
cmd/pod-scaler/testdata/zz_fixture_TestMutatePodResources_resources_to_add__limits_disabled.diff
pkg/testhelper/accessory.go
test/e2e/pod-scaler/run/consumer.go

My previous attempt at fixing the flakiness in the `pod-scaler` e2e TestAdmission didn't work. I cannot get this to fail locally so I added a bunch of extra logging to diagnose the problem. This logging is at the `debug` and `trace` levels and I think is useful to triage future issues.
This ended up being a very time consuming race condition to debug. It turns out that some of the time the subscription for the `memory` metrics was not in place upon the initial loading of the cache. Since the subscription wasn't in place, and we only produce the data once for this test the admission server never became `ready`. This lead to a timeout waiting for the condition, and an eventual failure to find any data for the `memory` metric.
The solution is to make sure that we don't mark the data as seen …

Pod Scaler e2e: reload cache after initial subscribe

---

pkg/jobrunaggregator/jobtableprimer/generated_job_names.txt

We've renamed a number of jobs to include `sdn` in their name, this
regenerates the job lists for the aggregator. Commands run:
- go build ./cmd/job-run-aggregator/...
- ./job-run-aggregator generate-job-names > pkg/jobrunaggregator/jobtableprimer/generated_job_names.txt
Will prime the job table again after this merges.

Update job names list for 4.12 after SDN job rename

---

pkg/registry/server/client.go

The first argument to the logging functions is a regular string, not a
formatting directive:
https://github.com/hashicorp/go-retryablehttp/blob/493aa4cf372e47ec00228558d9d91a9517b045a5/client.go#L315-L325
https://github.com/hashicorp/go-retryablehttp/blob/493aa4cf372e47ec00228558d9d91a9517b045a5/client.go#L587
This results in an incorrect message, e.g.:
```
{"level":"debug","msg":"performing request%!(EXTRA string=method, string=GET, string=url, *url.URL=https://config.ci.openshift.org/config?branch=master\u0026org=openshift\u0026repo=ci-tools)","time":"2022-07-11T17:03:22Z"}
```
https://gcsweb-ci.apps.ci.l2s4.p1.openshiftapps.com/gcs/origin-ci-test/pr-logs/pull/openshift_ci-tools/2883/pull-ci-openshift-ci-tools-master-unit/1546540394894856192/artifacts/ci-operator.log
Now:
``` …
```

pkg/registry: correct `retryablehttp` logger

---

cmd/check-gh-automation/main.go

We need to limit the repos that we check in the presubmit version. If there are more than 10 modified repos it is likely that this is a code-freeze (or similar) PR, and there is no need to check those.
for https://issues.redhat.com/browse/DPTP-2984

`check-gh-automation`: don't check repos in presubmit if more than 10 have been modified

---

pkg/api/types.go

This patch adds a new cluster profile to deploy OCP clusters on
vexxhost clouds for operator testing.

Add OpenStack Operators on Vexxhost cluster profile

---

cmd/ci-operator/main.go

https://issues.redhat.com/browse/DPTP-2989
The oldest version is vsphere:
```console
oc --kubeconfig /tmp/sa.config-updater.vsphere.config version
Client Version: 4.11.0-rc.3
Kustomize Version: v4.5.4
Server Version: 4.9.31
Kubernetes Version: v1.22.8+c02bd9d
```
https://kubernetes.io/docs/reference/using-api/deprecation-guide/#poddisruptionbudget-v125
> policy/v1 API version, available since v1.21

PDB Client: v1beta1 to v1

---

cmd/pr-reminder/README.md
cmd/pr-reminder/main.go
cmd/pr-reminder/main_test.go
hack/local-pr-reminder.sh
hack/pr-reminder-config.yaml

This requires:
- configuration updates to allow for multiple teams
- additional validation, and a `validate-only` mode to be used in a presubmit check when the config is modified
- performance improvements to be able to run at scale
I also updated the `local-pr-reminder.sh` script to not use the production config file for simpler manual testing.
For: https://issues.redhat.com/browse/DPTP-3016

`pr-reminder`: extend to the org

---

cmd/retester/main.go
cmd/retester/main_test.go
cmd/retester/retester.go
cmd/retester/retester_test.go
cmd/retester/testdata/testconfig/config.yaml
cmd/retester/testdata/testconfig/default.yaml
cmd/retester/testdata/testconfig/empty.yaml
cmd/retester/testdata/testconfig/no-config.yaml
cmd/retester/testdata/testconfig/openshift-config.yaml

Option `--config-file` path to File which configure maxRetestsForShaAndBase and maxRetestsForSha. Default maxRetests values are configured in file.
Options `--enable-on-repo` and `--enable-on-org` are removed. And replaced by config file.
Test config file: [cmd/retester/testdata/testconfig/config.yaml](cmd/retester/testdata/testconfig/config.yaml)
[ci-docs PR](https://github.com/openshift/ci-docs/pull/268)
[DPTP-2828](https://issues.redhat.com/browse/DPTP-2828)

retester: Adding config file to retester

---

cmd/pr-reminder/main.go
cmd/pr-reminder/main_test.go

PRs that have been assigned should also be included in the digest. Sometimes people assign a user without `cc`ing them, and we still need to be aware of those.
For: https://issues.redhat.com/browse/DPTP-3009

`pr-reminder`: include PRs where user is assigned

---

cmd/pr-reminder/main.go

Now that this is opened up to other teams we should have some additional logging to make it easier for us to respond to issues with it. Nothing has come up yet, but I was looking through the logs and I would have liked to know which users were and weren't sent their digests.

`pr-reminder`: add some additional logging

---

cmd/config-shard-validator/main.go
pkg/api/metadata.go
pkg/api/metadata_test.go

The `job-config-misc` `ConfigMap` now exceeds the 1MB capacity, so it needs to
be further divided.  The distribution of branch names has a bias for
`release-[0-9]`:
```
$ release config \
| yq -r '.zz_generated_metadata.branch' \
| sort | uniq -c | sort -n | tail -30
9 backplane-1.0
9 release-2.2
9 release-ocm-2.4
9 release-v1.4
11 release-ocm-2.5
11 release-ocm-2.6
11 release-v1.3
13 release-next
19 backplane-2.0
20 backplane-2.1
24 release-3.11
50 release-2.6
55 release-2.5
58 release-2.3
63 release-2.4
201 release-4.1
252 release-4.2
279 release-4.3
306 release-4.4
336 release-4.5
347 main
361 release-4.6
390 release-4.7
409 release-4.8
436 release-4.9
491 release-4.10
521 release-4.13
528 release-4.12
529 release-4.11
739 master
```
Take those out of `misc` by generalizing the …

config-shard-validator: further break `misc` CM

---

cmd/pod-scaler/admission.go
cmd/pod-scaler/admission_test.go

This adds metrics for pod-scaler admission to record an error to prometheus, in case pod-scaler determines that a job needs more than 10 times the memory configured in the spec.
for the first 2 subtasks of https://issues.redhat.com/browse/DPTP-2929
/cc smg247

Add metrics to pod-scaler-admission

---

images/ci-secret-generator/oc_sa_create_kubeconfig.sh

`vsphere` is now using the CA trusted cert on API server.  Thanks to @rvanderp3 
We do not need the flag any more.

vsphere: no need to use --insecure-skip-tls-verify

---

cmd/entrypoint-wrapper/main.go
pkg/steps/multi_stage/gen.go
pkg/steps/multi_stage/gen_test.go
pkg/steps/multi_stage/multi_stage.go
pkg/steps/multi_stage/run.go

This work is preparatory for a future e2e test (an additional PR will follow).
`entrypoint-wrapper` has been modified to opt-out the following features:
- make a `rw` copy of `$KUBECONFIG`
- synchronize `$SHARED_DIR` back to the shared secret
- upload a kubeconfig
`ci-operator` has been modified to configure observer-pods such that:
- they are not allowed to update the shared secret
- no kubeconfig will ever be uploaded
- a kubeconfig will exist in `$KUBECONFIG` as soon as possible
/cc @jmguzik @bbguimaraes 
/hold

Observer pods: manage kubeconfig and shared_dir features on entrypoint-wrapper

---

pkg/defaults/defaults.go

Resolve multi-arch namespace when overriding the cli image for the release payload

---

cmd/check-gh-automation/README.md
cmd/check-gh-automation/main.go
cmd/check-gh-automation/main_test.go
hack/local-check-gh-automation.sh

Now that this tool is getting more complicated, it is nice to have an easy way to run it locally. By adding a new option to supply the repo(s) to be checked we can achieve that.
As a follow up, I want to create a make target in `openshift/release` that allows us to simply check a repo on command. This is useful when we think some changes to the automation access may be causing problems.

`check-gh-automation`: allow repo to be passed in and create local dev script

---

cmd/ci-operator-prowgen/main.go
pkg/api/types.go
pkg/config/load.go
pkg/controller/prpqr_reconciler/prpqr_reconciler.go
pkg/prowgen/prowgen.go
pkg/prowgen/prowgen_test.go
pkg/prowgen/testdata/zz_fixture_TestGenerateJobs_disabled_rehearsals_at_job_level.yaml
pkg/prowgen/testdata/zz_fixture_TestGenerateJobs_disabled_rehearsals_at_repo_level.yaml
pkg/prowgen/testdata/zz_fixture_TestGeneratePeriodicForTest_periodic_with_disabled_rehearsal.yaml
pkg/prowgen/testdata/zz_fixture_TestGeneratePresubmitForTest_rehearsal_disabled.yaml
test/integration/ci-operator-prowgen/input/config/norehearsals/duper/.config.prowgen
test/integration/ci-operator-prowgen/input/config/norehearsals/duper/norehearsals-duper-master.yaml
test/integration/ci-operator-prowgen/input/config/norehearsals/stuper/.config.prowgen
test/integration/ci-operator-prowgen/input/config/norehearsals/stuper/norehearsals-stuper-master.yaml
test/integration/ci-operator-prowgen/output/jobs/norehearsals/duper/norehearsals-duper-master-postsubmits.yaml
test/integration/ci-operator-prowgen/output/jobs/norehearsals/duper/norehearsals-duper-master-presubmits.yaml
test/integration/ci-operator-prowgen/output/jobs/norehearsals/stuper/norehearsals-stuper-master-postsubmits.yaml
test/integration/ci-operator-prowgen/output/jobs/norehearsals/stuper/norehearsals-stuper-master-presubmits.yaml

This will allow job maintainers to disable rehearsals on **all** jobs for an org or repo by using the `.config.prowgen` file. It also allows for individual tests rehearsals to be disabled via a list of `disabled_rehearsals`.
I considered adding validation that each of the tests in the disabled rehearsals list actually matched a test name, but doing so would be fairly complex and difficult to put in place. Since the job maintainers will clearly be able to see that the label has still been applied if they were to make a typo in the entry in the list, I think it is okay to forgo this validation.
Coming up next: Information about using these new configs will be added to `ci-docs`
For: https://issues.redhat.com/browse/DPTP-3091

`prowgen`: disable rehearsals via the .config.prowgen file

---

cmd/ci-operator-checkconfig/main.go
cmd/promoted-image-governor/main.go
cmd/registry-replacer/main.go
pkg/api/helper/imageextraction.go
pkg/api/metadata.go
pkg/defaults/defaults.go
pkg/defaults/defaults_test.go
pkg/steps/release/promote.go
pkg/steps/release/promote_test.go

These changes allow image promotions to resolve the namespace based on the os architecture that the promotion pod is running.
For example, If the job is running on arm64 architecture, all images will be promoted to the `$NAMESPACE-arm64` namespace in apps.ci registry.   
In addition, the build cache for the images was refactored to resolve the namespace too, which means the non-amd64 architecture images will generate a new cache.

Support promoting images based on their architecture and resolve build cache

---

cmd/autoconfigbrancher/main.go

https://github.com/openshift/release/pull/30862 changed the merge method for all
pull requests in `openshift/release` to `squash`.  This destroys the discrete
commits intentionally created by `autoconfigbrancher`, resulting in a single
commit with all changes, e.g.: https://github.com/openshift/release/pull/31473.
This change makes the program always explicitly set the merge method so it is
not affected by repository configuration.

autoconfigbrancher: explicitly choose merge method

---

cmd/ci-operator/main.go

Updating the default from `12h` to `24h` as most `ns`s are cleaned up before 12 hours anyways, and QE needs to be able to create a longer running job. This also coincides with our overall Prow job limit: https://github.com/openshift/release/blob/1a0bca02f5b91e4a67e15e81b8e909e2abfd9d8b/core-services/prow/02_config/_config.yaml#L109
Note: I am using golang `1.19`, and it seems to like to update whitespace in comments. I can take out this change if necessary.
For: https://issues.redhat.com/browse/DPTP-3114

update default cleanup duration

---

cmd/result-aggregator/main.go
cmd/result-aggregator/main_test.go

Adds functionality to result-aggregator to handle requests from pod-scaler admission service and record them to Prometheus.
for https://issues.redhat.com/browse/DPTP-3106
/cc smg247

Result-aggregator: handle pod-scaler admission requests

---

cmd/cluster-init/update_bootstrap_secrets.go
test/integration/cluster-init/create/expected/core-services/ci-secret-bootstrap/_config.yaml
test/integration/cluster-init/update/expected/core-services/ci-secret-bootstrap/_config.yaml

With the recent changes that have been made to privatize the repositories in quay.io, some tests are still trying to pull the release payload from quay.io and failing
needed for https://github.com/openshift/release/pull/32209

add quay.io pull credentials when generating the bootstrap secrets for build clusters

---

cmd/cluster-init/update_bootstrap_secrets.go
test/integration/cluster-init/create/expected/core-services/ci-secret-bootstrap/_config.yaml
test/integration/cluster-init/update/expected/core-services/ci-secret-bootstrap/_config.yaml

/cc @openshift/test-platform @hongkailiu 
This is now safe and possible after https://github.com/openshift/ci-tools/pull/3008 and https://github.com/openshift/release/pull/32289

[cluster-init] add the quay.io secret when generating the registry-pull-credentials secret

---

pkg/jobrunaggregator/jobrunaggregatoranalyzer/cmd.go

Re: [TRT-370](https://issues.redhat.com//browse/TRT-370)
The current minimum is only 3 and when there are infra problems, this seems too small because too many job runs don't get to fully run as in [this example](https://prow.ci.openshift.org/view/gs/origin-ci-test/logs/aggregated-azure-sdn-upgrade-4.12-minor-release-openshift-release-analysis-aggregator/1570003912218382336).
3 seems too small of a sample for an accurate signal from aggregation; 6 seems more appropriate (allowing up to 4 jobs to fail due to infra issues).

Change minimum number of jobs to 6 instead of 3 for more accurate aggregation

---

cmd/pr-reminder/main.go
cmd/pr-reminder/main_test.go

When Pr Reminder slack tool lists PRs, this adds additional information if the PR is labeled as held (do-not-merge/hold).
for https://issues.redhat.com/browse/DPTP-3081
/cc smg247

DPTP-3081 prReminder add held label

---

cmd/result-aggregator/main.go
cmd/result-aggregator/main_test.go
pkg/results/report.go
pkg/results/report_test.go

This adds a PodScalerReporter as a way for sending http requests from pod-scaler-admission to result-aggregator.
for https://issues.redhat.com/browse/DPTP-3106
/cc smg247

DPTP-3106 Create PodScalerReporter

---

pkg/jobrunaggregator/jobrunaggregatoranalyzer/analyzer.go
pkg/jobrunaggregator/jobrunaggregatorlib/spyglass_summary.go
pkg/jobrunaggregator/jobrunaggregatorlib/util.go
pkg/jobrunaggregator/jobruntestcaseanalyzer/analyzer.go

Regarding [TRT-562](https://issues.redhat.com//browse/TRT-562)
Apparently, the name of the `job-run-summary.html` file is used as the title for the accordion menu in aggregated jobs.
For test analyzer aggregated jobs, there are several variants and so the title is always the same; this makes it hard to find results for a specific variant.
This PR names the `job-run-summary.html` with more text that is indicative of the variant to make it easier to look at the job results.  There will be no difference for the origin aggregated jobs.

Add title for test analyzer variant to enhance readability

---

pkg/steps/rpm_server.go

During extreme scale up events on build farms, particularly when clouds are low on capacity, it may take a long time for pods to be scheduled. It's normally counter productive for jobs to fail because of an rpm server timeout, so increase this timeout significantly.

Increase progress deadline for rpm server

---

cmd/pod-scaler/admission.go
cmd/pod-scaler/admission_test.go
cmd/pod-scaler/main.go
pkg/results/report.go
pkg/results/report_test.go
test/e2e/pod-scaler/run/consumer.go

Adds the ability to work with report credentials ([this PR](https://github.com/openshift/release/pull/32403)), and pod-scaler-admission can now send requests to result-aggregator using PodScalerReporter.
for https://issues.redhat.com/browse/DPTP-3106
/cc smg247

DPTP-3106 add reporter to admission

---

pkg/api/helper/imageextraction.go

Found a null pointer dereference while debugging some code.

Observer Pods: fix null pointer dereference

---

pkg/jobrunaggregator/jobrunaggregatoranalyzer/analyzer.go

We're extending the job limit to 8h in https://github.com/openshift/ci-tools/pull/3045
The aggregator's internal wait time was still 4h, thus we were still
timing out.

Bump aggregator to 6h at least temporarily.

---

cmd/sanitize-prow-jobs/main.go

Do as other programs which support arguments, such as `prowgen`.
```console
$ time sanitize-prow-jobs \
>     --prow-jobs-dir ci-operator/jobs \
>     --config-path core-services/sanitize-prow-jobs/_config.yaml
real    0m10.515s
user    1m11.742s
sys     0m2.853s
```
vs.
```console
$ time sanitize-prow-jobs \
>     --prow-jobs-dir ci-operator/jobs \
>     --config-path core-services/sanitize-prow-jobs/_config.yaml \
>     openshift/ci-tools
real    0m0.091s
user    0m0.106s
sys     0m0.020s
```

sanitize-prow-jobs: operate on subdirectories

---

pkg/prowgen/jobbase.go
pkg/prowgen/jobbase_test.go
pkg/prowgen/testdata/zz_fixture_TestNewProwJobBaseBuilderForTest_simple_container_based_test_with_arm01_cluster.yaml

The `ci-operator` in `arm01` cluster is being mirrored from apps.ci by the image distributor controller. The prowjob needs to pull from the `ci-arm64` namespace where the `ci-operator` image for arm64 architecture is being built.
/cc @danilo-gemoli @deepsm007 @openshift/test-platform 

[prowgen] override the ci-operator image for the arm01 cluster

---

cmd/cluster-init/main.go
cmd/cluster-init/update_bootstrap_secrets.go
test/integration/cluster-init/create/expected/core-services/ci-secret-bootstrap/_config.yaml
test/integration/cluster-init/update/expected/core-services/ci-secret-bootstrap/_config.yaml

The breaking will be fixed by https://github.com/openshift/release/pull/32833
As far as I can tell, the secret is used only in the tests of `ci-tools`:
https://github.com/openshift/release/blob/70499fc48ae9e4bbdc621dee9820ddd4c02d433f/ci-operator/config/openshift/ci-tools/openshift-ci-tools-master.yaml#L765
The verification will be in two steps:
1. add the tokenFile to the secret but the config file is still with `token`.
2. use the tokenFile in the config file.
We have to do this PR first because otherwise the build-clusters job would fail in 
https://github.com/openshift/release/pull/32642

Use token file in secret test-credentials/ci-operator
