openshift/ci-tools

cmd/autoconfigbrancher/main.go, cmd/private-prow-configs-mirror/main.go
Ref https://issues.redhat.com/browse/DPTP-2256
=> Private config mirror: Shard plugin config

pkg/steps/cluster_claim.go, pkg/steps/cluster_claim_test.go, pkg/steps/multi_stage.go, pkg/steps/multi_stage_test.go, pkg/steps/pod.go, pkg/steps/testdata/zz_fixture_envTestGetPodObjectMounts_with_cluster_claim.yaml, pkg/steps/testdata/zz_fixture_mountsTestGetPodObjectMounts_with_cluster_claim.yaml, pkg/steps/testdata/zz_fixture_volumesTestGetPodObjectMounts_with_cluster_claim.yaml, pkg/steps/utils/labels.go, test/e2e/multi-stage/cluster-claim.yaml
https://issues.redhat.com/browse/DPTP-2332
=> Name claim's secrets by test

pkg/prowconfigsharding/prowconfigsharding.go, pkg/prowconfigsharding/prowconfigsharding_test.go
This PR adds bugzilla config sharding for the `determinize-prow-config`.
command.
=> DPTP-2209: prowconfigsharding: add bugzilla sharding

cmd/cluster-display/main.go, cmd/cluster-display/main_test.go, pkg/api/constant.go, pkg/api/types.go
https://issues.redhat.com/browse/DPTP-2242
=> Add a new tool: cluster-displayer

pkg/controller/test-images-distributor/test_images_distributor.go, pkg/controller/test-images-distributor/test_images_distributor_test.go
When adding the functionality to trigger on index changes in
4d3bb5c500f7befb8f955b71f0b860abcf4a130e I didn't realize that the index
can also contain imagestreams instead of imagestreamtags, because for
ReleaseTagConfigurations we start distributing the whole stream. This
change fixes that.
=> Test imagestream distributor config change: Cope with imagestream

Makefile
https://issues.redhat.com/browse/DPTP-2303
=> Run integration tests 25 times in CI to detect flakes

cmd/determinize-prow-config/main.go, cmd/determinize-prow-config/main_test.go
Ref https://issues.redhat.com/browse/DPTP-2293
You can see this in action here: https://github.com/openshift/release/pull/19395
One drawback is that this results in a huge amount of duplication and might make branch cutting harder.
=> Shard tide queries

Makefile, pkg/prowconfigsharding/prowconfigsharding.go, pkg/prowconfigsharding/prowconfigsharding_test.go, test/integration/repo-init/expected/core-services/prow/02_config/_plugins.yaml, test/integration/repo-init/expected/core-services/prow/02_config/openshift/_pluginconfig.yaml, test/integration/repo-init/expected/core-services/prow/02_config/org/other/_pluginconfig.yaml, test/integration/repo-init/expected/core-services/prow/02_config/org/repo/_pluginconfig.yaml, test/integration/repo-init/expected/core-services/prow/02_config/org/third/_pluginconfig.yaml
Based on top of https://github.com/openshift/ci-tools/pull/2089
=> Shard lgtm plugin config

pkg/api/config.go, pkg/api/types.go, pkg/defaults/defaults.go, pkg/defaults/defaults_test.go, pkg/steps/bundle_source.go, pkg/steps/cluster_claim.go, pkg/steps/index_generator.go, pkg/steps/multi_stage.go, pkg/steps/utils/clusterpool.go, pkg/validation/config.go, pkg/validation/config_test.go, pkg/validation/test.go, pkg/validation/test_test.go, pkg/webreg/zz_generated.ci_operator_reference.go, test/e2e/multi-stage/cluster-claim.yaml, test/e2e/multi-stage/e2e_test.go
This reverts commit 2d35de23b3b31db4274cfb3151d2f0765f4e041a, reversing
changes made to 1501edbaa91360e18724f83968cc8957ee2ad03c.
It also adds a commit that fixes the nil pointer error that caused the
original PR to be reverted along with a test.
/cc @bbguimaraes @stevekuznetsov
=> Revert "Merge pull request #2092 from openshift/revert-2074-import-claim-release"

pkg/defaults/defaults.go, pkg/steps/input_env.go, pkg/steps/input_env_test.go, pkg/steps/output_image_tag.go, pkg/steps/release/import_release.go, pkg/validation/test.go, pkg/validation/test_test.go
Minor things found while working on https://github.com/openshift/ci-docs/pull/156.
=> Minor fixes

pkg/prowconfigsharding/prowconfigsharding.go
fixes: https://github.com/openshift/release/blob/master/core-services/prow/02_config/openshift-priv/bond-cni/_pluginconfig.yaml#L6-L141
=> add only one lgtm configuration on a sharded config

cmd/repo-init/main.go, pkg/api/types.go, pkg/prowgen/prowgen.go, pkg/validation/test.go
=> *: Add ClusterProfileAWSArm64

cmd/ci-secret-generator/main.go, cmd/ci-secret-generator/main_test.go, pkg/api/secretgenerator/secretgenerator.go, pkg/api/secretgenerator/testdata/TestLoadConfigFromPath/no_parameters.yaml, pkg/api/secretgenerator/testdata/TestLoadConfigFromPath/single_parameter.yaml, pkg/api/secretgenerator/testdata/TestLoadConfigFromPath/single_parameter_with_multiple_values.yaml, pkg/api/secretgenerator/testdata/TestLoadConfigFromPath/two_parameters_with_multiple_values.yaml, pkg/api/secretgenerator/testdata/zz_fixture_TestLoadConfigFromPath_no_parameters.yaml, pkg/api/secretgenerator/testdata/zz_fixture_TestLoadConfigFromPath_single_parameter.yaml, pkg/api/secretgenerator/testdata/zz_fixture_TestLoadConfigFromPath_single_parameter_with_multiple_values.yaml, pkg/api/secretgenerator/testdata/zz_fixture_TestLoadConfigFromPath_two_parameters_with_multiple_values.yaml, test/e2e/secret-generator/bootstrap.yaml, test/e2e/secret-generator/generator.yaml
follow-up of https://github.com/openshift/release/pull/19683
=> Remove deprecated fields from secret-generator

pkg/testhelper/accessory.go
=> testhelper: expose some useful functions

Makefile, test/e2e/framework/ci-operator.go, test/e2e/framework/framework.go, test/e2e/framework/test.go
=> e2e: use a separate tag for e2e framework

cmd/pod-scaler/main.go
=> pod-scaler: fix --produce-once behavior

cmd/pod-scaler/producer.go
=> pod-scaler: log how much we gathered in one query

cmd/ci-secret-bootstrap/main_test.go, pkg/api/secretbootstrap/secretboostrap.go, test/e2e/secret-generator/bootstrap.yaml
follow-up of https://github.com/openshift/release/pull/19672
=> Remove unused and deprecated fields from ci-secret-bootstrap

pkg/pod-scaler/types.go
=> pod-scaler: ignore NaN values from Prometheus

cmd/private-org-sync/main.go, cmd/private-org-sync/main_test.go
GitHub occasionally flakes, retry few times before we alert.
```
error="ls-remote failed: (exit code=128 output=fatal: unable to access 'https://github.com/openshift/kubernetes-kubelet/': Failed to connect to github.com port 443: Connection timed out\n)"
```
https://prow.ci.openshift.org/view/gs/origin-ci-test/logs/periodic-openshift-release-private-org-sync/1408364492290527232#1:build-log.txt%3A5005
=> private-org-sync: retry ls-remote with exponential backoff

cmd/ci-operator-checkconfig/main.go, pkg/load/load.go, pkg/validation/config.go, pkg/validation/test.go, pkg/validation/test_test.go
This would have prevented https://github.com/openshift/ci-tools/pull/2118 if I
had not been a moron and merged the two branches before I tested.
/hold
Includes/needs https://github.com/openshift/ci-tools/pull/2125.
=> ci-operator-checkconfig: validate resolved

cmd/autoowners/README.md
Catching up with 5d23ac7d24 (#634).
=> cmd/autoowners/README: Fix -config-subdirs -> -config-subdir references and update help text

cmd/cvp-trigger/main.go
Currently, the cvp-trigger utility is used to trigger and monitor Prow jobs that are used in the CVP operator bundle validation pipeline.  Because of a known OpenShift/AWS network interaction bug, an intermittent failure in connection can happen while the Prow Job is running. It has been determined that, while the connection from cvp-trigger gets refused, the Prow Job continues to run without issue and finishes to completion, while the cvp-trigger run gets re-triggered on the CVP side, causing unnecessary delays in the operator testing pipeline.
This MR adds a retry feature to the prow job creation code that retries up to ten times with exponential backoff.
=> [CVP-2012] Make the cvp-trigger utility resistent to refused Prow connections

cmd/ci-operator-checkconfig/main.go
One done signal was missed, fixes the data race seen in:
https://prow.ci.openshift.org/log?container=test&id=1410645943761506304&job=rehearse-19893-pull-ci-openshift-ci-tools-master-checkconfig
Add an extra message to the error which also got lost somehow in the
original.
=> ci-operator-checkconfig: correct synchronization

images/sprint-automation/Dockerfile
=> sprint-automation: add an image build

pkg/defaults/defaults.go
We label the output images we build with the versions of the inputs that
were used to build them, in order to be able to detect when an input has
changed so that we do not use a cached image in error. When we build on
top of a cache, however, we end up recording the cache as the input,
since we're built on top of it. However, we only know how to check for
input changes from the actual root. By not building on top of caches
when we're about to promote new caches, we side-step this issue.
=> ci-operator: don't use the root cache when building new caches

cmd/sprint-automation/main.go
=> sprint-automation: search only private channels

pkg/api/types.go, pkg/release/candidate/client.go, pkg/release/candidate/client_test.go, pkg/release/prerelease/client_test.go, pkg/validation/release.go, pkg/validation/release_test.go
=> Archs: Add arm64

cmd/dptp-pools-cm/main.go, hack/run-dptp-pools-cm.sh, pkg/controller/cluster_pools_pull_secret_provider/README.md, pkg/controller/cluster_pools_pull_secret_provider/cluster_pools_pull_secret_provider.go, pkg/controller/cluster_pools_pull_secret_provider/cluster_pools_pull_secret_provider_test.go, pkg/util/secret.go, pkg/util/secret_test.go
https://issues.redhat.com/browse/DPTP-2353
=> Add a new cli: dptp-pools-cm

cmd/sprint-automation/main.go
sprint-automation: DRY out issue rendering
---
sprint-automation: manage user groups
---
=> sprint-automation: manage user groups

hack/install.sh
=> hack: make production installs verbose

cmd/ci-operator/main.go, pkg/api/constant.go, pkg/defaults/defaults.go, pkg/defaults/defaults_test.go, pkg/steps/cluster_claim.go, pkg/steps/cluster_claim_test.go
/hold
will check the artifact folder in e2e.
=> Save artifacts in cluster claim step

pkg/testhelper/testhelper.go
=> testhelper: allow configuring the file extension

go.mod, go.sum, vendor/k8s.io/test-infra/prow/config/branch_protection.go, vendor/k8s.io/test-infra/prow/config/config.go, vendor/k8s.io/test-infra/prow/config/prow-config-documented.yaml, vendor/k8s.io/test-infra/prow/crier/reporters/github/reporter.go, vendor/modules.txt
Needed to be able to use https://github.com/kubernetes/test-infra/pull/22886
=> Bump test-infra to f8dbf1fd3d25

cmd/sprint-automation/main.go
We do not have secondary on-call members on the weekend, so when this
tool runs there it fails quickly. Instead, we can just gloss over that
entry and post the rest of them anyway.
=> sprint-automation: don't fail when no roles are found

pkg/steps/release/import_release.go
=> ci-operator: tolerate existing CLI override import

pkg/steps/cluster_claim.go
We can't DRY out this logic since the conditions are unique structs with
the same fields instead of any construct that shares the definition.
=> ci-operator: expose hive conditions on failure

pkg/api/types.go, pkg/prowgen/prowgen.go, pkg/prowgen/prowgen_test.go, pkg/prowgen/testdata/zz_fixture_TestGeneratePodSpecMultiStage_ibmcloud_cluster_profile.yaml, pkg/validation/test.go
Add support for IBM Cloud CI via a new cluster profile.
=> Add ibmcloud cluster profile

cmd/pod-scaler/admission.go, cmd/pod-scaler/admission_test.go, cmd/pod-scaler/main.go, test/e2e/pod-scaler/run/consumer.go
=> pod-scaler: turn off resource mutation by default

hack/check-test-infra-version.sh
=> hack: fix script for test-infra validation

cmd/repo-init/main.go, pkg/api/types.go, pkg/prowgen/prowgen.go, pkg/validation/test.go
Adding azurestack cluster profile for e2e-azurestack tests in CI.
=> azurestack: Add azurestack cluster profile for CI tests

cmd/determinize-prow-config/main.go
The changes we introduced in https://github.com/openshift/release/pull/20525. This PR just fix the codegen.
/cc @openshift/openshift-team-developer-productivity-platform
=> Abuse determinize-prow-config to implement 4.9 FF (no merge)

cmd/vault-secret-collection-manager/main.go, cmd/vault-secret-collection-manager/main_test.go
This changes the secret collection manager to:
* Produce a policy that allows deleting secrets
* Periodically reconcile all policies, so existing policies will get
updated
Ref https://issues.redhat.com/browse/DPTP-2207
=> Vault: Allow deleting secrets

cmd/determinize-prow-config/main.go
Reverts openshift/ci-tools#2188
The PR was not intended to merge.
=> Revert "Abuse determinize-prow-config to implement 4.9 FF (no merge) + FIX"

cmd/ci-secret-bootstrap/main.go, cmd/ci-secret-bootstrap/main_test.go
Found it https://prow.ci.openshift.org/view/gs/origin-ci-test/pr-logs/pull/openshift_release/20469/pull-ci-openshift-release-ci-secret-bootstrap-config-validation/1420121837651628032
=> secret-bootstrap: fix a validation bug

go.mod, go.sum, vendor/k8s.io/test-infra/prow/apis/prowjobs/v1/types.go, vendor/k8s.io/test-infra/prow/config/config.go, vendor/k8s.io/test-infra/prow/config/tide.go, vendor/k8s.io/test-infra/prow/crier/reporters/github/reporter.go, vendor/k8s.io/test-infra/prow/gerrit/client/client.go, vendor/k8s.io/test-infra/prow/plugins/override/override.go, vendor/modules.txt
Needs
* https://github.com/openshift/ci-chat-bot/pull/188
* https://github.com/openshift/release-controller/pull/294
=> Bump test-infra to 01baa4728fcb

Makefile, cmd/promoted-image-governor/main.go, cmd/promoted-image-governor/main_test.go
https://issues.redhat.com/browse/DPTP-1766
=> Add a new tool: promoted-image-governor

cmd/promoted-image-governor/main.go
=> image-governor: Add some debug logs

cmd/sprint-automation/main.go
=> sprint-automation: add docs links

cmd/ci-secret-bootstrap/main_test.go, pkg/secrets/vault.go
Ref https://issues.redhat.com/browse/DPTP-2415
=> Secret bootstrap: Allow multiple items to reference different keys in the same secret

cmd/ci-operator-checkconfig/main.go, cmd/ci-operator-prowgen/main.go, cmd/determinize-ci-operator/main.go, pkg/config/options.go, pkg/config/options_test.go, pkg/config/testdata/config/foo/bar/foo-bar-master.yaml, pkg/config/testdata/config/foo/bar/foo-bar-release-4.9.yaml, pkg/config/testdata/config/super/duper/super-duper-master.yaml, pkg/config/testdata/config/super/duper/super-duper-release-4.9.yaml
=> [DPTP-2280] Add options to determine and operate only on changed files

test/e2e/multi-stage/e2e_test.go
The fix has been deployed.
/hold
See if the rehearsal passes.
=> Enable the e2e tests with the fake pool

cmd/repo-init/main.go, pkg/api/types.go, pkg/prowgen/prowgen.go, pkg/validation/test.go
Adding ClusterProfile Alibaba.
=> Adding ClusterProfile Alibaba

Makefile, cmd/promoted-image-governor/main.go, cmd/promoted-image-governor/main_test.go
https://issues.redhat.com/browse/DPTP-1766
See https://github.com/openshift/release/pull/20824
=> image-governor: generate image mirror mapping files for origin

pkg/defaults/defaults.go
Second attempt, after https://github.com/openshift/ci-tools/pull/2205.
Changes made more localized since defaulting affected other tools.
=> pkg/defaults: do not modify configuration

Makefile
=> Makefile: add dummy targets for front-end checks

pkg/prowgen/prowgen.go, pkg/validation/test.go
=> Finish adding new mecha profiles

pkg/defaults/defaults.go, test/e2e/simple/e2e_test.go
When a user provides `$RELEASE_IMAGE_foo` they are only specifying the
release payload to import, so we need to figure out if we need an
override CLI to do it in all cases.
Fixes [DPTP-2434](https://issues.redhat.com/browse/DPTP-2434)
/cc @deepsm007 @bradmwilliams
=> ci-operator: always resolve an override CLI image

cmd/promoted-image-governor/main.go
The current logs of the job are a bit spammy.
=> promoted-image-governor: refine the log level

Makefile, cmd/pod-scaler/frontend/src/app/store.ts
I was trying to be clever to get around a type error but the error was
not real and the workaround did not work.
=> pod-scaler-ui: fix redux setter

pkg/steps/release/promote.go
=> ci-operator: make promotion namespace creation best-effort

test/e2e/simple/e2e_test.go
Ref https://issues.redhat.com/browse/DPTP-2422
=> E2E tests: Retry requests to cincinatti

cmd/sprint-automation/main.go
/cc @openshift/test-platform @stevekuznetsov 
=> DPTP-2451 Don't include obsolete cards for the intake role

cmd/ci-operator-configresolver/main.go
Currently the readyness server and the actual data server race with each
other, allowing clients to observe the first but not the second being
ready.
Ref https://issues.redhat.com/browse/DPTP-2363
=> Configresolver: Don't get ready until server is up

pkg/api/constant.go, pkg/api/leases.go, pkg/api/leases_test.go, pkg/api/types.go, pkg/defaults/defaults.go, pkg/defaults/defaults_test.go, pkg/prowgen/prowgen.go, pkg/prowgen/prowgen_test.go, pkg/prowgen/testdata/zz_fixture_TestGeneratePodSpecMultiStage_test_step_with_lease.yaml, pkg/prowgen/testdata/zz_fixture_TestGeneratePodSpecMultiStage_test_with_lease.yaml, pkg/steps/lease.go, pkg/steps/lease_test.go
[DPTP-1989](https://issues.redhat.com/browse/DPTP-1989): Make sure that we add boskos client args/mounts if any test step has a lease.
=> DPTP-1989: Make sure that we add boskos client args/mounts if any test step has a lease.

cmd/autoconfigbrancher/main.go, cmd/ci-operator-config-mirror/main.go, cmd/config-shard-validator/main.go, cmd/private-org-sync/main.go, cmd/private-org-sync/main_test.go, cmd/private-prow-configs-mirror/main.go, images/ci-operator-config-mirror/Dockerfile, images/config-shard-validator/Dockerfile, images/private-prow-configs-mirror/Dockerfile, test/integration/ci-operator-config-mirror.sh
follow-up of https://github.com/openshift/ci-tools/pull/2137
=> Add options to allow processing only the changed files to the rest of the tools

go.mod, go.sum, vendor/k8s.io/test-infra/prow/kube/config.go, vendor/modules.txt
=> Upgrade test-infra to 85d839e08600

cmd/prcreator/README.md, cmd/prcreator/main.go
Ref https://issues.redhat.com/browse/DPTP-2443
Very simplistic because pretty much all of the logic already exists.
=> Add a CLI to create PRs

cmd/ci-secret-bootstrap/main.go, cmd/cluster-display/main.go, cmd/dptp-controller-manager/main.go, cmd/dptp-pools-cm/main.go, cmd/pj-rehearse/main.go, cmd/pod-scaler/main.go, cmd/serviceaccount-secret-rotation-trigger/main.go, cmd/vault-subpath-proxy/main.go, pkg/util/client.go, pkg/util/client_test.go, pkg/util/testdata/load_from_kubeconfig/kubeconfig, pkg/util/testdata/load_from_kubeconfigDir/1.yaml, pkg/util/testdata/load_from_kubeconfigDir/2.yaml
/cc @stevekuznetsov @alvaroaleman 
/hold
wait for https://github.com/openshift/ci-tools/pull/2282
=> Load kubeconfig files from a directory

cmd/dptp-controller-manager/main.go, cmd/dptp-pools-cm/main.go, cmd/promoted-image-governor/main.go
To avoid the conflict of flags from the imported pkg.
=> Create a new flagSet

test/integration/ci-operator-prowgen/input/config/legacy/branches-separate-files/legacy-branches-separate-files-branch.yaml, test/integration/ci-operator-prowgen/input/config/legacy/branches-separate-files/legacy-branches-separate-files-master.yaml, test/integration/ci-operator-prowgen/input/config/legacy/random-file/legacy-random-file-master.yaml, test/integration/ci-operator-prowgen/input/jobs/legacy/branches-separate-files/legacy-branches-separate-files-branch-presubmits.yaml, test/integration/ci-operator-prowgen/input/jobs/legacy/branches-separate-files/legacy-branches-separate-files-master-presubmits.yaml, test/integration/ci-operator-prowgen/input/jobs/legacy/random-file/legacy-random-file-periodics.yaml, test/integration/ci-operator-prowgen/input/jobs/super/duper/super-duper-master-presubmits.yaml, test/integration/ci-operator-prowgen/output/jobs/legacy/branches-separate-files/legacy-branches-separate-files-branch-presubmits.yaml, test/integration/ci-operator-prowgen/output/jobs/legacy/branches-separate-files/legacy-branches-separate-files-master-presubmits.yaml, test/integration/ci-operator-prowgen/output/jobs/legacy/random-file/legacy-random-file-master-periodics.yaml, test/integration/ci-operator-prowgen/output/jobs/legacy/random-file/legacy-random-file-periodics.yaml
See https://github.com/openshift/ci-tools/pull/2304.
=> ci-operator-prowgen: add more integration tests

pkg/config/load.go, pkg/registry/resolver.go
Uses the same diamond fork-join pattern as `ci-operator-checkconfig`.
See https://github.com/openshift/ci-tools/pull/2304.
=> pkg/config: load in parallel

Makefile, cmd/promoted-image-governor/main.go
https://issues.redhat.com/browse/DPTP-2472
=> Explain why a tag on a promoted image stream exists

pkg/api/types.go, pkg/prowgen/prowgen.go, pkg/prowgen/prowgen_test.go, pkg/prowgen/testdata/zz_fixture_TestGeneratePodSpecMultiStage_a_ure_2_cluster_profile.yaml, pkg/validation/test.go
https://issues.redhat.com/browse/DPTP-2466
=> Add cluster profile for the 2nd azure account

pkg/api/constant.go, pkg/prowgen/prowgen.go, pkg/prowgen/prowgen_test.go, pkg/prowgen/testdata/zz_fixture_TestGenerateJobBase_private_jobs_that_clone_should_contain_oauth_token_secret_config.yaml, pkg/prowgen/testdata/zz_fixture_TestGeneratePodSpec_private_job_with_skip_cloning_false.yaml, test/integration/ci-operator-prowgen/input/config/private-org/super/private-org-super-master.yaml, test/integration/ci-operator-prowgen/output/jobs/private-org/super/private-org-super-master-presubmits.yaml
=> Make private jobs to use the oauth volume defined in decoration config

pkg/steps/project_image.go
The previous attempt at DRY was wrong.
=> pkg/steps: revert project image changes

pkg/api/types.go, pkg/jobconfig/files.go, pkg/prowgen/prowgen.go, pkg/prowgen/prowgen_test.go, pkg/prowgen/testdata/zz_fixture_TestGeneratePresubmitForTest_optional_presubmit.yaml, pkg/validation/test.go, pkg/validation/test_test.go, test/integration/ci-operator-prowgen/input/config/super/duper/super-duper-master.yaml, test/integration/ci-operator-prowgen/output/jobs/super/duper/super-duper-master-presubmits.yaml
https://issues.redhat.com/browse/DPTP-2501
=> Add a specification for optional jobs in ci-operator configuration

cmd/pod-scaler/admission.go, cmd/pod-scaler/admission_test.go
Only when we're rehearsing `ci-operator` jobs can we know the metadata
we need to auto-scale.
Fixes [DPTP-2490](https://issues.redhat.com/browse/DPTP-2490)
Ex:
```
2021-09-03T10:08:23Z  error    pod-scaler admission     msg=Failed to handle rehearsal Pod., error=could not find $CONFIG_SPEC in the environment of the rehearsal Pod's test container, $ENTRYPOINT_OPTIONS is running /app/prow/cmd/invitations-accepter/app.binary, not ci-operator
2021-09-03T10:08:23Z  error    pod-scaler admission     msg=Failed to handle rehearsal Pod., error=could not find $CONFIG_SPEC in the environment of the rehearsal Pod's test container, $ENTRYPOINT_OPTIONS is running /checkconfig, not ci-operator
```
/assign @openshift/test-platform
=> pod-scaler: admission: ignore non-ci-operator rehearsals

cmd/cluster-display/main.go
=> cluster-display: Use flagutil.KubernetesOptions

pkg/prowconfigsharding/prowconfigsharding.go, pkg/prowconfigsharding/prowconfigsharding_test.go
Ref https://issues.redhat.com/browse/DPTP-2405
=> Shard labels.restricted_labels

cmd/pod-scaler/main.go
=> pod-scaler: Use flagutil.KubernetesOptions

cmd/dptp-pools-cm/main.go
=> dptp-pools-cm: use inClusterConfig

cmd/pj-rehearse/main.go
=> pj-rehearse: Use flagutil.KubernetesOptions

cmd/config-brancher/main.go, test/integration/config-brancher/expected/org/bump/org-bump-master__releases.yaml, test/integration/config-brancher/expected/org/bump/org-bump-release-4.5__releases.yaml, test/integration/config-brancher/expected/org/bump/org-bump-release-4.6__releases.yaml, test/integration/config-brancher/input/org/bump/org-bump-master__releases.yaml
Part of [DPTP-2431](https://issues.redhat.com/browse/DPTP-2431)
=> config-brancher: honor releases.integration

go.mod, go.sum, vendor/k8s.io/test-infra/prow/flagutil/kubernetes_cluster_clients.go, vendor/modules.txt
Need
https://github.com/openshift/release-controller/pull/311
and
https://github.com/openshift/ci-chat-bot/pull/204
=> bump test-infra to 7cf307fffca5

cmd/ci-operator-config-mirror/main.go, cmd/ci-operator-config-mirror/main_test.go, test/integration/ci-operator-config-mirror/input-to-clean/foo/barry-white/foo-barry-white-official__releases.yaml, test/integration/ci-operator-config-mirror/input/foo/barry-white/foo-barry-white-official__releases.yaml, test/integration/ci-operator-config-mirror/output-only-super/foo/barry-white/foo-barry-white-official__releases.yaml, test/integration/ci-operator-config-mirror/output/foo/barry-white/foo-barry-white-official__releases.yaml, test/integration/ci-operator-config-mirror/output/super-priv/barry-white/super-priv-barry-white-official__releases.yaml
Part of [DPTP-2431](https://issues.redhat.com/browse/DPTP-2431)
=> ci-operator-config-mirror: honor releases.integration

cmd/serviceaccount-secret-rotation-trigger/main.go
=> serviceaccount-secret-rotation-trigger: Use flagutil.KubernetesOptions

pkg/validation/test.go, pkg/validation/test_test.go
Part of [DPTP-2431](https://issues.redhat.com/browse/DPTP-2431)
/assign @openshift/test-platform
=> validation: allow releases as well as tag_spec

cmd/ci-secret-bootstrap/main.go, cmd/ci-secret-bootstrap/main_test.go
=> ci-secret-bootstrap: Use flagutil.KubernetesOptions

cmd/ci-secret-bootstrap/main.go, cmd/ci-secret-bootstrap/main_test.go
https://issues.redhat.com/browse/DPTP-2452
=> DPTP-2452 [ci-secret-bootstrap] Delete the stale keys from the existing secrets

pkg/validation/config.go
=> validation: correctly populate releases

cmd/serviceaccount-secret-rotation-trigger/main.go
Follow up https://github.com/openshift/ci-tools/pull/2356
=> sa-secret-rotation-trigger: move Fatal logs to the main function

cmd/vault-subpath-proxy/main.go
=> vault-subpath-proxy: Use flagutil.KubernetesOptions

cmd/repo-init/main.go, pkg/api/types.go
=> add lease type for the azure-2 cluster profile and its missing references

cmd/dptp-controller-manager/main.go
=> dptp-cm: Use flagutil.KubernetesOptions

cmd/dptp-controller-manager/main.go
Easy myself if I can see this line of log.
=> dptp-cm: add logging for InClusterConfig

pkg/steps/release/import_release.go
This is the same logic we use in the override case. If we do not wait
for the tag to be imported, we risk racing with the admission cache and
creating Pods using this image name that are not resolved to the correct
image.
=> import_release: wait for CLI tag to import

pkg/steps/clusterinstall/OWNERS
=> OWNERS: Prune crawford

Makefile, cmd/dptp-controller-manager/main.go, cmd/promoted-image-governor/main.go, cmd/promoted-image-governor/main_test.go
https://issues.redhat.com/browse/DPTP-2480
=> promoted-image-governor: prune images on build farm

cmd/cluster-init/update_jobs.go, test/integration/cluster-init/create/expected/ci-operator/jobs/openshift/release/openshift-release-master-periodics.yaml, test/integration/cluster-init/create/expected/ci-operator/jobs/openshift/release/openshift-release-master-postsubmits.yaml, test/integration/cluster-init/create/expected/ci-operator/jobs/openshift/release/openshift-release-master-presubmits.yaml, test/integration/cluster-init/create/input/ci-operator/jobs/openshift/release/openshift-release-master-periodics.yaml, test/integration/cluster-init/create/input/ci-operator/jobs/openshift/release/openshift-release-master-postsubmits.yaml, test/integration/cluster-init/update/expected/ci-operator/jobs/openshift/release/openshift-release-master-periodics.yaml, test/integration/cluster-init/update/expected/ci-operator/jobs/openshift/release/openshift-release-master-postsubmits.yaml, test/integration/cluster-init/update/expected/ci-operator/jobs/openshift/release/openshift-release-master-presubmits.yaml, test/integration/cluster-init/update/input/ci-operator/jobs/openshift/release/openshift-release-master-periodics.yaml, test/integration/cluster-init/update/input/ci-operator/jobs/openshift/release/openshift-release-master-postsubmits.yaml
- handle build01, build02, vsphere
- fix the diff
=> Regulate the existing applyconfig jobs

cmd/cluster-init/README.md
=> create readme for cluster-init tool

images/cluster-init/Dockerfile
=> create image for cluster-init tool

images/cluster-init/Dockerfile
=> add diffutils to cluster-init image

cmd/autoconfigbrancher/main.go, cmd/autoowners/README.md, cmd/autoowners/main.go, cmd/autoowners/main_test.go, cmd/autotestgridgenerator/main.go
=> Rename test-platform github team name

cmd/ci-operator/main.go, cmd/ci-operator/main_test.go, pkg/api/constant.go
https://issues.redhat.com/browse/DPTP-1840
=> Make m(github_login)=kerberos_id as ci-op-xxxx's admin

pkg/jobrunaggregator/jobtableprimer/jobs.go
=> add new ovn job to aggregate

cmd/ldap-users-from-github-owners-files/README.md, cmd/ldap-users-from-github-owners-files/main.go, cmd/ldap-users-from-github-owners-files/main_test.go
=> Generate the mapping m(github_login)=kerberos_id

Makefile, cmd/github-ldap-user-group-creator/README.md, cmd/github-ldap-user-group-creator/main.go, cmd/github-ldap-user-group-creator/main_test.go
https://issues.redhat.com/browse/DPTP-1840
=> a new tool: github-ldap-user-group-creator

pkg/jobrunaggregator/jobrunaggregatoranalyzer/analyzer.go, pkg/jobrunaggregator/jobrunaggregatoranalyzer/pass_fail.go, pkg/jobrunaggregator/jobrunaggregatoranalyzer/spyglass_summary.go
Creates an html summary we'll be able to add to spyglass
=> write html status for aggregator

cmd/ci-operator/main.go, cmd/ci-operator/main_test.go, cmd/github-ldap-user-group-creator/main.go, pkg/api/constant.go
The first commit reverts https://github.com/openshift/ci-tools/pull/2398/files
https://issues.redhat.com/browse/DPTP-1840
=> ci-op: use group <author>-group in rolebinding/ci-op-author-access

pkg/jobconfig/files.go, pkg/jobconfig/files_test.go
The change should allow https://github.com/openshift/release/pull/22494 to pass
=> shard-validator: allow sharding master job shard further

cmd/bugzilla-mass-cloner/README.md, cmd/bugzilla-mass-cloner/main.go, cmd/bugzilla-mass-cloner/main_test.go
needs https://github.com/kubernetes/test-infra/pull/23695 + vendor update.
/hold
=> Initial commit for the bugzilla mass cloner tool

cmd/ldap-users-from-github-owners-files/main.go
- Use possibly uppercase for the mapping
- Convert them to lowercase after saving the mapping
=> ldap mapping file: do not convert the github users to lowercase

pkg/jobrunaggregator/jobrunaggregatoranalyzer/spyglass_summary.go
=> Style aggregation pages + make links open in a new tab/window

pkg/prowgen/prowgen_test.go, pkg/prowgen/testdata/zz_fixture_TestGenerateJobs_Promotion_configuration_causes_promote_job_with_unique_targets.yaml, pkg/prowgen/testdata/zz_fixture_TestGenerateJobs_cluster_label_for_periodic.yaml
Several cases overlooked in https://github.com/openshift/ci-tools/pull/2424
=> prowgen: sort more test fixtures

cmd/payload-testing-prow-plugin/filetestresolver.go, cmd/payload-testing-prow-plugin/filetestresolver_test.go, cmd/payload-testing-prow-plugin/main.go, cmd/payload-testing-prow-plugin/rcjobresolver.go, cmd/payload-testing-prow-plugin/server.go, cmd/payload-testing-prow-plugin/server_test.go, cmd/payload-testing-prow-plugin/testdata/config/openshift-api-master.yaml, cmd/payload-testing-prow-plugin/testdata/config/openshift-release-master__nightly-4.10.yaml, pkg/api/types.go
https://issues.redhat.com/browse/DPTP-2540
=> payload testing: create PullRequestPayloadQualificationRun

cmd/payload-testing-prow-plugin/filetestresolver.go, cmd/payload-testing-prow-plugin/filetestresolver_test.go
To fix https://github.com/openshift/ci-tools/pull/2453#issuecomment-956707225
The unit tests were right there and I did not catch it.
=> payload-testing-prow-plugin: fix filetestresolver

pkg/api/constant.go, pkg/dispatcher/config.go, pkg/dispatcher/config_test.go, pkg/dispatcher/testdata/TestLoadConfig/good_config_with_build_farm_with_jobs.yaml, pkg/prowgen/prowgen.go, pkg/prowgen/prowgen_test.go
https://issues.redhat.com/browse/DPTP-2586
=> Dispatch no-builds jobs to build03

cmd/payload-testing-prow-plugin/filetestresolver.go, cmd/payload-testing-prow-plugin/filetestresolver_test.go, cmd/payload-testing-prow-plugin/main.go, cmd/payload-testing-prow-plugin/rcjobresolver.go, cmd/payload-testing-prow-plugin/rcjobresolver_test.go, cmd/payload-testing-prow-plugin/server.go, cmd/payload-testing-prow-plugin/server_test.go, pkg/release/candidate/client.go, pkg/release/candidate/client_test.go, pkg/release/config/client.go, pkg/release/config/client_test.go
https://issues.redhat.com/browse/DPTP-2540
Will rebase after https://github.com/openshift/ci-tools/pull/2448
Require https://github.com/openshift/release-controller/pull/334
=> Use release controller to resolve jobs

cmd/payload-testing-prow-plugin/server.go, cmd/payload-testing-prow-plugin/server_test.go
https://issues.redhat.com/browse/DPTP-2540
=> payload-testing-prow-plugin: feed PullRequest

cmd/payload-testing-prow-plugin/server.go, cmd/payload-testing-prow-plugin/server_test.go
Will rebase after https://github.com/openshift/ci-tools/pull/2469
/hold
=> payload-testing-prow-plugin: feed ReleaseControllerConfig

pkg/controller/prpqr_reconciler/prpqr_reconciler.go, pkg/controller/prpqr_reconciler/prpqr_reconciler_test.go
=> generate prowjobs for each of the prpqr realease job spec items and improve tests

pkg/api/pullrequestpayloadqualification/v1/ci.openshift.io_pullrequestpayloadqualificationruns.yaml, pkg/api/pullrequestpayloadqualification/v1/types.go
=> add a short name for the pullrequestpayloadqualification CR

cmd/payload-testing-prow-plugin/main.go, cmd/payload-testing-prow-plugin/server.go, cmd/payload-testing-prow-plugin/server_test.go
https://issues.redhat.com/browse/DPTP-2606
/hold
need prepare the arg in the deployment.
=> payload-testing-prow-plugin: only collaborator can trigger runs

pkg/jobrunaggregator/jobrunaggregatorlib/ci_data_client.go
/hold
holding until I can review the logs to determine the failure modes that we see on read rate limiting for our uploader.
=> switch the testrun jobruns table to be the source of truth for what was uploaded

pkg/controller/prpqr_reconciler/prpqr_reconciler.go
=> fix a race when trying to update the prpqr object

pkg/controller/prpqr_reconciler/pjstatussyncer/pjstatussyncer.go
follow-up of https://github.com/openshift/ci-tools/pull/2486
=> fix a race when trying to update the prpqr object in pjstatussyncer controller

cmd/payload-testing-prow-plugin/main.go, cmd/payload-testing-prow-plugin/server.go
=> payload-testing-prow-plugin: add some debugging logs

cmd/blocking-issue-creator/main.go, cmd/blocking-issue-creator/main_test.go
Related to the changes done in https://github.com/openshift/release/pull/23503
=> Close the blocker issue when there is no blocked branch

cmd/payload-testing-prow-plugin/server.go, cmd/payload-testing-prow-plugin/server_test.go
=> Include a message with the UI link when commenting back to the PR

go.mod, go.sum, vendor/k8s.io/test-infra/prow/config/config.go, vendor/k8s.io/test-infra/prow/flagutil/strings.go, vendor/k8s.io/test-infra/prow/plugins/config.go, vendor/k8s.io/test-infra/prow/plugins/label/label.go, vendor/k8s.io/test-infra/prow/plugins/updateconfig/README.md, vendor/k8s.io/test-infra/prow/spyglass/architecture.md, vendor/modules.txt
Prerequisite for https://github.com/openshift/ci-tools/pull/2462
[DPTP-2577](https://issues.redhat.com/browse/DPTP-2577)
=> Bump test-infra to 74a5a2f770f3

pkg/api/types.go, pkg/prowgen/podspec.go, pkg/validation/test.go
[vsphere] Restrict cluster bot to only run on VMC - [SPLAT-338](https://issues.redhat.com/browse/SPLAT-338)
Adding new cluster-profile for cluster bot
=> Add Cluster Profile For Clusterbot

cmd/dptp-controller-manager/main.go, pkg/api/domain.go
https://issues.redhat.com/browse/DPTP-2626
=> dptp-controller-manager: detect forbidden registries

pkg/controller/prpqr_reconciler/prpqr_reconciler.go, pkg/controller/prpqr_reconciler/prpqr_reconciler_test.go
Before, the code was checking if a prowjob exists based on its name. This is incorrect because the `pj.Name` will always be different. 
This PR adds a label, when we create a `prowjob`, with information about the release job name. Example:
```yaml
pullrequestpayloadqualificationruns.ci.openshift.io: prpqr-test,
releaseJobName: periodic-ci-test-org-test-repo-test-branch-test-name
``` 
With the `releaseJobName` label we can make sure that a `prowjob` exists for a specific release job for a specific `prpqr`
Also test cases added.
=> prevent from creating prowjob when it is already exists based on labels

pkg/prowgen/jobbase.go, pkg/prowgen/jobbase_test.go, pkg/prowgen/prowgen.go, pkg/prowgen/testdata/zz_fixture_TestMiscellaneous_Cluster.yaml, pkg/prowgen/testdata/zz_fixture_TestMiscellaneous_PathAlias.yaml, pkg/prowgen/testdata/zz_fixture_TestMiscellaneous_Rehearsable.yaml, pkg/prowgen/testdata/zz_fixture_TestMiscellaneous_TestName.yaml, pkg/prowgen/testdata/zz_fixture_TestMiscellaneous_WithLabel.yaml, pkg/prowgen/testdata/zz_fixture_TestNewProwJobBaseBuilderForTest_simple_container_based_test_with_cluster.yaml
Add additional methods needed for interation into job-trigger-cm
Builds over https://github.com/openshift/ci-tools/pull/2483 so that one needs to merge first
/hold
=> prowgen jobbase builder: support clusters and labels

cmd/ci-secret-bootstrap/main.go, cmd/ci-secret-bootstrap/main_test.go
https://issues.redhat.com/browse/DPTP-2585
=> ci-secret-bootstrap: --secret-names

cmd/ci-secret-bootstrap/main.go, cmd/ci-secret-bootstrap/main_test.go
=> ci-secret-bootstrap: fix the secret-names flag

pkg/util/rbacs.go, pkg/util/rbacs_test.go
https://issues.redhat.com/browse/DPTP-2507
=> pkg/util/rbacs: propagate error messages

cmd/sprint-automation/main.go, cmd/sprint-automation/main_test.go
https://issues.redhat.com/browse/DPTP-1575
/hold
Need kubeconfigs on the job.
=> Remind triage of upgrading build02

pkg/api/constant.go, pkg/api/domain.go, pkg/validation/test.go
=> Allow build04 for a cluster name

pkg/dispatcher/config.go
Must be a result of reckless copy/paste
=> dispatcher: fix a bug on config.NoBuilds

cmd/sprint-automation/main.go
=> Better wording for the message to triage

pkg/controller/prpqr_reconciler/prpqr_reconciler.go
Instead of doing N `list` calls (one for each job in spec), we can `list` all Prowjobs belonging to the processed PRPQR and make a local index.
This reduces the surface for failures and simplifies the nested code.
=> job-trigger-cm: optimize the check for existing jobs

pkg/jobrunaggregator/jobrunaggregatoranalyzer/analyzer_disruption.go, pkg/jobrunaggregator/jobrunaggregatoranalyzer/pass_fail.go
This pushes the failed and not failed down into the check function.
=> refactor the disruption aggregation to be easier to extend

go.mod, go.sum, vendor/k8s.io/test-infra/prow/config/config.go, vendor/k8s.io/test-infra/prow/config/prow-config-documented.yaml, vendor/k8s.io/test-infra/prow/flagutil/jira.go, vendor/k8s.io/test-infra/prow/jira/jira.go, vendor/k8s.io/test-infra/prow/plugins/config.go, vendor/k8s.io/test-infra/prow/plugins/label/label.go, vendor/k8s.io/test-infra/prow/plugins/override/override.go, vendor/k8s.io/test-infra/prow/plugins/releasenote/releasenote.go, vendor/modules.txt
=> Update the test-infra vendors

pkg/jobrunaggregator/jobrunaggregatoranalyzer/analyzer_disruption.go, pkg/jobrunaggregator/jobrunaggregatoranalyzer/pass_fail.go
this will come in handy for conditional disruption tests.
/assign @stbenjam
=> add option to skip disruption evaluation

cmd/cluster-init/main.go, cmd/cluster-init/update_prow_plugin_config.go, cmd/cluster-init/update_prow_plugin_config_test.go, test/integration/cluster-init/create/expected/core-services/prow/02_config/_plugins.yaml, test/integration/cluster-init/create/input/core-services/prow/02_config/_plugins.yaml, test/integration/cluster-init/update/expected/core-services/prow/02_config/_plugins.yaml, test/integration/cluster-init/update/input/core-services/prow/02_config/_plugins.yaml
https://issues.redhat.com/browse/DPTP-2597
=> Cluster onboarding: Automate populating configMaps

hack/run-prow-job-dispatcher.sh
=> dispatch: remove duplicated flags in the test script

pkg/jobrunaggregator/jobrunaggregatoranalyzer/spyglass_summary.go
This isn't perfect, but it at least lets you see you have a problem
=> report failure summaries for jobs that dont' have enough attempts

pkg/controller/prpqr_reconciler/pjstatussyncer/pjstatussyncer.go, pkg/controller/prpqr_reconciler/pjstatussyncer/pjstatussyncer_test.go, pkg/controller/prpqr_reconciler/pjstatussyncer/testdata/zz_fixture_prpqr_TestReconcile_basic_case.yaml, pkg/controller/prpqr_reconciler/pjstatussyncer/testdata/zz_fixture_prpqr_TestReconcile_job_is_still_running.yaml, pkg/controller/prpqr_reconciler/pjstatussyncer/testdata/zz_fixture_prpqr_TestReconcile_previous_condition_exists.yaml
This change adds the `AllJobsFinished` condition if all jobs are finished.
=> Apply a condition when all jobs are finished in the pjstatussyncer controller

cmd/prow-job-dispatcher/main.go, pkg/dispatcher/config.go, pkg/dispatcher/config_test.go
/hold
will rebase after https://github.com/openshift/ci-tools/pull/2530/files
=> [DPTP-2650]Dispatch jobs to the e2e cloud

cmd/payload-testing-prow-plugin/rcjobresolver_test.go, cmd/payload-testing-prow-plugin/server.go, cmd/payload-testing-prow-plugin/server_test.go, pkg/api/pullrequestpayloadqualification/v1/ci.openshift.io_pullrequestpayloadqualificationruns.yaml, pkg/api/pullrequestpayloadqualification/v1/types.go, pkg/release/config/client.go
in the effort of https://issues.redhat.com/browse/DPTP-2598
=> [payload-testing-prow-plugin] Include aggregated job count information in PRPQR creation

pkg/prowgen/prowgen.go
With `@daily`, all periodics hit exactly at midnight which makes jobs race for boskos leases, hit cloud platform APIs at the same time and stress build farm clusters. We could spread these with Prowgen so they hit deterministically between 22 and 04 UTC.
=> prowgen: hash-spread @daily periodics

pkg/api/types.go, pkg/prowgen/podspec.go, pkg/validation/test.go
Adding new cluster profile for Azure Mag, to support e2e tests on Azure Mag region in ci-operator.
=> Azure mag cluster profile

pkg/dispatcher/config.go
=> sanitize: keep jobs from the same PR on the same cluster

Makefile, cmd/ci-operator/main.go, cmd/cluster-display/main.go, cmd/cluster-display/main_test.go, pkg/api/domain.go
```console
$ curl -s "localhost:8090/api/v1/clusters" | jq
{
"data": [
{
"cloud": "AWS",
"cluster": "app.ci",
"consoleHost": "console-openshift-console.apps.ci.l2s4.p1.openshiftapps.com",
"product": "OSD",
"registryHost": "registry.ci.openshift.org",
"version": "4.8.3"
},
{
"cloud": "AWS",
"cluster": "arm01",
"consoleHost": "console.arm-build01.arm-build.devcluster.openshift.com",
"product": "OCP",
"registryHost": "registry.arm-build01.arm-build.devcluster.openshift.com",
"version": "4.9.0-0.nightly-arm64-2021-07-05-165629"
},
{
"cloud": "AWS",
"cluster": "build01",
"consoleHost": "console.build01.ci.openshift.org",
"product": "OCP",
"registryHost": "registry.build01.ci.openshift.org",
"version": "4.9.11"
},
{
"cloud": "GCP",
"cluster": "build02",
"consoleHost": …
```
=> [DPTP-2635]cluster-display: add endpont for clusters

cmd/autoconfigbrancher/README.md, cmd/autoconfigbrancher/main.go
- Write a README for autoconfigbrancher
- autoconfigbrancher: simplify a conditional
=> Write a README for autoconfigbrancher

cmd/payload-testing-prow-plugin/server.go, cmd/payload-testing-prow-plugin/server_test.go
=> [DPTP-2660]payload-testing-prow-plugin: format errors

Makefile, hack/pr-deploy-prpqr-ui.yaml, images/payload-testing-ui/Dockerfile
Simplify hacking on PRPQR UI
https://payload-testing-ui-ci-tools-2580.apps.ci.l2s4.p1.openshiftapps.com/runs/
=> prpqr: add a PR deploy makefile target

cmd/payload-testing-prow-plugin/main.go, cmd/payload-testing-prow-plugin/server.go, cmd/payload-testing-prow-plugin/server_test.go
https://issues.redhat.com/browse/DPTP-2639
/hold
will rebase after https://github.com/openshift/ci-tools/pull/2581
=> Refuse /payload command on PRs to repositories that do not contribute to OCP

pkg/controller/prpqr_reconciler/prpqr_reconciler.go
/cc @deads2k @openshift/test-platform
=> prpqr reconciler: hack to unblock vpshere jobs

pkg/validation/config.go, pkg/validation/config_test.go
https://issues.redhat.com/browse/DPTP-2613
=> Stop promoting to RH managed namespaces

pkg/jobrunaggregator/jobrunaggregatoranalyzer/pass_fail.go
see https://coreos.slack.com/archives/C01CQA76KMX/p1642174183197200
=> handle history correction for service load balancer disruption on azure

pkg/load/load.go, pkg/load/load_test.go, pkg/util/gzip/gzip.go
Subset of https://github.com/openshift/ci-tools/pull/2603.
Should definitely be reviewed with `--ignore-space-change`.
=> pkg/load: reduce indentation, improve tests

cmd/payload-testing-ui/server.go
/cc @openshift/test-platform @bbguimaraes 
https://issues.redhat.com/browse/DPTP-2728
=> Remove the aggregator prefix while matching for jobs

cmd/sync-rover-groups/main.go
=> sync-rover-groups: fix ldap's connection

cmd/github-ldap-user-group-creator/main.go, cmd/sync-rover-groups/main.go
=> sync-rover-groups: add a nil check on config

cmd/github-ldap-user-group-creator/main.go
- Log whether we ended up modifying cluster state
- Log what operation failed when something fails
=> Improve logging in ldap-user-group-creator

cmd/ci-operator/main.go, cmd/pod-scaler/resources.go, pkg/job-runtime-analyzer/job-runtime-analyzer.go, test/e2e/pod-scaler/run/producer.go
A couple of logging modifications and additional utilization of constants that I noticed while researching pod-scaler.
=> pod-scaler cleanup

pkg/steps/release/import_release.go
We're hitting this noticeably often:
https://search.ci.openshift.org/?search=unable+to+wait+for+the+.*+image+in+the+stable+stream+to+populate&maxAge=48h&context=1&type=bug%2Bjunit&name=&excludeName=&maxMatches=5&maxBytes=20971520&groupBy=job
It seems that this tends to happen when release-controller submits a ton
of jobs at once. The existing limit seems to be quite strict, I think we
can afford to be more lenient.
Also add duration in the eventual error.
=> ci-operator: wait longer for `cli` image to appear

cmd/cluster-init/main.go, cmd/cluster-init/update_sync_rover_groups.go, test/integration/cluster-init/create/expected/core-services/sync-rover-groups/_config.yaml, test/integration/cluster-init/create/input/core-services/sync-rover-groups/_config.yaml, test/integration/cluster-init/update/expected/core-services/sync-rover-groups/_config.yaml, test/integration/cluster-init/update/input/core-services/sync-rover-groups/_config.yaml
https://issues.redhat.com/browse/DPTP-2732
=> cluster-init: update sync-rover-groups' config

pkg/jobrunaggregator/jobtableprimer/generate_jobnames.go, pkg/jobrunaggregator/jobtableprimer/generated_job_names.txt
This adds 4.11 jobs and updates the 4.10 job list.
=> update job definitions for aggregator

cmd/repo-init/main.go, test/integration/repo-init/expected/core-services/prow/02_config/_plugins.yaml, test/integration/repo-init/input/core-services/prow/02_config/_plugins.yaml
https://issues.redhat.com/browse/DPTP-2721
=> repo-init: do not resolve cluster groups

cmd/sync-rover-groups/ldap.go, cmd/sync-rover-groups/ldap_test.go
=> sync-rover-groups: exclude gitlab users

pkg/jobrunaggregator/jobrunaggregatorapi/types_row_job.go, pkg/jobrunaggregator/jobtableprimer/job_typer.go, pkg/jobrunaggregator/jobtableprimer/jobs.go
Adding the architecture to support multiarch. 
/cc @deads2k
=> Adding Multiarch platforms

pkg/steps/source.go
Reverts openshift/ci-tools#2648
Caused `could not create build libvirt-installer: resourceVersion should not be set on objects to be created` errors. Probably not hard to fix, but revert first and fix later
https://search.ci.openshift.org/?search=resourceVersion+should+not+be+set+on+objects+to+be+created&maxAge=6h&context=1&type=bug%2Bjunit&name=&excludeName=&maxMatches=5&maxBytes=20971520&groupBy=job
=> Revert "ci-operator: retry infra-failed builds immediately"

pkg/jobrunaggregator/jobrunaggregatorapi/types_row_job.go, pkg/jobrunaggregator/jobtableprimer/generate_jobnames.go, pkg/jobrunaggregator/jobtableprimer/generated_job_names.txt, pkg/jobrunaggregator/jobtableprimer/job_typer.go, pkg/jobrunaggregator/jobtableprimer/jobs.go
adds the jobs for other architectures.
=> add other architectures for uploading

cmd/promoted-image-governor/README.md
=> add promoted-image-governor/README.md

cmd/ci-operator-prowgen/main.go
/hold
See https://github.com/openshift/ci-tools/pull/2628.
These may be reviewed more easily by comparing the end result to
https://github.com/openshift/ci-tools/pull/2628 as I have tried to maintain
consistency across instantiations of the pattern more than between the old and
new code (and use `--ignore-space-change`).
=> ci-operator-prowgen: use generic pipeline function

cmd/pj-rehearse/main.go, pkg/rehearse/jobs.go, pkg/rehearse/jobs_test.go
Follow up to address @petr-muller's comment on https://github.com/openshift/ci-tools/pull/2663
=> refactor to utilize jobConfigurer

cmd/better-retester/main.go, go.mod, vendor/k8s.io/test-infra/prow/tide/BUILD.bazel, vendor/k8s.io/test-infra/prow/tide/OWNERS, vendor/k8s.io/test-infra/prow/tide/blockers/BUILD.bazel, vendor/k8s.io/test-infra/prow/tide/blockers/blockers.go, vendor/k8s.io/test-infra/prow/tide/history/BUILD.bazel, vendor/k8s.io/test-infra/prow/tide/history/history.go, vendor/k8s.io/test-infra/prow/tide/search.go, vendor/k8s.io/test-infra/prow/tide/status.go, vendor/k8s.io/test-infra/prow/tide/tide.go, vendor/modules.txt
=> query PRs to merge

pkg/jobconfig/files.go
/hold
See https://github.com/openshift/ci-tools/pull/2628.
These may be reviewed more easily by comparing the end result to
https://github.com/openshift/ci-tools/pull/2628 as I have tried to maintain
consistency across instantiations of the pattern more than between the old and
new code (and use `--ignore-space-change`).
=> pkg/jobconfig: use generic pipeline function

cmd/repo-init/api.go, cmd/repo-init/api_test.go
I need some more easily searchable logs to follow the steps and fix issues here.
=> Modify repo-init-apiserver logging to provide finer-grained info

cmd/repo-init/api.go, cmd/repo-init/api_test.go, cmd/repo-init/repo_manager.go
Without this info the commit fails.
I have also refactored `api.go` based on @droslean's suggestion in https://github.com/openshift/ci-tools/pull/2672.
=> Add committer info to repo-init-ui commit

pkg/jobrunaggregator/jobtableprimer/job_typer.go, pkg/jobrunaggregator/jobtableprimer/jobs.go
=> Fixed missing platform for s390x/ppc64le

cmd/better-retester/main.go, cmd/better-retester/retester.go
/hold
Builds over https://github.com/openshift/ci-tools/pull/2677
=> Retest backoff

cmd/better-retester/main.go, cmd/better-retester/retester.go
=> better-retester: persist cache

cmd/cluster-init/update_bootstrap_secrets.go, cmd/cluster-init/update_jobs.go
required by https://github.com/openshift/release/pull/26216
/hold
=> cluster-init: stop updating github_client_id for build0{1|2}

pkg/prowconfigsharding/prowconfigsharding.go
When opening openshift/release/pull/26022, I've noticed it lacking the ability to preserve trigger plugin configuration on the ``correctly-sharded-config`` job. This change should consider trigger configuration
It's dependent on this change in test-infra: 
kubernetes/test-infra/pull/25173
=> fix sharding plugin configs that contain trigger plugin configuration

cmd/ci-operator-checkconfig/main.go
/hold
See https://github.com/openshift/ci-tools/pull/2628.
These may be reviewed more easily by comparing the end result to
https://github.com/openshift/ci-tools/pull/2628 as I have tried to maintain
consistency across instantiations of the pattern more than between the old and
new code (and use `--ignore-space-change`).
=> ci-operator-checkconfig: use generic pipeline fn.

cmd/sanitize-prow-jobs/main.go
This now bounds the maximum number of files processed so we don't hit the
limit on open file descriptors as has been happening sometimes:
https://prow.ci.openshift.org/view/gs/origin-ci-test/pr-logs/pull/openshift_ci-tools/2611/pull-ci-openshift-ci-tools-master-breaking-changes/1485693309320957952
---
/hold
See https://github.com/openshift/ci-tools/pull/2628.
These may be reviewed more easily by comparing the end result to
https://github.com/openshift/ci-tools/pull/2628 as I have tried to maintain
consistency across instantiations of the pattern more than between the old and
new code (and use `--ignore-space-change`).
=> sanitize-prow-jobs: use generic pipeline function

cmd/github-ldap-user-group-creator/main.go, cmd/github-ldap-user-group-creator/main_test.go
https://issues.redhat.com/browse/DPTP-2778
=> github-ldap-user-group-creator: manange group/openshift-priv-admins

pkg/steps/multi_stage.go, pkg/steps/multi_stage_test.go
Make it easier to see "all the pre steps completed", etc., by declaring steps/test-cases for each phase (pre, test, and post).
=> pkg/steps/multi_stage: Add subTests for phase completion

cmd/repo-init/api.go
We noticed that the access token was being logged when pushing the commit at the end of the repo-init flow.
Now that log looks like `{"args":"['-C', '/var/folders/8l/vb1frxqj6r54xmrswnvctpm40000gn/T/repo-manager-release2106839879', 'push', '-f', 'https://smg247:****************************************@github.com/smg247/release.git', 'HEAD:new-ci-config-1646332911']","cmd":"git","component":"unset","level":"info","msg":"running command","severity":"info","time":"2022-03-03T13:41:51-05:00"}`
=> censor access tokens in repo-init

hack/local-slack-bot.sh
The jira-client now requires a bearer token rather than user and password, so we need to update the local script to adjust for that.
I also couldn't add the cert in the same manner on my mac so I created a mac specific path.
=> local-slack-bot: use jira bearer token, and modify certs to work on mac

pkg/rehearse/jobs.go, pkg/rehearse/jobs_test.go
Extract sort logic and created tests
First part of : [DPTP-2743](https://issues.redhat.com/browse/DPTP-2743)
=> Extract sort logic for SelectJobsForChangedRegistry

cmd/cluster-init/update_bootstrap_secrets.go, test/integration/cluster-init/create/expected/core-services/ci-secret-bootstrap/_config.yaml, test/integration/cluster-init/create/input/core-services/ci-secret-bootstrap/_config.yaml, test/integration/cluster-init/update/expected/core-services/ci-secret-bootstrap/_config.yaml, test/integration/cluster-init/update/input/core-services/ci-secret-bootstrap/_config.yaml
Required by https://github.com/openshift/release/pull/26914
=> Stop managing secrets for the non_app_ci_x86 group

pkg/rehearse/jobs.go, test/integration/pj-rehearse/expected.yaml
Fixes: [DPTP-2794](https://issues.redhat.com/browse/DPTP-2794)
periodic rehearsal's details links need to be determined in the same manner as presubmits
=> Fix details link for qe-private deck periodic rehearsals

pkg/api/types.go, pkg/prowgen/podspec.go, pkg/validation/test.go
After discuss with DPP and Installer dev team, QE should use our dedicated cluster profiles.
=> create QE dedicated azure cluster profiles

pkg/api/types.go
Some following fix for https://github.com/openshift/ci-tools/pull/2716
=> return correct ClusterType for QE's cluster profiles

cmd/repo-init/main.go, cmd/repo-init/main_test.go, pkg/config/release.go, test/integration/repo-init/expected/core-services/prow/02_config/_config.yaml, test/integration/repo-init/expected/core-services/prow/02_config/openshift/ci-tools/_prowconfig.yaml, test/integration/repo-init/expected/core-services/prow/02_config/openshift/cluster-version-operator/_prowconfig.yaml, test/integration/repo-init/expected/core-services/prow/02_config/org/other/_prowconfig.yaml, test/integration/repo-init/expected/core-services/prow/02_config/org/repo/_prowconfig.yaml, test/integration/repo-init/expected/core-services/prow/02_config/org/third/_prowconfig.yaml, test/integration/repo-init/input/core-services/prow/02_config/_config.yaml, test/integration/repo-init/input/core-services/prow/02_config/openshift/ci-tools/_prowconfig.yaml, test/integration/repo-init/input/core-services/prow/02_config/openshift/cluster-version-operator/_prowconfig.yaml
https://issues.redhat.com/browse/DPTP-2759
=> repo-init: create repo's prow configuration

pkg/rehearse/jobs.go, pkg/rehearse/jobs_test.go
Creating logic for moreRelevant method based on tests created in [this PR](https://github.com/openshift/ci-tools/pull/2708)
Second part of : [DPTP-2743](https://issues.redhat.com/browse/DPTP-2743)
=> Creating more relevant sorting logic for SelectJobsForChangedRegistry

cmd/repo-init/main.go, pkg/api/types.go, pkg/prowgen/podspec.go, pkg/validation/test.go
- added Nutanix Cluster Profile for CI
=> Add Nutanix Cluster Profile

cmd/repo-init/api.go, pkg/api/types.go, pkg/prowgen/podspec.go, pkg/validation/test.go
$Subject
This is a initial pull request that starts work with registering awsosdmsp clusterprofile with openshift ci.
=> Register AWSOSDMSP ClusterProfile with openshift ci

cmd/ci-secret-bootstrap/main_test.go, cmd/vault-subpath-proxy/kv_update_transport.go, cmd/vault-subpath-proxy/main_test.go, pkg/secrets/vault.go
Sometimes secrets need to exist in multiple namespaces. Today, this
requires creating the Vault entry multiple times. This updats the secret
syncing to instead allow specifying multiple comma-seperated namespaces
as target, similiar to what is already possible for clusters.
The diff is best viewed with whitespace changes disabled (280 LOC diff vs 125), as a bunch of code got moved into a loop, changing its indentation level along the way.
I'll do a follow-up for docs once this merges.
=> Secret sync: Allow targeting multiple namespaces

pkg/results/report.go
=> Add an unknown value in console host when it is not resolved

pkg/api/types.go, pkg/prowgen/podspec.go
See https://github.com/openshift/ci-docs/pull/238 for background and motivation.
Reviewing commit-by-commit is highly recommended.
=> pkg/prowgen: rework profile volume generation

cmd/sprint-automation/main.go
=> change the jira query to match with the new workflow changes

pkg/slack/events/helpdesk/helpdesk-message.go
We aren't responding to messages in `#forum-testplatform` like expected. I have looked through our logs and it never displays the "Handling response in forum-testplatform channel..." message, so we must be returning from the function prior to that. With these added debug logs we should be able to tell when it fails.
=> slack-bot: add extra debug logging to helpdesk-message handler

cmd/entrypoint-wrapper/main.go, cmd/vault-subpath-proxy/kv_update_transport.go, pkg/api/constant.go, pkg/api/secretbootstrap/secretboostrap.go, pkg/defaults/defaults.go, pkg/defaults/defaults_test.go, pkg/kubernetes/client.go, pkg/steps/artifacts.go, pkg/steps/artifacts_test.go, pkg/steps/cluster_claim.go, pkg/steps/clusterinstall/clusterinstall.go, pkg/steps/input_image_tag.go, pkg/steps/lease.go, pkg/steps/lease_test.go, pkg/steps/multi_stage.go, pkg/steps/multi_stage_test.go, pkg/steps/pod.go, pkg/steps/pod_test.go, pkg/steps/release/create_release.go, pkg/steps/release/import_release.go, pkg/steps/release/promote.go, pkg/steps/run.go, pkg/steps/secretrecordingclient/client.go, pkg/steps/source.go, pkg/steps/template.go, pkg/testhelper/pod.go, pkg/validation/test.go
Splitting this from a future PR to facilitate the review since the changes are
independent and self-contained.  Just to prepare you mentally, I'm planning to
create a `pkg/steps/multi_stage` package, so there will be a lot of code
movement but no functional change.
Package visibility in Go only works laterally, so unfortunately we have to
export more than I'd like in `pkg/steps`.
=> General refactoring

cmd/slack-bot/README.md
Updated the README file so it describes the new messaging functionality and also existing functionality. Not sure if it is detailed enough.
https://issues.redhat.com/browse/DPTP-2746
/cc smg247
=> Update slackbot readme

pkg/jobrunaggregator/jobrunaggregatoranalyzer/analyzer_disruption.go
reverts https://github.com/openshift/ci-tools/pull/2566
=> fail on disruption now that history is complete

pkg/api/ocplifecycle/ocplifecycle.go
=> Extend the ocplifecycle config code and introduce the event timeline operations

cmd/branchingconfigmanagers/fast-forwarding-config-manager/README.md, cmd/branchingconfigmanagers/fast-forwarding-config-manager/main.go, cmd/branchingconfigmanagers/fast-forwarding-config-manager/main_test.go
=> Initial implementation of the fast-forwarding config manager tool

cmd/determinize-prow-config/main.go, cmd/determinize-prow-config/main_test.go, pkg/api/shardprowconfig/shardprowconfig.go
=> Extract shardProwConfig and refactor it to re-use in tide shard branch cut tool

cmd/sprint-automation/main.go
Send a reminder message to the new primary triage engineer each Monday to look at the triage handover doc.
Story [DPTP-2807](https://issues.redhat.com/browse/DPTP-2807)
=> sprint-automation: reminder to view triage handover doc at beginning of week

cmd/branchingconfigmanagers/tide-config-manager/main.go, cmd/branchingconfigmanagers/tide-config-manager/main_test.go, pkg/api/ocplifecycle/ocplifecycle.go
Prototype with feature freeze implemented
/cc @droslean @danilo-gemoli @bear-redhat 
@droslean is currently absent so @danilo-gemoli and @bear-redhat please look instead :) 
=> Tide shard config manager for ocplifecycle events with feature freeze

CONTRIBUTING.md
=> [DPTP-2699]Add CONTRIBUTING.md

pkg/validation/release.go, pkg/validation/release_test.go
https://issues.redhat.com/browse/DPTP-2858
=> Validate the names of integration releases

cmd/branchingconfigmanagers/tide-config-manager/main.go, cmd/branchingconfigmanagers/tide-config-manager/main_test.go, cmd/determinize-prow-config/main.go, pkg/api/shardprowconfig/shardprowconfig.go
Added code freeze event to the config manager.
/cc @danilo-gemoli @droslean 
=> Tide config shard manager for automatic branch cuts: code freeze event

pkg/validation/config.go, pkg/validation/release.go, pkg/validation/release_test.go
https://coreos.slack.com/archives/GB7NB0CUC/p1651853180600959
Check all releases, instead of only integration releases.
=> Validate the name of all releases

cmd/entrypoint-wrapper/main.go, test/integration/entrypoint-wrapper.sh
This can be used to synchronize the wrapped command with some external
process, e.g. the establishment of a VPN connection.
=> entrypoint-wrapper: add option to wait for file

cmd/autoconfigbrancher/main.go, images/autoconfigbrancher/Dockerfile
https://issues.redhat.com/browse/DPTP-2863
=> Add promoted-image-governor into the auto-config-brancher image

cmd/autopublicizeconfig/main.go, cmd/blocking-issue-creator/main.go, cmd/ci-operator-config-mirror/main.go, cmd/config-brancher/main.go, cmd/payload-testing-prow-plugin/server.go, cmd/private-org-peribolos-sync/main.go, cmd/private-org-sync/main.go, cmd/private-org-sync/main_test.go, cmd/private-prow-configs-mirror/main.go, cmd/repo-brancher/main.go, pkg/api/promotion.go, pkg/api/promotion_test.go, pkg/promotion/promotion.go, pkg/promotion/promotion_test.go, pkg/prowgen/prowgen.go, pkg/validation/config.go, pkg/validation/config_test.go
https://issues.redhat.com/browse/DPTP-2857
=> Ensure importing release on promoting to official images

pkg/backporter/backporter.go, pkg/backporter/backporter_test.go
To debug for
https://coreos.slack.com/archives/CBN38N3MW/p1652351363015799
and found no logs was printed
=> backporter: fix a logging

pkg/steps/index_generator.go, pkg/steps/index_generator_test.go
https://issues.redhat.com/browse/DPTP-2692
/cc @openshift/test-platform @gallettilance
=> Failed the build upon a file-based catalog index

cmd/ci-operator/main.go, pkg/defaults/defaults.go, pkg/defaults/defaults_test.go, pkg/steps/multi_stage/gen.go, pkg/steps/multi_stage/gen_test.go, pkg/steps/multi_stage/multi_stage.go, pkg/steps/multi_stage/multi_stage_test.go, pkg/steps/multi_stage/run_test.go, pkg/steps/multi_stage/testdata/zz_fixture_TestGeneratePods.yaml, pkg/steps/pod.go, pkg/steps/pod_test.go, pkg/steps/release/create_release.go, pkg/steps/release/import_release.go
I've always had to hack the code to do this, supporting it as an option
is not too difficult.
=> ci-operator: add option to restrict scheduling

images/check-gh-automation/Dockerfile
The image needs `git` in order to determine changed files.
=> Add git to `check-gh-automation` image

cmd/branchingconfigmanagers/tide-config-manager/main.go, cmd/branchingconfigmanagers/tide-config-manager/main_test.go, pkg/api/ocplifecycle/ocplifecycle.go, pkg/api/shardprowconfig/shardprowconfig.go
=> Tide config shard manager for automatic branch cuts: GA event

cmd/payload-testing-prow-plugin/server.go, cmd/payload-testing-prow-plugin/server_test.go
https://issues.redhat.com/browse/DPTP-2730
=> Execute any release job on any PR

pkg/jobrunaggregator/jobtableprimer/generated_job_names.txt
created using the command at the top of the generated file: `./job-run-aggregator generate-job-names  > pkg/jobrunaggregator/jobtableprimer/generated_job_names.txt`
/assign @dgoodwin
=> update the generated job list

cmd/cluster-display/main.go
https://prow.ci.openshift.org/view/gs/origin-ci-test/pr-logs/pull/openshift_ci-tools/2846/pull-ci-openshift-release-snyk-code/1533857079431794688
```
✗ [High] Cross-site Scripting (XSS)
Path: cmd/cluster-display/main.go, line 227
Info: Unsanitized input from an HTTP header flows into fmt.Fprintf, where it is used to render an HTML page returned to the user. This may result in a Reflected Cross-Site Scripting attack (XSS).
```
=> cluster-display: fix a XSS

Makefile, hack/install.sh
https://issues.redhat.com/browse/DPTP-2777
=> ci-operator: no more dirty versions

Makefile
=> Makefile: document E2E test arguments

cmd/autoconfigbrancher/main_test.go
```
--- FAIL: TestRunSteps (0.01s)
--- FAIL: TestRunSteps/Command_changes_something (0.00s)
main_test.go:54: failed to create initial commit: exit status 128, out: Author identity unknown
*** Please tell me who you are.
Run
git config --global user.email "you@example.com"
git config --global user.name "Your Name"
to set your account's default identity.
Omit --global to set the identity only in this repository.
fatal: unable to auto-detect email address (got 'bbguimaraes@rh0.(none)')
```
=> autoconfigbrancher: set test Git user/email

pkg/api/types.go
Adding support for new platform IBM PowerVS 
=> add cluster-profile for IBM PowerVS

cmd/slack-bot/main.go, hack/local-slack-bot.sh, pkg/slack/events/helpdesk/helpdesk-message.go, pkg/slack/events/router/router.go
Based on keywords present in a message posted in forum-testplatform, this adds functionality for slack-bot's auto-response to include links to our docs.
https://issues.redhat.com/browse/DPTP-2840
/cc smg247
=> DPTP-2840 Add links to docs to slack-bot auto response

test/integration/entrypoint-wrapper.sh
Extracted from https://github.com/openshift/ci-tools/pull/1368.
=> integration: test kubeconfig upload on interrupt

pkg/api/helper/imageextraction.go, pkg/rehearse/jobs.go
=> [pj-rehearse] output the required imagestream tags for each job

pkg/slack/events/helpdesk/helpdesk-message_test.go, pkg/slack/events/helpdesk/testdata/zz_fixture_TestGetContactedHelpdeskResponse_botId_like_review_workflow.yaml, pkg/slack/events/helpdesk/testdata/zz_fixture_TestGetContactedHelpdeskResponse_empty_botId.yaml, pkg/slack/events/helpdesk/testdata/zz_fixture_TestGetContactedHelpdeskResponse_random_botId.yaml
Create unit tests for  helpdesk-message.go
for  [DPTP-2967](https://issues.redhat.com/browse/DPTP-2967)
/cc smg247
=> Create unit tests for helpdesk-message

test/e2e/pod-scaler/kubernetes/kubernetes.go
`TestBuildPodAdmission` fails occasionally (around 1/20 times from my estimation). From looking at the logs I found a failure to run the kubernetes server in the failed results:
```
accessory.go:66: found a never-before-seen port, returning: 46497
level=info msg="Server exited." error="listen tcp 0.0.0.0:46497: bind: address already in use"
```
I considered implementing some sort of retry for this condition, but I don't think it is happening often enough to necessitate that. using `interrupts.ListenAndServe` doesn't allow us to call out the error to bind as fatal, but if we run the server manually we can.
Now, when it fails it will be obvious what the cause is and the test can simply be re-run.
=> Call out specific failure in e2e TestBuildPodAdmission flakes

Makefile
Improve `snyk-code` output to show newly discovered vulnerabilities fingerprints
Save vulnerabilities report to artifacts
=> Better snyk code outputs

images/ci-secret-generator/Dockerfile, images/ci-secret-generator/oc_sa_create_kubeconfig.sh
https://issues.redhat.com/browse/DPTP-3002
=> Add oc_sa_create_kubeconfig.sh

cmd/ci-secret-generator/main_test.go
https://issues.redhat.com/browse/DPTP-3034
/cc @danilo-gemoli @bbguimaraes
=> ci-secret-generator: add unit tests for executeCommand

cmd/ci-secret-generator/main.go, cmd/ci-secret-generator/main_test.go
=> executeCommand doesn't mix std streams anymore

go.mod, go.sum, vendor/gopkg.in/yaml.v3/decode.go, vendor/gopkg.in/yaml.v3/parserc.go, vendor/modules.txt
`snyk-deps` complains `yaml.v3-3.0.0` has known vulnerability
https://prow.ci.openshift.org/view/gs/origin-ci-test/pr-logs/pull/openshift_ci-tools/2913/pull-ci-openshift-release-snyk-deps/1551576963439661056#1:build-log.txt%3A5
=> Update yaml.v3 to v3.0.1

cmd/entrypoint-wrapper/main.go, pkg/api/types.go, pkg/api/zz_generated.deepcopy.go, pkg/steps/multi_stage/gen.go, pkg/webreg/zz_generated.ci_operator_reference.go, test/e2e/multi-stage/no-kubeconfig.yaml
https://issues.redhat.com/browse/DPTP-3038
=> ci-operator: allow multi-stage steps to opt out of SA credentials

pkg/api/types.go, pkg/steps/release/promote.go, pkg/steps/release/promote_test.go, pkg/webreg/zz_generated.ci_operator_reference.go
=> ci-operator: allow promoting images with commit sha tag

images/ci-secret-generator/oc_sa_create_kubeconfig.sh
1. NS can be specified.
2. vsphere login with `--insecure-skip-tls-verify=true`
=> Enhance oc_sa_create_kubeconfig.sh

pkg/steps/source.go, pkg/steps/source_test.go
https://issues.redhat.com/browse/DPTP-3045
/cc @stevekuznetsov @bbguimaraes
=> waitForBuild: use watch instead of get

pkg/steps/source_test.go
https://issues.redhat.com/browse/DPTP-3045
=> Fix a copy/paste error

pkg/steps/release/promote.go
=> ci-operator: handle promotion with no refs

pkg/defaults/defaults.go, pkg/steps/multi_stage/gen.go, pkg/util/multi_arch.go
/cc @openshift/test-platform @bbguimaraes 
=> Resolve the entrypoint and clonerefs image namespace based on the os architecture

cmd/entrypoint-wrapper/main.go
=> entrypoint-wrapper: add renaming kubeconfig

pkg/api/types.go, pkg/util/multi_arch.go
=> add more logging when resolving namespace for multi architecture

images/ci-secret-generator/oc_sa_create_kubeconfig.sh
https://issues.redhat.com/browse/DPTP-3002
=> oc_sa_create_kubeconfig.sh: oc_cmd as var

pkg/api/types.go
add cluster profile `vsphere-connected` for QE testing
cc: @jianlinliu
=> add cluster profile vsphere-connected for QE testing

images/gh-pull-through-cache/Dockerfile, images/gh-pull-through-cache/nginx.conf
=> Add gh-pull-through-cache image

pkg/api/types.go, pkg/util/multi_arch.go
=> improve logging when resolving namespace for the os architecture

images/ci-secret-generator/Dockerfile
https://issues.redhat.com/browse/DPTP-3002
/hold
require https://github.com/openshift/release/pull/31563
=> Copy /usr/bin/oc411 in the ci-secret-generator image

images/gh-pull-through-cache/Dockerfile, images/gh-pull-through-cache/nginx.conf
=> gh-pull-through-cache: make nginx unprivileged

images/gh-pull-through-cache/Dockerfile, images/gh-pull-through-cache/nginx.conf
=> Change base image to internal unpriv nginx

pkg/api/types.go
=> resolve namespace in imagestream tag name method for multi arch images

cmd/check-gh-automation/main.go, cmd/check-gh-automation/main_test.go
We can utilize the newly added (https://github.com/kubernetes/test-infra/pull/27181) `IsAppInstalled` method to determine if our app has been installed in the repo.
For: https://issues.redhat.com/browse/DPTP-3041
=> `check-gh-automation`: check that app is installed in repo

pkg/dispatcher/config.go, pkg/dispatcher/config_test.go
Temporary setting to allow manual colocation
manual == step by step
=> Add IgnoreE2EByJobAssignment option to gradually enable colocation

cmd/promoted-image-governor/main.go
=> promoted-image-governor: don't delete images tagged by sha

pkg/api/domain.go, pkg/api/domain_test.go
=> resolve arm01 service domain registry address

images/ci-secret-generator/Dockerfile
Reverts openshift/ci-tools#2960
/hold
require https://github.com/openshift/release/pull/31904/files
=> Revert "Copy /usr/bin/oc411 in the ci-secret-generator image"

pkg/slack/events/helpdesk/helpdesk-message.go
In response to https://coreos.slack.com/archives/CBN38N3MW/p1662122635448789?thread_ts=1662122452.380299&cid=CBN38N3MW
=> `slack-bot`: clarify how to use workflow in forum

cmd/autoconfigbrancher/main.go
=> Change release minor 8 to current

pkg/steps/source_test.go
https://issues.redhat.com/browse/DPTP-3125
/cc @smg247
=> Fix an issue caused by gotestsum

cmd/cluster-init/update_bootstrap_secrets.go, test/integration/cluster-init/create/expected/core-services/ci-secret-bootstrap/_config.yaml, test/integration/cluster-init/update/expected/core-services/ci-secret-bootstrap/_config.yaml
Reverts openshift/ci-tools#2998
=> Revert "add quay.io pull credentials when generating the bootstrap secrets for build clusters"

cmd/ci-operator/main.go, pkg/prowgen/podspec.go, pkg/steps/source.go, pkg/steps/source_test.go
=> Use only one constant for registry-pull-credentials

images/ci-secret-generator/Dockerfile, images/ci-secret-generator/oc_create_kubeconfig.sh
We are going to use this script to generate the kubeconfig file without the token
=> Add script oc_create_kubeconfig.sh

images/ci-secret-generator/Dockerfile, images/ci-secret-generator/google-cloud-sdk.repo
/cc @openshift/test-platform @hongkailiu
=> remove the google cloud sdk repo in ci-secret-generator image

images/quayio-pull-through-cache/Dockerfile, images/quayio-pull-through-cache/config.yml, images/quayio-pull-through-cache/docker-entrypoint.sh
=> quay.io pull through cache image

images/quayio-pull-through-cache/Dockerfile, images/quayio-pull-through-cache/config.yml, images/quayio-pull-through-cache/docker-entrypoint.sh
=> Correct various misconfiguration problems in quay cache image

cmd/prcreator/main.go
Signed-off-by: eggfoobar <eggfoobar@users.noreply.github.com>
=> feat: expose pr message and assignee to prcreator cli

pkg/api/types.go
Blocks (and is followed up by):
- https://github.com/openshift/release/pull/32536
- https://github.com/openshift/release/pull/32498
Related to [ARMOCP-453](https://issues.redhat.com//browse/ARMOCP-453)
cc @pamoedom @jadhaj
=> ARMOCP-453: Adding the Packet QE Cluster Profile

cmd/result-aggregator/main.go
A fix so pod-scaler metrics are registered and are recorded, plus some refactoring so names are more descriptive.
for https://issues.redhat.com/browse/DPTP-3106
/cc smg247
=> DPTP-3106 register pod-scaler metrics

cmd/retester/main.go, cmd/retester/main_test.go, pkg/retester/retester.go, pkg/retester/retester_test.go, pkg/retester/testdata/NewController/basic_case.yaml, pkg/retester/testdata/jobconfig/simple.yaml, pkg/retester/testdata/prowconfig/simple.yaml, pkg/retester/testdata/testconfig/wrong_format.yaml
Adding tests.
Second step of [DPTP-3046](https://issues.redhat.com/browse/DPTP-3046)
/cc hongkailiu
=> retester: Add tests for retester

pkg/steps/multi_stage/init.go, pkg/steps/release/create_release.go, pkg/util/rbacs.go
This PR is an attempt to mitigate this problem: [DPTP-3134](https://issues.redhat.com/browse/DPTP-3134)
FYI: @jupierce
=> Pods acquiring imagePullSecrets: race condition mitigation

cmd/ci-operator-prowgen/main.go, pkg/api/types.go, pkg/config/load.go, pkg/prowgen/prowgen.go, pkg/prowgen/prowgen_test.go, pkg/prowgen/testdata/zz_fixture_TestGenerateJobs_multiarch_postsubmit_images__default_arch_and_others.yaml
This is related to [DPTP-3029](https://issues.redhat.com/browse/DPTP-3029)
/cc @droslean
=> Prowgen: multiarch postsubmit images

cmd/vault-secret-collection-manager/README.md
=> doc: get the members of a collection's group

pkg/config/release.go
=> Add observers suffix

pkg/prowgen/jobbase.go, pkg/prowgen/prowgen.go, pkg/prowgen/testdata/zz_fixture_TestGenerateJobs_cluster_label_for_periodic.yaml, pkg/prowgen/testdata/zz_fixture_TestGenerateJobs_cluster_label_for_postsubmit.yaml, pkg/prowgen/testdata/zz_fixture_TestGenerateJobs_cluster_label_for_presubmit.yaml, pkg/prowgen/testdata/zz_fixture_TestGenerateJobs_multiarch_postsubmit_images__default_arch_and_others.yaml, pkg/prowgen/testdata/zz_fixture_TestNewProwJobBaseBuilderForTest_simple_container_based_test_with_arm01_cluster.yaml, pkg/prowgen/testdata/zz_fixture_TestNewProwJobBaseBuilderForTest_simple_container_based_test_with_cluster.yaml
=> Mutate image when generating postsubmits for multi-arch and fix cluster references on test

cmd/retester/main.go
Release repo PR: https://github.com/openshift/release/pull/32797
[DPTP-3158](https://issues.redhat.com/browse/DPTP-3158)
=> retester: adding metrics

cmd/pj-rehearse/main.go, pkg/load/load.go, pkg/registry/graph.go, pkg/registry/graph_test.go
=> Treat observers as references in graph

cmd/sprint-automation/main.go, cmd/sprint-automation/main_test.go
If the last comment left on a new card is by TP Intake, this card won't be included in the intake digest on Slack.
for https://issues.redhat.com/browse/DPTP-2428
/cc smg247
=> DPTP-2428 Don't send acknowledged cards to Intake

cmd/prcreator/main.go, pkg/github/prcreation/prcreation.go
Signed-off-by: eggfoobar <eggfoobar@users.noreply.github.com>
=> feat: add support for commit message being different than pr body

pkg/api/types.go
add ibmcloud qe cluster profile
=> add ibmcloud qe cluster profile

OWNERS
=> Add new members to OWNERS

cmd/sprint-automation/main.go
Everything is on Steve's drive and I don't have rw access to it. Steve misses my requests. Anyway, it seems it is not a long-term solution to rely on Steve's drive so I moved these 5 documents to our Dev Productivity Test Platform folder. I do not know if it should be hosted long-term there, but until we decide on a better place (with automatic access for everyone within the team), let's have it there.
=> Update roles and definitions links

cmd/pr-reminder/main.go
Adds a :new: icon to the PR if the PR was updated in the last 24 hours.
/cc smg247
=> pr-reminder: show when the latest pr update is less than a day old

cmd/cluster-init/update_bootstrap_secrets.go, test/integration/cluster-init/create/expected/core-services/ci-secret-bootstrap/_config.yaml, test/integration/cluster-init/update/expected/core-services/ci-secret-bootstrap/_config.yaml
This PR starts the work of https://issues.redhat.com/browse/DPTP-3152
The breaking change will be fixed by https://github.com/openshift/release/pull/32546
/cc @smg247
=> cluster-init: add flag use-token-file-in-kubeconfig

pkg/api/types.go
release PR https://github.com/openshift/release/pull/33470
=> Add another AWS QE profile for local zone testing

pkg/retester/retester.go
Release repo PR: https://github.com/openshift/release/pull/32797
[DPTP-3158](https://issues.redhat.com/browse/DPTP-3158)
=> retester: adding metrics for counting retests

cmd/cluster-display/main.go, cmd/cluster-display/main_test.go
One of the things to follow up from the incident last Friday.
=> cluster-display: add #standby for pools

pkg/controller/test-images-distributor/test_images_distributor.go
This PR is related to [DPTP-3160](https://issues.redhat.com/browse/DPTP-3160)
`test-images-distributor` now distributes `ISTag`s coming from multiarch namespaces to the proper clusters, without modifying the existing behaviour.
Examples: 
ISTag `ci-arm64/ci-operator:latest` would be replicated on `arm01` but it won't on `build0x`
ISTag `ci/ci-operator:latest` would be replicated **only** on `amd64` clusters: `build0x`
/cc @droslean  @hongkailiu
=> test-images-distributor: distribute multiarch IS

cmd/ci-operator-prowgen/main.go, pkg/config/load.go
=> [prowgen] merge configuration defaults when both org and repo configs are specified

cmd/pj-rehearse/server.go
This will allow users to re-block the merge by removing the label on command.
I will also update the documentation once this is rolled out and functioning.
/cc @openshift/test-platform @droslean
=> `pj-rehearse` plugin: Add a way to remove the `rehearsals-ack` label

cmd/pj-rehearse/server.go
If an author pushes new commit(s) to their PR, they may want the ability to refresh the affected jobs list to know what rehearsals are available. This allows that with a simple `/pj-rehearse refresh` comment. It will also auto-ack if there are no jobs affected.
=> `pj-rehearse` plugin: allow for refreshing the affected job list

cmd/dptp-controller-manager/main.go
86f1d4db1c added the command-line argument but maintained the usage of the old
clients, which are not appropriate for a `git-sync` mount — they work but are
obscenely inefficient (see production logs).  This change copies the pattern
from `ci-operator-configresolver` (94fd5be7a8) to create agents of the
appropriate type.  Note that the required path manipulation based on the
argument is already present.
/hold
=> dptp-controller-manager: use universal watcher

cmd/pj-rehearse/server.go
The first step for https://issues.redhat.com/browse/DPTP-3218 involves accepting commands in the PR body itself. 
This required a minor change to the regex in order to accept multiple commands like:
```
/pj-rehearse
/pj-rehearse ack
```
The original regex would misinterpret the `/pj-rehearse`.
=> `pj-rehearse` plugin: accept commands in the PR body

cmd/determinize-prow-config/main_test.go, pkg/api/shardprowconfig/shardprowconfig.go
Requires 3 other PRs first:
* https://github.com/kubernetes/test-infra/pull/27933
* https://github.com/openshift/ci-tools/pull/3139
* https://github.com/openshift/release/pull/34250
=> Allow sharding of slack reporter configs

cmd/cluster-init/update_bootstrap_secrets.go, test/integration/cluster-init/create/expected/core-services/ci-secret-bootstrap/_config.yaml, test/integration/cluster-init/update/expected/core-services/ci-secret-bootstrap/_config.yaml, test/integration/cluster-init/update/input/core-services/ci-secret-bootstrap/_config.yaml
Follow up https://github.com/openshift/ci-tools/pull/3152
=> cluster-init: automate members of osd_global_pull_secret group

cmd/pj-rehearse/server.go, pkg/rehearse/rehearse.go
The `/pj-rehearse auto-ack` command will be used to trigger rehearsals and automatically add the `rehearsals-ack` label iff they succeed. This will be used for replacement of the `pj-rehearse-blocking` job.
I had originally hoped to remove the "wait for success" portion on non `auto-ack` runs, but it is also used to cleanup after the jobs are finished so we will have to keep that around.
For: https://issues.redhat.com/browse/DPTP-3218
/cc @droslean @openshift/test-platform 
/hold I want to watch the rollout
=> `pj-rehearse` plugin: add auto-ack command

pkg/api/types.go
release PR https://github.com/openshift/release/pull/34491
=> Add new profile for QE SD

pkg/api/types.go
Add QE dedicated cluster profile for azure stack test
=> Add QE dedicated cluster profile for azure stack test

pkg/jobrunaggregator/jobruntestcaseanalyzer/analyzer.go, pkg/jobrunaggregator/jobruntestcaseanalyzer/analyzer_test.go, pkg/jobrunaggregator/jobruntestcaseanalyzer/cmd.go
[TRT-614](https://issues.redhat.com/browse/TRT-614)
=> Add include-job-names argument to filter jobs by names

cmd/pj-rehearse/server.go
Failure messages will now provide more info about what went wrong, and also a link to our contact info in relevant cases. We should also not continue after one of these failures, so I have added appropriate `return` and `continue` statements.
=> `pj-rehearse`: cleanup failure messages: provide error and contact info

cmd/job-run-aggregator/README.md
updated readme to include examples for running locally
/assign @dgoodwin 
Signed-off-by: eggfoobar <eggfoobar@users.noreply.github.com>
=> feat: update readme

cmd/prow-job-dispatcher/main.go, hack/run-prow-job-dispatcher.sh, pkg/dispatcher/prometheus.go
https://issues.redhat.com/browse/DPTP-3254
=> prow-job-dispatcher: support auth with bearer token

cmd/config-brancher/main.go, cmd/config-brancher/main_test.go, pkg/api/types.go, pkg/webreg/zz_generated.ci_operator_reference.go, test/e2e/multi-stage/assembled-release-no-injection.yaml, test/e2e/multi-stage/assembled-release.yaml, test/e2e/multi-stage/cluster-claim.yaml, test/e2e/multi-stage/dependencies.yaml, test/e2e/multi-stage/e2e_test.go, test/e2e/multi-stage/integration-releases.yaml
That will cut around 2% of current spendings once enabled.
=> Add possibility of skipping periodic tests to config-brancher & fix e2e

cmd/pj-rehearse/main.go, cmd/pj-rehearse/server.go, pkg/rehearse/rehearse.go
We can use similar logic to [trigger](https://github.com/kubernetes/test-infra/blob/58e75f7ea76ff4ab825ec3cc7b6d5540bfca1206/prow/plugins/trigger/pull-request.go#L165-L193) to abort all rehearsal jobs for a particular PR. This will be useful when a PR author realizes there is something wrong with their code, but isn't ready to push a new change up yet. They can comment `/pj-rehearse abort` to abort all active rehearsals in the meantime. Once a new push is made they would all be aborted anyways.
For: https://issues.redhat.com/browse/DPTP-3209
=> `pj-rehearse`: allow the ability to abort active rehearsals

pkg/rehearse/rehearse.go
I am triaging a very strange bug that I cannot reproduce in the alpha version of the plugin. I need some additional logging to help narrow down the cause. I added most of these as trace so we can ignore them longer term.
=> `pj-rehearse`: add additional logging to FilterJobsByRequested

cmd/autoconfigbrancher/main.go
=> Skip periodics for the future and current releases

cmd/sippy-config-generator/main.go, pkg/api/sippy/v1/types.go
[TRT-714](https://issues.redhat.com/browse/TRT-714)
=> Add payload job types for sippy to use to generate testgrid url

pkg/api/sippy/OWNERS
[TRT-716](https://issues.redhat.com/browse/TRT-716)
=> Add TRT owners to api sippy folder

cmd/pj-rehearse/main.go
Exposing metrics so that I can add a service monitor and alert. I also added pprof capabilities in case we need them later.
For: https://issues.redhat.com/browse/DPTP-3263
=> `pj-rehearse`: expose metrics

pkg/controller/prpqr_reconciler/prpqr_reconciler.go, pkg/controller/prpqr_reconciler/testdata/zz_fixture_prowjobs_TestReconcile_basic_aggregated_case.yaml, pkg/controller/prpqr_reconciler/testdata/zz_fixture_prowjobs_TestReconcile_basic_case.yaml, pkg/controller/prpqr_reconciler/testdata/zz_fixture_prowjobs_TestReconcile_basic_case_with_metal_override.yaml, pkg/controller/prpqr_reconciler/testdata/zz_fixture_prowjobs_TestReconcile_basic_case_with_variant.yaml, pkg/controller/prpqr_reconciler/testdata/zz_fixture_prowjobs_TestReconcile_basic_case_with_vsphere_override.yaml, pkg/controller/prpqr_reconciler/testdata/zz_fixture_prowjobs_TestReconcile_multiple_case__one_of_the_prowjobs_already_exists.yaml, pkg/jobrunaggregator/jobrunaggregatoranalyzer/analyzer.go
=> Increase timeouts for payload jobs to land k8s 1.26

pkg/steps/index_generator.go, pkg/steps/index_generator_test.go
Currently results in a nil pointer dereference:
```
$ ci-operator --namespace bbguimaraes --config optional-operators.yaml --target verify-db-named
…
INFO[2022-11-18T16:37:09Z] Building named-bundle
INFO[2022-11-18T16:37:42Z] Build named-bundle succeeded after 33s
[signal SIGSEGV: segmentation violation code=0x1 addr=0x20 pc=0x1a85a71]
goroutine 970 [running]:
github.com/openshift/ci-tools/pkg/steps.(*indexGeneratorStep).run(0xc000e2c400, {0x241b258, 0xc000940e40})
/home/bbguimaraes/src/ci-tools/pkg/steps/index_generator.go:73 +0x451
github.com/openshift/ci-tools/pkg/steps.(*indexGeneratorStep).Run(0x0?, {0x241b258, 0xc000940e40})
/home/bbguimaraes/src/ci-tools/pkg/steps/index_generator.go:37 +0x5e …
```
=> pkg/steps: handle missing secret in index step

cmd/ci-secret-bootstrap/main.go
More improvement following up https://github.com/openshift/ci-tools/pull/3229#issuecomment-1373029275
=> secret-bootstrap: reduce #API calls to get namespaces

cmd/pj-rehearse/server.go
I don't believe users are reading down to the bottom of the comment. Let's nudge them a bit to get less questions on #forum-testplatform.
=> `pj-rehearse`: clarify where to obtain usage info

cmd/cluster-display/main.go
=> cluster-display: return zero value when err!=nil

cmd/sippy-config-generator/main.go, cmd/testgrid-config-generator/main.go, pkg/util/testgrid.go
[TRT-753](https://issues.redhat.com/browse/TRT-753)
=> Include test grid url for non payload jobs on the informing dashboard

images/tide-config-manager/Dockerfile
=> Add tide-config-manager image

images/dptp-3312-hypershift-leaks-cleaner/Dockerfile, images/dptp-3312-hypershift-leaks-cleaner/cleanup-hypershift-leaks.sh
Clean up HyperShift created but expired AWS resources.
=> Fix issue DPTP-3312 Clean up leaked resources

pkg/controller/hypershift_namespace_reconciler/hypershift_namespace_reconciler.go, pkg/controller/hypershift_namespace_reconciler/hypershift_namespace_reconciler_test.go
https://issues.redhat.com/browse/DPTP-3316
and
https://github.com/openshift/hypershift/pull/2036
=> hypershift_namespace_reconciler: more hypershift namespaces

images/dptp-3312-hypershift-leaks-cleaner/cleanup-hypershift-leaks.sh
Fix two bugs in the script
1. Skip all roles starts with `ci-`
2. Skip resources with `expirationDate=None`
=> Fix issue DPTP-3312 Skip ci-ops items and items without expirationDate

pkg/image-graph-generator/client.go, pkg/image-graph-generator/graphql.go, pkg/image-graph-generator/images.go, pkg/image-graph-generator/images_test.go, pkg/image-graph-generator/operator.go
=> introduce the fake client and add unittests for the images creation

cmd/github-ldap-user-group-creator/main.go
=> github-ldap-user-group-creator: retry on upsertGroup

pkg/api/types.go
https://github.com/openshift/release/pull/36592
=> Add new profile for QE Fleet-Manager

pkg/controller/prpqr_reconciler/prpqr_reconciler.go, pkg/controller/prpqr_reconciler/testdata/zz_fixture_prowjobs_TestReconcile_basic_aggregated_case.yaml, pkg/controller/prpqr_reconciler/testdata/zz_fixture_prowjobs_TestReconcile_basic_case.yaml, pkg/controller/prpqr_reconciler/testdata/zz_fixture_prowjobs_TestReconcile_basic_case_with_metal_override.yaml, pkg/controller/prpqr_reconciler/testdata/zz_fixture_prowjobs_TestReconcile_basic_case_with_variant.yaml, pkg/controller/prpqr_reconciler/testdata/zz_fixture_prowjobs_TestReconcile_basic_case_with_vsphere_override.yaml, pkg/controller/prpqr_reconciler/testdata/zz_fixture_prowjobs_TestReconcile_multiple_case__one_of_the_prowjobs_already_exists.yaml, pkg/jobrunaggregator/jobrunaggregatoranalyzer/analyzer.go
Revert timeout bumps from https://github.com/openshift/ci-tools/pull/3218 and https://github.com/openshift/ci-tools/pull/3258
Complementary to https://github.com/openshift/release/pull/36759
/assign @xueqzhan @sanchezl
=> Revert timeouts

pkg/jobrunaggregator/jobrunaggregatoranalyzer/analyzer_disruption.go
[TRT-869](https://issues.redhat.com/browse/TRT-869)
=> Exclude ci cluster backend when aggregate disruption tests

pkg/dispatcher/config.go, pkg/dispatcher/config_test.go
Tests are WIP
/hold
/cc @hongkailiu 
@hongkailiu please check what you think about this solution if you have something against it.
=> Enable possibility to change cloud assignment during dispatch

pkg/jobrunaggregator/jobrunaggregatoranalyzer/analyzer_disruption.go
[TRT-889](https://issues.redhat.com/browse/TRT-889)
=> Skip disruption aggregation for azure jobs for now

cmd/clusterimageset-updater/main.go, pkg/api/types.go, pkg/release/prerelease/client.go, pkg/webreg/zz_generated.ci_operator_reference.go
See https://github.com/openshift/release/pull/36890 for sample usage
=> DPTP-3326: Allow clusterpools to specify a release stream to select the release version from

cmd/sprint-automation/main.go
This PR fixes a nil pointer dereference that occurs when a Jira card has no assignee.
```
[signal SIGSEGV: segmentation violation code=0x1 addr=0xb0 pc=0x19fa40e]
goroutine 1 [running]:
main.getIssuesNeedingApproval(0xc000228180)
/go/src/github.com/openshift/ci-tools/cmd/sprint-automation/main.go:448 +0x3ee
main.sendTeamDigest(0xc0004ee810?, 0x36?, 0x0?)
/go/src/github.com/openshift/ci-tools/cmd/sprint-automation/main.go:193 +0x4e
main.main()
/go/src/github.com/openshift/ci-tools/cmd/sprint-automation/main.go:122 +0x745
{"component":"entrypoint","error":"wrapped process failed: exit status 2","file":"k8s.io/test-infra/prow/entrypoint/run.go:79","func":"k8s.io/test-infra/prow/entrypoint.Options.Run","level":"error","msg …
```
=> Sprint Automation: Handle nil Jira assignee

pkg/api/types.go, pkg/defaults/defaults.go, pkg/defaults/defaults_test.go, pkg/validation/config.go, pkg/validation/config_test.go, pkg/webreg/zz_generated.ci_operator_reference.go
Requested by @qbarrand via [slack](https://redhat-internal.slack.com/archives/CBN38N3MW/p1678800245341399?thread_ts=1678118334.237179&cid=CBN38N3MW).
=> oo-testing: opt out building index image

pkg/api/types.go
Add QE dedicated azure cluster profile for marketplace image testing
=> [azure] add QE dedicated azure cluster profile for marketplace image testing

cmd/pj-rehearse/server.go
The format of the errors we bubble up to the user could use a little work. This will make it so that the usage details are **always** at the end of the comment when they appear, and the error itself will be within a code block.
=> `pj-rehearse`: better error output

pkg/api/types.go
https://issues.redhat.com/browse/SPLAT-728
Added a dedicated Local Zones profile to run periodically to validate that feature.
The target account will be the one fully managed by SPLAT team.
=> SPLAT-728: added AWS local zones profile

pkg/controller/prpqr_reconciler/prpqr_reconciler.go, pkg/controller/prpqr_reconciler/testdata/zz_fixture_prowjobs_TestReconcile_basic_aggregated_case.yaml
Still having errors with the tests colliding.
Reverts openshift/ci-tools#3343
=> Revert "One build for aggregate payload jobs"

pkg/retester/cache.go, pkg/retester/fileBackOffCache.go, pkg/retester/retester.go, pkg/retester/retester_test.go
=> retester: interfacing backoffCache

cmd/dptp-controller-manager/main.go, pkg/controller/promotionreconciler/reconciler.go, pkg/controller/promotionreconciler/reconciler_test.go
We found image jobs are triggered recently in openshift-priv without the counter job from openshift.
It could be `promotionreconciler` that triggers it.
We want it to ignore those cases.
=> promotionreconciler: ignore imagestreams

pkg/controller/test-images-distributor/test_images_distributor.go
This reverts commit aa611e925c0ba3c1b30c9e4b2b42efbaa4129f7d - #3132 
More details on: [DPTP-3357](https://issues.redhat.com//browse/DPTP-3357)
/cc @droslean
=> Revert "test-images-distributor: distribute multiarch IS"

cmd/ci-operator/main.go
As a follow up to https://github.com/openshift/ci-tools/pull/3354, we need to trim this suffix off for input resolution. Otherwise, it defeats the purpose as each aggregate run ends up in it's own namespace again. 
There are a couple of ways to go about this, but each of the others that I attempted resulted in complex and far-reaching changes. Simply trimming it off for input resolution should do the trick in a self-contained manner where we cannot accidentally break something else.
/cc @jmguzik @bbguimaraes 
=> `ci-operator`: trim target-additional-suffix for input resolution

pkg/controller/prpqr_reconciler/prpqr_reconciler.go, pkg/controller/prpqr_reconciler/prpqr_reconciler_test.go, pkg/controller/prpqr_reconciler/testdata/zz_fixture_prowjobs_TestReconcile_basic_aggregated_case.yaml, pkg/controller/prpqr_reconciler/testdata/zz_fixture_prowjobs_TestReconcile_basic_case.yaml, pkg/controller/prpqr_reconciler/testdata/zz_fixture_prowjobs_TestReconcile_basic_case_with_metal_override.yaml, pkg/controller/prpqr_reconciler/testdata/zz_fixture_prowjobs_TestReconcile_basic_case_with_variant.yaml, pkg/controller/prpqr_reconciler/testdata/zz_fixture_prowjobs_TestReconcile_basic_case_with_vsphere_override.yaml, pkg/controller/prpqr_reconciler/testdata/zz_fixture_prowjobs_TestReconcile_multiple_case__one_of_the_prowjobs_already_exists.yaml
Secret args and volumes aren't being generated properly.
Reverts openshift/ci-tools#3364
=> Revert "One build for aggregate jobs v.4"

pkg/controller/prpqr_reconciler/prpqr_reconciler.go, pkg/controller/prpqr_reconciler/testdata/zz_fixture_prowjobs_TestReconcile_basic_aggregated_case.yaml, pkg/controller/prpqr_reconciler/testdata/zz_fixture_prowjobs_TestReconcile_basic_case.yaml, pkg/controller/prpqr_reconciler/testdata/zz_fixture_prowjobs_TestReconcile_basic_case_with_metal_override.yaml, pkg/controller/prpqr_reconciler/testdata/zz_fixture_prowjobs_TestReconcile_basic_case_with_variant.yaml, pkg/controller/prpqr_reconciler/testdata/zz_fixture_prowjobs_TestReconcile_basic_case_with_vsphere_override.yaml, pkg/controller/prpqr_reconciler/testdata/zz_fixture_prowjobs_TestReconcile_multiple_case__one_of_the_prowjobs_already_exists.yaml, pkg/jobrunaggregator/jobrunaggregatoranalyzer/analyzer.go
Complimentary to https://github.com/openshift/release/pull/38223
/hold
=> Increase timeouts for payload jobs to land k8s 1.27

pkg/controller/prpqr_reconciler/prpqr_reconciler.go, pkg/controller/prpqr_reconciler/prpqr_reconciler_test.go, pkg/controller/prpqr_reconciler/testdata/zz_fixture_prowjobs_TestReconcile_basic_aggregated_case.yaml, pkg/controller/prpqr_reconciler/testdata/zz_fixture_prowjobs_TestReconcile_basic_case.yaml, pkg/controller/prpqr_reconciler/testdata/zz_fixture_prowjobs_TestReconcile_basic_case_with_metal_override.yaml, pkg/controller/prpqr_reconciler/testdata/zz_fixture_prowjobs_TestReconcile_basic_case_with_variant.yaml, pkg/controller/prpqr_reconciler/testdata/zz_fixture_prowjobs_TestReconcile_basic_case_with_vsphere_override.yaml, pkg/controller/prpqr_reconciler/testdata/zz_fixture_prowjobs_TestReconcile_multiple_case__one_of_the_prowjobs_already_exists.yaml
Re-stabilize the plugin after testing.
Reverts openshift/ci-tools#3375
/hold for test to complete
=> Revert "One build for payload aggregate command (v.5)"

cmd/sprint-automation/main.go
Follow up https://redhat-internal.slack.com/archives/C03BH6YMGN9/p1681736444862769?thread_ts=1681718442.079969&cid=C03BH6YMGN9
=> sprint-automation: opt out sending b02's upgrade notifications

cmd/release/README.md
I somehow failed to push this one together with the others to
https://github.com/openshift/ci-tools/pull/3154 yesterday.
/assign danilo-gemoli
=> cmd/release: correct example

images/dptp-3312-hypershift-leaks-cleaner/cleanup-hypershift-leaks.sh
DPP pruner is not fast enough to clean up these leaked Route53 private zones.
Ref: #incident-hypershift-max-hosted-zone
Ref: https://redhat-internal.slack.com/archives/CFUGK0K9R/p1682009160992429
=> Fix issue DPTP-3312 Remove Route53 zones

pkg/controller/prpqr_reconciler/prpqr_reconciler.go, pkg/controller/prpqr_reconciler/prpqr_reconciler_test.go, pkg/controller/prpqr_reconciler/testdata/zz_fixture_prowjobs_TestReconcile_basic_aggregated_case.yaml, pkg/controller/prpqr_reconciler/testdata/zz_fixture_prowjobs_TestReconcile_basic_case.yaml, pkg/controller/prpqr_reconciler/testdata/zz_fixture_prowjobs_TestReconcile_basic_case_with_metal_override.yaml, pkg/controller/prpqr_reconciler/testdata/zz_fixture_prowjobs_TestReconcile_basic_case_with_variant.yaml, pkg/controller/prpqr_reconciler/testdata/zz_fixture_prowjobs_TestReconcile_basic_case_with_vsphere_override.yaml, pkg/controller/prpqr_reconciler/testdata/zz_fixture_prowjobs_TestReconcile_multiple_case__one_of_the_prowjobs_already_exists.yaml
This time I was able to manually submit a couple of prowjobs with my recent changes to `ci-operator` and it went well. I would like to test the whole thing end-to-end now. Either way I will revert this one as I am sure there are other edge cases I need to address.
/cc @jmguzik
=> one build for aggregate runs (V6)

pkg/controller/prpqr_reconciler/prpqr_reconciler.go, pkg/controller/prpqr_reconciler/prpqr_reconciler_test.go, pkg/controller/prpqr_reconciler/testdata/zz_fixture_prowjobs_TestReconcile_basic_aggregated_case.yaml, pkg/controller/prpqr_reconciler/testdata/zz_fixture_prowjobs_TestReconcile_basic_case.yaml, pkg/controller/prpqr_reconciler/testdata/zz_fixture_prowjobs_TestReconcile_basic_case_with_metal_override.yaml, pkg/controller/prpqr_reconciler/testdata/zz_fixture_prowjobs_TestReconcile_basic_case_with_variant.yaml, pkg/controller/prpqr_reconciler/testdata/zz_fixture_prowjobs_TestReconcile_basic_case_with_vsphere_override.yaml, pkg/controller/prpqr_reconciler/testdata/zz_fixture_prowjobs_TestReconcile_multiple_case__one_of_the_prowjobs_already_exists.yaml
Revert post test.
Reverts openshift/ci-tools#3389
=> Revert "one build for aggregate runs (V6)"

images/dptp-3312-hypershift-leaks-cleaner/cleanup-hypershift-leaks.sh
Clean up HyperShift domains under base domain as well.
=> Fix issue DPTP-3312 Clean up base domain in Route53

images/dptp-3312-hypershift-leaks-cleaner/cleanup-hypershift-leaks.sh
Ref: https://redhat-internal.slack.com/archives/CBN38N3MW/p1682686169214209
Incorrectly deleted the base domain
=> Fix bug for deleting base domain

pkg/controller/prpqr_reconciler/prpqr_reconciler.go, pkg/controller/prpqr_reconciler/prpqr_reconciler_test.go, pkg/controller/prpqr_reconciler/testdata/zz_fixture_prowjobs_TestReconcile_basic_aggregated_case.yaml, pkg/controller/prpqr_reconciler/testdata/zz_fixture_prowjobs_TestReconcile_basic_case.yaml, pkg/controller/prpqr_reconciler/testdata/zz_fixture_prowjobs_TestReconcile_basic_case_with_metal_override.yaml, pkg/controller/prpqr_reconciler/testdata/zz_fixture_prowjobs_TestReconcile_basic_case_with_variant.yaml, pkg/controller/prpqr_reconciler/testdata/zz_fixture_prowjobs_TestReconcile_basic_case_with_vsphere_override.yaml, pkg/controller/prpqr_reconciler/testdata/zz_fixture_prowjobs_TestReconcile_multiple_case__one_of_the_prowjobs_already_exists.yaml
Reverts openshift/ci-tools#3399
Revert after testing.
/hold until testing is complete
=> Revert "one build for aggregate jobs (V7)"

cmd/image-graph-generator/types.graphql, pkg/image-graph-generator/images.go, pkg/image-graph-generator/images_test.go, pkg/image-graph-generator/manifests.go
=> [image-graph-generator] include multiple inputs on all images in the graph as parents

cmd/payload-testing-prow-plugin/server.go, cmd/payload-testing-prow-plugin/server_test.go
A couple of items fell through the cracks in https://github.com/openshift/ci-tools/pull/3421:
- I mistakenly moved the trusted user check prior to verifying that the plugin needed to act on the comment. This simplified the code, but is a performance concern.
- Incorrect logging
- We gather jobs that are already completed. If they are old enough, they no longer exist and result in an error when getting them with the kubeclient. We now check that prior to actually getting the jobs, and we also report the specific jobs that failed to abort if necessary.
=> `payload-testing`: bug fix and cleanup

pkg/jobrunaggregator/jobruntestcaseanalyzer/analyzer.go
[TRT-1020](https://issues.redhat.com//browse/TRT-1020)
Currently the proxy job renders the title as "---", this fixes it so include/exclude feed into the report title.
=> Improve test case analyzer titles

cmd/pod-scaler/admission.go
We are considering making the `pod-scaler` the source of truth for resource requests. Prior to doing so, we need to get an idea on what percentage of workloads have a determined request amount that is **lower** than that which is configured. I am attempting to determine this in multiple ways, but one that just requires waiting and then gathering the results is here. I will wait 1 week to 1 month after this change to see what percentage are configured higher than the determined amount.
For: https://issues.redhat.com/browse/DPTP-2938
=> `pod-scaler`: add logging when determined amount smaller than configured

pkg/api/types.go
https://github.com/openshift/release/pull/39749
=> Add new profile: aws-perf-qe

pkg/util/pods.go
Now that pod deletion events are properly reported as a result of
https://github.com/openshift/ci-tools/pull/3281, it is possible to gather more
information and include it in the output log.
```
INFO[2023-05-15T13:21:15Z] Executing test verify
WARN[2023-05-15T13:31:33Z] Pod verify is being unexpectedly deleted
WARN[2023-05-15T13:31:33Z] Pod verify is being unexpectedly deleted
INFO[2023-05-15T13:31:35Z] Logs for container test in pod verify:
…
WARN[2023-05-15T13:31:35Z] Pod verify is being unexpectedly deleted
WARN[2023-05-15T13:31:35Z] failed to get object after finishing watch    error=pods "verify" not found
INFO[2023-05-15T13:31:35Z] Ran for 14m16s
```
https://prow.ci.openshift.org/view/gs/origin-ci-test/pr-logs/pull/openshift_hypershift/2559/pull-ci-openshift-hypershift-release-4.12-v …
=> ci-operator: log events when pods are deleted

cmd/ci-operator-checkconfig/main.go
https://issues.redhat.com/browse/DPTP-3395
=> Avoid config-files for feature branches

pkg/jobrunaggregator/jobrunaggregatorlib/ci_data_client.go
Noted aggregated disruption started to use [previous release](https://prow.ci.openshift.org/view/gs/origin-ci-test/logs/aggregated-azure-ovn-upgrade-4.14-micro-release-openshift-release-analysis-aggregator/1664131335981109248) backstop data
`(Using previous release historical data from job: periodic-ci-openshift-release-master-ci-4.13-e2e-azure-ovn-upgrade) Failed: Passed 1 times, failed 9 times`
Reviewed the GetBackendDisruptionRowCountByJob query and noted it was now returning 0 for it.TotalRows.  Testing revealed we had to call it.Next to populate that value now, this seems to be a change from what worked previously.
Updated the call to explicitly get a Count and call it.Next to populate the result
=> TRT-1071: Update RowCount query as previous version started returning 0.

go.mod, go.sum, vendor/k8s.io/test-infra/prow/git/v2/client_factory.go, vendor/k8s.io/test-infra/prow/git/v2/interactor.go, vendor/k8s.io/test-infra/prow/plugins/config.go, vendor/k8s.io/test-infra/prow/plugins/plugin-config-documented.yaml, vendor/k8s.io/test-infra/prow/pod-utils/downwardapi/jobspec.go, vendor/modules.txt
=> update test-infra fork vendors

pkg/steps/release/promote.go, pkg/steps/release/promote_test.go, pkg/steps/release/testdata/zz_fixture_TestGetPromotionPod_basic_case.yaml
https://issues.redhat.com/browse/DPTP-3452
/cc @openshift/test-platform @jupierce 
/hold
Need to set up the secret with the push credentials for quay.io
=> Promote CI images to Quay as well

pkg/jobrunaggregator/jobrunaggregatoranalyzer/analyzer.go, pkg/jobrunaggregator/jobrunaggregatorapi/gcs_jobrun.go, pkg/jobrunaggregator/jobrunaggregatorlib/ci_data_client.go, pkg/jobrunaggregator/jobrunaggregatorlib/jobrun_locator.go, pkg/jobrunaggregator/jobrunaggregatorlib/retrying_ci_data_client.go, pkg/jobrunaggregator/jobrunaggregatorlib/util.go, pkg/jobrunaggregator/jobruntestcaseanalyzer/analyzer.go, pkg/jobrunaggregator/jobruntestcaseanalyzer/cidataclient_test.go
Reverts openshift/ci-tools#3483
=> Revert "Revert "reduce job run query size""

pkg/steps/release/promote.go, pkg/steps/release/testdata/zz_fixture_TestGetPromotionPod_basic_case.yaml, pkg/steps/release/testdata/zz_fixture_TestGetPromotionPod_tag_by_commit_is_true.yaml
=> keep manifest list on image mirroring on promotion

pkg/jobrunaggregator/jobrunaggregatoranalyzer/analyzer_test.go, pkg/jobrunaggregator/jobrunaggregatorapi/gcs_jobrun.go, pkg/jobrunaggregator/jobrunaggregatorlib/util.go
[TRT-1078](https://issues.redhat.com/browse/TRT-1078)
=> minimize calls to big query for getting job runs

pkg/jobrunaggregator/jobrunaggregatoranalyzer/analyzer.go
Handle case where a job might fail to upgrade but others finish.  Only skip looking for the MasterNodesUpdated flag when we have a 'Y'.
=> TRT-945: Only stop checking MasterNodesUpdated flag if we find 'Y'

pkg/steps/index_generator.go, pkg/steps/index_generator_test.go, pkg/steps/testdata/isTags/59c70bff_image.yaml, pkg/steps/testdata/isTags/redhat-operator-index_v4.10_istag_manifests.yaml
https://issues.redhat.com/browse/DPTP-3534
=> Determine the type of index with the image in manifests

cmd/payload-testing-prow-plugin/filetestresolver.go, cmd/payload-testing-prow-plugin/filetestresolver_test.go
=> Modify fileresolver to allow payload plugin to trigger all openshift periodics

pkg/api/promotion.go, pkg/api/promotion_test.go, pkg/defaults/defaults.go, pkg/steps/release/promote.go
=> Include registry in the target name

pkg/api/types.go
Prow PR: https://github.com/openshift/release/pull/41217
=> add QE perf profiles: aws-perfscale-qe and aws-perfscale-lrc-qe

pkg/api/types.go
Remove vsphere-discon profile due to VMC migration
=> Remove vsphere-discon profile

pkg/api/types.go
Release PR https://github.com/openshift/release/pull/41324
=> create aws-terraform-qe profile

pkg/controller/prpqr_reconciler/prpqr_reconciler.go, pkg/controller/prpqr_reconciler/testdata/zz_fixture_prowjobs_TestReconcile_basic_aggregated_case.yaml, pkg/controller/prpqr_reconciler/testdata/zz_fixture_prowjobs_TestReconcile_basic_case.yaml, pkg/controller/prpqr_reconciler/testdata/zz_fixture_prowjobs_TestReconcile_basic_case_with_metal_override.yaml, pkg/controller/prpqr_reconciler/testdata/zz_fixture_prowjobs_TestReconcile_basic_case_with_variant.yaml, pkg/controller/prpqr_reconciler/testdata/zz_fixture_prowjobs_TestReconcile_basic_case_with_vsphere_override.yaml, pkg/controller/prpqr_reconciler/testdata/zz_fixture_prowjobs_TestReconcile_multiple_case__one_of_the_prowjobs_already_exists.yaml, pkg/jobrunaggregator/jobrunaggregatoranalyzer/analyzer.go
This reverts commit 46c5b20bfeede9cc93960145b474242179076eea.
=> Increase timeouts for payload jobs to land k8s 1.28

images/dptp-3312-hypershift-leaks-cleaner/cleanup-hypershift-leaks.sh
Add removal outdated and broken HyperShift clusters
=> Fix issue DPTP-3312 Remove broken clusters

cmd/ci-operator-config-mirror/main.go, pkg/config/load.go, test/integration/ci-operator-config-mirror/output-only-super/super-priv/barry-white/super-priv-barry-white-master.yaml, test/integration/ci-operator-config-mirror/output-only-super/super-priv/barry-white/super-priv-barry-white-official.yaml, test/integration/ci-operator-config-mirror/output-only-super/super-priv/barry-white/super-priv-barry-white-official__releases.yaml
/cc @openshift/test-platform @stlaz 
=> include the whitelisted repositories on different organization than --only-org

cmd/entrypoint-wrapper/main.go
This PR changes the exit code of the entrypoint-wrapper to return the exit code of the wrapped process.
cc @bbguimaraes 
[DPTP-3533](https://issues.redhat.com/browse/DPTP-3533) does not need this, because the wrapper as of now still returns zero if success, just when the child exits with another code it will exit with 1. That's changed here.
=> `entrypoint-wrapper`: exit with wrapped exit code

hack/run-job-aggregator-analyzer.sh, pkg/jobrunaggregator/jobrunaggregatorapi/types_row_historical_data.go, pkg/jobrunaggregator/jobrunaggregatorlib/ci_data_client.go, pkg/jobrunaggregator/jobrunhistoricaldataanalyzer/analyzer.go, pkg/jobrunaggregator/jobrunhistoricaldataanalyzer/pr_message_template.md, pkg/jobrunaggregator/jobrunhistoricaldataanalyzer/types.go, pkg/jobrunaggregator/jobrunhistoricaldataanalyzer/util.go
Includes both previous release data along with current release data
=> TRT-930: Including previous release data in ci-tools

pkg/api/domain.go, pkg/api/types.go
=> Add vsphere02

cmd/promoted-image-governor/main.go
It is found with the help of https://github.com/openshift/ci-tools/pull/3591 that 
```
curl -s https://storage.googleapis.com/origin-ci-test/logs/periodic-prow-auto-config-brancher/1696961198261538816/build-log.txt | grep 'quay.io/openshift/origin-fedora-coreos:4.15.0'
{"component":"promoted-image-governor","dst":"quay.io/openshift/origin-fedora-coreos:4.15.0","file":"/go/src/github.com/openshift/ci-tools/cmd/promoted-image-governor/main.go:264","filename":"mapping_origin_4_15","func":"main.generateMappings","level":"debug","mappingConfig.SourceNamespace":"origin","msg":"Insert into mapping ...","severity":"debug","src":"registry.ci.openshift.org/origin/4.15:fedora-coreos","tag.Namespace":"origin","time":"2023-08-30T19:06:28Z"}
{"component":"promoted-image-governor","dst":"quay.io/openshif …
```
=> promoted-image-governor: process each promoted tag only once

pkg/jobrunaggregator/jobrunaggregatorapi/types_row_historical_data.go, pkg/jobrunaggregator/jobrunaggregatorlib/ci_data_client.go, pkg/jobrunaggregator/jobrunaggregatorlib/ci_data_client_mock.go, pkg/jobrunaggregator/jobrunaggregatorlib/retrying_ci_data_client.go, pkg/jobrunaggregator/jobrunhistoricaldataanalyzer/analyzer.go
Updating ci-tools BigQuery query to include first time alert nurp was observed and updates the query_results.json
=> TRT-932: Adding alert query for known alerts

cmd/sanitize-prow-jobs/main.go
=> [sanitize-prow-jobs] configure a different ci-operator image for the arm01 cluster

pkg/api/types.go
This PR is to add a new profile for GCP ARM 
Ref: [ARMOCP-563](https://issues.redhat.com/browse/ARMOCP-563)
=> Add GCP arm64 cluster profile: gcp-arm64

images/multi-arch-builder-controller/Dockerfile
That's me keep learning and forgetting how builds work...
See https://github.com/openshift/ci-tools/pull/3592
/cc @droslean
=> `multi-arch-builder-controller`: add manifest-tool 

images/ci-operator-prowgen/Dockerfile
/cc @openshift/test-platform @danilo-gemoli
=> add the sanitize-prow-jobs binary in the ci-operator-prowgen image

pkg/api/types.go, pkg/dispatcher/config.go, pkg/dispatcher/config_test.go
selects vsphere build cluster to use based on cluster-profile
=> select vsphere build cluster to use based on cluster-profile

cmd/ci-images-mirror/main.go, hack/run-ci-images-mirror.sh, pkg/api/promotion.go, pkg/controller/quay_io_ci_images_distributor/mirror.go, pkg/controller/quay_io_ci_images_distributor/oc_quay_io_image_helper.go, pkg/controller/quay_io_ci_images_distributor/quay_io_ci_images_distributor.go
https://issues.redhat.com/browse/DPTP-3529
=> quay_io_ci_images_distributor: generate mirror tasks

cmd/ci-images-mirror/main.go, pkg/controller/quay_io_ci_images_distributor/mirror.go, pkg/controller/quay_io_ci_images_distributor/oc_quay_io_image_helper.go, pkg/controller/quay_io_ci_images_distributor/quay_io_ci_images_distributor.go
https://issues.redhat.com/browse/DPTP-3529
=> quay_io_ci_images_distributor: consume mirroring tasks

OWNERS
Adding @deepsm007 to the Owners list
=> Updating Owners

pkg/jobrunaggregator/jobrunaggregatoranalyzer/pass_fail.go
[TRT-1205](https://issues.redhat.com//browse/TRT-1205)
This changes the pass/fail logic in aggregation to support the concept of "never failing" tests. The first never failing test is "Undiagnosed panic in pod" which must always pass.
Re-aggregating https://prow.ci.openshift.org/view/gs/origin-ci-test/logs/aggregated-azure-ovn-upgrade-4.14-micro-release-openshift-release-analysis-aggregator/1694675626264367104 shows that undiagnosed panic now fails the aggregation:
=> aggregation: pods should never panic

cmd/autoconfigbrancher/main.go
`append` is a variadic function.
=> autoconfigbrancher: remove unnecessary slices

pkg/controller/prpqr_reconciler/prpqr_reconciler.go, pkg/controller/prpqr_reconciler/testdata/zz_fixture_prowjobs_TestReconcile_basic_aggregated_case.yaml, pkg/controller/prpqr_reconciler/testdata/zz_fixture_prowjobs_TestReconcile_basic_case.yaml, pkg/controller/prpqr_reconciler/testdata/zz_fixture_prowjobs_TestReconcile_basic_case_with_metal_override.yaml, pkg/controller/prpqr_reconciler/testdata/zz_fixture_prowjobs_TestReconcile_basic_case_with_variant.yaml, pkg/controller/prpqr_reconciler/testdata/zz_fixture_prowjobs_TestReconcile_basic_case_with_vsphere_override.yaml, pkg/controller/prpqr_reconciler/testdata/zz_fixture_prowjobs_TestReconcile_multiple_case__one_of_the_prowjobs_already_exists.yaml, pkg/jobrunaggregator/jobrunaggregatoranalyzer/analyzer.go
This reverts commit 91b490f6097e7292ed4a86629caea5abdd25e358.
/assign @soltysh @dgoodwin
=> Revert "Increase timeouts for payload jobs to land k8s 1.28"

pkg/defaults/defaults.go
should fix https://prow.ci.openshift.org/view/gs/origin-ci-test/pr-logs/pull/openshift_ci-tools/3581/pull-ci-openshift-ci-tools-master-lint/1709316574415949824
/cc @hongkailiu @smg247 @openshift/test-platform
=> fix resolving the root image when manifest list exists

pkg/defaults/defaults.go
=> fix build cache: specify the missing namespace

pkg/defaults/defaults.go
/cc @hongkailiu @smg247 @openshift/test-platform
=> fix resolving the root cached image from a manifest list

cmd/cluster-display/main.go, cmd/cluster-display/main_test.go, pkg/prowconfigutils/config.go
https://issues.redhat.com/browse/DPTP-3659
@openshift/test-platform
=> cluster-display: support disabled clusters

cmd/dptp-controller-manager/main.go
https://issues.redhat.com/browse/DPTP-3659
=> dptp-cm: support disabled clusters

cmd/dptp-controller-manager/main.go
It will help to verify https://github.com/openshift/ci-tools/pull/3662/files
=> dptp-cm: logging the managers with their cluster names

pkg/api/types.go
https://issues.redhat.com/browse/RHTAP-1749
=> create aws-rhtap-qe profile

cmd/ci-secret-generator/main.go, cmd/ci-secret-generator/main_test.go, cmd/ci-secret-generator/testdata/TestValidateConfig/no_cluster_param.yaml, cmd/ci-secret-generator/testdata/TestValidateConfig/valid.yaml, pkg/api/secretgenerator/secretgenerator.go
https://issues.redhat.com/browse/DPTP-3659
=> ci-secret-generator: support disabled clusters

cmd/ci-images-mirror/README.md
=> Add cmd/ci-images-mirror/README.md

pkg/api/types.go
We are creating a new cluster type for PER (Power Edge Routing) zones.
=> PowerVS: create powervs-3

pkg/api/types.go, pkg/prowgen/prowgen.go, pkg/webreg/zz_generated.ci_operator_reference.go, test/integration/ci-operator-prowgen/input/config/super/duper/super-duper-master.yaml, test/integration/ci-operator-prowgen/output/jobs/super/duper/super-duper-master-presubmits.yaml
=> Add possibility to mark deprecated bundles as optional

cmd/applyconfig/applyconfig.go
Follow up https://issues.redhat.com/browse/DPTP-3659?focusedId=23220514&page=com.atlassian.jira.plugin.system.issuetabpanels%3Acomment-tabpanel#comment-23220514
/assign @smg247
=> applyconfig: support disabled clusters

pkg/manifestpusher/manifestpusher.go
https://issues.redhat.com/browse/DPTP-3710
/cc @openshift/test-platform @danilo-gemoli @deepsm007 
=> add a retry mechanism while pushing the manifest list image

pkg/manifestpusher/manifestpusher.go
follow-up of https://github.com/openshift/ci-tools/pull/3697
=> continue retrying on manifest list push error

cmd/pr-reminder/main.go
Follow up https://redhat-internal.slack.com/archives/CHY2E1BL4/p1697643603344849?thread_ts=1697616249.241239&cid=CHY2E1BL4
1. log the msg for debugging
2. keep sending msgs to others even upon hitting errors
/assign @smg247
=> pr-reminder: improve error handling

cmd/github-ldap-user-group-creator/main.go, cmd/github-ldap-user-group-creator/main_test.go
Issue: [DPTP-3328](https://issues.redhat.com/browse/DPTP-3328)
Enhancing the  `github-ldap-user-group-creator` for deleting users who are on clusters, but not in the rover groups anymore.
=> `github-ldap-user-group-creator`: Delete users not in rover

pkg/jobrunaggregator/jobrunaggregatorlib/util.go
[TRT-1240](https://issues.redhat.com/browse/TRT-1240)
=> Specify ci namespace when listening for prowjob change

pkg/controller/quay_io_ci_images_distributor/quay_io_ci_images_distributor.go
Before this PR, for an image stream tag on app.ci, we use `istag.Image.ObjectMeta.Name=imageInfo.digest` to tell if the image has been up to date where `imageInfo` is the result of `oc image info <target_image_in_quay>`.
We have found examples that the above reasoning is invalid.
With this PR, we calculate the source image's digest by `oc image info` as well.
=> ci-images-mirror: use oc-image-info for the source image

pkg/api/types.go
Ref: https://github.com/openshift/ci-tools/commit/958c6f9a5ee2626270a58b73cb5b28a160cfcb72
=> Fix issue DPTP-3720 Add CM to gcp-3

cmd/ci-images-mirror/main.go, pkg/controller/quay_io_ci_images_distributor/metrics.go, pkg/controller/quay_io_ci_images_distributor/oc_quay_io_image_helper.go
=> ci-images-mirror: add metrics

pkg/controller/quay_io_ci_images_distributor/mirror.go
=> quay_io_ci_images_distributor: fix memoryMirrorStore's Take function

pkg/controller/quay_io_ci_images_distributor/metrics.go, pkg/controller/quay_io_ci_images_distributor/mirror.go
=> ci-images-mirror: add metric/mirror_queue_depth

cmd/cluster-init/main.go, cmd/cluster-init/testdata/clusters/build-clusters/existingCluster/common_cert_manager, test/integration/cluster-init/create/expected/clusters/build-clusters/existingCluster/common_cert_manager, test/integration/cluster-init/create/expected/clusters/build-clusters/newCluster/common_cert_manager, test/integration/cluster-init/create/input/clusters/build-clusters/existingCluster/common_cert_manager, test/integration/cluster-init/update/expected/clusters/build-clusters/existingCluster/common_cert_manager, test/integration/cluster-init/update/input/clusters/build-clusters/existingCluster/common_cert_manager
Add missing cert-manager symlink
=> Fix issue DPTP-3711 add common_cert_manager

cmd/check-gh-automation/main.go, cmd/check-gh-automation/main_test.go, hack/local-check-gh-automation.sh
- **Files Modified:**
- `/check-gh-automation/main.go`
- `hack/local-check-gh-automation.sh`
- `main_test.go` (additional changes)
- **Goal:** Ensure proper permissions for `openshift-cherrypick-robot` in repositories using the cherrypick plugin.
1. **`main.go`**: 
- Added constants for cherrypick plugin and robot.
- New field for plugin configuration in `options` struct.
- Plugin flag parsing in `gatherOptions`.
- Initialization for plugin configuration in `main`.
- Enhanced `checkRepos` to validate `openshift-cherrypick-robot`.
2. **`local-check-gh-automation.sh`**:
- Reordered function definitions.
- New directory setup for plugin data.
- Extracted plugin configuration.
- Updated `go run` command for plugin-related flags.
3. **`main_test.go`**:
- Adjustments to align with changes in …
=> check-gh-automation bug resolution

cmd/qci-appci/main.go
https://issues.redhat.com/browse/DPTP-3749
=> qci-appci: podman works for authenticated users

cmd/qci-appci/README.md
https://issues.redhat.com/browse/DPTP-3749
=> Add cmd/qci-appci/README.md

cmd/qci-appci/main.go
Before this PR, all authenticated users will get though the proxy.
Now, only users with access to ocp images do.
/hold
Require https://github.com/openshift/release/pull/45880
=> qci-appci: add sar check on users

pkg/api/types.go
Closes https://github.com/devfile/api/issues/1333
Adds a new cluster profile for running OpenShift CI workloads for devfile repositories
=> Create aws-devfile profile

cmd/qci-appci/main.go
=> qci-appci: log auth header in response upon 401

cmd/qci-appci/main.go
https://issues.redhat.com/browse/DPTP-3760
=> qci-appci: support robot's Access to QCI-APPCI

cmd/qci-appci/main.go
=> qci-appci: reuse variable username

cmd/qci-appci/main.go, cmd/qci-appci/main_test.go
=> qci-appci: better test coverage

cmd/cluster-display/main.go
To follow up https://redhat-internal.slack.com/archives/CBN38N3MW/p1701180766676159?thread_ts=1701106555.174429&cid=CBN38N3MW
/assign @bear-redhat 
Local test:
```console
curl -s localhost:8090/api/v1/clusters | jq -r '.data[]|select(.cluster=="hive") | .hypershiftSupportedVersions'
["4.15","4.14","4.13"]
```
/hold
Requires https://github.com/openshift/release/pull/46215
=> cluster-display: return Hypershift's supported versions

images/dptp-3312-hypershift-leaks-cleaner/cleanup-hypershift-leaks.sh
Add support for multiple cluster profiles and update credentials according to the cluster it was created with.
Connected to: https://github.com/openshift/release/pull/45376
Issue: [DPTP-3713](https://issues.redhat.com/browse/DPTP-3713)
/cc @bear-redhat
=> `hypershift-leaks-cleaner`: Support multiple cluster profiles

hack/run-dptp-controller-manager.sh, images/ci-secret-generator/oc_sa_create_kubeconfig.sh
Many things have been changed to debug the tool.
This PR is to make the script runnable again for local debugging.
=> dptp-cm: fix hack/run-dptp-controller-manager.sh

pkg/api/types.go, pkg/prowgen/prowgen.go, pkg/prowgen/prowgen_test.go, pkg/prowgen/testdata/zz_fixture_TestGeneratePresubmitForTest_presubmit_with_always_run_but_pipeline_run_if_changed_set.yaml, pkg/prowgen/testdata/zz_fixture_TestGeneratePresubmitForTest_presubmit_with_always_run_false_and_pipeline_run_if_changed.yaml, pkg/webreg/zz_generated.ci_operator_reference.go
It's need to try extending pipeline controller
=> Annotation field pipeline_run_if_changed

pkg/prowgen/prowgen.go
Since `ci-operator` are not being built on arm64 yet, this PR is a temporary workaround to allow promoting from `multi01` by running `ci-operator` on amd64 nodes only.
As soon as we manage to build `ci-operator` on the arechitectures we need, these changes would be no longer required and therefore reverted.
The only promotion ProwJobs that are going to be affected by the following are those whose a `.config.prowgen` exists and contains:
```
multi_arch: true
```
anything else is going to stay the same.
=> `ci-operator-prowgen`: Spawn promotion on amd64 nodes only when multiarch

pkg/api/types.go
We are creating a new cluster type for testing 4.16 on PowerVS.
=> PowerVS: Create new powervs-4 type

pkg/jobrunaggregator/jobrunaggregatoranalyzer/analyzer.go, pkg/jobrunaggregator/jobrunaggregatoranalyzer/analyzer_disruption.go, pkg/jobrunaggregator/jobrunaggregatoranalyzer/cmd.go, pkg/jobrunaggregator/jobrunaggregatoranalyzer/junit.go, pkg/jobrunaggregator/jobrunaggregatorapi/gcs_jobrun.go, pkg/jobrunaggregator/jobrunaggregatorlib/gcs_client.go, pkg/jobrunaggregator/jobrunbigqueryloader/alert.go, pkg/jobrunaggregator/jobrunbigqueryloader/cmd.go, pkg/jobrunaggregator/jobrunbigqueryloader/disruption.go, pkg/jobrunaggregator/jobruntestcaseanalyzer/analyzer.go, pkg/jobrunaggregator/jobruntestcaseanalyzer/cmd.go, pkg/jobrunaggregator/jobtableprimer/cmd.go, pkg/jobrunaggregator/jobtableprimer/create_jobs.go, pkg/jobrunaggregator/jobtableprimer/job_typer.go
Support option to specify gcs bucket for productization efforts.
=> trt-1407: support gcs bucket cmd line option

pkg/api/types.go
related: https://github.com/openshift/release/pull/46797
=> Add new cluster profile medik8s-aws

cmd/ci-secret-bootstrap/main.go, cmd/ci-secret-bootstrap/main_test.go
=> secret-bootstrap: support disabled clusters

pkg/api/types.go
Jira issue: https://issues.redhat.com/browse/GITOPS-3483
=> Create `gitops-aws` cluster profile 

cmd/github-ldap-user-group-creator/main.go
Follow up https://redhat-internal.slack.com/archives/CHY2E1BL4/p1703171209033809?thread_ts=1703122509.179219&cid=CHY2E1BL4
=> user-group-creator: support disabled clusters

cmd/github-ldap-user-group-creator/main.go, cmd/github-ldap-user-group-creator/main_test.go
Following up https://redhat-internal.slack.com/archives/CHY2E1BL4/p1704275099215689?thread_ts=1704274359.343049&cid=CHY2E1BL4
The cluster name could come from the config file such as
https://github.com/openshift/release/blob/1b5b95b197ec303ec0add4fab7b4b7f25ff38bd6/core-services/sync-rover-groups/_config.yaml#L53-L56
This case was not handled by https://github.com/openshift/ci-tools/pull/3866
=> user-group-creator: fix ensureGroups for disabled clusters

Makefile
=> fix the image registry route resolving on local e2e tests

pkg/api/types.go
JIRA issue: https://issues.redhat.com/browse/CRW-5370
Related PR: https://github.com/openshift/release/pull/47226
=> Add che-aws cluster profile for eclipse-che jobs

pkg/api/types.go
https://issues.redhat.com/browse/CORS-2580
release PR: https://github.com/openshift/release/pull/47479
=> Add AWS Outpost QE profile

cmd/ci-scheduling-webhook/prioritization.go
In one scenario, spot.io somehow seemed wedged and unable to scale build nodes. I think this may have occurred because it saw unutilized nodes with NoSchedule that pods could not be scheduled to.
Since spot.io only saw that there were already underutilized nodes, it didn't try to scale up.
=> Never set NoSchedule for spot.io nodes

pkg/registry/resolver.go, pkg/registry/resolver_test.go, pkg/registry/stack.go
This should make it possible to override the DNSConfig of a jobs individual steps from higher-level step-registry entries like workflows.
Note, I'm not confident I've understood how chains would interact with this. Would appreciate guidance from the team.
=> OCPBUGS-23211: Fix propagation of DNSConfig from Test configuration to Pod creation

pkg/api/types.go
=> Add nutanix zone profile

pkg/controller/promotionreconciler/reconciler.go, pkg/controller/promotionreconciler/reconciler_test.go
To replace https://github.com/openshift/ci-tools/pull/3270 which is closed by a bad push.
https://issues.redhat.com/browse/DPTP-2509
/hold
Need to watch the rolling
=> Trigger first promotion automatically if isTag does not exist

cmd/payload-testing-prow-plugin/server.go
Takes care of a longstanding TODO
=> `payload-testing-prow-plugin`: complete the plugin help section

Makefile, pkg/controller/promotionreconciler/reconciler.go, pkg/controller/promotionreconciler/reconciler_test.go
https://issues.redhat.com/browse/DPTP-2509
=> promotionreconciler: ignore istags from ns/build-cache

cmd/payload-testing-prow-plugin/server.go, cmd/payload-testing-prow-plugin/server_test.go
adds `/payload-aggregate-with-prs` command to trigger aggreagated payload testing jobs with additional PRs included in the payload.
Merge after https://github.com/openshift/ci-tools/pull/3915
=> `payload-testing-prow-plugin`: payload aggregate with prs command

pkg/jobconfig/files.go
=> prowgen: fix a corner case

pkg/steps/release/promote.go, pkg/steps/release/testdata/zz_fixture_TestGetPromotionPod_basic_case.yaml, pkg/steps/release/testdata/zz_fixture_TestGetPromotionPod_basic_case__arm64_only.yaml, pkg/steps/release/testdata/zz_fixture_TestGetPromotionPod_basic_case__multi_architecture.yaml, pkg/steps/release/testdata/zz_fixture_TestGetPromotionPod_promotion_quay.yaml
=> promotion: upgrade the oc version to 4.14

pkg/api/types.go
create new rosa-aws cluster profile for osde2e jobs 
[sdcicd-1210](https://issues.redhat.com//browse/sdcicd-1210)
=> added cluster-profile rosa-aws

pkg/api/types.go
Related to: openshift/release#45414
=> Add cluster_profile for redhat-openshift-ecosystem

pkg/validation/test.go, pkg/validation/test_test.go
https://issues.redhat.com/browse/DPTP-3870
/cc @openshift/test-platform @bparees
=> cron can be with run_if_changed if presubmit is true

pkg/testhelper/kubernetes/pod.go
This PR addresses https://issues.redhat.com/browse/DPTP-3866
/cc @Prucek @openshift/test-platform
=> `ci-operator`: Add lock to FakePodExecutor

cmd/cluster-init/main.go, test/integration/cluster-init/create/expected/clusters/build-clusters/existingCluster/common_cert_manager, test/integration/cluster-init/create/expected/clusters/build-clusters/newCluster/common_cert_manager, test/integration/cluster-init/create/input/clusters/build-clusters/existingCluster/common_cert_manager, test/integration/cluster-init/update/expected/clusters/build-clusters/existingCluster/common_cert_manager, test/integration/cluster-init/update/input/clusters/build-clusters/existingCluster/common_cert_manager
Prepare for using cert-manager-operator
=> Fix issue DPTP-3711 Remove common_cert_manager

cmd/cluster-init/update_bootstrap_secrets.go, test/integration/cluster-init/create/expected/core-services/ci-secret-bootstrap/_config.yaml, test/integration/cluster-init/update/expected/core-services/ci-secret-bootstrap/_config.yaml
=> DPTP-3786: Adding the QCI credentials into the registry pull secret

cmd/pj-rehearse/server.go
When tools don't do anything and don't tell the user why they explicitly choose not to do something, the UX is frustrating.
=> pj-rehearse: tell the user when you're ignoring them

cmd/qci-appci/main.go
=> qci-appci: add more logging fields for debugging

pkg/rehearse/rehearse.go
- Mirroring images is only required only once and we read the images from app.ci
- Follow up on a minor comment. https://github.com/openshift/ci-tools/pull/3812#discussion_r1500790567
/assign @Prucek
=> pj-rehearse: mirror the images only once

cmd/qci-appci/main.go, cmd/qci-appci/main_test.go, go.mod
This is to avoid bugging app.ci too often.
/assign @bear-redhat
=> qci-appci: generate jwt token

cmd/ci-operator-checkconfig/README.md, pkg/load/load.go, test/integration/pj-rehearse.sh, test/validate-checkconfig.sh
Updating paths as we are moving (https://github.com/openshift/release/pull/49127) the cluster profiles config into `ci-operator/step-registry` folder
/cc @droslean
=> Update cluster profiles config paths

pkg/steps/multi_stage/gen.go, test/e2e/multi-stage/assembled-release-no-injection.yaml, test/e2e/multi-stage/assembled-release.yaml, test/e2e/multi-stage/dependencies.yaml, test/e2e/multi-stage/e2e_test.go
Reverts openshift/ci-tools#4000
=> Revert "NO-JIRA: Use RHEL8 oc explicitly"

cmd/qci-appci/main.go
=> qci-appci: logging duration of app.ci token validation

cmd/cluster-init/update_bootstrap_secrets.go, test/integration/cluster-init/create/expected/core-services/ci-secret-bootstrap/_config.yaml, test/integration/cluster-init/update/expected/core-services/ci-secret-bootstrap/_config.yaml
Required by https://github.com/openshift/release/pull/49492
=> Add pull secret for quay.io/openshift/ci

pkg/config/release.go
Sometimes the `git checkout` in pj-rehearse [fails](https://github.com/openshift/release/pull/49286#issuecomment-1969478116). It is almost always resolved with a retry of the command. We should automatically do this up to `4` times in order to mitigate this for our users.
=> `pj-rehearse`: Retry git checkout to mitigate transient failures

images/dptp-3312-hypershift-leaks-cleaner/Dockerfile
https://github.com/openshift/release/pull/49650
=> DPTP-3312 Change to ubi image

pkg/api/types.go
https://github.com/openshift/release/pull/49703
=> Add new profile aws-autorelease-qe

cmd/pipeline-controller/main.go
I was thinking about creating some unit tests for that, but in the end this is one API call which is pretty straightforward I hope.
=> Pipeline controller: add info about repo being managed by pipeline ctrl

pkg/api/helper/imageextraction.go, pkg/api/helper/imageextraction_test.go, pkg/controller/quay_io_ci_images_distributor/quay_io_ci_images_distributor.go
This is needed because `FileGetterFactory` could return `nil, nil` (which would lead zero value of tag getting inserted).
https://github.com/openshift/ci-tools/blob/a6f24219a5526f810560be36770896d77023d299/pkg/github/github.go#L56-L58
Also added more unit tests to cover those cases.
=> Handle error better in TestInputImageStreamTagsFromResolvedConfig

images/dptp-3312-hypershift-leaks-cleaner/cleanup-hypershift-leaks.sh
The `dptp-3312-hypershift-leaks-cleaner` is not working properly, this PR is trying to address this issue.
/cc @bear-redhat
=> cleaner: remove whitespaces

OWNERS
Add @Prucek & remove bbguimaraes from/to OWNERS.
=> owners: add Prucek & remove bbguimaraes

cmd/ci-images-mirror/main.go, hack/run-ci-images-mirror.sh, pkg/controller/quay_io_ci_images_distributor/quay_io_ci_images_distributor.go
=> ci-images-mirror: fix a few things

pkg/steps/input_image_tag.go
Follow up https://redhat-internal.slack.com/archives/CBN38N3MW/p1710879181671709?thread_ts=1710775759.882629&cid=CBN38N3MW
Another code path similar to https://github.com/openshift/ci-tools/pull/4021/files
/cc @openshift/test-platform @bradmwilliams 
/hold
Let us test with the built image
=> input_image_tag: use ImageStreamImage for cluster-bot jobs

pkg/steps/input_image_tag.go, pkg/steps/release/create_release.go, pkg/steps/release/snapshot.go, pkg/steps/utils/image.go, pkg/steps/utils/image_test.go
https://issues.redhat.com/browse/DPTP-3913
=> Add retries on importing the input images

pkg/api/types.go
This is for leases in the mad02 zone.
=> PowerVS: Create new powervs-5 type

pkg/api/types.go
[SPLAT-1581](https://issues.redhat.com//browse/SPLAT-1581)
- Added new "vsphere-multi-vcenter" cluster profile
=> SPLAT-1581: Created new "vsphere-multi-vcenter" cluster profile.

pkg/api/types.go, pkg/prowgen/prowgen.go, pkg/prowgen/testdata/zz_fixture_TestGenerateJobs_multiarch_postsubmit_images__default_arch_and_others.yaml
=> schedule the multi arch jobs to the build10 cluster instead

cmd/cluster-display/main.go, cmd/cluster-display/main_test.go, cmd/github-ldap-user-group-creator/main_test.go, pkg/api/types.go
=> Update the name of the hive cluster: hosted-mgmt

pkg/api/types.go
Related to [PERFSCALE-2945](https://issues.redhat.com/browse/PERFSCALE-2945)
cc @jtaleric
=> PERFSCALE-2945: New metal-perfscale-cpt cloud profile

pkg/steps/output_image_tag.go, pkg/steps/output_image_tag_test.go
/cc @bear-redhat  @openshift/test-platform
=> include the PreserveOriginal import mode on output image tags

pkg/api/clusterbotjob.go, pkg/steps/input_image_tag.go, pkg/steps/input_image_tag_test.go, pkg/steps/release/snapshot.go
https://issues.redhat.com/browse/DPTP-3952
=> inputImageTagStep: reference images in QCI

pkg/api/constant.go, pkg/controller/test-images-distributor/test_images_distributor.go, pkg/steps/release/create_release.go, pkg/steps/release/import_release.go, pkg/steps/release/release_images.go, pkg/steps/release/snapshot.go
=> Share api.ReleaseConfigAnnotation among tools

pkg/steps/release/import_release.go, pkg/steps/utils/image.go, pkg/steps/utils/image_test.go
=> Reuse utils.ImportTagWithRetries in step/import_release

cmd/ci-operator-configresolver/main.go, cmd/ci-operator-configresolver/main_test.go
Expose some information (list of tag names and release-controller's config name at the moment) on app.ci.
https://issues.redhat.com/browse/DPTP-3969
=> configresolver: add an endpoint integratedStream

cmd/ci-operator-configresolver/main.go, cmd/ci-operator-configresolver/main_test.go
Reverts openshift/ci-tools#4093
/hold
Verifying ...
The fix is https://github.com/openshift/release/pull/51514
=> Revert "Revert "configresolver: add an endpoint integratedStream""

pkg/api/constant.go, pkg/steps/release/import_release.go, pkg/steps/utils/image.go, pkg/steps/utils/image_test.go
=> Do more retires on importing

cmd/ci-operator-configresolver/main.go, cmd/ci-operator-configresolver/main_test.go, cmd/ci-operator/main.go, pkg/api/configresolver/configresolver.go, pkg/defaults/defaults.go, pkg/defaults/defaults_test.go, pkg/registry/server/client.go, pkg/steps/release/create_release.go, pkg/steps/release/release_images.go, pkg/steps/release/snapshot.go
https://issues.redhat.com/browse/DPTP-3969
/hold
test with rehearsals
=> releaseSnapshotStep: no dependencies on isTags of the cluster cluster

cmd/ci-operator-configresolver/main.go, cmd/ci-operator-configresolver/main_test.go, pkg/api/configresolver/configresolver.go
/assign @deepsm007 
https://issues.redhat.com/browse/DPTP-3969
=> configresolver: cache integrated streams

pkg/steps/release/import_release.go
The replaced implementation uses different API from the one in `utils`.
But they have the same feature that is "wait until all tags are imported on an image stream or timeout".
=> Reuse utils.WaitForImportingISTag in import_release

pkg/api/domain.go, pkg/api/promotion.go, pkg/steps/input_image_tag.go
=> Document QCIAPPCIDomain

cmd/ci-images-mirror/main.go, pkg/controller/quay_io_ci_images_distributor/supplemental_images.go, pkg/controller/quay_io_ci_images_distributor/supplemental_images_test.go
https://issues.redhat.com/browse/DPTP-3992
=> ci-images-mirror: support ART images

pkg/controller/quay_io_ci_images_distributor/supplemental_images.go, pkg/controller/quay_io_ci_images_distributor/supplemental_images_test.go
The case with the name "source from tag and ignored source from image" is for https://github.com/openshift/release/pull/51899
=> Fix the ignored function

pkg/util/testgrid.go
Adds OpenStack TechPreview periodics added in https://github.com/openshift/release/pull/51880
=> Add OpenStack TechPreview Periodics to Sippy

pkg/prowgen/prowgen.go, pkg/prowgen/prowgen_test.go, pkg/prowgen/testdata/zz_fixture_TestGenerateJobs_multiarch_branch_filtered_with_variant__no_cluster_change.yaml
case found on https://github.com/openshift/release/pull/51838
=> exclude variant configuration on multi-arch cluster failover

pkg/jobrunaggregator/jobrunhistoricaldataanalyzer/analyzer.go
When the [scripting used in the automation](https://github.com/openshift/release/blob/ef1047161807a90062a6a596ae58b0de712c1027/ci-operator/jobs/infra-periodics.yaml#L2557-L2601) runs, we might get an error when fetching disruption data for alerts. Here's an example of a recently [failed run](https://prow.ci.openshift.org/view/gs/test-platform-results/logs/periodic-update-origin-disruption-alert-data/1788735954228350976) (which succeeded on a retry 2 days later):
```
Updating alerts data
Using target release: 4.17, previous release: 4.16
time="2024-05-10T01:03:24.825Z" level=fatal msg="Command failed" error="Failed while attempting to read Alert Historical Data"
```
If we every fail again, it would be nice to know what failed. This PR ensures that captured errors are "bubbled" up to the …
=> TRT-1613: Bubble up error for getting alert disruption data

cmd/ci-operator-configresolver/main.go, cmd/ci-operator-configresolver/main_test.go
https://issues.redhat.com/browse/DPTP-4005
=> Allow more early versions of streams in ocp

pkg/api/types.go
[KONFLUX-3169](https://issues.redhat.com//browse/KONFLUX-3169)
=> create aws-konflux-qe profile

pkg/jobrunaggregator/jobrunaggregatorlib/ci_data_client.go
Seeing failures like
```
error getting historical disruption data, skipping: googleapi: Error 400: Unrecognized name: StartTime at [6:5], invalidQuery 
```
=> trt-1627: fix up table references

cmd/ci-images-mirror/main.go
https://issues.redhat.com/browse/DPTP-3999
/hold
Will watch the rolling.
=> ci-images-mirror: disable quay_io_ci_images_distributor by default

cmd/pr-reminder/main.go, cmd/pr-reminder/main_test.go
While Prow does auto-request review from folks in OWNERS, it's common for these automatic review requests to go primarily to root OWNERS, leading to a situation where the original code in the pr-reminder would send a very long private message to one or two people who are already swamped and can't do much about it.
This commit adds new functionality that lets teams put a channel into their config where brand-new PRs that need eyeballs can be highlighted. Once someone is assigned to the PR, these will no longer be part of the "new" pool.
=> pr-reminder: allow updating a channel with brand-new PRs

pkg/api/domain.go, pkg/steps/input_image_tag_test.go
=> Use the qci-appci's domain

pkg/api/types.go, pkg/steps/pod.go, pkg/webreg/zz_generated.ci_operator_reference.go
/cc @openshift/test-platform @deepsm007 @danilo-gemoli 
=> ci-operator: support specifing the node architecture on specific tests

cmd/generate-registry-metadata/main_test.go, pkg/load/load_test.go, pkg/registry/resolver.go, pkg/registry/resolver_test.go, test/integration/ci-operator-configresolver/configs/release-4.2/openshift-installer-release-4.2.yaml, test/integration/ci-operator-configresolver/expected/openshift-installer-console-merged-release-4.2-injected.json, test/integration/ci-operator-configresolver/expected/openshift-installer-release-4.2-golang111.json, test/integration/ci-operator-configresolver/expected/openshift-installer-release-4.2-injected.json, test/integration/ci-operator-configresolver/expected/openshift-installer-release-4.2.json, test/integration/pj-rehearse/expected.yaml, test/multistage-registry/registry/ipi-observers/OWNERS, test/multistage-registry/registry/ipi-observers/ipi-observers-workflow.metadata.json, test/multistage-registry/registry/ipi-observers/ipi-observers-workflow.yaml
More info at https://issues.redhat.com/browse/DPTP-4040
=> Resolve observer pods from workflow

pkg/steps/utils/image.go, pkg/steps/utils/image_test.go
The bug fixed (introduced in https://github.com/openshift/ci-tools/pull/4056) in this PR will show up only when importing images failed.
See an [example](https://gcsweb-ci.apps.ci.l2s4.p1.openshiftapps.com/gcs/test-platform-results/pr-logs/pull/openshift_cluster-ingress-operator/1073/pull-ci-openshift-cluster-ingress-operator-release-4.13-images/1797768696622485504/artifacts/ci-operator.log) of ci-op's log.
```console
{"conditionMessage":"Internal error occurred: [quay.io/openshift/ci:ocp_4.13_apiserver-network-proxy: unknown: Tag ocp_4.13_apiserver-network-proxy was deleted or has expired. To pull, revive via time machine, quay-proxy.ci.openshift.org/openshift/ci:ocp_4.13_apiserver-network-proxy: unknown: Tag ocp_4.13_apiserver-network-proxy was deleted or has expired. To pull, revive …
```
=> ci-op: fix the getEvaluator function

cmd/cluster-init/update_bootstrap_secrets.go, test/integration/cluster-init/create/expected/core-services/ci-secret-bootstrap/_config.yaml, test/integration/cluster-init/update/expected/core-services/ci-secret-bootstrap/_config.yaml
/cc @openshift/test-platform @hongkailiu
=> DPTP-3742: Add pull secret for qci-pull-through-cache

pkg/api/types.go
=> Add new cluster profiles for Telco5G and PTP jobs

pkg/api/types.go
https://issues.redhat.com/browse/OCPQE-22600
=> OCPQE-22600: add new cluster profile azure-autorelease-qe

pkg/steps/ip_pool.go, pkg/steps/ip_pool_test.go
This is the 3rd attempt at solving the DataRace with varying success. The `fakecrtlruntimeclient` is not thread safe. Despite attempting to work around this, I cannot get consistent results. This defines a new `SecretClient` interface that is easy to mock.
=> `ci-operator`: add SecretClient interface in order to mitigate DataRace issues from using fakecrtlruntimeclient

cmd/qci-appci/main.go
=> qci-appci: improve logging for debugging

cmd/qci-appci/README.md
=> Update qci-appci's readme

images/job-run-aggregator/Dockerfile
Follow-up of https://github.com/openshift/release/pull/52994/files 
/cc @DennisPeriquet
=> Add missing prcreator to the job-run-aggregator

pkg/controller/prpqr_reconciler/prpqr_reconciler.go, pkg/controller/prpqr_reconciler/testdata/zz_fixture_prowjobs_TestReconcile_basic_aggregated_case.yaml, pkg/controller/prpqr_reconciler/testdata/zz_fixture_prowjobs_TestReconcile_basic_aggregated_case_with_scheduling.yaml, pkg/controller/prpqr_reconciler/testdata/zz_fixture_prowjobs_TestReconcile_basic_case.yaml, pkg/controller/prpqr_reconciler/testdata/zz_fixture_prowjobs_TestReconcile_basic_case_with_metal_override.yaml, pkg/controller/prpqr_reconciler/testdata/zz_fixture_prowjobs_TestReconcile_basic_case_with_scheduling.yaml, pkg/controller/prpqr_reconciler/testdata/zz_fixture_prowjobs_TestReconcile_basic_case_with_variant.yaml, pkg/controller/prpqr_reconciler/testdata/zz_fixture_prowjobs_TestReconcile_basic_case_with_vsphere_override.yaml, pkg/controller/prpqr_reconciler/testdata/zz_fixture_prowjobs_TestReconcile_basic_case_without_PR__testing_specified_base.yaml, pkg/controller/prpqr_reconciler/testdata/zz_fixture_prowjobs_TestReconcile_multiple_case__one_of_the_prowjobs_already_exists.yaml, pkg/controller/prpqr_reconciler/testdata/zz_fixture_prowjobs_TestReconcile_override_initial_and_base_payload_pullspecs.yaml, pkg/jobrunaggregator/jobrunaggregatoranalyzer/analyzer.go
Revert https://github.com/openshift/ci-tools/pull/4115
=> API-1783: Revert payload timeout increase

pkg/api/promotion.go, pkg/api/promotion_test.go, pkg/controller/quay_io_ci_images_distributor/quay_io_ci_images_distributor.go, pkg/steps/release/promote.go, pkg/steps/release/promote_test.go, pkg/steps/release/testdata/zz_fixture_TestGetPromotionPod_promotion_quay.yaml
https://issues.redhat.com/browse/DPTP-4041
/cc @openshift/test-platform @jupierce 
/hold
Will watch the rolling
=> Improve the tags for the pruner

cmd/ci-images-mirror/main.go
Those vars are used only in `quayiociimagesdistributor`.
This PR moved stanza of initializing them only when the controller is enabled.
=> ci-images-mirror: create agents when needed

cmd/ci-images-mirror/main.go
=> ci-images-mirror: reload config file

pkg/api/types.go
Required for https://issues.redhat.com/browse/SDE-3465
=> Add aws and gcp cluster profiles for SD CICD's Managed OpenShift

cmd/helpdesk-faq/main.go, cmd/slack-bot/main.go, hack/local-slack-bot.sh, pkg/helpdesk-faq/client.go, pkg/helpdesk-faq/types.go, pkg/helpdesk-faq/types_test.go, pkg/slack/events/helpdesk/helpdesk-faq.go, pkg/slack/events/helpdesk/helpdesk-faq_test.go, pkg/slack/events/router/router.go
Link back to the original thread, this will be added to the display so users can find more info.
/hold Builds on https://github.com/openshift/ci-tools/pull/4180, merge this after
=> `helpdesk-faq`: add link to thread

pkg/api/types.go
=> Remove aws-centos-40 cluster profile

pkg/api/types.go
Related release repo PR: https://github.com/openshift/release/pull/53567
=> Remove gcp-ha, gcp-crio, gcp-logging

pkg/slack/events/helpdesk/helpdesk-faq.go, pkg/slack/events/helpdesk/helpdesk-faq_test.go
Bonus: the tests found a very minor bug, which I have fixed :)
=> `helpdesk-faq`: create tests for slack handler

hack/cloudfront/lambda_function.py
=> DPTP-4073: Updating for build09/build10 cloudfront distribution map

pkg/defaults/defaults.go, pkg/defaults/defaults_test.go
Follow up https://prow.ci.openshift.org/view/gs/test-platform-results/pr-logs/pull/openshift_ci-tools/4192/pull-ci-openshift-ci-tools-master-e2e/1805584236464312320
```
WARN[2024-06-25T12:51:12Z] Waiting for imagestreamtag ci/ci-tools-build-root:1.22 failed  error=timed out waiting for the condition
INFO[2024-06-25T12:51:12Z] Using namespace https://console-openshift-console.apps.build04.34d2.p2.openshiftapps.com/k8s/cluster/projects/ci-op-2xf4zmz9 
INFO[2024-06-25T12:51:12Z] Running [input:root], src, test-bin, e2e     
INFO[2024-06-25T12:51:12Z] Tagging ci/ci-tools-build-root:1.22 into pipeline:root. 
```
The warning log came from the following function 
https://github.com/openshift/ci-tools/blob/b704e3b0cee243a89447683d4ca7001f3c9a7510/pkg/defaults/defaults.go#L1100-L1131
As shown the …
=> Disable ensureImageStreamTag() on the root tag

pkg/api/types.go
https://github.com/openshift/release/pull/53855
=> Add new profile: equinix-ocp-hcp

hack/cloudfront/lambda_function.py
Follow-up of https://issues.redhat.com/browse/DPTP-4073 
/hold while testing it
=> Modify lambda_function to support multiple regions

hack/cloudfront/lambda_r2_redirect_blobs.py
=> Build clusters image registry redirect to R2

images/autotestgridgenerator/Dockerfile, images/backport-verifier/Dockerfile, images/blocking-issue-creator/Dockerfile, images/bugzilla-backporter/Dockerfile, images/ci-operator-checkconfig/Dockerfile, images/ci-operator-configresolver/Dockerfile, images/ci-operator-prowgen/Dockerfile, images/config-brancher/Dockerfile, images/config-change-trigger/Dockerfile, images/config-shard-validator/Dockerfile, images/determinize-ci-operator/Dockerfile, images/determinize-peribolos/Dockerfile, images/determinize-prow-config/Dockerfile, images/dptp-controller-manager/Dockerfile, images/pod-scaler/Dockerfile, images/repo-brancher/Dockerfile, images/slack-bot/Dockerfile, images/sprint-automation/Dockerfile, images/testgrid-config-generator/Dockerfile
These don't really need to have a `maintainer` listed in the image
=> remove Alvaro and Steve from ownership of tools

pkg/api/types.go
We are creating two new CI zones and therefore need two new cluster types.
=> PowerVS: Add two new cluster types

pkg/api/types.go
Adding the `azure-perfscale` cluster profile
=> Adding new profile: azure-perfscale

cmd/cluster-init/update_bootstrap_secrets.go, test/integration/cluster-init/create/expected/core-services/ci-secret-bootstrap/_config.yaml, test/integration/cluster-init/update/expected/core-services/ci-secret-bootstrap/_config.yaml
=> DPTP-3742: Update the registry_url

cmd/ci-secret-bootstrap/main.go, cmd/ci-secret-bootstrap/main_test.go, pkg/api/domain.go, pkg/api/types.go
=> DPTP-4046: Allow more registry domains for OSD clusters

pkg/jobrunaggregator/jobrunaggregatorlib/ci_data_client.go
JobRuns table has been removed, need to fix the reference to it.
=> NO-JIRA: Fix JobRuns reference

cmd/ci-secret-bootstrap/main.go, cmd/ci-secret-bootstrap/main_test.go
`ci-secret-bootstrap` fetches the secrets from the Vault before syncing them on a cluster.
Prior to this changeset, the `ci-secret-bootstrap` secrets fetching procedure was done at best effort, and it would potentially lead to data inconsistency/corruption.
What follows is a real use case we faced and that caused a serious outage on our CI (kind of, I'll make it up a bit for the sake of the explanation):
- we want to synchronize a secret in accordance with the following specification:
```yaml
secret_configs:
- from:
sa.prow-controller-manager.app.ci.config:
field: sa.prow-controller-manager.app.ci.config
item: build_farm
sa.prow-controller-manager.app.ci.token.txt:
field: sa.prow-controller-manager.app.ci.token.txt
item: build_farm
sa.prow-controller-manager.build01.config:
field: …
```
=> ci-secret-bootstrap: skip secret sync on error

hack/install.sh
We have updated the import paths of Prow in https://github.com/openshift/ci-tools/pull/4203 but I forgot to do the same on this script.
/cc @smg247
=> fix: update version import path

pkg/pod-scaler/v2/types.go, pkg/pod-scaler/v2/types_test.go
Using the newly existing `Added` field in the pod-scaler data, we can now prune data that is older than 90 days. This will not go into effect until around October 9th 2024, as there will not be any `v2` data from older than July 9th. The 90 days figure is just a guess at an amount of data that will be significant for the histograms, but not require huge amounts of memory to process. This time period can be adjusted if needed.
For: https://issues.redhat.com/browse/DPTP-4069
=> `pod-scaler producer`: prune data older than 90 days

pkg/jobrunaggregator/jobrunaggregatorlib/ci_data_client.go, pkg/jobrunaggregator/jobrunaggregatorlib/util.go
Reverts openshift/ci-tools#4254
=> Revert "Revert "TRT-1706: Use big query labels with aggregator""

pkg/jobrunaggregator/jobrunaggregatoranalyzer/aggregation-testrun-summary.gohtml, pkg/jobrunaggregator/jobrunaggregatoranalyzer/analyzer.go, pkg/jobrunaggregator/jobrunaggregatoranalyzer/spyglass_summary.go, pkg/jobrunaggregator/jobrunaggregatoranalyzer/types.go
changed to using go template for the html
updated ui to help with glancable information
Ex:
=> NO-JIRA: feat: update html for aggregated results

OWNERS
Added hector-vido to OWNERS file.
=> Added hector-vido

cmd/cluster-init/update_bootstrap_secrets.go, test/integration/cluster-init/create/expected/core-services/ci-secret-bootstrap/_config.yaml, test/integration/cluster-init/update/expected/core-services/ci-secret-bootstrap/_config.yaml
/cc @jupierce @openshift/test-platform 
https://github.com/openshift/release/pull/55715
=> Update pull secret for quay.io/openshift

cmd/ci-secret-bootstrap/main_test.go, cmd/cluster-init/update_bootstrap_secrets.go, pkg/api/domain.go, test/integration/cluster-init/create/expected/core-services/ci-secret-bootstrap/_config.yaml, test/integration/cluster-init/update/expected/core-services/ci-secret-bootstrap/_config.yaml
=> Fix for registry url auth string match

pkg/api/ocpbuilddata/types.go
Reverts openshift/ci-tools#4268
=> Revert "Fix validation for ocp-build-data from.builder.image"

pkg/api/ocpbuilddata/types.go
`image configs from ocp-build-data: error validating images/okd-only-upi-installer.yml: [.from.5 failed validation: both stream and member were unset, .from.6 failed validation: both stream and member were unset, .from.7 failed validation: both stream and member were unset, .from.8 failed validation: both stream and member were unset]" 
`
=> Fix validation for ocp-build-data

cmd/cluster-init/cmd/onboard/update_secret_generator.go, cmd/cluster-init/cmd/onboard/update_secret_generator_test.go, test/integration/cluster-init/create/expected/core-services/ci-secret-generator/_config.yaml, test/integration/cluster-init/create/input/core-services/ci-secret-generator/_config.yaml, test/integration/cluster-init/update/expected/core-services/ci-secret-generator/_config.yaml, test/integration/cluster-init/update/input/core-services/ci-secret-generator/_config.yaml
Fix the tool such that it will be able to handle the following case: https://github.com/openshift/release/pull/55874
=> cluster-init: handle SA wildcard on secret generator update

pkg/steps/multi_stage/gen.go, pkg/steps/multi_stage/gen_test.go, pkg/steps/multi_stage/testdata/zz_fixture_TestGeneratePods.yaml
=> DPTP-4138: Add additional tests for node_Architecture

pkg/api/graph.go
follow-up of https://github.com/openshift/ci-tools/pull/4299
/cc @deepsm007 
=> ensure resolving multi-arch builds for all children in the step graph

pkg/steps/bundle_source.go
https://issues.redhat.com/browse/DPTP-4143
Bundle images by design are not multi-arch. In the meantime, there is currently a supported way to allow users to enable multi-arch builds for bundles. So ci-operator was building the image with a manifest-list for amd64 only. That caused a problem using the image on arm nodes since the desired manifest from the list was missing. Also in the meantime, the bundle doesn't care about any architecture... 
This change will use the old building way. Ci-operator will just create a single build forced on amd64 node for consistency and the output image won't hold a manifest list.
/cc @deepsm007 @openshift/test-platform @aleskandro 
=> ci-operator: treat bundle images as non multi-arch without manifest list

pkg/sanitizer/determinize.go
Use dispatcher algo only if needed/cluster blocked
=> Fix bug in sanitizer

cmd/ci-operator/main.go, pkg/defaults/defaults.go, pkg/defaults/defaults_test.go
Reverts openshift/ci-tools#4316
=> Revert "`ci-operator`: treat building the primary ref differently from the extra_refs"

pkg/api/types.go
https://github.com/openshift/release/pull/56821
https://issues.redhat.com/browse/OCPQE-25726
=> Add new profile: aws-kubevirt

cmd/payload-testing-prow-plugin/main.go
I previously implemented https://github.com/openshift/ci-tools/pull/4325, which didn't solve the issue of constantly reloading configs. I noticed that the `dptp-controller-manager` [uses](https://github.com/openshift/ci-tools/pull/2805) a symlink watcher. It seems reasonable that the absence of this here is causing this issue.
For: https://issues.redhat.com/browse/DPTP-4172
=> `payload-testing-prow-plugin`: introduce symlink watcher 

go.mod, go.sum, vendor/modules.txt, vendor/sigs.k8s.io/prow/pkg/github/client.go, vendor/sigs.k8s.io/prow/pkg/plugins/config.go
Needed to grab: https://github.com/kubernetes-sigs/prow/pull/275
=> bump `prow` dependency

cmd/ci-operator/main.go
OSD clusters are on OpenShift SDN which does not have the CRD
=> Fix issue DPTP-4032 Warn in all cases

cmd/ci-operator/main.go
Like https://github.com/openshift/ci-tools/pull/4342 but with a stronger assertion `errors.Is(err, &meta.NoKindMatchError{})`
=> ci-operator: warn when CRD `egressfirewalls.k8s.ovn.org` is not available

cmd/registry-replacer/main_test.go
Missed on a big vendor refactoring.
=> fix the unit tests of the registry replacer tool

go.mod, go.sum, vendor/modules.txt, vendor/sigs.k8s.io/prow/pkg/config/prow-config-documented.yaml, vendor/sigs.k8s.io/prow/pkg/config/tide.go, vendor/sigs.k8s.io/prow/pkg/ghcache/ghcache.go, vendor/sigs.k8s.io/prow/pkg/github/client.go, vendor/sigs.k8s.io/prow/pkg/github/ghmetrics/ghpath.go, vendor/sigs.k8s.io/prow/pkg/github/report/report.go, vendor/sigs.k8s.io/prow/pkg/plugins/override/override.go, vendor/sigs.k8s.io/prow/pkg/simplifypath/simplify.go, vendor/sigs.k8s.io/prow/pkg/tide/github.go, vendor/sigs.k8s.io/prow/pkg/tide/tide.go
We need the new `GitHub` Client for multi-pr presubmit testing
=> update prow dependency

pkg/api/types.go, pkg/prowgen/prowgen.go, pkg/prowgen/testdata/zz_fixture_TestGenerateJobs_multiarch_branch_filtered__cluster_change.yaml, pkg/prowgen/testdata/zz_fixture_TestGenerateJobs_multiarch_postsubmit_images__default_arch_and_others.yaml
Moving the multiarch promotion to different cluster for failover
=> Move the prowgen promotion to build11

pkg/api/types.go, pkg/prowgen/prowgen.go, pkg/prowgen/testdata/zz_fixture_TestGenerateJobs_multiarch_branch_filtered__cluster_change.yaml, pkg/prowgen/testdata/zz_fixture_TestGenerateJobs_multiarch_postsubmit_images__default_arch_and_others.yaml
Reverts openshift/ci-tools#4362
=> Revert "Move the prowgen promotion to build11"

cmd/multi-pr-prow-plugin/main.go, cmd/multi-pr-prow-plugin/report.go, cmd/multi-pr-prow-plugin/report_test.go, cmd/multi-pr-prow-plugin/server.go, cmd/multi-pr-prow-plugin/server_test.go, cmd/multi-pr-prow-plugin/testdata/zz_fixture_TestGenerateProwJob_additional_PR_from_the_same_repo.yaml, cmd/multi-pr-prow-plugin/testdata/zz_fixture_TestGenerateProwJob_multiple_additional_PRs.yaml, cmd/multi-pr-prow-plugin/testdata/zz_fixture_TestHandle_trigger_a_single_multi_pr_job_run_with_additional_PR_from_a_different_repo.yaml, cmd/multi-pr-prow-plugin/testdata/zz_fixture_TestHandle_trigger_a_single_multi_pr_job_run_with_additional_PR_from_the_same_repo.yaml, cmd/multi-pr-prow-plugin/testdata/zz_fixture_TestHandle_trigger_multiple_multi_pr_job_runs_with_diverse_additional_PRs.yaml, images/multi-pr-prow-plugin/Dockerfile, pkg/api/types.go, pkg/controller/prpqr_reconciler/prpqr_reconciler.go
The initial MVP for multi-pr presubmit testing. There are a couple of TODOS left in here intentionally, and a couple of open questions that I have that will only be answered once I start trying this out on real scenarios. Expect a few follow-ups here.
For: https://issues.redhat.com/browse/DPTP-4148
=> `multi-pr-prow-plugin`: Create a prow plugin to handle multi-pr presubmit testing

pkg/api/types.go
This PR adds OVN PerfScale AWS Cluster Profile to DPTP-Tooling
=> [PERFSCALE-3524] Add OVN PerfScale AWS Cluster Profile

cmd/multi-pr-prow-plugin/server.go, pkg/helpdesk-faq/types.go, pkg/steps/source.go
The TODOs have already been taken care of, and the description was just missed in the original PR
=> clean up a couple of TODOs that are no longer relevant, and add plugin description

pkg/api/types.go
Want to add profile for chaos specific gcp configuration
CC: @chaitanyaenr
=> Adding gcp chaos

cmd/multi-pr-prow-plugin/server.go, cmd/multi-pr-prow-plugin/server_test.go
The copy/paste results in the additional PRs having a fully resolved github link rather than the expected formatting. Currently, the regex doesn't pick this up at all, and the plugin silently ignores the command. We could just throw an error to warn people, but its even better to adapt the format instead.
=> `multi-pr`: handle the common case that the user has copy/pasted the command 

pkg/steps/release/create_release.go
Related to the `unexpected EOF`  errors  
https://redhat-internal.slack.com/archives/CBN38N3MW/p1730198582759599
=> Add retry during extraction

pkg/api/types.go
=> SUSTAINING-328: Add new profile for aws-sustaining-autorelease-412

cmd/branchingconfigmanagers/frequency-reducer/main.go, pkg/api/ocplifecycle/ocplifecycle.go
UTs are not needed as rules will be adjusted quite frequently if needed and also exec on repo can be treated as test.
=> tiny post-GA tool to reduce exec frequency of periodics

pkg/jobrunaggregator/jobrunaggregatoranalyzer/analyzer.go
```
job-run-aggregator analyze-job-runs \
--job periodic-ci-openshift-release-master-ci-4.18-e2e-aws-upgrade-ovn-single-node \
--payload-tag 4.18.0-0.nightly-2024-10-07-090036 \
--google-service-account-credential-file openshift-sippy-prd.creds.json \
--job-start-time 2024-10-07T09:06:08Z --timeout 60m
FATA Command failed  error="None of the jobs aggregated ran an expected test suite.  This usually means they failed very early."
```
=> TRT-1861: fail aggregation when all job runs died early

cmd/ci-operator/main.go, cmd/ci-operator/main_test.go
The first part of allowing rehearsals to retrieve their ci-operator config spec from a GCS bucket is to amend ci-operator to get it from GCS when the proper env var is found.
For: https://issues.redhat.com/browse/DPTP-4241
=> `ci-operator`: allow for the possibility of fetching the config from the `CONFIG_SPEC_GCS_URL`

pkg/controller/test-images-distributor/test_images_distributor.go, pkg/controller/test-images-distributor/test_images_distributor_test.go
/cc @deepsm007 @openshift/test-platform 
needed for https://github.com/openshift/ci-tools/pull/4404
=> update the ci-operator rolebindings to allow pushing images

pkg/api/types.go, pkg/cmd/release/profile.go
For https://issues.redhat.com/browse/DPTP-4113
Merge after https://github.com/openshift/ci-tools/pull/4391
=> Remove ConfigMap() func

OWNERS
Add @pruan-rht and @liangxia to OWNERS
=> owners: add pruan-rht and liangxia

pkg/api/types.go
=> add nutanix flow profile

cmd/prow-job-dispatcher/main.go, cmd/prow-job-dispatcher/main_test.go, cmd/prow-job-dispatcher/prometheus_volumes.go, cmd/prow-job-dispatcher/prometheus_volumes_test.go, cmd/sanitize-prow-jobs/main.go, pkg/dispatcher/config.go, pkg/dispatcher/config_test.go, pkg/dispatcher/helpers.go, pkg/dispatcher/helpers_test.go, pkg/sanitizer/determinize.go, pkg/sanitizer/determinize_test.go
prowgen is coming soon as separate PR
=> Capabilities in the dispatcher algorithm

cmd/check-gh-automation/main.go, cmd/check-gh-automation/main_test.go
Reverts openshift/ci-tools#4421
=> Revert "[DPTP-3546] Verify if the repo is public for branch protection"

cmd/autoconfigbrancher/main.go
Ref: https://redhat-internal.slack.com/archives/CHY2E1BL4/p1732637099259749
Ref: https://github.com/openshift-eng/ocp-build-data/pull/5618
=> Remove ensure-correct-promotion-dockerfile

pkg/controller/prpqr_reconciler/prpqr_reconciler.go, pkg/controller/prpqr_reconciler/testdata/zz_fixture_prowjobs_TestReconcile_basic_aggregated_case.yaml, pkg/controller/prpqr_reconciler/testdata/zz_fixture_prowjobs_TestReconcile_basic_aggregated_case_with_scheduling.yaml, pkg/controller/prpqr_reconciler/testdata/zz_fixture_prowjobs_TestReconcile_basic_case.yaml, pkg/controller/prpqr_reconciler/testdata/zz_fixture_prowjobs_TestReconcile_basic_case_with_cluster_override.yaml, pkg/controller/prpqr_reconciler/testdata/zz_fixture_prowjobs_TestReconcile_basic_case_with_metal_override.yaml, pkg/controller/prpqr_reconciler/testdata/zz_fixture_prowjobs_TestReconcile_basic_case_with_scheduling.yaml, pkg/controller/prpqr_reconciler/testdata/zz_fixture_prowjobs_TestReconcile_basic_case_with_variant.yaml, pkg/controller/prpqr_reconciler/testdata/zz_fixture_prowjobs_TestReconcile_basic_case_with_vsphere_override.yaml, pkg/controller/prpqr_reconciler/testdata/zz_fixture_prowjobs_TestReconcile_basic_case_without_PR__testing_specified_base.yaml, pkg/controller/prpqr_reconciler/testdata/zz_fixture_prowjobs_TestReconcile_multiple_case__one_of_the_prowjobs_already_exists.yaml, pkg/controller/prpqr_reconciler/testdata/zz_fixture_prowjobs_TestReconcile_override_initial_and_base_payload_pullspecs.yaml, pkg/controller/prpqr_reconciler/testdata/zz_fixture_prowjobs_TestReconcile_url_not_found_in_created_job.yaml, pkg/jobrunaggregator/jobrunaggregatoranalyzer/analyzer.go
=> CNTRLPLANE-1: Increase timeouts for payload jobs to land k8s 1.32

cmd/job-trigger-controller-manager/main.go, pkg/controller/prpqr_reconciler/prpqr_reconciler.go, pkg/controller/prpqr_reconciler/prpqr_reconciler_test.go, pkg/controller/prpqr_reconciler/testdata/zz_fixture_prowjobs_TestReconcile_basic_aggregated_case.yaml, pkg/controller/prpqr_reconciler/testdata/zz_fixture_prowjobs_TestReconcile_basic_aggregated_case_with_scheduling.yaml, pkg/jobrunaggregator/jobrunaggregatoranalyzer/analyzer.go
Implement additional parameters for aggregator job timeout which is required for k8 testing
/cc @smg247
=> Implement additional controller parameters

cmd/check-gh-automation/main.go, cmd/check-gh-automation/main_test.go
This modifications verify if branch protection is enable for private repositories using a free plan, if this is the case, the verification should return an error.
=> [DPTP-4239] Verifying branch protection on public repos or paid plans

pkg/api/types.go
https://issues.redhat.com/browse/OCPQE-27657
=> OCPQE-27657: add new cluster profile azurestack-dev

cmd/pj-rehearse/server.go
We recently hit an issue where the rebase process failed on certain PRs. The upstream rebase logic only emits an `info` log when this happens, but the logic here wasn't outputting an error. It is unclear why that is happening, but we can add some better logging to help us be more aware next time. If this happens again, we might have a chance to see why we aren't outputting an error thanks to this logging.
=> `pj-rehearse`: add better logging when rebase is retried

cmd/config-brancher/main.go, cmd/config-brancher/main_test.go
This should fix the issue with variants of Openshift during branching and avoid PRs like this: https://github.com/openshift/release/pull/56051
Resolves: [DPTP-4150](https://issues.redhat.com/browse/DPTP-4150)
=> config-brancher: respect prefix when bumping to future-release

pkg/clusterinit/onboard/certmanager/certmanager.go
This code fix a problem that return the following message:
```
```
The local `err` variable was replacing the original on the function signature.
=> Added the error on every return

pkg/steps/source.go
Reverts openshift/ci-tools#4484
=> Revert "remove PushImageToRegistryFailed infra failure reason for retrying the builds"

cmd/ci-scheduling-webhook/main.go, cmd/ci-scheduling-webhook/mutation.go
https://github.com/openshift/release/pull/61165
=> Fix issue DPTP-4311 Add toleration to large Build pods

pkg/clusterinit/onboard/certmanager/certmanager.go, pkg/clusterinit/onboard/certmanager/certmanager_test.go, pkg/kubernetes/portforward/portforward.go, pkg/kubernetes/portforward/portforward_test.go
Fix a race condition between the portforwarder and its caller, [here](https://prow.ci.openshift.org/view/gs/test-platform-results/pr-logs/pull/openshift_ci-tools/4495/pull-ci-openshift-ci-tools-master-unit/1890145613144657920) is a failed run.
In the previous version, `Run` would have returned an error channel on which the caller would have listened for any error:
```golang
err := <-Run(ctx, portforward.SPDYPortForwarder, opts)
```
but there was not guarantee about the caller receiving the error at the right time. Here an example on how the execution would unfold in case of a race condition:
1. The caller is supposed to call `Run` (into its own goroutine `goroutine_a`):
```golang
Run(ctx, portforward.SPDYPortForwarder, opts)
```
2. The port forwarder raise an error and closes the …
=> Fix kube port forwarder race condition

cmd/ci-operator/main.go, cmd/ci-operator/main_test.go
Currently, when we use the Gangway API with the following structure:
```
"pod_spec_options": {
"envs": {
"xxxx": "xxxx"
}
}
```
The variables are not being received in the step. However, in some cases, such as with the Hypershift team, this is required. For example, when performing multi-version testing, we need to change the MCE version via the Gangway API. Therefore, I'm submitting this PR to support passing pod_spec_options to the step.
=> Pass pod_spec_options to the step.

pkg/registry/resolver.go, pkg/validation/test.go
https://issues.redhat.com/browse/DPTP-4345
=> fix node_architecture configuration while loading the step registry

cmd/pj-rehearse/server.go
This will be useful when the pull request created or push event is dropped. It happens from time to time, and currently the only recourse is to push an empty commit.
=> `pj-rehearse`: add list command

pkg/steps/pod.go, pkg/steps/release/import_release.go, pkg/steps/release/promote.go
follow-up of https://github.com/openshift/ci-tools/pull/4527
/cc @openshift/test-platform @deepsm007
=> allow gathering the logs from the promotion pods

pkg/api/types.go
-    Add new profile for gcp-sustaining-autorelease-412
=> SUSTAINING-607: Add GCP sustaining cluster profile

pkg/clusterinit/onboard/cischedulingwebhook/aws.go, test/integration/cluster-init/update-build99/expected/clusters/build-clusters/build99/ci-scheduling-webhook/ci-builds-worker-aarch64.yaml, test/integration/cluster-init/update-build99/expected/clusters/build-clusters/build99/ci-scheduling-webhook/ci-builds-worker-amd64.yaml
[Thread](https://redhat-internal.slack.com/archives/CBN38N3MW/p1742955551719369?thread_ts=1742492310.556259&cid=CBN38N3MW)
=> Update builds machineset volume

cmd/pipeline-controller/main.go
=> More logs to Pipelines ctrl

pkg/api/types.go, pkg/prowgen/prowgen.go, pkg/prowgen/prowgen_test.go, pkg/prowgen/testdata/zz_fixture_TestGenerateJobs_promotion_postsubmit_and_periodic_.yaml, pkg/webreg/zz_generated.ci_operator_reference.go
forum followup, not to give away gangway tokens for some hacky solution which will run postsubmits periodically in external loops
=> Optional promotion periodic

pkg/registry/resolver.go
/cc @openshift/test-platform @deepsm007
=> propagate the node architecture config to the multi arch step on resolution

pkg/steps/multi_stage/multi_stage.go
=> ensure correct implementation of multi-stage test step as a multi-arch step node

pkg/api/types.go
Add a new AWS account for OEX team which owns rosacli and terraform (RHCS)
=> Add a new AWS account for OEX team

pkg/api/types.go
with ref to this : https://docs.ci.openshift.org/docs/how-tos/adding-a-cluster-profile/
=> Add AWS cluster profile for MCO

cmd/ci-operator/main.go, cmd/ci-operator/main_test.go, pkg/api/job_spec.go, pkg/defaults/defaults.go, pkg/defaults/defaults_test.go, pkg/metrics/builds.go, pkg/metrics/insights.go, pkg/metrics/metrics.go, pkg/steps/git_source.go, pkg/steps/index_generator.go, pkg/steps/pipeline_image_cache.go, pkg/steps/project_image.go, pkg/steps/rpm_injection.go, pkg/steps/source.go
https://issues.redhat.com/browse/DPTP-4433
This is just the initialization of the metrics controller. Metrics for builds and some internal insights have been included.
=> Initial implementation of the metrics controller in ci-operator

cmd/repo-brancher/main.go, cmd/repo-brancher/main_test.go
=> Adding support for ignore flag for fast-forward

pkg/api/types.go
Add a new cluster profile for confidential cluster.
=> Add a new cluster profile

cmd/github-ldap-user-group-creator/main.go, cmd/github-ldap-user-group-creator/main_test.go
`periodic-github-ldap-user-group-creator` crashes gloriously when a client for a cluster isn't available. This PR fix the issue.
A snippet of the stack trace:
```
E0718 02:05:45.980919      14 panic.go:262] "Observed a panic" panic="runtime error: invalid memory address or nil pointer dereference" panicGoValue="\"invalid memory address or nil pointer dereference\"" stacktrace=<
goroutine 205124 [running]:
...
main.upsertGroup({0x3306390, 0xc001286fa0}, {0x0, 0x0}, 0xc001efcb40)
/go/src/github.com/openshift/ci-tools/cmd/github-ldap-user-group-creator/main.go:594 +0x91
main.upsertGroupWithRetry.func1()
...
```
=> ldap-user-group-creator: fail gracefully if a cluster client is nil

pkg/api/types.go
A new AWS Cluster Profile `aws-lp-chaos` is created for Layered Product Chaos Test.
=> Add new AWS Cluster Profile.

cmd/ci-scheduling-webhook/mutation.go
TRT is working on understanding network outages detected during e2e tests. To facilitate this, we want to do network capture when the condition is detected.
It is intended to be paired with: https://github.com/openshift/release/pull/68174
=> Allow special pods to get NET_ caps for diagnostic purposes

pkg/metrics/builds.go, pkg/metrics/builds_test.go, pkg/metrics/insights.go, pkg/metrics/insights_test.go, pkg/metrics/leases.go, pkg/metrics/metrics.go, pkg/metrics/nodes.go, pkg/metrics/plugins.go, pkg/metrics/pods.go, pkg/metrics/pods_test.go, pkg/util/pods.go
=> Introduce the pod metrics agent plugin, improve the metrics agent debug logs

pkg/steps/source.go
=> [ci-operator] record a pod lifecycle event on build pods

pkg/metrics/metrics.go, pkg/metrics/pods.go, pkg/metrics/pods_test.go, pkg/steps/source.go, pkg/util/pods.go
=> [ci-operator] improve the pod metric events

images/tide-config-manager/Dockerfile
Follow this up https://github.com/openshift/release/pull/68752
/cc @psalajova
=> tide-config-manager: Install diffutils

cmd/ci-operator/main.go, pkg/metrics/insights.go, pkg/metrics/metrics.go
Add more insights metrics. Include also information about the cluster, by getting the clusterID from the cluster.
=> [ci-operator] improve the insights events in the metrics agent, expand the metrics data

pkg/api/types.go
Add new cluster profile "aws-confidential-qe".
=> Add cluster profile "aws-confidential-qe"

cmd/retester/main.go
/cc @openshift/test-platform @danilo-gemoli
=> [retester]: ensure the preloading of the aws configuration on the controller initialization

pkg/defaults/defaults.go, pkg/validation/release.go, pkg/validation/release_test.go
Follow up of: https://github.com/openshift/ci-tools/pull/4700
=> ci-operator: referencePolicy = Source fix

pkg/jobrunaggregator/jobtableprimer/create_jobs.go
[slack ref](https://redhat-internal.slack.com/archives/C02K89U2EV8/p1758552220375049?thread_ts=1758542901.878509&cid=C02K89U2EV8)
=> fix errors in daily job-aggregation table updater

pkg/registry/server/server.go
https://issues.redhat.com/browse/DPTP-4551
https://redhat-internal.slack.com/archives/CBN38N3MW/p1758225583360539
=> Fix cannonical_go_repository error when merging 2 repos

cmd/ci-scheduling-webhook/mutation.go
This modifies the generic interfaces that are in use by defined kubernetes ones.
=> Modified generic interfaces to k8s.io/api/core/v1
