- cmd/ipi-deprovision/ipi-deprovision.sh
- images/ipi-deprovision/Dockerfile
less is required by aws cli
https://unix.stackexchange.com/questions/295340/how-to-install-less-on-oracle-linux-server
> Install less in ipi-deprivision image

- pkg/rehearse/jobs.go
- pkg/rehearse/jobs_test.go
- test/pj-rehearse-integration/expected.yaml
This reverts commit 5f6bb3d52fa434a35f7564fc234e6a70dc6f24dd, reversing
changes made to 150c8d957a036b8001457d973805826af356f5cc.
> Revert "Merge pull request #41 from droslean/git-ref-remove"

- pkg/steps/source.go
Recent prow changes that make use of the `workdir: true` in the refs, change the idea of how we treat the refs in `ci-operator`. 
Now we are just assigning the `PathAlias` to the `refs` but that breaks a different logic that we are now able to use in the `pj-rehearse` tool.
Rehearsals have a ref that point to the `release` repo PR and `extra_refs` with `workdir: true` that will be the main repo to be cloned and run the tests against that. 
The problem was that ci-operator is assigning the `PathAlias` to the `refs` which is, in this case, the `release` repo instead. 
To solve this issue, this PR is changing the logic with injecting the `PathAlias` to the ref that has a `workdir: true` instead. If there isn't any, then assign it to the `refs` as usual.
> ci-operator: inject path alias to refs

- pkg/rehearse/jobs.go
- pkg/rehearse/jobs_test.go
- test/pj-rehearse-integration/expected.yaml
Reverts openshift/ci-tools#47
This can finally lands after #48 merged.
> Revert "Revert "Merge pull request #41 from droslean/git-ref-remove""

- pkg/api/job_spec.go
- pkg/steps/pod.go
- pkg/steps/pod_test.go
https://jira.coreos.com/browse/DPTP-473
The list of env. var. names are defined:
https://github.com/openshift/test-infra/blob/master/prow/jobs.md#job-environment-variables
> Populate env. var. in test pods

- go.mod
- go.sum
- vendor/k8s.io/test-infra/prow/plugins/heart/heart.go
- vendor/k8s.io/test-infra/prow/pod-utils/decorate/podspec.go
- vendor/modules.txt
> Update test-infra vendor

- cmd/ci-operator-prowgen/main_test.go
/assign @droslean @petr-muller
> Add unit tests for generating the job base

- pkg/steps/source.go
- pkg/steps/source_test.go
/assign @droslean @petr-muller
> Add a test for source build creation

- pkg/steps/clusterinstall/template.go
/assign @wking 
:man_facepalming:
> Add AWS quota leasing to internal template

- pkg/jobconfig/files.go
> Remove unused function

- pkg/steps/clusterinstall/template.go
> Update inline template to mirror those in openshift/release

- pkg/steps/template.go
> add branch label in template pods

- pkg/steps/source.go
> Adding checks for additional possible infra failures

- pkg/steps/pod_test.go
- pkg/steps/source.go
- pkg/steps/source_test.go
> Inject org/repo/branch labels to pods created by ci-operator

- pkg/steps/multi_stage.go
I was over-thinking this, this implementation with (irrelevant) inefficiencies
is good enough and simple.  `dumpObject` is unnecessarily generic to cover
future uses, and could potentially be used by other parts of the code base.
> ci-operator multi-stage: dry-run mode

- pkg/steps/clusterinstall/template.go
This updates the template to match openshift/release@a6eb34a.
This is mainly being done so that the openshift-install invoker is
properly set.
> clusterinstall: sync upstream template

- pkg/api/config.go
- vendor/modules.txt
See #120 for more details.
Closes #120 
> pkg/api/config.go: use apimachinery's DNS 1123 subdomain check for Secret names

- cmd/autobumper/main.go
- images/autobumper/Dockerfile
- vendor/k8s.io/test-infra/experiment/autobumper/bumper/BUILD.bazel
- vendor/k8s.io/test-infra/experiment/autobumper/bumper/bumper.go
- vendor/k8s.io/test-infra/experiment/image-bumper/bumper/BUILD.bazel
- vendor/k8s.io/test-infra/experiment/image-bumper/bumper/bumper.go
- vendor/k8s.io/test-infra/robots/pr-creator/updater/BUILD.bazel
- vendor/k8s.io/test-infra/robots/pr-creator/updater/updater.go
- vendor/modules.txt
> Implement autobumper for release repo

- cmd/autobumper/main.go
> Use openshift-bot in autobumper

- cmd/autobumper/main.go
> Inject auth info into git-commit command

- cmd/autoowners/README.md
- cmd/autoowners/main.go
/cc @stevekuznetsov @petr-muller
> Remove flags of autoowners from dependencies

- cmd/autoowners/README.md
- cmd/autoowners/main.go
> Add ignore-repo flag in autoowners README.md

- cmd/autoowners/main.go
> Fix the commit msg in autoowners

- cmd/ci-operator/main.go
- go.mod
- pkg/api/graph.go
- pkg/api/graph_test.go
- pkg/api/types.go
- pkg/config/template.go
- pkg/diffs/diffs.go
- pkg/interrupt/interrupt.go
- pkg/junit/types.go
- pkg/load/load.go
- pkg/registry/resolver.go
- pkg/registry/resolver_test.go
- pkg/rehearse/jobs.go
- pkg/rehearse/jobs_test.go
- pkg/rehearse/metrics.go
- pkg/rehearse/metrics_test.go
- pkg/steps/artifacts.go
- pkg/steps/clusterinstall/clusterinstall.go
- pkg/steps/git_source.go
- pkg/steps/multi_stage_test.go
- pkg/steps/output_image_tag_test.go
- pkg/steps/release/release_images.go
- pkg/steps/run_test.go
- pkg/steps/types/types.go
- test/prowgen-integration/data/input/config/super/duper/super-duper-release-3.11.yaml
We've got a couple hundred of these things hanging around ... 
@openshift/openshift-team-developer-productivity-test-platform
> Address static code linting warnings

- pkg/diffs/diffs_test.go
> Handle errors from DeepCopy()

- cmd/autoowners/README.md
- cmd/autoowners/main.go
- cmd/autoowners/main_test.go
- vendor/modules.txt
Address https://github.com/openshift/release/pull/5014#issuecomment-531163608
> Ignore the repo with no OWNERS file in the upstream repo

- cmd/autoowners/main.go
https://github.com/openshift/release/pull/5054#issuecomment-532403121
> Add debug logs into autoowners

- cmd/pj-rehearse/main.go
- pkg/diffs/diffs.go
- pkg/diffs/diffs_test.go
> Refactor away more compound configuration usage

- cmd/pj-rehearse/main.go
- pkg/diffs/diffs.go
- pkg/diffs/diffs_test.go
@openshift/openshift-team-developer-productivity-test-platform
> Remove unused loggers

- cmd/autoowners/main.go
Using master/head as commit generates unnecessary modification for OWNERS file.
Ideally, we should use the last commit on the file and modify it only when the last commit is changed (as today, this need to implement list-commits function at upstream).
With limit time on this task, we remove the headers.
> Remove the commit releated header in OWNERS file

- images/autoconfigbrancher/Dockerfile
> Add Dockerfile for auto-config-brancher

- pkg/steps/template.go
- pkg/steps/template_test.go
This patch only moves the label injection code to its own function and adds unit tests for it.
> Refactor labels injection and add tests.

- images/autoconfigbrancher/Dockerfile
> Build auto-config-brancher image with its binary

- Makefile
- cmd/ci-operator-configresolver/main.go
- test/ci-operator-configresolver-integration/configs/release-4.2/openshift-installer-release-4.2.yaml
- test/ci-operator-configresolver-integration/expected/openshift-installer-release-4.2.json
- test/ci-operator-configresolver-integration/run.sh
- vendor/modules.txt
This adds a new ci-operator-configresolver command.
This PR is a breakout of PR #131 to make it easier to review and move forward.
> Add ci-operator-configresolver

- cmd/ci-operator/main.go
- cmd/ipi-deprovision/ipi-deprovision.sh
- pkg/api/types.go
- test/artifact/test.yaml
> correction of misspelled words and yaml fields.

- cmd/ci-operator-configresolver/main.go
- cmd/ci-operator-prowgen/main_test.go
- cmd/ci-operator/main.go
- pkg/api/config.go
- pkg/api/graph.go
- pkg/steps/output_image_tag_test.go
- pkg/steps/pod.go
- pkg/steps/source.go
> Staticcheck nits corrections

- cmd/autoowners/main.go
- cmd/autoowners/main_test.go
The bug is from the case in which `OWNERS` file DOES exist while
`OWNERS_ALIASES` not. It led to the result of non-existence of
the `OWNERS` file, i.e., `httpResult.ownersFileExists=false`.
The impact of this bug is that we had ignored syncing `OWNERS`
for the repos in the above case.
Test cases have been added to avoid recurrence of this bug in the
feature.
> Fix getOwnersHTTP in autoowners

- cmd/blocking-issue-creator/main.go
- images/blocking-issue-creator/Dockerfile
Also fix a small pitfall in how `blocking-issue-creator` handles token.
> Add a Dockerfile to build blocking-issue-creator

- cmd/config-change-trigger/main.go
- cmd/config-change-trigger/main_test.go
When asking for a branch, the format is `heads/<name>`.
> Ask GitHub for the correct ref

- cmd/testgrid-config-generator/main.go
- test/testgrid-config-generator/config/release/ocp-4.2.json
- test/testgrid-config-generator/config/release/okd-4.1.json
- test/testgrid-config-generator/config/release/okd-4.2.json
- test/testgrid-config-generator/expected/redhat-openshift-ocp-release-4.2-informing.yaml
- test/testgrid-config-generator/expected/redhat-openshift-okd-release-4.1-informing.yaml
- test/testgrid-config-generator/expected/redhat-openshift-okd-release-4.2-informing.yaml
/cc @smarterclayton @petr-muller
> Ignore a job that is not sharded by version

- pkg/jobconfig/files.go
- pkg/jobconfig/files_test.go
Reverts openshift/ci-tools#194
https://github.com/openshift/release/pull/5274 should bring everyting that is needed for this to merge.
> Revert "Revert "Collapse job configuration configmaps for master branch""

- pkg/rehearse/jobs.go
- test/pj-rehearse-integration/expected.yaml
> Ensure periodics still the correct workdir in rehearsal

- cmd/config-change-trigger/main.go
> Trigger images jobs even when they're brand new

- pkg/rehearse/jobs.go
- test/pj-rehearse-integration/candidate/ci-operator/jobs/super/duper/super-duper-ciop-cfg-change-presubmits.yaml
- test/pj-rehearse-integration/expected.yaml
- test/pj-rehearse-integration/master/ci-operator/jobs/super/duper/super-duper-ciop-cfg-change-presubmits.yaml
> Correctly honor "extra" fields for refs in rehearsal

- cmd/ci-operator-configresolver/main.go
- pkg/load/configAgent.go
- pkg/load/load.go
This PR should improve the debugging experience for ci-operator-configresolver
> change ci-op and configresolver logging to improve debugging

- cmd/autobumper/main.go
The problem is not fixed by [1] since we still found such failures,
(see [2]).
The reason is that the images map returned from bumper pkg does not
reflect the files that have been modifed.
We implement this by a `git-status` call.
[1]. https://github.com/openshift/ci-tools/pull/200
[2]. https://prow.svc.ci.openshift.org/view/gcs/origin-ci-test/logs/periodic-prow-image-autobump/85
> Fix failures when no update of image is made (2)

- pkg/load/load.go
There haven't been any errors or discrepencies being detected so far with the resolver, so this PR will let us use the config from the configresolver directly for the ci-tools repo. If nothing breaks, this will be the default behavior for all repos.
> ci-operator: use configresolver config directly for ci-tools repo

- pkg/steps/clusterinstall/template.go
Includes compact clusters and gathers machine info.
> ci-operator: Update the upgrade template to match release

- cmd/ci-operator-prowgen/main.go
- test/prowgen-integration/data/output/jobs/private/duper/private-duper-master-periodics.yaml
- test/prowgen-integration/data/output/jobs/private/duper/private-duper-master-postsubmits.yaml
- test/prowgen-integration/data/output/jobs/private/duper/private-duper-master-presubmits.yaml
/cc @petr-muller @stevekuznetsov
> [prowgen] Manually inject private bucket on decoration config of private jobs

- cmd/applyconfig/README.md
- cmd/applyconfig/applyconfig.go
- cmd/applyconfig/applyconfig_test.go
> Specify context name of kubeconfig in applyConfig

- pkg/api/types.go
https://blog.golang.org/constants#TOC_4.
> pkg/api: use strongly-typed constants

- cmd/applyconfig/applyconfig.go
follow up https://github.com/openshift/ci-tools/pull/224#discussion_r338631576
> Improve the format of error msg for applyConfig

- cmd/ci-operator-prowgen/main.go
- test/prowgen-integration/data/output/jobs/private/duper/private-duper-master-periodics.yaml
- test/prowgen-integration/data/output/jobs/private/duper/private-duper-master-postsubmits.yaml
- test/prowgen-integration/data/output/jobs/private/duper/private-duper-master-presubmits.yaml
/cc @openshift/openshift-team-developer-productivity-test-platform-maintainers
> remove decoration config injection to private jobs.

- cmd/determinize-prow-config/main.go
- images/determinize-prow-config/Dockerfile
- pkg/config/release.go
> Add a tool to determinize prow configuration

- GENERATOR.md
- pkg/jobconfig/files.go
Follow up https://github.com/openshift/ci-tools/pull/254
> Ignore the cluster param in prowgen

- cmd/determinize-prow-config/main.go
> Fix import ordering

- pkg/promotion/promotion.go
- pkg/promotion/promotion_test.go
> Allow individual repos to enter branch cut early

- cmd/ci-operator-configresolver/main.go
Running the configresolver without config or registry directories is
going to fail anyway so we should validate those on startup to make it
clear to the user. A new `--validate-only` flag allows running the
binary to validate config on disk but not running the server.
/assign @AlexNPavel @bbguimaraes
> Validate flags in the configresolver, add a validator mode

- pkg/load/load.go
> Allow README and OWNERS in registry directories

- cmd/ci-operator-prowgen/main.go
Based on https://github.com/openshift/release/pull/5934#issuecomment-554383694
> Use kubuconfig arg with prowgen

- pkg/load/load.go
> Add a nil check to the registry load code

- pkg/api/config.go
- pkg/api/types.go
- pkg/steps/artifacts.go
- pkg/steps/multi_stage.go
- pkg/steps/multi_stage_test.go
- pkg/steps/pod.go
- pkg/steps/pod_test.go
- test/ci-operator-integration/base/config/test-config.yaml
- test/ci-operator-integration/base/expected_files/expected.json
fixes https://github.com/openshift/ci-tools/issues/294
> Re-revert defaulting PR

- cmd/ci-operator/main.go
Trying to figure out https://prow.svc.ci.openshift.org/view/gcs/origin-ci-test/pr-logs/pull/openshift_ci-secret-mirroring-controller/15/pull-ci-openshift-ci-secret-mirroring-controller-master-e2e-aws-build01/7
https://coreos.slack.com/archives/CBN38N3MW/p1574200499392000
---
Update
1. openshift uses secret of type `kubernetes.io/dockerconfigjson` to do the auth when importing images: [doc](https://docs.openshift.com/container-platform/3.11/dev_guide/managing_images.html#private-registries). It solves https://github.com/openshift/ci-tools/pull/290#issuecomment-556504425. With [the image built by this PR](https://prow.svc.ci.openshift.org/view/gcs/origin-ci-test/pr-logs/pull/openshift_ci-tools/290/pull-ci-openshift-ci-tools- …
> Create pull secret for importing is from api.ci

- pkg/steps/clusterinstall/template.go
Picks up changes to unify under CLUSTER_VARIANT
> ci-operator: Update the embedded template to the latest

- pkg/defaults/defaults.go
- pkg/steps/release/create_release.go
- test/ci-operator-integration/base/expected_files/expected.json
- test/ci-operator-integration/base/expected_files/expected_with_template.json
- test/ci-operator-integration/multi-stage/expected/hyperkube.json
> Replace SA builder with ci-operator

- cmd/pj-rehearse/main.go
- pkg/config/release.go
- pkg/load/registryAgent.go
- pkg/registry/resolver.go
- pkg/rehearse/jobs.go
- pkg/rehearse/jobs_test.go
- test/pj-rehearse-integration/candidate/ci-operator/config/super/trooper/super-trooper-master.yaml
- test/pj-rehearse-integration/expected.yaml
- test/pj-rehearse-integration/run.sh
Resolve inlined ci-operator configs in pj-rehearse.
> pj-rehearse: resolve multi-stage configurations

- test/ci-operator-configresolver-integration/run.sh
- test/ci-operator-integration/multi-stage/run.sh
This improves the `ci-operator-configresolver`'s tests in a variety of ways.
1. Checks that the generation is greater than `currGen` instead of `currGen+1`. This was always failing previously
2. Report error when `"${i}" -eq 9` instead of `"${i}" -eq 10`. Due to the way bash for loops work, `i` only reaches 9 in the loop, so this case was never hit previously, which is why the previous test bug wasn't detected.
3. Use `rsync -avh --quiet --delete --inplace` instead of deleting all files in `registry` and then copying files from `registry2` into the newly emptied directory. This prevents the registry from being reloaded excessively during the updates and prevents the configresolver reload errors.
4. Instead of storing `$PID`, use `$(jobs -p)` to get all background jobs. This prevents the …
> test/ci-operator-*: improve configresolver tests

- cmd/ci-operator-prowgen/main.go
- cmd/ci-operator/main.go
- go.mod
- go.sum
- pkg/lease/client.go
- vendor/k8s.io/test-infra/boskos/client/BUILD.bazel
- vendor/k8s.io/test-infra/boskos/client/client.go
- vendor/k8s.io/test-infra/prow/bugzilla/client.go
- vendor/k8s.io/test-infra/prow/config/BUILD.bazel
- vendor/k8s.io/test-infra/prow/config/branch_protection.go
- vendor/k8s.io/test-infra/prow/config/config.go
- vendor/k8s.io/test-infra/prow/config/inrepoconfig.go
- vendor/k8s.io/test-infra/prow/git/git.go
- vendor/k8s.io/test-infra/prow/plugins/buildifier/buildifier.go
- vendor/k8s.io/test-infra/prow/plugins/golint/golint.go
- vendor/k8s.io/test-infra/prow/plugins/mergecommitblocker/mergecommitblocker.go
- vendor/k8s.io/test-infra/prow/plugins/trigger/BUILD.bazel
- vendor/k8s.io/test-infra/prow/plugins/trigger/generic-comment.go
- vendor/k8s.io/test-infra/prow/plugins/trigger/pull-request.go
- vendor/k8s.io/test-infra/prow/plugins/trigger/trigger.go
- vendor/k8s.io/test-infra/prow/plugins/updateconfig/updateconfig.go
- vendor/k8s.io/test-infra/prow/plugins/verify-owners/verify-owners.go
- vendor/k8s.io/test-infra/prow/repoowners/repoowners.go
- vendor/modules.txt
https://jira.coreos.com/browse/DPTP-670
require https://github.com/kubernetes/test-infra/pull/15458/files and prow-image bumping
/hold
> Replace svc bokos with its route

- cmd/ci-operator-prowgen/main.go
- cmd/ci-operator-prowgen/main_test.go
We'll migrate more for testing. This is a prep step.
> Introduce a set of migrated repos

- pkg/steps/lease.go
- pkg/steps/lease_test.go
> pkg/steps/lease: forward junit sub-tests

- pkg/steps/release/create_release.go
https://prow.svc.ci.openshift.org/view/gcs/origin-ci-test/pr-logs/pull/openshift_release/6331/rehearse-6331-pull-ci-openshift-origin-master-e2e-gcp-upgrade/7#1:build-log.txt%3A25
```
2019/12/13 15:59:49 No initial release image necessary, stable-initial image stream does not include a cluster-version-operator image
```
However, 
```
- items:
- created: "2019-12-13T16:02:06Z"
dockerImageReference: registry.svc.ci.openshift.org/ocp/4.4@sha256:86e069315246948233d8c148a1ffc6af34c9a20344a35a84aacc4ba9931283b2
generation: 2
image: sha256:86e069315246948233d8c148a1ffc6af34c9a20344a35a84aacc4ba9931283b2
tag: cluster-version-operator
```
It seems we did not wait long enough.
Will verify with this image.
Why did not we hit this problem for other e2e tests? They all from existing namespace?
/cc …
> Wait cluster-version-operator to be imported

- GENERATOR.md
- cmd/ci-operator-prowgen/main.go
- cmd/ci-operator-prowgen/main_test.go
- cmd/config-migrater/README.md
- cmd/config-migrater/main.go
- pkg/jobconfig/files.go
- pkg/migrate/migrate.go
- pkg/migrate/migrate_test.go
- test/repo-init-integration/expected/ci-operator/jobs/openshift/origin/openshift-origin-master-postsubmits.yaml
- test/repo-init-integration/expected/ci-operator/jobs/openshift/origin/openshift-origin-master-presubmits.yaml
> Migrate openshift/origin to build01

- pkg/rehearse/jobs.go
> Define const CanBeRehearsedLabel in one place

- test/validate-prowgen-breaking-changes.sh
Updating vendored test-infra may cause `determinize-prow-config` to
produce different output. Unless addresses, this makes `prow-config`
job to fail for unrelated PRs to openshift/release (in principle
this is similar to when we change prowgen output).
Make the breaking-change script detect this situation.
> Detect breaking changes caused by test-infra updates

- cmd/ci-secret-bootstrap/README.md
Init the work on https://issues.redhat.com/browse/DPTP-639
> Add a new tool: ci-secret-mirroring

- cmd/pj-rehearse/main.go
- pkg/rehearse/jobs.go
- pkg/rehearse/jobs_test.go
- test/pj-rehearse-integration/run.sh
/hold
This requires an immediate follow-up to the release repo to update the presubmit.
> Remove --allow-volumes flag from the pj-rehearse tool

- pkg/steps/clusterinstall/template.go
Picks up changes to azure placement and exiting the test container
if setup fails with exit code 0 instead of 1 (so we don't double
report errors).
> steps: Update cluster upgrade template to latest

- pkg/rehearse/jobs.go
- pkg/rehearse/jobs_test.go
> Prevent rehearsing hidden jobs

- images/private-org-sync/Dockerfile
xref: https://github.com/openshift/ci-tools/pull/357
> Add a Dockerfile for private-org-sync

- pkg/load/load.go
> pkg/load: improve error msg when configresolver returns non-200 status

- cmd/ci-secret-bootstrap/README.md
- cmd/ci-secret-bootstrap/main.go
- cmd/ci-secret-bootstrap/main_test.go
- pkg/bitwarden/bitwarden.go
- pkg/bitwarden/cli.go
- pkg/bitwarden/cli_test.go
- pkg/bitwarden/fake.go
https://issues.redhat.com/browse/DPTP-639
> Implement ci-secret-bootstrap

- cmd/ci-secret-bootstrap/main.go
Before any secrets are read, the censoring formatter does nothing.
Therefore, setting the formatter to the censoring formatter before we've
read the password and ingested it does nothing of value. We can set the
formatter afterwords and keep the level of complexity here smaller,
removing global variables and other machinery.
> ci-secret-bootstrap: simplify censoring formatter setup

- cmd/ipi-deprovision/ipi-deprovision.sh
- images/ipi-deprovision/Dockerfile
- images/ipi-deprovision/google-cloud-sdk.repo
> ipi-deprovision: refactor to add gcp

- images/ipi-deprovision/Dockerfile
> ipi-deprovision: install latest awscli

- cmd/ipi-deprovision/ipi-deprovision.sh
> ipi-deprovision: script fixes

- images/ci-secret-bootstrap/Dockerfile
> Build image for ci-secret-bootstrap

- cmd/ipi-deprovision/ipi-deprovision.sh
> ipi-deprovision: fix directory structure

- cmd/ipi-deprovision/ipi-deprovision.sh
> ipi-deprovision: shuffle all possible clusters to reap

- cmd/ipi-deprovision/ipi-deprovision.sh
> ipi-deprovision: turn deprovisioning on 

- cmd/ci-secret-bootstrap/main.go
- cmd/ci-secret-bootstrap/main_test.go
https://issues.redhat.com/browse/DPTP-645
> Detect diff. between BW items and secrets

- cmd/ipi-deprovision/ipi-deprovision.sh
Follow up https://coreos.slack.com/archives/CBN38N3MW/p1579539221077700
> Timeout after 30m of destroying a cluster

- pkg/registry/graph_test.go
Adds a test for the `NewGraph` function to make sure that the error detection added in #376 continues to work properly.
> pkg/registry: add unit tests for NewGraph

- cmd/ipi-deprovision/ipi-deprovision.sh
> ipi-deprovision: calculate GCE TTL from creation time

- cmd/ipi-deprovision/ipi-deprovision.sh
> ipi-deprovision: fix GCE timing

- cmd/ci-secret-bootstrap/README.md
- cmd/ci-secret-bootstrap/main.go
- cmd/ci-secret-bootstrap/main_test.go
- pkg/bitwarden/bitwarden.go
- pkg/bitwarden/cli.go
- pkg/bitwarden/cli_test.go
- pkg/bitwarden/fake.go
> Support .login.password for ci-secret-bootstrap

- cmd/ci-secret-bootstrap/main.go
https://coreos.slack.com/archives/GB7NB0CUC/p1580230086114900
```bash
go test -race -count=1000 ./cmd/ci-secret-bootstrap/...
ok      github.com/openshift/ci-tools/cmd/ci-secret-bootstrap   78.493s
```
/assign @stevekuznetsov @bbguimaraes
> Fix a flaky test TestConstructSecrets

- cmd/ci-secret-bootstrap/README.md
https://issues.redhat.com/browse/DPTP-750?focusedCommentId=13959538&page=com.atlassian.jira.plugin.system.issuetabpanels%3Acomment-tabpanel#comment-13959538
> Improve doc for ci-secret-bootstrap

- pkg/steps/clusterinstall/template.go
Reverts openshift/ci-tools#402
> Revert "Add a pre-upgrade save for iptables and must-gather"

- cmd/ci-operator-prowgen/main.go
- cmd/ci-operator-prowgen/main_test.go
/assign @stevekuznetsov 
/hold
wait for the release repo change.
> Clean up build01 setup on ci-secret-mirroring repo

- cmd/ci-operator-prowgen/main.go
- pkg/config/load.go
/cc @openshift/openshift-team-developer-productivity-platform
> globalize prowgen's configuration name

- cmd/ci-operator-configresolver/main.go
- pkg/webreg/webreg.go
- test/ci-operator-configresolver-integration/config.yaml
- test/ci-operator-configresolver-integration/run.sh
- test/ci-operator-integration/multi-stage/run.sh
This PR adds a page where users can search for jobs they are interested in.
> webreg: add job search page

- pkg/load/load.go
- pkg/load/load_test.go
> pkg/load: check error from filepath.Walk in Registry

- cmd/autoconfigbrancher/main.go
> add ci-op-configs-mirror step in autoconfigbrancher tool

- images/autoconfigbrancher/Dockerfile
> add ci-op-configs-mirror to autoconfigbrancher image

- GENERATOR.md
- cmd/ci-operator-prowgen/main.go
- cmd/config-migrator/README.md
- cmd/config-migrator/main.go
- pkg/jobconfig/files.go
- pkg/migrate/migrate.go
> Migrate openshift/jenkins-openshift-login-plugin/master to build01

- pkg/migrate/migrate.go
required by https://github.com/openshift/release/pull/7088
> Migrate openshift/jenkins-openshift-login-plugin to build01

- cmd/ci-operator-prowgen/main.go
- pkg/api/config.go
- pkg/api/types.go
Add support for a separate OpenStack cloud for the ppc64le architecture
> Add support for a separate OpenStack cloud for the ppc64le architecture

- cmd/ci-operator-prowgen/main.go
This is real: if build01 is down it will block the merge on the repo.
/hold
https://github.com/openshift/release/pull/7124
> Migrate presubmits of jenkins-openshift-login-plugin to build01

- pkg/migrate/migrate.go
> Migrate presubmits of 30 repos

- cmd/pj-rehearse/main.go
The use case is the redhat-operator-ecosystem/release repo which is
supposed to only contain job config, and all other config items should
be taken from openshift/release repo. This means that templates etc are
never changed in PRs to that repo, so we can safely ignore all these.
> rehearse: add options to ignore templates, profiles and registry

- \
- cmd/ci-operator-prowgen/main.go
- cmd/ci-operator-prowgen/main_test.go
- cmd/config-migrator/main.go
- test/prowgen-integration/data/output/jobs/private-org/duper/private-org-duper-master-presubmits.yaml
- test/prowgen-integration/data/output/jobs/private/duper/private-duper-master-periodics.yaml
- test/prowgen-integration/data/output/jobs/private/duper/private-duper-master-postsubmits.yaml
- test/prowgen-integration/data/output/jobs/private/duper/private-duper-master-presubmits.yaml
- test/prowgen-integration/data/output/jobs/subdir/repo/subdir-repo-master-presubmits.yaml
- test/prowgen-integration/data/output/jobs/super/duper/super-duper-master-periodics.yaml
- test/prowgen-integration/data/output/jobs/super/duper/super-duper-master-postsubmits.yaml
- test/prowgen-integration/data/output/jobs/super/duper/super-duper-master-presubmits.yaml
- test/prowgen-integration/data/output/jobs/super/duper/super-duper-master-removed-promotion-presubmits.yaml
- test/prowgen-integration/data/output/jobs/super/duper/super-duper-release-3.11-postsubmits.yaml
- test/prowgen-integration/data/output/jobs/super/duper/super-duper-release-3.11-presubmits.yaml
- test/repo-init-integration/expected/ci-operator/jobs/openshift/ci-tools/openshift-ci-tools-master-postsubmits.yaml
- test/repo-init-integration/expected/ci-operator/jobs/openshift/ci-tools/openshift-ci-tools-master-presubmits.yaml
- test/repo-init-integration/expected/ci-operator/jobs/openshift/origin/openshift-origin-master-postsubmits.yaml
- test/repo-init-integration/expected/ci-operator/jobs/openshift/origin/openshift-origin-master-presubmits.yaml
- test/repo-init-integration/expected/ci-operator/jobs/org/other/org-other-nonstandard-presubmits.yaml
- test/repo-init-integration/expected/ci-operator/jobs/org/repo/org-repo-master-presubmits.yaml
/hold
wait for the change on release repo
---
Update:
https://github.com/openshift/release/pull/7107
> Complete args for all jobs

- cmd/config-change-trigger/main.go
/assign @hongkailiu @petr-muller
> config-change-trigger: limit maximum number of triggerd jobs

- pkg/load/configAgent.go
> config agent: ignore missing files

- CONFIGURATION.md
- cmd/ci-operator-prowgen/main.go
- pkg/api/config.go
- pkg/api/types.go
This will enable us to use the lease system when acquiring resources
from packet.net.
> Add packet cluster profile

- OWNERS
/assign @droslean @petr-muller
> Make alvaroaleman owner

- cmd/ci-op-configs-mirror/main.go
- test/ci-op-configs-mirror-integration/data/output/super-priv/duper/super-priv-duper-master.yaml
- test/ci-op-configs-mirror-integration/data/output/super-priv/trooper/super-priv-trooper-master.yaml
> ci-op-configs-mirror: change promotion config naming configuration

- cmd/autoconfigbrancher/main.go
This allows the autoconfigbrancher to self-approve its PR and hence avoid distracting humans.
We repeat the `BotName()` and `FindIssues` GitHub api call, because `bumper.UpdatePullRequest` doesn't allow to specificy labels that should be set, which I could fix upstream in a follow-up.
> Autoconfigbrancher: Add option to self-approve

- test/validate-prowgen-breaking-changes.sh
Typically we'll break both repos so checking openshift/release is usually enough, but checking both repos does not hurt anything.
> breaking-changes check: check breaking r-o-e/release

- cmd/pj-rehearse/main.go
- pkg/config/jobs.go
- pkg/diffs/diffs.go
- pkg/diffs/diffs_test.go
- pkg/rehearse/jobs.go
- pkg/rehearse/metrics.go
- test/pj-rehearse-integration/candidate/ci-operator/jobs/super/duper/super-duper-master-presubmits.yaml
- test/pj-rehearse-integration/expected.yaml
/assign @petr-muller @hongkailiu
> pj-rehearse: choose periodics and presubmits with changed clusters

- cmd/testgrid-config-generator/main.go
> testgrid: Add upgrade jobs to generic informing automatically

- pkg/steps/clusterinstall/template.go
Includes changes to allow upgrade tests to be parameterized.
> steps: Update cluster upgrade template

- pkg/steps/source.go
> ci-operator: wait for build deletion properly

- Makefile
- hack/pr-deploy.yaml
- pkg/webreg/webreg.go
> webreg: help: expand the section on using tests from another repo

- pkg/webreg/webreg.go
> help: don't use 'config' slang

- pkg/webreg/webreg.go
> help: style ci-operator consistently

- hack/pr-deploy.yaml
- pkg/webreg/webreg.go
> help: give all headers identifiers and self-links

- pkg/webreg/webreg.go
> help: use long-form works for numbers

- pkg/webreg/webreg.go
> help: be more explicit about which end-to-end tests are run

- pkg/steps/input_image_tag.go
- pkg/steps/input_image_tag_test.go
- pkg/steps/release/create_release.go
- pkg/steps/release/release_images.go
- pkg/util/imagestream.go
https://issues.redhat.com/browse/DPTP-826
> Wait pipeline image ready before build src

- pkg/webreg/webreg.go
> help: add a page explaining ci-operator and its config

- cmd/autoconfigbrancher/main.go
> Autoconfigbrancher: Use UpdatePullRequestWithLabel

- pkg/steps/template.go
> ci-operator: check err when waiting for Pods to finish

- Makefile
- go.mod
- go.sum
- vendor/k8s.io/test-infra/boskos/client/BUILD.bazel
- vendor/k8s.io/test-infra/boskos/client/client.go
- vendor/k8s.io/test-infra/prow/crier/reporters/github/BUILD.bazel
- vendor/k8s.io/test-infra/prow/crier/reporters/github/reporter.go
- vendor/modules.txt
In contrast to our downstream implementation, it retries all types of requests, not just update.
> Use upstream boskos client retrying

- cmd/ci-operator/main.go
- pkg/api/graph.go
- pkg/api/graph_test.go
- pkg/steps/clusterinstall/clusterinstall.go
- pkg/steps/git_source.go
- pkg/steps/images_ready.go
- pkg/steps/input_env.go
- pkg/steps/input_image_tag.go
- pkg/steps/lease.go
- pkg/steps/lease_test.go
- pkg/steps/multi_stage.go
- pkg/steps/output_image_tag.go
- pkg/steps/pipeline_image_cache.go
- pkg/steps/pod.go
- pkg/steps/project_image.go
- pkg/steps/release/create_release.go
- pkg/steps/release/promote.go
- pkg/steps/release/release_images.go
- pkg/steps/rpm_injection.go
- pkg/steps/rpm_server.go
- pkg/steps/run_test.go
- pkg/steps/source.go
- pkg/steps/template.go
- pkg/steps/testing.go
- pkg/steps/write_params.go
```
$ git checkout -q master; git diff --name-only master..rm | xargs wc | tail -1
7783  26187 249846 total
$ git checkout -q rm; git diff --name-only master..rm | xargs wc | tail -1
7636  25607 244736 total
```
=)
> ci-operator: remove dead code

- cmd/ci-operator/main.go
Contrary to step execution, `ci-operator`'s initialization can be
interrupted at any time, instantly.  Move it out of the
`interrupt.Handler.Run` call.
> ci-operator: restrict interrupt handling area

- go.mod
- pkg/rehearse/jobs_test.go
- pkg/rehearse/testdata/TestMakeRehearsalPresubmit_hidden_job_that_belong_to_the_same_org_repo_with_refs.yaml
- pkg/rehearse/testdata/TestMakeRehearsalPresubmit_job_that_belong_to_different_org_repo_than_refs.yaml
- pkg/rehearse/testdata/TestMakeRehearsalPresubmit_job_that_belong_to_the_same_org_but_different_repo_than_refs.yaml
- pkg/rehearse/testdata/TestMakeRehearsalPresubmit_job_that_belong_to_the_same_org_repo_with_refs.yaml
- pkg/rehearse/testdata/TestMakeRehearsalPresubmit_job_that_doesn't_report_reports_on_rehearsal.yaml
- vendor/github.com/pmezard/go-difflib/LICENSE
- vendor/github.com/pmezard/go-difflib/difflib/difflib.go
- vendor/modules.txt
Putting this into a dedicated PR to make the actual change I want to make easier to review.
> Make TestMakeRehearsalPresubmit fixture-based to easen maintainability

- pkg/steps/template.go
`Delete` events have a valid object:
https://godoc.org/k8s.io/apimachinery/pkg/watch#Event
Additionally, they:
- could be ignored if either `podJobIsOK` or `podJobIsFailed` matched
the event object
- logged an older version of the pod — from the `List` call at the top
of the function
> ci-operator: properly handle deleted pods

- cmd/pj-rehearse/main.go
- go.mod
- go.sum
- pkg/rehearse/jobs.go
- pkg/rehearse/testdata/TestMakeRehearsalPresubmit_hidden_job_that_belong_to_the_same_org_repo_with_refs.yaml
- pkg/rehearse/testdata/TestMakeRehearsalPresubmit_job_that_belong_to_different_org_repo_than_refs.yaml
- pkg/rehearse/testdata/TestMakeRehearsalPresubmit_job_that_belong_to_the_same_org_but_different_repo_than_refs.yaml
- pkg/rehearse/testdata/TestMakeRehearsalPresubmit_job_that_belong_to_the_same_org_repo_with_refs.yaml
- pkg/rehearse/testdata/TestMakeRehearsalPresubmit_job_that_doesn't_report_reports_on_rehearsal.yaml
- vendor/k8s.io/test-infra/prow/config/config.go
- vendor/k8s.io/test-infra/prow/plugins/bugzilla/BUILD.bazel
- vendor/k8s.io/test-infra/prow/plugins/bugzilla/bugzilla.go
- vendor/modules.txt
This PR makes the rehearsals validate the job config before creating jobs.
Not really sure how to test it, just merge and create a pr against openshift/release to check if it works?
> Rehearsals: validate job config

- pkg/migrate/migrate.go
required by https://github.com/openshift/release/pull/7363
> Migrate presubmits: repo 201 - 230

- pkg/migrate/migrate.go
required by https://github.com/openshift/release/pull/7379
> Keep presubmits openshift/release on default

- cmd/autoowners/main.go
- cmd/autoowners/main_test.go
This PR extends the autoowners tool to filter out entries from the owners file that are not org members in order to produce an owners file that is valid.
Note that I explicitly choose not to use [`trigger.TrustedUser`](https://github.com/kubernetes/test-infra/blob/18fae0a00a2cd5be7ee45563d0b0f940c0e86397/prow/plugins/trigger/trigger.go#L155) because it does a set of api calls per user, which would result in a gigantic token usage. This means that:
* We filter out entries as invalid that are valid due to being a collaborator 
* We filter out entries as invalid due to being member of the trusted org (which we haven't configured, so should be irrelevant)
/assign stevekuznetsov @petr-muller
> Autoowners: Remove non-org members

- cmd/autoowners/main.go
- cmd/autoowners/main_test.go
> Autoowners: Ignore casing when checking if owners are org members

- pkg/migrate/migrate.go
required by https://github.com/openshift/release/pull/7422
> Migrate presubmits of installer repo

- pkg/webreg/webreg.go
/assign @AlexNPavel @bbguimaraes
> help: document a step's execution environment

- cmd/ci-operator/main.go
When the user does not specify a TTL argument, don't overwrite an
existing annotation value on the namespace. This allows a later
invocation to inherit an earlier invocation's values, but still
override if necessary.
> ci-operator: Do not overwrite TTL annotations unless explicit

- pkg/webreg/webreg.go
This should make it less confusing to users
> webreg: change "reference" to "step"

- pkg/migrate/migrate.go
- test/repo-init-integration/expected/ci-operator/jobs/openshift/origin/openshift-origin-master-presubmits.yaml
required by https://github.com/openshift/release/pull/7426
> Migrate presubmits of origin repo

- pkg/steps/git_source.go
- pkg/steps/pipeline_image_cache.go
- pkg/steps/project_image.go
- pkg/steps/rpm_injection.go
- pkg/steps/source.go
/hold
I would like to monitor jobs when this is merged.
> ci-operator: make build functions interruptible

- pkg/steps/input_image_tag.go
> input images: wait longer for import

- pkg/steps/input_image_tag.go
- pkg/steps/release/create_release.go
- pkg/steps/rpm_server.go
/hold
I would like to monitor jobs when this is merged.
> ci-operator: make other functions interruptible

- pkg/steps/multi_stage.go
The code that handles interruptions could be called up to three times
(harmlessly) because multiple versions of the same go routine were
started unnecessarily.
> ci-operator multi-stage: delete pods only once

- cmd/ci-operator-prowgen/main.go
- cmd/ci-operator-prowgen/main_test.go
- test/prowgen-integration/data/output/jobs/private-org/duper/private-org-duper-master-presubmits.yaml
- test/prowgen-integration/data/output/jobs/private/duper/private-duper-master-presubmits.yaml
- test/prowgen-integration/data/output/jobs/subdir/repo/subdir-repo-master-presubmits.yaml
- test/prowgen-integration/data/output/jobs/super/duper/super-duper-master-presubmits.yaml
- test/prowgen-integration/data/output/jobs/super/duper/super-duper-master-removed-promotion-presubmits.yaml
- test/prowgen-integration/data/output/jobs/super/duper/super-duper-release-3.11-presubmits.yaml
- test/repo-init-integration/expected/ci-operator/jobs/openshift/ci-tools/openshift-ci-tools-master-presubmits.yaml
- test/repo-init-integration/expected/ci-operator/jobs/openshift/origin/openshift-origin-master-presubmits.yaml
- test/repo-init-integration/expected/ci-operator/jobs/org/other/org-other-nonstandard-presubmits.yaml
- test/repo-init-integration/expected/ci-operator/jobs/org/repo/org-repo-master-presubmits.yaml
/assign @hongkailiu @petr-muller
> prowgen: duplicate tests on build01 that don't use quota

- cmd/ci-operator-prowgen/main.go
- cmd/ci-operator-prowgen/main_test.go
- test/prowgen-integration/data/output/jobs/private-org/duper/private-org-duper-master-presubmits.yaml
- test/prowgen-integration/data/output/jobs/private/duper/private-duper-master-presubmits.yaml
- test/prowgen-integration/data/output/jobs/subdir/repo/subdir-repo-master-presubmits.yaml
- test/prowgen-integration/data/output/jobs/super/duper/super-duper-master-presubmits.yaml
- test/prowgen-integration/data/output/jobs/super/duper/super-duper-master-removed-promotion-presubmits.yaml
- test/prowgen-integration/data/output/jobs/super/duper/super-duper-release-3.11-presubmits.yaml
- test/repo-init-integration/expected/ci-operator/jobs/openshift/ci-tools/openshift-ci-tools-master-presubmits.yaml
- test/repo-init-integration/expected/ci-operator/jobs/openshift/origin/openshift-origin-master-presubmits.yaml
- test/repo-init-integration/expected/ci-operator/jobs/org/other/org-other-nonstandard-presubmits.yaml
- test/repo-init-integration/expected/ci-operator/jobs/org/repo/org-repo-master-presubmits.yaml
Reverts openshift/ci-tools#527
> Revert "Revert "prowgen: duplicate tests on build01 that don't use quota""

- pkg/steps/clusterinstall/template.go
cherry-pick of openshift/release@89f98ec8cce5575bcd4263d47d7fe986a6d00e82
/assign @wking @smarterclayton
> upgrade: tar must-gather output

- cmd/ci-operator-prowgen/main.go
- test/prowgen-integration/data/output/jobs/private/duper/private-duper-master-postsubmits.yaml
Reverts openshift/ci-tools#464
> Revert "prowgen: temporarily rename private postsubmits"

- cmd/ci-operator/main.go
- pkg/steps/multi_stage.go
- pkg/steps/run.go
> ci-operator: don't exit when steps are interrupted

- cmd/autobumper/main.go
> autobumper: update clusters/

- cmd/applyconfig/applyconfig.go
This is needed for the `app.ci` deploy job because:
* We want to apply everything automatically there
* We can not use `system:admin` due to lack of permission
* Impersonating ourselves drops us from the `system:authenticated` group,  which means the `basic-user` clusterrolebinding doesn't apply anymore, which means we do not have permission to use discovery anymore, which means `oc apply` doesn't work at all
> Applyconfig: Allow to disable --as when applying admin config

- pkg/webreg/webreg.go
Document the new mode of operation introduced in
https://github.com/openshift/ci-tools/pull/544.
> secret-wrapper: update documentation

- cmd/ci-secret-bootstrap/main.go
- cmd/ci-secret-bootstrap/main_test.go
> Secret bootstrap: Allow provisioning only one cluster

- pkg/load/load.go
/assign @AlexNPavel @bbguimaraes
> ci-operator: log the configresolver fetch if we do it

- pkg/webreg/webreg.go
/assign @bparees @smarterclayton @petr-muller
> webreg: document different types of jobs and how to configure them

- images/private-prow-config-mirror/Dockerfile
- images/private-prow-configs-mirror/Dockerfile
> fix private-prow-configs mirror image name

- cmd/autoconfigbrancher/main.go
- images/autoconfigbrancher/Dockerfile
> Add private-prow-configs-mirror tool in autoconfigbrancher pipeline

- cmd/applyconfig/applyconfig.go
Needed so we do not have to duplicate everything for app.ci.
/assign @petr-muller @hongkailiu
> Applyconfig: Allow passing multiple config dirs

- cmd/autoconfigbrancher/main.go
- images/autoconfigbrancher/Dockerfile
follow-up of https://github.com/openshift/ci-tools/pull/569
> Add prow-configs-mirror tool in autoconfigbrancher pipeline

- cmd/ci-operator-prowgen/main_test.go
- cmd/ci-operator-prowgen/testdata/postsubmit-TestFromCIOperatorConfigToProwYaml_Input_is_YAML_and_it_is_correctly_processed.yaml
- cmd/ci-operator-prowgen/testdata/postsubmit-TestFromCIOperatorConfigToProwYaml_Using_a_variant_config,_one_test_and_images,_one_existing_job._Expect_one_presubmit,_pre_post_submit_images_jobs._Existing_job_should_not_be_changed..yaml
- cmd/ci-operator-prowgen/testdata/postsubmit-TestFromCIOperatorConfigToProwYaml_one_test_and_images,_no_previous_jobs._Expect_test_presubmit_+_pre_post_submit_images_jobs.yaml
- cmd/ci-operator-prowgen/testdata/presubmit-TestFromCIOperatorConfigToProwYaml_Input_is_YAML_and_it_is_correctly_processed.yaml
- cmd/ci-operator-prowgen/testdata/presubmit-TestFromCIOperatorConfigToProwYaml_Using_a_variant_config,_one_test_and_images,_one_existing_job._Expect_one_presubmit,_pre_post_submit_images_jobs._Existing_job_should_not_be_changed..yaml
- cmd/ci-operator-prowgen/testdata/presubmit-TestFromCIOperatorConfigToProwYaml_one_test_and_images,_no_previous_jobs._Expect_test_presubmit_+_pre_post_submit_images_jobs.yaml
Changing the inline yaml is a huge waste of time.
/assign @petr-muller @stevekuznetsov
> Ci operator prowgen: Test via fixtures

- cmd/cvp-trigger/README.md
/cc @stevekuznetsov @dirgim @robnester-rh 
Please note that the mentioned job is still in a pending PR https://github.com/openshift/release/pull/7710, but this describes my current intentions.
> cvp-trigger: describe interface to common CVP jobs

- go.mod
- go.sum
- test/cvp-trigger-integration/periodic-ipi-deprovision.expected
- test/pj-rehearse-integration/expected.yaml
- test/repo-init-integration/expected/core-services/prow/02_config/_config.yaml
- vendor/k8s.io/test-infra/ghproxy/ghcache/README.md
- vendor/k8s.io/test-infra/ghproxy/ghcache/coalesce.go
- vendor/k8s.io/test-infra/ghproxy/ghmetrics/ghmetrics.go
- vendor/k8s.io/test-infra/prow/apis/prowjobs/v1/types.go
- vendor/k8s.io/test-infra/prow/apis/prowjobs/v1/zz_generated.deepcopy.go
- vendor/k8s.io/test-infra/prow/config/config.go
- vendor/k8s.io/test-infra/prow/flagutil/github.go
- vendor/k8s.io/test-infra/prow/github/client.go
- vendor/k8s.io/test-infra/prow/pjutil/pjutil.go
- vendor/k8s.io/test-infra/prow/plugins/OWNERS
- vendor/k8s.io/test-infra/prow/plugins/plugins.go
- vendor/k8s.io/test-infra/prow/repoowners/repoowners.go
- vendor/modules.txt
> vendor: bump prow

- cmd/determinize-prow-jobs/main.go
This PR changes the `determinize-job-config` tool to go over all jobs, not just the ones managed by ci-operator.
I also added parallelization because I got bored while waiting for it to finish running.
> Determinize job config: Run over all jobs

- cmd/ci-operator-prowgen/main.go
- cmd/ci-operator-prowgen/main_test.go
- pkg/config/load.go
https://issues.redhat.com/browse/DPTP-972
> prowgen: add expose option to prowgen config (DPTP-972)

- images/autoconfigbrancher/Dockerfile
> Autoconfigbrancher image: Add determinize prow jobs

- cmd/autoconfigbrancher/main.go
- cmd/determinize-prow-jobs/main.go
> Autoconfigbrancher: Fix determinize-prow-job call arguments

- pkg/api/config.go
- pkg/api/config_test.go
> ci-operator: fix promotion validation

- pkg/api/config.go
- pkg/api/config_test.go
> ci-operator: make promotion validation more strict

- images/ipi-deprovision/Dockerfile
- images/ipi-deprovision/azure-cli.repo
> ipi-deprovision: install the azure cli

- pkg/load/load.go
- pkg/load/load_test.go
- test/multistage-registry/invalid-filename/ipi/install/ipi-install-install-ref.yaml
> pkg/load: validate full filename for registry components

- cmd/ipi-deprovision/ipi-deprovision.sh
/assign @abhinavdahiya @jhixson74
> ipi-deprovision: prune azure clusters, too

- cmd/cvp-trigger/README.md
/cc @robnester-rh @dirgim @stevekuznetsov
> cvp-trigger: describe parameters specifying optional operator under test

- cmd/applyconfig/applyconfig.go
Helps tremendously with debugging.
We set a censoring formatter for logrus in init, so this should be fine.
> Applyconfig: Log command

- Makefile
- pkg/webreg/webreg.go
> webreg: document leases and quota

- pkg/steps/lease.go
- pkg/steps/multi_stage.go
- pkg/steps/multi_stage_test.go
- test/ci-operator-integration/multi-stage/expected/installer.json
- test/ci-operator-integration/multi-stage/run.sh
> ci-operator: expose which resource was leased to steps

- pkg/webreg/webreg.go
> webreg: document $OPENSHIFT_CI

- pkg/webreg/webreg.go
> webreg: cross-reference lease doc in env doc

- cmd/repo-init/main.go
- cmd/repo-init/main_test.go
- pkg/api/config.go
- pkg/api/config_test.go
- pkg/steps/input_image_tag.go
- pkg/steps/multi_stage.go
- test/ci-op-configs-mirror-integration/data/input/foo/bar/foo-bar-master.yaml
- test/ci-op-configs-mirror-integration/data/output/foo/bar/foo-bar-master.yaml
- test/ci-operator-configresolver-integration/ci-op-configmaps/master/..2019_11_15_19_57_20.547184898/openshift-installer-master.yaml
- test/ci-operator-configresolver-integration/ci-op-configmaps/release-4.2/..2019_11_15_19_57_20.547184898/openshift-installer-release-4.2.yaml
- test/ci-operator-configresolver-integration/configs/release-4.2/openshift-installer-release-4.2.yaml
- test/ci-operator-configresolver-integration/configs2/release-4.2/openshift-installer-release-4.2-golang111.yaml
- test/ci-operator-configresolver-integration/expected/openshift-installer-release-4.2-golang111.json
- test/ci-operator-configresolver-integration/expected/openshift-installer-release-4.2-regChange.json
- test/ci-operator-configresolver-integration/expected/openshift-installer-release-4.2.json
- test/ci-operator-integration/base/config/test-config.yaml
- test/ci-operator-integration/base/expected_files/expected.json
- test/ci-operator-integration/base/expected_files/expected_pull_secret.json
- test/ci-operator-integration/base/expected_files/expected_with_template.json
- test/ci-operator-integration/multi-stage/configs/master/openshift-hyperkube-master.yaml
- test/ci-operator-integration/multi-stage/configs/release-4.2/openshift-installer-release-4.2.yaml
- test/ci-operator-integration/multi-stage/expected/hyperkube.json
- test/ci-operator-integration/multi-stage/expected/installer.json
- test/prowgen-integration/data/input/config/private-org/duper/private-org-duper-master.yaml
- test/repo-init-integration/expected/ci-operator/config/openshift/ci-tools/openshift-ci-tools-master.yaml
- test/repo-init-integration/expected/ci-operator/config/openshift/origin/openshift-origin-master.yaml
- test/repo-init-integration/expected/ci-operator/config/org/other/org-other-nonstandard.yaml
- test/repo-init-integration/expected/ci-operator/config/org/repo/org-repo-master.yaml
- test/repo-init-integration/input/ci-operator/config/openshift/ci-tools/openshift-ci-tools-master.yaml
- test/repo-init-integration/input/ci-operator/config/openshift/origin/openshift-origin-master.yaml
https://issues.redhat.com/browse/DPTP-1010
/hold
require https://github.com/openshift/release/pull/7951
> Check empty cluster in ci-op's config

- cmd/repo-init/main.go
- cmd/repo-init/main_test.go
- pkg/api/config.go
- pkg/api/config_test.go
- pkg/steps/input_image_tag.go
- pkg/steps/multi_stage.go
- test/ci-op-configs-mirror-integration/data/input/foo/bar/foo-bar-master.yaml
- test/ci-op-configs-mirror-integration/data/output/foo/bar/foo-bar-master.yaml
- test/ci-operator-configresolver-integration/ci-op-configmaps/master/..2019_11_15_19_57_20.547184898/openshift-installer-master.yaml
- test/ci-operator-configresolver-integration/ci-op-configmaps/release-4.2/..2019_11_15_19_57_20.547184898/openshift-installer-release-4.2.yaml
- test/ci-operator-configresolver-integration/configs/release-4.2/openshift-installer-release-4.2.yaml
- test/ci-operator-configresolver-integration/configs2/release-4.2/openshift-installer-release-4.2-golang111.yaml
- test/ci-operator-configresolver-integration/expected/openshift-installer-release-4.2-golang111.json
- test/ci-operator-configresolver-integration/expected/openshift-installer-release-4.2-regChange.json
- test/ci-operator-configresolver-integration/expected/openshift-installer-release-4.2.json
- test/ci-operator-integration/base/config/test-config.yaml
- test/ci-operator-integration/base/expected_files/expected.json
- test/ci-operator-integration/base/expected_files/expected_pull_secret.json
- test/ci-operator-integration/base/expected_files/expected_with_template.json
- test/ci-operator-integration/multi-stage/configs/master/openshift-hyperkube-master.yaml
- test/ci-operator-integration/multi-stage/configs/release-4.2/openshift-installer-release-4.2.yaml
- test/ci-operator-integration/multi-stage/expected/hyperkube.json
- test/ci-operator-integration/multi-stage/expected/installer.json
- test/prowgen-integration/data/input/config/private-org/duper/private-org-duper-master.yaml
- test/repo-init-integration/expected/ci-operator/config/openshift/ci-tools/openshift-ci-tools-master.yaml
- test/repo-init-integration/expected/ci-operator/config/openshift/origin/openshift-origin-master.yaml
- test/repo-init-integration/expected/ci-operator/config/org/other/org-other-nonstandard.yaml
- test/repo-init-integration/expected/ci-operator/config/org/repo/org-repo-master.yaml
- test/repo-init-integration/input/ci-operator/config/openshift/ci-tools/openshift-ci-tools-master.yaml
- test/repo-init-integration/input/ci-operator/config/openshift/origin/openshift-origin-master.yaml
This reverts commit 93a610b90a3f0819173c0a95c9a50517e1ae43ed, reversing
changes made to 54704d469a58f6c0a7382a1ce2083625d7cb69d1.
> Revert "Merge pull request #604 from hongkailiu/cluster_stanza"

- cmd/determinize-peribolos/main.go
- images/determinize-peribolos/Dockerfile
> add a tool to determinize the peribolos config

- pkg/diffs/diffs.go
The way how this diff was presented was not useful anyway [1] so we can
as well remove it.
[1] https://prow.svc.ci.openshift.org/view/gcs/origin-ci-test/pr-logs/pull/openshift_release/8058/pull-ci-openshift-release-master-pj-rehearse/17488#1:build-log.txt%3A4
> rehearse: do not log full diff in a field

- cmd/cvp-trigger/README.md
Not sure if this is the best location for this documentation, but I haven't found any better. It describes how the `tool ↔ job ↔ ci-operator config ↔ workflow` are wired together, so that this knowledge is no longer only in my head. The implementation details can (and probably will) change while we are further iterating on this feature; I **commit** to maintain this section up-to-date until the feature settles.
I'd especially like the DPTP to review this so that I know if it makes sense to people who might need to build on this. Comments by CPaaS folks are also welcome though!
/cc @dirgim @robnester-rh
> cvp-trigger: document the architecture of the OO tests

- pkg/webreg/webreg.go
> docs: document time zone of nodes for cron

- pkg/webreg/webreg.go
Chains do not affect the treatment of failures.
> webreg: correct chain documentation

- cmd/testgrid-config-generator/README.md
The previous invocation example was not sufficient to explain how to adjust the job labels and controller configs to acheive a particular change to the TestGrid configuration.  Hopefully the explanation I'm adding allows folks to do that without having to work through the Go source.
> cmd/testgrid-config-generator: Add details to the README

- cmd/ci-secret-bootstrap/main.go
- cmd/ci-secret-bootstrap/main_test.go
- pkg/bitwarden/cli.go
/assign @hongkailiu @alvaroaleman
> ci-secret-bootstrap: improve UX

- cmd/testgrid-config-generator/README.md
Prune down to the minimum. The new algorithm is documented.
> testgrid-config-generator: Docs collision with my changes, remove

- cmd/testgrid-config-generator/README.md
Used this for the first time and got a little stuck... Add steps to make usage easier.
> cmd/testgrid-config-generator: add specific directions to README

- cmd/applyconfig/applyconfig.go
- cmd/applyconfig/applyconfig_test.go
/assign @petr-muller @droslean
> Re-Remove level functionality from applyconfig

- pkg/diffs/diffs.go
- pkg/diffs/diffs_test.go
The comparison logic was duplicated in methods that compared Presubmits
and Periodics, so I extracted the logic to a common method. I also
enhanced the logging to capture the reasons why a job is selected for
rehearsal.
> rehearse: unify how changed jobs are detected

- cmd/applyconfig/applyconfig.go
/hold
needs merging together with the o/release pr
> Applyconfig: Completely remove the level flag

- cmd/ci-secret-bootstrap/main.go
/assign @hongkailiu @alvaroaleman
> ci-secret-bootstrap: be explicit in errors

- cmd/autoconfigbrancher/main.go
- images/autoconfigbrancher/Dockerfile
> Fix autoconfigbrancher to generate correct cluster

- pkg/config/template.go
- pkg/config/template_test.go
e.g.
```
time="2020-04-14T19:24:14Z" level=info msg="Rehearsing Prow jobs for configuration PR openshift/release#1586892254" org=openshift repo=release
time="2020-04-14T19:24:24Z" level=info msg="templates changed" org=openshift repo=release templates="[{ci-operator/templates/openshift/installer/cluster-launch-installer-e2e.yaml 889b5f1c2e27850a9edf42154a667b140089d4c7}]"
time="2020-04-14T19:24:24Z" level=error msg="couldn't create template configMap" error="no entry in `updateconfig` matches \"ci-operator/templates/openshift/installer/cluster-launch-installer-e2e.yaml\"" org=openshift repo=release
time="2020-04-14T19:24:24Z" level=info msg="deleting temporary template configMaps" org=openshift repo=release
ERROR: pj-rehearse: setup failure
pj-rehearse failed to finish all setup necessary …
```
> rehearse: validate CMs are managed by updateconfig

- cmd/autoowners/README.md
- cmd/autoowners/main.go
- cmd/autoowners/main_test.go
- cmd/autoowners/testdata/test2/jobs/openshift/somefile.md
- cmd/autoowners/testdata/test2/jobs/somefile.md
Add parameters for github (org, repo, team) and directories
(config subdirs, target subdirectory).
Fixes kubevirt/project-infra#406
> Parameterize autoowners

- pkg/steps/release/create_release.go
> create_release: wait longer for image import

- cmd/autoperibolossync/main.go
- images/autoperibolossync/Dockerfile
simple to tool to run the `private-org-peribolos-sync` and open a PR against the `openshift/config` repository.
> Add a tool to run peribolos sync and open a PR with the changes included

- cmd/ci-operator/main.go
> sentry: stop reading sentry flag

- images/autoperibolossync/Dockerfile
> fix autoperibolossync image

- cmd/config-shard-validator/main.go
> Validate we don't use the `default` cluster alias and enable gzip

- cmd/ci-operator-configresolver/main.go
When we can't find a config, we should not call it a 400 but a 404.
> ci-operator-configresolver: return 404, log better

- cmd/ci-operator/main.go
https://issues.redhat.com/browse/DPTP-992
/hold
Need RBAC for SA in the release repo.
https://github.com/openshift/release/pull/8410
> Add console URL to ci-op's log

- cmd/sanitize-prow-jobs/main.go
Required by https://github.com/openshift/ci-tools/pull/660#discussion_r413085427
> Add flag config-path to sanitize-prow-jobs

- cmd/autoconfigbrancher/main.go
- cmd/sanitize-prow-jobs/main.go
- cmd/sanitize-prow-jobs/main_test.go
- cmd/sanitize-prow-jobs/testdata/TestLoadConfig/good_config.yaml
- cmd/sanitize-prow-jobs/testdata/TestLoadConfig/invalid_regex.yaml
- cmd/sanitize-prow-jobs/testdata/TestLoadConfig/invalid_yaml.yaml
- test/repo-init-integration/expected/ci-operator/jobs/openshift/origin/openshift-origin-master-presubmits.yaml
- test/repo-init-integration/expected/ci-operator/jobs/org/other/org-other-nonstandard-presubmits.yaml
- test/repo-init-integration/expected/core-services/sanitize-prow-jobs/_config.yaml
- test/repo-init-integration/input/core-services/sanitize-prow-jobs/_config.yaml
- test/repo-init-integration/run.sh
/cc @alvaroaleman @petr-muller 
Tested with
```bash
sanitize-prow-jobs --prow-jobs-dir=./ci-operator/jobs
```
/hold
requires https://github.com/openshift/release/pull/8209/files
> Use sanitize-prow-jobs to control jobs' cluster

- cmd/ci-operator/main.go
- pkg/results/report.go
- pkg/results/report_test.go
/assign @ingvagabund @alvaroaleman
> ci-operator: add optional, best-effort reporting of result

- cmd/result-aggregator/main.go
- images/result-aggregator/Dockerfile
New server for collecting error messages from ci-operator and exposing error metrics for Prometheus
> Result aggregator: new server for collecting error messages from ci-operator and exposing error metrics for Prometheus

- cmd/autoconfigbrancher/main.go
- images/autoconfigbrancher/Dockerfile
Required by https://github.com/openshift/release/pull/8530
> Revert 659 and keep centos:8

- go.sum
- pkg/load/agents/configAgent.go
- pkg/load/agents/configAgent_test.go
Needed for the ImageStreamController who needs to index configs by ImageStreamTag
> ConfigAgent: Allow adding indexers

- cmd/ipi-deprovision/ipi-deprovision.sh
4.2 clusters still leak these, so we need to remove them manually.
> ipi-deprovision: remove old buckets

- cmd/ipi-deprovision/ipi-deprovision.sh
> ipi-deprovision: specify project when listing buckets

- cmd/ipi-deprovision/ipi-deprovision.sh
> ipi-deprovision: delete buckets only when we have some to remove

- cmd/ci-secret-bootstrap/main.go
`ci-admins` are no longer `cluster-admin`.
We need to impersonate for updating secrets.
> Support impersonating in ci-secret-bootstrap

- cmd/ci-secret-bootstrap/main.go
/cc @alvaroaleman @petr-muller
> Fix impersonating in ci-secret-bootstrap

- cmd/autoconfigbrancher/main.go
Fixes: https://coreos.slack.com/archives/CHY2E1BL4/p1588025114125900
> auto-config-brancher: fix how determinize-ci-operator is called

- cmd/ci-operator/main.go
- cmd/pj-rehearse/main.go
- pkg/registry/graph.go
- pkg/steps/clusterinstall/clusterinstall.go
- pkg/steps/source.go
- pkg/steps/template.go
> Remove dead code

- cmd/autoowners/main.go
- cmd/ci-operator-config-mirror/main.go
- cmd/ci-operator/main.go
- cmd/config-migrator/main.go
- cmd/private-org-peribolos-sync/main.go
- pkg/api/graph.go
- pkg/load/agents/utils.go
- pkg/steps/run.go
- pkg/webreg/webreg.go
This PR implements the suggestions from the gosimple linter
> Implement gosimple suggestions

- cmd/determinize-ci-operator/main.go
- pkg/config/options.go
- pkg/promotion/promotion.go
> options: allow opting into --confirm as necessary

- pkg/config/options.go
We need this now to fix the binaries but I'll follow up with a test harness to catch this in the future
> options: fix binding for confirmable options

- cmd/ci-operator-prowgen/testdata/postsubmit-TestFromCIOperatorConfigToProwYaml_Input_is_YAML_and_it_is_correctly_processed.yaml
- cmd/ci-operator-prowgen/testdata/postsubmit-TestFromCIOperatorConfigToProwYaml_Using_a_variant_config,_one_test_and_images,_one_existing_job._Expect_one_presubmit,_pre_post_submit_images_jobs._Existing_job_should_not_be_changed..yaml
- cmd/ci-operator-prowgen/testdata/postsubmit-TestFromCIOperatorConfigToProwYaml_one_test_and_images,_no_previous_jobs._Expect_test_presubmit_+_pre_post_submit_images_jobs.yaml
- pkg/api/types.go
- pkg/prowgen/prowgen.go
- pkg/prowgen/prowgen_test.go
- test/prowgen-integration/data/output/jobs/private/duper/private-duper-master-postsubmits.yaml
- test/prowgen-integration/data/output/jobs/super/duper/super-duper-master-postsubmits.yaml
- test/prowgen-integration/data/output/jobs/super/duper/super-duper-release-3.11-postsubmits.yaml
- test/repo-init-integration/expected/ci-operator/jobs/openshift/ci-tools/openshift-ci-tools-master-postsubmits.yaml
- test/repo-init-integration/expected/ci-operator/jobs/openshift/origin/openshift-origin-master-postsubmits.yaml
> Label promototion jobs to allow recognizing them

- cmd/autoconfigbrancher/main.go
> autoconfigbrancher: forward config-dir to commands

- cmd/repo-brancher/main.go
- cmd/repo-brancher/main_test.go
- pkg/config/options.go
- pkg/config/options_test.go
- pkg/promotion/promotion_test.go
> options: add tests validating that flags load correctly

- cmd/config-brancher/main.go
- cmd/config-brancher/main_test.go
> config-brancher: read flags correctly

- cmd/result-aggregator/main.go
> result-aggregator: update logging

- pkg/results/report.go
> ci-operator: default the result aggregator address

- cmd/ipi-deprovision/ipi-deprovision.sh
> ipi-deprovision: ignore 3.11 clusters on GCP

- cmd/ci-operator/main.go
- cmd/ci-operator/main_test.go
> ci-operator: fix handling of jUnit errors

- cmd/ci-operator/main.go
- test/ci-operator-integration/base/run.sh
- test/ci-operator-integration/multi-stage/run.sh
>  ci-operator: initialize a lease client only when appropriate

- pkg/config/load.go
This reverts commit e37fc3abdd792173376ea8ae26cae4cd35f704d7.
This should not have merged -- the PR was declined here https://github.com/openshift/ci-tools/pull/739
The commit was accidentally added to the HEAD of https://github.com/openshift/ci-tools/pull/697 on a rebase.
/assign @alvaroaleman @droslean
> Revert "add a list of conditions when operating in ci-operator configs"

- pkg/steps/lease.go
> ci-operator: return better errors on lease failures

- cmd/private-prow-configs-mirror/main.go
> [private-prow-configs-mirror] include whitelisted repos in private prow configs mirror

- cmd/config-brancher/main.go
> config-brancher: set branch correctly in metadata

- pkg/prowgen/prowgen.go
- pkg/prowgen/prowgen_test.go
- test/repo-init-integration/expected/ci-operator/jobs/org/repo/org-repo-master-presubmits.yaml
> prowgen: don't add flags with default values

- Makefile
- cmd/cvp-trigger/main_test.go
- pkg/load/load_test.go
> Fix flaky TestLoad complex input

- pkg/api/config.go
- pkg/api/types.go
- pkg/prowgen/prowgen.go
Signed-off-by: Christy Norman <christy@linux.vnet.ibm.com>
> add remote libvirt profile for ppc64le

- cmd/private-org-peribolos-sync/main.go
> [private-org-peribolos-sync] include whitelisted repos in peribolos sync

- go.mod
- pkg/api/helper/imageextraction.go
- pkg/api/helper/imageextraction_test.go
- pkg/api/types.go
> Add helper to extract all ImageStreamTags for a test config

- hack/extract-kubeconfig.sh
> hack: add a script to grab a kubeconfig from a running cluster

- pkg/results/report.go
- pkg/results/report_test.go
> ci-operator: support basic auth for result aggregator

- pkg/results/report.go
> ci-operator: only load password when set

- Makefile
- hack/install.sh
> hack: expose production-install target

- cmd/result-aggregator/main.go
- pkg/results/report.go
> result-aggregator: handle basic auth in server

- cmd/ci-operator-prowgen/testdata/postsubmit-TestFromCIOperatorConfigToProwYaml_Input_is_YAML_and_it_is_correctly_processed.yaml
- cmd/ci-operator-prowgen/testdata/postsubmit-TestFromCIOperatorConfigToProwYaml_Using_a_variant_config,_one_test_and_images,_one_existing_job._Expect_one_presubmit,_pre_post_submit_images_jobs._Existing_job_should_not_be_changed..yaml
- cmd/ci-operator-prowgen/testdata/postsubmit-TestFromCIOperatorConfigToProwYaml_one_test_and_images,_no_previous_jobs._Expect_test_presubmit_+_pre_post_submit_images_jobs.yaml
- cmd/ci-operator-prowgen/testdata/presubmit-TestFromCIOperatorConfigToProwYaml_Input_is_YAML_and_it_is_correctly_processed.yaml
- cmd/ci-operator-prowgen/testdata/presubmit-TestFromCIOperatorConfigToProwYaml_Using_a_variant_config,_one_test_and_images,_one_existing_job._Expect_one_presubmit,_pre_post_submit_images_jobs._Existing_job_should_not_be_changed..yaml
- cmd/ci-operator-prowgen/testdata/presubmit-TestFromCIOperatorConfigToProwYaml_one_test_and_images,_no_previous_jobs._Expect_test_presubmit_+_pre_post_submit_images_jobs.yaml
- pkg/prowgen/prowgen.go
- pkg/prowgen/prowgen_test.go
- test/prowgen-integration/data/output/jobs/private-org/duper/private-org-duper-master-presubmits.yaml
- test/prowgen-integration/data/output/jobs/private/duper/private-duper-master-periodics.yaml
- test/prowgen-integration/data/output/jobs/private/duper/private-duper-master-postsubmits.yaml
- test/prowgen-integration/data/output/jobs/private/duper/private-duper-master-presubmits.yaml
- test/prowgen-integration/data/output/jobs/subdir/repo/subdir-repo-master-presubmits.yaml
- test/prowgen-integration/data/output/jobs/super/duper/super-duper-master-periodics.yaml
- test/prowgen-integration/data/output/jobs/super/duper/super-duper-master-postsubmits.yaml
- test/prowgen-integration/data/output/jobs/super/duper/super-duper-master-presubmits.yaml
- test/prowgen-integration/data/output/jobs/super/duper/super-duper-master-removed-promotion-presubmits.yaml
- test/prowgen-integration/data/output/jobs/super/duper/super-duper-release-3.11-postsubmits.yaml
- test/prowgen-integration/data/output/jobs/super/duper/super-duper-release-3.11-presubmits.yaml
- test/repo-init-integration/expected/ci-operator/jobs/openshift/ci-tools/openshift-ci-tools-master-postsubmits.yaml
- test/repo-init-integration/expected/ci-operator/jobs/openshift/ci-tools/openshift-ci-tools-master-presubmits.yaml
- test/repo-init-integration/expected/ci-operator/jobs/openshift/origin/openshift-origin-master-postsubmits.yaml
- test/repo-init-integration/expected/ci-operator/jobs/openshift/origin/openshift-origin-master-presubmits.yaml
- test/repo-init-integration/expected/ci-operator/jobs/org/other/org-other-nonstandard-presubmits.yaml
- test/repo-init-integration/expected/ci-operator/jobs/org/repo/org-repo-master-presubmits.yaml
> ci-operator-prowgen: add report username and password

- cmd/result-aggregator/main.go
> Fix result-aggregator flags

- cmd/private-org-sync/main.go
This refactoring stands out the synching logic that was happening inside the callback while iterating in the `ci-operator` configs and includes also the whitelisted org/repo/branches.
/cc @petr-muller @openshift/openshift-team-developer-productivity-test-platform
> [private-org-sync] Include whitelisted org/repo/branches in synching

- cmd/ci-operator/main.go
> Use app.ci configresolver

- cmd/autoperibolossync/main.go
> pass a whitelist file in the autoperibolos sync tool

- cmd/autoconfigbrancher/main.go
> pass whitelist file to the private sync tools in autoconfigbrancher

- Makefile
> make: add a stub for the e2e target

- cmd/ci-operator/main.go
> ci-operator: default --artifact-dir to $ARTIFACTS

- pkg/defaults/defaults.go
- pkg/steps/lease.go
- pkg/steps/lease_test.go
> ci-operator: annotate namespace as active while acquiring lease

- cmd/ci-operator/main.go
> ci-operator: monitor the namespace we run in

- cmd/autoperibolossync/main.go
/cc @petr-muller @stevekuznetsov @openshift/openshift-team-developer-productivity-test-platform 
> [autoperibolossync]] add a self-approve option

- cmd/ci-secret-bootstrap/main.go
- cmd/ci-secret-bootstrap/main_test.go
- go.mod
> Limit concurrency on ci-secret-bootstrap

- cmd/pj-rehearse/main.go
- pkg/rehearse/jobs.go
- pkg/rehearse/jobs_test.go
> rehearsal: fail when not able to inline configuration

- pkg/api/config.go
- pkg/api/config_test.go
- pkg/api/types.go
- pkg/steps/multi_stage.go
- pkg/steps/multi_stage_test.go
- pkg/webreg/webreg.go
- test/ci-operator-integration/multi-stage/configs/master/openshift-hyperkube-master.yaml
- test/ci-operator-integration/multi-stage/expected/hyperkube.json
> ci-operator: allow custom credentials in steps

- pkg/webreg/webreg.go
> webreg: doc API for $KUBECONFIG

- Makefile
- hack/test-e2e.sh
- hack/test-integration.sh
- test/e2e/simple.sh
- test/e2e/simple/config.yaml
Biggest question is ... will we have the RBAC we need?
> test: add an e2e test that runs simple commands

- cmd/secret-wrapper/main.go
> secret-wrapper: use in-cluster config

- pkg/api/types.go
- test/ci-operator-integration/multi-stage/configs/master/openshift-hyperkube-master.yaml
> fix missing json tags

- pkg/controller/promotionreconciler/reconciler.go
- pkg/controller/promotionreconciler/reconciler_test.go
- pkg/controller/util/error.go
- pkg/controller/util/error_test.go
> Add re-usable terminal errors

- Makefile
> make: deploy test servers to app.ci

- Makefile
- cmd/ci-operator/main.go
- go.mod
- pkg/api/config.go
- pkg/api/config_test.go
- pkg/api/types.go
- pkg/release/candidate/client.go
- pkg/release/candidate/client_test.go
- pkg/release/candidate/types.go
- pkg/release/official/client.go
- pkg/release/official/client_test.go
- pkg/release/official/types.go
- pkg/release/prerelease/client.go
- pkg/release/prerelease/client_test.go
- pkg/webreg/webreg.go
- test/e2e/simple.sh
- test/e2e/simple/dynamic-releases.yaml
/assign @openshift/openshift-team-developer-productivity-platform @smarterclayton
> ci-operator: allow for dynamically resolved releases

- pkg/api/types.go
> api: make architecture omitempty as it should be

- cmd/ci-operator/main.go
- cmd/testgrid-config-generator/main.go
- pkg/prowgen/prowgen.go
- pkg/release/candidate/client.go
- pkg/steps/input_image_tag.go
- pkg/util/domain.go
> util: DRY out the service host for our main cluster

- pkg/steps/multi_stage.go
- test/ci-operator-integration/multi-stage/expected/installer.json
> ci-operator: multi-stage: expose $IMAGE_FORMAT with profiles

- cmd/ipi-deprovision/ipi-deprovision.sh
It got lost here https://github.com/openshift/ci-tools/pull/849/files#diff-e656561bb535dd9f8aa0fc63095cbfacL36
Presumably an accident?
/assign @abhinavdahiya
> Ipi-deprovision: Re-Add lost infraID

- pkg/api/types.go
- pkg/defaults/defaults.go
- pkg/steps/release/create_release.go
- test/ci-operator-integration/base/expected_files/expected_with_template.json
- test/e2e/simple.sh
/assign @petr-muller @bbguimaraes
> ci-operator: propagate release input steps for releases

- pkg/defaults/defaults.go
> ci-operator: expose leased resource env

- cmd/private-org-sync/main.go
> [private-org-sync] Add `--debug` flag

- pkg/defaults/defaults.go
> ci-operator: expose more lease step params

- pkg/prowgen/prowgen.go
- pkg/prowgen/prowgen_test.go
- test/integration/ci-operator-prowgen/input/config/super/duper/super-duper-master.yaml
- test/integration/ci-operator-prowgen/output/jobs/super/duper/super-duper-master-presubmits.yaml
> ci-operator-prowgen: create a pull secret when resolving releases

- cmd/private-org-sync/main.go
> respect exit codes in git command errors

- pkg/release/candidate/client.go
- pkg/release/official/client.go
- pkg/release/prerelease/client.go
> ci-operator: emit better errors when failing to resolve

- cmd/prow-job-dispatcher/main.go
- cmd/prow-job-dispatcher/main_test.go
- go.mod
- pkg/dispatcher/prometheus.go
- pkg/dispatcher/prometheus_test.go
- vendor/github.com/prometheus/client_golang/api/client.go
- vendor/github.com/prometheus/client_golang/api/prometheus/v1/api.go
- vendor/modules.txt
> Implement Prow Jobs dispatcher

- pkg/api/config.go
- pkg/api/config_test.go
Preparation for https://github.com/openshift/ci-tools/pull/892
> Remove validation for cluster field set in imagestreamtags

- pkg/api/config.go
- pkg/api/config_test.go
Seems I missed it before, completes https://github.com/openshift/ci-tools/pull/897
> Remove remaining imagestreamtag cluster check

- hack/lib/integration.sh
- pkg/load/load_test.go
- pkg/registry/resolver.go
- test/ci-operator-integration/multi-stage/configs/release-4.2/openshift-installer-release-4.2.yaml
- test/ci-operator-integration/multi-stage/expected/installer.json
- test/ci-operator-integration/multi-stage/run.sh
- test/integration/ci-operator-configresolver/expected/openshift-installer-release-4.2-golang111.json
- test/integration/ci-operator-configresolver/expected/openshift-installer-release-4.2.json
- test/multistage-registry/configmap/..2019_11_15_19_57_20.547184898/ipi-install-install-ref.yaml
- test/multistage-registry/registry/ipi/install/install/ipi-install-install-ref.yaml
- test/multistage-registry/registry/ipi/install/with-parameter/ipi-install-with-parameter-chain.yaml
Different resolutions overwrite each other otherwise.
> registry: copy step environment when resolving

- hack/revert-ci-operator.sh
- pkg/rehearse/jobs.go
- test/pj-rehearse-integration/expected.yaml
Fixes failures like this: https://deck-ci.apps.ci.l2s4.p1.openshiftapps.com/view/gcs/origin-ci-test/pr-logs/pull/openshift_release/9572/pull-ci-openshift-release-master-pj-rehearse/22705#1:build-log.txt%3A10
> Rehearse: Set passed namespace

- cmd/ci-operator/main.go
> ci-operator: fix configuration access order

- pkg/steps/source_test.go
- pkg/steps/testdata/TestCreateBuild_basic_options_for_a_presubmit.yaml
- pkg/steps/testdata/TestCreateBuild_with_OAuth_token.yaml
- pkg/steps/testdata/TestCreateBuild_with_a_path_alias.yaml
- pkg/steps/testdata/TestCreateBuild_with_a_pull_secret.yaml
- pkg/steps/testdata/TestCreateBuild_with_extra_refs.yaml
- pkg/steps/testdata/TestCreateBuild_with_extra_refs_setting_workdir_and_path_alias.yaml
- pkg/steps/testdata/TestCreateBuild_with_ssh_key.yaml
The motivation for this is https://github.com/openshift/ci-tools/pull/893 but making this its own PR to make sure we spot it if #893 results in a diff
> Step tests: Use fixtures to make changes easier

- pkg/defaults/defaults.go
It's not clear why it was ever necessary to conditionally expose the
paramters that a step provides. We should ensure that all steps always
have their provided parameters exposed.
/assign @petr-muller @bbguimaraes
> ci-operator: unconditionally expose paramters from steps

- pkg/defaults/defaults.go
- test/e2e/simple.sh
> ci-operator: allow explicit env overrides for releases

- pkg/load/load.go
Turned multi-branch `if` to an idiomatic switch. Decapitalized few errors. Renamed
a `bytes` variable to not shadow a package. Removed a tautology.
> Code cleanups in ci-op config Load()

- test/integration/repo-init.sh
> test: update a test suite name

- cmd/registry-replacer/README.md
- cmd/registry-replacer/main.go
- cmd/registry-replacer/main_test.go
- cmd/registry-replacer/testdata/zz_fixture_TestReplacer_ContextDir_is_respected.yaml
- cmd/registry-replacer/testdata/zz_fixture_TestReplacer_Default_to_dockerfile.yaml
- cmd/registry-replacer/testdata/zz_fixture_TestReplacer_Existing_base_image_is_not_overwritten.yaml
- cmd/registry-replacer/testdata/zz_fixture_TestReplacer_Replaces_with_tag.yaml
- cmd/registry-replacer/testdata/zz_fixture_TestReplacer_Replaces_without_tag.yaml
Ref: https://issues.redhat.com/browse/DPTP-1264?focusedCommentId=14174826&page=com.atlassian.jira.plugin.system.issuetabpanels%3Acomment-tabpanel#comment-14174826
Could maybe be updated to also create a PR already?
> Add registry-replacer

- cmd/registry-replacer/testdata/zz_fixture_TestReplacer_ContextDir_is_respected.yaml
- cmd/registry-replacer/testdata/zz_fixture_TestReplacer_Default_to_dockerfile.yaml
- cmd/registry-replacer/testdata/zz_fixture_TestReplacer_Existing_base_image_is_not_overwritten.yaml
- cmd/registry-replacer/testdata/zz_fixture_TestReplacer_Replaces_with_tag.yaml
- cmd/registry-replacer/testdata/zz_fixture_TestReplacer_Replaces_without_tag.yaml
- pkg/api/types.go
- test/integration/cvp-trigger/periodic-ipi-deprovision.expected
- test/integration/pj-rehearse/expected.yaml
- test/integration/repo-init/expected/ci-operator/config/openshift/origin/openshift-origin-master.yaml
No reason to serialize this as `null`.
Realized in https://github.com/openshift/release/pull/9954
> Omitempty paths attribute

- pkg/steps/clusterinstall/template.go
Conditionally run-resourcewatch if it is available, to get the git monitoring tool running during the upgrade tests.
> Conditionally run the resourcewatch during the upgrade tests

- cmd/registry-replacer/main.go
- images/applyconfig/Dockerfile
- images/registry-replacer/Dockerfile
This PR adds pr-creating abilities to the registry replacer
> Registry replacer: add pr creation functionality

- pkg/util/imagestreamtagwrapper/imagestreamtagwrapper.go
The wrapper is called into for each request. Right now we create for
both tagReferences and tagEvents a map to solve the problem of "Give me
this one by name", resulting in creation of a map that is accessed once
and never again. These two functions are the top two for allocations:
```
$ go tool pprof /tmp/allocs.out
File: dptp-controller-manager
Type: alloc_space
Time: Jul 6, 2020 at 11:08am (EDT)
Entering interactive mode (type "help" for commands, "o" for options)
(pprof) top
Showing nodes accounting for 1126.33GB, 62.50% of 1802.25GB total
Dropped 1126 nodes (cum <= 9.01GB)
Showing top 10 nodes out of 204
flat  flat%   sum%        cum   cum%
399.30GB 22.16% 22.16%   399.30GB 22.16%  github.com/openshift/ci-tools/pkg/util/imagestreamtagwrapper.tagReferenceListToMap
190.15GB 10.55% …
```
> Imagestreamtagwrapper: Significantly reduce allocations

- cmd/registry-replacer/main.go
- cmd/registry-replacer/main_test.go
Sample is here and looks correct to me (smoke verified some of the examples): https://github.com/openshift/release/pull/10135
> Registry cleaner: Prune replacements

- pkg/steps/source.go
- pkg/steps/template.go
Ideally we would also show the events but that would require replacing the client with one that can get events. I can do that in a follow-up if we deem it necesary. The conditions do at least cover the pull image case properly:
```
containerStatuses:
- image: guaranteed-undef
imageID: ""
lastState: {}
name: guaranteed-undef
ready: false
restartCount: 0
started: false
state:
waiting:
message: Back-off pulling image "guaranteed-undef"
reason: ImagePullBackOff
```
> Pod step: Fail if pod doesn't start running within 30 minutes

- pkg/steps/source.go
Sample: https://deck-ci.apps.ci.l2s4.p1.openshiftapps.com/view/gcs/origin-ci-test/pr-logs/pull/openshift_ci-tools/997/pull-ci-openshift-ci-tools-master-images/1281666692186902528#1:build-log.txt%3A187
> Imagebuild: All mirrors tried means its non-terminal

- cmd/group-auto-updater/main.go
> add more logging to the group-auto-updater tool

- cmd/ci-operator/main.go
The usecase is to be able to determine what pods belong to a given test by getting all step names for the given test. The dependencies slice is something I added in case we need it in the future.
> CI-Operator: Dump step graph to artifacts

- pkg/steps/rpm_server.go
> ci-operator: expose rpm repo env var for periodics

- pkg/registry/resolver_test.go
I'm making some changes here and decided to go easy on the reviewers and break
this into a separate PR.  I'd love to know if there is a less hideous way of
doing it, but no other combination of `reflect`/`go-cmp` works and this is how
upstream `test-infra` does it, so…
/shrug
> pkg/registry: simplify tests

- cmd/dptp-controller-manager/main.go
- pkg/controller/test-images-distributor/test_images_distributor.go
- pkg/controller/test-images-distributor/test_images_distributor_test.go
https://github.com/openshift/release/pull/10475#issuecomment-664429816
> dptp-controller-manager: a new flag additional-image-stream-namespaces

- pkg/steps/artifacts.go
- pkg/steps/artifacts_test.go
- pkg/steps/multi_stage_test.go
Supersedes and thereby closes https://github.com/openshift/ci-tools/pull/958
> pkg/steps/artifacts: Wait for running artifacts container

- cmd/bugzilla-backporter/main.go
- pkg/backporter/httpcache.go
- pkg/backporter/httpcache_test.go
Inject the HTTPRoundTripper transport to the bugzilla client when caching is necessary
> Add a caching transport for the Bugzilla client

- cmd/autopublicizeconfig/README.md
- cmd/autopublicizeconfig/main.go
- images/autopublicizeconfig/Dockerfile
This tool re-generates the publicize plugin configuration file and submits a pull request against the `openshift/release` repository.
/cc @openshift/openshift-team-developer-productivity-test-platform  
> initial commit for auto publicize config tool

- pkg/backporter/httpcache.go
- pkg/backporter/httpcache_test.go
When the caching transport roundtrips, it starts a go routine to use
the underlying transport and then either gets the data from the cache or
waits for the goroutine to finish. In the tests, the go routine would
sometimes be able to finish before we get to the point of checking the
cache, causing us to return data from the goroutine and failing the
test.
> Bugzilla backporter TestRoundTrip: Deflake

- images/generate-registry-metadata/Dockerfile
Add `Dockerfile` for `generate-registry-metadata`.
> images: add generate-registry-metadata image

- cmd/applyconfig/applyconfig.go
Required by https://github.com/openshift/release/pull/10545
> appyconfig: support symlinks

- cmd/ci-operator/main.go
- pkg/api/domain.go
- pkg/api/domain_test.go
- test/integration/testgrid-config-generator/expected/redhat-openshift-informing.yaml
- test/integration/testgrid-config-generator/expected/redhat-openshift-ocp-release-4.1-blocking.yaml
- test/integration/testgrid-config-generator/expected/redhat-openshift-ocp-release-4.1-informing.yaml
- test/integration/testgrid-config-generator/expected/redhat-openshift-ocp-release-4.2-blocking.yaml
- test/integration/testgrid-config-generator/expected/redhat-openshift-ocp-release-4.2-informing.yaml
- test/integration/testgrid-config-generator/expected/redhat-openshift-ocp-release-4.3-broken.yaml
> ci-operator: use the vanity URL for our config API

- pkg/load/load.go
This round about halves the time needed to load the config which is great to speed up inner dev cycle
> Parallelize config loading

- pkg/controller/test-images-distributor/test_images_distributor.go
- pkg/controller/test-images-distributor/test_images_distributor_test.go
/hold
needs rbac updates first
> Test image distributor: Make sure imagestreams have local: true

- cmd/ci-secret-bootstrap/main.go
- pkg/steps/input_env.go
Fixes issues in https://prow.ci.openshift.org/view/gs/origin-ci-test/pr-logs/pull/openshift_release/10577/rehearse-10577-pull-ci-openshift-ci-tools-master-lint/1288947940097789952
> FIx some linting issues found by newer versions of golangci-lint

- pkg/load/agents/configAgent.go
- pkg/load/agents/configAgent_test.go
- pkg/load/agents/registryAgent.go
- test/integration/ci-operator-configresolver.sh
- test/integration/ci-operator-configresolver/expected/openshift-installer-release-4.2-regChange.json
- test/integration/pj-rehearse/expected.yaml
- test/multistage-registry/registry2/ipi/install/empty-parameter/ipi-install-empty-parameter-chain.yaml
- test/multistage-registry/registry2/ipi/install/install/ipi-install-install-ref.yaml
- test/multistage-registry/registry2/ipi/install/with-parameter/ipi-install-with-parameter-chain.yaml
See discussion in https://github.com/openshift/ci-tools/pull/1062.
> pkg/load/agents: expand critical section

- cmd/dptp-controller-manager/main.go
> DPTP-CM: Fix typo, opeartor->operator

- cmd/private-org-sync/main.go
- cmd/private-org-sync/main_test.go
Problem described in https://issues.redhat.com/browse/DPTP-1423 
> perform a merge --abort when merge is not possible

- pkg/backporter/backporter.go
- pkg/backporter/backporter_test.go
Allow users to identify missing clones in the existing clones.
> Add info box to show missing clones

- cmd/publicize/server.go
> fix link in successful publicize message

- cmd/publicize/server_test.go
> [publicize] extend unittest coverage to cover also the git operations

- pkg/rehearse/jobs.go
- pkg/rehearse/jobs_test.go
> pj-rehearse: don't remove unnecessary flags on accident

- cmd/private-org-sync/main.go
- cmd/private-org-sync/main_test.go
Changes are described in DPTP-1425
> [private-org-sync] change git merge commit message

- cmd/publicize/server.go
- cmd/publicize/server_test.go
Changes are described in [DPTP-1425](https://issues.redhat.com/browse/DPTP-1425)
> improve publicize message responses and commits

- cmd/dptp-controller-manager/main.go
xref https://github.com/kubernetes-sigs/controller-runtime/issues/1122
> DPTP-CM: Use null logger to require less memory

- cmd/publicize/server.go
- cmd/publicize/server_test.go
also part of https://issues.redhat.com/browse/DPTP-1425
> [publicize] include a link to the direct merge commit in the success message

- cmd/publicize/server_test.go
/cc @openshift/openshift-team-developer-productivity-test-platform @stevekuznetsov 
> fix git-version-dependent tests in publicize tool

- cmd/bugzilla-backporter/main.go
- pkg/backporter/backporter.go
- pkg/backporter/backporter_test.go
The create clones functionality will automatically chose
the immediately higher target release as the source bug while
creating a clone.
> Auto detect source bug for create clones

- pkg/steps/clusterinstall/template.go
> upgrade: annotate prowjob with version info

- pkg/backporter/backporter.go
- pkg/backporter/backporter_test.go
The clone tree was added to the UI to make it easier for
the user to understand the relationship between various clones.
> Add dependence tree to backporter UI

- pkg/steps/clusterinstall/template.go
> upgrade tempalate: use $BRANCH since it's already set

- pkg/steps/release/import_release.go
> ci-operator: only expose link if tag_spec isnt set

- cmd/registry-replacer/main.go
> Registry replacer: Explain promotion dockerfile fixup

- .golangci.yml
- cmd/autoconfigbrancher/main.go
- cmd/autoowners/main.go
- cmd/ci-operator/main_test.go
- cmd/ocp-build-data-enforcer/main.go
- cmd/ocp-build-data-enforcer/main_test.go
- cmd/pj-rehearse/main.go
- cmd/private-org-sync/main.go
- cmd/prow-job-dispatcher/main.go
- cmd/registry-replacer/main.go
- cmd/testgrid-config-generator/main.go
- pkg/backporter/backporter.go
- pkg/config/jobs.go
- pkg/controller/util/request_coalescer.go
- pkg/dispatcher/prometheus.go
- pkg/release/candidate/client_test.go
- pkg/release/official/client_test.go
- pkg/release/prerelease/client_test.go
- pkg/webreg/webreg.go
- Fix ineffassigns
- Fix a couple of spelling mistakes
> Enable ineffassign and misspell linters

- pkg/steps/clusterinstall/template.go
Prototyping a side-car container that continuously watch the test run and report the cluster operator status into container log.
This should run the resource watcher from `openshift-tests` binary.
> WIP: add continous watcher to monitor the jobs

- pkg/bitwarden/cli.go
Sometimes it seems like we get correct stdout from `bw` but we get
something like 'mac failed.' in stderr, which we can't parse as JSON.
> bitwarden: make the client more resilient

- pkg/steps/template.go
- test/e2e/simple.sh
> e2e: use import secrets always

- go.mod
- go.sum
- vendor/k8s.io/test-infra/prow/bugzilla/BUILD.bazel
- vendor/k8s.io/test-infra/prow/bugzilla/client.go
- vendor/k8s.io/test-infra/prow/bugzilla/fake.go
- vendor/k8s.io/test-infra/prow/config/config.go
- vendor/k8s.io/test-infra/prow/config/jobs.go
- vendor/k8s.io/test-infra/prow/git/git.go
- vendor/k8s.io/test-infra/prow/hook/BUILD.bazel
- vendor/k8s.io/test-infra/prow/initupload/run.go
- vendor/k8s.io/test-infra/prow/logrusutil/logrusutil.go
- vendor/k8s.io/test-infra/prow/pjutil/filter.go
- vendor/k8s.io/test-infra/prow/plugins/bugzilla/bugzilla.go
- vendor/k8s.io/test-infra/prow/plugins/plugins.go
- vendor/modules.txt
To pick up https://github.com/kubernetes/test-infra/pull/18921
> Update test-infra to 859d15fc4364265500611c3c137d6dd610dafbcf

- pkg/jobconfig/files.go
- pkg/prowgen/prowgen.go
- pkg/prowgen/prowgen_test.go
- pkg/prowgen/testdata/zz_fixture_TestGeneratePeriodicForTest_periodic_for_specific_release.yaml
- pkg/prowgen/testdata/zz_fixture_TestGeneratePostSubmitForTest_fourth.yaml
- pkg/prowgen/testdata/zz_fixture_TestGeneratePresubmitForTest_presubmit_with_job_release_specified.yaml
- test/integration/ci-operator-prowgen/input/config/super/duper/super-duper-job-release.yaml
- test/integration/ci-operator-prowgen/output/jobs/super/duper/super-duper-job-release-periodics.yaml
Add the job-release annotation based on the releases[latest].Candidate.Version
https://issues.redhat.com/browse/DPTP-1309
> Add the job-release annotation

- cmd/ci-secret-generator/main.go
> ci-secret-generator: quality-of-life fixes

- pkg/webreg/webreg.go
Another source of weekly questions.
> webreg: document configuration sharding

- pkg/defaults/defaults.go
- pkg/steps/pod.go
- pkg/steps/pod_test.go
- pkg/steps/release/create_release.go
- pkg/steps/release/import_release.go
- pkg/steps/testdata/zz_fixture_TestPodStepExecution_Pod_run_by_PodStep_fails_so_PodStep_terminates_and_returns_an_error.yaml
- pkg/steps/testdata/zz_fixture_TestPodStepExecution_Pod_run_by_PodStep_succeeds_so_PodStep_terminates_and_returns_no_error.yaml
Reverts openshift/ci-tools#1158
> Revert "ci-operator: create Pods with resolved refs"

- test/e2e/simple.sh
> e2e: don't require vars from the owning job

- pkg/controller/secretsyncer/secretsyncer.go
- pkg/controller/secretsyncer/secretsyncer_test.go
In order to allow secrets that have some keys that come from ci-secret-bootstrap and some that come from a different source secret.
> Secretsyncer: Verify per-key if secret is mangaged by ci-secret-boostrap

- cmd/dptp-controller-manager/main.go
- pkg/controller/test-images-distributor/test_images_distributor.go
- pkg/controller/test-images-distributor/test_images_distributor_test.go
Follow up https://github.com/openshift/ci-tools/pull/1165#issue-473338328
> TestImageDistributor: Add setting for forbidden registries

- cmd/ipi-deprovision/ipi-deprovision.sh
> ipi-deprovision: always try all clusters

- pkg/steps/artifacts.go
> ci-operator: artifacts: don't delete pods, handle missing container

- pkg/steps/release/create_release.go
> ci-operator: show commands in release creation

- cmd/bugzilla-backporter/main.go
- cmd/ci-operator-configresolver/main.go
> simplifypath: handle root elements

- go.mod
- go.sum
- test/integration/repo-init/expected/core-services/prow/02_config/_config.yaml
- vendor/k8s.io/test-infra/experiment/autobumper/bumper/bumper.go
- vendor/k8s.io/test-infra/ghproxy/ghmetrics/ghpath.go
- vendor/k8s.io/test-infra/prow/config/config.go
- vendor/k8s.io/test-infra/prow/config/tide.go
- vendor/k8s.io/test-infra/prow/crier/reporters/github/BUILD.bazel
- vendor/k8s.io/test-infra/prow/crier/reporters/github/reporter.go
- vendor/k8s.io/test-infra/prow/plugins/trigger/pull-request.go
- vendor/modules.txt
> update test-infra vendors

- go.mod
- go.sum
- vendor/k8s.io/test-infra/experiment/autobumper/bumper/bumper.go
- vendor/k8s.io/test-infra/prow/flagutil/kubernetes_cluster_clients.go
- vendor/k8s.io/test-infra/prow/io/iterator.go
- vendor/k8s.io/test-infra/prow/io/opener.go
- vendor/k8s.io/test-infra/prow/plugins/BUILD.bazel
- vendor/k8s.io/test-infra/prow/plugins/config.go
- vendor/k8s.io/test-infra/prow/plugins/override/override.go
- vendor/modules.txt
Mostly to pick up https://github.com/kubernetes/test-infra/pull/19100 so the autobumper works again
> Bump test-infra to a33a9aaf77f7

- images/autobumper/Dockerfile
- images/autoowners/Dockerfile
- images/blocking-issue-creator/Dockerfile
- images/ci-operator-checkconfig/Dockerfile
- images/ci-operator-configresolver/Dockerfile
- images/ci-operator-prowgen/Dockerfile
- images/ci-operator/Dockerfile
- images/config-brancher/Dockerfile
- images/config-change-trigger/Dockerfile
- images/config-shard-validator/Dockerfile
- images/determinize-ci-operator/Dockerfile
- images/determinize-peribolos/Dockerfile
- images/determinize-prow-config/Dockerfile
- images/group-auto-updater/Dockerfile
- images/pj-rehearse/Dockerfile
- images/repo-brancher/Dockerfile
- images/repo-init/Dockerfile
- images/result-aggregator/Dockerfile
- images/sanitize-prow-jobs/Dockerfile
- images/secret-wrapper/Dockerfile
- images/testgrid-config-generator/Dockerfile
This is a no-op in terms of what CI does, but makes things more obvious
when building images locally
> Bump all Dockerfiles to centos:8

- pkg/webreg/webreg.go
Only multi-stage tests support this configuration.
> webreg: fix `dependencies` documentation

- pkg/webreg/webreg.go
These are the ones that were requested last week and some others I can think of
off the top of my head.
https://server-ci-tools-1206.apps.ci.l2s4.p1.openshiftapps.com
> pkg/webreg: add a page with useful links

- pkg/webreg/webreg.go
https://server-ci-tools-1179.apps.ci.l2s4.p1.openshiftapps.com/help/ci-operator#buildroot
> webreg: document build_root images

- cmd/ci-secret-generator/README.md
- cmd/ci-secret-generator/main.go
- cmd/ci-secret-generator/main_test.go
- pkg/bitwarden/bitwarden.go
- pkg/bitwarden/cli.go
- pkg/bitwarden/cli_test.go
- pkg/bitwarden/fake.go
1. Allow user to enter notes for an item
2. Allow user to enter multiple attachments and fields for a single
item
3. Allow user to pass parameters in the config file
> Secret Generator: Improve input mechanism

- pkg/webreg/webreg.go
Based on Steve's original doc. Will follow development in https://github.com/openshift/release/pull/11339.
https://server-ci-tools-1190.apps.ci.l2s4.p1.openshiftapps.com/help/operators
> ci-operator: document operator-sdk testing

- images/ci-secret-generator/Dockerfile
> ci-config-generator: add Dockerfile

- cmd/slack-bot/main.go
- images/slack-bot/Dockerfile
> slack-bot: seed binary, image

- cmd/autotestgridgenerator/main.go
This tool will generate a PR similar to https://github.com/GeoBK/test-infra/pull/3
> Tool to periodically generate testgrids in test-infra

- pkg/steps/rpm_server.go
After switching to ubi8 we got python3 which borked the rpm serving job.
```
error: some steps failed:
* could not run steps: step [serve:rpms] failed: could not wait for RPM repo server to deploy: could not wait for deployment: could not determine current deployment status: the deployment config ci-op-n0mp9vmb/rpm-repo failed with status "ProgressDeadlineExceeded"
```
https://prow.ci.openshift.org/view/gs/origin-ci-test/pr-logs/pull/openshift_kubernetes/350/pull-ci-openshift-kubernetes-master-images/1305758717110652928#1:build-log.txt%3A73
logs showed
```
Traceback (most recent call last):
File "/tmp/tmp.p6rDk9qoF9", line 1, in <module>
import time, threading, socket, socketserver, BaseHTTPServer, SimpleHTTPServer
ModuleNotFoundError: No module named 'BaseHTTPServer'
```
This switches …
> Migrate rpm server to python3

- pkg/steps/rpm_server.go
RHEL7 base images contain only python2 while RHEL8 contains only python3.
> Allow rpm server to run in python2 or 3

- pkg/controller/test-images-distributor/test_images_distributor.go
- pkg/controller/test-images-distributor/test_images_distributor_test.go
> test-images-distributor: copy annotations for ImageStreams

- cmd/ci-operator-configresolver/main.go
https://issues.redhat.com/browse/DPTP-1525
> configresolver: fix nil pointer access

- pkg/webreg/webreg.go
Describe various aspects of contributing to openshift/release, focusing on non-DPTP members (components owners and the like). For now it does not touch stuff like `applyconfig`-ed manifests. When this get merged I'll want to put some links to https://github.com/openshift/release/blob/master/CONTRIBUTING.md.
https://server-ci-tools-1225.apps.ci.l2s4.p1.openshiftapps.com/help/release
> webreg: openshift/release contribution guidelines

- cmd/ci-operator/main.go
We should wait a little longer as we've seen 5s not be enough. We should
also make the error message more user-friendly.
> ci-operator: improve namespace auth wait

- cmd/prow-job-dispatcher/main.go
- cmd/prow-job-dispatcher/main_test.go
- pkg/dispatcher/prometheus.go
- pkg/dispatcher/prometheus_test.go
> prow-job-dispatcher: Add flag -prometheus-days-before

- cmd/ci-operator/main.go
- hack/lib/integration.sh
- pkg/lease/client.go
- pkg/lease/fake.go
- test/e2e/lease.sh
- test/e2e/lease/boskos.yaml
- test/e2e/lease/config.yaml
Provisional version for reference.
> e2e: add an initial version of lease tests

- go.mod
- go.sum
- vendor/k8s.io/test-infra/experiment/autobumper/bumper/bumper.go
- vendor/k8s.io/test-infra/prow/clonerefs/run.go
- vendor/k8s.io/test-infra/prow/config/config.go
- vendor/k8s.io/test-infra/prow/config/jobs.go
- vendor/k8s.io/test-infra/prow/flagutil/kubernetes_cluster_clients.go
- vendor/k8s.io/test-infra/prow/github/BUILD.bazel
- vendor/k8s.io/test-infra/prow/github/client.go
- vendor/k8s.io/test-infra/prow/io/providers/BUILD.bazel
- vendor/k8s.io/test-infra/prow/io/providers/providers.go
- vendor/k8s.io/test-infra/prow/plugins/bugzilla/bugzilla.go
- vendor/k8s.io/test-infra/prow/plugins/config.go
- vendor/k8s.io/test-infra/prow/pod-utils/clone/BUILD.bazel
- vendor/k8s.io/test-infra/prow/pod-utils/clone/clone.go
- vendor/k8s.io/test-infra/prow/pod-utils/clone/format.go
- vendor/k8s.io/test-infra/prow/pod-utils/clone/types.go
- vendor/k8s.io/test-infra/prow/pod-utils/gcs/BUILD.bazel
- vendor/k8s.io/test-infra/prow/pod-utils/gcs/upload.go
- vendor/modules.txt
This PR updates test-infra to include the new state_after_close config
option for the hook bugzilla plugin.
> vendor: update test-infra

- cmd/ci-secret-bootstrap/main.go
- pkg/api/secretbootstrap/secretboostrap.go
- pkg/api/secretbootstrap/secretboostrap_test.go
- pkg/api/secretbootstrap/testdata/TestLoadConfigFromFile/basic_base.yaml
- pkg/api/secretbootstrap/testdata/TestLoadConfigFromFile/dup_key.yaml
Follow up https://github.com/openshift/release/pull/12043#issuecomment-696971732
> Verify duplications in the keys from secret-bootstrap's config

- cmd/ci-operator/main.go
- pkg/defaults/defaults.go
https://issues.redhat.com/browse/DPTP-1564
This will allow us to promote images to a registry running on any cluster.
> Use kubeconfig to promote images

- cmd/ci-operator/main.go
- pkg/api/graph.go
Found while reviewing https://github.com/openshift/ci-tools/pull/1262.
Move `IterateAllEdges` to the graph package and remove some duplicated
code between those two files.
> ci-operator: remove some `cmd`/`pkg` duplication

- cmd/publicize/main.go
> add read/liveness probes in publicize plugin

- pkg/steps/source.go
https://issues.redhat.com/browse/DPTP-1612
> add the failed to extract image content as an infra reason

- pkg/webreg/webreg.go
Follow up https://github.com/openshift/release/pull/12440
> Update the link to app.ci's console

- cmd/ci-operator/main.go
- pkg/steps/lease.go
To prevent races where the ci-ns-ttl controllers cleans up the NS because the ci-operator deleted all pods but plans on creating more
> CI Operator: Bump the namespace active annotation every 10 minutes

- pkg/webreg/webreg.go
Follow up https://coreos.slack.com/archives/CBN38N3MW/p1602104393223300?thread_ts=1602104107.221700&cid=CBN38N3MW
> Fix the doc about build_root.from_repository

- pkg/steps/clusterinstall/template.go
/assign @stevekuznetsov @sanchezl
> templates: capture audit logs

- cmd/blocking-issue-creator/main.go
When running with `--current-release=X --future-release=X` (rare state
when we do not have X+1 config prepared yet), we may end up with
duplicate tokens in the blocker issues:
```
Future Release Branches Frozen For Merging | branch:release-4.7 branch:release-4.7
```
> blocking-issue-creator: avoid duplicate branch tokens

- cmd/ci-operator/main.go
> ci-operator: read custom routes for console

- pkg/api/config.go
- pkg/api/types.go
- pkg/prowgen/prowgen.go
This is for a ppc64le OpenStack cloud located at
Oregon State University's Open Source Lab
> Add new cluster_profile openstack-OSUOSL

- cmd/ci-operator/main.go
> ci-operator: explain why we could not get routes

- cmd/ci-secret-bootstrap/main.go
- cmd/ci-secret-bootstrap/main_test.go
> [ci-secret-bootstrap] fix validation indexes and improve the error message

- pkg/steps/template.go
As requested in https://github.com/openshift/ci-tools/pull/1281.
This is just one of several undocumented pitfalls, which can be added as we
encounter/remember them.
> ci-operator: add "here be dragons" comment

- cmd/ci-secret-bootstrap/main.go
- cmd/ci-secret-bootstrap/main_test.go
- pkg/api/secretbootstrap/secretboostrap.go
Follow up https://github.com/openshift/release/pull/12827#discussion_r505704574
/cc @alvaroaleman @droslean
> ci-secret-bootstrap: Allow RegistryURL in config

- cmd/ci-operator-prowgen/testdata/zz_fixture_postsubmit_TestFromCIOperatorConfigToProwYaml_Input_is_YAML_and_it_is_correctly_processed.yaml
- cmd/ci-operator-prowgen/testdata/zz_fixture_postsubmit_TestFromCIOperatorConfigToProwYaml_Using_a_variant_config__one_test_and_images__one_existing_job._Expect_one_presubmit__pre_post_submit_images_jobs._Existing_job_should_not_be_changed..yaml
- cmd/ci-operator-prowgen/testdata/zz_fixture_postsubmit_TestFromCIOperatorConfigToProwYaml_one_test_and_images__no_previous_jobs._Expect_test_presubmit__pre_post_submit_images_jobs.yaml
- pkg/api/constant.go
- pkg/prowgen/prowgen.go
- pkg/prowgen/testdata/zz_fixture_TestGenerateJobs_Promotion_configuration_causes_promote_job_with_unique_targets.yaml
- test/integration/ci-operator-prowgen/output/jobs/private/duper/private-duper-master-postsubmits.yaml
- test/integration/ci-operator-prowgen/output/jobs/super/duper/super-duper-master-postsubmits.yaml
- test/integration/ci-operator-prowgen/output/jobs/super/duper/super-duper-release-3.11-postsubmits.yaml
- test/integration/repo-init/expected/ci-operator/jobs/openshift/ci-tools/openshift-ci-tools-master-postsubmits.yaml
- test/integration/repo-init/expected/ci-operator/jobs/openshift/origin/openshift-origin-master-postsubmits.yaml
https://issues.redhat.com/browse/DPTP-1564
Require https://github.com/openshift/release/pull/12809/files and another PR for release repo to fix the breaking changes.
> prowgen: mount tokens to promotion jobs

- pkg/steps/multi_stage.go
- pkg/steps/testdata/zz_fixture_TestGeneratePods.yaml
Follow-Up to https://github.com/openshift/release/pull/13044
I will create a docs PR after this merges
> Multi steps: Export KUBEADMIN_PASSWORD_FILE env var

- pkg/steps/multi_stage.go
- pkg/steps/testdata/zz_fixture_TestGeneratePods.yaml
Supersedes https://github.com/openshift/ci-tools/pull/1318
> Steps: Provide a writable kubeconfig location

- cmd/ci-operator/main.go
- pkg/defaults/defaults.go
- pkg/steps/release/promote.go
- pkg/steps/release/promote_test.go
https://issues.redhat.com/browse/DPTP-1564
Require https://github.com/openshift/ci-tools/pull/1305
> Promote images by oc-image-mirror

- pkg/steps/multi_stage.go
- pkg/steps/pod.go
- pkg/steps/testdata/zz_fixture_TestGeneratePods.yaml
Ref: https://issues.redhat.com/browse/DPTP-1669
> Steps: always provide a HOME

- cmd/ci-operator/main.go
Follow up https://coreos.slack.com/archives/GB7NB0CUC/p1603818011190400?thread_ts=1603817965.189700&cid=GB7NB0CUC
> ci-operator: add a flag image-mirror-push-secret

- pkg/slack/events/joblink/link.go
- pkg/slack/events/joblink/link_test.go
> slack-bot: only reply to valid links

- pkg/slack/events/joblink/link.go
- pkg/slack/events/joblink/link_test.go
This is not where we want to end up but at least will keep the handler from being wrong and/or unhelpful with spam when someone links a rehearsal PR.
> slack-bot: be more intelligent about rehearsal jobs

- cmd/ci-operator/main.go
- pkg/defaults/defaults.go
- pkg/steps/release/promote.go
- pkg/steps/release/promote_test.go
will rebase after https://github.com/openshift/ci-tools/pull/1337
require https://github.com/openshift/ci-tools/pull/1338/files
> ci-op: use flag image-mirror-push-secret

- pkg/slack/events/joblink/link.go
> slack-bot: say nothing when there's nothing to say

- cmd/ci-operator-prowgen/testdata/zz_fixture_postsubmit_TestFromCIOperatorConfigToProwYaml_Input_is_YAML_and_it_is_correctly_processed.yaml
- cmd/ci-operator-prowgen/testdata/zz_fixture_postsubmit_TestFromCIOperatorConfigToProwYaml_Using_a_variant_config__one_test_and_images__one_existing_job._Expect_one_presubmit__pre_post_submit_images_jobs._Existing_job_should_not_be_changed..yaml
- cmd/ci-operator-prowgen/testdata/zz_fixture_postsubmit_TestFromCIOperatorConfigToProwYaml_one_test_and_images__no_previous_jobs._Expect_test_presubmit__pre_post_submit_images_jobs.yaml
- pkg/prowgen/prowgen.go
- pkg/prowgen/testdata/zz_fixture_TestGenerateJobs_Promotion_configuration_causes_promote_job_with_unique_targets.yaml
- test/integration/ci-operator-prowgen/output/jobs/private/duper/private-duper-master-postsubmits.yaml
- test/integration/ci-operator-prowgen/output/jobs/super/duper/super-duper-master-postsubmits.yaml
- test/integration/ci-operator-prowgen/output/jobs/super/duper/super-duper-release-3.11-postsubmits.yaml
- test/integration/repo-init/expected/ci-operator/jobs/openshift/ci-tools/openshift-ci-tools-master-postsubmits.yaml
- test/integration/repo-init/expected/ci-operator/jobs/openshift/origin/openshift-origin-master-postsubmits.yaml
/hold
will rebase after https://github.com/openshift/ci-tools/pull/1337 is merged.
> Generate flag --image-mirror-push-secret for promotion jobs

- cmd/ci-secret-generator/main.go
> Secret generator: Add validate-only flag to allow running in presubmit

- cmd/secret-wrapper/main.go
Run a best-effort attempt to upload the $KUBECONFIG when we notice that
it exists. Re-try upload failures forever, expecting that the process
will exit when needed and we should attempt to do the upload until then.
> secret-wrapper: upload $KUBECONFIG when possible

- pkg/rehearse/jobs.go
- pkg/rehearse/jobs_test.go
Will be used by template-deprecation code. Also, add tests.
> rehearse: export UsesConfigMap

- cmd/determinize-ci-operator/main.go
- cmd/determinize-ci-operator/main_test.go
Based on top of https://github.com/openshift/ci-tools/pull/1330
/hold
To check on rehearsals in https://github.com/openshift/release/pull/13217
> Migrate openshift installer upi

- cmd/ci-secret-generator/main.go
> Secret-Generator: Don't require credentials in --validate-only

- pkg/api/types.go
- pkg/defaults/defaults.go
- pkg/lease/client_test.go
- pkg/lease/fake.go
- pkg/steps/lease.go
- pkg/steps/lease_test.go
- pkg/steps/multi_stage.go
Reintroduces https://github.com/openshift/ci-tools/pull/1126.
/hold
Includes/requires https://github.com/openshift/ci-tools/pull/1258.
> pkg/steps/lease: add support for multiple leases

- cmd/ci-secret-generator/main.go
Tested with the config with the troublesome line.
https://github.com/openshift/release/pull/13286/files
> Consider BWContext in dockerconfig on validating

- cmd/generate-registry-metadata/main_test.go
- cmd/pj-rehearse/main.go
- pkg/api/helper/imageextraction.go
- pkg/api/types.go
- pkg/load/agents/registryAgent.go
- pkg/load/load.go
- pkg/load/load_test.go
- pkg/registry/resolver.go
- pkg/registry/resolver_test.go
- pkg/rehearse/jobs_test.go
- pkg/webreg/graphviz_test.go
- test/integration/ci-operator-configresolver/expected/openshift-installer-release-4.2-golang111.json
- test/integration/ci-operator-configresolver/expected/openshift-installer-release-4.2.json
- test/multistage-registry/registry/ipi/install/install/ipi-install-install-ref.yaml
- test/multistage-registry/registry/ipi/ipi-workflow.yaml
- test/multistage-registry/registry/resourcewatcher/OWNERS
- test/multistage-registry/registry/resourcewatcher/resourcewatcher-commands.sh
- test/multistage-registry/registry/resourcewatcher/resourcewatcher-observer.metadata.json
- test/multistage-registry/registry/resourcewatcher/resourcewatcher-observer.yaml
Part of [DPTP-1668](https://issues.redhat.com/browse/DPTP-1668)
> ci-operator: allow configuring observers, serve their config

- pkg/steps/release/release_images.go
> ci-operator: import status tags on imagestreams

- pkg/slack/events/joblink/link.go
> slack-bot: dedupe links to job information

- pkg/steps/artifacts.go
- pkg/steps/artifacts_test.go
- pkg/steps/testdata/zz_fixture_TestGeneratePods.yaml
Docker.io pull limit breaks us: https://prow.ci.openshift.org/view/gs/origin-ci-test/pr-logs/pull/openshift_ci-tools/1379/pull-ci-openshift-ci-tools-master-unit/1324066256050982912#1:build-log.txt%3A34
> Use busybox image from quay.io/prometheus

- images/template-deprecator/Dockerfile
- Add Dockerfile for template-deprecator
- ~Include in autoconfigbrancher image (that automation will need to
maintain the allowlist, too)~
> template-deprecator: images

- cmd/ci-operator/main.go
> ci-op: Add flag image-creator-kubeconfig

- cmd/pj-rehearse/main.go
See for example https://prow.ci.openshift.org/view/gs/origin-ci-test/pr-logs/pull/openshift_release/12990/pull-ci-openshift-release-master-pj-rehearse/1324721217449496576, a single import didn't succeed and now we do not rehearse anything. Instead, store the error and try to rehearse.
> PJ rehearse: Try rehearsing even when there are setup failures

- cmd/dptp-controller-manager/main.go
- pkg/api/domain.go
- pkg/controller/registrysyncer/registrysyncer.go
- pkg/controller/registrysyncer/registrysyncer_test.go
- pkg/testhelper/testhelper.go
- pkg/testhelper/testhelper_test.go
https://issues.redhat.com/browse/DPTP-1656
> dptp-cm: add registrysyncer

- cmd/ci-operator/main.go
Avoids failures like this: https://prow.ci.openshift.org/view/gs/origin-ci-test/pr-logs/pull/openshift_ci-tools/1397/pull-ci-openshift-ci-tools-master-e2e/1325975202122698752#1:build-log.txt%3A89
Being able to get the project doesn't mean the RBAC is finished setting
up.
> Verify via SelfSubjectAccessReview that namespace is ready

- pkg/webreg/webreg.go
Mostly intended for https://steps.ci.openshift.org/ci-operator-reference
> Add javascript to allow highlighting multiple lines

- cmd/dptp-controller-manager/main.go
- cmd/dptp-controller-manager/main_test.go
- pkg/controller/registrysyncer/registrysyncer.go
- pkg/controller/registrysyncer/registrysyncer_test.go
https://issues.redhat.com/browse/DPTP-1656?focusedCommentId=15345756&page=com.atlassian.jira.plugin.system.issuetabpanels%3Acomment-tabpanel#comment-15345756
/hold
Testing it on my PC ...
> registry_syncer controller: Implement filters

- cmd/dptp-controller-manager/main.go
- pkg/controller/registrysyncer/registrysyncer.go
- pkg/controller/test-images-distributor/test_images_distributor.go
- pkg/controller/test-images-distributor/test_images_distributor_test.go
- pkg/controller/util/metrics.go
> Use metrics in the registrysyncer controller

- cmd/template-deprecator/main.go
- pkg/deprecatetemplates/allowlist.go
- pkg/deprecatetemplates/allowlist_test.go
- pkg/deprecatetemplates/enforcer.go
- pkg/deprecatetemplates/enforcer_test.go
This was slightly problematic to unit-test, b/c there is an annoying
difference between "usefully storted stats" and "stable sorted stats in
the presence of various equalities".
> template-deprecator: --stats

- cmd/prow-job-dispatcher/README.md
- hack/run-prow-job-dispatcher.sh
> Doc how to run prow-job-dispatcher locally

- cmd/template-deprecator/main.go
- pkg/deprecatetemplates/allowlist.go
- pkg/deprecatetemplates/allowlist_test.go
- pkg/deprecatetemplates/enforcer.go
- pkg/deprecatetemplates/enforcer_test.go
> template-deprecator: allow suppressing totals, handle no unknowns

- hack/debug-e2e.sh
> hack: add a script to debug e2e runs

- pkg/steps/artifacts.go
Seen here: https://prow.ci.openshift.org/view/gs/origin-ci-test/pr-logs/pull/openshift_ci-tools/1413/pull-ci-openshift-ci-tools-master-e2e/1329158528216076288#1:build-log.txt%3A73
> Artifacts: Revert back to unlocking on channel write

- cmd/ci-operator-configresolver/main.go
- pkg/load/load.go
https://issues.redhat.com/browse/DPTP-1637
> CI operator: Print error message from config resolver

- cmd/repo-brancher/main.go
This PR factors out the git command execution into a func that does
retrying. It also moves all the command-related logging into that func.
ref https://issues.redhat.com/browse/DPTP-1625
> Repo brancher: Retry git commands

- pkg/api/config.go
- pkg/api/config_test.go
- pkg/api/types.go
- pkg/defaults/defaults.go
- pkg/defaults/defaults_test.go
- pkg/registry/resolver.go
- pkg/registry/resolver_test.go
- pkg/steps/multi_stage.go
- pkg/steps/multi_stage_test.go
- pkg/webreg/zz_generated.ci_operator_reference.go
- test/e2e/lease/config.yaml
- test/e2e/lease/step-registry/check-leases/check-leases-commands.sh
- test/e2e/lease/step-registry/check-leases/check-leases-ref.yaml
Documented in https://github.com/openshift/ci-docs/pull/13.
> ci-operator: add option to configure leases

- pkg/controller/registrysyncer/registrysyncer.go
https://issues.redhat.com/browse/DPTP-1779
/cc @alvaroaleman @petr-muller
> registrySyncer: ensure the created imagestream to exist in cache

- cmd/dptp-controller-manager/main.go
- pkg/controller/registrysyncer/registrysyncer.go
- pkg/controller/test-images-distributor/test_images_distributor.go
- pkg/controller/util/metrics.go
> imagestream_successful_import_count: add label of imagestream name

- pkg/api/domain.go
- pkg/controller/registrysyncer/registrysyncer.go
- pkg/controller/registrysyncer/registrysyncer_test.go
> registrySyncer: No importing back

- pkg/steps/multi_stage.go
- pkg/steps/pod.go
- pkg/steps/template.go
Addresses [DPTP-1785](https://issues.redhat.com/browse/DPTP-1785)
> ci-operator: use correct context on pod delete

- pkg/controller/registrysyncer/registrysyncer.go
- pkg/controller/registrysyncer/registrysyncer_test.go
The queue got longer over timve.
https://user-images.githubusercontent.com/4013349/99980877-b9b57580-2d76-11eb-8c50-e3f0327c20e0.png
> registrySyncer: #workers=100

- pkg/steps/artifacts.go
ref: https://issues.redhat.com/browse/DPTP-1792
> Atifacts: Nil check channel before closing and add debug output

- pkg/defaults/defaults.go
- pkg/defaults/defaults_test.go
- pkg/validation/test.go
- pkg/validation/test_test.go
- test/e2e/lease.sh
- test/e2e/lease/boskos.yaml
- test/e2e/lease/config.yaml
- test/e2e/lease/step-registry/declare-and-check-leases/declare-and-check-leases-commands.sh
- test/e2e/lease/step-registry/declare-and-check-leases/declare-and-check-leases-ref.yaml
Includes https://github.com/openshift/ci-tools/pull/1455.
> pkg/defaults: add step leases to tests

- pkg/controller/registrysyncer/registrysyncer.go
- pkg/controller/registrysyncer/registrysyncer_test.go
- cover the case: the older IS is deleted. This is actually what happens in our production. IS is synced from api.ci to app.ci and then the one on api.ci is deleted. When reconcile, the one on app.ci becomes the sourceIS because it is newer. But we cannot enter the deleting logic because the one on app.ci is not with deleteTimestamp. The fix here is: if IS on any cluster has a deleteTimestamp, we remove the finalizer (if existing) for IS on all clusters and delete the ones with deleteTimestamp.
- adding logs for deleting IS and removing finalizer
> registrySyncer: delete IS when it is deleted on any cluster

- cmd/ci-operator/main.go
> ci-operator: clean up scheme init

- cmd/ci-operator/main.go
- pkg/api/constant.go
> ci-operator: allow passing a GCS upload secret

- pkg/slack/events/joblink/link.go
> slack-bot: fix rehearsal PR link

- pkg/controller/registrysyncer/registrysyncer.go
- pkg/controller/registrysyncer/registrysyncer_test.go
* replace ISImport with ISTag: the import will be created by openshift. Unlike imports, the creation of isTag will be async. This will help to digest the queue. The disadvantage is that it is harder to check the import status (See the TODO).
* Copy the annotation over on the isTags: This is why we do this PR. The release controller replies on the annotation on isTags to do things.
* if found soft-delete annotation on any IS, delete the IS on all clusters. https://github.com/openshift/release-controller/pull/233
> registrysyncer: use isTag instead of isImport

- pkg/steps/source.go
- pkg/steps/testdata/zz_fixture_TestCreateBuild_basic_options_for_a_presubmit.yaml
- pkg/steps/testdata/zz_fixture_TestCreateBuild_with_OAuth_token.yaml
- pkg/steps/testdata/zz_fixture_TestCreateBuild_with_a_path_alias.yaml
- pkg/steps/testdata/zz_fixture_TestCreateBuild_with_a_pull_secret.yaml
- pkg/steps/testdata/zz_fixture_TestCreateBuild_with_extra_refs.yaml
- pkg/steps/testdata/zz_fixture_TestCreateBuild_with_extra_refs_setting_workdir_and_path_alias.yaml
- pkg/steps/testdata/zz_fixture_TestCreateBuild_with_ssh_key.yaml
> ci-operator: throughput limit xargs on clone

- cmd/ipi-deprovision/ipi-deprovision.sh
> ipi-deprovision: use the correct artifact location

- cmd/ipi-deprovision/ipi-deprovision.sh
> ipi-deprovision: fix more env issues

- pkg/api/constant.go
- pkg/controller/registrysyncer/registrysyncer.go
- pkg/controller/registrysyncer/registrysyncer_test.go
- pkg/util/imagestreamtagmapper/imagestreamtagmapper.go
- pkg/util/imagestreamtagmapper/imagestreamtagmapper_test.go
Follow up https://github.com/openshift/release-controller/pull/233
/hold
will rebase after https://github.com/openshift/ci-tools/pull/1437 is merged.
> registrySyncer: delete isTags when they are soft-deleted

- pkg/defaults/defaults.go
- pkg/defaults/defaults_test.go
- pkg/steps/source_test.go
> ci-operator: update to new clonerefs location

- pkg/defaults/defaults.go
- pkg/defaults/defaults_test.go
- pkg/steps/source.go
- pkg/steps/source_test.go
- pkg/steps/testdata/zz_fixture_TestCreateBuild_basic_options_for_a_presubmit.yaml
- pkg/steps/testdata/zz_fixture_TestCreateBuild_with_OAuth_token.yaml
- pkg/steps/testdata/zz_fixture_TestCreateBuild_with_a_path_alias.yaml
- pkg/steps/testdata/zz_fixture_TestCreateBuild_with_a_pull_secret.yaml
- pkg/steps/testdata/zz_fixture_TestCreateBuild_with_extra_refs.yaml
- pkg/steps/testdata/zz_fixture_TestCreateBuild_with_extra_refs_setting_workdir_and_path_alias.yaml
- pkg/steps/testdata/zz_fixture_TestCreateBuild_with_ssh_key.yaml
> ci-operator: use a managed clonerefs image

- pkg/defaults/defaults.go
- pkg/defaults/defaults_test.go
> ci-operator: use the managed-clonerefs image

- cmd/ci-operator/main.go
So the likelyhood of the NS expiring and thus deleted in after we upserted it is reduced
> CI operator: Hearbeat namespace before creating secrets or rbac

- cmd/ipi-deprovision/ipi-deprovision.sh
Prevents failures such as:
```
ls: cannot access '/logs/artifacts/deprovision/*/failure': No such file or directory
```
https://prow.ci.openshift.org/view/gs/origin-ci-test/logs/periodic-ipi-deprovision/1336292322861649920
> ipi-deprovision: fix failure report

- Makefile
> make: add simple targets to streamline e2e

- pkg/release/candidate/client.go
- pkg/release/official/client.go
- pkg/release/prerelease/client.go
> ci-operator: provide better errors when failing to resolve releases

- pkg/api/types.go
- pkg/registry/resolver.go
- pkg/registry/resolver_test.go
- pkg/steps/multi_stage.go
- pkg/steps/multi_stage_test.go
- pkg/webreg/zz_generated.ci_operator_reference.go
- test/e2e/multi-stage.sh
- test/e2e/multi-stage/best-effort.yaml
Implements https://issues.redhat.com/browse/DPTP-1799
> ci-operator: allow marking post steps as best-effort

- pkg/api/domain.go
- pkg/api/domain_test.go
- pkg/steps/release/promote_test.go
- pkg/steps/testdata/zz_fixture_TestGeneratePods.yaml
/hold
* need to rebase after https://github.com/openshift/ci-tools/pull/1502 is merged.
* Will merge with other clients
https://issues.redhat.com/browse/DPTP-1658
> Promote images to app.ci

- pkg/api/domain.go
- pkg/api/domain_test.go
- pkg/steps/release/promote_test.go
- pkg/steps/testdata/zz_fixture_TestGeneratePods.yaml
This reverts commit 219a3b8762d7b27d53bc30f80a10dd57a0116fb6.
> Revert "Promote images to app.ci"

- cmd/registry-replacer/main.go
- cmd/registry-replacer/main_test.go
https://issues.redhat.com/browse/DPTP-1658
> registry-replacer: recognize domain registry.ci.openshift.org

- pkg/controller/test-images-distributor/test_images_distributor.go
`buildClusterManagers`  does not contain registry cluster.
When `app.ci` is the registry cluster, the client isn't in the map `r.buildClusterClients`.
Tested locally with or without `--registry-cluster-name=app.ci`.
> Fix test_images_distributor when app.ci is registry cluster

- go.mod
- go.sum
- vendor/k8s.io/test-infra/prow/flagutil/github.go
- vendor/k8s.io/test-infra/prow/git/v2/client_factory.go
- vendor/k8s.io/test-infra/prow/pod-utils/decorate/podspec.go
- vendor/modules.txt
Needed for [DPTP-1819](https://issues.redhat.com/browse/DPTP-1819)
> vendor: bump test-infra

- cmd/autobumper/main.go
> autobumper: put credentials back in remote for MakeGitCommit

- images/cvp-trigger/Dockerfile
> Add Dockerfile for cvp-trigger

- pkg/controller/registrysyncer/registrysyncer.go
9 hits in last 3 days, all on api.ci.
> Wait for 10 secs for the IS to appear after creating it

- pkg/controller/test-images-distributor/test_images_distributor.go
> test-images-distributor: no distribution to api.ci

- pkg/prowgen/prowgen.go
Adding the missing cluster profile
> Adding the cluster profile for libvirt ppc64le

- pkg/webreg/webreg.go
Address @alvaroaleman 's suggestion from https://github.com/openshift/ci-tools/pull/1522#discussion_r541125842
- avoid parsing it again on each request
- detect bad template on unit tests (by parsing in init()) instead of
during runtime
Unfortunately it's not as straighforward as I'd like - the base template (optionally!) consumes docs/chains/workflows which are only available on handle time from the configagent, so that content needs to be filled in at handle time.
Test deployment: https://server-ci-tools-1553.apps.ci.l2s4.p1.openshiftapps.com
/cc @alvaroaleman @AlexNPavel
> webreg: parse base template in init()

- pkg/webreg/webreg.go
Address https://github.com/openshift/ci-tools/pull/1522#issuecomment-743337546
[before](https://steps.ci.openshift.org/reference/ipi-install-rbac) | [after](https://server-ci-tools-1552.apps.ci.l2s4.p1.openshiftapps.com/reference/ipi-install-rbac)
> webreg: tune spacing for h3

- images/ci-secret-generator/Dockerfile
- images/ci-secret-generator/google-cloud-sdk.repo
Needed to run it in a job which in turn is needed for https://issues.redhat.com/browse/DPTP-1763
> Secret generator: Install gcloud CLI

- pkg/steps/template.go
> ci-operator: log image used to run pods

- pkg/steps/release/import_release.go
replaces https://github.com/openshift/ci-tools/pull/1566
> Import: Add pull secret to $HOME/.docker

- cmd/dptp-controller-manager/main.go
- hack/run-dptp-controller-manager.sh
- pkg/controller/serviceaccount_secret_refresher/serviceaccount_secret_refresher.go
- pkg/controller/serviceaccount_secret_refresher/serviceaccount_secret_refresher_test.go
Needed for https://issues.redhat.com/browse/DPTP-1763
> Add controller to rotate old serviceaccount secrets

- pkg/util/rbacs_test.go
/assign @droslean 
Sample: https://prow.ci.openshift.org/view/gs/origin-ci-test/pr-logs/pull/openshift_ci-tools/1536/pull-ci-openshift-ci-tools-master-unit/1346206349469421568
> TestCreateRBACs: Fix race

- pkg/webreg/webreg.go
Add a new "Environment" section to the step page, containing a table
with different elements that expose something to the step payload as
an environmental variable:
- dependencies
- parameters
- leases
Example deployment: https://server-ci-tools-1568.apps.ci.l2s4.p1.openshiftapps.com/
Part of [DPTP-1652](https://issues.redhat.com/browse/DPTP-1652)
> webreg: expose step environment variables

- test/e2e/simple/e2e_test.go
> e2e: add a literal resolution test for release-controller image

- test/e2e/framework/test.go
> e2e: lock around access to testing logger

- hack/test-go.sh
> test: write out test JSON

- test/e2e/framework/framework.go
If we do not wait for the helper process to exit and the goroutine
watching it to finish, we risk having that goroutine use the *testing.T
after the test is complete, which leads to a data race.
> e2e: framework: wait for helper process exit in cleanup

- pkg/controller/serviceaccount_secret_refresher/serviceaccount_secret_refresher.go
I blatantly plagiarized what registrysyncer does (https://github.com/openshift/ci-tools/pull/1475/commits/daa03ade208a7e041a297d9ead662a321ee962a2).
Avoid polluting the logs with:
```
failed to update ServiceAccount: Operation cannot be fulfilled on serviceaccounts .*: the object has been modified; please apply your changes to the latest version and try again
```
Also fixed a typo.
/cc @alvaroaleman @hongkailiu
> sa_secret_refresher: tolerate conflics

- cmd/ci-secret-bootstrap/main.go
- cmd/ci-secret-bootstrap/main_test.go
> [DPTP-1847] add key name in errors while constructing the secrets

- test/e2e/framework/test.go
> e2e: make sure we're as parallel as possible

- cmd/ci-secret-bootstrap/main.go
- cmd/dptp-controller-manager/main.go
- cmd/pj-rehearse/main.go
- pkg/util/client.go
- pkg/util/client_test.go
Needed for https://issues.redhat.com/browse/DPTP-1763
> DPDP CM: Exit on kubeconfig changes to pick them up

- pkg/webreg/webreg.go
Expose additional information about steps in the UI
Test deployment eventually shows up at: https://server-ci-tools-1596.apps.ci.l2s4.p1.openshiftapps.com
Example: https://server-ci-tools-1596.apps.ci.l2s4.p1.openshiftapps.com/reference/gather-loki#properties
> webreg: show steps' properties in UI

- test/e2e/framework/ci-operator.go
> e2e: hold on to ci-operator logs as artifacts

- cmd/applyconfig/applyconfig.go
Needs https://github.com/openshift/release/pull/14762 first to bring the repo into the conformant state.
/hold
> applyconfig: use best detected dryrun by default

- cmd/autobumper/main.go
- cmd/autoconfigbrancher/main.go
- cmd/autoowners/main.go
- cmd/autoperibolossync/main.go
- cmd/registry-replacer/main.go
For https://issues.redhat.com/browse/DPTP-1852
> Fix PR-Creating tools

- cmd/ci-secret-bootstrap/main.go
- cmd/ci-secret-bootstrap/main_test.go
> [DPTP-1846] ci-secret-bootstrap: output valid yaml data when running on dry-run mode

- pkg/webreg/webreg.go
Link to timeout doc from https://github.com/openshift/ci-docs/pull/47
/hold
Needs to wait for the above PR and possibly adjusted if the anchor links change.
> webreg: doc links for timeout properties

- pkg/api/domain.go
- pkg/api/domain_test.go
- pkg/prowgen/testdata/zz_fixture_TestGeneratePodSpecTemplate_testcase_0.yaml
- test/integration/ci-operator-prowgen/input/jobs/super/duper/super-duper-master-periodics.yaml
- test/integration/ci-operator-prowgen/output/jobs/private/duper/private-duper-master-periodics.yaml
- test/integration/ci-operator-prowgen/output/jobs/private/duper/private-duper-master-presubmits.yaml
- test/integration/ci-operator-prowgen/output/jobs/super/duper/super-duper-master-periodics.yaml
- test/integration/ci-operator-prowgen/output/jobs/super/duper/super-duper-master-presubmits.yaml
- test/integration/pj-rehearse/candidate/ci-operator/jobs/super/duper/super-duper-periodics.yaml
- test/integration/pj-rehearse/expected.yaml
- test/integration/pj-rehearse/master/ci-operator/jobs/super/duper/super-duper-periodics.yaml
Required by https://github.com/openshift/release/pull/14998
> prowgen: use rpms routes on app.ci

- cmd/dptp-controller-manager/main.go
- pkg/api/constant.go
- pkg/controller/imagepusher/imagepusher.go
- pkg/controller/imagepusher/imagepusher_test.go
- pkg/controller/registrysyncer/registrysyncer.go
- pkg/controller/registrysyncer/registrysyncer_test.go
- pkg/controller/util/secret.go
- pkg/controller/util/secret_test.go
https://issues.redhat.com/browse/DPTP-1856
> dptp-cm: add controller image_pusher

- cmd/dptp-controller-manager/main.go
- pkg/controller/registrysyncer/registrysyncer.go
- pkg/controller/registrysyncer/registrysyncer_test.go
- pkg/controller/test-images-distributor/test_images_distributor.go
- pkg/controller/test-images-distributor/test_images_distributor_test.go
https://issues.redhat.com/browse/DPTP-1845?focusedCommentId=15649043&page=com.atlassian.jira.plugin.system.issuetabpanels%3Acomment-tabpanel#comment-15649043
I will remove the flags after
* This PR is merged.
* The flags in the deployement is removed.
> dptp-cm: copy pull secret from ci namespace

- cmd/ci-operator/main.go
In the newest version of OCP it seems like image pull secret creation
can take some time and if we create Pods using the default service
accounts before those pull secrets are ready for them, the Pods are
doomed to never work.
> ci-operator: wait for image pull secrets to exist

- cmd/dptp-controller-manager/main.go
https://issues.redhat.com/browse/DPTP-1845?focusedCommentId=15649043&page=com.atlassian.jira.plugin.system.issuetabpanels%3Acomment-tabpanel#comment-15649043
/hold
require https://github.com/openshift/release/pull/15105
need rebase after https://github.com/openshift/ci-tools/pull/1625 gets merged
> dptp-cm: remove 2 unused flags

- pkg/steps/release/create_release.go
- pkg/steps/release/import_release.go
https://search.ci.openshift.org/?search=release-release-images-latest&maxAge=48h&context=1&type=bug%2Bjunit&name=&maxMatches=5&maxBytes=20971520&groupBy=job
Reverts openshift/ci-tools#1621
> Revert "ci-operator: release: use a configmap for data transfer"

- pkg/steps/output_image_tag.go
> ci-operator: use a more resilient upsert on output ist

- cmd/ci-operator/main.go
- pkg/api/config.go
- pkg/defaults/defaults.go
- pkg/defaults/defaults_test.go
- pkg/steps/artifacts.go
- pkg/steps/artifacts_test.go
- pkg/steps/multi_stage.go
- pkg/steps/multi_stage_test.go
- pkg/steps/pod.go
- pkg/steps/release/create_release.go
- pkg/steps/release/import_release.go
- pkg/steps/testdata/zz_fixture_TestAddPodUtils.yaml
> ci-operator: optionally use pod-utils to push artifacts up

- pkg/validation/config.go
- pkg/validation/test_test.go
We are going to use this for CoreOS builds/testing.
xref https://github.com/openshift/os/issues/417
> validation: Support devices.kubevirt.io/kvm

- pkg/prowgen/prowgen.go
- test/integration/repo-init/expected/ci-operator/jobs/openshift/ci-tools/openshift-ci-tools-master-postsubmits.yaml
- test/integration/repo-init/expected/ci-operator/jobs/openshift/ci-tools/openshift-ci-tools-master-presubmits.yaml
> prowgen: use pod-utils for ci-tools repo

- cmd/ci-operator/main.go
> ci-operator: fix typo

- pkg/load/load.go
> config/load: do something with the VERSION file

- go.mod
- go.sum
- test/integration/repo-init/expected/core-services/prow/02_config/_config.yaml
- vendor/k8s.io/test-infra/experiment/autobumper/bumper/bumper.go
- vendor/k8s.io/test-infra/experiment/image-bumper/bumper/bumper.go
- vendor/k8s.io/test-infra/prow/apis/prowjobs/v1/types.go
- vendor/k8s.io/test-infra/prow/config/branch_protection.go
- vendor/k8s.io/test-infra/prow/config/config.go
- vendor/k8s.io/test-infra/prow/config/jobs.go
- vendor/k8s.io/test-infra/prow/plugins/config.go
- vendor/k8s.io/test-infra/prow/plugins/verify-owners/verify-owners.go
- vendor/k8s.io/test-infra/prow/repoowners/repoowners.go
- vendor/k8s.io/test-infra/robots/pr-creator/updater/updater.go
- vendor/modules.txt
Mostly to get https://github.com/kubernetes/test-infra/pull/20563
> Bump test-infra to bc8196c5c352

- cmd/ipi-deprovision/ipi-deprovision.sh
`$ARTIFACTS/deprovision` did not exist when there was no cluster to clean up
> deprovisioner: do not fail when there is nothing to cleanup

- cmd/backport-verifier/main.go
- cmd/backport-verifier/server.go
- cmd/backport-verifier/server_test.go
- images/backport-verifier/Dockerfile
implements https://issues.redhat.com/browse/DPTP-1842
/cc @sttts
> backport-verifier: a new Prow plugin for forks

- cmd/backport-verifier/server.go
- cmd/backport-verifier/server_test.go
We want to be able to turn on this plugin for the entire org, so we
can't be spamming a comment for unconfigured repositories unless the
user asked us to do a backport verification explicitly.
> backport-verifier: only comment about missing config when explicit

- cmd/backport-verifier/server.go
- cmd/backport-verifier/server_test.go
/assign @sttts 
Part of [DPTP-1842](https://issues.redhat.com/browse/DPTP-1842)
> backport-verifier: update wording to be more clear

- cmd/backport-verifier/server.go
- cmd/backport-verifier/server_test.go
> backport-verifier: print commit messages in output

- cmd/prow-job-dispatcher/main.go
- cmd/prow-job-dispatcher/main_test.go
- hack/run-prow-job-dispatcher.sh
- images/prowjobdispatcher/Dockerfile
- pkg/dispatcher/prometheus.go
https://issues.redhat.com/browse/DPTP-1765
> prow-job-dispatcher: add a flag to create a PR

- go.mod
- go.sum
- vendor/modules.txt
- vendor/sigs.k8s.io/controller-runtime/pkg/internal/controller/controller.go
- vendor/sigs.k8s.io/controller-runtime/pkg/log/deleg.go
- vendor/sigs.k8s.io/controller-runtime/pkg/manager/internal.go
- vendor/sigs.k8s.io/controller-runtime/pkg/source/source.go
We need https://github.com/kubernetes-sigs/controller-runtime/pull/1345,
otherwise souce.Channel doesn't do anything which renders the
promotion_job_creator useless as it never gets triggered.
> Update controller-runtime to fix source.Channel

- cmd/serviceaccount-secret-rotation-trigger/README.md
- cmd/serviceaccount-secret-rotation-trigger/main.go
- cmd/serviceaccount-secret-rotation-trigger/main_test.go
- images/serviceaccount-secret-rotation-trigger/Dockerfile
- pkg/controller/serviceaccount_secret_refresher/serviceaccount_secret_refresher.go
- pkg/controller/serviceaccount_secret_refresher/serviceaccount_secret_refresher_test.go
Ref https://issues.redhat.com/browse/DPTP-1897
> Add tooling to trigger SA secret rotation

- images/prowjobdispatcher/Dockerfile
> Fix the entrypoint of the prow-job-dispatch image

- pkg/steps/release/promote.go
- pkg/steps/release/testdata/zz_fixture_TestGetPromotionPod_basic_case.yaml
> Use ocp/4.8:cli image for promotion pod

- cmd/serviceaccount-secret-rotation-trigger/main.go
Ref https://issues.redhat.com/browse/DPTP-1897
Otherwise the run always fails with conflicts
> SA secret rotation trigger: Use patch to avoid conflicts

- cmd/private-prow-configs-mirror/main_test.go
- go.mod
- go.sum
- pkg/steps/artifacts_test.go
- vendor/k8s.io/test-infra/experiment/autobumper/bumper/bumper.go
- vendor/k8s.io/test-infra/prow/apis/prowjobs/v1/types.go
- vendor/k8s.io/test-infra/prow/apis/prowjobs/v1/zz_generated.deepcopy.go
- vendor/k8s.io/test-infra/prow/config/branch_protection.go
- vendor/k8s.io/test-infra/prow/config/prow-config-documented.yaml
- vendor/k8s.io/test-infra/prow/flagutil/BUILD.bazel
- vendor/k8s.io/test-infra/prow/flagutil/github.go
- vendor/k8s.io/test-infra/prow/github/client.go
- vendor/k8s.io/test-infra/prow/github/fakegithub/fakegithub.go
- vendor/k8s.io/test-infra/prow/github/types.go
- vendor/k8s.io/test-infra/prow/plugins/config.go
- vendor/k8s.io/test-infra/prow/plugins/jira/BUILD.bazel
- vendor/k8s.io/test-infra/prow/plugins/jira/jira.go
- vendor/k8s.io/test-infra/prow/plugins/plugin-config-documented.yaml
- vendor/k8s.io/test-infra/prow/pod-utils/decorate/podspec.go
- vendor/k8s.io/test-infra/prow/spyglass/artifacts.go
- vendor/modules.txt
So we can use https://github.com/kubernetes/test-infra/pull/20788
> Bump test-infra to 5e490580b8a6

- cmd/prow-job-dispatcher/main.go
- hack/run-prow-job-dispatcher.sh
- follow up https://github.com/openshift/ci-tools/pull/1651#discussion_r569128414
- fix some bugs found from local test
The PR created from local test with this PR:
https://github.com/openshift/release/pull/15613
> prow-job-dispatcher: fix the PR creation

- cmd/ci-operator/main.go
https://issues.redhat.com/browse/DPTP-1913
> ci-operator: add flag --lease-server-username-file

- cmd/autoconfigbrancher/main.go
- images/autoconfigbrancher/Dockerfile
/cc @openshift/openshift-team-developer-productivity-test-platform @alvaroaleman 
follow-up https://github.com/openshift/release/pull/15700
> [DPTP-1433] Add the registry-replacer step in the autoconfigbrancher tool

- cmd/ci-secret-bootstrap/main.go
> [DPTP-1909] Improve logging of unused elements in bw items

- cmd/backport-verifier/main.go
- cmd/bugzilla-backporter/main.go
- cmd/ci-secret-generator/main.go
- cmd/determinize-peribolos/main.go
- cmd/dptp-controller-manager/main.go
- cmd/generate-registry-metadata/main.go
- cmd/group-auto-updater/main.go
- cmd/private-org-peribolos-sync/main.go
- cmd/prow-job-dispatcher/main.go
- cmd/publicize/main.go
- cmd/release-job-migrator/main.go
- cmd/sanitize-prow-jobs/main.go
- cmd/testgrid-config-generator/main.go
- pkg/api/secretbootstrap/secretboostrap.go
- pkg/config/load.go
- pkg/config/whitelist.go
- pkg/controller/secretsyncer/config/config.go
- pkg/deprecatetemplates/allowlist.go
- pkg/dispatcher/config.go
- pkg/jobconfig/files.go
- pkg/load/load.go
- pkg/load/load_test.go
- pkg/rehearse/configmaps.go
- pkg/util/gzip/gzip.go
> [DPTP-1902] Add the ability to load gzipped ci-operator configuration

- cmd/ci-operator/main.go
- cmd/ci-operator/main_test.go
- pkg/lease/client.go
Follow up https://github.com/openshift/ci-tools/pull/1676#issuecomment-776017085
/cc @petr-muller @alvaroaleman
> ci-operator: support credentials file for boskos

- pkg/registry/resolver.go
- pkg/registry/resolver_test.go
While technically correct according to the [specification][0],
completely overriding the workflow fields is sometimes not what is
desired when fields are added to the test in the `ci-operator`
configuration file.  [DPTP-1824][1] documents one of these cases: when
an `env` section is added to a test, the intent is likely to augment the
workflow section, but it is instead completely overridden.
The behavior of configuration resolution is changed so that the two
sections are now merged for list and dictionary fields, namely:
- `env`/`TestEnvironment`: parameters in the test override those in the
workflow if they target the same environment variable.  Otherwise,
the resulting parameter list is the combination of both sections.  An
existing value can be cleared by setting `default` to the …
> pkg/registry: merge test/workflow list/dict fields

- cmd/cvp-trigger/main.go
- test/integration/cvp-trigger/periodic-ipi-deprovision.expected
> cvp-trigger: supply parameters to namespace hash

- cmd/applyconfig/applyconfig.go
- cmd/applyconfig/applyconfig_test.go
https://prow.ci.openshift.org/view/gs/origin-ci-test/pr-logs/pull/openshift_release/15799/pull-ci-openshift-release-master-app-ci-config-dry/1360237065387642880#1:build-log.txt%3A100
/cc @droslean
> applyconfig: more robust missing namespace detection

- pkg/prowgen/prowgen.go
- pkg/prowgen/testdata/zz_fixture_TestGeneratePodSpecMultiStage_aws_cluster_profile.yaml
- pkg/prowgen/testdata/zz_fixture_TestGeneratePodSpecMultiStage_aws_cpaas_cluster_profile.yaml
- pkg/prowgen/testdata/zz_fixture_TestGeneratePodSpecTemplate_testcase_1.yaml
- pkg/prowgen/testdata/zz_fixture_TestGeneratePodSpecTemplate_testcase_2.yaml
- pkg/prowgen/testdata/zz_fixture_TestGeneratePodSpecTemplate_testcase_3.yaml
- pkg/prowgen/testdata/zz_fixture_TestGeneratePodSpecTemplate_testcase_4.yaml
- pkg/prowgen/testdata/zz_fixture_TestGeneratePodSpecTemplate_testcase_5.yaml
- test/integration/repo-init/expected/ci-operator/jobs/org/repo/org-repo-master-presubmits.yaml
- test/integration/repo-init/expected/ci-operator/jobs/org/third/org-third-nonstandard-presubmits.yaml
https://issues.redhat.com/browse/DPTP-1913
/hold
require
https://github.com/openshift/ci-tools/pull/1675
> prowgen: generate flag --lease-server-credentials-file

- cmd/ci-operator/main.go
ci-operator was setting up SSAR and pull secrets between the namespace
creation and setting up the annotations, so if one of them failed, the
annotations were not set and we leak the namespace.
> ci-operator: set TTL annotations before everything else

- pkg/slack/events/mention/mention.go
- pkg/slack/events/mention/testdata/zz_fixture_TestRespnseFor_unrelated_text_gets_a_sad_response.yaml
> slack-bot: show off everything we can do when user asks

- go.mod
> Upgrade to go 1.16

- go.sum
> vendor: fix for 1.16

- cmd/secret-wrapper/main.go
- test/secret-wrapper-integration.sh
There are a number of changes we make to the environment of the process
under test. Some occur in the `secret-wrapper` tool, while some form an
ugly Bash preable. As the content of these changes continues to grow and
become more complex, we should aim to make all of them in the Go tool.
/cc @alvaroaleman 
This is backwards  compatible and will work with *both* `secret-wrapper` and the shell. I'll remove the shell later.
> secret-wrapper: handle writable home

- cmd/secret-wrapper/main.go
- test/secret-wrapper-integration.sh
As we upload `$KUBECONFIG` as soon as it's available and some consumers
of the `$SHARED_DIR` (observers) will want to be able to consume it as
soon as it's uploaded, we need to handle the case where it does not
exist at the moment that a process starts reading the `$SHARED_DIR`, and
furthermore we can handle the creation of a unique, writeable copy of
the `$KUBECONFIG` for every consumer.
/cc @alvaroaleman 
follow-up to #1691
> secret-wrapper: populate a unique, writable KUBECONFIG

- cmd/registry-replacer/main.go
Follow up https://coreos.slack.com/archives/CHY2E1BL4/p1613657069247400
The periodic-prow-auto-config-brancher job is flaky.
https://prow.ci.openshift.org/view/gs/origin-ci-test/logs/periodic-prow-auto-config-brancher/1362401502118809600#1:build-log.txt%3A3642
The job run a batch of ci-tools. This tool `registry-replacer` is added the last and it uses concurrency to handle ci-operator's config.
This should improve the success rate.
/hold
Will run a job with the built image.
> registry-replacer: add flag -maxConcurrency

- cmd/result-aggregator/main.go
- cmd/result-aggregator/main_test.go
- cmd/result-aggregator/validator.go
https://issues.redhat.com/browse/DPTP-1970
> result-aggregator: support --passwd-file

- cmd/autopublicizeconfig/main.go
/cc @openshift/openshift-team-developer-productivity-test-platform @petr-muller 
> [DPTP-2001] fix autopublicizeconfig pr creating function arguments

- pkg/results/report.go
- pkg/results/report_test.go
https://issues.redhat.com/browse/DPTP-1970
> ci-operator: add flag -report-credentials-file

- pkg/steps/multi_stage.go
- pkg/steps/release/create_release.go
- pkg/util/rbacs.go
> ci-operator: remove 2min from every test's runtime

- cmd/ci-operator/main.go
- cmd/result-aggregator/main.go
- pkg/results/report.go
- pkg/results/report_test.go
https://issues.redhat.com/browse/DPTP-1970
> stop using user/password for result-aggregator

- pkg/steps/multi_stage.go
Today, the test steps' grace periods are simply inherited from their
parent job. Test steps have their own Pod grace periods (either default
or configured by the user), so we should set our test process to have a
grace period shy of that.
In the future we should deprecate the existing active deadline seconds
and grace period fields on the test steps and use the Prow timeout and
grace period concepts, as they are more friendly to users.
/assign @alvaroaleman @bbguimaraes
> ci-operator: be more intelligent with grace periods

- cmd/registry-replacer/main.go
> [DPTP-2013] Pass an empty map when creating a new image builder instead of nil

- cmd/ci-secret-bootstrap/main.go
- cmd/ci-secret-bootstrap/main_test.go
- pkg/api/secretbootstrap/secretboostrap.go
- pkg/api/secretbootstrap/secretboostrap_test.go
> secret-bootstrapper: check the attribute value in config validation

- pkg/steps/multi_stage.go
- pkg/steps/testdata/zz_fixture_TestGeneratePods.yaml
Part of [DPTP-1668](https://issues.redhat.com/browse/DPTP-1668)
> ci-operator: use the renamed entrypoint wrapper

- pkg/api/config.go
- pkg/api/types.go
- pkg/steps/multi_stage_test.go
- pkg/webreg/zz_generated.ci_operator_reference.go
/assign @alvaroaleman @petr-muller @bbguimaraes
> ci-operator: don't allow setting artifact dir for steps

- cmd/vault-subpath-proxy/main.go
Ref https://issues.redhat.com/browse/DPTP-1890
> Vault subpath proxy: ListenTLS when certificate is passed

- Makefile
- cmd/secret-wrapper/main.go
- images/secret-wrapper/Dockerfile
- test/entrypoint-wrapper-integration.sh
> remove unused secret-wrapper image

- cmd/ci-operator/main.go
> ci-operator: remove deprecated flags nobody uses

- pkg/api/constant.go
- pkg/prowgen/prowgen.go
- pkg/prowgen/prowgen_test.go
- pkg/prowgen/testdata/zz_fixture_TestGenerateJobs_kvm_label.yaml
https://issues.redhat.com/browse/DPTP-2017
/cc @openshift/openshift-team-developer-productivity-test-platform @cgwalters
> prowgen: generate kvm label

- pkg/dispatcher/config.go
- pkg/dispatcher/config_test.go
- pkg/dispatcher/testdata/TestLoadConfig/good_config_with_build_farm_with_jobs.yaml
https://issues.redhat.com/browse/DPTP-2017
> sanitize: use kvm label

- pkg/registry/resolver.go
- pkg/registry/resolver_test.go
- pkg/registry/stack.go
This addresses https://issues.redhat.com/browse/DPTP-2043, among other related
improvements.
See the tests in the final `diff` for examples.
> pkg/registry: emit less arcane error messages

- cmd/vault-secret-collection-manager/main.go
- cmd/vault-secret-collection-manager/middleware.go
Ref https://issues.redhat.com/browse/DPTP-1891
> Vault secret manager: Add request logging

- cmd/vault-secret-collection-manager/main.go
- cmd/vault-secret-collection-manager/main_test.go
- pkg/vaultclient/vaultclient.go
- pkg/vaultclient/vaultclient_test.go
Ref https://issues.redhat.com/browse/DPTP-1891
> Vault secret collection manager: Add backend for Deletion

- cmd/ci-secret-generator/README.md
- cmd/ci-secret-generator/main.go
- pkg/bitwarden/cli.go
https://issues.redhat.com/browse/DPTP-1974
> ci-secret-generator: minor fixes

- hack/check-test-infra-version.sh
> hack: add a no-op script to pass test

- cmd/vault-secret-collection-manager/main.go
- cmd/vault-secret-collection-manager/middleware.go
https://issues.redhat.com/browse/DPTP-1891
> Secret collection manager: Add instrumentation

- Makefile
- hack/compile-typescript.sh
- hack/test-go.sh
> make: use dummy data for front-end without a compiler

- cmd/ci-operator/main.go
> ci-operator: really do verbose logging

- pkg/steps/multi_stage.go
- pkg/steps/testdata/zz_fixture_TestGeneratePods.yaml
This is probably better than setting them to 0 or nil.
> ci-operator: default both timeout and grace period

- hack/check-test-infra-version.sh
> hack: check vendor vs ci-chat-bot, too

- cmd/ci-operator/main.go
- pkg/util/secret.go
This makes the kubelet not watch them which reduces the load on the
APIServers.
> CI-Operator: Create immutable secrets to avoid scaling issues

- cmd/vault-secret-collection-manager/docker-compose.yaml
- cmd/vault-secret-collection-manager/index.template.html
- cmd/vault-secret-collection-manager/index.ts
- cmd/vault-secret-collection-manager/main.go
- cmd/vault-secret-collection-manager/main_test.go
- cmd/vault-secret-collection-manager/style.css
- hack/compile-typescript.sh
- hack/pr-deploy-vault-secret-manager.yaml
- pkg/vaultclient/vaultclient.go
Ref https://issues.redhat.com/browse/DPTP-1891
> Vault secret collection manager: Add edit members functionality

- pkg/controller/secretsyncer/secretsyncer.go
`secretsyncer` can race with other thins that manage secrets (like ci-secret-bootstrap) and then it unnecessarily polluted logs:
```
failed to upsert secret: Operation cannot be fulfilled on secrets "cluster-secrets-packet": the object has been modified; please apply your changes to the latest version and try again
```
Part of this secret above is managed by bootstrap and part by the syncer.
> secretsyncer: tolerate conflicts without polluting logs

- cmd/autoowners/main.go
- cmd/autoowners/main_test.go
> Autoowners: Add support for custom owners{,aliases} filenames

- pkg/steps/multi_stage.go
Workaround for apiserver issue https://bugzilla.redhat.com/show_bug.cgi?id=1937523
which triggered force deletion is any pod matching the selection was already
terminated.
> Iterate through pods during multi-stage delete

- pkg/steps/project_image.go
- pkg/steps/project_image_test.go
> ci-operator: correctly mount source volumes

- pkg/api/types.go
- pkg/steps/artifacts.go
- pkg/steps/multi_stage.go
- pkg/steps/multi_stage_test.go
- pkg/validation/test.go
- pkg/validation/test_test.go
- pkg/webreg/zz_generated.ci_operator_reference.go
Adding the DNSCONFIG for pod spec [DPTP-1260](https://issues.redhat.com/browse/DPTP-1260)
Signed-off-by: Deep Mistry
> Adding dnsConfig for test pods

- pkg/defaults/defaults.go
> ci-operator: make the cache work

- pkg/rehearse/jobs.go
- pkg/rehearse/jobs_test.go
- pkg/rehearse/testdata/zz_fixture_TestMakeRehearsalPresubmit_job_that_belong_to_different_org_repo_than_refs_with_custom_config.yaml
/assign @droslean @petr-muller
> pj-rehearse: copy custom config to refs

- pkg/api/types.go
- pkg/prowgen/prowgen.go
- pkg/prowgen/prowgen_test.go
- pkg/prowgen/testdata/zz_fixture_TestGeneratePodSpecMultiStage_aws_2_cluster_profile.yaml
- pkg/validation/test.go
> DPTP-1996 Add cluster profile for the second AWS

- pkg/steps/release/promote.go
- pkg/steps/release/testdata/zz_fixture_TestGetPromotionPod_basic_case.yaml
/hold
will rebase after https://github.com/openshift/ci-tools/pull/1816
/cc @stevekuznetsov @alvaroaleman 
I should not have cared much about the readability of the cmd. :sigh
> Fix the line breaks of the command in promotion pod

- cmd/ci-operator/main.go
- pkg/defaults/defaults.go
- pkg/steps/secretrecordingclient/client.go
- vendor/github.com/sirupsen/logrus/hooks/writer/README.md
- vendor/github.com/sirupsen/logrus/hooks/writer/writer.go
- vendor/modules.txt
> ci-operator: create logfile

- pkg/registry/graph.go
- Fix godocs
- `Childrens` -> `Children`
> Cleanup registry code

- hack/generate-ci-op-reference.sh
- pkg/api/config.go
- pkg/api/types.go
- pkg/validation/test.go
- pkg/validation/test_test.go
- pkg/webreg/zz_generated.ci_operator_reference.go
https://issues.redhat.com/browse/DPTP-2098
> Expose tests.cluster_claim in ci-op's configuration

- cmd/prow-job-dispatcher/main_test.go
- pkg/api/constant.go
- pkg/api/domain.go
- pkg/api/types.go
- pkg/dispatcher/config.go
- pkg/dispatcher/config_test.go
- pkg/prowgen/prowgen.go
- pkg/prowgen/prowgen_test.go
- pkg/prowgen/testdata/zz_fixture_TestGenerateJobs_cluster_label.yaml
- pkg/validation/test.go
- pkg/validation/test_test.go
- pkg/webreg/zz_generated.ci_operator_reference.go
https://issues.redhat.com/browse/DPTP-2054
> Expose tests.cluster in ci-op's config

- cmd/ci-secret-bootstrap/main.go
- pkg/bitwarden/bitwarden.go
- pkg/bitwarden/cli.go
- pkg/bitwarden/fake.go
- pkg/secrets/client.go
- pkg/secrets/vault.go
> [DPTP-2094] ci-secret-bootstrap: validate if the given items/field/attachments exist

- cmd/ci-secret-bootstrap/main.go
- pkg/bitwarden/bitwarden.go
- pkg/bitwarden/cli.go
- pkg/bitwarden/fake.go
- pkg/secrets/client.go
- pkg/secrets/vault.go
Reverts openshift/ci-tools#1843
> Revert "[DPTP-2094] ci-secret-bootstrap: validate if the given items/field/attachments exist"

- cmd/ci-secret-bootstrap/main.go
- cmd/ci-secret-bootstrap/main_test.go
- cmd/ci-secret-generator/main.go
- pkg/secrets/flags.go
- pkg/secrets/flags_test.go
- pkg/vaultclient/vaultclient.go
Includes https://github.com/openshift/ci-tools/pull/1855 and fixups
> Add support for Vault Kubernetes auth to secret flag and fix validation

- cmd/ci-secret-bootstrap/main.go
- pkg/bitwarden/bitwarden.go
- pkg/bitwarden/cli.go
- pkg/bitwarden/fake.go
- pkg/secrets/client.go
- pkg/secrets/vault.go
Reverts openshift/ci-tools#1859
/hold
> Revert "Revert "[DPTP-2094] ci-secret-bootstrap: validate if the given items/field/attachments exist""

- cmd/ci-secret-bootstrap/main.go
- pkg/bitwarden/bitwarden.go
- pkg/bitwarden/cli.go
- pkg/bitwarden/fake.go
- pkg/secrets/client.go
- pkg/secrets/vault.go
Reverts openshift/ci-tools#1863
> Revert "Revert "Revert "[DPTP-2094] ci-secret-bootstrap: validate if the given items/field/attachments exist"""

- pkg/steps/pod.go
- pkg/steps/pod_test.go
- pkg/steps/release/create_release.go
- pkg/steps/release/import_release.go
- pkg/steps/testdata/zz_fixture_envTestGetPodObjectMounts_with_cluster_claim.yaml
- pkg/steps/testdata/zz_fixture_mountsTestGetPodObjectMounts_with_cluster_claim.yaml
- pkg/steps/testdata/zz_fixture_volumesTestGetPodObjectMounts_with_cluster_claim.yaml
https://issues.redhat.com/browse/DPTP-2099
Require https://github.com/openshift/ci-tools/pull/1837
/hold
> Support cluster_claim in container tests

- pkg/steps/cluster_claim.go
- pkg/steps/cluster_claim_test.go
> Fix the condition of ClusterClaim being running

- pkg/api/types.go
- pkg/prowgen/prowgen.go
- pkg/prowgen/prowgen_test.go
- pkg/prowgen/testdata/zz_fixture_TestGeneratePodSpecMultiStage_gcp_2_cluster_profile.yaml
- pkg/validation/test.go
> Add cluster profile for the second GCP account

- pkg/prowgen/prowgen.go
- pkg/prowgen/testdata/zz_fixture_TestGeneratePodSpecMultiStage_gcp_2_cluster_profile.yaml
> fix prowgen to generate cluster profile for the 2nd GCP account

- pkg/api/constant.go
- pkg/prowgen/prowgen.go
- pkg/prowgen/prowgen_test.go
- pkg/prowgen/testdata/zz_fixture_TestGeneratePodSpecMultiStage_cluster_claim.yaml
https://issues.redhat.com/browse/DPTP-2099
/hold
wait for https://github.com/openshift/ci-tools/pull/1838 and https://github.com/openshift/ci-tools/pull/1837
> prowgen: generate the hive-kubeconfig arg

- pkg/api/types.go
/cc @openshift/openshift-team-developer-productivity-test-platform @wking 
> change the lease type for the second GCP account

- pkg/api/types.go
- pkg/prowgen/prowgen.go
- pkg/prowgen/prowgen_test.go
- pkg/prowgen/testdata/zz_fixture_TestGeneratePodSpecMultiStage_hypershift_cluster_profile.yaml
- pkg/validation/test.go
Adds a new cluster profile to support HyperShift clusters, which have
new quota requirements.
> HOSTEDCP-103: Add cluster profile for HyperShift

- cmd/ci-secret-bootstrap/main_test.go
- pkg/controller/imagepusher/imagepusher_test.go
- pkg/controller/registrysyncer/registrysyncer_test.go
- pkg/controller/util/secret_test.go
- pkg/steps/cluster_claim_test.go
- pkg/steps/output_image_tag_test.go
- pkg/testhelper/testhelper.go
- pkg/testhelper/testhelper_test.go
> Fix a typo: RuntimeObjectIgnoreRvTypeMeta

- cmd/ci-secret-bootstrap/main.go
- cmd/ci-secret-bootstrap/main_test.go
- pkg/api/secretbootstrap/secretboostrap.go
So ppl can store binary data in vault
> Secret-bootstrap: Add option to base64-decode

- cmd/pod-scaler/main.go
> pod-scaler: allow kubeconfig through env

- cmd/vault-secret-collection-manager/main.go
- cmd/vault-secret-collection-manager/main_test.go
- pkg/vaultclient/vaultclient.go
- pkg/vaultclient/vaultclient_test.go
> Secret collection manager: Fix cleanup on delete

- pkg/api/types.go
- pkg/steps/bundle_source.go
- pkg/steps/git_source.go
- pkg/steps/index_generator.go
- pkg/steps/pipeline_image_cache.go
- pkg/steps/project_image.go
- pkg/steps/rpm_injection.go
- pkg/steps/source.go
- pkg/steps/source_test.go
- pkg/steps/testdata/zz_fixture_TestBuildFromSource.yaml
- pkg/webreg/zz_generated.ci_operator_reference.go
https://issues.redhat.com/browse/DPTP-2157
/cc @openshift/openshift-team-developer-productivity-test-platform @vrutkovs
> Support buildArgs for image building

- cmd/applyconfig/applyconfig.go
- cmd/applyconfig/applyconfig_test.go
Use case: `arm01` has its own version of cert-manager which is much newer than what we have.
So we will ignore the file in the common folder for arm01.
> applyconfig: support ignore-file

- cmd/ldap-users-from-github-owners-files/README.md
- cmd/ldap-users-from-github-owners-files/main.go
- cmd/ldap-users-from-github-owners-files/main_test.go
- cmd/ldap-users-from-github-owners-files/testdata/ldapsearch.out
- cmd/ldap-users-from-github-owners-files/testdata/test-repo/OWNERS
- cmd/ldap-users-from-github-owners-files/testdata/test-repo/OWNERS_ALIASES
Built in the context of https://issues.redhat.com/browse/DPTP-2158 but
might be useful elsewhere.
> Add CLI to get ldap IDs from Owners file

- cmd/pod-scaler/admission.go
- cmd/pod-scaler/main.go
> pod-scaler: expect serving cert and key for admission

- cmd/pod-scaler/admission.go
- cmd/pod-scaler/main.go
> pod-scaler: log more in admission

- pkg/steps/output_image_tag.go
Previously we could have hit a conflict, swallow it (the code was copied
from controllers where conflicts were handled by an outer loop), do not
promote anything and as a result, test baseline instead of candidate.
From our Slack convo I understand that checking for conflicts or alreadyexists so I removed both swallows.
> ci-op: patch ist instead of update to override conflicts

- cmd/ci-secret-bootstrap/main.go
- cmd/ci-secret-generator/main.go
- cmd/ci-secret-generator/main_test.go
- pkg/api/secretgenerator/secretgenerator.go
- pkg/api/secretgenerator/secretgenerator_test.go
- pkg/api/secretgenerator/testdata/TestLoadConfigFromPath/no_parameters.yaml
- pkg/api/secretgenerator/testdata/TestLoadConfigFromPath/single_parameter.yaml
- pkg/api/secretgenerator/testdata/TestLoadConfigFromPath/single_parameter_with_multiple_values.yaml
- pkg/api/secretgenerator/testdata/TestLoadConfigFromPath/two_parameters_with_multiple_values.yaml
- pkg/api/secretgenerator/testdata/zz_fixture_TestLoadConfigFromPath_no_parameters.yaml
- pkg/api/secretgenerator/testdata/zz_fixture_TestLoadConfigFromPath_single_parameter.yaml
- pkg/api/secretgenerator/testdata/zz_fixture_TestLoadConfigFromPath_single_parameter_with_multiple_values.yaml
- pkg/api/secretgenerator/testdata/zz_fixture_TestLoadConfigFromPath_two_parameters_with_multiple_values.yaml
> [DPTP-2155] Skip item existance validation that exist in ci-secret-generator configuration

- cmd/determinize-prow-config/main.go
- cmd/determinize-prow-config/main_test.go
This reverts commit c7153c44fb76ebf49d3ae3d76efb61354aa54914.
> Revert "Shard tide merge method"

- pkg/steps/output_image_tag.go
https://github.com/openshift/ci-tools/pull/1928 assumed we do not need nto handle conflicts when we patch because they should not happen.
They happen.
This is suspected to be a bug in kube so I decided to keep this so that we have a repro (instead of switching it back to CreateOrUpdate where the conflict handling would not be surprising).
> ci-op: retry on conflicts when we patch ists

- cmd/determinize-prow-config/main.go
- cmd/determinize-prow-config/main_test.go
There seems to be a bug with prow loading it.
Config revert was in https://github.com/openshift/release/pull/18183
> Disable tide merge method sharding

- pkg/steps/cluster_claim.go
Follow up https://github.com/openshift/ci-tools/pull/1905#discussion_r622695852
> Use the trimLabels function to trim labels

- cmd/pod-scaler/main.go
> pod-scaler: correctly format output logs

- cmd/ci-secret-bootstrap/main.go
> ci-secret-bootstrap: log what we're doing w.r.t. vault

- go.mod
- go.sum
- vendor/k8s.io/test-infra/prow/cmd/generic-autobumper/bumper/bumper.go
- vendor/k8s.io/test-infra/prow/config/agent.go
- vendor/k8s.io/test-infra/prow/config/branch_protection.go
- vendor/k8s.io/test-infra/prow/config/config.go
- vendor/k8s.io/test-infra/prow/config/prow-config-documented.yaml
- vendor/k8s.io/test-infra/prow/config/tide.go
- vendor/k8s.io/test-infra/prow/flagutil/config/config.go
- vendor/k8s.io/test-infra/prow/io/providers/providers.go
- vendor/k8s.io/test-infra/prow/spyglass/artifacts.go
- vendor/modules.txt
So we can use https://github.com/kubernetes/test-infra/pull/21999
Needs 
* https://github.com/openshift/release-controller/pull/269
* https://github.com/openshift/ci-chat-bot/pull/155
> Bump test infra to a8de1a965bad0faf5b30e300753111b44d84385d

- pkg/steps/cluster_claim.go
Follow up https://github.com/openshift/ci-tools/pull/1905#discussion_r622695466
> Add a reason maker: acquiring_cluster_claim

- cmd/determinize-prow-config/main.go
- cmd/determinize-prow-config/main_test.go
/hold
Needs https://github.com/openshift/ci-tools/pull/1935
Ref https://issues.redhat.com/browse/DPTP-2110
> Re-Enable tide merge method config sharding

- pkg/steps/cluster_claim.go
- pkg/steps/lease.go
Follow up https://github.com/openshift/ci-tools/pull/1905#discussion_r622695659
> Dry out function aggregateWrappedErrorAndReleaseError

- cmd/ci-secret-generator/main.go
Logrus exit handler exits the whole binary, so it will swallow panics.
This change instead moves most of the logic into a new func in which we
never Fatal and just defer the Logout withot Logrus.
> Ci-Secret-Generator: Don't swallow panics

- pkg/rehearse/jobs.go
- pkg/rehearse/jobs_test.go
- pkg/steps/cluster_claim.go
- pkg/steps/source.go
- pkg/steps/source_test.go
- pkg/steps/utils/labels.go
- pkg/steps/utils/labels_test.go
- test/integration/pj-rehearse/expected.yaml
> ci-operator: handle labels in a DRY manner, better rehearsal contexts

- go.mod
- go.sum
- vendor/modules.txt
- vendor/sigs.k8s.io/controller-runtime/Makefile
- vendor/sigs.k8s.io/controller-runtime/pkg/cache/cache.go
- vendor/sigs.k8s.io/controller-runtime/pkg/cache/internal/cache_reader.go
- vendor/sigs.k8s.io/controller-runtime/pkg/cache/internal/deleg_map.go
- vendor/sigs.k8s.io/controller-runtime/pkg/cache/internal/informers_map.go
- vendor/sigs.k8s.io/controller-runtime/pkg/cache/internal/metadata_infomer_wrapper.go
- vendor/sigs.k8s.io/controller-runtime/pkg/cache/internal/selector.go
- vendor/sigs.k8s.io/controller-runtime/pkg/cache/multi_namespace_cache.go
- vendor/sigs.k8s.io/controller-runtime/pkg/client/apiutil/apimachinery.go
- vendor/sigs.k8s.io/controller-runtime/pkg/client/client.go
- vendor/sigs.k8s.io/controller-runtime/pkg/client/client_cache.go
- vendor/sigs.k8s.io/controller-runtime/pkg/client/fake/client.go
- vendor/sigs.k8s.io/controller-runtime/pkg/client/namespaced_client.go
- vendor/sigs.k8s.io/controller-runtime/pkg/controller/controllerutil/controllerutil.go
- vendor/sigs.k8s.io/controller-runtime/pkg/internal/objectutil/objectutil.go
- vendor/sigs.k8s.io/controller-runtime/pkg/manager/internal.go
- vendor/sigs.k8s.io/controller-runtime/pkg/manager/manager.go
- vendor/sigs.k8s.io/controller-runtime/pkg/webhook/admission/multi.go
- vendor/sigs.k8s.io/controller-runtime/pkg/webhook/admission/webhook.go
- vendor/sigs.k8s.io/controller-runtime/pkg/webhook/server.go
This PR is generated from
```console
$ go get -u sigs.k8s.io/controller-runtime@master
```
I would like to use https://github.com/kubernetes-sigs/controller-runtime/commit/2a2f6b4ef26cd4201d84c051663c3bf0678477e3
> Update controller-runtime to the latest

- cmd/ci-secret-bootstrap/main.go
Fix the issues seen in
https://deck-internal-ci.apps.ci.l2s4.p1.openshiftapps.com/view/gs/origin-ci-private/logs/periodic-ci-secret-bootstrap/1390700008038207488
> ci-secret-bootstrap: fix secret creation logic

- test/e2e/framework/framework.go
- test/e2e/multi-stage/cluster-claim.yaml
- test/e2e/multi-stage/e2e_test.go
https://issues.redhat.com/browse/DPTP-2143
> Add e2e test for cluster claim

- pkg/steps/multi_stage.go
- pkg/steps/multi_stage_test.go
- pkg/steps/testdata/zz_fixture_TestGeneratePods.yaml
[DPTP-1260](https://issues.redhat.com/browse/DPTP-1260)
Signed-off-by: Deep Mistry
> Applying custom dnsPolicy for pod spec

- cmd/ci-secret-bootstrap/main.go
- cmd/ci-secret-bootstrap/main_test.go
- cmd/vault-subpath-proxy/kv_key_validator.go
- cmd/vault-subpath-proxy/main_test.go
- pkg/api/vault/vault.go
Ref https://issues.redhat.com/browse/DPTP-2172
> Secretsync: Allow to target only a subset of clusters

- hack/pr-deploy-backporter.yaml
- hack/pr-deploy.yaml
- pkg/webreg/webreg.go
- pkg/webreg/webreg_test.go
With [DPTP-1827](https://issues.redhat.com/browse/DPTP-1827) we want to output environment variables for chains and workflows
See: https://server-ci-tools-1974.apps.ci.l2s4.p1.openshiftapps.com/ for post-merge state.
> DPTP-1827: Output environment variables for chains and workflows

- cmd/autoowners/main.go
- cmd/autoowners/main_test.go
I noticed that autoowners would not populate OWNERS files for prow
config dirs where the repo doesn't have any jobs, this change fixes
that.
Note: The diff gets a lot smaller when disabling whitespace changes
> Autoowners: Also extend repos from extra_dirs

- cmd/ci-operator/main.go
- cmd/ci-operator/main_test.go
With [DPTP-2199](https://issues.redhat.com/browse/DPTP-2199) we want to allow setting multi-stage parameters externally through the ci-operator
> DPTP-2199: Allow setting multi-stage params externally

- Makefile
> Makefile: create Hive kubeconfig for local E2E

- Makefile
- pkg/api/constant.go
- pkg/prowgen/testdata/zz_fixture_TestGeneratePodSpecMultiStage_cluster_claim.yaml
- pkg/steps/multi_stage_test.go
https://issues.redhat.com/browse/DPTP-2187
> Use the new hive kubeconfig

- cmd/ci-secret-bootstrap/main_test.go
> [DPTP-2169] Add integration tests for ci-secret-bootstrap pipeline

- pkg/steps/source.go
- pkg/steps/source_test.go
- pkg/steps/testdata/zz_fixture_TestCreateBuild_title_in_pull_gets_squashed.yaml
> ci-operator: don't pass title into refs

- cmd/pj-rehearse/main.go
- pkg/config/jobs.go
- pkg/config/jobs_test.go
- pkg/diffs/diffs.go
- pkg/diffs/diffs_test.go
- test/integration/pj-rehearse/candidate/ci-operator/config/super/trooper/super-trooper-master.yaml
- test/integration/pj-rehearse/candidate/ci-operator/jobs/super/trooper/super-trooper-master-periodics.yaml
- test/integration/pj-rehearse/expected.yaml
- test/integration/pj-rehearse/master/ci-operator/config/super/trooper/super-trooper-master.yaml
- test/integration/pj-rehearse/master/ci-operator/jobs/super/trooper/super-trooper-master-periodics.yaml
Resolves: [DPTP-1095](https://issues.redhat.com/browse/DPTP-1095)
> rehearse periodics affected by changed ci-op configs

- cmd/autoconfigbrancher/main.go
- test/e2e/simple/e2e_test.go
Ref https://issues.redhat.com/browse/DPTP-2245
/assign @jupierce
> Autoconfigbrancher: Add ci-operator-yaml-creator

- images/autoconfigbrancher/Dockerfile
> add ci-operator-yaml-creator binary in autoconfigbrancher image

- cmd/pod-scaler/main.go
When running this thing locally it's much nicer not to have JSON.
> pod-scaler: allow choosing log style

- cmd/pod-scaler/producer.go
This was an omission on the first implementation.
> pod-scaler: handle read errors

- Makefile
> make: allow opting out of verbosity

- cmd/ci-operator-yaml-creator/main.go
The PR creation changes the working dir, so we can not do it in parallel
or bad things will happen.
Also, we need to chdir before removing a repo, otherwise git clone will
fail as it requires to be in a valid dir.
Ref https://issues.redhat.com/browse/DPTP-2245
Sample failure: https://prow.ci.openshift.org/view/gs/origin-ci-test/logs/periodic-ci-operator-yaml-creator/1404544266985803776#1:build-log.txt%3A309
> Prow Yaml creator: Fix chdir issues

- pkg/validation/field.go
- pkg/validation/test.go
In preparation to address the inconsistency highlighted in:
https://github.com/openshift/ci-tools/pull/2062#discussion_r652757992
> pkg/validation: add a `struct` for field paths

- go.mod
- go.sum
- test/integration/repo-init/expected/core-services/prow/02_config/_config.yaml
- vendor/k8s.io/test-infra/prow/config/config.go
- vendor/k8s.io/test-infra/prow/config/tide.go
- vendor/modules.txt
To pick up https://github.com/kubernetes/test-infra/pull/22586
> Bump test-infra to 2443b17c6b6196f6f380464f1cb30ab9ed8b502e
