openshift/ci-tools

pkg/rehearse/jobs.go
pkg/rehearse/jobs_test.go

Removes the need for an update every time a new type is added (usually
discovered by our users):
- https://github.com/openshift/ci-operator-prowgen/pull/158
- https://github.com/openshift/ci-operator-prowgen/pull/151
- https://github.com/openshift/ci-tools/pull/2
With openshift/release@dd91eaa1b, the following types are detected:
- aws
- azure4
- gcp
- metal
- openstack
- vsphere

rehearse: detect cluster types

---

pkg/jobconfig/files.go
pkg/jobconfig/files_test.go

/cc @stevekuznetsov @hongkailiu @droslean @bbguimaraes

Shard validator: shard job-config-master further (by job type)

---

CI_OPERATOR.md
CONTRIBUTORS.md

ci-operator was recently merged into ci-tools. The ci-operator repo
and build command needed to be updated.

Update URL and build command

---

pkg/steps/clusterinstall/template.go

/cc @smarterclayton @stevekuznetsov

clusterinstall: sync the template with openshift/release@16eaebe45

---

cmd/pj-rehearse/main.go
test/pj-rehearse-integration/run.sh
test/prowgen-integration/run.sh
test/validate-prowgen-breaking-changes.sh

Same as https://github.com/openshift/release/pull/4205

Fix ERROR prefixes to be hightlighted by Spyglass

---

pkg/steps/git_source.go

Treat extra refs the same way as other steps (e.g. source).  Found when
testing a periodic job with a `project_image` `build_root`.

ci-operator: check extra refs in gitSourceStep

---

pkg/steps/release/create_release.go

/cc @eparis @smarterclayton 
/assign @bbguimaraes @petr-muller

Wait longer for image import

---

cmd/ci-operator-prowgen/main.go
cmd/ci-operator-prowgen/main_test.go

Previously we needed to handle labels specifically in postsubmits
because we were marking them with `artifacts: images`. We no longer do
that, but we were still creating an empty map, passing it through and
API that was more complicated than needed and copying it around. All
this was removed.
Also, remove one unused parameter, simplify regexes and fix a typo.
/cc @stevekuznetsov @bbguimaraes @droslean @stevekuznetsov

prowgen: Remove some dead code

---

pkg/diffs/diffs.go
pkg/diffs/diffs_test.go

rehearse: Get changed periodics

---

cmd/ci-operator-prowgen/main.go
cmd/ci-operator-prowgen/main_test.go
pkg/jobconfig/files.go

Generate the JobBase parts of both Presubmits and Postsubmit in a single
method.
Additionally, remove some of the regex-handling code for Postsubmits. We
never passed anything else than `true` to the `treatBranchesAsExplicit`
param, so I've removed the parameter and simplified the API. Also, we
took some measures to handle regex-y branches, but the branches come
from **ci-operator** config (not Prowjob config), so they are never
regexes, so we do not need to handle that.
/cc @stevekuznetsov @droslean @bbguimaraes @hongkailiu

prowgen: DRY out JobBase generation

---

test/prowgen-integration/data/input/config/super/duper/super-duper-master-removed-promotion.yaml
test/prowgen-integration/data/input/config/super/duper/super-duper-master__variant.yaml
test/prowgen-integration/data/input/jobs/super/duper/super-duper-master-removed-ciop-config-postsubmits.yaml
test/prowgen-integration/data/input/jobs/super/duper/super-duper-master-removed-promotion-postsubmits.yaml
test/prowgen-integration/data/input/jobs/super/duper/super-duper-master-removed-promotion-presubmits.yaml
test/prowgen-integration/data/output/jobs/super/duper/super-duper-master-postsubmits.yaml
test/prowgen-integration/data/output/jobs/super/duper/super-duper-master-presubmits.yaml
test/prowgen-integration/data/output/jobs/super/duper/super-duper-master-removed-promotion-presubmits.yaml

Three commits, each adds a single test:
1. Test that removing `promotion` results in removing the promotion postsubmit entirely
2. Test that removing a ci-op config entirely results in removing all jobs
3. Test that variant ci-op config results in variant jobs correctly merged with normal ones
/cc @bbguimaraes @stevekuznetsov

prowgen: Add integration tests for pruning and variants

---

cmd/pj-rehearse/main.go
pkg/rehearse/jobs.go
pkg/rehearse/jobs_test.go

This PR generalizes the functions that are responsible for the job configuration. This will allow to accept different job types in the future without the need of further refactoring.

refactor job configuration

---

cmd/ci-operator-prowgen/main.go

I tried `--{from,to}-release-repo` for the first time (sue me) and they did not
work because `GOPATH` was not set.  go 1.8 (two years old now and beyond the
two-major-versions support policy) has a way to resolve the value, see
https://golang.org/pkg/go/build.

prowgen: use default GOPATH

---

cmd/pj-rehearse/main.go
pkg/rehearse/jobs.go
pkg/rehearse/jobs_test.go
pkg/rehearse/metrics.go
pkg/rehearse/metrics_test.go
test/pj-rehearse-integration/candidate/ci-operator/jobs/super/duper/super-duper-periodics.yaml
test/pj-rehearse-integration/expected.yaml
test/pj-rehearse-integration/master/ci-operator/jobs/super/duper/super-duper-periodics.yaml

In this PR we enable the periodic jobs to the rehearse tool.

pj-rehearse: Add periodic jobs to the rehearsals 

---

.gitignore
cmd/ipi-deprovision/ipi-deprovision.sh
images/ipi-deprovision/Dockerfile

https://jira.coreos.com/browse/DPTP-471

Build ipi_deprovision image

---

pkg/api/job_spec.go
pkg/steps/source.go

Get working directory from jobspec and use it in the source image.
reference: [apis/prowjobs/v1/types.go#L565](https://github.com/kubernetes/test-infra/blob/master/prow/apis/prowjobs/v1/types.go#L565)
Working directory will be overwritten if there is an `extra_refs` with `workdir:true` in the `$JOB_SPEC`

determine working directory for the source image.

---

cmd/ci-operator/main.go

Periodic jobs don't have `refs` but we include extrarefs later in the code already.

include extrarefs pulls to authors

---

cmd/ipi-deprovision/ipi-deprovision.sh

follow-up of https://github.com/openshift/release/pull/4489

Check if AWS_SHARED_CREDENTIALS_FILE is set

---

ONBOARD.md

`destination_dir` has to be a relative path. Otherwise [1]
error: could not run steps: step ipi-deprovision failed: could not create build ipi-deprovision: Build.build.openshift.io "ipi-deprovision" is invalid: spec.source.images[0].paths[0].destinationDir: Invalid value: "/usr/bin": must be a relative path
[1]. https://prow.svc.ci.openshift.org/view/gcs/origin-ci-test/pr-logs/pull/openshift_release/4531/rehearse-4531-pull-ci-openshift-ci-tools-master-images/1#0:build-log.txt%3A53

Fix an example of destination_dir in ONBOARD.md

---

cmd/applyconfig/README.md
cmd/applyconfig/applyconfig.go
cmd/applyconfig/applyconfig_test.go
images/applyconfig/Dockerfile

...from https://github.com/openshift/release/tree/master/tools/applyconfig
The move will make the following two items easier:
1) Building an image for `applyconfig` to be used by o/release jobs
2) Extending `applyconfig` to handle Templates.
/cc @stevekuznetsov @bbguimaraes @droslean @hongkailiu

Move `applyconfig` from release to ci-tools

---

cmd/pj-rehearse/main.go
pkg/rehearse/jobs.go
pkg/rehearse/jobs_test.go
test/pj-rehearse-integration/expected.yaml

All job types are sharing a `JobBase` which can be used to convert the periodic jobs to presubmits. 
The reason for that is that the job will be able to report back to Github's PR, and the artifacts will be uploaded in the correct place.

convert Periodics to Presubmits

---

cmd/ci-operator-prowgen/main.go
cmd/ci-operator-prowgen/main_test.go
pkg/jobconfig/files.go
test/prowgen-integration/data/output/jobs/subdir/repo/subdir-repo-master-presubmits.yaml
test/prowgen-integration/data/output/jobs/super/duper/super-duper-master-presubmits.yaml
test/prowgen-integration/data/output/jobs/super/duper/super-duper-master-removed-promotion-presubmits.yaml
test/prowgen-integration/data/output/jobs/super/duper/super-duper-release-3.11-presubmits.yaml

We are about to add an opt-in mechanism for the rehearsals that will be allowed to be executed only if they hold the `pj-rehearse.openshift.io/can-be-rehearsed: "true"` label. 
With this PR, we include this label to all generated ci-operator presubmits.

add rehearse label to generated presubmits

---

cmd/ci-operator-checkconfig/main.go
cmd/ci-operator/main.go
pkg/api/config.go
pkg/api/types.go
pkg/config/load.go
pkg/defaults/defaults.go
pkg/load/load_test.go

The default clone location for a repository is
`${GOPATH}/src/github.com/<org>/<repo>`. There is no need to allow
people to add an alias that points at the same location.

Disallow redundant path aliases

---

cmd/ci-operator-prowgen/main.go
cmd/ci-operator-prowgen/main_test.go
cmd/ci-operator/main.go
pkg/api/types.go
pkg/defaults/defaults.go
pkg/steps/source.go
pkg/steps/source_test.go
test/prowgen-integration/data/input/config/super/duper/super-duper-master__variant.yaml
test/prowgen-integration/data/output/jobs/super/duper/super-duper-master-postsubmits.yaml
test/prowgen-integration/data/output/jobs/super/duper/super-duper-master-presubmits.yaml

Use `canonical_go_repository` to generate `path_alias`
These settings are identical, so we should use the CI Operator
configuration to generate an appropriate set of jobs.
---
Don't change refs at runtime unless running locally
When running with a Prow-provided set of Refs, we should honor those and
not attempt to change them in CI Operator. If a user is passing
`--git-ref` manually, though, we have to construct a set of refs
dynamically at runtime.
---
depends on #66 
/assign @petr-muller @droslean

Don't change refs at runtime unless running locally 

---

cmd/ipi-deprovision/ipi-deprovision.sh

Respond to `Throttling: Rate exceeded` when calling `hiveutil`.
Discussion over [slack](https://coreos.slack.com/archives/CBN38N3MW/p1565277171160600).

Kill hiveutil after 10m

---

cmd/ipi-deprovision/ipi-deprovision.sh

The info-level logs don't give a lot of information about where we're stuck [when a cluster hangs][1]:
```
handling cluster: kubernetes.io/cluster/ci-op-cyzb4xyb-57a9f-29jcd in region us-east-1 with expirationDate: 2019-08-07T12:49+0000
{"component":"entrypoint","file":"prow/entrypoint/run.go:159","func":"k8s.io/test-infra/prow/entrypoint.Options.ExecuteProcess","level":"error","msg":"Process did not finish before 8h0m0s timeout","time":"2019-08-08T10:09:15Z"}
```
[1]: https://storage.googleapis.com/origin-ci-test/logs/periodic-ipi-deprovision/3630/build-log.txt

cmd/ipi-deprovision/ipi-deprovision.sh: Debug logs for aws-tag-deprovision

---

pkg/api/types.go

This will be useful in the cases we determinize or auto-generate ci-operator fields.
/assign @petr-muller @droslean @bbguimaraes

Don't serialize `upgrade: false`

---

pkg/steps/template.go

Since `ci-operator` can get this kind of information from `jobSpec`, this PR adds a label to template pods with the org and repo details.
Example:
`"ci.openshift.io/refs.org": "openshift"`
`"ci.openshift.io/refs.repo": "origin"`
Why?
We can use this label in Prometheus queries. We can track the template jobs by org/repo and we will be able to gather metrics, etc...

add org/repo label in template pods

---

pkg/steps/template.go

It was wrong to return with an error here and assume that the rest of the objects can't be unmarshaled. Also, logging is not needed here.

fix unmarhal error log

---

pkg/api/config.go
pkg/api/config_test.go
pkg/api/types.go

Slightly modified subset of https://github.com/openshift/ci-tools/pull/85.
Open questions:
- Is a step with just a `name` the best way to reference a pre-defined step?  See the original PR for details and https://github.com/bbguimaraes/release/tree/steps for an example.
- Is `resources` required? That is the case for other ci-operator tests, but not for templates.
- `TestStep` is a terrible name.

ci-operator: add TestStep type

---

pkg/diffs/diffs.go
pkg/diffs/diffs_test.go

It makes sense to rehearse the job when it changes to non-optional and when `always_run` changes to `true`.
That will help our stakeholders to make sure that they won't block anything.

rehearse jobs when optional and always_run changes.

---

pkg/api/config.go
pkg/api/types.go
pkg/registry/resolver.go
pkg/registry/resolver_test.go
pkg/steps/types/types.go

This implements a few new structs to allow us to read in user test configs and a function to expand the user's config (which may contain references, chains, etc) into a full internal test representation. This contains some duplicate code from `TestStepConfiguration` as this is essentially the evolution of that struct, but I did not want to trample that code while this new config format is still in a WIP state.
/cc @stevekuznetsov @bbguimaraes

Implement multi-stage test registry interface

---

pkg/api/config.go
pkg/api/config_test.go
pkg/api/types.go
pkg/registry/resolver.go
pkg/registry/resolver_test.go
pkg/steps/types/types.go

Change field names to conform to the design document.
@AlexNPavel: FYI

ci-operator multi-stage: use appropriate names

---

pkg/api/config.go
pkg/api/job_spec.go
pkg/api/types.go
pkg/api/types_test.go
pkg/defaults/defaults.go
pkg/steps/multi_stage.go
pkg/steps/multi_stage_test.go

Basic implementation of the multi-stage test type. Subset of
https://github.com/openshift/ci-tools/pull/85, based on
https://github.com/openshift/ci-tools/pull/98. Design document:
https://docs.google.com/document/d/1md-1BMf4_7mtKgGVoeZ3jOh4zSIBSjwl6vTTAYESwIM.
Fully-functional but lacking management of artifacts, the test secret, cluster
profile, and release image(s).

ci-operator multi-stage: MultiStageTestStep

---

pkg/api/config.go
pkg/api/config_test.go
pkg/api/types.go
pkg/registry/resolver.go
pkg/registry/resolver_test.go
pkg/steps/multi_stage_test.go

Adds support for test references via a step map that is passed to the registry in the `NewResolver` function.

pkg/registry: add support for test references

---

cmd/ci-operator/main.go
pkg/defaults/defaults.go
pkg/steps/clusterinstall/clusterinstall.go
pkg/steps/git_source.go
pkg/steps/input_image_tag.go
pkg/steps/input_image_tag_test.go
pkg/steps/output_image_tag.go
pkg/steps/output_image_tag_test.go
pkg/steps/pipeline_image_cache.go
pkg/steps/pod.go
pkg/steps/pod_test.go
pkg/steps/project_image.go
pkg/steps/release/create_release.go
pkg/steps/release/promote.go
pkg/steps/release/release_images.go
pkg/steps/rpm_injection.go
pkg/steps/rpm_server.go
pkg/steps/source.go
pkg/steps/template.go
pkg/steps/testing.go
pkg/steps/testing_test.go

DryLogger holds the generated object from each step. This can be used to JSON Marshal only once the whole array and generate a valid JSON output to be used for tests etc...

Introduce a dry run logger to ci-operator

---

pkg/api/config.go
pkg/api/config_test.go
pkg/api/types.go
pkg/registry/resolver.go
pkg/registry/resolver_test.go

Add chains to the multistage registry. The registry first unrolls chains to form an unrolled `[]api.TestStep` and then continues to process as before.

ci-operator multistage: implement chains

---

pkg/api/config.go
pkg/api/config_test.go

edit: I'd used the lazy approach of commenting out code to determine if it is covered by tests and it turns out we had a bad test (a disadvantage of having a single boolean to determine success), not bad coverage. I fixed it and added the remaining validation code.together with the original content of this PR — validating duplicates across stages.
---
original:
Eventually, with all the indirections of references, chains, and workflows, we
may want error messages that state more clearly the origin of each conflicting
name.
We will still want a final validation, so this code will remain relevant.

ci-operator: add validation

---

pkg/defaults/defaults.go
pkg/steps/multi_stage.go
pkg/steps/multi_stage_test.go

When given an output artifact directory, for each step that declares an
artifact directory, copy files from the container to
`$artifact_dir/$test_name/$step_name/`.
---
Tests involving `pkg/steps/artifacts.go` are impractical and it would be a lot
of work to invent a separate test infrastructure, so tests are limited to pod
generation. I am open for ideas, though, and to working on that in a separate
PR.

ci-operator multi-stage: gather artifacts

---

pkg/api/config.go
pkg/api/types.go
pkg/registry/resolver.go
pkg/registry/resolver_test.go

Implement workflows in the registry resolver. If a user specifies the same field as a field the workflow specifies, the user's config takes priority and overrides the workflow.

ci-operator: implement multi stage test workflows

---

cmd/config-brancher/main.go

This fixes a segfault when we attempted to branch a config with a
`promotion` stanza but not `tag_specification` stanza. That config only
defined container tests and built no images, so not having
`tag_specification` is fine and we should not segfault on it.

config-brancher: Only bump the fields actually present in the config

---

pkg/steps/clusterinstall/template.go

Template needs return instead of exit so we can run multiple test suites (upgrade + e2e).
https://github.com/openshift/release/pull/5035

ci-operator: Update install template to have latest settings

---

pkg/load/load_test.go

I originally believed that `DeepEqual` did not dereference pointers in Go, but that is only true of the `==` operand. `DeepEqual` on the other hand dereferences pointers when they are not equal.
This commit makes `load_test.go` use `DeepEqual` instead of custom functions for checking equality.

pkg/load_test.go: use reflect.DeepEqual

---

cmd/pj-rehearse/main.go
pkg/config/load.go
pkg/config/load_test.go
pkg/config/release.go
pkg/diffs/diffs.go
pkg/diffs/diffs_test.go

When we load every CI Operator configuration, we have the ability to
record a lot of metadata about the files. We should do so and record it
so that it can be used downstream. This patch adds that change and a
conversion function so that the rollout of the change can be
incremental.
depends on #145

Use a data structure with more metadata for storing config

---

pkg/steps/artifacts.go
pkg/steps/artifacts_test.go
pkg/steps/multi_stage.go
pkg/steps/multi_stage_test.go
pkg/steps/pod.go
pkg/steps/template.go

Not for the faint-hearted.  As promised (and since regretted) in
https://github.com/openshift/ci-tools/pull/110, test artifact gathering in
multi-stage tests, making internal APIs more generic where required.
`waitForPodCompletion` and friends are very complex and messy functions, but
changes are as small as possible and tests are added as soon as it's practical.
This also makes it possible to add test to those functions.
Additionally, I've verified multiple executions of container, template, and
multi-stage tests using the new binary.
Each commit is independent.

ci-operator: make the artifact worker testable

---

pkg/rehearse/jobs.go
pkg/rehearse/jobs_test.go

If the rehearse job belongs to the same org/repo with the refs, the `extrarefs` injection is not needed. Otherwise, `clonerefs` will fail.

Don't add extraRefs if the job belongs to the same org/repo with refs.

---

test/ci-operator-integration/expected_files/expected.json
test/ci-operator-integration/expected_files/expected_with_template.json
test/ci-operator-integration/run.sh

When we run `diff` with $(commands), it will still exit 0 even if the commands will fail. 
To prevent that, this PR add some extra checks to the jq commands.

integration: Add sorting command and update expected files

---

cmd/autoowners/main.go

Although it is unlikely that `git-status` exposes sensitive
information, it is better to avoid surprises.

Use HideSecretsWriter as stderr for git-status command

---

cmd/autobumper/main.go
cmd/autoowners/main.go

When the targetDir is ".", the log shows, for example,
```
time="2019-09-18T13:35:51Z" level=info msg="Changing working directory to '.' ..."
```
instead of
```
time="2019-09-18T13:35:51Z" level=info msg="Changing working directory to ...."
```

Fix logs for changeDir

---

pkg/steps/artifacts.go
pkg/steps/artifacts_test.go
pkg/steps/template.go
pkg/steps/template_test.go
pkg/steps/testing.go
test/ci-operator-integration/config/test-template.yaml
test/ci-operator-integration/expected_files/expected_with_template.json

Trying to land this kind of changes, we met a lot of complications. 
Another PR that removes the unnecessary variables in the template has to be merged in order for this PR to work.
The previous attempt was crashing to Decode the pod from the template because of [this](https://github.com/openshift/release/blob/master/ci-operator/templates/openshift/installer/cluster-launch-installer-src.yaml#L151) variable.
ref: [release/pull/4950](https://github.com/openshift/release/pull/4950)

Refactor artifacts container injection to Template pods.

---

pkg/defaults/defaults.go
pkg/steps/clusterinstall/clusterinstall.go
pkg/steps/template.go
pkg/steps/template_test.go
test/ci-operator-integration/base/config/test-config.yaml
test/ci-operator-integration/base/config/test-template.yaml
test/ci-operator-integration/base/expected_files/expected_with_template.json

With this patch, we allow resources injection to the template pod's test container. 
The logic is the following:
* If the test container has already resources defined, use them.
* else If the ci-operator config has resources defined with the template's name, inject the resources to the test container.
* else If there are only the default resources defined in the ci-operator's config, use them instead.
Note: The resources will be injected only if the template has a pod and the pod has a container named "test"

Inject resources in template pod's container named "test"

---

cmd/autoconfigbrancher/main.go

Automate @petr-muller routine on Monday. For example, https://github.com/openshift/release/pull/5029
```
/user/bin/determinize-ci-operator --config-dir ./ci-operator/config --current-release ${CURRENT_RELEASE} --future-release ${FUTURE_RELEASE} --confirm
/user/bin/config-brancher --config-dir ./ci-operator/config --current-release ${CURRENT_RELEASE} --future-release ${FUTURE_RELEASE} --confirm
/user/bin/ci-operator-prowgen --from-dir ./ci-operator/config --to-dir ./ci-operator/jobs
```

Add tool auto-config-brancher

---

Makefile

./vendor/modules.txt can be modified (reordering the lines in it)
even if the dependencies are not changed. This forces us to run
`make validate-vendor` for each commit.
We ingore the changes on that file in the check.
https://github.com/openshift/ci-tools/pull/161#issuecomment-533296228

Ignore the changes on modules.txt

---

cmd/autobumper/main.go
cmd/autoconfigbrancher/main.go
cmd/autoowners/README.md
cmd/autoowners/main.go

Add options of github endpoints to auto-tools
With the option we can use ghproxy service and get metrics.
For the existing prwo jobs using those tools, we need to update the args accordingly.

Add options of github endpoints to auto-tools

---

images/config-change-trigger/Dockerfile
images/pj-rehearse/Dockerfile

Fixes [this](https://prow.svc.ci.openshift.org/view/gcs/origin-ci-test/logs/branch-ci-openshift-release-master-config-change-trigger/268):
```
time="2019-09-23T17:09:04Z" level=fatal msg="could not load configuration from base revision of release repo" error="failed to get SHA of current HEAD: '[git rev-parse HEAD]' failed with error=exec: \"git\": executable file not found in $PATH, output:\n" org=openshift repo=release
```

Install git for the postsubmit change trigger

---

cmd/config-change-trigger/main.go

When a postsubmit is triggered from a merge, `SHA^1` will refer to the
previous state of the branch before the merge, regardless of how many
commits have been merged in one action. Therefore, this is a safe way
to grab the previous state of the repository. This will work unless
someone manually pushes commits to the repository, which shouldn't
happen, so this is a reasonably resilient, albeit best-effort approach.
/assign @petr-muller @dros

Grab base config from one commit back

---

Makefile
cmd/ci-operator-configresolver/main.go
go.mod
pkg/coalescer/coalescer.go
pkg/coalescer/coalescer_test.go
pkg/load/configAgent.go
test/ci-operator-configresolver-integration/configs2/release-4.2/openshift-installer-release-4.2-golang111.yaml
test/ci-operator-configresolver-integration/expected/openshift-installer-release-4.2-golang111.json
test/ci-operator-configresolver-integration/run.sh

This adds both a periodic reloader and an fs event based reloader for the ci-operator-configresolver. The fsnotify reloader uses a new `Coalescer` type that only allows one instance of the reload to run at a time. Any other instance that is started while the reload is still occuring simply waits for the existing instance to finish and then returns. This is useful because if we mount configs via a configmap, changing a single file can result in 10s of events due to the way configmap mounts work, which would result in the reloader running many times. The periodic reloader is included in case the fsnotify reloader manages to run before all the configmap mount changes are finished and makes sure that the configs being served by the resolver are eventually consistent.

ci-op-configresolver: add fsnotify and periodic reloaders

---

Makefile
cmd/ci-operator/main.go
cmd/secret-wrapper/main.go
images/secret-wrapper/Dockerfile
pkg/defaults/defaults.go
pkg/steps/multi_stage.go
pkg/steps/multi_stage_test.go
pkg/util/secret.go
test/ci-operator-integration/multi-stage/expected.json
test/secret-wrapper-integration.sh

Each test is assigned a secret with a pre-defined name (already
accessible via the `$JOB_NAME_SAFE` environment variable) that will be
mounted at a specific path in all pods (from `pre` to `post`) and can be
used to pass a small amount of data to subsequent steps.

ci-operator multi-stage: create secret

---

pkg/api/types.go
pkg/steps/multi_stage.go
pkg/steps/multi_stage_test.go

When the test has a non-empty profile:
- check that a secret with a pre-defined name exists
- mount the contents of that secret in every pod
- assume a `kubeconfig` key will be added to the test's secret and set
`$KUBECONFIG` to point to it in every pod

ci-operator multi-stage: add cluster profile

---

cmd/ci-operator/main.go

A minor change, but it annoys me deeply (and I remember at least one case where
users were confused because of it).
When creating an EventRecorder, first check if we have permission to create
events and use a FakeRecorder if we don't.  An added benefit is being able to
use the FakeRecorder in dry-run mode and removing some code from conditionals.
<details>
<summary>before (much worse with line wrapping)</summary>
```
2019/10/01 16:44:34 Resolved source https://github.com/openshift/ci-tools to master@1b0baff4
2019/10/01 16:44:35 Resolved openshift/release:golang-1.11 to sha256:580a279c3f0e29cded68868db9a2bdb9abe86227537cfea8d26f237386053f49
2019/10/01 16:44:35 Resolved openshift/release:golang-1.11 to sha256:580a279c3f0e29cded68868db9a2bdb9abe86227537cfea8d26f237386053f49
2019/10/01 …
```

ci-operator: check for permission to create events

---

cmd/ci-operator-prowgen/main.go
pkg/api/types.go
pkg/jobconfig/files.go
pkg/jobconfig/files_test.go
test/prowgen-integration/data/input/config/super/duper/super-duper-master.yaml
test/prowgen-integration/data/input/jobs/super/duper/super-duper-master-periodics.yaml
test/prowgen-integration/data/output/jobs/super/duper/super-duper-master-periodics.yaml

In addition to generating presubmits and postsubmits, a new field on the
test type allows users to generate periodic jobs. In order to support
generating periodic jobs that require the `src-build` step, we add the
repo under test as the first `extra_ref`. Jobs that do not need to clone
anything will no-op.

Allow users to generate periodic jobs

---

cmd/testgrid-config-generator/main.go
pkg/jobconfig/files.go
test/testgrid-config-generator/config/jobs/org/repo/org-repo-master-periodics.yaml
test/testgrid-config-generator/expected/redhat-openshift-ocp-release-4.2-informing.yaml
test/testgrid-config-generator/expected/redhat-openshift-okd-release-4.2-informing.yaml
test/testgrid-config-generator/run.sh

The doc for release informing jobs didn't make it clear that
we allow jobs from periodics that aren't part of release config.
Add support to the generator to read periodics that have the label
`ci.openshift.io/release-type=informing` and add them to dashboards
based on the existing `job-release` label (already in use by other
components like ci-chat-bot and release-controller). These become
part of the appropriate informing dashboard.

testgrid-config-generator: Support more informing jobs

---

pkg/jobconfig/files.go
pkg/jobconfig/files_test.go

Now that we zip all of our files, space constraints are not relevant any
longer and we can just shard simply by branch.

Collapse job configuration configmaps for master branch

---

pkg/jobconfig/files.go
pkg/jobconfig/files_test.go

Reverts openshift/ci-tools#192
The collapsed shard does not exist so the Prow components cannot use it yet. We need to do some preparation before we can merge this PR.

Revert "Collapse job configuration configmaps for master branch"

---

cmd/testgrid-config-generator/main.go
test/testgrid-config-generator/config/jobs/org/repo/org-repo-master-periodics.yaml
test/testgrid-config-generator/expected/redhat-openshift-ocp-release-4.2-informing.yaml
test/testgrid-config-generator/expected/redhat-openshift-okd-release-4.2-informing.yaml
test/testgrid-config-generator/run.sh

The publish steps inside the release config are not good indicators of ocp or okd. Instead, the naming conventions chosen by the release should be used.  `-openshift-origin-` means `okd` in a job, and `X.Y.Z-0.ci` for release name also means `okd`.  The okd release streams are downstream of CI and can be ignored for now.
Fix a bug where the periodics were added to both dashboards by checking for the correct convention. Also revert the run.sh script to be correct and add a generate mode.

testgrid-config-generator: Correct some faulty assumptions

---

cmd/ci-operator-configresolver/main.go
go.mod
pkg/load/configAgent.go
vendor/github.com/prometheus/client_golang/prometheus/promhttp/delegator.go
vendor/github.com/prometheus/client_golang/prometheus/promhttp/http.go
vendor/github.com/prometheus/client_golang/prometheus/promhttp/instrument_client.go
vendor/github.com/prometheus/client_golang/prometheus/promhttp/instrument_server.go
vendor/github.com/prometheus/client_golang/prometheus/push/deprecated.go
vendor/github.com/prometheus/client_golang/prometheus/push/push.go
vendor/k8s.io/test-infra/prow/metrics/BUILD.bazel
vendor/k8s.io/test-infra/prow/metrics/README.md
vendor/k8s.io/test-infra/prow/metrics/metrics.go
vendor/modules.txt

Adds 4 metrics to configresolver:
- HTTP response size
- Response time
- Error rate (sorted by error)
- Config reload time

ci-operator-configresolver: add metrics

---

cmd/autobumper/main.go

https://prow.svc.ci.openshift.org/view/gcs/origin-ci-test/logs/periodic-prow-image-autobump/64

Fix failures when no update of image is made

---

cmd/ci-operator-configresolver/main.go
pkg/load/configAgent.go

This PR improves some of the metrics based on some initial findings when running  the configresolver on the CI cluster.
Request Duration: It seems that most if not all requests were finishing under 0.005 seconds in some initial testing, so I've shrunk the duration sizes by 10x.
Request Size: The request size can be anywhere from a couple of bytes for errors up to ~7.5KB for the largest ci-operator config. The request size metric has been updated to better reflect that.
Config Reload Duration: In the cluster with the configs from master and 4.1-4.4, this seemed to range between ~750ms and 2.5s. The metrics buckets now reflect that.
I've also added a generic handler, so if we get 404s triggered by incorrect paths, those get logged as well.

ci-operator-configresolver: improve metrics buckets

---

pkg/load/configAgent.go

This piece of code was intended to keep internal state for fsnotify clean/consistent, but it looks like that is automatically handled by fsnotify when a REMOVE event is received, and this just triggers a lot of errors.

pkg/load/configAgent.go: don't call fsnotify.Remove on REMOVE event

---

cmd/ci-operator-prowgen/main.go

This PR adds the `ci-operator-configresolver` flags to `prowgen` job generation. Before rolling out the new configresolver flags to all jobs, we will only add the flags to this repo's jobs to make sure we don't break everything.

prowgen: add configresolver flags to ci-tools repo

---

cmd/ci-operator-configresolver/main.go
pkg/load/configAgent.go

This expands the bucket sizes for response size (previous buckets were based off of YAML config sizes, not JSON which is larger; the largest JSON response with current configs is 10471 bytes) and adds more levels for configresolver reload times, as the 0.95 and 0.99 quantile times pushed up against the upper 3 second bucket quite a lot.
This also changes some debug statements that could generate 100s of MB per hour to trace statements instead, as they are overly verbose for most debugging purposes.

configresolver: improve metrics buckets and change logging

---

cmd/testgrid-config-generator/main.go
test/testgrid-config-generator/expected/groups.yaml
test/testgrid-config-generator/expected/redhat-openshift-informing.yaml
test/testgrid-config-generator/expected/redhat-openshift-release-4.1-blocking-ci.yaml
test/testgrid-config-generator/expected/redhat-openshift-release-4.1-informing-ci.yaml
test/testgrid-config-generator/expected/redhat-openshift-release-4.2-blocking-ci.yaml
test/testgrid-config-generator/expected/redhat-openshift-release-4.2-blocking-ocp.yaml
test/testgrid-config-generator/expected/redhat-openshift-release-4.2-informing-ci.yaml
test/testgrid-config-generator/expected/redhat-openshift-release-4.2-informing-ocp.yaml

Add a new generic informing dashboard for openshift to cover jobs
that fall outside the release spectrum but are still relevant.
Restructure the naming so that we use 'ci' instead of 'okd' (which
was not accurate), and also leave fixes for when we correct the
job naming in prow.
Finally, order the naming so that it is product-release-type-source
and so that the OCP and CI tabs are next to each other - CI is a
leading indicator for OCP, not a separate product.

testgrid-config-generator: Update naming and dashboard ordering

---

pkg/load/load.go
pkg/rehearse/jobs.go
pkg/rehearse/jobs_test.go

~~Add a flag to `ci-operator` to enable a "rehearse" mode, which simply disables use of the configresolver by preventing the creation of the `load.ResolverInfo` that `load.Config()` uses for the configresolver.~~
~~`pj-rehearse` has been updated to make use of this as well, adding the `--rehearse` flag to all rehearsal jobs that use the `ci-operator` command.~~
The way this is handled has been redone. Now `pj-rehearse` looks at the `Args` for all rehearsal jobs that use the `ci-operator` commands and removes all configresolver configuration args.

pj-rehearse: remove configresolver flags from rehearsals

---

cmd/ci-operator-prowgen/main.go
cmd/ci-operator-prowgen/main_test.go
test/prowgen-integration/data/output/jobs/subdir/repo/subdir-repo-master-presubmits.yaml
test/prowgen-integration/data/output/jobs/super/duper/super-duper-master-periodics.yaml
test/prowgen-integration/data/output/jobs/super/duper/super-duper-master-postsubmits.yaml
test/prowgen-integration/data/output/jobs/super/duper/super-duper-master-presubmits.yaml
test/prowgen-integration/data/output/jobs/super/duper/super-duper-master-removed-promotion-presubmits.yaml
test/prowgen-integration/data/output/jobs/super/duper/super-duper-release-3.11-postsubmits.yaml
test/prowgen-integration/data/output/jobs/super/duper/super-duper-release-3.11-presubmits.yaml

Make prowgen add `configresolver` flags to all `ci-operator` jobs (and update tests)

ci-operator-prowgen: enable configresolver for all jobs

---

cmd/testgrid-config-generator/main.go
test/testgrid-config-generator/expected/redhat-openshift-informing.yaml
test/testgrid-config-generator/expected/redhat-openshift-release-4.1-blocking-ci.yaml
test/testgrid-config-generator/expected/redhat-openshift-release-4.1-informing-ci.yaml
test/testgrid-config-generator/expected/redhat-openshift-release-4.2-blocking-ci.yaml
test/testgrid-config-generator/expected/redhat-openshift-release-4.2-blocking-ocp.yaml
test/testgrid-config-generator/expected/redhat-openshift-release-4.2-informing-ci.yaml
test/testgrid-config-generator/expected/redhat-openshift-release-4.2-informing-ocp.yaml

This better reflects actual health and the summarizer will take it into
account.

testgrid-config-generator: Filter the monitor cluster test from testgrid

---

cmd/ci-operator-prowgen/main.go
pkg/api/config.go
pkg/api/types.go
pkg/load/load_test.go

This template has been added in https://github.com/openshift/release/pull/5388.
This lines up the needed steps in prowgen for this to be correctly picked up and usable in CI configs.

Add UPI-src template to prowgen.

---

cmd/blocking-issue-creator/main.go

This makes it easier to grep for things which might eventually cause an terminal failure [like][1]:
```
level=fatal msg="Could not publish merge blocking issues." error="<nil>"
```
You can already find those by grepping for `level=error`, since we only use error logging before setting `failed=true`, which you can confirm with:
```console
$ git grep -1 'logger.*Error\|failed = true' cmd/blocking-issue-creator/
```
But "there's already some consistency" shouldn't block us from adding the additional consistency I'm adding here ;).
[1]: https://prow.svc.ci.openshift.org/view/gcs/origin-ci-test/logs/periodic-openshift-release-merge-blockers/692

cmd/blocking-issue-creator: Use "Failed to ..." for all failing errors

---

cmd/blocking-issue-creator/main.go

This may already seem pretty obvious, but folks like me who aren't as familiar with the registry configs for image promotion might appreciate the extra hand-holding.  And being a bit noisy in debug logs doesn't seem like a problem ;).

cmd/blocking-issue-creator: Log reason for skipping a config

---

cmd/ci-operator-prowgen/main.go
pkg/config/load.go
test/prowgen-integration/data/input/config/private/duper/.config.prowgen
test/prowgen-integration/data/input/config/private/duper/private-duper-master.yaml
test/prowgen-integration/data/output/jobs/private/duper/private-duper-master-periodics.yaml
test/prowgen-integration/data/output/jobs/private/duper/private-duper-master-postsubmits.yaml
test/prowgen-integration/data/output/jobs/private/duper/private-duper-master-presubmits.yaml

Now the config contains only one field `private: bool`.
When we detect this in any repo's ci-op config folder, we generate jobs with the bot's secret mounted and add the `ssh-key-path` argument to ci-operator's command.

[prowgen] Introduce prowgen configuration files.

---

cmd/ipi-deprovision/ipi-deprovision.sh

Sometimes we get stuck on one cluster, for example because [AWS fumbled a load balancer deletion][1].  By shuffling the results, we'll gradually nip off any deletable clusters instead of having them pile up while we're blocking on the same hung-up cluster with each run.
[1]: https://bugzilla.redhat.com/show_bug.cgi?id=1760616

cmd/ipi-deprovision: Shuffle cluster IDs

---

pkg/load/load.go
pkg/load/load_test.go

This PR makes ci-operator use the configresolver result by default for all repos

ci-operator: use configresolver for all repos

---

pkg/steps/release/create_release.go

We were importing into (frequently) the release configuration namespace, so ocp/release:latest and ocp/release:initial and were getting set by the PR.  Instead we should create those in the job namespace.  Did not fail the run because we don't use the reference in the namespace (we use the exact value provided to the test).

Import initial release into test namespace correctly

---

pkg/load/agent_utils.go
pkg/load/configAgent.go

This PR refactors `pkg/load/configAgent.go` to make it more generic and make implementing a similar `registryAgent.go` cleaner.
- Renames `agent` to `configAgent`
- Renames `reloadTimeMetric` to `configReloadTimeMetric`
- Makes `reloadWatcher` more generic by not requiring a `configAgent` in the function signature
- Move generic agent helpers to their own file

pkg/load/configAgent: make some functions more generic

---

pkg/load/registryAgent.go

Add `registryAgent`, which will be used by the `ci-operator-configresolver`
This is a subset of the changes from #248

pkg/load: add registryAgent

---

pkg/api/types.go
pkg/defaults/defaults.go

Use the same mechanism as multi-stage tests to acquire a lease for the cluster
type (if one is provided).
To enable a gradual migration, ignore templates without a specific parameter.
This allows the code to be merged without changes to existing jobs.  Each
template can be migrated by adding the special parameter and removing the lease
container.  When all are migrated, the parameter and the code that checks for
it can be removed.
Successfully tested locally with one of the `openshift/origin` jobs.

ci-operator: use lease step for templates

---

pkg/api/types.go

These were changed at some point from `azure` to `azure4`.

pkg/api: fix Azure profile strings

---

cmd/ci-operator-prowgen/main.go
cmd/ci-operator-prowgen/main_test.go
test/prowgen-integration/data/output/jobs/private-org/duper/private-org-duper-master-presubmits.yaml
test/prowgen-integration/data/output/jobs/private/duper/private-duper-master-periodics.yaml
test/prowgen-integration/data/output/jobs/private/duper/private-duper-master-postsubmits.yaml
test/prowgen-integration/data/output/jobs/private/duper/private-duper-master-presubmits.yaml

This is a low-cost way how to make sure private and public jobs are shown in the correct Deck instance. This way we do not need to sync repos to the `hidden_repos` config for deck, or implement `hidden_orgs` yet.
We may eventually decide to implement `hidden_orgs` anyway, as it's the most clean solution, but this saves us from it being urgent.
/cc @droslean @openshift/openshift-team-developer-productivity-test-platform

prowgen: Generate private jobs as `hidden: true`

---

pkg/load/agent_utils.go
pkg/load/load.go
test/ci-operator-configresolver-integration/run.sh

Add validation during registry loading. This makes the registry contents much more consistent and prevents naming collisions. It should also significantly reduce the complexity of implementing rehearsals for the changes in the step_registry.
This also adds error logging for registry loading errors that occur in the reload watcher and fixes a bug in the configresolver integration tests.

pkg/load: add validation during registry loading

---

CONFIGURATION.md
cmd/ci-operator-prowgen/main.go
pkg/api/config.go
pkg/api/types.go

This patch adds ovirt as a valid cluster profile
Signed-off-by: Gal Zaidman <gzaidman@redhat.com>

Add ovirt as a cluster profile

---

pkg/lease/client.go

The following sequence happens in production where `boskos` takes an
extraordinarily long time to respond to each operation (JSON lines are
the server logs):
```
2019-11-12 16:50:36 debug: start update
2019-11-12 16:50:48 debug: start release
{"level":"info","msg":"Updated resource 0cff6b17-983f-450e-97a9-0a495ea37627","time":"2019-11-12T16:51:51Z"}
2019-11-12 16:51:51 debug: end update
2019-11-12 16:51:51 debug: start update
{"level":"info","msg":"Done with resource 0cff6b17-983f-450e-97a9-0a495ea37627, set to state free","time":"2019-11-12T16:53:11Z"}
2019-11-12 16:53:12 debug: end release
2019-11-12 16:53:12 debug: end update
2019-11-12 16:53:12 cleanup: Deleting pods with label ci.openshift.io/multi-stage-test=e2e
2019-11-12 16:53:12 failed to update leases: failed to update lease …
```

pkg/lease: increase mutual exclusion

---

cmd/ci-operator/main.go
pkg/api/config.go
pkg/api/config_test.go

Regardless of the origin, `ci-operator` should never receive a
configuration with unresolved multi-stage tests.  Currently, if that
happens, the test is ignored.
This check generates a validation error even if the test is not targeted
because limiting it would require extensive changes.

pkg/api: validate configuration is fully-resolved

---

CONFIGURATION.md
cmd/ci-operator/main.go
pkg/defaults/defaults.go
pkg/util/client.go
pkg/util/client_test.go

Backwards compatibility should be there, i.e., it should not break `ci-operator` pod after merge.

Add kubeconfig arg to ci-operator

---

cmd/ci-operator-prowgen/main.go

Previously, when `additional_images` were present but `images` were not,
prowgen did not create a promoting postsubmit.

prowgen: Generate promoting postsubmit on only additional_images

---

cmd/ci-operator-prowgen/main.go

This has never caused someone to choose a shorter name and is only spam
today.

Remove warning on job name length

---

cmd/ci-operator/main.go
cmd/ci-operator/main_test.go

after #252 the jobs couldn't report to testgrid.  This patch is fixing that.

convert metadata revision to string and refactor the tests

---

pkg/api/config.go
pkg/api/types.go
pkg/steps/artifacts.go
pkg/steps/multi_stage.go
pkg/steps/multi_stage_test.go
pkg/steps/pod.go
test/ci-operator-integration/base/expected_files/expected.json

When a user runs a test they should be able to set their artifacts
directory to something other than the default, but they should not need
to do anything special to get the default. All good tests create
artifacts so this should not make much of a difference for the amount of
containers we actually run.

Default artifacts directory, set env

---

cmd/ci-operator-prowgen/main.go
cmd/ci-operator-prowgen/main_test.go
test/prowgen-integration/data/output/jobs/super/duper/super-duper-release-3.11-presubmits.yaml

Previously, it was possible to not attempt to build all promoted images
in any of the PR presubmits. Make the `images` presubmit target all
images that are promoted, including those in `additional_images`.
Resolves: https://github.com/openshift/ci-tools/issues/284

prowgen: build all promoted images in `images` presubmits

---

pkg/api/config.go
pkg/api/types.go
pkg/steps/artifacts.go
pkg/steps/multi_stage.go
pkg/steps/multi_stage_test.go
pkg/steps/pod.go
test/ci-operator-integration/base/expected_files/expected.json

Reverts openshift/ci-tools#286
Jobs starting to fail
```console
failed to create or restart test pod: unable to create pod: Pod "e2e-prod-4.2" is invalid: spec.containers[1].volumeMounts[0].name: Not found: "artifacts"
```
https://prow.svc.ci.openshift.org/view/gcs/origin-ci-test/logs/periodic-ci-openshift-osde2e-master-e2e-prod-4.2/78

Revert "Default artifacts directory, set env"

---

cmd/autoowners/README.md

Console syntax highlighting, consistent `$` `PS1` prompt instead of splitting between `$` and `#`, backticks around the `OWNERS` filename literal, fixed link to the now-in-a-different-repo origin jobs.

cmd/autoowners/README: openshift/origin link and other cleanup

---

cmd/ci-operator-prowgen/main.go
cmd/ci-operator-prowgen/main_test.go

Last requirement for https://github.com/openshift/release/pull/5802.
Rehearsals work as expected (even the ones with flakes =):
https://prow.svc.ci.openshift.org/view/gcs/origin-ci-test/pr-logs/pull/openshift_release/5802/rehearse-5802-pull-ci-openshift-origin-master-e2e-aws/6
https://prow.svc.ci.openshift.org/view/gcs/origin-ci-test/pr-logs/pull/openshift_release/5802/rehearse-5802-pull-ci-openshift-origin-master-e2e-azure/6
https://prow.svc.ci.openshift.org/view/gcs/origin-ci-test/pr-logs/pull/openshift_release/5802/rehearse-5802-pull-ci-openshift-origin-master-e2e-cmd/6
On Monday, I'll open the corresponding PR in `openshift/release`, merge all,
and monitor.  If no disruption occurs, we can move on to replacing all lease
containers and finally remove the temporary code.
/hold

prowgen: add --lease-server to one test type

---

Makefile
cmd/repo-init/main.go
cmd/repo-init/main_test.go
images/repo-init/Dockerfile
pkg/api/types.go
pkg/config/load.go
pkg/diffs/diffs.go
test/repo-init-integration/expected/Makefile
test/repo-init-integration/expected/ci-operator/config/openshift/ci-tools/openshift-ci-tools-master.yaml
test/repo-init-integration/expected/ci-operator/config/openshift/origin/openshift-origin-master.yaml
test/repo-init-integration/expected/ci-operator/config/org/other/org-other-nonstandard.yaml
test/repo-init-integration/expected/ci-operator/config/org/repo/org-repo-master.yaml
test/repo-init-integration/expected/ci-operator/jobs/openshift/ci-tools/openshift-ci-tools-master-postsubmits.yaml
test/repo-init-integration/expected/ci-operator/jobs/openshift/ci-tools/openshift-ci-tools-master-presubmits.yaml
test/repo-init-integration/expected/ci-operator/jobs/openshift/origin/openshift-origin-master-postsubmits.yaml
test/repo-init-integration/expected/ci-operator/jobs/openshift/origin/openshift-origin-master-presubmits.yaml
test/repo-init-integration/expected/ci-operator/jobs/org/other/org-other-nonstandard-presubmits.yaml
test/repo-init-integration/expected/ci-operator/jobs/org/repo/org-repo-master-presubmits.yaml
test/repo-init-integration/expected/core-services/prow/02_config/_config.yaml
test/repo-init-integration/expected/core-services/prow/02_config/_plugins.yaml
test/repo-init-integration/input/Makefile
test/repo-init-integration/input/ci-operator/config/openshift/ci-tools/openshift-ci-tools-master.yaml
test/repo-init-integration/input/ci-operator/config/openshift/origin/openshift-origin-master.yaml
test/repo-init-integration/input/core-services/prow/02_config/_config.yaml
test/repo-init-integration/input/core-services/prow/02_config/_plugins.yaml
test/repo-init-integration/run.sh

Adding a new repository to the `openshift/release` repository is
nontrivial and requires understanding of three or four different
configuration formats. New component authors rarely care about any of
the nuance on their first pull and will be happy with a smaller set of
options and more defaults. This tool aims to boil down the initial
configuration to a set of simple questions and lets the user edit that
as necessary afterword.
TODO:

Add an interactive tool to bootstrap a repo's config

---

cmd/repo-init/main.go
test/repo-init-integration/expected/Makefile
test/repo-init-integration/input/Makefile
test/repo-init-integration/run.sh

Since we're running repo-init in a container in the first place, this
would require nested virtualization and all sorts of craziness, so we
can just chain the make targets instead.

Don't call out to make jobs in repo-init

---

pkg/steps/multi_stage.go
pkg/steps/multi_stage_test.go
test/ci-operator-integration/multi-stage/expected/hyperkube.json
test/ci-operator-integration/multi-stage/expected/installer.json

depends on #286 
How were you expecting that users use this dir if it was not exposed via some var?

Expose shared directory for users in test continers

---

cmd/ci-operator-prowgen/main.go

Follow up of https://github.com/openshift/ci-tools/pull/290/files
/hold
need to prepare for the PR to recover breaking changes

Generate pull-secret arg for migrated jobs

---

pkg/registry/graph.go
pkg/registry/graph_test.go

This adds a registry graph, which allows a user to identify all ancestors or descendants of a registry component as well as detect any cycles in the chains.
Will be used in pj-rehearse and greatly simplify #267

pkg/registry: add registry graph

---

cmd/repo-init/main.go
cmd/repo-init/main_test.go
test/repo-init-integration/expected/ci-operator/config/org/repo/org-repo-master.yaml

repo-init: correctly choose origin base, golang 1.13

---

pkg/lease/client.go
pkg/lease/client_test.go
pkg/lease/fake.go
pkg/steps/lease.go

Many resource types have very low maximum values and rely on waiting for
extended periods of time until one is available.
The hard-coded timeout period used is based on the original templates
(https://github.com/openshift/release/pull/5802).

pkg/lease: use AcquireWait instead of Acquire

---

pkg/defaults/defaults.go
pkg/steps/clusterinstall/template.go
test/ci-operator-integration/base/run.sh

Clean the temporary code to filter templates, which will now be
permanent since not all templates actually had a `lease` container, as
initially thought.  The logic is changed slightly, but should be
practically equivalent.

ci-operator: use lease client in upgrade tests

---

pkg/defaults/defaults.go
pkg/steps/lease.go

Whether a lease client was provided cannot be checked in that module
because it does not have the information of which steps are targeted
(and which are not).

pkg/defaults: defer lease client validation

---

cmd/ci-operator-prowgen/main.go
cmd/pj-rehearse/main.go
pkg/config/load.go
pkg/config/release.go
pkg/jobconfig/files.go
pkg/rehearse/jobs.go
pkg/rehearse/metrics.go
test/pj-rehearse-integration/candidate/ci-operator/config/super/trooper/super-trooper-master.yaml
test/pj-rehearse-integration/candidate/ci-operator/jobs/super/duper/super-duper-ciop-cfg-change-presubmits.yaml
test/pj-rehearse-integration/candidate/ci-operator/jobs/super/duper/super-duper-master-presubmits.yaml
test/pj-rehearse-integration/candidate/ci-operator/jobs/super/duper/super-duper-periodics.yaml
test/pj-rehearse-integration/candidate/ci-operator/jobs/super/trooper/super-trooper-master-presubmits.yaml
test/pj-rehearse-integration/expected.yaml
test/pj-rehearse-integration/master/ci-operator/config/super/trooper/super-trooper-master.yaml
test/pj-rehearse-integration/master/ci-operator/jobs/super/duper/super-duper-ciop-cfg-change-presubmits.yaml
test/pj-rehearse-integration/master/ci-operator/jobs/super/duper/super-duper-master-presubmits.yaml
test/pj-rehearse-integration/master/ci-operator/jobs/super/duper/super-duper-periodics.yaml
test/pj-rehearse-integration/master/ci-operator/jobs/super/trooper/super-trooper-master-presubmits.yaml
test/pj-rehearse-integration/run.sh

This PR adds support for choosing presubmits to rehearse based on changed registry steps.

pj-rehearse: implement rehearsing of changed registry steps

---

pkg/lease/client.go
pkg/lease/client_test.go
pkg/lease/fake.go
pkg/steps/lease_test.go

This was another regression between the usage in `boskosctl` and the
in-house lease adaptation.

lease: use acquire with priority

---

pkg/load/load.go

This adds cycle detection to the step registry loader. This is an important second step of validation that prevents the resolver from encountering infinite loops in the registry.

registry: create graph in loadRegistry to detect cycles

---

cmd/ci-operator-prowgen/main.go
cmd/ci-operator-prowgen/main_test.go
test/prowgen-integration/data/output/jobs/private-org/duper/private-org-duper-master-presubmits.yaml
test/prowgen-integration/data/output/jobs/private/duper/private-duper-master-periodics.yaml
test/prowgen-integration/data/output/jobs/private/duper/private-duper-master-postsubmits.yaml
test/prowgen-integration/data/output/jobs/private/duper/private-duper-master-presubmits.yaml

Since `clonerefs` now supports OAuth authentication, we want to get rid of the SSH configuration and use an OAuth token instead.
Note: OAuth requires a `cloneURI` with a scheme included. 
/cc @petr-muller @stevekuznetsov

[prowgen] Generate private jobs by using OAuth token instead of SSH 

---

pkg/steps/template.go

`waitForPodCompletion` is unreliable, sometimes failing to report an
error when the test is cancelled.  Compare:
https://prow.svc.ci.openshift.org/view/gcs/origin-ci-test/pr-logs/pull/openshift_release/6331/rehearse-6331-pull-ci-openshift-origin-master-e2e-cmd/5
https://prow.svc.ci.openshift.org/view/gcs/origin-ci-test/pr-logs/pull/openshift_machine-config-operator/1311/pull-ci-openshift-machine-config-operator-fcos-e2e-aws/124
Force a failure by testing if the cancelling context is done.

pkg/steps/template: force a failure when cancelled

---

cmd/ci-operator/main.go
pkg/defaults/defaults.go
pkg/steps/lease.go
pkg/steps/lease_test.go

Input resolution, required to determine the namespace and, as a
consequence, the lease owner, is done after the steps are created.

ci-operator: postpone lease client creation

---

test/ci-operator-integration/base/run.sh

Being negligent about the parameters prevented us from catching
https://github.com/openshift/ci-tools/pull/321 with the existing
integration tests:
```
$ make install integration-ci-operator > /dev/null
$ git revert --no-commit b129c64d35903697444b2fdc4e2e25b58779d7ce
$ make install integration-ci-operator > /dev/null
ERROR: ci-operator failed.
2019/12/13 15:27:42 Resolved source https://github.com/openshift/ci-tools to master@af8a90a2, merging: #1234 538680df @droslean
2019/12/13 15:27:42 Ran for 0s
error: failed to generate steps from config: step "e2e-aws-upgrade" needs a lease but no lease client provided
make: *** [Makefile:48: integration-ci-operator] Error 1
```

Remove unnecessary parameter in integration tests

---

pkg/steps/clusterinstall/template.go

Bringing over a number of changes which have landed in
ci-operator/templates/openshift/installer/cluster-launch-installer-e2e.yaml
as of openshift/release@016eb4ed27 (Merge pull request
openshift/release#6505 from hongkailiu/clusterReaders, 2019-12-19).
One series was improved kill logic:
* openshift/release@9cd158adf3 (template: Use a more correct kill
command, 2019-12-03, openshift/release#6223).
* openshift/release@d0744e520d (exit with 0 even if kill failed,
2019-12-09, openshift/release#6295)
Another series was around AWS instance console logs:
* openshift/release@e102a16d89
(ci-operator/templates/openshift/installer/cluster-launch-installer-e2e:
Gather node console logs on AWS, 2019-12-02,
openshift/release#6189).
* openshift/release@26fde70045 …

pkg/steps/clusterinstall/template: Sync with openshift/release

---

pkg/steps/clusterinstall/template.go

* Set LC_ALL so that py2-based `aws ec2 get-console-output` wouldn't crash with UnicodeEncodeError
* Store only text (json by default) in output file
Backport of https://github.com/openshift/release/pull/6536
/cc @wking

Set LC_ALL in artifacts so that aws cli would convert unicode correctly

---

pkg/rehearse/jobs.go
pkg/rehearse/jobs_test.go
vendor/github.com/google/go-cmp/cmp/cmpopts/equate.go
vendor/github.com/google/go-cmp/cmp/cmpopts/ignore.go
vendor/github.com/google/go-cmp/cmp/cmpopts/sort.go
vendor/github.com/google/go-cmp/cmp/cmpopts/struct_filter.go
vendor/github.com/google/go-cmp/cmp/cmpopts/xform.go
vendor/modules.txt

Rehearsals of hidden jobs are also hidden jobs, but they are "special"
by being hidden jobs on a repository that should not have hidden
jobs (openshift/release). This causes problems because the config makes
jobs on `openshift/release` to have URLs in GH to the public Deck/Spyglass
instance, but that instance does not have access to the underlying private
storage so it cannot show the rehearsal's logs and artifacts.
(see the `
ci/rehearse/openshift-priv/ci-experiment-origin/master/e2e-cmd`
rehearsal on  https://github.com/openshift/release/pull/6536 for an example)
Additionally, whoever triggers a rehearsal of a hidden job is unlikely to
have access to the Deck instance that shows hidden jobs, so they would not
be able to access the logs even if the URL were correct.
Therefore, we make …

 Make rehearsals of hidden jobs have `skip_report: true`

---

pkg/diffs/diffs.go
pkg/diffs/diffs_test.go

Previously we have mistakenly bailed out early from the check if a given
job uses a ci-operator config, whenever we encountered items that
populated an envvar from something else than a ConfigMap key reference.
Fix this so that we check in all EnvVar items.
Fixes: #350 #339 
---
Additionally, I migrated the unit tests to use `cmp.Diff` instead of (deprecated) `diff.Object*Diff` family, because the latter was panicking on the unexported fields in job structs.

rehearse: fix detection of jobs affected by ciop config changes

---

pkg/steps/artifacts.go

This isn't actually measuring in mebibytes.

steps/artifacts: fix artifact size suffix

---

pkg/load/load.go
pkg/load/load_test.go
pkg/registry/graph.go
pkg/registry/graph_test.go
pkg/registry/resolver.go
pkg/registry/resolver_test.go

Add new types for the maps of registry components. This shortens method signatures and type declarations and makes it easier to implement new functions that work with the registry.

pkg/registry: add types for maps of registry components

---

cmd/private-org-sync/README.md
cmd/private-org-sync/main.go
cmd/private-org-sync/main_test.go
pkg/promotion/promotion.go

This tool automatically syncs code from which "official" images are
built from their public git repo locations to their mirrors in private
GitHub organization. It is intended to be run in a Prow periodic job
with an interval of less than an hour.
Both source and destination are queried with `git ls-remote`: if they are
already in sync, no further git operations are done. When the destination is
detected to be an empty repo, full `git fetch` is done against a source,
and FETCH_HEAD is then pushed to the destination. When the destination
is a non-empty repository, `git fetch --depth X` is done against the
source and the resulting shallow branch tip is attempted to be pushed.
When this fails, X is exponentially increased and the fetch is retried.
When a threshold is hit, the shallow branch …

Add a tool for syncing git content between mirrors

---

images/private-org-sync/Dockerfile

(I know I need to change ci-op config to actually base the thing on centos:8)

Install git for private-org-sync and base it on centos:8

---

cmd/private-org-sync/main.go

Unfortunately error messages change between git versions, I was seeeing
this one with `git 2.18.1` which is the version in CentOS 8 which I want
to use as a base to run in production.

private-org-sync: add another retried error pattern

---

cmd/testgrid-config-generator/main.go
test/testgrid-config-generator/expected/redhat-openshift-informing.yaml
test/testgrid-config-generator/expected/redhat-openshift-ocp-release-4.1-blocking.yaml
test/testgrid-config-generator/expected/redhat-openshift-ocp-release-4.1-informing.yaml
test/testgrid-config-generator/expected/redhat-openshift-ocp-release-4.2-blocking.yaml
test/testgrid-config-generator/expected/redhat-openshift-ocp-release-4.2-informing.yaml

Many periodics are on 24h or 48h intervals, so test grid's default of 7
days doesn't show much info. For those jobs, use a heuristic to try and get
100 test results based on the configured interval of the periodic, between
7d (the default) and 60d (a reasonable max).
Release controller jobs are not changed because they are run at intervals
outside of our control.
Also:
testgrid: Exclude the test container summary junit from testgrid
The test container junit (generated by ci-operator) is already summarized
by the overall test result (if we fail test, we fail the overall run), but
the summary page for test grid will count it as part of the flake rate and
failure percentage. A downside of this change is that if the test container
breaks test grid won't show a specific red box (but prow …

testgrid: Gather more testgrid results for jobs that run less frequently

---

cmd/applyconfig/applyconfig.go
cmd/applyconfig/applyconfig_test.go

We are getting bitten by not catching validation failures in our dry-run
presubmit, so we should explicitly ask for validation in order to catch
this.

applyconfig: use --validate

---

cmd/applyconfig/applyconfig.go
cmd/applyconfig/applyconfig_test.go

Reverts openshift/ci-tools#371
Looks like a ton of our config does not pass this, breaking merges to openshift/release:
```
time="2020-01-15T13:14:19Z" level=error msg="oc apply -f core-services/base-ci-images/images-ocp.yaml --validate --dry-run: failed to apply\nerror: error validating \"core-services/base-ci-images/images-ocp.yaml\": error validating data: ValidationError(ImageStream): missing required field \"spec\" in com.github.openshift.api.image.v1.ImageStream; if you choose to ignore these errors, turn validation off with --validate=false\n"
time="2020-01-15T13:14:20Z" level=error msg="oc apply -f core-services/base-ci-images/images-origin.yaml --validate --dry-run: failed to apply\nerror: error validating \"core-services/base-ci-images/images-origin.yaml\": error validating …
```

Revert "applyconfig: use --validate"

---

cmd/private-org-sync/main.go
cmd/private-org-sync/main_test.go

This saves hundreds of useless git executions in the current state when `openshift-priv` is empty.

private-org-sync: fail-fast when destination does not exist

---

pkg/steps/clusterinstall/template.go

We need to pass the TEST_OPTIONS flag through to the test in order
to properly test rollbacks.

ci-operator: Update template from latest

---

pkg/registry/graph.go

Fix panics for registry components that include a chain or reference that does not actually exist in the registry. This was caught by the graph, but through a panic. Now the graph detects the problem and returns a proper error message.

pkg/registry/graph: fix panics for invalid regsitry components

---

pkg/steps/template.go

@stevekuznetsov @openshift/openshift-team-developer-productivity-platform @petr-muller @bbguimaraes @droslean @hongkailiu
I believe there is still a small race condition in the template wait logic after my fix from last week.  Though thankfully this one results in the test failing prematurely vs. letting anything pass.
I've seen it a couple of times now.  The latest incarnation is https://prow.svc.ci.openshift.org/view/gcs/origin-ci-test/pr-logs/pull/openshift_cluster-samples-operator/220/pull-ci-openshift-cluster-samples-operator-master-e2e-aws-image-ecosystem/789
The error message is `could not wait for template instance to be ready: resource name may not be empty`
The error comes from the core k8s rest code complaining that we've called `Get` with an empty key ... …

fix wait for template instance failing on get with empty key

---

cmd/ci-secret-bootstrap/main.go
pkg/bitwarden/bitwarden.go
pkg/bitwarden/cli.go
pkg/bitwarden/cli_test.go
pkg/bitwarden/fake.go
pkg/util/client.go
pkg/util/client_test.go

* Load kubeconfig from default e.g., $HOME/.kube/config if
`--kubeconfig` is not set.
* Log standard err when bw cmd failed
* Add logout to avoid "you have already logged in" error.

Improve the secret-bootstrap tool

---

pkg/load/configAgent.go
pkg/load/load.go
pkg/load/load_test.go
pkg/load/registryAgent.go
pkg/registry/graph.go
pkg/registry/graph_test.go
pkg/registry/resolver.go
pkg/registry/resolver_test.go
pkg/webreg/webreg.go

This changes the `ReferenceMap`, `ChainMap`, and `WorkflowMap` type names to `ReferenceByName`, `ChainByName`, and `WorkflowByName` respectively. It also changes the name of the `GetFilenameToConfig` function in `ConfigAgent` to `GetAll`. This keeps the code simpler and less fragile as it disconnects the names from the implementation.

registry: refactor naming for component maps

---

cmd/ipi-deprovision/ipi-deprovision.sh

ipi-deprovisioner: do not prematurely exit on no-matching grep

---

pkg/steps/template.go

Follow up https://coreos.slack.com/archives/CEKNRGF25/p1579544330056200
Some check passed without running the test pod from the template.
/assign @petr-muller @gabemontero

Revertd92df0facdccf541f126d679750e214bd33c7c9d

---

pkg/steps/template.go

Another shot at the issue described in https://github.com/openshift/ci-tools/pull/359, essentially a re-revert of https://github.com/openshift/ci-tools/pull/392 with additional fixes.
Previously, it was possible for `waitForTemplateInstanceReady` to exit
with `instance, nil` (no error) even when `templateInstanceReady`
returned an error. This then likely caused the cases where ci-operator
treat this operation as success and never run any tests (it continued to
wait until no containers were running, which was true for the template
that failed to instantiate).
Fix this so that the error from `waitForTemplateInstanceReady` is
propagated to the polling method return code. This way the polling ends
only either on timeout (returning an error), or when
`templateInstanceReady` returns ready=true. …

ci-operator: fixes in template-handling logic

---

cmd/ipi-deprovision/ipi-deprovision.sh

```
$ export CLUSTER_TTL='30 minutes ago'
$ export gce_cluster_age_cutoff="$(TZ=":America/Los_Angeles" date --date="${CLUSTER_TTL}-4 hours" '+%Y-%m-%dT%H:%M%z')"
$ echo "deprovisioning clusters with a creationTimestamp before ${gce_cluster_age_cutoff} in GCE ..."
deprovisioning clusters with a creationTimestamp before 2020-01-23T08:33-0800 in GCE ...
$ export FILTER="creationTimestamp.date('%Y-%m-%dT%H:%M%z')<${gce_cluster_age_cutoff} AND name~'ci-*'"
$ gcloud --project=openshift-gce-devel-ci compute networks list --filter "${FILTER}" --format "value(name, creationTimestamp.date('%Y-%m-%dT%H:%M%z'))"
ci-op-20c3i7xz-dee8c    2020-01-22T22:17-0800
ci-op-70smjrrs-dee8c    2020-01-21T21:25-0800
ci-op-97kvk-network     2020-01-21T04:39-0800 …
```

ipi-deprovision: use US pacific time zone

---

cmd/ci-secret-bootstrap/main.go
cmd/ci-secret-bootstrap/main_test.go
pkg/bitwarden/cli.go
pkg/bitwarden/cli_test.go

* bw-get-attachment saves the attachment in a file, the output
is the file path. We need to read that file. In the fix, we specify
the path with `--output` of bw-cmd.
* Consider the default value of secret type to fix [1].
1. error log
```
time="2020-01-24T19:42:41Z" level=fatal msg="Failed to update secrets." error="cannot change secret type from \"Opaque\" to \"\" (immutable file): default:ci/sentry-dsn"
```

Fix the bugs of ci-secret-bootstrap found in test

---

images/ci-operator-configresolver/Dockerfile
pkg/webreg/graphviz.go
pkg/webreg/graphviz_test.go
pkg/webreg/webreg.go

This PR adds graphical representations of workflows, jobs, and chains to the registry's web UI using graphviz. Since the `gographviz` library does not support nested subgraphs/clusters, generation of the dot file for graphviz was done using local functions instead.

pkg/webreg: add graphs

---

pkg/webreg/webreg.go

UI Improvements:
- Rename "Documentation" to "Description" in tables
- Add light dotted underline to UI elements with titles to
- Separate bread crumbs from site title
- Remove link from main page to reference, chain, workflows, and job subpages
- Add 10px of padding to top of headings and paragraphs

webreg: various small style improvements

---

pkg/defaults/defaults.go
pkg/steps/multi_stage.go
pkg/steps/multi_stage_test.go
test/ci-operator-integration/multi-stage/expected/hyperkube.json
test/ci-operator-integration/multi-stage/expected/installer.json

This addresses two problems: allowing the `secret-wrapper` to update its
Secret and allowing tests to manipulate a limited set of objects in the
test namespace.
Template tests are "allowed" to create any kind of resource because they
are evaluated by the ci-operator ServiceAccount, an admin in the test
namespace.  Multi-stage tests currently use the same account as other
tests (`default`), so their set of allowed operations is much more
limited.
This commit creates:
- a ServiceAccount specific to each test
- a Role that can
- list/create RoleBindings
- get/list/create the test-specific Secret
- get imagestream/layers
- a RoleBinding that assigns the Role above and the
`system:image-puller` ClusterRole to the test's ServiceAccount

ci-operator multi-stage: create service account

---

cmd/secret-wrapper/main.go

The secret is always created by `ci-operator`, so this code was never
strictly necessary.  This way, the ServiceAccount used, which
transitively applies to the process executed by the wrapper, can be
restricted to just `update` the specific secret.  This is necessary
because:
- Although we never actually create the Secret, calls fail even if they
would result in an "already exists" error if the account does not have
`create` permission.
- `create` cannot be limited to a single secret:
https://github.com/kubernetes/kubernetes/issues/80295.

secret-wrapper: don't try to create the secret

---

pkg/lease/client.go
pkg/steps/lease.go

The CI NS TTL controller will remove namespaces that are inactive for
more than an hour. Therefore, it does not make sense for CI Operator to
wait for more than an hour while acquiring a lease, or the underlying
namespace will be removed.

lease: log when acquiring, lower timeout

---

pkg/steps/artifacts.go
pkg/steps/multi_stage.go
pkg/steps/multi_stage_test.go
test/ci-operator-integration/multi-stage/expected/hyperkube.json
test/ci-operator-integration/multi-stage/expected/installer.json

Add an annotation to pods created by multi-stage tests to write the logs of
all containers into the artifact directory, as is done for template tests.
The `prow.k8s.io/id` label is removed so logs are not collected once more
by the `artifact-uploader` controller.  Detailed discussion:
https://github.com/openshift/release/pull/6708#issuecomment-579772817

ci-operator multi-stage: save container logs

---

cmd/private-org-sync/main.go
cmd/private-org-sync/main_test.go

After https://github.com/openshift/release/pull/6963 we will expect all destinations to be existing repos. Hence, add an option that causes the tool to fail when the destination repo does not exist.
@openshift/openshift-team-developer-productivity-test-platform

private-org-sync: allow failing on missing destinations

---

cmd/ci-operator-prowgen/main.go
cmd/ci-operator-prowgen/main_test.go
pkg/config/load.go

This is needed for the new tool that syncs ci-operator configs.

Move prowgen config to config package

---

Makefile
cmd/ci-op-configs-mirror/main.go
test/ci-op-configs-mirror-integration/data/input/foo/bar/foo-bar-master.yaml
test/ci-op-configs-mirror-integration/data/input/super/duper/super-duper-master.yaml
test/ci-op-configs-mirror-integration/data/input/super/trooper/super-trooper-master.yaml
test/ci-op-configs-mirror-integration/expected_files/expected.yaml
test/ci-op-configs-mirror-integration/expected_files/expected_skipped.yaml
test/ci-op-configs-mirror-integration/run.sh

This is a simple tool that syncs ci-operator configuration files from a single or multiple organization to a single organization and generates a prowgen config file to mark the org as private.

Add tool to mirror ci-operator configs to a single private repo

---

Makefile
cmd/ci-op-configs-mirror/main.go
images/ci-op-configs-mirror/Dockerfile
test/ci-op-configs-mirror-integration/data/input/foo/bar/foo-bar-master.yaml
test/ci-op-configs-mirror-integration/data/input/super/duper/super-duper-master.yaml
test/ci-op-configs-mirror-integration/data/input/super/trooper/super-trooper-master.yaml
test/ci-op-configs-mirror-integration/data/output/foo/bar/foo-bar-master.yaml
test/ci-op-configs-mirror-integration/data/output/super-priv/duper/super-priv-duper-master.yaml
test/ci-op-configs-mirror-integration/data/output/super-priv/trooper/super-priv-trooper-master.yaml
test/ci-op-configs-mirror-integration/data/output/super/duper/super-duper-master.yaml
test/ci-op-configs-mirror-integration/data/output/super/trooper/super-trooper-master.yaml
test/ci-op-configs-mirror-integration/run.sh

This is a simple tool that syncs ci-operator configuration files from a single or multiple organization to a single organization with the ability to generate a prowgen config file to mark the org as private.
/cc @petr-muller @stevekuznetsov

Add tool to mirror ci-operator configs to a single repo

---

cmd/ci-operator/main.go
pkg/defaults/defaults.go
pkg/steps/git_source.go
pkg/steps/pipeline_image_cache.go
pkg/steps/project_image.go
pkg/steps/rpm_injection.go
pkg/steps/source.go
pkg/steps/source_test.go
test/ci-operator-integration/base/expected_files/expected_pull_secret.json
test/ci-operator-integration/base/run.sh

openshift/installer repo has builds which need accessimages in api.ci.
The default pull secret by build is from SA `builder` on the same cluster.
We use the pull secrets created with https://github.com/openshift/release/pull/6478 which contains oauth for both registries on api.ci and build01.
Verified by
https://github.com/openshift/release/pull/6420#issuecomment-567329232

Specify pull secret in build steps

---

cmd/ci-operator-configresolver/main.go

This adds an optional `jobs` arg that get's passed to the prow `jobAgent`. This allows us to properly account for repos that aren't directly listed in the main prow config.

configresolver: add jobs arg for configresolver's jobAgent

---

test/validate-prowgen-breaking-changes.sh

The git version that we were using was old enough to not know `-C` and
this was silently ignored because of us hiding it from the `errexit`
option by having the git execution in an `if`.

Fix silent breakage of breaking-change check

---

test/validate-prowgen-breaking-changes.sh

The git in our build root is too old to know `-C`.
Note: the job is currently expected to fail until https://github.com/openshift/release/pull/7107 merges

breaking-changes check: revert `git -C` to pushd/popd

---

cmd/ci-operator/main.go
pkg/load/configAgent.go
pkg/load/load.go
pkg/load/load_test.go
test/ci-operator-integration/multi-stage/run.sh

Upstreaming a simpler version of a patch I've had for months on my machine.
This requires a local copy of `openshift/release`, but is useful to test
changes to the registry locally (@petr-muller: FYI).

ci-operator: add flag to resolve steps

---

pkg/webreg/webreg.go

This PR adds a help page for the test step registry web UI as well as some small descriptions of what each test component is above the respective components table.

webreg: add help page

---

cmd/ci-secret-bootstrap/main.go
cmd/ci-secret-bootstrap/main_test.go
pkg/bitwarden/bitwarden.go
pkg/bitwarden/cli.go
pkg/bitwarden/cli_test.go

https://issues.redhat.com/browse/DPTP-880
Local test results:
```bash
$ ci-secret-bootstrap -bw-user aaa@redhat.com --bw-password-path /tmp/_bw_password --config ./core-services/ci-secret-bootstrap/_config.yaml 
INFO[0000] Parsed kubeconfig context: default           
INFO[0000] Parsed kubeconfig context: build01           
INFO[0000] running bw command ...                        args="[login aaa@redhat.com CENSORED --response]"
INFO[0003] running bw command ...                        args="[--session CENSORED list items]"
INFO[0003] running bw command ...                        args="[--session CENSORED get attachment
```

Censor seesion in the log of ci-secret-bootstrap

---

cmd/ci-op-configs-mirror/main.go
cmd/ci-op-configs-mirror/main_test.go
test/ci-op-configs-mirror-integration/data/input/super/duper/super-duper-master.yaml
test/ci-op-configs-mirror-integration/data/output/super-priv/duper/super-priv-duper-master.yaml
test/ci-op-configs-mirror-integration/data/output/super/duper/super-duper-master.yaml

While writing this, I realize that some of the `base_images` and some of the `build_root` are using images from different imagestreams as well. (ex. ocp/openshift)
We need to make sure that we have those as well.

Change all imagestream tag references in the generated ci-op configuration files.

---

cmd/ci-operator-prowgen/main.go
test/prowgen-integration/data/output/jobs/private/duper/private-duper-master-postsubmits.yaml

Revert this after DPTP-823
For the CVE effort we expect many builds to be broken for some time
so we are changing the name to not be covered by the regexes that
openshift org build cops are watching.
/cc @droslean

prowgen: temporarily rename private postsubmits

---

cmd/ci-operator-configresolver/main.go
pkg/load/agents/configAgent.go
pkg/load/agents/registryAgent.go
pkg/load/agents/utils.go
pkg/webreg/webreg.go

Importing `pkg/load` resulted in the `init` function in `test-infra`'s
`pkg/utils/interrupts` being executed, accidentally changing signal
handling.

pkg/load: make agents a sub-package

---

pkg/webreg/webreg.go

Fix a slight formatting issue caused by a tab being used instead of spaces here: https://steps.svc.ci.openshift.org/help#config
Also removes extra spaces at the end of lines (autoformatting).

pkg/webreg: change a tab to spaces to keep formatting consistent

---

pkg/rehearse/jobs.go
pkg/rehearse/jobs_test.go

It doesn't really make sense to execute the rehearsal job without reporting its status, but there are some cases where ppl might not want the original job to be reported (e.G. canary it out without getting ppl worried).

Rehersals: Always report

---

pkg/steps/template.go

Reverts openshift/ci-tools#480
Multiple tests without artifacts were reported:
- https://prow.svc.ci.openshift.org/view/gcs/origin-ci-test/pr-logs/pull/openshift_cluster-etcd-operator/206/pull-ci-openshift-cluster-etcd-operator-master-e2e-azure/777
- https://prow.svc.ci.openshift.org/view/gcs/origin-ci-test/pr-logs/pull/openshift_cluster-etcd-operator/206/pull-ci-openshift-cluster-etcd-operator-master-e2e-aws/888
Looking at executions before the change that is being reverted, artifact gathering takes a significantly long time:
- https://prow.svc.ci.openshift.org/view/gcs/origin-ci-test/pr-logs/pull/openshift_cluster-etcd-operator/185/pull-ci-openshift-cluster-etcd-operator-master-e2e-azure/709#1:build-log.txt%3A1430
- https://prow.svc.ci.openshift.org/view/gcs/origin-ci-test/pr-logs/pull/o …

Revert "ci-operator: check err when waiting for Pods to finish"

---

pkg/migrate/migrate.go

Follow up https://coreos.slack.com/archives/GB7NB0CUC/p1582750095166700?thread_ts=1582739113.156800&cid=GB7NB0CUC
required by https://github.com/openshift/release/pull/7337

Keep integr8ly-ansible-tower-configuration on default

---

pkg/steps/multi_stage.go
pkg/steps/multi_stage_test.go

By not expecting users to refer to hard-coded paths we give ourselves
breathing room in case we need to change how things work under the
covers in the future as well as providing a more streamlined interface
between the infrastructure and the test step.

multi-stage: expose cluster profile location via env

---

cmd/ci-op-configs-mirror/main.go
cmd/ci-op-configs-mirror/main_test.go
test/ci-op-configs-mirror-integration/data/output/super-priv/duper/super-priv-duper-master.yaml

This PR adds an extra check to update only integration imagestreams instead. Also, update the `base_rpm_images` as well.

[ci-op-configs-mirror] Update only integration imagestreams to private ones

---

pkg/migrate/migrate.go

This reverts commit f62fa40ded839b672ea84a22fb7cdb0e4435e362.
required by https://github.com/openshift/release/pull/7387
/hold
wait for jobs' rehearsals

Revert "Keep presubmits openshift/release on default"

---

pkg/webreg/webreg.go

help: use spaces, not tabs, for consistent indents

---

cmd/config-migrator/main.go

This PR is used to generate https://github.com/openshift/release/pull/7415
We missed the case base_rpm_images before.

Add cluster for base_rpm_images

---

cmd/ci-operator/main.go

@petr-muller 
When we use an `OAuth` token authentication,  we want the same secret to being used if there is a git source strategy build. (e.x `build_root.project_image)
Note: Having the secret as `BasicAuth` type doesn't break anything.

add secret keys for git source strategy builds

---

pkg/steps/multi_stage.go
pkg/steps/pod.go
pkg/steps/release/create_release.go
pkg/steps/template.go

/hold
I would like to monitor jobs when this is merged.

ci-operator: make pod functions interruptible

---

cmd/ci-op-configs-mirror/main.go
cmd/ci-op-configs-mirror/main_test.go
test/ci-op-configs-mirror-integration/data/output/super-priv/duper/super-priv-duper-master.yaml
test/ci-op-configs-mirror-integration/data/output/super-priv/trooper/super-priv-trooper-master.yaml

this PR removes the `disable: true` in the promotion configuration on the generated ci-operator configs for the private repositories.

[ci-op-configs-mirror] Enable promotion

---

test/pj-rehearse-integration/candidate/ci-operator/jobs/super/duper/super-duper-periodics.yaml
test/pj-rehearse-integration/expected.yaml
test/pj-rehearse-integration/master/ci-operator/config/super/duper/super-duper-cluster-profile.yaml
test/pj-rehearse-integration/master/ci-operator/jobs/super/duper/super-duper-cluster-profile-presubmits.yaml

This PR fixes a job in the `pj-rehearse` integration tests that was incorrect. It was using the outdated and unused `ci-operator-configs` configmap, which our `IsCiOpConfigCM` regex did not match against. This resulted in `CONFIG_SPEC` not being inlined. This has been changed to the `ci-operator-misc-configs` configmap, which is used when a configmap is not a master or release branch config.
The job was also referencing a non-existent `ci-operator` config which would cause the `pj-rehearse` to fail and had `openshift/origin` as the org-repo instead of `super/duper`. This has also been fixed.

test/pj-rehearse: fix an incorrect job

---

cmd/ci-operator-prowgen/main.go
cmd/ci-operator-prowgen/main_test.go
pkg/api/config.go
pkg/api/types.go

We add two variables:
* bool switch for enable-nested-virt on/off
* nested-virt custom image
Prerequisite for openshift/release#7457
/cc @davidvossel @sallyom

Reintegrate nested virt enablement into custom-test-image template

---

cmd/ci-operator-prowgen/main.go
cmd/ci-operator-prowgen/main_test.go
pkg/jobconfig/files.go
pkg/rehearse/jobs.go
pkg/rehearse/jobs_test.go
test/prowgen-integration/data/output/jobs/private-org/duper/private-org-duper-master-presubmits.yaml
test/prowgen-integration/data/output/jobs/private/duper/private-duper-master-periodics.yaml
test/prowgen-integration/data/output/jobs/private/duper/private-duper-master-postsubmits.yaml
test/prowgen-integration/data/output/jobs/private/duper/private-duper-master-presubmits.yaml
test/prowgen-integration/data/output/jobs/subdir/repo/subdir-repo-master-presubmits.yaml
test/prowgen-integration/data/output/jobs/super/duper/super-duper-master-periodics.yaml
test/prowgen-integration/data/output/jobs/super/duper/super-duper-master-postsubmits.yaml
test/prowgen-integration/data/output/jobs/super/duper/super-duper-master-presubmits.yaml
test/prowgen-integration/data/output/jobs/super/duper/super-duper-master-removed-promotion-presubmits.yaml
test/prowgen-integration/data/output/jobs/super/duper/super-duper-release-3.11-postsubmits.yaml
test/prowgen-integration/data/output/jobs/super/duper/super-duper-release-3.11-presubmits.yaml
test/repo-init-integration/expected/ci-operator/jobs/openshift/ci-tools/openshift-ci-tools-master-postsubmits.yaml
test/repo-init-integration/expected/ci-operator/jobs/openshift/ci-tools/openshift-ci-tools-master-presubmits.yaml
test/repo-init-integration/expected/ci-operator/jobs/openshift/origin/openshift-origin-master-postsubmits.yaml
test/repo-init-integration/expected/ci-operator/jobs/openshift/origin/openshift-origin-master-presubmits.yaml
test/repo-init-integration/expected/ci-operator/jobs/org/other/org-other-nonstandard-presubmits.yaml
test/repo-init-integration/expected/ci-operator/jobs/org/repo/org-repo-master-presubmits.yaml

This PR removes generation of the `CONFIG_SPEC` env var from `ci-operator-prowgen`. It also updates `pj-rehearse` to not depend on `CONFIG_SPEC` being set and instead use other methods of determining what config file needs to be inlined.

prowgen,pj-rehearse: do not add CONFIG_SPEC to generated jobs

---

cmd/ci-operator-prowgen/main.go
cmd/ci-operator-prowgen/main_test.go
pkg/jobconfig/files.go
pkg/rehearse/jobs.go
pkg/rehearse/jobs_test.go
test/prowgen-integration/data/output/jobs/private-org/duper/private-org-duper-master-presubmits.yaml
test/prowgen-integration/data/output/jobs/private/duper/private-duper-master-periodics.yaml
test/prowgen-integration/data/output/jobs/private/duper/private-duper-master-postsubmits.yaml
test/prowgen-integration/data/output/jobs/private/duper/private-duper-master-presubmits.yaml
test/prowgen-integration/data/output/jobs/subdir/repo/subdir-repo-master-presubmits.yaml
test/prowgen-integration/data/output/jobs/super/duper/super-duper-master-periodics.yaml
test/prowgen-integration/data/output/jobs/super/duper/super-duper-master-postsubmits.yaml
test/prowgen-integration/data/output/jobs/super/duper/super-duper-master-presubmits.yaml
test/prowgen-integration/data/output/jobs/super/duper/super-duper-master-removed-promotion-presubmits.yaml
test/prowgen-integration/data/output/jobs/super/duper/super-duper-release-3.11-postsubmits.yaml
test/prowgen-integration/data/output/jobs/super/duper/super-duper-release-3.11-presubmits.yaml
test/repo-init-integration/expected/ci-operator/jobs/openshift/ci-tools/openshift-ci-tools-master-postsubmits.yaml
test/repo-init-integration/expected/ci-operator/jobs/openshift/ci-tools/openshift-ci-tools-master-presubmits.yaml
test/repo-init-integration/expected/ci-operator/jobs/openshift/origin/openshift-origin-master-postsubmits.yaml
test/repo-init-integration/expected/ci-operator/jobs/openshift/origin/openshift-origin-master-presubmits.yaml
test/repo-init-integration/expected/ci-operator/jobs/org/other/org-other-nonstandard-presubmits.yaml
test/repo-init-integration/expected/ci-operator/jobs/org/repo/org-repo-master-presubmits.yaml

Reverts openshift/ci-tools#534
There is currently a small mistake from that PR that breaks rehearsals. Working on fixing that as well as updating the integration tests to run without `CONFIG_SPEC` set

Revert "prowgen,pj-rehearse: do not add CONFIG_SPEC to generated jobs"

---

Makefile
cmd/cvp-trigger/README.md
cmd/cvp-trigger/main.go
cmd/cvp-trigger/main_test.go
test/cvp-trigger-integration/config.yaml
test/cvp-trigger-integration/jobs.yaml
test/cvp-trigger-integration/periodic-ipi-deprovision.expected
test/cvp-trigger-integration/run.sh

CVP Trigger tool will be used by the CVP pipeline to parametrize and
trigger the verification jobs for optional operator artifacts built
internally in RH.
Right now the tool reads Prow config, finds a specified periodic job
specification, creates a Prowjob, submits it to the cluster and waits
until the job finishes.
In the future we expect this tool to perform some job parametrization.
/cc @openshift/openshift-team-developer-productivity-test-platform  @dirgim

Add the CVP trigger tool skeleton

---

cmd/secret-wrapper/main.go
pkg/steps/multi_stage.go
test/ci-operator-integration/multi-stage/expected/hyperkube.json
test/ci-operator-integration/multi-stage/expected/installer.json
test/secret-wrapper-integration.sh

Copy the input directory (where the secret is mounted) to the output
directory and use that to overwrite the secret after the wrapped command
is executed.  This is done so the program:
- deals with a single directory
- does not have to copy files manually to preserve them
- can delete files from the secret by removing them from the directory

secret-wrapper: unify input and output directories

---

cmd/ci-operator-prowgen/main.go
cmd/ci-operator-prowgen/main_test.go
cmd/ci-operator/main.go
cmd/ci-operator/main_test.go
go.mod
pkg/load/load.go
test/ci-operator-integration/multi-stage/expected/hyperkube.json
test/ci-operator-integration/multi-stage/expected/installer.json
test/ci-operator-integration/multi-stage/run.sh
test/prowgen-integration/data/output/jobs/private-org/duper/private-org-duper-master-presubmits.yaml
test/prowgen-integration/data/output/jobs/private/duper/private-duper-master-periodics.yaml
test/prowgen-integration/data/output/jobs/private/duper/private-duper-master-postsubmits.yaml
test/prowgen-integration/data/output/jobs/private/duper/private-duper-master-presubmits.yaml
test/prowgen-integration/data/output/jobs/subdir/repo/subdir-repo-master-presubmits.yaml
test/prowgen-integration/data/output/jobs/super/duper/super-duper-master-periodics.yaml
test/prowgen-integration/data/output/jobs/super/duper/super-duper-master-postsubmits.yaml
test/prowgen-integration/data/output/jobs/super/duper/super-duper-master-presubmits.yaml
test/prowgen-integration/data/output/jobs/super/duper/super-duper-master-removed-promotion-presubmits.yaml
test/prowgen-integration/data/output/jobs/super/duper/super-duper-release-3.11-postsubmits.yaml
test/prowgen-integration/data/output/jobs/super/duper/super-duper-release-3.11-presubmits.yaml
test/repo-init-integration/expected/ci-operator/jobs/openshift/ci-tools/openshift-ci-tools-master-postsubmits.yaml
test/repo-init-integration/expected/ci-operator/jobs/openshift/ci-tools/openshift-ci-tools-master-presubmits.yaml
test/repo-init-integration/expected/ci-operator/jobs/openshift/origin/openshift-origin-master-postsubmits.yaml
test/repo-init-integration/expected/ci-operator/jobs/openshift/origin/openshift-origin-master-presubmits.yaml
test/repo-init-integration/expected/ci-operator/jobs/org/other/org-other-nonstandard-presubmits.yaml
test/repo-init-integration/expected/ci-operator/jobs/org/repo/org-repo-master-presubmits.yaml
vendor/k8s.io/utils/diff/diff.go
vendor/k8s.io/utils/field/path.go
vendor/modules.txt

This PR allows the `ci-operator` to use Prow's downward API to determine the `org`, `repo`, and `branch` that is passed to the `configresolver` when retrieving the config. It also changes the loading priority to the following:
1. If `--config` is set, use file.
2. If `CONFIG_SPEC` is set, use environment variable.
3. Use configresolver. Use `jobSpec.Refs` and `jobSpec.ExtraRefs` to determine `org`, `repo`, and `branch`. If `org`, `repo`, and/or `branch` are not available via the refs and extra_refs, use flags to get unset `org`, `repo`, and `branch`.
The variant for the resolver still gets passed via the `--variant` flag, and now the `--resolverAddress` defaults its value instead of being set by prowgen.
Prowgen has also been updated to not set flags for jobs other than `--variant`.
/cc …

ci-operator,prowgen: don't set redundant ci-operator flags

---

cmd/autobumper/main.go

Samplerun where this caused failures: https://github.com/openshift/release/pull/7602
/assign petr-muller

Autobumper: Run make update-app-ci

---

images/autobumper/Dockerfile

Otherwise it fails like this: https://prow.svc.ci.openshift.org/view/gcs/origin-ci-test/logs/periodic-prow-image-autobump/409

Autobumper: Install make

---

cmd/ci-secret-bootstrap/main.go
cmd/ci-secret-bootstrap/main_test.go

Currently it can fail validation with a
```
time="2020-03-13T12:34:25Z" level=fatal msg="Failed to complete options." error="config[0].to is empty"
```

Secret bootstrapper: fix --cluster flag

---

cmd/private-prow-configs-mirror/README.md
cmd/private-prow-configs-mirror/main.go
cmd/private-prow-configs-mirror/main_test.go
images/private-prow-config-mirror/Dockerfile

This tool detects the configuration of all of the org/repos that promotes official images and injects an `openshift-priv/repo` version of the config.
Affected configuration: 
`config.branch-protection`
`config.context_options`
`config.tide.merge_method`
`config.tide.queries`
`config.tide.pr_status_base_urls`
`config.plank.default_decoration_configs`
`config.plank.job_url_prefix_config`
`plugins.approve`
`plugins.lgtm`
`plugins.plugins`
`plugins.bugzilla`
/cc @petr-muller @stevekuznetsov 

Private prow configs mirroring tool

---

cmd/ci-operator-prowgen/main.go
pkg/api/config.go
pkg/api/types.go

This patch was modeled after #425, so it tightly couples the architecture to the cluster profile. Some consideration was made to leaving this profile as a generic "libvirt" profile, but the current x86_64 tests use the AWS profile. Also, it would be useful in terms of tracking metrics to ensure that Z/s390x can be filtered out.

Added a libvirt profile for remote s390x testing.

---

pkg/steps/multi_stage.go
pkg/steps/multi_stage_test.go
test/ci-operator-integration/multi-stage/expected/hyperkube.json
test/ci-operator-integration/multi-stage/expected/installer.json

Contrary to all other areas of `ci-operator`, multi-stage tests need to be
able to use images from both the `pipeline` and `stable` ImageStreams.
The set of images that are part of the `pipeline` IS can be identified from
the configuration, but `stable` is populated at runtime after steps are
instantiated.  Crucially, support for arbitrary external images
(i.e. outside the release configuration) is not desired, so the simple rule
of identifying if an image is declared in the configuration and defaulting
it to `stable` otherwise can be used.

ci-operator multi-stage: default images to `stable`

---

cmd/autoconfigbrancher/main.go
images/autoconfigbrancher/Dockerfile

Reverts openshift/ci-tools#558
`private-prow-configs-mirror` tool generates a warning. Reverting until the fix will land.

Revert "Add private-prow-configs-mirror tool in autoconfigbrancher pipeline"

---

pkg/steps/multi_stage.go
pkg/steps/multi_stage_test.go
pkg/webreg/webreg.go
test/ci-operator-integration/multi-stage/expected/hyperkube.json
test/ci-operator-integration/multi-stage/expected/installer.json

This reverts commit b72fccf706599296534d38adbe6a27381e7babb7.
https://github.com/openshift/release/pull/7693
/hold

Revert "ci-operator multi-stage: ignore existing `stable:`"

---

cmd/private-prow-configs-mirror/main.go
cmd/private-prow-configs-mirror/main_test.go

This PR refactors the implementation of generating the plugins for the private repos.
Added unit tests for the get common values function.
This implementation includes also the empty public repos that inherit their values from the org wide level config.

[private-prow-configs-mirror] Fix the private plugins generation 

---

pkg/webreg/webreg.go

Being a header is already enough to say "I'm providing context for the following content"; you don't need to include a colon too.

pkg/webreg: Drop colons from headers

---

pkg/webreg/webreg.go

In the same spirit as:
- https://github.com/openshift/ci-tools/pull/561
- https://github.com/openshift/release/pull/7693
Eventually, a section detailing which images are accepted in that field
should be added.

webreg: replace `centos:7` with `base`

---

cmd/autoowners/main.go
cmd/autoowners/main_test.go

This is done to make sure there is never an empty Reviewers list, as
that makes blunderbuss traverse up until it finds reviewers rather than
defaulting to the approvers.

Autoowners: Default Reviewers to Approvers

---

cmd/testgrid-config-generator/README.md

Based on @bparees [here][1], showing folks how to update the TestGrid config to include release-controller promotion jobs.
[1]: https://github.com/openshift/release/pull/7768#issuecomment-600933491

cmd/testgrid-config-generator: Add a README

---

pkg/api/types.go
pkg/rehearse/jobs_test.go
test/ci-operator-configresolver-integration/expected/openshift-installer-release-4.2-golang111.json
test/ci-operator-configresolver-integration/expected/openshift-installer-release-4.2-regChange.json
test/ci-operator-configresolver-integration/expected/openshift-installer-release-4.2.json
test/pj-rehearse-integration/expected.yaml

`Commands` in tests is no longer a required field since the introduction
of multi-stage tests.  Add `omitempty` so that tools stop adding it
unnecessarily.

ci-operator: omit `commands` in tests if empty

---

Makefile
cmd/determinize-prow-jobs/main.go
cmd/determinize-prow-jobs/main_test.go
pkg/jobconfig/files.go
test/prowgen-integration/run.sh
test/repo-init-integration/expected/ci-operator/jobs/openshift/ci-tools/openshift-ci-tools-master-postsubmits.yaml
test/repo-init-integration/expected/ci-operator/jobs/openshift/ci-tools/openshift-ci-tools-master-presubmits.yaml
test/repo-init-integration/expected/ci-operator/jobs/openshift/origin/openshift-origin-master-postsubmits.yaml
test/repo-init-integration/expected/ci-operator/jobs/openshift/origin/openshift-origin-master-presubmits.yaml
test/repo-init-integration/expected/ci-operator/jobs/org/other/org-other-nonstandard-presubmits.yaml
test/repo-init-integration/expected/ci-operator/jobs/org/repo/org-repo-master-presubmits.yaml

I do realize that mutating the jobs means the tool does more than what would expect it to do, but its the one thing we run over all jobs. Maybe rename it?

Determinize job config: Set api.ci cluster if cluster is unset

---

pkg/webreg/webreg.go

/cc @openshift/openshift-team-developer-productivity-platform

webreg: remove old CSS for a sidenav that was never implemented

---

hack/pr-deploy.yaml

`pr-deploy` is useful to generate an example of changes to webreg, but the builds are very slow. Part of this is because it is running `make` install to build the binaries, which builds all of the ci-tools binaries instead of just the resolver. This is unnecessary for the `pr-deploy` command, so this changes that to `go install ./cmd/ci-operator-configresolver/...`

hack/pr-deploy: build images faster

---

pkg/webreg/webreg.go

Due to the long names of some steps, the workflow table on the main page for the step registry web UI became very poorly formatted. This PR combines the `Pre`, `Test`, and `Post` columns into a single `Steps` column to alleviate the issue.

webreg: change layout of workflow table to better fit step names

---

pkg/steps/multi_stage_test.go
pkg/steps/pod.go
pkg/steps/pod_test.go
test/ci-operator-integration/base/expected_files/expected.json
test/ci-operator-integration/base/expected_files/expected_pull_secret.json
test/ci-operator-integration/multi-stage/expected/hyperkube.json
test/ci-operator-integration/multi-stage/expected/installer.json

Users may want to detect when their workload is being executed by
ci-operator. Today, they can tell that they are executing in Prow by
checking $CI. This change sets $OPENSHIFT_CI so that they can
furthermore detect that they are running under ci-operator specifically.

ci-operator: identify ci-operator specific workloads

---

cmd/autoconfigbrancher/main.go

needs https://github.com/openshift/release/pull/7846
Needed, because what autoconfigbrancher produces does not currently pass the `ordered-prow-config` presubmit, see e.G. here: https://github.com/openshift/release/pull/7821

Autoconfigbrancher: Run determinize-prow-jobs

---

pkg/rehearse/jobs.go
pkg/rehearse/jobs_test.go

We forced rehearsals to report, but that may confuse ppl that are not aware that some jobs are not expected to pass, which is why they were set to `report: false` in the first place.
If reporting is explicitly wanted for the rehearsal, the job itself can be changed to `report: true`.

Rehearsals: Don't force reporting

---

cmd/ci-operator-checkconfig/main.go
cmd/ci-operator-checkconfig/main_test.go
pkg/defaults/defaults.go
pkg/steps/release/promote.go
pkg/steps/release/promote_test.go

It should never be possible for separate source configurations to
publish the same image tag.

ci-operator-checkconfig: disallow duplicate promotions

---

Makefile
hack/pr-deploy.yaml

Use `ci-operator-master-configs` instead of the old, unused `ci-operator-configs`, and use `create` instead of `apply` for `oc` to fix the "annotation too long" issues when using `apply`

pr-deploy: use correct cm and use create not apply

---

pkg/webreg/webreg.go

This PR adds line numbers printed next to the lines as well as lines that can be linked to and be highlighted.
The `chroma` package does not currently have support for clickable links which leads to some limitations.
- To link to a line, you manually append `line%d` to the address
- This doesn't work for the help pages, as all code blocks would have the same id prefixes. Clickable lines would solve this problem as we could make unique prefixes for each block.

webreg: number lines and make them linkable

---

pkg/steps/multi_stage.go
pkg/steps/optional_operators.go
pkg/steps/optional_operators_test.go

The parameters correspond to the inputs in:
https://steps.svc.ci.openshift.org/registry/optional-operators-subscribe
Right now, this only passes the same information passed into ci-operator
via environmental variables (similar how the `RELEASE_IMAGE_*` ones are
consumed). In the future, some images built by ci-operator itself will
be used to populate these parameters.
/assign  @stevekuznetsov

Pass optional operator installation parameters to steps

---

cmd/ci-operator-prowgen/main.go
cmd/ci-operator-prowgen/main_test.go
cmd/ci-operator-prowgen/testdata/postsubmit-TestFromCIOperatorConfigToProwYaml_Input_is_YAML_and_it_is_correctly_processed.yaml
cmd/ci-operator-prowgen/testdata/postsubmit-TestFromCIOperatorConfigToProwYaml_Using_a_variant_config,_one_test_and_images,_one_existing_job._Expect_one_presubmit,_pre_post_submit_images_jobs._Existing_job_should_not_be_changed..yaml
cmd/ci-operator-prowgen/testdata/postsubmit-TestFromCIOperatorConfigToProwYaml_one_test_and_images,_no_previous_jobs._Expect_test_presubmit_+_pre_post_submit_images_jobs.yaml
test/prowgen-integration/data/output/jobs/private/duper/private-duper-master-postsubmits.yaml
test/prowgen-integration/data/output/jobs/super/duper/super-duper-master-postsubmits.yaml
test/prowgen-integration/data/output/jobs/super/duper/super-duper-release-3.11-postsubmits.yaml
test/repo-init-integration/expected/ci-operator/jobs/openshift/ci-tools/openshift-ci-tools-master-postsubmits.yaml
test/repo-init-integration/expected/ci-operator/jobs/openshift/origin/openshift-origin-master-postsubmits.yaml

Publication jobs change external state. When publication jobs are
triggered concurrently, they can race to finish and the resulting state
of external systems is not correct. Setting a maximum concurrency for
these jobs of 1 will sacrifice throughput for correctness.
/assign @smarterclayton 

ci-operator-prowgen: set max concurrency on publication jobs

---

cmd/ci-operator-prowgen/main.go

When there are `_variant` `ci-operator` configs, `prowgen` generates, as it should, the job name with the prefix `variant-`. However, it doesn't do the same in the `JOB_NAME_SAFE` environment variable. That caused race problems like:
https://prow.svc.ci.openshift.org/view/gcs/origin-ci-test/pr-logs/pull/openshift_tektoncd-pipeline/364/pull-ci-openshift-tektoncd-pipeline-release-v0.11.0-rc3-variant-e2e/10  

fix job name safe env var for the variant jobs

---

pkg/webreg/webreg.go

We italicize the first occurrence of a term that we mean to define on
pages that exist to define it, then do not emphasize the term any
longer.

webreg: reformat identifiers

---

cmd/ci-operator-prowgen/main.go

after #614 merged we change the value of the `JOB_NAME_SAFE` env var. Unfortunately, this is being used in the template as the name of the secret for mounting, but `ci-operator` creates the secret without the variant prefix.
This PR will resolve this issue. Related JIRA https://issues.redhat.com/browse/DPTP-1019

add variant prefix in secret names

---

pkg/config/load.go
pkg/config/load_test.go
pkg/rehearse/jobs.go
pkg/rehearse/jobs_test.go

Improve pj-rehearse to try harder in cases when it needs to rehearse a
job (usually a periodic) which is not apparently tied to any specific
ci-operator config, but is configured to run `ci-operator` with explicit
`--org/--repo/--branch/--variant` options. We were already removing
these options, so we can as well save their values, and use them in case
when the normally used ones are not available (previously we would
simply fail with a "ci-operator config file --.yaml was not found"
message).
The method that removes the args from containers running `ci-operator`
was rewritten to better accomodate the need to save the values,
otherwise the changes are quite simple.

rehearse: infer ci-operator config from parameters when needed

---

cmd/ci-operator-prowgen/main.go
cmd/ci-operator-prowgen/main_test.go
pkg/config/load.go
pkg/config/load_test.go

The `Info.JobName()` method did not return a name including a variant
(although a variant is one of the member fields of the struct), which
made rehearsal mistakenly treat more jobs as affected by a variant
ci-operator config change. By not matching agains job name including a variant,
it incorrectly selected all non-variant jobs as affected.
Fix `JobName()` together with Prowgen, which was actually depending on
this incorrect behavior, and appended the variant itself. Write few new
GoDocs and tests.

rehearse: fix excessive rehearsals for variants

---

cmd/pj-rehearse/main.go

I want to entirely remove this code (it was only useful at the beginning
when we wanted to run in a stealth mode) and to do that, I need to
remove the option from the jobs that calls `pj-rehearse`. To do that, I
need to make the `--no-fail=false` the default so I can remove the option
without actually changing the behavior.

rehearse: set no-fail=false to stage its removal

---

cmd/testgrid-config-generator/README.md
cmd/testgrid-config-generator/main.go
test/testgrid-config-generator/config/jobs/org/repo/org-repo-master-periodics.yaml
test/testgrid-config-generator/expected/groups.yaml
test/testgrid-config-generator/expected/redhat-openshift-ocp-release-4.3-broken.yaml

The periodic label overrides the release config suggestion. The
generator is restructured to be simpler as a result. A new 'broken'
type is introduced for jobs we deem failures.
This is a result of agreement with release oversight.

testgrid-config-generator: Include new dashboard type 'broken'

---

cmd/testgrid-config-generator/OWNERS

@stevekuznetsov is comfortable maintaining the script, but not interested in driving policy decisions.  @bparees and @smarterclayton are both interested in policy decisions and the script implementation.

cmd/testgrid-config-generator/OWNERS: Scope script approvers

---

cmd/applyconfig/applyconfig.go
cmd/applyconfig/applyconfig_test.go

This pr removes the level functionality while still keeping the flag
with its old default. Applyconfig will now always fail when not called
with `--level=all`, this is done to make sure we notice these cases.

Applyconfig: Remove level functionality

---

cmd/applyconfig/applyconfig.go
cmd/applyconfig/applyconfig_test.go

Reverts openshift/ci-tools#645
Apparently broke stuff, example from https://prow.svc.ci.openshift.org/view/gcs/origin-ci-test/pr-logs/pull/openshift_release/8216/pull-ci-openshift-release-master-services-dry/9718:
```
time="2020-04-08T11:54:25Z" level=error msg="oc apply -f services/README.md --dry-run: failed to apply\nW0408 11:54:23.698493      26 helpers.go:535] --dry-run is deprecated and can be replaced with --dry-run=client.\nerror: error parsing services/README.md: error converting YAML to JSON: yaml: line 4: mapping values are not allowed in this context\n"
```

Revert "Applyconfig: Remove level functionality"

---

cmd/ci-operator-prowgen/main.go

This reverts commit 7a4efaafe3cb29db765c791965aa2834f1616573.
This reverts commit fb7981adfcac1401f3466369af1c3a80ace1d7bb.
Variants should not be in the same namespace by design (they are
different versions of the same config and we don't support config
in the same namespace). We should identify whatever the fix is
outside, because a variant using e2e-gcp should look exactly like
the core branch using e2e-gcp.

Revert "fix job name safe env var for the variant jobs"

---

cmd/pj-rehearse/main.go
pkg/diffs/diffs.go
pkg/diffs/diffs_test.go

There is no reason why this needs to be in a separate method when
existing methods already iterate over all jobs and check for different
fields.

rehearse: simplify detection of jobs with changed clusters

---

cmd/pj-rehearse/main.go
test/pj-rehearse-integration/run.sh

This was was only useful at the beginning when we wanted to run in a
stealth mode, but not anymore. The `gracefulExit` method only existed to
handle the no-fail decision, so it was removed and partially inlined
in call sites.
This is safe to do after: https://github.com/openshift/release/pull/8219

rehearse: remove --no-fail parameter entirely

---

cmd/pj-rehearse/main.go
pkg/diffs/diffs.go
pkg/diffs/diffs_test.go
pkg/rehearse/jobs.go

The semi-machine-read-able logs are hard to parse but this at least fixes areas where we'd not output anything at all when choosing a job.

pj-rehearse: be better at logging

---

cmd/private-org-peribolos-sync/README.md
cmd/private-org-peribolos-sync/main.go
cmd/private-org-peribolos-sync/main_test.go
images/private-org-peribolos-sync/Dockerfile
vendor/k8s.io/test-infra/prow/github/fakegithub/BUILD.bazel
vendor/k8s.io/test-infra/prow/github/fakegithub/fakegithub.go
vendor/modules.txt

This tool generates the `peribolos[org].Repos` for the given organization by listing all the repositories that promote official images plus the ones that are included in the `--whitelist` flag. 
This is a part of the workload described in https://issues.redhat.com/browse/DPTP-753
/cc @stevekuznetsov @petr-muller

[private-org-peribolos-sync] Tool to sync the peribolos config for the private org

---

cmd/config-shard-validator/main.go
cmd/pj-rehearse/main.go
cmd/repo-init/main.go
pkg/diffs/diffs.go

The same constants are defined in pkg/config/release.go where they fit
better.

Remove duplicate constants from diffs package

---

pkg/steps/multi_stage.go
pkg/steps/multi_stage_test.go
test/ci-operator-integration/multi-stage/expected/hyperkube.json
test/ci-operator-integration/multi-stage/expected/installer.json

https://github.com/openshift/ci-tools/issues/633
Follow regular container tests and name the container "test" (the pod
name remains the same, i.e. the step name).
Resulting JUnit output:
```xml
<testcase name="Run multi-stage test unit - unit-pre container test" time="0"></testcase>
<testcase name="Run multi-stage test unit - unit-unit container test" time="72"></testcase>
<testcase name="Run multi-stage test unit - unit-post container test" time="0">
```
Resulting artifacts directory:
```
artifacts/
└── unit
└── test
└── container-logs
├── cp-secret-wrapper.log.gz
└── test.log.gz
```

ci-operator multi-stage: name containers "test"

---

pkg/load/load.go
pkg/load/load_test.go
test/multistage-registry/invalid-field/ipi/install/ipi-install-ref.yaml

This PR allows us to fail verification if a config or registry component has extra, invalid fields set.

pkg/load: use UnmarshalStrict to detect extra, invalid fields

---

cmd/ci-operator-prowgen/main.go
cmd/ci-operator-prowgen/main_test.go

Fixes bug where created secret name is different from secret name in podspec, causing a volume mount error.
This will require a regen PR in openshift/release

prowgen: mount secrets at /secrets/secret.Name

---

cmd/ci-operator-prowgen/main.go
pkg/api/config.go
pkg/api/types.go

We're adding a new OpenStack cloud on Vexxhost to run some of our CI jobs. We need a separate cluster profile in order to differentiate boskos leases pools.

OpenStack: Add profile type for OpenStack Vexxhost cloud

---

cmd/ci-operator/main.go
pkg/load/load.go
pkg/results/error.go
pkg/results/error_test.go
pkg/results/results.go

In order to be able to expose a history over time of known, annotated
reasons for failure in the ci-operator process, we need a mechanism to
communicate these errors, with annotations, thoughout the codebase. In
order to allow administrators to apply default policy while also
allowing for specific error causes, a concatentating mechanism is used
in defining the error reason string. This will allow for queries for a
specific subsystem or a symptom that may occur across subsystems by
using regular expression matching on these error strings.

ci-operator: annotate errors at the top-most levels

---

pkg/steps/multi_stage.go
pkg/steps/multi_stage_test.go

https://github.com/openshift/ci-tools/pull/657 unified the container
names of all multi-stage pods, causing artifacts to be written to the
same directory.

ci-operator multi-stage: fix artifact directory

---

pkg/lease/client.go

We have a global timeout of 4h, so a 50m timeout is unnecessarily
restrictive for jobs that could grab a lease and still have time to
finish in their allotted window.

boskos: bump acquire timeout to 120m

---

cmd/config-shard-validator/main.go
cmd/config-shard-validator/main_test.go

/assign @stevekuznetsov 
Had to refactor the thing to make it testable. We still log a message per error we encountered.

Config shard validation: add field path to errors

---

cmd/ci-operator/main.go
cmd/ci-secret-bootstrap/main.go
pkg/defaults/defaults.go
pkg/util/client.go
pkg/util/client_test.go

Like the rest of the places, rest config is always a pointer.
I should have done this from the beginning.

Use pointer in the kubeconfig map

---

cmd/blocking-issue-creator/main.go
cmd/config-brancher/main.go
cmd/determinize-ci-operator/main.go
cmd/repo-brancher/main.go
pkg/api/types.go
pkg/config/load.go
pkg/config/load_test.go
pkg/config/options.go
pkg/config/options_test.go
pkg/jobconfig/files.go
pkg/promotion/promotion.go
pkg/promotion/promotion_test.go
test/ci-operator-configresolver-integration/expected/openshift-installer-release-4.2-golang111.json
test/ci-operator-configresolver-integration/expected/openshift-installer-release-4.2-regChange.json
test/ci-operator-configresolver-integration/expected/openshift-installer-release-4.2.json
test/pj-rehearse-integration/expected.yaml

Previously, we had one set of common options -- for promotion. In
reality, tools may need to load and operate on CI Operator
configuration, honor promotion rules, care about future releases or all
three. As it stands, some tools have flags they don't use (and often our
validation forces them to be set). This refactor separates our concerns
and DRYs out the logic used to select subsets of config from provided
flags. It does not change the end behavior of tools other than the
remove unused flags.

config: partition useful flags

---

pkg/controller/util/request_coalescer.go
pkg/controller/util/request_coalescer_test.go

This allows to delay ReconcileRequests after a successful Reconciliation
in order to decrease load for controllers that watch objects that change
very frequently.
Needed now for the ImageStreamTagReconciler but may be useful elsewhere.
To give a bit more background: ImageStreamTags do not support watching (https://github.com/openshift/api/issues/601). This means that:
* We have to watch ImageStreams instead
* And enqueue each and every ImageStreamTag in them on every event (basically whenever any changes)
* Since api.ci has some imageStreams that basically permanently get events, we produce _a lot_ of events
* This results in a high load because the ImageStreamTag reconciler has a somewhat expensive reconcile loop where it does a git fetch and some json unmarshaling
Apart from the …

Add a ReconcileRequestCoalescer

---

cmd/ci-secret-bootstrap/main.go
cmd/ci-secret-bootstrap/main_test.go

Just dumping secrets to stdout is never an expected behavior unless it
was explicitly requested, so this is at best surprising and might at
worst lead to accidentally relevaing all secrets (e.G. if it runs in
CI).

Ci-Secret-Bootstrap: Don't dump secrets to stdout on dry-run

---

cmd/config-brancher/main.go

fixes the missing `---future-release` flag binding.
before
```console
$ config-brancher --help
Usage of config-brancher:
-bump-release string
Bump the dev config to this release and manage mirroring.
-config-dir string
Path to CI Operator configuration directory.
-confirm
Create the branched configuration files.
-current-release string
Configurations targeting this release will get branched.
-log-level string
Level at which to log output. (default "info")
-org string
Limit repos affected to those in this org.
-repo string
Limit repos affected to this repo.
```
after
```console
$ config-brancher --help
Usage of config-brancher:
-bump-release string
Bump the dev config to this release and manage mirroring.
-config-dir …
```

fix missing future-release flag

---

pkg/jobconfig/files.go
pkg/jobconfig/files_test.go

Follow up https://coreos.slack.com/archives/GB7NB0CUC/p1588003186030600?thread_ts=1588002752.029100&cid=GB7NB0CUC
/cc @stevekuznetsov @alvaroaleman 
Breaking change ... Need to prepare the PR for release change.
Fix tests if breaking.
Update:
Added unit tests and https://github.com/openshift/release/pull/8610

Fix default postsubmit.MaxConcurrency = 1 for promotion jobs

---

Makefile
hack/lint.sh

Enables golangci-lint with three linters:
* `unused`: Finds variables that are assigned to and then never read from until they go out of scope or are written to again. This finds correctness issues.
* `deadcode`: Pretty much what it says. Doesn't find correctness issues but IMHO good to have to keep things simple
* `gosimple`: Also pretty much what it says. Doesn't find correctness issues either, but keeps the code simple
/assign @bbguimaraes @petr-muller

Enable golangci-lint in CI

---

cmd/ci-operator/main.go
pkg/results/report.go

We have a number of flags whose usage is ubiquitous and does not change
ove time. We should bake these in to the code so that we can make the
generated job configurations smaller, but continue to expose the flags
so that a quick change in configuration is all that's necessary to edit
them, not a full rebuild and redeploy.

ci-operator: add sane defaults to ubiquitous flags

---

cmd/ci-operator/main.go

Reverts openshift/ci-tools#728
We can't include default lease server everywhere without providing a lease server password everywhere.

Revert "ci-operator: add sane defaults to ubiquitous flags"

---

Makefile
hack/lint.sh

...Rather than `make: Nothing to be done for 'lint'.`

Actually run lint

---

cmd/ci-operator/main.go

The error wrapper prevents writing multiple JUnits and was
accidentally included.

ci-operator: Only log errors if they haven't been written

---

cmd/autoconfigbrancher/main.go

We only need to run prowgen once, after we run all of the CI Operator
configuration generators. We can run the CI Operator configiuration
santiizer then, too.

autoconfigbrancher: restructure commands

---

cmd/ci-operator/main.go
cmd/ci-operator/main_test.go
pkg/interrupt/interrupt.go
pkg/load/load.go
pkg/results/results.go
pkg/steps/clusterinstall/clusterinstall.go
pkg/steps/git_source.go
pkg/steps/input_image_tag.go
pkg/steps/lease.go
pkg/steps/multi_stage.go
pkg/steps/output_image_tag.go
pkg/steps/pipeline_image_cache.go
pkg/steps/pod.go
pkg/steps/project_image.go
pkg/steps/release/create_release.go
pkg/steps/release/promote.go
pkg/steps/release/release_images.go
pkg/steps/rpm_injection.go
pkg/steps/rpm_server.go
pkg/steps/run.go
pkg/steps/source.go
pkg/steps/template.go
pkg/steps/write_params.go

ci-operator: bubble up multiple errors to the top
We currently flatten all errors from a potentially parallel execution of
steps in the graph, which makes it impossible to report the results of
any individual failure easily. Instead, bubble up all the errors
individually and format them in a flat way just for presentation.
---
results: remove constants for reasons
By definition, each of these reasons is only ever going to occur once in
our code, so there is no re-use happening due to the constants. Adding
them is just grunt work and serves no other purpose.
---
ci-operator: add top-level error identifiers for steps
---
/assign …

ci-operator: add finer-grained error identifiers

---

cmd/ci-operator/main.go

ci-operator: correctly default error reaons

---

cmd/ci-operator/main.go

I think this should fix the false negatives where ci-operator-running jobs end with PASS even when some errors happened during the execution.

ci-operator: fix an off-by-one bug in error handling

---

pkg/load/agents/configAgent.go
pkg/load/agents/configAgent_test.go
pkg/load/load.go
pkg/webreg/webreg.go

Currently, the code to move all ci-op configs is part of the agent.
However there are cases where this is needed but an agent is not, e.G. a
CLI that acts on all configs.
This PR does not change any code, it just moves code around.

Move ci-op recursive config loading from pkg/load/agents to pkg/load

---

hack/install.sh

With a simple `go install ./cmd/...` we re-use the cache.
/assign @alvaroaleman @bbguimaraes

hack: inject ldflags only on official builds

---

cmd/ci-operator-configresolver/main.go
cmd/ci-operator-prowgen/main.go
cmd/config-brancher/main_test.go
cmd/config-change-trigger/main.go
cmd/config-change-trigger/main_test.go
cmd/determinize-ci-operator/main.go
cmd/pj-rehearse/main.go
cmd/private-org-sync/main_test.go
cmd/private-prow-configs-mirror/main.go
cmd/repo-init/main.go
cmd/repo-init/main_test.go
pkg/api/metadata.go
pkg/api/metadata_test.go
pkg/config/load.go
pkg/config/load_test.go
pkg/config/options.go
pkg/config/options_test.go
pkg/config/release.go
pkg/config/whitelist_test.go
pkg/diffs/diffs.go
pkg/diffs/diffs_test.go
pkg/jobconfig/files.go
pkg/load/agents/configAgent.go
pkg/prowgen/prowgen.go
pkg/prowgen/prowgen_test.go
pkg/rehearse/jobs.go
pkg/rehearse/jobs_test.go

config: rename type storing data by filename
---
config: use Metadata type when loading from directories
---
api: declare our directory structure and naming an api, use it
We have an API/interface around how we format names and identifiers
based on what org/repo/branch/variant is being considered. Refactor code
to make this an obvious API.
---

 api: declare our directory structure and naming an api, use it 

---

hack/install.sh

As they are more portable and don't inhibit varying behavior depending on the glibc they have been compiled against.

Build static binaries

---

cmd/ci-operator-configresolver/main.go
pkg/api/metadata.go
pkg/load/agents/configAgent.go
pkg/load/agents/configAgent_test.go
pkg/load/load.go
pkg/load/load_test.go
pkg/webreg/webreg.go
test/ci-operator-integration/multi-stage/configs/master/openshift-hyperkube-master.yaml
test/ci-operator-integration/multi-stage/configs/release-4.2/openshift-installer-release-4.2.yaml

(Creating a new PR because I can not push to steves branch)
At feature-freeze, developers create branches which prefix their working
branch and use Prow's regex matching on branch names to not need to
reconfigure their CI whatsoever. For instance, a master branch will be
used to create master-feature. We now support the same operation in
the configuration server.
Signed-off-by: Steve Kuznetsov skuznets@redhat.com
/cc @openshift/openshift-team-developer-productivity-platform
This pr has one additional commit that minimizes the exported surface of pkg/load. I didn't get around to make the job retrieval an index, because it requires a bit more refactoring wrt to error handling and I don't have time for that now.
closes #767

ci-operator-configresolver: serve matching configurations

---

pkg/webreg/webreg.go

Fixes `/job` URLs that broke due to implementation of metadata in the config agent.

webreg: fix job page

---

pkg/webreg/graphviz.go
pkg/webreg/graphviz_test.go
pkg/webreg/webreg.go

This makes 2 changes to slightly improve the workflow and job graphs generated for webreg.
1. Dynamically name graph as "Job ..." or "Workflow ..." instead of all jobs being named as workflows.
2. Fix length issues of some arrows between nodes and subgraphs.

webreg: improve graphs

---

hack/extract-kubeconfig.sh

New UX:
```
$ hack/extract-kubeconfig.sh ci-op-r680h2s5 e2e-aws
Scanning ci-op-r680h2s5 for the $KUBECONFIG for the e2e-aws test...
Error from server (Forbidden): secrets is forbidden: User "stevekuznetsov" cannot list secrets in the namespace "ci-op-r680h2s5": no RBAC policy matched
You do not have permissions to see secrets for this namespace. Did you enter the namespace correctly?
```
```
$ hack/extract-kubeconfig.sh ci-op-r680h2s5 e2e-aws
Scanning ci-op-r680h2s5 for the $KUBECONFIG for the e2e-aws test...
No $KUBECONFIG for the e2e-aws test has been created yet, waiting...
^C
```
```
$ hack/extract-kubeconfig.sh ci-op-s6xflhby e2e-aws
Scanning ci-op-s6xflhby for the $KUBECONFIG for the e2e-aws test...
$KUBECONFIG saved to …
```

extract-kubeconfig: update to use oc extract

---

cmd/pj-rehearse/main.go

This PR allows to explicitly set a kubeconfig for prowjobs via a new flag on pj-rehearse.

PJ rehearse: Allow using dedicated kubeconfig for prowjobs

---

cmd/result-aggregator/main.go
pkg/results/report.go

Depends on #781 and NYI work to populate the fields,
/hold

ci-operator: require basic auth for result aggregator

---

cmd/ci-operator-config-mirror/main.go
test/ci-operator-config-mirror-integration/data/input/foo/barry-white/foo-barry-white-official.yaml
test/ci-operator-config-mirror-integration/data/output/foo/barry-white/foo-barry-white-official.yaml
test/ci-operator-config-mirror-integration/data/output/super-priv/barry-white/super-priv-barry-white-official.yaml

For repos that are both whitelisted and have official images we must not
disable promotion (they would be included even if not whitelisted, and they would not disable promotion in such case)
/cc @droslean

c-o-config-mirror: dont disable promotion for official image repos on whitelist

---

cmd/autobumper/main.go

This currently makes the job fail: https://deck-ci.apps.ci.l2s4.p1.openshiftapps.com/?job=periodic-prow-image-autobump

Autobumper: Stop running make update-app-ci as its gone

---

pkg/api/parameters.go
pkg/steps/multi_stage.go
pkg/steps/multi_stage_test.go

Effectively for correctness only.  This has worked so far because every E2E
test also uses images from `stable`, which adds the same dependency.

ci-operator multi-stage: make profile need release

---

Makefile
cmd/ci-operator-prowgen/testdata/postsubmit-TestFromCIOperatorConfigToProwYaml_Input_is_YAML_and_it_is_correctly_processed.yaml
cmd/ci-operator-prowgen/testdata/postsubmit-TestFromCIOperatorConfigToProwYaml_Using_a_variant_config,_one_test_and_images,_one_existing_job._Expect_one_presubmit,_pre_post_submit_images_jobs._Existing_job_should_not_be_changed..yaml
cmd/ci-operator-prowgen/testdata/postsubmit-TestFromCIOperatorConfigToProwYaml_one_test_and_images,_no_previous_jobs._Expect_test_presubmit_+_pre_post_submit_images_jobs.yaml
cmd/ci-operator-prowgen/testdata/presubmit-TestFromCIOperatorConfigToProwYaml_Input_is_YAML_and_it_is_correctly_processed.yaml
cmd/ci-operator-prowgen/testdata/presubmit-TestFromCIOperatorConfigToProwYaml_Using_a_variant_config,_one_test_and_images,_one_existing_job._Expect_one_presubmit,_pre_post_submit_images_jobs._Existing_job_should_not_be_changed..yaml
cmd/ci-operator-prowgen/testdata/presubmit-TestFromCIOperatorConfigToProwYaml_one_test_and_images,_no_previous_jobs._Expect_test_presubmit_+_pre_post_submit_images_jobs.yaml
hack/lib/integration.sh
pkg/prowgen/prowgen.go
pkg/prowgen/prowgen_test.go
test/integration/ci-operator-prowgen.sh
test/prowgen-integration/data/output/jobs/private-org/duper/private-org-duper-master-presubmits.yaml
test/prowgen-integration/data/output/jobs/private/duper/private-duper-master-periodics.yaml
test/prowgen-integration/data/output/jobs/private/duper/private-duper-master-postsubmits.yaml
test/prowgen-integration/data/output/jobs/private/duper/private-duper-master-presubmits.yaml
test/prowgen-integration/data/output/jobs/subdir/repo/subdir-repo-master-presubmits.yaml
test/prowgen-integration/data/output/jobs/super/duper/super-duper-master-periodics.yaml
test/prowgen-integration/data/output/jobs/super/duper/super-duper-master-postsubmits.yaml
test/prowgen-integration/data/output/jobs/super/duper/super-duper-master-presubmits.yaml
test/prowgen-integration/data/output/jobs/super/duper/super-duper-master-removed-promotion-presubmits.yaml
test/prowgen-integration/data/output/jobs/super/duper/super-duper-release-3.11-postsubmits.yaml
test/prowgen-integration/data/output/jobs/super/duper/super-duper-release-3.11-presubmits.yaml
test/repo-init-integration/expected/ci-operator/jobs/openshift/ci-tools/openshift-ci-tools-master-postsubmits.yaml
test/repo-init-integration/expected/ci-operator/jobs/openshift/ci-tools/openshift-ci-tools-master-presubmits.yaml
test/repo-init-integration/expected/ci-operator/jobs/openshift/origin/openshift-origin-master-postsubmits.yaml
test/repo-init-integration/expected/ci-operator/jobs/openshift/origin/openshift-origin-master-presubmits.yaml
test/repo-init-integration/expected/ci-operator/jobs/org/other/org-other-nonstandard-presubmits.yaml
test/repo-init-integration/expected/ci-operator/jobs/org/repo/org-repo-master-presubmits.yaml

make: don't check breaking changes in integration
---
hack: be more intelligent on updates
---
test: migrate the prowgen integration test
---
ci-operator-prowgen: stop setting default values
---

cleanup: stop setting default values

---

cmd/ipi-deprovision/ipi-deprovision.sh

ipi-deprovision: actually skip 3.11 clusters on GCP

---

cmd/ci-secret-bootstrap/main.go

/cc @alvaroaleman @petr-muller

Log o.maxConcurrency in ci-secret-bootstrap

---

pkg/webreg/webreg.go

Comparison operations in go templates are in prefix notation, not infix (to be more precise, comparators in go templates are actually functions). Go pre-1.14 allowed syntax errors and would handle infix notation. Go 1.14+, however, does not allow syntax errors for comparisons.
This fixes the web UI when compiling the configresolver with go 1.14+.

webreg: fix syntax error in templates

---

Makefile
hack/pr-deploy.yaml

We recently stopped updating `ci-operator-*-configs` CMs on `api.ci`,
and now I would like to remove them entirely. `make pr-deploy` needs
`ci-operator-master-configs` on the same cluster where it deploys, so
let's allow to deploy it on app.ci. Alternatively, we can change the
script to fetch the CM from `app.ci` with `--context app.ci` or
something similar.
- I was not able to `oc process` on app.ci without `--as system:admin`,
so adding it.
- The replacement base images' imagestreams are not (yet) migrated to
app.ci. Rather than figuring out what needs to move and what not, I
disabled the replacements. This does not run often enough for this
optimization to be crucial.
/cc @stevekuznetsov @AlexNPavel

Enable `make pr-deploy` on app.ci

---

cmd/pj-rehearse/main.go
pkg/config/release.go
pkg/registry/graph.go
pkg/registry/graph_test.go
pkg/rehearse/jobs.go

This changes the `NodeByName` type in `pkg/registry` to have explicit `References`, `Chains`, and `Workflows` fields as well as fixes a bug in the graphs handling of nested chains.
When the registry graph was first designed, it was assumed that nobody would make a chain and reference that have identical names (the `as` fields). This was not enforced in the release repo, however, and it has now become convention to have both a reference and a chain called `{i|u}pi-conf-cluster_type` for every `cluster_type` we support. This meant that the graph would overwrite references with the same names as chains. This could potentially cause a rehearsal to not occur for jobs that use just the reference with said name instead of the chain for whatever reason. It is also simply not ideal to overwrite …

rehearse,registry: make explicit maps for type in NodeByName

---

pkg/steps/multi_stage.go

When copying a secret from one spot to another, we need to be careful to
unset fields like the resource version and self-link. Instead, just copy
over the bits we need and create a new secret.

ci-operator: create a new secret instead of copying

---

pkg/util/client.go

ci-operator: load KUEBCONFIG if set, then use in-cluster

---

hack/lib/util/find.sh

The variable is now optional: https://golang.org/doc/gopath_code.html#GOPATH.
Integration tests fail silently without it.

integration: don't depend on $GOPATH

---

cmd/dptp-controller-manager/main.go
hack/run-dptp-controller-manager.sh
pkg/controller/promotionreconciler/reconciler.go

The 404 means that either:
* The repo/branch was deleted, so this request can not be reconciled
* We do not have access to this repo, which also means we can not
reconcile it
The PR also removes the `ignoredGitHubOrganizations`, we instead try
everything and just stop retrying on the 404.
Fixes https://github.com/openshift/release/issues/9283

Promotionreconciler: Stop retrying on requests that get a 404 from GH

---

pkg/api/config.go
pkg/api/config_test.go
pkg/api/helper/imageextraction.go
pkg/api/helper/imageextraction_test.go
pkg/api/types.go
pkg/defaults/defaults.go
pkg/steps/multi_stage.go
pkg/webreg/webreg.go
test/ci-operator-integration/multi-stage/configs/master/openshift-hyperkube-master.yaml
test/ci-operator-integration/multi-stage/expected/hyperkube.json

A test step from the registry needs to be able to reference an external
image so that it can ship together with the dependencies it needs.
Otherwise, every test configuration that ends up using that test step
will need to update its' `base_images` stanza, which is terrible for UX.

ci-operator: allow steps to reference external images

---

test/repo-init-integration/run.sh
test/secret-wrapper-integration.sh

```
#with -a, -r is there too.
man cp
-a, --archive
same as -dR --preserve=all
-R, -r, --recursive
copy directories recursively
man pgrep
-c, --count
Suppress normal output; instead print a count of matching processes.  When count does not match anything, e.g.
returns zero, the command will return non-zero value.
-P, --parent ppid,...
Only match processes whose parent process ID is listed.
```
The real reason that I want this PR: it is more mac-os friendly with it.

Simplify 2 commands in integration tests

---

cmd/ipi-deprovision/ipi-deprovision.sh

openshift 4, creates newtorks with autoCreateSubnetworks false, i.e Subnet Mode as Manual where the installer will create the subnets for the cluster.
openshift 3 CI, uses the networks in auto subnet mode automatically createing networks in all the regions.
Filter all the expired Openshift 4 clusters
```
$ FILTER="creationTimestamp.date('%Y-%m-%dT%H:%M%z')<${gce_cluster_age_cutoff} AND autoCreateSubnetworks=false AND name~'ci-'"
$ gcloud --project=openshift-gce-devel-ci compute networks list --filter "${FILTER}"
NAME                              SUBNET_MODE  BGP_ROUTING_MODE  IPV4_RANGE  GATEWAY_IPV4
ci-ln-vrrr4pk-f76d1-hxtnc-network   CUSTOM       REGIONAL
ci-op-d8lfy7cb-8eb03-wmtd8-network  CUSTOM       REGIONAL
ci-op-gvj98-network                 CUSTOM       REGIONAL …
```

ipi-deprovision: skip 3.11 clusters on GCP based on network's autoCreateSubnetwork

---

pkg/steps/clusterinstall/template.go

Copied from https://github.com/openshift/release/pull/9198, we want to run this in 4.x upgrade tests

Add openshift-tests run-resourcewatch to ugprades

---

pkg/steps/template.go

A template step already knows how to depend on the steps which provide
it with the paramters it needs. Therefore, today templates end up
requiring the release payload steps that create `$RELEASE_IMAGE_foo`.
These steps, in turn, require the suite of release images to be present
if necessary. There is no utlity in requiring those images, again, from
the template itself.
/assign @bbguimaraes @petr-muller

ci-operator: don't wait for release images in templates

---

pkg/controller/promotionreconciler/prowjobreconciler/prowjobreconciler.go
pkg/controller/promotionreconciler/reconciler.go

Right now its impossible to get back from a prowjob to the imagestreamtag that triggered its creation which makes debugging hard.

Improve promotionreconcilers logging

---

pkg/steps/multi_stage.go
pkg/steps/multi_stage_test.go

When we require a full release payload, we are guaranteed to get the
release images, as well. We do not need to require both in this case.

ci-operator: multi-stage: require release images only without payload

---

pkg/api/types.go

Same thing like https://github.com/openshift/ci-tools/pull/843 but for the remaining structs

Make `Architecture` field omitempty in all Release structs

---

pkg/webreg/graphviz.go
pkg/webreg/graphviz_test.go
pkg/webreg/webreg.go

This PR fixes an issue where chains with the same name as a reference would not appear in the web UI since the web UI only used names as an identifier.

webreg: allow chains with the same name as a reference be displayed

---

pkg/controller/promotionreconciler/reconciler.go

We log this on each and every imagestreamtag event for which we do not
have a config, e.G. all the imagestreamtags generated during tetsts.
During workdays this generates around 60k lines/30 minutes and its not
useful information, hence degrade to Trace which we don't log by
default.

Dptp-controller-manager: Degrade "no promotionconfig found" to trace

---

pkg/steps/clusterinstall/template.go

Reverts the changes from https://github.com/openshift/ci-tools/pull/845 until this command can
be made available in the 4.4 openshift-tests binary
In recent runs of the test, we see the following error:
```
Error: unknown command "run-resourcewatch" for ""
Run ' --help' for usage.
error: unknown command "run-resourcewatch" for ""
```
(See build log in https://gcsweb-ci.apps.ci.l2s4.p1.openshiftapps.com/gcs/origin-ci-test/pr-logs/pull/25040/pull-ci-openshift-origin-release-4.4-e2e-gcp-upgrade/294/ for one example)
The PR to add this command to 4.4 is open at https://github.com/openshift/origin/pull/25042

Revert "Add openshift-tests run-resourcewatch to ugprades"

---

cmd/private-org-sync/main.go
cmd/private-org-sync/main_test.go

Resolves  [DPTP-1228](https://issues.redhat.com/browse/DPTP-1228).
Git merge commands need to have a valid git configuration.

add git name,email flags to be used in merge commands

---

pkg/defaults/defaults.go
pkg/steps/release/create_release.go

It's possible for tag_specification and a release image literal to exist
together, in which case the tag_specification will populate the stable
stream with images that (mostly) get overriden immediately.

ci-operator: depend on images when we underride a release

---

pkg/webreg/webreg.go

I think it is useful to have an explicit example for people who want to migrate from `openshift_installer_src`-like templates.
/cc @bbguimaraes @stevekuznetsov

webreg: add example of overriding workflow with literal steps

---

pkg/webreg/webreg.go

This PR adds support for displaying variant tests in the job list and search pages separately from the standard tests and providing proper hyperlinks to the the individual job pages for variant jobs.

webreg: support variant jobs in the job list and search

---

cmd/dptp-controller-manager/main.go

Makes reasoning from the logs a bit easier, we also log the contexts we loaded from explicitly specified kuebconfig

Dptp-controller-manager: Log in-cluster config loading

---

cmd/ci-operator/main.go
pkg/api/types.go
pkg/defaults/defaults.go
pkg/steps/release/create_release.go
pkg/steps/release/import_release.go

The creation of a new release payload from local image sources in an
image stream and the import of an external release are simply two
separate actions, which are executed in entirely unrelated ways. This
commit breaks the previous step that conditionally did both into two,
and chooses which to add to the graph as appropriate. This should be a
no-op for users.
/assign @bbguimaraes @petr-muller

ci-operator: split the import and creation of releases

---

hack/revert-ci-operator.sh

As I don't want to search slack next time this is needed.

Add script to revert ci-operator version

---

cmd/ci-operator-config-mirror/main.go
test/integration/ci-operator-config-mirror.sh
test/integration/ci-operator-config-mirror/input-to-clean/foo/bar/foo-bar-master.yaml
test/integration/ci-operator-config-mirror/input-to-clean/foo/barry-white/foo-barry-white-master.yaml
test/integration/ci-operator-config-mirror/input-to-clean/foo/barry-white/foo-barry-white-official.yaml
test/integration/ci-operator-config-mirror/input-to-clean/super-priv/barry-white/super-priv-barry-white-master.yaml
test/integration/ci-operator-config-mirror/input-to-clean/super-priv/barry-white/super-priv-barry-white-official.yaml
test/integration/ci-operator-config-mirror/input-to-clean/super-priv/deprecated-repo/super-priv-deprecated-repo-master.yaml
test/integration/ci-operator-config-mirror/input-to-clean/super-priv/duper/super-priv-duper-master.yaml
test/integration/ci-operator-config-mirror/input-to-clean/super-priv/trooper/super-priv-trooper-deprecated.yaml
test/integration/ci-operator-config-mirror/input-to-clean/super-priv/trooper/super-priv-trooper-master.yaml
test/integration/ci-operator-config-mirror/input-to-clean/super/duper/super-duper-master.yaml
test/integration/ci-operator-config-mirror/input-to-clean/super/trooper/super-trooper-master.yaml

Introduces a map by repo with their data. Two methods will be responsible to clean up and generate the data.
Adds a `--clean` flag, and default it to true.
/cc @petr-muller @stevekuznetsov @openshift/openshift-team-developer-productivity-test-platform 

[ci-operator-config-mirror] allow the tool to delete the existing but deprecated configs 

---

pkg/controller/test-images-distributor/test_images_distributor.go
pkg/load/agents/registryAgent.go
pkg/load/load.go
pkg/load/load_test.go
pkg/registry/graph.go
pkg/registry/graph_test.go
pkg/registry/resolver.go
pkg/registry/resolver_test.go
pkg/webreg/graphviz.go
pkg/webreg/webreg.go

A requirement for https://github.com/openshift/ci-tools/pull/854.
We are going to need to keep track of the resolution stack to resolve
parameters, so this PR adds that to the existing implementation.  As a nice
side-effect, we can emit error messages with more context.

registry: keep track of chain stack when resolving

---

cmd/ci-operator/main.go
pkg/api/types.go
pkg/defaults/defaults.go
pkg/steps/release/create_release.go
pkg/steps/release/import_release.go

Revert "Merge pull request #874 from alvaroaleman/revert-5"
This reverts commit 6eb6b2b8cd9b98e792f83a8d541f1c48696105bf, reversing
changes made to c91af1cc534203c646bc5707197ad5bbaf1ac6a3.
---
ci-operator: evaluate namespace at runtime
When we construct the step and determine the list of parameters it
provides, we have not yet determined the inputs to the graph or created
a namespace, so we need to read that value at run-time when the
parameters are evaluated.
---

ci-operator: evaluate namespace at runtime

---

pkg/controller/test-images-distributor/test_images_distributor.go
pkg/controller/test-images-distributor/test_images_distributor_test.go

/hold
~needs extended rbac for the controller~ rbac was merged

Test images distributor: Create rbac for ci-operator

---

cmd/ci-operator/main.go
pkg/api/job_spec.go
pkg/defaults/defaults.go
pkg/steps/clusterinstall/clusterinstall.go
pkg/steps/input_image_tag.go
pkg/steps/input_image_tag_test.go
pkg/steps/lease.go
pkg/steps/lease_test.go
pkg/steps/multi_stage.go
pkg/steps/multi_stage_test.go
pkg/steps/output_image_tag.go
pkg/steps/output_image_tag_test.go
pkg/steps/pipeline_image_cache.go
pkg/steps/pod.go
pkg/steps/pod_test.go
pkg/steps/project_image.go
pkg/steps/release/create_release.go
pkg/steps/release/import_release.go
pkg/steps/release/promote.go
pkg/steps/release/release_images.go
pkg/steps/rpm_injection.go
pkg/steps/rpm_server.go
pkg/steps/source.go
pkg/steps/source_test.go
pkg/steps/template.go

Before, the namespace was a public property of the jobSpec. This lead to
semi-common wrong usage where it was evaluated before it was set,
resulting in bugs.
This PR changes jobSpec to provide getters and setters instead. The
getter will log an error if the namespace was unset, as this is always a
bug. This allows us to easely identify such wrong usages without making
any tests fail due to a potentially non-fatal issue.
Also fixes a bug where the namespace property was used wrongly as
described above.

Use methods for getting/setting the namespace on jobConfig

---

pkg/defaults/defaults.go
pkg/steps/release/import_release.go

Today, some jobs are using the following workflow:
- build an image or set `tag_specification`
- also provide `$RELEASE_IMAGE_LATEST`
With the previous implementation, two separate steps would create images
to fill out the stable stream and overwrite each other's work. The
effect was that the jobs could end up with images in the stable stream
that were not in the imported release from the env var, as they would be
created by the image steps and not be overwritten.
By allowing an explicit configuration for the import step, we can wait
on these other steps in the cases where we'd do in the past and continue
to provide the same user experience. This is not ideal and we need to
provide a clear way for users to simply import images they are
interested in, since the combination of …

ci-operator: allow waiting before importing a release

---

pkg/controller/test-images-distributor/test_images_distributor.go
pkg/controller/test-images-distributor/test_images_distributor_test.go

Needed because for some imagestreams, there is no `.spec.tags` set, even though there are imagestreamtags in them, for example:
```
apiVersion: image.openshift.io/v1
kind: ImageStream
metadata:
annotations:
hello: world
kubectl.kubernetes.io/last-applied-configuration: |
{"apiVersion":"image.openshift.io/v1","kind":"ImageStream","metadata":{"annotations":{},"name":"cli-jq","namespace":"ocp"}}
creationTimestamp: "2020-03-19T21:53:21Z"
generation: 1
name: cli-jq
namespace: ocp
resourceVersion: "744318274"
selfLink: /apis/image.openshift.io/v1/namespaces/ocp/imagestreams/cli-jq
uid: 0cb0d0c7-6a2c-11ea-a71e-42010a8e0003
spec:
lookupPolicy:
local: false
status:
dockerImageRepository: docker-registry.default.svc:5000/ocp/cli-jq
publicDockerImageRepository: …
```

Test images distributor: use imagestream.status to find all tags

---

pkg/api/graph.go

This method was unused.
/assign @petr-muller @bbguimaraes

ci-operator: remove step link equality

---

pkg/api/graph.go
pkg/api/graph_test.go
pkg/api/types.go
pkg/defaults/defaults.go
pkg/steps/lease_test.go
pkg/steps/multi_stage.go
pkg/steps/multi_stage_test.go
pkg/steps/output_image_tag.go
pkg/steps/output_image_tag_test.go
pkg/steps/release/create_release.go
pkg/steps/release/import_release.go
pkg/steps/release/release_images.go
pkg/steps/template.go

ci-operator: remove step link equality
This method was unused.
---
ci-operator: rename step link method to better reflect usage
The `Matches(other)` function was used to determine if `other` satisfied
the requirements of the link being evaluated. This rename makes that
relationship clear.
---
ci-operator: treat latest and initial stable as an API
---
ci-operator: refactor step links to be generic on is or istag
While it remains important to be able to differentiate at the call-site
on whether we're talking about an internal ImageStreamTag, a release
payload image, or other, it's not important to have a plethora of types
under the …

 ci-operator: refactor step links to be generic on is or istag

---

cmd/autoconfigbrancher/main.go
cmd/ci-operator-config-mirror/main.go
test/integration/ci-operator-config-mirror.sh
test/integration/ci-operator-config-mirror/output-only-super/foo/bar/foo-bar-master.yaml
test/integration/ci-operator-config-mirror/output-only-super/foo/barry-white/foo-barry-white-master.yaml
test/integration/ci-operator-config-mirror/output-only-super/foo/barry-white/foo-barry-white-official.yaml
test/integration/ci-operator-config-mirror/output-only-super/super-priv/duper/super-priv-duper-master.yaml
test/integration/ci-operator-config-mirror/output-only-super/super-priv/trooper/super-priv-trooper-master.yaml
test/integration/ci-operator-config-mirror/output-only-super/super/duper/super-duper-master.yaml
test/integration/ci-operator-config-mirror/output-only-super/super/trooper/super-trooper-master.yaml

Introduces the `--only-org` flag. Give the tool the ability to mirror the ci-operator configurations that belong in a specified organization.
/cc @stevekuznetsov @petr-muller 

[ci-operator-config-mirror] Add the ability to mirror the configs from a specific organization

---

pkg/steps/release/create_release.go
pkg/steps/release/import_release.go

These names are used in the generation of jUnit test cases and should
therefore be unique.

ci-operator: parameterize names of release steps

---

pkg/steps/output_image_tag.go
pkg/steps/output_image_tag_test.go

ci-operator: require stable image stream before creating tags

---

cmd/config-brancher/main.go
pkg/promotion/promotion_test.go
test/integration/ci-operator-config-mirror.sh
test/integration/config-brancher.sh
test/integration/config-brancher/expected/org/bump/org-bump-master.yaml
test/integration/config-brancher/expected/org/bump/org-bump-release-4.5.yaml
test/integration/config-brancher/expected/org/bump/org-bump-release-4.6.yaml
test/integration/config-brancher/expected/org/existing/org-existing-master.yaml
test/integration/config-brancher/expected/org/existing/org-existing-release-4.5.yaml
test/integration/config-brancher/expected/org/existing/org-existing-release-4.6.yaml
test/integration/config-brancher/expected/org/new/org-new-master.yaml
test/integration/config-brancher/expected/org/new/org-new-release-4.5.yaml
test/integration/config-brancher/expected/org/new/org-new-release-4.6.yaml
test/integration/config-brancher/input/org/bump/org-bump-master.yaml
test/integration/config-brancher/input/org/existing/org-existing-master.yaml
test/integration/config-brancher/input/org/existing/org-existing-release-4.5.yaml
test/integration/config-brancher/input/org/existing/org-existing-release-4.6.yaml
test/integration/config-brancher/input/org/new/org-new-master.yaml
test/pj-rehearse-integration/expected.yaml

The config-brancher tool works across a number of different versions:
- the current version devs are working on
- future versions we've created in advance
- the version we are bumping the dev version to
Originally, you only had to specify a version in one of these three
fields to ensure that the config for that version was updated when the
tool was run. At some point that regressed, so for instance when you
configured a current version, future versions and a bump version, unless
you specifically listed the bump version as a future version, the bump
version would not be updated. This is problematic as when we do a bump,
the dev configuration is changed to the bump version, and the branch for
that bump version must also be changed to no longer publish images, or
we'd have two branches …

config-brancher: always update all affected versions

---

cmd/pj-rehearse/main.go
pkg/results/report.go
test/pj-rehearse-integration/expected.yaml

This PR updates pj-reherase to support multiple build clusters for the configmap creation. It was done in preparation for https://issues.redhat.com/browse/DPTP-1244 but happens to (mostly) fix https://issues.redhat.com/browse/DPTP-1172
/hold
So I can be present when this gets rolled out.

Support multiple build clusters in pj-rehearse

---

cmd/autoowners/main.go
cmd/autoowners/main_test.go

I'd like to set up `--ignore-org=openshift-priv` in our autoowners job so that the two jobs stop to flap OWNERS in `openshift-priv/*` repos:
- Here is autoowners creating them: https://github.com/openshift/release/pull/9718/files
- Here is autoconfigbrancher deleting them: https://github.com/openshift/release/pull/9720/files
We do not need OWNERS in `openshift-priv` directories (they are managed purely by automation).
I also took the opportunity to modernize the naming and call the thing `blocklist`.
/cc @hongkailiu @droslean

autoowners: allow ignoring full orgs

---

pkg/webreg/webreg.go

The `chainTable` template definition had a minor mistake that broke the homepage below the first chain. This fixes that.

webreg: fix broken chain table on homepage

---

cmd/pj-rehearse/main.go
pkg/api/helper/imageextraction.go
pkg/api/metadata.go
pkg/rehearse/jobs.go
pkg/rehearse/jobs_test.go

This PR extends pj-reherase to propagate back the ImageStreamTags. It doesn't yet create the ImageStreamTags, will be done in a follow-up.

Rehearsals: Propagate back Imagestreamtags

---

pkg/webreg/webreg.go

Make it `release:` instead, to match the rest of the block.  The pre-colon spaces landed with the YAML block in 33c2eaa49b (#839).

pkg/webreg: Normalize "release   :" YAML

---

cmd/autoperibolossync/main.go
cmd/private-org-peribolos-sync/main.go

Successful Peribolos dump relies on having admin access on the target
repository, which we can now only guarantee in the `openshift` org. The
remaining pieces of the `openshift-priv` tooling already have (and use)
the same parameter. Non-openshift orgs are currently out of scope.
Will fix the following in https://deck-ci.apps.ci.l2s4.p1.openshiftapps.com/view/gcs/origin-ci-test/logs/periodic-org-sync/1274094822981898240, caused by an invalid dump of the https://github.com/code-ready/crc repo for which our bot does not have `admin` permissions. Non-openshift repositories are currently out of scope for the openshift-priv tooling.
```
{"component":"peribolos","file":"prow/cmd/peribolos/main.go:201","func":"main.main","level":"fatal","msg":"Configuration failed: failed to configure …
```

peribolos sync: add --only-org

---

pkg/api/types.go

Empty `from` means we do not substitute a `FROM` in the repo's
Dockerfile, which makes sense in some cases.
Hit while building an optional operator bundle image which is built from
scratch.

ci-operator configs: omitempty images.from

---

hack/lib/integration.sh
test/integration/cvp-trigger.sh
test/integration/cvp-trigger/periodic-ipi-deprovision.expected
test/integration/pj-rehearse.sh
test/integration/pj-rehearse/expected.yaml

Currently we filter out certain things during diff time. This PR changes
that to instead replace those fields with a static string before writing
the fixtures in order to reduce review overhead for no-op changes.

Avoid no-op changes in integration test fixtures

---

pkg/prowgen/prowgen.go
pkg/prowgen/prowgen_test.go
pkg/prowgen/testdata/zz_fixture_TestGenerateJobs_Promotion_configuration_causes_promote_job_with_unique_targets.yaml

If additionalImages is specified where two output names exist for
the same image, then prowgen can generate duplicate targets which
causes an error on ci-operator parsing (`--target=foo --target=foo`
is invalid).
Fix the generator so that
```
promotion:
additional_images:
base: base-7
base-7: base-7
base-8: base-8
```
does not generate
```
- --target=base-7
- --target=base-7
- --target=base-8
```
Blocks openshift/release#9949 which needs to publish `base`, `base-7`, and `base-8` from `base-7` and `base-8`
@stevekuznetsov

Prowgen should handle duplicate targets

---

pkg/steps/source.go

Samples: 
* https://deck-ci.apps.ci.l2s4.p1.openshiftapps.com/view/gs/origin-ci-test/pr-logs/pull/openshift_ci-tools/955/pull-ci-openshift-ci-tools-master-images/1277668136862093312#1:build-log.txt%3A88
* https://deck-ci.apps.ci.l2s4.p1.openshiftapps.com/view/gcs/origin-ci-test/pr-logs/pull/openshift_ci-tools/963/pull-ci-openshift-ci-tools-master-images/1277694810026676224#1:build-log.txt%3A199

Builds: Consider DNS errors to be transient

---

pkg/api/metadata.go
pkg/api/metadata_test.go

Main branches are now supported by the ci-operator. For now, they're
basically just aliases of the master branch.

Add main branch support.

---

cmd/pj-rehearse/main.go
cmd/pj-rehearse/main_test.go

Otherwise we do not end up creating all necessary ImageStreams (see
DPTP-1312). Also, adding some logging.
https://github.com/golang/go/wiki/CommonMistakes#using-goroutines-on-loop-iterator-variables
/cc @alvaroaleman @bbguimaraes

pj-rehearse: Avoid reusing loop iterators in closures 

---

pkg/steps/release/import_release.go

The pullspecs can come from two sources: `releases` stanza in the ci-op
config (which is an input on its own, so in this case its a no-op), and
`RELEASE_IMAGE_` variables. In the second case, we need to treat the
value as an input for the namespace to be different for different
release images.
/cc @stevekuznetsov @bbguimaraes

Consider a pullspec an input for ImportReleaseStep

---

pkg/steps/clusterinstall/template.go

Now that `run-resourcewatch` is available in 4.4 (https://github.com/openshift/origin/pull/25042), we should be able to add back the changes from https://github.com/openshift/ci-tools/pull/845 (reverted by https://github.com/openshift/ci-tools/pull/860) and get the git monitoring tool running in upgrade tests

Add run-resourcewatch (back) to upgrade tests

---

pkg/steps/clusterinstall/template.go

builds on https://github.com/openshift/ci-tools/pull/973
/assign @damemi

create namespace for leader election to succeed for resource watcher in upgrade

---

pkg/steps/clusterinstall/template.go

if https://github.com/openshift/ci-tools/pull/974 doesn't fix it, then I'll merge this one to remove everything and try again next week.
puts us back to a https://github.com/openshift/ci-tools/pull/965 state.

remove all changes for resourcewatch

---

pkg/steps/lease.go

In order to be able to meaningfully alert on lease exhausting we need to know the cloud on which it occured.

CI-Operator: Report lease type when acquiring fails

---

cmd/ci-operator/main.go
pkg/results/report.go

Its a tad weird because we end up with a time series called `ci_operator_error_rate` that has a `state` property which indicates if it actually was an error or not. Maybe we can rename it to `ci_operator_result_rate`?

CI-Operator: Report successes

---

pkg/api/types.go
pkg/defaults/defaults.go
pkg/steps/bundle_source.go
pkg/steps/bundle_source_test.go
pkg/steps/project_image.go
pkg/steps/testdata/4.6-expected/meteringoperator.v4.6.0.clusterserviceversion.yaml
pkg/steps/testdata/4.6/meteringoperator.v4.6.0.clusterserviceversion.yaml
test/integration/ci-operator/base/config/test-config.yaml
test/integration/ci-operator/base/expected_files/expected.json
test/integration/ci-operator/base/expected_files/expected_pull_secret.json
test/integration/ci-operator/base/expected_files/expected_with_template.json

This commit adds a new `BundleSourceStep` to be used by bundle image
builds. It creates a new image based off of the `pipeline:src` image
and uses `sed` to replace the pullspecs specified in the ci-operator
config with the in-cluster image references.
This is an early WIP and doesn't have tests yet. Those will be added soon.

pkg/steps: add new bundle source step

---

cmd/pj-rehearse/main.go

Currently, periodics that have openshift/release in extraRefs will fail to rehearse because clonerefs fails with
```
Invalid options: sync config for openshift/release provided more than once
```
This PR fixes that.

PJ-Reharse: Deduplicate extraRefs/Refs

---

cmd/pj-rehearse/main.go
pkg/config/release.go
pkg/config/release_test.go
pkg/config/template.go
pkg/config/template_test.go
pkg/diffs/diffs_test.go
pkg/rehearse/jobs.go
pkg/rehearse/jobs_test.go

Part of why pj-rehearse is annoying is that the names are often wrong (things contain something entirely different than their names suggests). Cleanups were extracted from https://github.com/openshift/ci-tools/pull/992 to reduce the size of the actual funcionality code change. There is no actual functionality change.
Various names changed to match their actual content:
- plugin config -> config updater config
- Template CM Manager -> Rehearsal CM Manager
- ConfigMapSource.Filename -> PathInRepo
- typos
Removed unused parameters and misplaced nil check.

pj-rehearse code cleanups

---

cmd/pj-rehearse/main.go
pkg/config/release.go
pkg/rehearse/configmaps.go
pkg/rehearse/configmaps_test.go

The only purpose of CMManager is to support rehearsals, so it makes
sense for it to live in the `rehearse` package. This makes the
assumptions done by the code correct, and allows to simplify names even
more.
The direction of this change is to lessen the importance of the `ConfigMapSource` struct to make decisions about CM names.
This because the only thing that knows the names is the config-updater config for the production CMs, and the rehearse package can then infer a name from that.

rehearse: extract CMManager to rehearse package

---

cmd/registry-replacer/main.go

Self-approve is the first boolean arg, not the second: https://github.com/openshift/ci-tools/blob/584bfc8c8a36b2b533bee2b6d03368b0a975e532/cmd/registry-replacer/main.go#L122

Registry replacer: Fix self-approve option

---

cmd/registry-replacer/main.go
cmd/registry-replacer/main_test.go
pkg/github/github.go

Because its also needed for the `ocp-build-data-enforcer`

Factor githubFileGetter out of registry-replacer

---

pkg/steps/multi_stage.go
pkg/webreg/webreg.go

This PR adds a link to the step registry info page for failed multistage
steps in the test logs. This makes it easier to debug failing tests.
This also makes the 404 error page for non-existent registry components
more verbose. Since it is possible for users to be running a job that
has an embedded literal step in the test config, this error page may be
hit more often so it was made a bit more verbose.

multi_stage: add link to registry info page for failed steps

---

pkg/util/client.go
pkg/util/client_test.go

We had a case where the dptp-controller-manager got a KUBECONFIG submitted via env var that was not actually in the secret mounted there. This error got silently swallowed. After this PR, we will fail startup instead, preventing silently defunct binaries.

Kubeconfig loading: Error if env var has not found kubeconfig

---

cmd/registry-replacer/main.go
cmd/registry-replacer/main_test.go
cmd/registry-replacer/testdata/zz_fixture_TestReplacer_OCP_builder_pruning_happens.yaml

Produces https://github.com/openshift/release/pull/10413
Guaranteed to break some ppl once enabled. Its featuregated though.

Registry replacer: Prune ocp/builder replacements

---

pkg/api/config.go
pkg/api/config_test.go
pkg/api/types.go
pkg/steps/multi_stage.go
pkg/steps/multi_stage_test.go
pkg/webreg/webreg.go
test/e2e/multi-stage.sh
test/e2e/multi-stage/config.yaml

* allow_skip_on_success is an umbrella flag being set inside the "steps" element,
it gives a signal to all steps that define optional_on_success to be
skipped
* optional_on_success is being set inside individual step
If both are set to true and all previous `pre` and `test` steps were
successful, the given step will be skipped. If the step is a `post` step it will be skipped in this case even if previous `post` steps failed but all `pre` and `test` steps passed.

Define AllowSkipOnSuccess and OptionalOnSuccess flags

---

cmd/ipi-deprovision/ipi-deprovision.sh

We've had the "could not determine region" bail-out since d9ba62b1d2 (#380).  But we only [run GCP CI in us-east1][1] today.  Falling back to us-east1 will allow us to clean up clusters which die in setup after creating the network but before creating any subnets, like:
```console
$ gcloud --project=openshift-gce-devel-ci compute networks describe ci-op-pb0tz84t-d2203-tgjwj-network
autoCreateSubnetworks: false
creationTimestamp: '2020-07-09T11:21:51.305-07:00'
id: ...
kind: compute#network
name: ci-op-pb0tz84t-d2203-tgjwj-network
routingConfig:
routingMode: REGIONAL
selfLink: https://www.googleapis.com/compute/v1/projects/openshift-gce-devel-ci/global/networks/ci-op-pb0tz84t-d2203-tgjwj-network
x_gcloud_bgp_routing_mode: REGIONAL
x_gcloud_subnet_mode: CUSTOM
```
Before we shard out to …

cmd/ipi-deprovision: Fall back to assuming us-east1 for GCP

---

pkg/rehearse/jobs.go

Fixes https://issues.redhat.com/browse/DPTP-1377.

rehearse: fix `wait.Poll` return value

---

pkg/results/report.go

Sample: https://prow.ci.openshift.org/view/gs/origin-ci-test/pr-logs/pull/openshift_ci-tools/1030/pull-ci-openshift-ci-tools-master-format/1288132168748371968#1:build-log.txt%3A30
That is this line and it panics because the response is nil: https://github.com/openshift/ci-tools/blob/2f5585541d75db395612b0f63eeb7e561f85105d/pkg/results/report.go#L137
Reporting is always best-effort and should never result in a panic.

CI operator: Don't panic when reporting fails

---

images/generate-registry-metadata/Dockerfile

Apparently, diff isn't included by default in the centos:8 image so
diffutils needs to be installed.

images/generate-registry-metadata: install diffutils

---

cmd/applyconfig/applyconfig.go

ref. https://stackoverflow.com/questions/18062026/resolve-symlinks-in-go/28249042
and also tested locally with the folder in release repo (i should have done this in the last round)
Fix https://prow.ci.openshift.org/view/gs/origin-ci-test/pr-logs/pull/openshift_release/10545/pull-ci-openshift-release-master-vsphere-dry/1288841842586030080#1:build-log.txt%3A28

applyconfig: handle properly the relative path of a symlink

---

pkg/load/agents/configAgent.go

We need to hold the lock when building the index, otherwise a different
routine might manipulate the index map while we are still iterator over
it.
Sample:
==================
WARNING: DATA RACE
Read at 0x00c0002fe808 by goroutine 54:
github.com/openshift/ci-tools/pkg/load/agents.(*configAgent).buildIndexes()
/home/alvaro/git/golang/src/github.com/openshift/ci-tools/pkg/load/agents/configAgent.go:206 +0x6c
github.com/openshift/ci-tools/pkg/load/agents.(*configAgent).loadFilenameToConfig()
/home/alvaro/git/golang/src/github.com/openshift/ci-tools/pkg/load/agents/configAgent.go:191 +0x230
github.com/openshift/ci-tools/pkg/load/agents.(*configAgent).loadFilenameToConfig-fm()
/home/alvaro/git/golang/src/github.com/openshift/ci-tools/pkg/load/agents/configAgent.go:183 +0x44 …

Config Agent: Fix data race

---

cmd/pj-rehearse/main.go
pkg/config/release.go
pkg/load/agents/registryAgent.go
pkg/load/load.go
pkg/load/load_test.go
pkg/rehearse/jobs_test.go
pkg/webreg/graphviz_test.go
pkg/webreg/webreg.go

This PR adds github links and owner information for all registry
components in the `configresolver` web UI using the registry metadata.
This PR also exposes the registry component suffixes and replaces all
hardcoded suffix values across all packages with the exposed consts to
prevent typos and make potential future refactors easier.

webreg: add metadata based info to web UI

---

cmd/ipi-deprovision/ipi-deprovision.sh

In order to see what the installer is up to, we should send SIGQUIT on
timeout so that the Go runtime prints the active stack trace.

ipi-deprovision: send SIGQUIT to installer on timeout

---

pkg/results/report.go

before
```
level=info msg="Reporting job state \"succeeded\" with reason \"unknown\""
```
after
```
level=info msg="Reporting job state 'succeeded'"
level=info msg="Reporting job state 'failed' with reason 'something'"
```

[pkg/report] fix result's report message

---

hack/lib/integration.sh
pkg/load/agents/configAgent.go
pkg/load/agents/registryAgent.go
pkg/load/agents/utils.go
test/integration/ci-operator-configresolver.sh

This PR makes the configresolver integration tests check for an exact number of revision changes.
As part of this, the periodic reload and event coalescing was removed.
I will issue a follow-up to remove the now-unused arguments.

Configresoler integration test: Check for exact number of rev changes

---

cmd/autopublicizeconfig/main.go

The tool was ignoring the whitelist since the map was always empty.

[autopublicizeconfig] allow validation to change the options

---

pkg/backporter/backporter.go

Sort clones by Target Release to make it easier for users to spot gaps

Order clones by Target Release

---

cmd/private-org-sync/main.go

The problem is described in https://issues.redhat.com/browse/DPTP-1419
It seems that we hit a special case where the commits are less than 8 and the push was still failing.

perform a merge when depth is shallow out and push was still failing

---

CONFIGURATION.md
cmd/ci-operator-prowgen/main_test.go
pkg/api/config.go
pkg/api/config_test.go
pkg/steps/release/create_release.go
test/integration/ci-operator-prowgen/input/config/super/duper/super-duper-release-3.11.yaml

In order to allow users to inspect the version of the cluster that they
are interacting with, we use the MAJOR.MINOR version from the imported
release context in order to create a test-specific version that follows
the format used for production versions, nightlies, and CI candidates.
```
$ oc adm release info registry.svc.ci.openshift.org/ci-op-kh0zrk59/release:latest
Name:      4.5.0-0.test-2020-08-05-191240-ci-op-kh0zrk59
Digest:    sha256:225640962cefbb1a9c5a842287de3d054838a684442f5e04017365d1883b8002
Created:   2020-08-05T19:12:53Z
OS/Arch:   linux/amd64
Manifests: 419
Pull From: registry.svc.ci.openshift.org/ci-op-kh0zrk59/release@sha256:225640962cefbb1a9c5a842287de3d054838a684442f5e04017365d1883b8002
Release Metadata:
Version: …
```

ci-operator: explicitly name ephemeral releases

---

CONFIGURATION.md
cmd/ci-operator-prowgen/main_test.go
pkg/api/config.go
pkg/api/config_test.go
pkg/steps/release/create_release.go
test/integration/ci-operator-prowgen/input/config/super/duper/super-duper-release-3.11.yaml

This reverts commit 97562d95c1bb7fcadc3953db9974b7c1ff4e69d5.
```json
{"component":"dptp-controller-manager","error":"failed to laod config: loading config failed: invalid ci-operator config: invalid configuration: tag_specification.name: must be of the form 4.\u003cminor\u003e, not \"origin-v3.11\"","file":"/go/src/github.com/openshift/ci-tools/cmd/dptp-controller-manager/main.go:190","func":"main.main","level":"fatal","msg":"Failed to construct ci-opeartor config agent","severity":"fatal","time":"2020-08-05T20:44:09Z"}
```

Revert "ci-operator: explicitly name ephemeral releases"

---

cmd/publicize/server.go

On a merge error the upstream code already tries to `merge --abort`, and if that fail to then it returns an error. Otherwise, the error will be nil and the merged bool will be false. The previous implementation caused the tool to continue on a merge error. This PR fixes that.

[publicize] exit with error if merge won't succeed

---

pkg/api/config.go
pkg/api/config_test.go
pkg/steps/release/create_release.go
test/integration/ci-operator-prowgen/input/config/super/duper/super-duper-release-3.11.yaml

Follow up https://coreos.slack.com/archives/CEKNRGF25/p1596722228493900?thread_ts=1596681831.483000&cid=CEKNRGF25
https://prow.ci.openshift.org/view/gs/origin-ci-test/logs/release-openshift-origin-installer-launch-gcp/1291364637454897152
```json
"promotion": {
"name": "stable",
"namespace": "$(NAMESPACE)"
},
```
Reverts openshift/ci-tools#1076

Revert "ci-operator: allow origin-v3.11 release version"

---

pkg/dispatcher/config.go
pkg/dispatcher/config_test.go
pkg/jobconfig/files.go

After merge (this should not be a breaking change), I will contact authors of each bastion in https://github.com/openshift/release/tree/master/core-services/sshd-bastion/ to ask them add the label `"dptp.openshift.io/ssh-bastion": "true"` to the jobs which uses the bastions.
/cc @stevekuznetsov @alvaroaleman @bbguimaraes

Keep ssh bastion jobs on api.ci

---

pkg/controller/promotionreconciler/reconciler.go
pkg/controller/test-images-distributor/test_images_distributor.go
pkg/util/imagestreamtagmapper/imagestreamtagmapper.go
pkg/util/imagestreamtagmapper/imagestreamtagmapper_test.go

Currently we have two controllers that care about imagestreamtags but
watch imagestreams because imagestreamtags do not support watching. One
implication of this is that whenever any tag in a given imagestream
changes, all tags in that stream get reconciled, which is very
inefficient.
This PR adds an imagestreamtagmapper which maps imagestreams to images,
giving update events a special treatment by only enqeueing the tags that
have changed.
This mapper is then used in the promotionreconciler and the
test-images-distributor. The usage of this mapper allows the
promotionreconciler to drop request coalescing.

Only enq changed imagestreamtags on imagestream update event

---

test/e2e/simple.sh

After migrating the e2e job to a build farm, the code that imports releases resolved by release-controller to release payloads in authenticated namespaces on api.ci does not seem to be able to access these images, despite us providing the e2e tests the credentials in https://github.com/openshift/release/pull/10912. This means that either the credentials are not used properly or there is some other problem. This currently blocks unrelated merges to ci-tools, so I propose to disable it temporarily to unblock them.
Immediately after that I will open a revert linked to a card that will make us fix this.

disable the failing custom-release e2e test

---

pkg/steps/release/create_release.go
pkg/steps/release/release_images.go

When we import a release from a stream that's configured to have a name
and be released in some way, we can piggy-back off of that name to
create a name for our release that clearly labels us as a derivative
while also uniquely identifying the test configuration that is running.
All of this is best-effort and will no-op if no release config is
present, allowing us to still mark the cluster version as one udner test
but not identifying the parent release.
/assign @petr-muller @smarterclayton

ci-operator: expose ephemeral cluster versions based on parents

---

cmd/private-org-sync/main.go
cmd/private-org-sync/main_test.go

The request is described in https://issues.redhat.com/browse/DPTP-1426
/cc @openshift/openshift-team-developer-productivity-test-platform @petr-muller @jupierce 

[private-org-sync] don't fail on merge conflict errors, instead print a warning

---

pkg/defaults/defaults.go
pkg/steps/release/import_release.go
test/e2e/simple.sh

```
grep -irn "oc adm release" .
./pkg/steps/project_image.go:74:                // oc adm release info tooling
./pkg/steps/release/create_release.go:193:oc adm release new --max-per-registry=32 -n %q --from-image-stream %q --to-image-base %q --to-image %q
./pkg/steps/release/create_release.go:194:oc adm release extract --from=%q --to=/tmp/artifacts/release-payload-%s
./pkg/steps/release/import_release.go:156:      // get the CLI image from the payload (since we need it to run oc adm release extract)
./pkg/steps/release/import_release.go:220:oc adm release extract%s --from=%q --file=image-references > /tmp/artifacts/%s
./pkg/steps/clusterinstall/template.go:215:            DIGEST="$(oc adm release info --image-for="${NAME}" | sed 's/.*@//')"
./pkg/steps/clusterinstall/template.go:417: …
```

Specify registry-config for oc adm release command

---

cmd/blocking-issue-creator/main.go

This change makes blocking-issue-creator consistent with how other tools
(repo-brancher, mainly) treat the `--current-release` option. The
current release is considered a "future-release" and therefore blocking
issue is created for it.
Consistently, repo-brancher (the tool that performs the fast forwarding)
will fast-forward code to the release branch for the current release,
which implies the necessity to have that blocker issue.
The gist here is that `FutureOptions.Validate` does the backfill from
`--current-release`, whereas `Options.Validate` does not:
https://github.com/openshift/ci-tools/blob/ae10a83be7627796abe322a12672a365a294e9bb/pkg/promotion/promotion.go#L85-L98
/cc @stevekuznetsov 

blocking-issue-creator: block merges to current-release too

---

cmd/ci-operator-configresolver/main.go
pkg/load/load.go
pkg/registry/resolver.go
pkg/registry/resolver_test.go
test/integration/ci-operator-configresolver.sh

Full validation can only be done in the presence of test configurations,
but many useful validations can be performed when the registry is initially
loaded.
There is probably a more efficient algorithm, but this way we maintain a
single execution path for all validation phases.  Validating the entire
step registry in `openshift/release` still stays below 1s on my machine and
I don't see any change in total execution time.
The original bug report has been added as an integration tests.  I've also
verified that the new code correctly identifies the error:
```
$ cd openshift/release/
$ git checkout --quiet 67cb826934
$ ci-operator-configresolver --validate-only …
INFO[0000] Configs reloaded                             duration=683.772282ms
FATA[0000] Failed to get registry agent: Failed to …
```

pkg/load: partially validate registry contents

---

pkg/steps/release/import_release.go

Not only does importing a release provide the release payload, but it
also creates all of the imported tags from the payload as well.

ci-operator: steps: importing a release creates the stream

---

pkg/steps/clusterinstall/template.go

Environment variables on the Pod's contents are entirely unnecessary
unless you need to expose it to something in the script, then you also
need to explcitly have the value replaced, otherwise what LOOKS like an
environment variable dereference by bash actually is bash reading a
literal string that's injected at template instance render time.

clusterinstall: fix template

---

cmd/registry-replacer/README.md
cmd/registry-replacer/main.go
cmd/registry-replacer/main_test.go
cmd/registry-replacer/testdata/zz_fixture_TestReplacer_Context_dir_gets_fixed_up.yaml
cmd/registry-replacer/testdata/zz_fixture_TestReplacer_Dockerfile_gets_fixed_up.yaml
pkg/api/ocpbuilddata/types.go

The diff this PR produces is here: https://github.com/openshift/release/pull/10799
First commit is pure moving code around, second commit is the actual change.

Registry replacer: Update dockerfiles from ocp-build-data

---

pkg/api/config.go
pkg/api/config_test.go
pkg/api/types.go
pkg/defaults/defaults.go
pkg/defaults/defaults_test.go
pkg/steps/bundle_source.go
pkg/steps/bundle_source_test.go
pkg/steps/index_generator.go
pkg/steps/index_generator_test.go
pkg/steps/project_image.go
test/e2e/simple.sh
test/e2e/simple/optional-operators.yaml
test/manifests/4.6/hive.crd.yaml
test/manifests/4.6/image-references
test/manifests/4.6/meteringconfig.crd.yaml
test/manifests/4.6/meteringoperator.v4.6.0.clusterserviceversion.yaml
test/manifests/4.6/prestotable.crd.yaml
test/manifests/4.6/report.crd.yaml
test/manifests/4.6/reportdatasource.crd.yaml
test/manifests/4.6/reportquery.crd.yaml
test/manifests/4.6/storagelocation.crd.yaml
test/manifests/bundle.Dockerfile
test/manifests/metadata/annotations.yaml

This PR adds support for building operator index images by adding an
`operator_index` field for images. The process is handled in a similar
manner to the bundle images, which require 2 steps, with the first step
involving building a new image to be used as a source image.
First, an image build is made that runs the `opm` command that generates
the `index.db` file and a dockerfile to build the corresponding index
image.
Second, a build is made with the previous build's image as its source,
using the dockerfile generated by `opm`.
This PR also adds validation for the `images` section of the config as
both `operator_manifests` and `operator_index` add potential for user
error.

ci-operator: add support for building operator index images

---

pkg/controller/test-images-distributor/test_images_distributor.go
pkg/controller/test-images-distributor/test_images_distributor_test.go

When users query for an image on a build cluster, we want them to pull
from the internal registry of that cluster. This will force the internal
registry to use pull-through and cache the image layers, which was the
point of distributing the images in the first place.

image distributor: use local image reference policy

---

pkg/steps/clusterinstall/template.go

[Avoiding][1]:
```
2020/08/20 21:43:28 Running pod e2e-gcp-upgrade
/bin/bash: -c: line 12: unexpected EOF while looking for matching `''
/bin/bash: -c: line 20: syntax error: unexpected end of file
2020/08/20 21:43:31 Container resourcewatch in pod e2e-gcp-upgrade failed, exit code 1, reason Error
```
fixing a typo from 31b8aa1900 (#1131).
[1]: https://storage.googleapis.com/origin-ci-test/logs/release-openshift-origin-installer-e2e-gcp-upgrade/1296562905130471424/build-log.txt

pkg/steps/clusterinstall/template: Fix resourcewatch jsonpath quote

---

pkg/steps/clusterinstall/template.go

Preserve the resource watch logs in artifacts.

resourcewatch: copy output into resourcewatch.log

---

test/e2e/multi-stage.sh
test/e2e/simple.sh

This reintroduces the actual e2e test fix commit from https://github.com/openshift/ci-tools/pull/1132 that got reverted in https://github.com/openshift/ci-tools/pull/1140. I think that the *other* commit (in `template.go`) that was the reason for the revert was not needed for the actual e2e test fix, so I think we can get the e2e fix back in separately while we figure out how to fix the `tempalte.go` change.

e2e: use import secrets always

---

pkg/steps/template.go

ci-operator: detect running pods using phase
Looking at conditions made us think that pods were finished when a
single container had exited, so we should look at the overall phase
instead.
---
ci-operator: cancel notifier when pod doesn't start
The notifiers that gather logs and write jUnit expect to be triggered
when a Pod terminates, but never are if the Pod never starts in the
first place. Our early-exit code waits on the notifier, so it was
nonfunctional as written.
---

Detect failed pods better

---

pkg/defaults/defaults.go
pkg/steps/pod.go
pkg/steps/pod_test.go
pkg/steps/release/create_release.go
pkg/steps/release/import_release.go
pkg/steps/testdata/zz_fixture_TestPodStepExecution_Pod_run_by_PodStep_fails_so_PodStep_terminates_and_returns_an_error.yaml
pkg/steps/testdata/zz_fixture_TestPodStepExecution_Pod_run_by_PodStep_succeeds_so_PodStep_terminates_and_returns_no_error.yaml

The built-in ImageStreamTag resolution process in OpenShift is arcane
and very difficult to understand in conjuction with all of the different
levels of image imports and distribution we have. We always want to pull
from the local registry when we're creating a Pod with an ImageStreamTag
so we can just do the digest resolution ourselves and use the resolved
pull specification in the Pod's configuration. If that ends up being
pull-through with the central registry as the source, that's fine, but
opaque to the end-user ci-operator process.
/cc @bparees

ci-operator: create Pods with resolved refs

---

cmd/ocp-build-data-enforcer/main.go

The code in gatherAllOCPImageConfigs relies on the directory path not
having a trailing slash:
https://github.com/openshift/ci-tools/blob/ae31d1102348b34a2cc218c6df66420927bb3b42/pkg/api/ocpbuilddata/types.go#L343
`Clean` cleans the path on input.

ocp-build-data-enforcer: cleaup input path

---

pkg/steps/release/release_images.go

We want users of these ImageStreams to refer to their content with the
local registry's domain, not wherever their content might be sourced
during pull-through.

ci-operator: create imagestreams with local reference policy

---

pkg/api/types.go
pkg/registry/resolver.go
pkg/registry/resolver_test.go
pkg/webreg/webreg.go

This allows e.g. the normal install step to define the install target to
be release:latest and the upgrade workflow to override it to be
release:initial.

ci-operator: allow overriding dependency definitions

---

pkg/controller/promotionreconciler/prowjobreconciler/prowjobreconciler.go

Currently, we add the promotionreconciler twice to the manager,
resulting in it getting started twice, resulting in a datarace as we
replace an in-use workqueue and double the configured workers.

Prompotionreconciler: Only start once

---

pkg/webreg/webreg.go

Fix step parameter example. Before, the example suggested the `env` is a
member of the `TestStepConfiguration` struct, but it is actually a
member of the `MultiStageTestConfiguration` one (under `steps:`).
Also:
- fix anchors
- provide captions for the examples to separate them

registry docs: cleanups

---

pkg/steps/template.go

ci-operator: add an import alias for k8s errors
---
ci-operator: immediately print when a Pod fails to start
---

ci-operator: immediately print when a Pod fails to start

---

pkg/api/config.go
pkg/api/config_test.go

This allows users to depend on the `ci-index` image in multistage test steps, which is required for optional-operator tests.

api/config: add support for using ci-index as step dependency

---

pkg/steps/index_generator.go
pkg/steps/index_generator_test.go

We are adding custom-build bundles into an ephemeral, empty indices, so
we need `--mode semver` to avoid problems when adding CSVs with
`replaces:` stanzas.
Also, cleanup imports (courtesy of Goland) and improve tests.
/cc @stevekuznetsov @AlexNPavel

ci-operator: build oo indices with `--mode semver` 

---

cmd/ci-secret-bootstrap/main.go
cmd/ci-secret-bootstrap/main_test.go
pkg/api/secretbootstrap/secretboostrap.go
pkg/api/secretbootstrap/secretboostrap_test.go
pkg/controller/secretsyncer/secretsyncer.go
pkg/controller/secretsyncer/secretsyncer_test.go

This PR allows defining and targeting a named group of clusters via ci-secret-bootstrap.
The resolving is implemented as part of a custom unmarshaler, which makes this completely transparent for consumers.
This PR breaks the config format, which means after we merge it, we need to adjust the config in o/release to have the secret configs below the `secret_configs` as seen in the testcase changes.
Its recommended to review this PR with whitespace changes disabled.

CI secret boostrap: Allow targeting a named group of clusters

---

pkg/steps/source.go

Sample: https://prow.ci.openshift.org/view/gs/origin-ci-test/pr-logs/pull/openshift_ci-tools/1185/pull-ci-openshift-ci-tools-master-images/1300548570507644928

Imagebuild: connection reset by peer is a transient failure

---

cmd/testgrid-config-generator/README.md
cmd/testgrid-config-generator/main.go
cmd/testgrid-config-generator/main_test.go
test/integration/testgrid-config-generator.sh
test/integration/testgrid-config-generator/config/_allow-list.yaml
test/integration/testgrid-config-generator/config/jobs/org/repo/org-repo-master-periodics.yaml
test/integration/testgrid-config-generator/expected/redhat-openshift-ocp-release-4.2-informing.yaml

This change allows the release-type to be specified in the allowed
list thereby deprecating the need to add the release-type annotation.

Add allow-list as input to testgrid

---

pkg/steps/template.go
pkg/steps/template_test.go

> A Pod that is initializing is in the Pending state but should have a
> condition Initialized set to true.
https://kubernetes.io/docs/concepts/workloads/pods/init-containers/#detailed-behavior

ci-operator: check if init containers are running

---

pkg/api/config.go
pkg/api/config_test.go
pkg/prowgen/prowgen.go
pkg/prowgen/prowgen_test.go
pkg/prowgen/testdata/zz_fixture_TestGenerateJobs_operator_section_creates_ci_index_presubmit_job.yaml
test/integration/ci-operator-prowgen/input/config/super/duper/super-duper-master.yaml
test/integration/ci-operator-prowgen/output/jobs/super/duper/super-duper-master-presubmits.yaml

This PR adds support for automatically generating a `ci-index`
targetting presubmit for any config that contains an `operator` section.

prowgen: add support for generating ci-index presubmit

---

pkg/steps/project_image.go
pkg/steps/source.go
pkg/steps/testdata/zz_fixture_TestCreateBuild_basic_options_for_a_presubmit.yaml
pkg/steps/testdata/zz_fixture_TestCreateBuild_with_OAuth_token.yaml
pkg/steps/testdata/zz_fixture_TestCreateBuild_with_a_path_alias.yaml
pkg/steps/testdata/zz_fixture_TestCreateBuild_with_a_pull_secret.yaml
pkg/steps/testdata/zz_fixture_TestCreateBuild_with_extra_refs.yaml
pkg/steps/testdata/zz_fixture_TestCreateBuild_with_extra_refs_setting_workdir_and_path_alias.yaml
pkg/steps/testdata/zz_fixture_TestCreateBuild_with_ssh_key.yaml

Before this commit, we set the build labels like vcs ref identifier in the
projectDirectoryImageBuildStep but nowhere else. This means that all the
other images will either not have these labels or inherit them from
their base.
When such an image without correct labels gets promoted, the
promotionreconciler and possibly other automation that relies on the
correctness on them doesn't work properly anymore.

Make sure build labels are always set correctly

---

pkg/api/config.go
pkg/api/config_test.go
pkg/api/types.go
pkg/prowgen/prowgen.go
pkg/prowgen/prowgen_test.go
pkg/prowgen/testdata/zz_fixture_TestGenerateJobs_two_tests_and_empty_Images_with_one_test_configured_as_a_postsubmit.yaml
pkg/webreg/webreg.go
test/integration/ci-operator-prowgen/input/config/super/duper/super-duper-master.yaml
test/integration/ci-operator-prowgen/output/jobs/super/duper/super-duper-master-postsubmits.yaml

This PR allows users to generate postsubmits from a test defined
in ci-operator by adding a `postsubmit` field to the TestStepConfiguration
type.

prowgen: add support for generating postsubmits

---

pkg/webreg/webreg.go

It seems that it is mountPath in volumeMounts: but mount_path in credentials:
Signed-off-by: Johnny Bieren <jbieren@redhat.com>

Fix mountPath vs mount_path in README

---

pkg/lease/client.go
pkg/lease/fake.go
pkg/steps/lease.go

The upstream client and server errors are confusing because both
non-existent and exhausted resources result in an HTTP 404 error.
We often receive support requests because the error message (`failed to
acquire lease: resources not found`) can give the false impression that
the test infrastructure is at fault.
Sample output:
```
2020/09/04 18:08:42 Acquiring lease for "aws-quota-slice"
2020/09/04 18:08:47 warning: Failed to acquire resource, current capacity: 0 free, 1 leased
2020/09/04 18:08:47 Ran for 2m17s
error: some steps failed:
* could not run steps: step test failed: failed to acquire lease: resources not found
```

pkg/steps/lease: print resource metrics on failure

---

images/ci-operator/Dockerfile

Some handcrafted jobs (some of them important upgrade jobs) are doing
`python -c ...` calls. Recently we bumped tools to centos8 which does
not include python by default.
/cc @droslean @deads2k

ci-operator image: install python2

---

cmd/pj-rehearse/main.go

We should just provide correct kubeconfigs for all clusters. Also, change the default prowjob cluster to app.ci.

pj-rehearse: stop assuming to run on api.ci

---

cmd/ci-secret-generator/main.go
cmd/ci-secret-generator/main_test.go
pkg/bitwarden/cli.go
pkg/bitwarden/cli_test.go

ci-secret-generator: run bash commands safely
---
ci-secret-generator: clean up errors
Before, illegible and not useful:
```
INFO[0030] processing attachment                         attachment=build01_ci_reg_auth_value.txt command="oc --as system:adsmin --context api.ci get secrets --namespace ocp -o json | jq '.items[] | select(.type==\"kubernetes.io/dockercfg\") | select(.metadata.annotations[\"kubernetes.io/service-account.name\"]==\"default\") | .data[\".dockercfg\"]' --raw-output | base64 --decode | jq '.[\"docker-registry.default.svc:5000\"].auth' --raw-output | tr -d '\\\\n'" item=build_farm
ERRO[0031] oc --as system:adsmin --context api.ci get secrets --namespace ocp -o json | jq '.items[] | …
```

Updates to ci-secret-generator

---

pkg/bitwarden/cli.go
pkg/bitwarden/cli_test.go

Since the bw delete command was being called after the item was removed from the list, we were actually deleting the element which occurs after intended element - since the pointer points to the item at that index.
This change would move the delete from the list after the call to bw delete

Delete attachment from local bw mirror after running bw cmd

---

cmd/ci-operator/main.go
pkg/api/graph.go
pkg/api/graph_test.go
pkg/steps/bundle_source.go
pkg/steps/clusterinstall/clusterinstall.go
pkg/steps/git_source.go
pkg/steps/images_ready.go
pkg/steps/index_generator.go
pkg/steps/input_env.go
pkg/steps/input_image_tag.go
pkg/steps/lease.go
pkg/steps/lease_test.go
pkg/steps/multi_stage.go
pkg/steps/output_image_tag.go
pkg/steps/pipeline_image_cache.go
pkg/steps/pod.go
pkg/steps/project_image.go
pkg/steps/release/create_release.go
pkg/steps/release/import_release.go
pkg/steps/release/promote.go
pkg/steps/release/release_images.go
pkg/steps/rpm_injection.go
pkg/steps/rpm_server.go
pkg/steps/run_test.go
pkg/steps/source.go
pkg/steps/template.go
pkg/steps/write_params.go

```
2020/09/10 14:07:47 Running [input:root], [release-inputs], src, [images], bin, [release:latest], e2e
2020/09/10 14:07:47 Ran for 1s
error: some steps failed:
* step "e2e" failed validation: step needs a lease but no lease client provided
* a lease client was required but none was provided, add the --lease-... arguments
```

pkg/steps/lease: fail faster if client not present

---

cmd/ci-operator/main.go
pkg/api/config.go
pkg/api/config_test.go
pkg/api/types.go
pkg/steps/bundle_source.go
pkg/steps/source.go

`operator.substitute.with` must be resolvable to a image involved in the
ci-operation execution, otherwise we start using returning `nil`s when
computing step dependencies, leading to `nil` dereference.
Addressed in two places: on validation, and on usage (defensively -- log a
warning. this should not happen with the validation but this way it's more
resilient to changes).
Also took the opportunity and fixed few code style issues.
Fixes: DPTP-1484

ci-operator: validate operator.substitute.with better

---

pkg/api/config.go
pkg/api/config_test.go

Rework test From validation to allow imagestreamtag references (i.e. `stable-initial:installer`) instead of plain tag names.
Ref: https://issues.redhat.com/browse/DPTP-1518

validateLiteralTestStepCommon: allow using imagestreamtag references

---

pkg/steps/template.go

We've frequently seen image pulls take 10m (!), e.g.:
https://prow.ci.openshift.org/view/gs/origin-ci-test/pr-logs/pull/openshift_cluster-kube-controller-manager-operator/449/pull-ci-openshift-cluster-kube-controller-manager-operator-master-e2e-aws-operator/1306162734701744128
```
2020-09-16T09:29:58Z pulling image "docker-registry.default.svc:5000/ci-op-dftcl0f8/stable@sha256:e4f935c038e45a58ca4d2e46233930dc1f0354027249690297d766f24a86f7a2"
2020-09-16T09:39:13Z Successfully pulled image "docker-registry.default.svc:5000/ci-op-dftcl0f8/stable@sha256:e4f935c038e45a58ca4d2e46233930dc1f0354027249690297d766f24a86f7a2"
```
/shrug

ci-operator: wait 15m for pending pods

---

pkg/api/config.go
pkg/api/config_test.go

Reverts openshift/ci-tools#1230
Just removing the validation does not seem to be sufficient, IST references need to be processed differently later. Right now ci-operator spawns invalid pods, and then image-registry operator chokes on them:
```
The following objects have invalid references:
Pod[ci-op-2cq11w99/e2e-azure-ipi-install-install]: invalid container image reference "stable:stable-initial:installer": invalid reference format
Pod[ci-op-5hr1jn9h/e2e-gcp-image-ecosystem-ipi-install-install]: invalid container image reference "stable:stable-initial:installer": invalid reference format
Pod[ci-op-7gyk1rg4/e2e-ovn-hybrid-step-registry-ipi-install-install]: invalid container image reference "stable:stable-initial:installer": invalid reference format …
```

Revert "validateLiteralTestStepCommon: allow using imagestreamtag references"

---

pkg/defaults/defaults.go
pkg/steps/clusterinstall/clusterinstall.go
pkg/steps/multi_stage.go
pkg/steps/multi_stage_test.go
pkg/steps/pod.go
pkg/steps/pod_test.go
pkg/steps/release/create_release.go
pkg/steps/release/import_release.go
pkg/steps/source.go
pkg/steps/template.go

ci-operator: expose message only when there is one
---
ci-operator: spew events for pods that fail to start
In almost all cases, the PodStatus does not contain enough information
and until we have a better way to show off the output of a job, we
should put the event data into the output.
---

Improve failed pod output

---

pkg/dispatcher/config.go
pkg/dispatcher/config_test.go

/hold
until all vsphere jobs are actualy migrated

Config sanitizer: Force vsphere jobs onto the vsphere cluster

---

pkg/dispatcher/config.go
pkg/dispatcher/config_test.go

Those are admin jobs.
According to https://issues.redhat.com/browse/DPTP-1505, they should be on app.ci
And we have our config to do so.
https://github.com/openshift/release/blob/06c181cf669b68cf9bf04d0c26ddc1c4dded51a7/core-services/sanitize-prow-jobs/_config.yaml#L1614-L1615
This PR is a breaking change. The fix is https://github.com/openshift/release/pull/12104

Disable forcing applyconfig jobs on vphere

---

cmd/prow-job-dispatcher/main_test.go
pkg/dispatcher/config.go
pkg/dispatcher/config_test.go
pkg/dispatcher/testdata/TestLoadConfig/good_config.yaml
pkg/dispatcher/testdata/TestLoadConfig/good_config_with_build_farm.yaml
pkg/dispatcher/testdata/TestLoadConfig/good_config_with_build_farm_with_jobs.yaml
pkg/dispatcher/testdata/TestLoadConfig/invalid_regex.yaml

According to https://github.com/kubernetes/test-infra/blob/6d83fa84beb472a6b3e916a89f371e251b321e84/prow/config/jobs.go#L93-L94
The value of `agent` is "kubernetes".

empty agent jobs are running on k8s

---

pkg/api/config.go
pkg/api/config_test.go
pkg/steps/multi_stage.go
pkg/steps/multi_stage_test.go
pkg/steps/testdata/zz_fixture_TestGeneratePods.yaml
test/e2e/multi-stage/config.yaml

Resubmit of https://github.com/openshift/ci-tools/pull/1230 (reverted by https://github.com/openshift/ci-tools/pull/1238).
If multistage "from" contains imagestreamtag it would be used in the pod. This is useful for upgrade jobs, which require installer to be used from "stable-initial:installer" imagstreamtag.

multistage: handle imagestream references in From

---

pkg/api/types.go
pkg/defaults/defaults.go
pkg/lease/client_test.go
pkg/lease/fake.go
pkg/steps/lease.go
pkg/steps/lease_test.go
pkg/steps/multi_stage.go

An internal change that should not have any externally observable behavior
change (other than a few log messages).  Required to support multiple
leases per test in the future.
/hold
Reviewable, but I'll work on adding tests for the existing code tomorrow.

pkg/steps/lease: add support for multiple leases

---

pkg/dispatcher/config.go

not include the namespace while detecting an applyconfig job

---

pkg/api/types.go
pkg/defaults/defaults.go
pkg/lease/client_test.go
pkg/lease/fake.go
pkg/steps/lease.go
pkg/steps/lease_test.go
pkg/steps/multi_stage.go

This reverts commit 1140ae9ddf9c9a9308e0fd3ec8cf59d7996bbf64, reversing
changes made to c8753200eb307c44d3da4bf51f0109f238cb0181.
As it seems to break template jobs, e.G. https://deck-ci.apps.ci.l2s4.p1.openshiftapps.com/view/gs/origin-ci-test/logs/release-openshift-origin-installer-e2e-remote-libvirt-s390x-4.6/1308798346420293632

Revert "Merge pull request #1126 from bbguimaraes/lease_conf"

---

pkg/webreg/webreg.go

Be more informational about how the indices are built.
~~WIP: I'd like to add a link to the docs that describe `opm index add` modes but I need to find one.~~ turns out there is no good doc page (asked on #forum-operator-fw) so I tried to elaborate.

docs: more details about built oo indices

---

Makefile
pkg/api/config.go
pkg/api/config_test.go
pkg/api/types.go
pkg/defaults/defaults.go
pkg/defaults/defaults_test.go
pkg/prowgen/prowgen.go
pkg/prowgen/prowgen_test.go
pkg/prowgen/testdata/zz_fixture_TestGenerateJobBase_expose_option_set_but_not_private_with_clone__true.yaml
pkg/prowgen/testdata/zz_fixture_TestGeneratePeriodicForTest_periodic_for_specific_release_and_clone__true.yaml
pkg/prowgen/testdata/zz_fixture_TestGeneratePostSubmitForTest_Lowercase_org_repo_and_branch.yaml
pkg/prowgen/testdata/zz_fixture_TestGeneratePostSubmitForTest_Lowercase_org_repo_and_branch_with_release.yaml
pkg/prowgen/testdata/zz_fixture_TestGeneratePostSubmitForTest_Uppercase_org__repo_and_branch.yaml
pkg/prowgen/testdata/zz_fixture_TestGeneratePostSubmitForTest_Uppercase_org__repo_and_branch_with_clone__true.yaml
pkg/prowgen/testdata/zz_fixture_TestGeneratePresubmitForTest_presubmit_with_job_release_specified_and_clone.yaml
pkg/webreg/webreg.go

This PR allows to specify the `build_root_image` inside the repository by setting `build_root.from_repository: true`. If this is set, we will:
* Enable cloning on all prowjobs that are based off of that ci-operator config (We might optimize this later on to only do so when we actually have that image in our graph, but that requires some bigger refacotoring of the ci-operator and prowgen)
* Read the imagestream from a file named `.build_root_image` in the repo
/assign @stevekuznetsov 
/cc @marun 

Allow specifying build_root_image in the repository

---

cmd/ci-operator/main.go
pkg/defaults/defaults.go

This reverts commit ccfb80db4bd628e0d73a6020c36007c10f994e85.
Things did not work out as I expected.
We probably need to use the following to push the image (built on build01) to the central CI registry (on api.ci for now, and app.ci for the future).
```
oc explain build.spec.output.pushSecret
oc explain build.spec.output.to
```

Revert "Use kubeconfig to promote images"

---

cmd/ci-operator/main.go
cmd/ci-operator/main_test.go
pkg/api/graph.go
pkg/steps/project_image.go

For https://issues.redhat.com/browse/DPTP-1493
This PR makes errors related to dependency issues in the steps a bit easier to understand by:
* De-Duplicating them
* Avoiding to print steps whose depend on steps that have unfulfilled dependencies by first creating a list of all available dependencies
* Allowing StepLinks to contain an explanation as to why this is needed, print that instead of the raw StepLink and fill it in for the `Inputs` of the `ProjectImage` step
A sample output for a config similiar to whats in the card looks like this:
```
step <*steps.projectDirectoryImageBuildStep> is missing dependencies: "cli" is neither an imported nor a built image
```
This doesn't fully cover the AC, because to do that, we would need to also allow Steps to contain the info where exactly in …

Steps: Make errors a bit more helpful

---

pkg/steps/input_image_tag.go

AFAICT, this was an omission.  I'm wary of adding features to templates,
but this allows for more reliable and much simpler and faster E2E tests
(e.g. https://github.com/openshift/ci-tools/pull/1258), which will still
be required for as long as we support templates.

ci-operator: expose `base_images` to templates

---

CONFIGURATION.md

It would be nice if these links could get closer to the relevant sections, but the upstream doc page is abominably light on anchors.
Fixes: #814

Fix upstream doc links in CONFIGURATION.md

---

pkg/steps/template.go

The TODO are from 0dcdf1090b (#1058).  Possibly they were just `sed`ed in, because the function has taken a Context argument since c242af1190 (#510).
CC @alvaroaleman

pkg/steps/template: Replace context.TODO in waitForPodCompletionOrTimeout

---

pkg/webreg/webreg.go

- OCP links should lead to *.ocp.* stuff
- fix typo: pp->ppc

webreg: fix release-controller links

---

pkg/steps/multi_stage.go
pkg/steps/template.go

This seems generically useful, and not something that needs to be restricted to multi-step, where it has been since 8cf5f87d55 (#100).

pkg/steps/template: Push "Executing pod..." logging into createOrRestartPod

---

pkg/steps/multi_stage.go
pkg/steps/pod.go
pkg/steps/release/import_release.go
pkg/steps/template.go

To allow future callers to switch on particular pod states when explaining error messages.  For example, we may want to say something about the configured `activeDeadlineSeconds` if we see a pod that failed with `DeadlineExceeded` (#1257).

pkg/steps: Return Pod from waitForPodCompletion

---

pkg/webreg/webreg.go

This reverts commit 01bb082f368c75212930580ba35d72bf38d43b33.
We need to stop the auto-recovery from OSD side.
https://issues.redhat.com/browse/OHSS-1722

Revert "Update the link to app.ci's console"

---

pkg/promotion/promotion.go
pkg/promotion/promotion_test.go

Fixes:
```console
$ config-brancher --config-dir ./ci-operator/config --current-release=4.7 --future-release=4.8 --confirm
...
ERRO[0000] could not determine future branch that would promote to current imagestream  branch=main error="invalid branch \"main\" promoting to current release" org=openshift repo=osd-metrics-exporter source-file=openshift-osd-metrics-exporter-main.yaml
...
```

promotion: support `main` branch

---

pkg/api/types.go
pkg/steps/multi_stage.go
pkg/steps/template.go
pkg/webreg/webreg.go
test/e2e/multi-stage.sh
test/e2e/multi-stage/config.yaml
test/e2e/multi-stage/registry/timeout/timeout-commands.sh
test/e2e/multi-stage/registry/timeout/timeout-ref.yaml

Sometimes test steps like updates [take a long time][1].  When that happens, something wrapping the workflow may be timed out instead, and the whole thing gets torn down without any post-test gather/teardown steps running.  With this commit, we expose two timeout-related [properties from `PodSpec`][2] to step maintainers to use to control this behavior.  Step maintainers can now set per-step timeouts that are comfortably less than the wrapper timeout, ensuring that slow/hung steps get killed, and the remaining steps have some time to gather details that will explain the delay and perform other teardown.
[1]: https://github.com/openshift/cluster-network-operator/pull/785#issuecomment-698017421
[2]: https://kubernetes.io/docs/reference/generated/kubernetes-api/v1.18/#podspec-v1-core

pkg/steps: Configurable activeDeadlineSeconds and terminationGracePeriodSeconds

---

pkg/results/report.go

If we can't report due to missing info it should be a no-op reporter and the user should see no error.

Reporter: Remove error if -report-password-file is not set

---

pkg/api/config.go
pkg/api/types.go
pkg/prowgen/prowgen.go

This fixes the following error:
{"component":"boskos","error":"[ResourceObject.boskos.k8s.io "openstack-OSUOSL-02" is invalid: metadata.name: Invalid value: "openstack-OSUOSL-02": a DNS-1123 subdomain must consist of lower case alphanumeric characters,...

Change uppercase OSUOSL to lowercas

---

pkg/steps/template.go

Calling these functions with a cancelled context causes them to fail and
return an error (debugging output included):
```
^CINFO[0050] Received signal.                              signal=interrupt
2020/10/08 12:11:33 error: Process interrupted with signal interrupt, cancelling execution...
debug: event: watch.Event{Type:"ERROR", Object:(*v1.Status)(0xc0008d8000)}, ok: true
2020/10/08 12:11:33 error: Unrecognized event in watch: ERROR &v1.Status{TypeMeta:v1.TypeMeta{Kind:"", APIVersion:""}, ListMeta:v1.ListMeta{SelfLink:"", ResourceVersion:"", Continue:"", RemainingItemCount:(*int64)(nil)}, Status:"Failure", Message:"an error on the server (\"unable to decode an event from the watch stream: context canceled\") has prevented the request from succeeding", Reason:"InternalError", …
```

ci-operator: remove uses of top-level context

---

cmd/ci-secret-bootstrap/main.go
cmd/ci-secret-bootstrap/main_test.go
cmd/ci-secret-generator/main.go
pkg/api/secretbootstrap/secretboostrap.go

https://issues.redhat.com/browse/DPTP-1496
Keeping backward compatibility, this PR adds a specific case of configuration to generate a single docker config JSON secret from multiple bitwarden values.
example config:
```yaml
secret_configs:
- from:
.dockerconfigjson:
dockerconfigJSON:
- bw_item: pull-secret-0
registry_url_bw_field: registryURL
auth_bw_field: auth
email_bw_field: email
- bw_item: pull-secret-1
registry_url_bw_field: registryURL
auth_bw_field: auth
to:
- cluster: app.ci
namespace: test
name: pull-secret-test
type: kubernetes.io/dockerconfigjson
```
example output with some comments for better understanding.
```
{
"auths": {
"cloud.openshift.com": { // registry_url field
"auth": "123456789", // auth field
"email": "test@test.com" // email field
}, …
```

[ci-secret-bootstrap] introduce the dockerconfigJSON configuration

---

cmd/ci-secret-bootstrap/main.go
cmd/ci-secret-bootstrap/main_test.go
pkg/api/secretbootstrap/secretboostrap.go

Unfortunately, a bitwarden field can't hold more than 1000 characters. Instead, we have to grab the auth token from an attachment.
the new config should look like:
```yaml
secret_configs:
- from:
.dockerconfigjson:
dockerconfigJSON:
- bw_item: pull-secret-1
registry_url_bw_field: registry_url
auth_bw_attachment: auth
email_bw_field: email
- bw_item: pull-secret-2
registry_url_bw_field: registry_url
auth_bw_attachment: auth
email_bw_field: email
to:
- cluster: app.ci
namespace: test
name: pull-secret-test
type: kubernetes.io/dockerconfigjson
```

[ci-secret-bootstrap] make dockerconfigJSON config to get the auth field from attachment instead

---

pkg/api/config.go

The condition was added when workflows were first introduced in
66b8344bdfa9510f0e6971be327d902735429db1.  The unresolved configuration
is used to generate ProwJob definitions, so the cluster profile in the
configuration is effectively the one that prevails and must always be
validated.
```
$ sed -i 's/\(cluster_profile: \)azure4$/\1azure/' ci-operator/config/openshift/kubernetes/openshift-kubernetes-master.yaml
$ ci-operator-prowgen_master --from-dir ci-operator/config --to-dir ci-operator/jobs |& grep -v level=warning
$ ci-operator-prowgen --from-dir ci-operator/config --to-dir ci-operator/jobs |& grep -v level=warning
time="2020-10-14T11:57:08Z" level=error msg="Failed to load CI Operator configuration" error="invalid ci-operator config: invalid configuration: tests[9]: invalid cluster …
```

pkg/api: validate cluster profile unconditionally

---

pkg/api/types.go
pkg/steps/multi_stage.go
test/e2e/multi-stage.sh
test/e2e/multi-stage/dependencies.yaml

This implements [DPTP-1242](https://issues.redhat.com/browse/DPTP-1242)

ci-operator: allow users to inject the oc cli into test steps

---

pkg/steps/lease.go
pkg/steps/lease_test.go

To allow for the suffixed lease names from openshift/release#12589 without exposing the suffixes to consuming steps.

pkg/steps/lease: Split leased resource on '--'

---

go.mod
pkg/github/github.go

Like it for example happened here: https://prow.ci.openshift.org/view/gs/origin-ci-test/logs/periodic-prow-auto-registry-replacer/1316499184521580544#1:build-log.txt%3A86

Github FileGetter: Retry to not choke on transient errors

---

pkg/steps/rpm_server.go

The use of the `>>` append redirect for the python serving script
meant that subsequent executions would not update the contents.
While this is unlikely to impact the pod, someone debugging the
script would never see their changes to the script reflected
because the new version would be appended to the python script
after a blocking function (so the updated code would never run).
Correct the typo so no other copy and paste mistakes occur.
Found while adapting https://github.com/openshift/release-controller/pull/222

rpm_server: Should use overwrite and not append for script creation

---

cmd/slack-bot/main.go
hack/local-slack-bot.sh
pkg/slack/events/handler.go
pkg/slack/events/mention/mention.go
pkg/slack/events/mention/mention_test.go
pkg/slack/events/mention/testdata/zz_fixture_TestRespnseFor_many_keywords_get_many_button_block.yaml
pkg/slack/events/mention/testdata/zz_fixture_TestRespnseFor_one_keyword_gets_a_button_block.yaml
pkg/slack/events/mention/testdata/zz_fixture_TestRespnseFor_unrelated_text_gets_a_sad_response.yaml
pkg/slack/events/router/router.go
pkg/slack/interactions/router/router.go
pkg/slack/interactions/router/router_test.go
pkg/slack/interactions/router/testdata/zz_fixture_TestIsMessageButtonPress_button_press_in_a_message_callback.yaml
pkg/slack/interactions/router/testdata/zz_fixture_TestIsMessageButtonPress_button_press_in_a_modal_callback.yaml
pkg/slack/interactions/router/testdata/zz_fixture_TestIsMessageButtonPress_not_a_button_press_callback.yaml
pkg/slack/modals/bug/view_test.go
pkg/slack/modals/modaltesting/issueparameters.go
pkg/slack/modals/modaltesting/submission.go

Nobody wants to go to the "lightning bolt menu" and find the interaction
shortcut buttons for the bot, so now we can just mention the bot in a
conversation and it will respond with a button that starts a flow.
/assign @petr-muller @alvaroaleman 
As always feel free to test it out on the robot-testing workspace.

slack-bot: expose interaction flows in messages

---

cmd/pj-rehearse/main.go

Before this commit, pj-rehearse would just [give up][1]:
```console
$ curl -s https://storage.googleapis.com/origin-ci-test/pr-logs/pull/openshift_release/12959/pull-ci-openshift-release-master-pj-rehearse/1318651994902106112/build-log.txt | tail -n2
time="2020-10-20T20:36:51Z" level=info msg="Created a rehearsal job to be submitted" org=openshift rehearsal-job=rehearse-12959-pull-ci-openshift-kubernetes-master-e2e-cmd repo=release target-job=pull-ci-openshift-kubernetes-master-e2e-cmd target-repo=openshift/kubernetes
time="2020-10-20T20:36:51Z" level=info msg="Would rehearse too many jobs, will not proceed" org=openshift rehearsal-jobs=68 rehearsal-threshold=45 repo=release
```
But skipping rehearsals for a change that touches tons of jobs, like we have done since ef4f47ebfe …

cmd/pj-rehearse: Truncate extra rehearsals

---

cmd/pj-rehearse/main.go

I don't have a personal preference for what this should be, but @stevekuznetsov felt that coverage with 15 wasn't great and wanted 35 instead.

cmd/pj-rehearse: Default rehearsal-limit to 35

---

cmd/private-prow-configs-mirror/main.go

We identify repo by name which means if a different org has the same
repo as its in the openshift org, we will flap based on map ordering.
This tool was never intended to handle non-openshift orgs anyways.

Private prow configs mirror: Ignore non-openshift orgs

---

cmd/private-prow-configs-mirror/main.go
cmd/private-prow-configs-mirror/main_test.go

The fact that we don't do this today currently results in invalid config, because there are duplicate plugins in now-unmanaged openshift/priv repos that are also set at the org level, see for example here: https://prow.ci.openshift.org/view/gs/origin-ci-test/pr-logs/pull/openshift_release/13103/pull-ci-openshift-release-master-config/1319700661008338944
Result of this PR is here: https://github.com/openshift/release/pull/13107

Private config mirror: Remove stale plugin configs

---

cmd/ci-secret-bootstrap/main.go
cmd/ci-secret-bootstrap/main_test.go

Currently we are defaulting the secret type to be `kubernetes.io/dockerconfigjson` when there is a `dockerconfigJSON` configuration included. This doesn't make any sense because there are secrets that are using this as simple key in their secrets with `opaque` secret type. 
Therefore, we don't want to default it or validate it.
Fixes: https://deck-internal-ci.apps.ci.l2s4.p1.openshiftapps.com/log?job=periodic-ci-secret-bootstrap&id=1320692848172994560

[ci-secret-bootstrap] stop forcing the secret type on dockerconfigJSON configuration

---

pkg/api/config.go
pkg/api/types.go

The only reference in o/release is this:
```
$ rg openshift_installer_random
core-services/iaas-e2e-config/README.md
3:This ConfigMap is used by the IaaS-agnostic tests (`openshift_installer_random`
```

Remove unused openshift_installer_random template

---

pkg/api/types.go
pkg/prowgen/prowgen.go
pkg/prowgen/prowgen_test.go
pkg/prowgen/testdata/zz_fixture_TestGeneratePodSpecTemplate_testcase_2.yaml
pkg/prowgen/testdata/zz_fixture_TestGeneratePodSpecTemplate_testcase_3.yaml

```
[2020-10-23-15:00]:[build01@ci-op-fwfg97yy][master]~/.../openshift/release
$ rg 'enable_nested_virt|nested_virt_image'
```
Yields no result

OpenshiftInstallerCustomTest template: Remove unused nested virt properties

---

cmd/ci-secret-bootstrap/main.go
cmd/ci-secret-bootstrap/main_test.go
pkg/bitwarden/bitwarden.go
pkg/bitwarden/cli.go
pkg/bitwarden/fake.go

This commit includes:
- A way how to compare the bitwarden vs config items
- flag `--validate-bitwarden-items-usage` to enable the validation
- flag `--bw-allow-unused` to allow bitwarden items to existing without being used
- unittests
[DPTP-1547](https://issues.redhat.com/browse/DPTP-1547)

[ci-secret-bootstrap] add the ability to validate the usage of the bitwarden items

---

cmd/slack-bot/main.go
go.mod
hack/local-slack-bot.sh
pkg/api/domain.go
pkg/rehearse/jobs.go
pkg/rehearse/jobs_test.go
pkg/slack/events/joblink/link.go
pkg/slack/events/joblink/link_test.go
pkg/slack/events/router/router.go
vendor/modules.txt

When a user pastes a link to a job or artifact, we often want to see the
full Spyglass link and the ci-operator configuration that gave rise to
the job in the first place. Instead of asking them for this information
we can just calculate it and post a reply.

slack-bot: add context to job links

---

pkg/jobconfig/files.go

Follow up https://coreos.slack.com/archives/GB7NB0CUC/p1603894425209800?thread_ts=1603817965.189700&cid=GB7NB0CUC
Have tested with https://github.com/openshift/release/pull/13204
/hold
Need to see if this one does NOT introduce any breaking changes.

prowgen: keep image-mirror-push-secret if existing

---

pkg/steps/template.go

I'd fixed this for multi-step while rerolling 9d209c7b24 (#1257), but missed fixing the template log.  Catch that up now.

pkg/steps/template: De-ref pointer in with activeDeadlineSeconds= message

---

Makefile
cmd/docgen/main.go
go.mod
go.sum
hack/generate-ci-op-reference.sh
hack/run-step-registry.sh
pkg/webreg/webreg.go
pkg/webreg/zz_generated.ci_operator_reference.go
vendor/k8s.io/test-infra/pkg/genyaml/BUILD.bazel
vendor/k8s.io/test-infra/pkg/genyaml/README.md
vendor/k8s.io/test-infra/pkg/genyaml/genyaml.go
vendor/k8s.io/test-infra/pkg/genyaml/populate_struct.go
vendor/k8s.io/test-infra/prow/bugzilla/client.go
vendor/k8s.io/test-infra/prow/bugzilla/types.go
vendor/k8s.io/test-infra/prow/config/BUILD.bazel
vendor/k8s.io/test-infra/prow/config/README.md
vendor/k8s.io/test-infra/prow/config/prow-config-documented.yaml
vendor/k8s.io/test-infra/prow/flagutil/bugzilla.go
vendor/k8s.io/test-infra/prow/plugins/approve/approve.go
vendor/k8s.io/test-infra/prow/plugins/config.go
vendor/k8s.io/test-infra/prow/plugins/plugins.go
vendor/modules.txt

The content for the handler is pre-generated because the generation needs the source code which we do not have anymore in the final image.

Step registry ui: Add handler for ci-operator config reference

---

pkg/jobconfig/files.go

This reverts commit 670cc23b6cc50c772caeff828cbcf753f61afc1c.
/hold
Will merge this when stable.

Revert "prowgen: keep image-mirror-push-secret if existing"

---

pkg/api/types.go
pkg/steps/multi_stage.go
pkg/steps/multi_stage_test.go
pkg/steps/testdata/zz_fixture_TestGeneratePodReadonly.yaml

Add a configuration option in multi-stage steps to not add the
`secret-wrapper` to the test process.  Results in noticeably faster
tests when a read-only version of the directory is sufficient.

ci-operator: add option for read-only shared dir

---

pkg/testhelper/testhelper.go

- mark `CompareWithFixture` as a test helper so failure messages display
the true origin
- include the fixture file name in the diff to make it a real patch

pkg/testhelper: mark as helper, include filename

---

cmd/autopublicizeconfig/main.go

ignore non-openshift organizations from the publucize config sync

---

cmd/ci-operator/main.go
pkg/steps/multi_stage.go

These have been deprecated for months and are not used anywhere.

ci-operator: remove deprecated flags

---

pkg/github/github.go

Makes debugging of errors like this one possible: https://prow.ci.openshift.org/view/gs/origin-ci-test/logs/periodic-prow-auto-registry-replacer/1323369491274403840#1:build-log.txt%3A81

GitHub: Include URL on errors

---

pkg/steps/artifacts.go
pkg/steps/artifacts_test.go
pkg/steps/multi_stage.go
pkg/steps/pod.go
pkg/steps/template.go

In all cases that the worker had it's work cancelled, this was done as a
result of a context being done. In every case, it is improper to not
cancel the worker if the test context is cancelled, so there is no use
in forcing callers that construct an artifact worker remember that they
need to cancel it appropriately. We can instead just require the context
to be passed to the constructor and always do the right thing.

ci-operator: let artifacts worker cancel itself

---

test/e2e/multi-stage.sh
test/e2e/multi-stage/registry/timeout/timeout-commands.sh
test/e2e/multi-stage/registry/timeout/timeout-ref.yaml

While we try to determine the particular deadlock/hang that occurs when
a Pod starts after it's ActiveDeadlineSeconds are exhausted, make the
test timeout in a longer period of time to make it less likely that we
hit this issue and cause 4h timeouts in e2e presubmits.
Addresses [DPTP-1698](https://issues.redhat.com/browse/DPTP-1698)

e2e: make timeout 120s instead of 10s

---

cmd/ci-operator-prowgen/main.go
cmd/template-deprecator/README.md
cmd/template-deprecator/main.go
pkg/deprecatetemplates/allowlist.go
pkg/deprecatetemplates/allowlist_test.go
pkg/deprecatetemplates/enforcer.go
pkg/deprecatetemplates/enforcer_test.go
pkg/prowgen/prowgen.go
pkg/prowgen/prowgen_test.go
pkg/slack/events/joblink/link.go
test/integration/template-deprecator.sh
test/integration/template-deprecator/expected/allowlist.yaml
test/integration/template-deprecator/expected/blockered-allowlist.yaml
test/integration/template-deprecator/input/blockered-allowlist.yaml
test/integration/template-deprecator/input/config.yaml
test/integration/template-deprecator/input/jobs/periodics.yaml
test/integration/template-deprecator/input/partial-allowlist.yaml
test/integration/template-deprecator/input/plugins.yaml

~This code makes `sanitize-prow-jobs` _optionally_ read config-updater config, get a list of all existing templates, and compile an allowlist of all jobs that currently use these templates. This allowlist is merged with a previously saved one~.
I made the second iteration a separate binary, because the functionality did not really fit into `sanitize-prow-jobs` in the end (it would become a totally modal tool, wiith separate options etc). Also, we may want to make interaction with the allowllist easier for users via the tool, and an explicit tool is better for that.
This is how the allowlist looks like:
```yaml
templates:
prow-job-cluster-launch-e2e:
blockers:
JIRA-1234:
description: "Things do not thing the way they should thing"
jobs:
periodic-ci-openshift-origin-release-3.11-e2e-gcp: …
```

template-deprecator: add new tool

---

cmd/determinize-prow-config/main.go
cmd/determinize-prow-config/main_test.go

De-Duplicate our tide queries in order to reduce the amount of config we have.
Produces this, which shaves off ~200 lines of the config file: https://github.com/openshift/release/pull/13346

De-Duplicate tide queries

---

pkg/controller/test-images-distributor/test_images_distributor.go
pkg/controller/test-images-distributor/test_images_distributor_test.go

What is confusing though:  Why does the registry not resolve `RawSteps` but only `Tests`? https://github.com/openshift/ci-tools/blob/7b99e122c7ec94a8f7b0d9f5b6b33da4570a4574/pkg/registry/resolver.go#L327

Test Images Distributor: Use ResolveConfig instead of re-implementing it

---

pkg/api/config.go
pkg/api/config_test.go

Fixes [DPTP-1727](https://issues.redhat.com/browse/DPTP-1727) (happened in https://github.com/openshift/release/pull/13394)

ci-operator: detect duplicate images[*].to stanzas

---

pkg/steps/bundle_source_test.go

This test prevents me from running `make test` successfully on a non-Linux PC.

Skip a linux-only test

---

pkg/release/official/client.go
pkg/release/official/client_test.go

Reproduced by:
```yaml
releases:
latest:
release:
channel: stable
version: "4.7"
```
Should this be a bug in cincinatti? This should IMO return a 404 or maybe a 204.

ci-operator: handle empty response by cincinnati

---

images/template-deprecator/Dockerfile

We need `diff` to run the presubmit that compares allowlists (https://prow.ci.openshift.org/view/gs/origin-ci-test/pr-logs/pull/openshift_release/13427/rehearse-13427-pull-ci-openshift-release-master-deprecate-templates/1324654573951913984#1:build-log.txt%3A1)

template-deprecator: install diff in image

---

cmd/autoconfigbrancher/main.go
images/autoconfigbrancher/Dockerfile

Changing Prow config in `private-prow-configs-mirror` may cause
reshuffling of Tide queries. 
The binaries are provided as inputs to the build already in https://github.com/openshift/release/pull/13422

autoconfigbrancher: determinize prow config

---

cmd/ci-operator/main.go

This reverts commit 19fc7841b534d5e723ff7b654275ed6046055fe8.

Revert "ci-op: Add flag image-creator-kubeconfig"

---

cmd/dptp-controller-manager/main.go

We have not used this flag yet.
https://github.com/openshift/release/blob/fae7f47a56abf5c3ac4ea9e9230eb2ec123b2597/clusters/app.ci/assets/dptp-controller-manager.yaml#L100-L111

Fix a typo in DPTP-CM

---

cmd/template-deprecator/main.go
pkg/deprecatetemplates/allowlist.go
pkg/deprecatetemplates/allowlist_test.go
pkg/deprecatetemplates/enforcer.go
pkg/deprecatetemplates/enforcer_test.go
test/integration/template-deprecator.sh
test/integration/template-deprecator/input/to-be-pruned-allowlist.yaml

To be called in autoconfigbrancher to regularly clean up the allowlist
(do not bother people who are migrating jobs with allowlist changes).

template-deprecator: --prune

---

pkg/api/parameters.go
pkg/defaults/defaults.go

Part of https://github.com/openshift/ci-tools/pull/1362 (which in turn is part
of https://github.com/openshift/ci-tools/pull/1312).  Opened separately to limit
the number of changes in a single PR.
See https://github.com/openshift/ci-tools/pull/1362#issuecomment-723284065 for
more details.  Due to refactorings in `pkg/defaults`, we eventually started
processing `Provides` more than once for some types of build steps.  This does
not appear to have a negative effect, but is certainly wrong and misleading.

pkg/defaults: only process `Provides` once

---

cmd/private-org-peribolos-sync/main.go
cmd/publicize/main.go
pkg/registry/resolver.go
pkg/rehearse/jobs.go
pkg/steps/artifacts.go

Importing it as kerrors is extremely confusing as kerrors is 99% of the
time the "k8s.io/apimachinery/pkg/api/errors" package.

Import utilerrors as utilerrors and not kerrors

---

pkg/api/config.go
pkg/api/types.go
pkg/prowgen/prowgen.go
pkg/webreg/zz_generated.ci_operator_reference.go

`openshift_ansible_upgrade`:
This template is not used in any generated job (and so in no ci-operator
config), so all code that handles the tempalte can be removed:
```console
$ git grep openshift_ansible_upgrade
$ git grep prow-job-cluster-launch-e2e-upgrade ci-operator/jobs/
ci-operator/jobs/openshift/openshift-ansible/openshift-openshift-ansible-release-3.11-presubmits.yaml:          name: prow-job-cluster-launch-e2e-upgrade
```
`openshift_installer_console`
It is only used by online ci-op configs (which should be changed to
match what the jobs actually use).
/hold 
Needs https://github.com/openshift/release/pull/13529

Cleanup code handling obsolete templates

---

cmd/pj-rehearse/main.go

We get a 403 if the namespace doesn't exist, which also means we need to
create an import.

PJ rehearse: Treat 403 like 404 when determining if to import

---

pkg/defaults/defaults.go
pkg/release/official/client.go
pkg/release/official/client_test.go

This PR changes the `ResolvePullSpec` function for official release to
`ResolvePullSpecAndVersion`. The `release-controller` will be importing
this package to use this function when determining releases for upgrades
and needs a tag name for the release to use as an annotation for the
upgrade job. `version` will be used as the tag name.

pkg/release: return version for official release

---

cmd/autoconfigbrancher/main.go
images/autoconfigbrancher/Dockerfile

The tool can add copies of existing jobs, so it needs to be able to add
them to the the allowlist, too. Also, remove non-existent/irrelevant
jobs from the allowlist.
/hold
Needs https://github.com/openshift/ci-tools/pull/1399 first

autoconfigbrancher: maintain and prune template deprecation allowlist

---

pkg/controller/registrysyncer/registrysyncer.go
pkg/controller/registrysyncer/registrysyncer_test.go

```
dockerImageRepository	<string>
dockerImageRepository is optional, if specified this stream is backed by a
container repository on this server Deprecated: This field is deprecated as
of v3.7 and will be removed in a future release. Specify the source for the
tags to be imported in each tag via the spec.tags.from reference instead.
lookupPolicy	<Object>
lookupPolicy controls how other resources reference images within this
namespace.
tags	<[]Object>
tags map arbitrary string values to specific image locators
```
We copied `lookupPolicy` already and `dockerImageRepository` is deprecated.
Maybe keep the whole `tags` as the sourceImageStream which (has the latest isTag)?

Ensure ImageStreamSpec while sync images

---

pkg/deprecatetemplates/allowlist.go
pkg/deprecatetemplates/allowlist_test.go
pkg/deprecatetemplates/enforcer_test.go

Some maps are nil after unmarshaling, so we need to test before
assigning into them.
Unfortunately I needed to change few internal types to be pointers so the change is larger than would be necessary if I did the initial programming job right :)

template-deprecator: do not choke on nil maps

---

cmd/registry-replacer/main.go

Typo landed with the pruning line in d98daf9ba6 (#995).

cmd/registry-replacer: Fix "dircetive" -> "directive" typo

---

cmd/testgrid-config-generator/main.go
test/integration/testgrid-config-generator.sh
test/integration/testgrid-config-generator/config/_allow-list-broken.yaml

When a job is listed as required in the `release-controller`
configuration, it will be added to a blocking dashboard and it is not
possible to overwrite that behavior with an entry in the allow-list. It
is not therefore useful to allow users to put any such jobs into the
allow-list in the first place.

testgrid-config-generator: disallow ignored allow-list entries

---

.golangci.yml
pkg/backporter/httpcache.go
pkg/github/github.go
pkg/job-runtime-analyzer/job-runtime-analyzer.go
pkg/load/load.go
pkg/release/candidate/client.go
pkg/release/official/client.go
pkg/release/prerelease/client.go

Not closing the response body presumably claused flakyness in the
registry replacer when it tries to read a response body[0], see[1]
for why this can happen.
As this seems to be a common mistake in our codebase, this change
activates a linter for it.
[0] https://issues.redhat.com/browse/DPTP-1692
[1] https://github.com/golang/go/issues/36700

Close http bodies and add linter for it

---

cmd/dptp-controller-manager/main.go
pkg/controller/promotionreconciler/prowjobretrigger/reconciler.go
pkg/controller/promotionreconciler/prowjobretrigger/reconciler_test.go
pkg/controller/promotionreconciler/reconciler.go

The current image promotion reconciler ensures that we have correct
output in the form of ImageStreamTags, but misses the most common reason
that the content may be incorrect: a post-submit job building images
failed. This new controller re-triggers failed post-submit images jobs
when they are for the latest commit in the branch they're meant to
build.
implements [DPTP-1647](https://issues.redhat.com/browse/DPTP-1647)

controllers: add retries for failed images jobs

---

cmd/autotestgridgenerator/main.go

To avoid inscrutable messages such as:
https://prow.ci.openshift.org/view/gs/origin-ci-test/logs/periodic-prow-auto-testgrid-generator/1329213114704465920
```
time="2020-11-19T00:01:52Z" level=fatal msg="failed to run /usr/bin/testgrid-config-generator -testgrid-config ./config/testgrids/openshift -release-config ../../openshift/release/core-services/release-controller/_releases -prow-jobs-dir ../../openshift/release/ci-operator/jobs -allow-list ../../openshift/release/core-services/testgrid-config-generator/_allow-list.yaml" error="exit status 1"
```

autotestgridgenerator: report command error

---

pkg/rehearse/jobs.go
pkg/rehearse/jobs_test.go
test/integration/pj-rehearse/candidate/ci-operator/jobs/super/duper/super-duper-periodics.yaml
test/integration/pj-rehearse/expected.yaml
test/integration/pj-rehearse/master/ci-operator/jobs/super/duper/super-duper-periodics.yaml

Previously, pj-rehearse had code that detected when Prow jobs mounted
ci-operator config CMs (`ci-operator-*-configs`) directly, and handled
resolving and inlining this case. OpenShift CI Prowjobs are no longer
supposed to mount ci-op configs like this (and no longer do so [1]), so
all this code is no longer necessary.
[1]
```console
$ git grep 'ci-operator-.*-configs' ci-operator/jobs/
$
```
This code cleanup is part of [DPTP-1685](https://issues.redhat.com/browse/DPTP-1685)

pj-rehearse: no longer detect references to ci-op config CMs

---

cmd/dptp-controller-manager/main.go
pkg/controller/registrysyncer/registrysyncer.go
pkg/controller/registrysyncer/registrysyncer_test.go

Follow up https://coreos.slack.com/archives/CBN38N3MW/p1605814866021000?thread_ts=1605798608.421500&cid=CBN38N3MW
`origin/release` and `ocp/release` are special.
We do not touch them for now.
We will have to handle those specially when we do registry migration to app.ci.

registrysyncer: support denied imagestreams

---

pkg/steps/template.go

The previous use of the test context for this client call meant that by
definition we would fail to make the call in every case, since a
precondition for the call was that the context was done.
addresses part of https://issues.redhat.com/browse/DPTP-1683

ci-operator: always delete template instance

---

pkg/defaults/defaults.go
pkg/steps/release/promote.go

The step has a src, dst and PodClient but all of them are backed by the same client, making the whole thing confusing and useless.

Promotionstep: Remove unused src/destClient

---

cmd/repo-init/main.go
cmd/repo-init/main_test.go
test/integration/repo-init.sh
test/integration/repo-init/expected/ci-operator/config/org/third/org-third-nonstandard.yaml
test/integration/repo-init/expected/ci-operator/jobs/org/third/org-third-nonstandard-presubmits.yaml
test/integration/repo-init/expected/core-services/prow/02_config/_config.yaml
test/integration/repo-init/expected/core-services/prow/02_config/_plugins.yaml

When a user is not promoting with the OpenShift release we don't put
them into the CI stream with `tag_specification`, so we can ask them
some basic questions about the release they want to run e2es with. We
don't expose every possible option as that's par for the course for this
simple bootstrapping tool.
fixes [DPTP-1722](https://issues.redhat.com/browse/DPTP-1722)

repo-init: allow users basic custom release choice

---

cmd/secret-wrapper/main.go

Right now we will always print a timeout error and its impossible to figure out why this actually didn't work, because we don't print that info at all.

Secretwrapper: Pass on inner error when upload fails

---

cmd/template-deprecator/main.go
pkg/deprecatetemplates/allowlist.go
pkg/deprecatetemplates/allowlist_test.go
pkg/deprecatetemplates/enforcer.go
pkg/deprecatetemplates/enforcer_test.go

Newly added jobs are by default added to the "unknown" blocker, allow to
override this behavior.  This is a UX prerequisite for stricter
validations, I wanted to have an easy way to suggest to the users.
Allow the following things:
```console
$ template-deprecator --block-new-jobs JIRA-1234
$ template-deprecator --block-new-jobs JIRA-1234 --block-new-jobs JIRA-4568
$ template-deprecator --block-new-jobs "JIRA-1234:templates are great can we have moar templates"
```

template-deprecator: allow adding new jobs under a blocker

---

pkg/steps/artifacts.go

When we run into issues starting containers, it may take much longer
than thirty seconds to start the artifacts container. There's no real
reason we need to be so aggressive.
Addresses [DPTP-1787](https://issues.redhat.com/browse/DPTP-1787)

ci-operator: wait longer for artifacts

---

pkg/steps/artifacts.go
pkg/steps/artifacts_test.go
pkg/steps/multi_stage.go
pkg/steps/pod.go
pkg/steps/template.go

Today, we cancel the notifier in order to stop a very specific style of
deadlock:
When we run a test workload that hangs forever upon receipt of SIGINT,
the artifacts will not be collected for that Pod as we wait for all
containers to finish before starting the artifact retrieval. If the
`ci-operator` process cannot wait for all artifacts to be retrieved,
nothing is uploaded to GCS.
If a test process is well-formed and exits early before the grace period
is up but after an interrupt is sent, however, the artifact retrieval
process should complete correctly and no explicit cancellation will be
necessary.
However, the side effect of cancelling the notifier explicitly as soon
as an interrupt is received is that we will never retrieve artifacts for
a Pod even if it is well formed and exits …

ci-operator: don't cancel notifiers on interrupt

---

pkg/controller/registrysyncer/registrysyncer.go
pkg/controller/registrysyncer/registrysyncer_test.go

When a src IS is deleted, it will be deleted on other clusters.
We still need to clean up the current mess after merge: delete each IS on app.ci as src IS (or equivalently, has our own finalizer). Then our queue should be back to normal.

registrySyncer: handle deleted ImageStreams

---

pkg/controller/registrysyncer/registrysyncer.go
pkg/controller/registrysyncer/registrysyncer_test.go

hit:
```
failed to ensure finalizer to ocp-priv/4.6-art-latest-priv-2020-11-18-154142 from cluster app.ci: ImageStream.image.openshift.io "4.6-art-latest-priv-2020-11-18-154142" is invalid: metadata.finalizers[0]: Invalid value: "registry_syncer": name is neither a standard finalizer name nor is it fully qualified
```

registrySyncer: fix finalizer name

---

pkg/steps/run.go

Right now it always contains the start time, as we add to the start time, ignore the result of that operation and then use the start time

Fix finishedAt in step graph

---

pkg/controller/registrysyncer/registrysyncer.go

95 hits in the last 3 hours.
```
failed to ensure finalizer to ocp-ppc64le/4.5.14 from cluster app.ci: Operation cannot be fulfilled on imagestreams.image.openshift.io "4.5.14": the object has been modified; please apply your changes to the latest version and try again
```

registrySyncer: Use patch to add finalizer

---

cmd/ipi-deprovision/ipi-deprovision.sh

The job is currently timing out b/c of problems with cleaning up AWS
clusters ([DPTP-1770](https://issues.redhat.com/browse/DPTP-1770)), which creates a backlog and prevents analysing
which clusters are stuck - and some clusters are stuck for days, so the
long timeout does not help.
I checked the logs for the duration of successful cleanups, and in 99%
cases, we either manage to cleanup under 10m, or we hit the 30m timeout.
From the ~370 successful cleanups, just 7 were over 10 minutes, which I
think is acceptable for now when we need to get that job under the
timeout so that we can continue to analyze which clusters are stuck
long-term.

ipi-deprovisioner: tighen timeout to 10m per cluster

---

cmd/release-job-migrator/main.go
cmd/release-job-migrator/main_test.go
test/integration/release-job-migrator.sh
test/integration/release-job-migrator/expected.txt
test/integration/release-job-migrator/expected/ci-operator/openshift/release/openshift-release-master__ocp-4.7.yaml
test/integration/release-job-migrator/expected/ci-operator/openshift/release/openshift-release-master__okd-4.7.yaml
test/integration/release-job-migrator/expected/ci-operator/openshift/release/openshift-release-master__origin-4.6.yaml
test/integration/release-job-migrator/expected/ci-operator/openshift/release/openshift-release-master__origin-4.7.yaml
test/integration/release-job-migrator/expected/config.yaml
test/integration/release-job-migrator/expected/jobs/openshift-release-master-periodics.yaml
test/integration/release-job-migrator/expected/jobs/openshift-release-release-4.6-periodics.yaml
test/integration/release-job-migrator/expected/jobs/openshift-release-release-4.7-periodics.yaml
test/integration/release-job-migrator/expected/releases/release-ocp-4.7.json
test/integration/release-job-migrator/expected/releases/release-origin-4.7.json
test/integration/release-job-migrator/input/ci-operator/openshift/release/openshift-release-master__ocp-4.7.yaml
test/integration/release-job-migrator/input/config.yaml
test/integration/release-job-migrator/input/jobs/openshift-release-master-periodics.yaml
test/integration/release-job-migrator/input/jobs/openshift-release-release-4.6-periodics.yaml
test/integration/release-job-migrator/input/jobs/openshift-release-release-4.7-periodics.yaml
test/integration/release-job-migrator/input/releases/release-ocp-4.7.json
test/integration/release-job-migrator/input/releases/release-origin-4.7.json

This PR adds a new command to ci-tools that migrates release jobs from
hand-crafted jobs to jobs generated by a ci-operator config file. There
are 2 ways it can do this conversion:
1. If a job has an `UNRESOLVED_CONFIG` set, it can identify required base images and tests from there.
2. A config file can be used to configure jobs that use the same test name.
The config file is simply a yaml map where the key is the base test
name of a job (for example, for job `release-openshift-origin-installer-e2e-gcp-upgrade-4.7`,
the base test name is `gcp-upgrade`) and the value contains 2 things:
1. The corresponding multi-stage test configuration.
2. Any extra base images that the test may require.
This is an example of the config:
```
config:
e2e-metal-ipi:
steps:
cluster_profile: packet
env: …
```

release-job-migrator: initial commit

---

pkg/util/imagestreamtagmapper/imagestreamtagmapper.go
pkg/util/imagestreamtagmapper/imagestreamtagmapper_test.go

Changes on `DeletionTimestamp` generate UpdateEvent.
The DeleteEvent occurs only when the the object is deleted.
When we handles the annotations of isTag, I believe we need to modify this function too.

isTag handler: reconcile when DeletionTimestamp is defined

---

pkg/rehearse/jobs.go
pkg/rehearse/jobs_test.go
test/integration/pj-rehearse/candidate/ci-operator/jobs/super/duper/super-duper-periodics.yaml
test/integration/pj-rehearse/expected.yaml

/hold 
Builds on https://github.com/openshift/ci-tools/pull/1429
This is a thing of beauty! The tests needed to be completely rewritten (there were no real tests for the inlining functionality not working over the CM references -- removed in #1249 ), and the method was refactored - it is probably easier to review as new code than looking at the diff.
There is an annoying gotcha in that our code avoids resolving whole ci-op configs, but it resolves only the test relevant for the job, which is impossible to detect for handcrafted jobs in other way than looking at the `--target=XXX` parameter. Other option was to implement a "if no matching test was found, resolve *all present*, but that changes the behavior more significantly, and breaks multiple integration tests (which are a pinnacle of …

pj-rehearse: support handcrafted jobs with UNRESOLVED_CONFIG

---

cmd/ipi-deprovision/ipi-deprovision.sh

Reverts openshift/ci-tools#1463
@stevekuznetsov got timestamped logs from [this run][1], and they included:
```
2020-12-01T17:42:50.801274924Z level=debug msg=OpenShift Installer unreleased-master-3986-g36cf196e4bb097967ed6d0355f448eaf3c9763af-dirty
2020-12-01T17:42:50.801300795Z level=debug msg=Built from commit 36cf196e4bb097967ed6d0355f448eaf3c9763af
...
2020-12-01T17:42:51.549404286Z level=debug msg=search for IAM roles
2020-12-01T17:44:58.393568493Z level=debug msg=search for IAM users
2020-12-01T17:51:39.370784031Z level=debug msg=search for IAM instance profiles
...
2020-12-01T17:52:50.71621937Z SIGQUIT: quit
```
So the slow IAM user listing is only leaving us ~70s to perform the actual deletion.  We should raise the cap back up to give things more time.  And also probably prune …

Revert "ipi-deprovisioner: tighen timeout to 10m per cluster"

---

cmd/ci-operator/main.go
pkg/api/graph.go
pkg/api/graph_test.go
pkg/steps/artifacts.go
pkg/steps/artifacts_test.go
pkg/steps/loggingclient/loggingclient.go
pkg/steps/multi_stage.go
pkg/steps/multi_stage_test.go
pkg/steps/run.go

Includes https://github.com/openshift/ci-tools/pull/1458 to avoid needing another rebase
The json unmarshaler refuses to unmarshal into a non-empty interface as it can't know the underlying type. So this adds a custom unmarshaler, that unmarshals the manifests into `*unstructured.Unstructured`. This in turn requires TypeMeta which is not set by default, so the second commit adds that.

Allow unmarshaling ci-operator step graph

---

pkg/controller/registrysyncer/registrysyncer.go
pkg/controller/registrysyncer/registrysyncer_test.go

The lock prevents the concurrent reconcile because the events for the same IS are grouping together (they are converted from the events on IS).
The reason that we lock in the first place is that we do not want to see loggings on `isConflict` errors.
Here we reconcile on those errors, but ignore the logging.

 registrySyncer: remove locks on imagestream at reconcile

---

pkg/rehearse/jobs.go
pkg/rehearse/jobs_test.go
test/integration/pj-rehearse/candidate/ci-operator/jobs/super/duper/super-duper-periodics.yaml
test/integration/pj-rehearse/expected.yaml

My IDE was yelling at me so I fixed the issues. Left out from https://github.com/openshift/ci-tools/pull/1430 b/c that one is already hard to review.
/hold
Needs https://github.com/openshift/ci-tools/pull/1430 first

minor code cleanup in rehearsals 

---

pkg/controller/registrysyncer/registrysyncer.go

Save us some cost for storage and make triage's work easier.

registrySyncer: ingore logging of IsAlreadyExists errors

---

pkg/steps/multi_stage.go
pkg/steps/multi_stage_test.go
pkg/steps/release/create_release.go
pkg/steps/release/import_release.go
pkg/util/rbacs.go
pkg/util/rbacs_test.go

When a service account is being created, the [DockercfgController](https://github.com/openshift/openshift-controller-manager/blob/master/pkg/serviceaccounts/controllers/create_dockercfg_secrets.go#L315) creates the pull secret and then update the service account. Therefore if the service account will be used before the creation of that secret, the running pod will pull images as anonymous instead. 
This PR fixes this race condition by creating a new function that will be responsible for the RBAC creation and waits until the dockercfg controller will create the secret and sync the service account.
Jobs with the related error: [ci-search - Container .* is not ready with reason ImagePullBackOff](https://search.ci.openshift.org/?search=Container+.*+is+not+ready+with+reason+ImagePullBackOff&max …

[DPTP-1731] add the ability to create rbacs and wait until the image pull secret has been created

---

cmd/template-deprecator/main.go
pkg/deprecatetemplates/allowlist.go
pkg/deprecatetemplates/allowlist_test.go
pkg/deprecatetemplates/enforcer.go
pkg/deprecatetemplates/enforcer_test.go

Adds two checks over the allowlist:
- Force removal of unused templates
- Prevent people from adding jobs to an "unknown blokcker" section that was previously empty
Example output:
```console
$ template-deprecator --prow-jobs-dir ci-operator/jobs --prow-config-path core-services/prow/02_config/_config.yaml --prow-plugin-config-path core-services/prow/02_config/_plugins.yaml --allowlist-path core-services/template-deprecation/_allowlist.yam
ERROR: Template deprecation allowlist has errors:
ERROR: 1)
The following templates are not used by any job. Please remove their
config-updater config from core-services/prow/02_config/_plugins.yaml)
and code from ci-operator/templates. If you are trying to add a new template,
you should add multi-stage steps instead.
- …
```

template-deprecator: add enforcing checks

---

pkg/steps/source.go
pkg/steps/testdata/zz_fixture_TestCreateBuild_basic_options_for_a_presubmit.yaml
pkg/steps/testdata/zz_fixture_TestCreateBuild_with_OAuth_token.yaml
pkg/steps/testdata/zz_fixture_TestCreateBuild_with_a_path_alias.yaml
pkg/steps/testdata/zz_fixture_TestCreateBuild_with_a_pull_secret.yaml
pkg/steps/testdata/zz_fixture_TestCreateBuild_with_extra_refs.yaml
pkg/steps/testdata/zz_fixture_TestCreateBuild_with_extra_refs_setting_workdir_and_path_alias.yaml
pkg/steps/testdata/zz_fixture_TestCreateBuild_with_ssh_key.yaml

It is not clear why this change ever landed into our build manifest for
the source image. The `clonerefs` utility gained this behavior six
months after the change here landed, and obsoleted it.
Our hack: https://github.com/openshift/ci-tools/commit/9ee986993c1c5c3f92078ba664710a892587255f
Upstream: https://github.com/kubernetes/test-infra/commit/7f9f4fc812769639ea72924fa2b7c99ca0bf25c1

ci-operator: stop explicitly updating submodules

---

cmd/ipi-deprovision/ipi-deprovision.sh

Cluster teardown is not particularly CPU-intensive, and there is a lot of waiting around for cloud-provider queries to come back or cloud-provider state to become eventually consistent.  Tearing down clusters in parallel will allow us to grind through a backlog of leaked clusters more quickly, and will also give us some ability to continue reaping in the face of small numbers of stuck-in-teardown clusters (which currently gum up the works for their full 30m quota before being SIGQUITed).
The `queue` function is lifted from `pkg/steps/clusterinstall/template.go` with minor changes (no need to redirect stdout, since the installer is mostly writing to stderr).  I've dropped the parallel-job to 10, which will still be 10x faster than the outgoing, serial logic, and seems like plenty until we …

cmd/ipi-deprovision: Parallel cluster teardown

---

pkg/controller/registrysyncer/registrysyncer.go
pkg/controller/registrysyncer/registrysyncer_test.go

Follow up https://github.com/openshift/release-controller/pull/233#discussion_r537586799

registrySyncer: use RFC3339 to format soft-delete annotation

---

cmd/dptp-controller-manager/main.go
pkg/api/domain.go
pkg/api/domain_test.go
pkg/controller/registrysyncer/registrysyncer.go
pkg/controller/registrysyncer/registrysyncer_test.go
pkg/controller/secretsyncer/secretsyncer.go
pkg/controller/test-images-distributor/test_images_distributor.go
pkg/controller/test-images-distributor/test_images_distributor_test.go

https://issues.redhat.com/browse/DPTP-1657
The target of this PR is that promotion and DPTP-CM are ready for CI registry migration from api.ci to app.ci:
Modify the two TODOs in this PR.

Make CI Registry configurable

---

pkg/steps/input_image_tag.go
pkg/steps/multi_stage.go

We are migrating the registry soon and decouple `api.ci` and CI registry.

Rename var apiCIRegistry to ciRegistry

---

cmd/determinize-ci-operator/main.go
cmd/determinize-ci-operator/main_test.go

Moves forward [DPTP-1775](https://issues.redhat.com/browse/DPTP-1775)
Right now we have these two types in the repo:
1. upgrade tests (are migrated to the matching workflow)
```diff
- as: e2e-aws-upgrade
-  commands: TEST_SUITE=all run-upgrade-tests
-  openshift_installer:
+  steps:
cluster_profile: aws
-    upgrade: true
+    workflow: openshift-upgrade-aws-loki
```
2. disruptive tests (cannot be simply migrated right now, so they are
kept)
I added code to migrate plain `openshift_installer` jobs too b/c it was
simple enough. Not handling that case would be suprising to an
unsuspecting reader of the code.

Add feature to automatically migrate openshift_installer jobs

---

cmd/ci-secret-bootstrap/main.go
cmd/ci-secret-bootstrap/main_test.go
pkg/api/secretbootstrap/secretboostrap.go
pkg/api/secretbootstrap/secretboostrap_test.go

The added validation step will fail the run as early as possible.
Otherwise, it will be rejected by k8s server eventually.

ci-secret-bootstrap: validate config

---

cmd/determinize-ci-operator/main.go
cmd/determinize-ci-operator/main_test.go

@wking and @vrutkovs prefer to use the non-loki workflow for the general usage

Migrate to non-loki upgrade workflow

---

hack/lib/integration.sh
test/e2e/lease.sh

There is no status API endpoint, so the name of a valid resource which
will be acquired and released is required.
Output with the current E2E failure:
```
[INFO] Waiting for boskos to be ready...
FAILURE after 0.456s: hack/lib/integration.sh:136: executing 'curl --request POST --silent --show-error --fail 'http://localhost:8080/acquire?type=aws-quota-slice&state=free&dest=leased&owner=test'' expecting success; re-trying every 0.2s until completion or 0.030s: the command timed out
Standard output from the command:
Standard error from the command:
curl: (7) Failed to connect to localhost port 8080: Connection refused
... repeated 2 times
[INFO] Stopping boskos...
/home/bbguimaraes/src/ci-tools/hack/lib/integration.sh: line 153: kill: (298912) - No such process
[ERROR] boskos exited early, …
```

e2e: verify that the boskos server started

---

cmd/dptp-controller-manager/main.go
pkg/controller/registrysyncer/registrysyncer.go
pkg/controller/registrysyncer/registrysyncer_test.go

Follow up https://github.com/openshift/release/pull/14171#issuecomment-740778585
* hard-coded denied list of namespace prefixes: 
```
deniedNamespacePrefixes = sets.NewString("kube", "openshift", "default", "redhat", "ci-op")
```
* the above can be overwritten by `registrySyncerOptions.image-stream-prefix` because we need to sync those
```
- --registrySyncerOptions.image-stream-prefix=openshift/knative-
- --registrySyncerOptions.image-stream-prefix=openshift/kubefed-operator-
- --registrySyncerOptions.image-stream-prefix=openshift/tektoncd-
```

registrySyncer: sync all images by default

---

Makefile

Corrects:
```
bash: oc: command not found
```
https://prow.ci.openshift.org/view/gs/origin-ci-test/pr-logs/pull/openshift_ci-tools/1509/pull-ci-openshift-ci-tools-master-e2e/1336962442692923392
```
$ CI=1 make --dry-run e2e
hack/test-e2e.sh
$ make --dry-run e2e
mkdir -p /tmp/pull-secret
oc --context api.ci --as system:admin --namespace ci get secret registry-pull-credentials -o 'jsonpath={.data.\.dockerconfigjson}' | base64 --decode | jq > /tmp/pull-secret/.dockerconfigjson
mkdir -p /tmp/import-secret
oc --context api.ci --as system:admin --namespace ci get secret ci-pull-credentials -o 'jsonpath={.data.\.dockerconfigjson}' | base64 --decode | jq > /tmp/import-secret/.dockerconfigjson
mkdir -p /tmp/image
oc image extract registry.ci.openshift.org/ci/boskos:latest --path /:/tmp/image
mv …
```

Makefile: only setup E2E environment outside of CI

---

pkg/steps/artifacts.go

It seems getting called multiple times is expected and not an issue, so
don't confuse users. We will hopefully get rid of this soon and use
decoration utils instead.

Artifacts: Remove stack printing

---

pkg/controller/registrysyncer/registrysyncer.go

regSyncer: ingore images in ci-ln* namespaces

---

pkg/steps/multi_stage.go

Made redundant by https://github.com/openshift/ci-tools/pull/1312.  A
synthetic lease configuration is always added if the test declares a
cluster profile:
https://github.com/openshift/ci-tools/blob/7cb311dcb781a92b5ab12e9cb382e5c8b57246e6/pkg/defaults/defaults.go#L378-L384
This results in a (harmless) duplicated environment variable in the pod,
e.g.:
https://prow.ci.openshift.org/view/gs/origin-ci-test/pr-logs/pull/openshift_machine-config-operator/2289/pull-ci-openshift-machine-config-operator-release-4.6-e2e-vsphere/1337056306510434304
https://gcsweb-ci.apps.ci.l2s4.p1.openshiftapps.com/gcs/origin-ci-test/pr-logs/pull/openshift_machine-config-operator/2289/pull-ci-openshift-machine-config-operator-release-4.6-e2e-vsphere/1337056306510434304/artifacts/build-resources/pods.json
```json
{ …
```

ci-operator multi-stage: add lease env once

---

pkg/api/domain.go
pkg/api/domain_test.go
pkg/steps/release/promote_test.go
pkg/steps/testdata/zz_fixture_TestGeneratePods.yaml

This reverts commit ecb704fdd1d890c40d2fe692ce0732336ba21e73.
I was not patient enough to wait for the first successful promote because promotions were failing because of https://github.com/openshift/release/pull/14268
Will try with the presubmit image this time.
/hold

Revert "Revert "Promote images to app.ci""

---

cmd/dptp-controller-manager/main.go

Follow up https://github.com/openshift/release/pull/14283
Did not notice that we use the inClusterConfig for app.ci.

Check app.ci's kubeconfig after loading InClusterConfig

---

cmd/repo-init/main.go
cmd/repo-init/main_test.go
pkg/api/types.go
test/integration/repo-init.sh
test/integration/repo-init/expected/ci-operator/config/org/repo/org-repo-master.yaml
test/integration/repo-init/expected/ci-operator/config/org/third/org-third-nonstandard.yaml
test/integration/repo-init/expected/ci-operator/jobs/org/repo/org-repo-master-presubmits.yaml
test/integration/repo-init/expected/ci-operator/jobs/org/third/org-third-nonstandard-presubmits.yaml

This PR makes the `repo-init` tool to generate multi-stage jobs instead of template ones. 
It is currently allows to create a job using only `gcp` `aws` and `azure4` cluster profiles.

[DPTP-1721] make repo-init tool to generate multi-stage jobs instead of templates

---

pkg/api/types.go
pkg/webreg/zz_generated.ci_operator_reference.go

Why is the generator missing the docstring for `ResourceList`? Is it getting lost on the type alias to `map[string]string`?
Fixes [DPTP-1744](https://issues.redhat.com/browse/DPTP-1744)

config: document resource requests and limits

---

pkg/steps/clusterinstall/template.go

Like openshift/release@7aa198b3c7 (openshift/release#12584), but for AWS and GCP here too, now that we have evidence that the approach is working.
I'm keeping a switch for AWS to give folks a pattern for selecting zones, if AWS breaks a zone in a particular region.  We should probably distribute that (and the shared subnets, for shared-subnet tests?) via leases as well, but baby steps.

pkg/steps/clusterinstall/template: Get region from Boskos lease

---

pkg/load/load.go

The `configFromResolver` function prints the response body for non-200
status responses from the resolver, but it wasn't changed for
`literalConfigFromResolver`. This PR fixes that.

load: print response body from configresolver for literal configs

---

pkg/steps/clusterinstall/template.go

I'd attempted to consume this as an environment variable in 00ebab17e1 (#1527), but it's failing in CI [with][1]:
```
2020/12/15 18:04:36 Running pod e2e-aws-upgrade
Installing from initial release registry.svc.ci.openshift.org/ocp/release:4.5.23
/bin/bash: line 59: LEASED_RESOURCE: unbound variable
```
With this commit, I'm making it a template parameter, so it will be filled in by Go template expansion (and never be an environment variable within the test pod).
[1]: https://prow.ci.openshift.org/view/gs/origin-ci-test/logs/release-openshift-origin-installer-e2e-aws-upgrade-rollback-4.5-to-4.6/1338903713728696320#1:build-log.txt%3A29

pkg/steps/clusterinstall/template: Add LEASED_RESOURCE parameter

---

pkg/controller/registrysyncer/registrysyncer.go

`.tag.from.name` does NOT reflect the current status of the image.
After promoting to `app.ci`, this became an overkill: we ignore some images that we should sync.
I keep the log there because I want to see how many of them are happening.

registerSyncer: Allow images pushed back to the original cluster

---

cmd/release-job-migrator/main.go
test/integration/release-job-migrator/expected.txt
test/integration/release-job-migrator/expected/ci-operator/openshift/release/openshift-release-master__origin-4.6.yaml
test/integration/release-job-migrator/expected/jobs/openshift-release-release-4.7-periodics.yaml
test/integration/release-job-migrator/expected/releases/release-origin-4.7.json
test/integration/release-job-migrator/input/jobs/openshift-release-release-4.6-periodics.yaml
test/integration/release-job-migrator/input/jobs/openshift-release-release-4.7-periodics.yaml
test/integration/release-job-migrator/input/releases/release-origin-4.7.json

Due to very simple find replace for updating release-controller job
names, some upgrades would get renamed improperly. For example, in the
updated integration test, the code would've changed
`release-openshift-origin-installer-e2e-gcp-upgrade-4.6-stable-to-4.7`
to
`periodic-ci-openshift-release-master-origin-4.6-e2e-gcp-upgrade-stable-to-4.7`
due to `release-openshift-origin-installer-e2e-gcp-upgrade-4.6` being
migrated and the 4.6-to-4.7 job containing the entire 4.6 job's name in
it. The replacement now does a larger replacement that avoids this
issue.

release-job-migrator: fix release-controller jobName replacement

---

pkg/webreg/webreg.go

Fixes: [DPTP-1653](https://issues.redhat.com/browse/DPTP-1653)
~Preview is supposed to be on https://server-ci-tools-1522.apps.ci.l2s4.p1.openshiftapps.com but :thisisfine: is happening on app.ci.~
- [example step with `from`](https://server-ci-tools-1522.apps.ci.l2s4.p1.openshiftapps.com/reference/ipi-install-rbac) ([current state](https://steps.ci.openshift.org/reference/ipi-install-rbac))
- [example test with `from_image`](https://server-ci-tools-1522.apps.ci.l2s4.p1.openshiftapps.com/reference/ipi-conf) ([current_state](https://steps.ci.openshift.org/reference/ipi-conf))

webreg: surface `from_image` in UI 

---

cmd/secret-wrapper/main.go

The unconditional log message in the go routine that uploads the
`kubeconfig` misleads readers into thinking there is some infrastructure
problem when a test fails, e.g.:
```
level=fatal msg=failed to initialize the cluster: Working towards 4.7.0-0.ci.test-2020-12-17-035943-ci-op-lqd3b7rr: 88% complete
2020/12/17 05:29:25 Failed to upload $KUBECONFIG: timed out waiting for the condition: stat /tmp/secret/kubeconfig: no such file or directory
error: failed to execute wrapped command: exit status 1
2020/12/17 05:29:30 Container test in pod kubevirt-plugin-ipi-install-install failed, exit code 1, reason Error
```
https://prow.ci.openshift.org/view/gs/origin-ci-test/pr-logs/pull/openshift_console/6739/pull-ci-openshift-console-master-kubevirt-plugin/1339417605932322816

secret-wrapper: do not log cancellations

---

pkg/steps/clusterinstall/template.go

I still wish the end-to-end suite pulled the region out of the cluster itself, but until it does, lean on [the Infrastructure status][1] like we've been doing for AWS since openshift/release@bf0a271f5c (openshift/release#2507).  The hard-coding I'm replacing here was fine until the GCP region became dynamic in 00ebab17e1 (#1527).
[1]: https://github.com/openshift/api/blob/164a2fb63b5f12918c439a5a0a768aa911bcad99/config/v1/types_infrastructure.go#L327-L328

pkg/steps/clusterinstall/template: GCP region from the cluster
