pkg/steps/multi_stage/run.go
This part of the code is already difficult to follow as it is.
`ci-operator` is generally not happy about pods it is following being deleted,
which does not happen frequently due to the PDB used for builds and tests.  Put
the error in the debug log so it can be used to understand how the monitoring
code responds to the deletion.
---
The notifier (which generates JUnit information) is only triggered by terminated
pods:
https://github.com/openshift/ci-tools/blob/68249882ebce83a5f9b093b313adad88d67f67dd/pkg/util/pods.go#L378
which explains results seen in some of the E2E test failures (the test itself is
a very contrived — but possible — scenario).  This should help identify the sort
of information coming from the API server in those situations.
=> ci-operator multi-stage: log observer errors

cmd/pj-rehearse/main.go, pkg/rehearse/rehearse.go, pkg/rehearse/rehearse_test.go, test/integration/pj-rehearse.sh, test/integration/pj-rehearse/expected.yaml
Reverts openshift/ci-tools#3066 which reverted https://github.com/openshift/ci-tools/pull/3063, and fixes the setupDependencies step. 
All we needed to do was actually load the buildClusterConfigs, but I messed up the assignment operator during the refactor...
=> `pj-rehearse`: refactor in place to allow for use in prow plugin

cmd/pod-scaler/admission.go, cmd/pod-scaler/admission_test.go
To reduce the number of alerts, this modifies pod-scaler admission so it doesn't report the warning when the configured memory is 0.
for https://issues.redhat.com/browse/DPTP-2929
/cc smg247
=> pod-scaler admission: filter out workloads with 0 configured memory

pkg/controller/prpqr_reconciler/prpqr_reconciler.go, pkg/controller/prpqr_reconciler/testdata/zz_fixture_prowjobs_TestReconcile_basic_aggregated_case.yaml, pkg/controller/prpqr_reconciler/testdata/zz_fixture_prowjobs_TestReconcile_basic_case.yaml, pkg/controller/prpqr_reconciler/testdata/zz_fixture_prowjobs_TestReconcile_basic_case_with_variant.yaml, pkg/controller/prpqr_reconciler/testdata/zz_fixture_prowjobs_TestReconcile_multiple_case__one_of_the_prowjobs_already_exists.yaml, pkg/jobrunaggregator/jobrunaggregatoranalyzer/analyzer.go
This reverts changes from the following PRs:
- https://github.com/openshift/ci-tools/pull/3045
- https://github.com/openshift/ci-tools/pull/3042
- https://github.com/openshift/ci-tools/pull/3041
- https://github.com/openshift/ci-tools/pull/3034 (partially)
also:
- https://github.com/openshift/ci-tools/pull/3046
/assign @bradmwilliams @dgoodwin
=> Revert timeouts needed to land k8s bump

OWNERS
So we avoid nonsensical approval attributions such as:
https://github.com/openshift/ci-tools/pull/3070#issuecomment-1271668611
=> Unify approvers/reviewers in root OWNERS file

cmd/pj-rehearse/main.go
Minor bug with the refactor, we now report the job as failed if we don't find anything to rehearse. See [example log](https://prow.ci.openshift.org/view/gs/origin-ci-test/pr-logs/pull/openshift_release/32927/pull-ci-openshift-release-master-pj-rehearse/1578381689887920128).
=> `pj-rehearse`: don't report failure when there are no jobs to rehearse

cmd/cluster-init/update_secret_generator.go, cmd/config-brancher/main.go, cmd/prow-job-dispatcher/main.go, pkg/backporter/httpcache_test.go, pkg/jobrunaggregator/jobrunaggregatorapi/types_row_job.go, pkg/jobrunaggregator/jobrunaggregatorapi/types_row_testrun.go, pkg/kubernetes/pkg/credentialprovider/config.go, pkg/release/official/client.go, pkg/results/error.go, pkg/util/sync.go, pkg/webreg/webreg.go, test/e2e/framework/ci-operator.go, test/e2e/framework/test.go
I know that we aren't using `go` version `1.19` yet, but I started using it locally and it seems `gofmt` likes to format comments differently now. This change should be backwards compatible and will just be one less thing we have to do when we bump versions.
=> Update formatting to prep for golang version 1.19

pkg/rehearse/rehearse.go
I discovered another case of `pj-rehearse` behaving incorrectly post-refactor. It marks itself as failed if all the affected jobs are filtered out due to not being valid for rehearsal. The original code: https://github.com/openshift/ci-tools/blob/59dafbf35eb09ed0ba56fa06a33022f3f47bfe30/cmd/pj-rehearse/main.go#L326-L328
Example erroneous [log](https://prow.ci.openshift.org/view/gs/origin-ci-test/pr-logs/pull/openshift_release/32983/pull-ci-openshift-release-master-pj-rehearse/1579448374787051520).
=> `pj-rehearse`: do not error when all jobs have been filtered out

cmd/entrypoint-wrapper/main.go, cmd/pr-reminder/main.go, pkg/steps/multi_stage/multi_stage.go, pkg/steps/multi_stage/multi_stage_test.go
I finally managed to get `golangci-lint` working on my machine again
(apparently, it's very sensitive about the Go version on the system, building
from source made it work again).
Fix a few new issues identified by this new version (`v1.48.0`).
=> Satisfy new linter warnings

pkg/api/types.go
Because only some specific azure location supports arm64 vm_type, add a new Cluster Profile for it with specific location quota slice.
refer [release#33059](https://github.com/openshift/release/pull/33059)
refer [ARMOCP-221](https://issues.redhat.com/browse/ARMOCP-221)
=> Add the Azure Arm64 QE Cluster Profile

cmd/sprint-automation/main.go
This one only started being identified here after
https://github.com/openshift/ci-tools/pull/3078, for whatever reason.
=> sprint-automation: address another linter warning

pkg/api/types.go, pkg/release/prerelease/client.go, pkg/webreg/zz_generated.ci_operator_reference.go
To allow access to [4-dev-preview][1] (and [on arm64][2], etc.).
[1]: https://amd64.ocp.releases.ci.openshift.org/#4-dev-preview-arm64
[2]: https://arm64.ocp.releases.ci.openshift.org/#4-dev-preview-arm64
=> pkg/release/prerelease: Add 'stream' property

cmd/pj-rehearse/main.go
Follow up to: https://github.com/openshift/ci-tools/pull/3074. We exited from the `setupJobs` function, but the whole process needs to end in this case. See example [log](https://prow.ci.openshift.org/view/gs/origin-ci-test/pr-logs/pull/openshift_release/33169/pull-ci-openshift-release-master-pj-rehearse/1582007145447034880) where it still fails.
=> `pj-rehearse`: don't validate or rehearse when all jobs have been filtered out

cmd/pj-rehearse/main.go, cmd/pj-rehearse/server.go, pkg/config/jobs.go, pkg/rehearse/rehearse.go
This adds a server to `pj-rehearse` to act as an external prow plugin. Initially, we will have `preCheck` and `commentOnPrCreation` turned off to do a soft-rollout of this change. Eventually, these will both be turned on.
When a PR is created in configured repos, the plugin determines the affected jobs and comments like:
When a user adds a comment like `/pj-rehearse` or any of the similar commands, the jobs are triggered.
When a user comments `/pj-rehearse ack` or `/pj-rehearse skip` the `rehearsals-ack` label is added.
For: https://issues.redhat.com/browse/DPTP-3092
/cc @openshift/test-platform @droslean
=> `pj-rehearse`: create external plugin server

cmd/pod-scaler/admission.go, cmd/pod-scaler/admission_test.go
We need to better identify prowjobs in prometheus metrics (`pod_scaler_admission_high_determined_memory`) by reading the prow job label.
for https://issues.redhat.com/browse/DPTP-2929
/cc smg247
=> DPTP-2929: determine prowjob name based on labels

cmd/cluster-init/update_jobs.go, pkg/jobconfig/files.go, pkg/jobconfig/files_test.go, test/integration/cluster-init/create/expected/ci-operator/jobs/openshift/release/openshift-release-master-periodics.yaml, test/integration/cluster-init/create/expected/ci-operator/jobs/openshift/release/openshift-release-master-postsubmits.yaml, test/integration/cluster-init/create/expected/ci-operator/jobs/openshift/release/openshift-release-master-presubmits.yaml, test/integration/cluster-init/update/expected/ci-operator/jobs/openshift/release/openshift-release-master-periodics.yaml, test/integration/cluster-init/update/expected/ci-operator/jobs/openshift/release/openshift-release-master-postsubmits.yaml, test/integration/cluster-init/update/expected/ci-operator/jobs/openshift/release/openshift-release-master-presubmits.yaml, test/integration/cluster-init/update/input/ci-operator/jobs/openshift/release/openshift-release-master-periodics.yaml, test/integration/cluster-init/update/input/ci-operator/jobs/openshift/release/openshift-release-master-postsubmits.yaml, test/integration/cluster-init/update/input/ci-operator/jobs/openshift/release/openshift-release-master-presubmits.yaml
This PR will rename the label such as `ci.openshift.io/cluster: build01` on the `applyconfig` jobs.
E.g., https://github.com/openshift/release/blob/3ac02be7013dee4f368683dc1cd61763df9efef3/ci-operator/jobs/openshift/release/openshift-release-master-presubmits.yaml#L278
`ci.openshift.io/generator: cluster-init` should be enough to show the job is managed/generated.
`ci.openshift.io/cluster: build01` could be easily interpreted as the job runs on `build01` but it actually on `app.ci`.
The label `ci-operator.openshift.io/cluster: build01` is for that purpose.
We rename the former for reducing the confusion.
/hold
Need to fix the breaking.
=> Rename the cluster label on applyconfig jobs

cmd/pj-rehearse/server.go, pkg/rehearse/rehearse.go
I found a couple of issues related to the refs when testing out the new plugin:
1. Many modified jobs are found that weren't actually present in the PR. This is due to simply using the base SHA from the `PullRequest` rather than determining the SHA for the current head. See [example comment on test PR](https://github.com/openshift/release/pull/33262#issuecomment-1284368180).
2. Triggered rehearsal jobs don't contain the proper org in the `refs`. They currently have the `org` set to that of the fork. I didn't notice this with initial testing as I was testing it in my fork. We need to use the Base org instead.
=> `pj-rehearse`: fix incorrect ref issues with plugin

pkg/steps/release/promote.go
This PR fixes the logging only when promoting the tags built for a different architecture.
Example: https://prow.ci.openshift.org/view/gs/origin-ci-test/logs/branch-ci-openshift-ci-tools-master-images-arm64/1582469276256702464#1:build-log.txt%3A243
=> fix logging when promoting images for different architectures

pkg/api/types.go, pkg/validation/release.go, pkg/validation/release_test.go
This PR fixes the consumers of the ReleaseProduct and ReleaseStream APIs that will try validating the new OKD's `okd-scos` ReleaseStream name. 
I tested `ci-operator-checkconfig`, `ci-operator,prowgen`, `the determinize-ci-operator` locally against the changes at [openshift/openshift-release#33320](https://github.com/openshift/release/pull/33320)
/cc @LorbusChris @vrutkovs
I'm not 100% sure this is enough for the jobs at the PR above to start passing and the rehearsals to be triggered.
=> [OKD/SCOS] Adding okd-scos as a ReleaseStream for the OKD ReleaseProduct

cmd/pj-rehearse/server.go, pkg/rehearse/rehearse.go
Follows up on: https://github.com/openshift/ci-tools/pull/3101.
Unfortunately, even when the correct `SHA` was used for determining the changes we still got a bunch of changes that were made in between the HEAD and the BASE.
In order to solve this we simply need to rebase the PR branch onto the current head. This will apply cleanly in the case that a manual rebase is not needed, and if that is needed we don't want to run rehearsals anyways. We don't push the rebase, so it is only present in our local git checkout.
I also needed to remove the `head` ref from the prow job `refs` in order for the rehearsal jobs to initialize. This is not something that the original `pj-rehearse` was setting, so no need to set it with the plugin.
=> `pj-rehearse`: plugin: rebase the branch onto the current master

pkg/jobrunaggregator/jobrunaggregatorapi/types_row_historical_data.go, pkg/jobrunaggregator/jobrunaggregatorlib/ci_data_client.go, pkg/jobrunaggregator/jobrunhistoricaldataanalyzer/analyzer.go, pkg/jobrunaggregator/jobrunhistoricaldataanalyzer/types.go, pkg/jobrunaggregator/jobrunhistoricaldataanalyzer/util.go
We fail tests if you're over the P99 value, but it turns out the
majority of our platforms we were enforcing on do not have 100 results
per 3 weeks, so we weren't really getting P99s and thus could fail quite
often for some.
Update the query to include the count of JobRuns, and exclude if there's less
than 100.
Also added sorting so the file stays in a consistent order, which will
help us decipher diffs when they land in origin.
[TRT-583](https://issues.redhat.com//browse/TRT-583)
=> Only include disruption NURPs if we have 100 rows.

pkg/api/types.go
The cloud services and platform integration team requires a dedicated cluster profile for spinning up openshift clusters using our aws account. Profile will be used for interoperability testing of products on openshift.
=> Create a dedicated aws cluster profile for cspi qe

pkg/config/release.go, pkg/config/release_test.go, pkg/registry/graph.go
This pull request adds tests for the existing implementation of change detection
for registry components.  Perfectly valid infrastructure was already in place
for profile/template/etc. tests (from before that implementation existed), so
this new test is fairly trivial.
37c63e53f tests the old code which detects reference/chain/workflow changes.
Some minor implementation improvements follow, then 3953052d9 extends the test
to also cover the temporary implementation for observer pod introduced in
https://github.com/openshift/ci-tools/pull/3061.
I have a proper graph node type with the correct edges for observers
implemented, but have been wrestling with our `pj-rehearse` integration tests,
so I'm separating this work into its own PR.
=> pkg/config: add test for registry change detection

pkg/api/domain.go, pkg/api/domain_test.go, pkg/slack/events/joblink/link.go, pkg/slack/events/joblink/link_test.go
We should be able to post the job info from links like https://storage.googleapis.com/origin-ci-test/pr-logs/pull/openshift_cluster-ingress-operator/836/pull-ci-openshift-cluster-ingress-operator-master-e2e-aws-operator/1583384716713660416/build-log.txt rather than just the GCS viewer links.
Brought on by this [slack thread](https://coreos.slack.com/archives/CBN38N3MW/p1666378352080869).
=> `slack-bot`: post job links for storage.googleapis.com links

cmd/pj-rehearse/server.go, cmd/sprint-automation/main.go
We don't want to ever comment an empty job table, if no rehearsable jobs are found we should just say that and immediately ack the rehearsals. I also refactored the code to de-duplicate the acknowledgement.
We also need to fail when the rebase fails. This utilizes the returned `bool` of `MergeWithStrategy` which will be false if the rebase failed.
=> `pj-rehearse`: plugin: don't comment empty job table and streamline acknowledgement

pkg/jobrunaggregator/jobtableprimer/generate_jobnames.go, pkg/jobrunaggregator/jobtableprimer/job_typer.go, pkg/jobrunaggregator/jobtableprimer/jobs.go
We recently noticed data in bigquery with no platform. Traced down to a couple key issues missing alibaba and ibmcloud as platforms.
I've also disabled microshift jobs for the time being, today they're using a single GCP UPI vm, but the jobs are not consistently named, stable, and I don't feel safe lumping it in with standard GCP IPI, nor single node.
[TRT-624](https://issues.redhat.com//browse/TRT-624)
=> fix empty platforms

pkg/jobrunaggregator/jobtableprimer/generate_jobnames.go
[TRT-646](https://issues.redhat.com//browse/TRT-646)
=> Also skip okd jobs for gathering disruption/alert data.

pkg/controller/serviceaccount_secret_refresher/serviceaccount_secret_refresher.go, pkg/controller/serviceaccount_secret_refresher/serviceaccount_secret_refresher_test.go
To follow up https://coreos.slack.com/archives/GB7NB0CUC/p1665415175612979
```
{
"cluster": "build01",
"component": "dptp-controller-manager",
"controller": "serviceaccount_secret_refresher",
"error": "failed to wait for ServiceAccount to have a pull and a tokenSecret: timed out waiting for the condition",
"file": "/go/src/github.com/openshift/ci-tools/pkg/controller/serviceaccount_secret_refresher/serviceaccount_secret_refresher.go:87",
"func": "github.com/openshift/ci-tools/pkg/controller/serviceaccount_secret_refresher.(*reconciler).Reconcile",
"kubernetes": {
"container_id": "cri-o://15a1d90a1b6f0702fbdd273f277f504b3b7b9bcab0380c6e204aef709889aa14",
"container_image": "image-registry.openshift-image-registry.svc:5000/ci/dptp-controller-manager@sha256:e3d4861b7782ef92405195e223425953479 …
```
=> serviceaccount_secret_refresher: stop handling SA's token secrets

cmd/pj-rehearse/main.go
A typo made this functionality not work.
=> `pj-rehearse` plugin: fix comment-on-pr-creation

cmd/pod-scaler/admission.go, cmd/pod-scaler/admission_test.go, cmd/result-aggregator/main.go, cmd/result-aggregator/main_test.go, pkg/results/report.go, pkg/results/report_test.go
This adds workload type for the Prometheus metric (`pod_scaler_admission_high_determined_memory`) to make determining the origin of workloads easier.
for https://issues.redhat.com/browse/DPTP-2929
/cc smg247
=> pod-scaler admission: add workload type

cmd/pr-reminder/main.go
Adds explanation of the :new: emoji (signifying a PR that was updated in the last 24h) into pr-reminder's legend.
/cc smg247
=> pr-reminder: add 'updated' emoji to legend

pkg/jobrunaggregator/jobrunaggregatorapi/types_row_historical_data.go, pkg/jobrunaggregator/jobrunhistoricaldataanalyzer/analyzer.go, pkg/jobrunaggregator/jobrunhistoricaldataanalyzer/pr_message_template.md, pkg/jobrunaggregator/jobrunhistoricaldataanalyzer/types.go
/assign @dgoodwin 
Changed:
- Updated template
- Removed redundant `JobRuns` from `AlertHistoricalDataRow` which is being inlined by `HistoricalJobData`
Signed-off-by: eggfoobar <eggfoobar@users.noreply.github.com>
=> feat: update render output to account for new release data

cmd/pj-rehearse/server.go, pkg/rehearse/jobs.go, pkg/rehearse/jobs_test.go, pkg/rehearse/rehearse.go, pkg/rehearse/testdata/zz_fixture_TestMakeRehearsalPresubmit_hidden_job_that_belong_to_the_same_org_repo_with_refs.yaml, pkg/rehearse/testdata/zz_fixture_TestMakeRehearsalPresubmit_job_that_belong_to_different_org_repo_than_refs.yaml, pkg/rehearse/testdata/zz_fixture_TestMakeRehearsalPresubmit_job_that_belong_to_different_org_repo_than_refs_with_custom_config.yaml, pkg/rehearse/testdata/zz_fixture_TestMakeRehearsalPresubmit_job_that_belong_to_the_same_org_but_different_repo_than_refs.yaml, pkg/rehearse/testdata/zz_fixture_TestMakeRehearsalPresubmit_job_that_belong_to_the_same_org_repo_with_refs.yaml, pkg/rehearse/testdata/zz_fixture_TestMakeRehearsalPresubmit_reporting_configuration_is_stripped_from_rehearsals_to_avoid_polluting.yaml, test/integration/pj-rehearse/expected.yaml
A few tweaks to the plugin are needed after seeing results and hearing comments from real users:
- Clean up the failure comments
- Fix the rerun command output for rehearsal jobs
- Move the label filtering logic to determineAffectedJobs so that we don’t list jobs that will eventually be filtered out
- When a user asks to rehearse and there are no affected jobs comment as such
- Refs should not be created using the repo name from the fork. See [thread](https://coreos.slack.com/archives/CBN38N3MW/p1667507527620019).
There are some more incoming, but wanted to get these out since they are ready.
/cc @droslean @openshift/test-platform 
/hold so I can watch the rollout
=> `pj-rehearse` plugin: day 1 fixes

cmd/check-gh-automation/main.go
We shouldn't add prowgen config files that are named `.config.prowgen` as repos to check in the tool.
For: https://issues.redhat.com/browse/DPTP-3204
=> `check-gh-automation`: stop mis-categorizing the prowgen config as a repo

pkg/jobrunaggregator/jobtableprimer/generate_jobnames.go
- Also skip okd jobs for gathering disruption/alert data.
- Safer detection of okd jobs to skip.
=> skip okd jobs 2

pkg/rehearse/rehearse.go
`build-cache` imagestreamtag importing always fails on new repo rehearsals. `ci-operator` doesn't care that the tags aren't present, so it just emits an error that is un-actionable and ultimately expected. See [slack thread](https://coreos.slack.com/archives/CBN38N3MW/p1667485385109159).
=> `pj-rehearse` plugin: stop importing build-cache imagestreamtags

pkg/release/candidate/client.go, pkg/release/config/client.go, pkg/release/official/client.go, pkg/release/prerelease/client.go
The error is confusing when the user doesn't know from what URL ci-operator is trying to get the release. e.x https://prow.ci.openshift.org/view/gs/origin-ci-test/logs/periodic-ci-openshift-multiarch-master-nightly-4.13-ocp-e2e-sdn-serial-aws-arm64/1590299757518000128
=> improve logging when requesting a release payload

pkg/controller/prpqr_reconciler/prpqr_reconciler_test.go, pkg/controller/prpqr_reconciler/testdata/zz_fixture_prowjobs_TestReconcile_basic_aggregated_case.yaml, pkg/controller/prpqr_reconciler/testdata/zz_fixture_prowjobs_TestReconcile_basic_case.yaml, pkg/controller/prpqr_reconciler/testdata/zz_fixture_prowjobs_TestReconcile_basic_case_with_cluster_override.yaml, pkg/controller/prpqr_reconciler/testdata/zz_fixture_prowjobs_TestReconcile_basic_case_with_metal_override.yaml, pkg/controller/prpqr_reconciler/testdata/zz_fixture_prowjobs_TestReconcile_basic_case_with_variant.yaml, pkg/controller/prpqr_reconciler/testdata/zz_fixture_prowjobs_TestReconcile_basic_case_with_vsphere_override.yaml, pkg/controller/prpqr_reconciler/testdata/zz_fixture_prpqr_TestReconcile_basic_case_with_cluster_override.yaml, pkg/controller/prpqr_reconciler/testdata/zz_fixture_prpqr_TestReconcile_basic_case_with_metal_override.yaml, pkg/controller/prpqr_reconciler/testdata/zz_fixture_prpqr_TestReconcile_basic_case_with_vsphere_override.yaml
This PR updates the unit tests to more clearly test the logic that selects the `Cluster` where to run the `/payload` jobs.
=> Adding cluster override unit tests

pkg/api/types.go
CNV team requires a dedicated cluster profile for running openshift clusters on our aws account. It will be used for interoperability testing - OCP+CNV+ODF
=> Create a dedicated aws cluster profile for interop testing

pkg/config/load.go
A continuation of https://github.com/openshift/ci-tools/pull/3137.
This allows resetting the ``additional_architectures`` list in a
repository configuration when it's also defined in the organization
configuration.
Required due to arm64 builds failing for assisted-installer
repositories.
=> [prowgen] merge additional_architectures when repo defines them

cmd/pr-reminder/main.go
This is another nice feature to see if a PR is worth opening. I tested it with the local script and received desired output.
=> `pr-reminder`: add 'accepted' and 'lgtm' labels to output

test/e2e/optional-operators/optional-operators.yaml
This took _way_ too much time to figure out.
This test has been failing for a long time.  No one cared because it is executed
as a post-submit.  The reason for that is its average execution time is around
30m:
https://prow.ci.openshift.org/job-history/gs/origin-ci-test/logs/branch-ci-openshift-ci-tools-master-e2e-oo-post
The failure is very puzzling:
```json
{
"component": "entrypoint",
"error": "could not start the process: fork/exec /var/run/configmaps/ci.openshift.io/multi-stage/verify: no such file or directory",
"file": "k8s.io/test-infra/prow/entrypoint/run.go:79",
"func": "k8s.io/test-infra/prow/entrypoint.Options.Run",
"level": "error",
"msg": "Error executing test process",
"severity": "error",
"time": "2022-11-18T19:50:39Z"
}
```
That is the `ConfigMap` which is used to mount …
=> test/e2e: fix optional operator tests

cmd/branchingconfigmanagers/rpm-deps-mirroring-services/.gitignore, cmd/branchingconfigmanagers/rpm-deps-mirroring-services/README.md, cmd/branchingconfigmanagers/rpm-deps-mirroring-services/main.go, go.mod, pkg/branchcuts/bumper/bumper.go, pkg/branchcuts/bumper/repo-bumper.go, pkg/branchcuts/bumper/repo-bumper_test.go
This is a tool that tries to automate the first step of phase "Before branching day" .
Check [Centralized Release Branching and Config Management V3](https://docs.google.com/document/d/1Z6ejnDCOCvNv9PWkyNPzVbjuLbDMAAT5GEeDpzb0SMs/edit#heading=h.r9xn02r1cyfn)
/cc @jmguzik @droslean
=> Before branching day: step 1

cmd/pod-scaler/producer.go
Starting around 11/02/22 the pod-scaler producer has been throwing errors like the following in all of the OSD managed clusters:
```
{"cluster":"build03","component":"pod-scaler","error":"could not determine Prometheus retention duration: not a valid duration string: \"11d or 90GiB\""}
```
This appears to be due to some recent change in the retention policy that OSD made. We have no better way to grab the duration piece of the policy, but it seems like if it is configured as a duration **or** a size then the duration comes first. This will work for the OSD clusters and the clusters we manage.
I will be monitoring the deployment to verify that this error goes away post-merge.
=> `pod-scaler` producer: parse retention duration out of full result

pkg/steps/index_generator.go, pkg/steps/index_generator_test.go, pkg/steps/testdata/isTags/pipeline_malformed_istag.yaml, pkg/steps/testdata/isTags/pipeline_no_bytes_istag.yaml, pkg/steps/testdata/isTags/pipeline_no_label_istag.yaml, pkg/steps/testdata/isTags/pipeline_v4.10_istag.yaml, pkg/steps/testdata/isTags/pipeline_v4.11_istag.yaml
Replacing https://github.com/openshift/ci-tools/pull/3169
This PR not going to fix https://issues.redhat.com/browse/DPTP-2969. Instead it does what it should have been done in https://github.com/openshift/ci-tools/pull/2818 as the short term solution to https://issues.redhat.com/browse/DPTP-2692
- Reverted https://github.com/openshift/ci-tools/pull/2818/files because the build errored out earlier. 
- Based on [the finding](https://issues.redhat.com/browse/DPTP-2969?focusedCommentId=21311180&page=com.atlassian.jira.plugin.system.issuetabpanels%3Acomment-tabpanel#comment-21311180), the job fails at the runtime of steps to compose the build if ci-operator detects that index in the config is not database format.
We still need to figure out how to adopt the middle term solution with the help …
=> Failed the build upon a file-based catalog index (2)

cmd/autoconfigbrancher/main.go, cmd/autoowners/main.go, cmd/pj-rehearse/server.go, cmd/prow-job-dispatcher/main.go, pkg/github/prcreation/prcreation.go, pkg/rehearse/rehearse.go
The following jobs will need to have rehearsals skipped (and thus have the label applied) in order to add the `rehearsals-ack`  label to the merge criteria. This is needed so that the `periodic-prow-auto-bump` job can auto merge only if all rehearsals pass.
1. autoconfigbrancher
2. autoowners
3. prow-job-dispatcher
I considered adding this as a parameter to each of these tools, but it seems like something that is unlikely to change as long as we are using the plugin as we will never care about rehearsals for these.
For: https://issues.redhat.com/browse/DPTP-3218
=> Add `rehearsals-ack` label on uninterested `openshift-bot` PRs

cmd/prow-job-dispatcher/main.go, pkg/dispatcher/config.go, pkg/dispatcher/config_test.go
When there is a failover and colocation is enabled (`DetermineE2EByJob`) some jobs are not moved from the broken cluster. This feature detects enabled colocation and replaces it for the time of the incident with optional colocation setting (`IgnoreE2EByJobAssignment`).
`IgnoreE2EByJobAssignment` means the job could be colocated or not; both states are accepted. It was developed to enable gradual colocation (% of jobs in batch PR). The incident is a similar situation, as some of the jobs need to be colocated and others not (these from the failing cluster).
Not using this flag and disabling `DetermineE2EByJob` means a complete rearrangement of jobs, the resulting PR will fallback to not colocated jobs for the time of the incident which may lead to scaling problems and will need to be again …
=> Fix dispatcher issue when failover happens and colocation is enabled

cmd/pj-rehearse/main.go, cmd/pj-rehearse/server.go, pkg/rehearse/configmaps.go, pkg/rehearse/configmaps_test.go, pkg/rehearse/jobs.go, pkg/rehearse/jobs_test.go, pkg/rehearse/rehearse.go, test/integration/pj-rehearse.sh, test/integration/pj-rehearse/expected.yaml
There are a few things that we no longer need in `pj-rehearse` now that the old runner jobs are no longer around:
- the dual job and debug loggers - now it can just be a single logger
- rehearsalLimit
- the job mode is now simplified to a basic mode for integration testing, this also means we can simplify the error messages
- the temporary CM code references `SHA` now instead of `buildId`
- we don't need to be able to create a `RehearsalCandidate` from a `JobSpec` anymore
For: https://issues.redhat.com/browse/DPTP-3208
/cc @openshift/test-platform @droslean 
/ hold so I can watch the rollout
=> `pj-rehearse`: remove defunct code for old runner

cmd/pj-rehearse/server.go, pkg/rehearse/jobs.go, pkg/rehearse/jobs_test.go, pkg/rehearse/rehearse.go, pkg/rehearse/rehearse_test.go, pkg/rehearse/testdata/zz_fixture_TestMakeRehearsalPresubmit_hidden_job_that_belong_to_the_same_org_repo_with_refs.yaml, pkg/rehearse/testdata/zz_fixture_TestMakeRehearsalPresubmit_job_that_belong_to_different_org_repo_than_refs.yaml, pkg/rehearse/testdata/zz_fixture_TestMakeRehearsalPresubmit_job_that_belong_to_different_org_repo_than_refs_with_custom_config.yaml, pkg/rehearse/testdata/zz_fixture_TestMakeRehearsalPresubmit_job_that_belong_to_the_same_org_but_different_repo_than_refs.yaml, pkg/rehearse/testdata/zz_fixture_TestMakeRehearsalPresubmit_job_that_belong_to_the_same_org_repo_with_refs.yaml, pkg/rehearse/testdata/zz_fixture_TestMakeRehearsalPresubmit_reporting_configuration_is_stripped_from_rehearsals_to_avoid_polluting.yaml, test/integration/pj-rehearse/expected.yaml
The long-awaited feature of being able to specify which job(s) to be rehearsed! This allows for comments like `/pj-rehearse some-test some-other-test` to trigger one or more of the affected jobs from the list that is commented on each PR.
For: https://issues.redhat.com/browse/DPTP-3170
=> `pj-rehearse`: allow for rehearsal of specific jobs

cmd/pj-rehearse/server.go
We should never apply the `rehearsals-ack` label when the user has simply requested to run a job. Even if that job is not found or unaffected.
=> `pj-rehearse`: don't ack the rehearsals when we just request to run a job

pkg/rehearse/jobs.go, pkg/rehearse/jobs_test.go
The filtering function has a bug where it will entirely skip looking at certain jobs. This can manifest in jobs not ending up in the final result that should have. We need to use some custom looping logic to account for removing elements from the slice in-place. The unit test was not complex enough to catch this error, so I made it more robust.
=> `pj-rehearse`: fix filter presubmit logic to not skip jobs

cmd/ci-secret-bootstrap/main.go, cmd/ci-secret-bootstrap/main_test.go
```
{"component":"XX-secret-bootstrap","error":"failed to update secrets: [error updating secret build03:openshift-config/pull-secret: Secret \"pull-secret\" is invalid: type: Invalid value: \"Opaque\": field is immutable, failed to check if namespace test-credentials exists: Get \"https://api.build02.gcp.xx.openshift.org:6443/api/v1/namespaces/test-credentials\": dial tcp: lookup api.build02.gcp.XX.openshift.org on 172.30.0.10:53: read udp 10.129.129.240:43287-\u003e172.30.0.10:53: read: connection refused, error updating secret build05:openshift-config/pull-secret: Secret \"pull-secret\" is invalid: type: Invalid value: \"Opaque\": field is immutable, error updating secret build04:openshift-config/pull-secret: Secret \"pull-secret\" is invalid: type: Invalid value: \"Opaque\": field is …
```
=> Fix the update of OSD global pull secrets

cmd/branchingconfigmanagers/generated-release-gating-jobs/.gitignore, cmd/branchingconfigmanagers/generated-release-gating-jobs/README.md, cmd/branchingconfigmanagers/generated-release-gating-jobs/main.go, pkg/branchcuts/bumper/gen-release-jobs-bumper.go, pkg/branchcuts/bumper/gen-release-jobs-bumper_test.go, pkg/branchcuts/bumper/replace.go, pkg/branchcuts/bumper/replace_test.go
This is a tool that tries to automate the second step of phase "Before branching day" .
Check [Centralized Release Branching and Config Management V3](https://docs.google.com/document/d/1Z6ejnDCOCvNv9PWkyNPzVbjuLbDMAAT5GEeDpzb0SMs/edit#heading=h.r9xn02r1cyfn)
/cc @jmguzik @droslean
=> Before branching day: step 2

pkg/jira/issues.go, pkg/jira/issues_test.go, pkg/slack/modals/incident/view.go, pkg/slack/modals/incident/view_test.go, pkg/slack/util.go
Generated by
> rg coreos.slack -l | while read file; do gsed -i 's/coreos.slack.com/redhat-internal.slack.com/g' $file; done
/cc @openshift/test-platform @jupierce 
/hold
Do it tomorrow?
From the letter:
"Check your Slack integrations and update references to the old workspace URL. The workspace URL for the CoreOS workspace will change from https://coreos.slack.com/ to https://redhat-internal.slack.com/ on Friday, December 16th, at 9 AM EST. Developers should update any workflows, webhooks, bots, custom or third-party applications that reference the old URL to ensure the link works."
=> Use redhat-internal.slack.com

pkg/api/types.go
Add 3 new cluster profiles to run OpenShift virtualization:
* aws-virtualization
* azure-virtualization
* gcp-virtualization
Signed-off-by: Nahshon Unna-Tsameret <nunnatsa@redhat.com>
=> Add new cluster profiles for OpenShift Virtualization

cmd/private-org-sync/README.md, cmd/private-org-sync/main_test.go
I recently spent a good amount of time tracking this problem after a support
request only to discover it's intentional and rigorously undocumented policy.
While it's debatable whether all the silent failures we currently have are
preferrable to the problem described in DPTP-1426, this at least documents the
behavior to save future-us some time.
=> private-org-sync: document merge conflict policy

cmd/pj-rehearse/main.go, cmd/pj-rehearse/server.go, pkg/rehearse/rehearse.go
When there are more than `35` jobs affected by a change it is very difficult to tell which jobs can be triggered for rehearsal. This often happens with a step-registry change. We can dump the full job list to a GCS file and share the location in the job table comment.
Example Comment: https://github.com/smg247/release/pull/48#issuecomment-1361994419
Example file: https://gcsweb-ci.apps.ci.l2s4.p1.openshiftapps.com/gcs/origin-ci-test/pj-rehearse/smg247/release/48/e672ce33686a04c5290c61dc292325edd2df3c2f.md
I also removed the `preCheck` option as there is no reason to ever have that turned off, and it was further complicating the code.
For: https://issues.redhat.com/browse/DPTP-3262
=> `pj-rehearse`: dump affected jobs list to GCS when there are more than 35 jobs affected

cmd/branchingconfigmanagers/release-controller-config-manager/.gitignore, cmd/branchingconfigmanagers/release-controller-config-manager/README.md, cmd/branchingconfigmanagers/release-controller-config-manager/main.go, cmd/branchingconfigmanagers/rpm-deps-mirroring-services/README.md, pkg/branchcuts/bumper/bumper.go, pkg/branchcuts/bumper/release-controller-config-bumper.go, pkg/branchcuts/bumper/release-controller-config-bumper_test.go, pkg/branchcuts/bumper/release-controller-types.go, pkg/branchcuts/bumper/repo-bumper.go
This is a tool that tries to automate the fourth step of phase "Before branching day" .
Check [Centralized Release Branching and Config Management V3](https://docs.google.com/document/d/1Z6ejnDCOCvNv9PWkyNPzVbjuLbDMAAT5GEeDpzb0SMs/edit#heading=h.r9xn02r1cyfn)
/cc @jmguzik @droslean
=> Before branching day: step 4

pkg/api/types.go
Introducing the vsphere 8 cluster profile to enable testing of CI jobs in the vSphere 8 environment
=> SPLAT-910: introduce vsphere 8 cluster profile

cmd/ci-operator-config-mirror/main.go, cmd/config-brancher/main.go, cmd/payload-testing-prow-plugin/filetestresolver.go, pkg/api/types.go, pkg/prowgen/prowgen.go, pkg/rehearse/jobs.go
When the `minimum_interval` field was added in https://github.com/openshift/ci-tools/pull/2980, only some of the checks were updated to include it. An important missing place is in `pj-rehearse`, where we will, consequently, not pick up any jobs that are configured with the field as being affected. In order to solve this problem permanently I have standardized the check for a test being a periodic, and replaced all usages with the new method.
For: https://issues.redhat.com/browse/DPTP-3264
=> Standardize check for periodic

pkg/rehearse/rehearse.go
It appears that `pj-rehearse` is occasionally throwing the following error:
```
pj-rehearse: failed to create rehearsal jobs ERROR: 'failed to ensure imagestreamtags in cluster build03: failed waiting for imagestreamtag ocp/4.8:elasticsearch-operator-src to appear: timed out waiting for the condition'. If the problem persists, please contact Test Platform.
```
I haven't seen it much myself, but I have no good way of knowing the frequency since we aren't also logging it. I think we should double the wait time, and also log it so I can check the frequency in a week or so and see if anything else needs to be done.
For: https://issues.redhat.com/browse/DPTP-3241
=> `pj-rehearse`: double wait for ist creation

cmd/ci-secret-bootstrap/main.go, cmd/ci-secret-bootstrap/secretstats.go, cmd/ci-secret-bootstrap/secretstats_test.go
The [job history](https://deck-internal-ci.apps.ci.l2s4.p1.openshiftapps.com/job-history/gs/origin-ci-private/logs/periodic-ci-secret-bootstrap) shows that it takes 35m to execute the job which seems quite long.
IIRC, it took about 2m when we just switch from BitWarden to Vault.
Most of the time is spent on updating the secrets on the cluster.
We want to show some stats info to understand the work.
=> ci-secret-bootstrap: log some stats of secrets

cmd/ci-secret-bootstrap/main.go, cmd/ci-secret-bootstrap/main_test.go
```
curl -s 'https://storage.googleapis.com/origin-ci-private/logs/periodic-ci-secret-bootstrap/1611087940132278272/build-log.txt?Expires=1672953333&GoogleAccessId=openshift-private%40openshift-ci-private.iam.gserviceaccount.com&Signature=MAafQFIoqlLieE7B%2BVkAv8BhBrKfjsMfF9fv2UljBm15RUpNOn%2FdEVOQdujtTstaWu2ml4jCR43L%2Bzlp68VNO0aM%2FFyPwbZmmYUInQwuLYEIdpPHr3IojtvecaCxliYlBhEdNFGXpKwIB0Cn9eTVxXmyFjbHToJYD32R%2BdvghjkyMC3%2F3jmq44v9%2B%2BuaEeGuJYIdHEPp7OUdeclX2BUCWKRywe0mKh%2FgrbRum5i9Dajs9dWmbWh8SUIpEo2eaBSsekExxupqQBB%2FOQcjOkJZBuMLkMmWjU%2FpGmIYSnx9%2FOPrfs7eONUrxWluxAinPNBQo3q9jeNTjHTGPLxSVOE8yA%3D%3D' | grep "secret updated" | wc -l
3484
```
I would like to reduce the execution time of the job.
=> secret-bootstrap: update secrets only when needed

pkg/api/types.go, pkg/api/zz_generated.deepcopy.go, pkg/prowgen/prowgen.go, pkg/prowgen/prowgen_test.go, pkg/prowgen/testdata/zz_fixture_TestGeneratePresubmitForTest_presubmit_with_always_run_false.yaml, pkg/webreg/zz_generated.ci_operator_reference.go
If there is an existing job definition then the prow job generation preserves the value of the always_run setting. However, when generating a new job it is always set to true unless forced to false by a run_if_changed or skip_if_always_changed directive in the config.
The result of this is that when copying or renaming job configs, jobs that were intended to only ever be run manually always get enabled on every PR and nobody ever notices before merging the configuration change.
Allow setting "always_run: false" in the config so that we at least have the option to set it in the config and thus have it preserved when jobs are renamed or duplicated.
=> Allow setting always_run in the ci-operator config

cmd/ci-operator-yaml-creator/main_test.go, cmd/publicize/server_test.go
These unit tests started failing locally for me recently. Apparently, some git update I made defaulted the initial branch to `main` rather than `master`. We can just specify the initial branch as `master` to resolve this.
=> Specify initial `localgit` branch

cmd/repo-init/main.go, cmd/repo-init/main_test.go
Currently, when a plugin is listed in the `openshift/origin` plugin config, it will be added to a newly configured repo's config as well. This works as long as that same plugin isn't listed in the org's config file (assuming one exists). If that is the case it results in an error while attempting to load the plugin config in `determinize-prow-config` like:
```
level=fatal msg="could not update Prow plugin configuration" error="could not load Prow plugin configuration: plugins [approve] are duplicated for openshift-assisted/assisted-grafana and openshift-assisted"
```
In order to resolve this when a plugin config for the repo's org exists, we should prune each of those configured plugins out of the resulting list.
For: https://issues.redhat.com/browse/DPTP-3222
=> `repo-init`: don't duplicate plugins that are already configured at the org level

cmd/dptp-pools-cm/main.go
I forgot to do it in https://github.com/openshift/ci-tools/pull/3228
It led to (with `--enable-controller=hypershift_namespace_reconciler`):
```
{"component":"dptp-pools-cm","error":"the following controllers are unknown but were disabled via --disable-controller: [hypershift_namespace_reconciler]","file":"/go/src/github.com/openshift/ci-tools/cmd/dptp-pools-cm/main.go:78","func":"main.main","level":"fatal","msg":"Failed to get options","severity":"fatal","time":"2023-01-06T21:41:33Z"}
```
=> dptp-pools-cm: recognize controller hypershift_namespace_reconciler

cmd/cluster-display/main.go, cmd/cluster-display/main_test.go
Updated error handling so that if there's an error regarding one cluster, the error is logged, and the rest of the clusters are _not_ skipped.
for https://issues.redhat.com/browse/DPTP-3086
/cc smg247
=> cluster-display: update error handling for cluster list

pkg/steps/index_generator.go
https://issues.redhat.com/browse/DPTP-2969
/cc @openshift/test-platform @joelanford @grokspawn 
/hold
This should not go in before the PR on the ci-docs is ready.
=> oo testing: skip building index images when file-based index is used

pkg/jobrunaggregator/cmd.go, pkg/jobrunaggregator/jobrunaggregatorlib/gcs_client.go, pkg/jobrunaggregator/jobrunaggregatorlib/jobrun_locator.go, pkg/jobrunaggregator/jobrunbigqueryloader/alert.go, pkg/jobrunaggregator/jobrunbigqueryloader/disruption.go, pkg/jobrunaggregator/jobrunbigqueryloader/test_run_uploader.go, pkg/jobrunaggregator/jobrunbigqueryloader/uploader.go
Jobs are locking up, we would like timestamp information to be able to
start debugging where when and why.
There was some inconsistent use of logrus in here already but mostly
just fmt.Prints.
Rough attempt at structured contextual logging.
=> First pass at logging improvements for job run analyzer

cmd/prow-job-dispatcher/main.go, cmd/prow-job-dispatcher/main_test.go, pkg/dispatcher/config.go, pkg/dispatcher/config_test.go
- revert https://github.com/openshift/ci-tools/commit/ef2a28d87bc879fdc3f1bdd27a890c6da4be3544
-  remove `IgnoreE2EByJobAssignment`
- change the way clusters are added and deleted 
- add get HTTP to know provider
=> Change the way clusters are disabled during failover

pkg/rehearse/jobs.go, pkg/rehearse/jobs_test.go, pkg/rehearse/rehearse.go
I was looking through error logs following https://github.com/openshift/release/blob/master/docs/dptp-triage-sop/logs/README.md, and noticed some errors that `pj-rehearse` is throwing. These aren't actually platform level errors and should simply be logged at the `info` level.
=> `pj-rehearse`: change logging to info for non-platform errors

pkg/jobrunaggregator/jobrunaggregatorlib/big_query.go, pkg/jobrunaggregator/jobrunaggregatorlib/gcs_client.go, pkg/jobrunaggregator/jobrunbigqueryloader/alert.go, pkg/jobrunaggregator/jobrunbigqueryloader/cmd.go, pkg/jobrunaggregator/jobrunbigqueryloader/disruption.go, pkg/jobrunaggregator/jobrunbigqueryloader/test_run_uploader.go, pkg/jobrunaggregator/jobrunbigqueryloader/uploader.go
[TRT-772](https://issues.redhat.com//browse/TRT-772)
Upload jobs for alerts, disruption, and test runs are all seemingly locking up in dpcr cluster. Logs stop, pod stays running forever.
In debugging the lockups in the uploader jobs, I found that removing the top level of concurrency, which appears to be queuing up every job unbounded and attempting to process them all as fast as the cpu can, the problem went away.  Upload times then got a little too long particularly for the test runs without any concurrency though.
This change adds a new implementation for concurrency at the job level bounding to 10 goroutines pulling from a channel until there's nothing left.
Note that there is a second layer of concurrency at the job run level, where we limit to 20 concurrent uploads. I think this …
=> Limit concurrency of bigquery job uploads, fix memory spikes

Makefile
```console
$ make local-e2e
[…]
--- FAIL: TestMultiStage (0.00s)
--- FAIL: TestMultiStage/e2e-claim-as-custom (1.15s)
[…]
ERRO[2023-01-16T17:26:07Z] Failed to load arguments.                     error=could not load Hive kube config from path /tmp/hive-kubeconfig: could not load client configuration: open /tmp/sa.hive.hive.token.txt: no such file or directory
[…]
```
=> Makefile: add Hive token target for `local-e2e`

pkg/junit/types.go, pkg/junit/types_test.go, test/e2e/observer/artifacts/failing-observer-junit_operator.xml, test/e2e/observer/artifacts/multi-observers-junit_operator.xml, test/e2e/observer/artifacts/simple-observer-junit_operator.xml, test/e2e/simple/artifacts/junit_operator.xml
[TRT-789](https://issues.redhat.com//browse/TRT-789)
TestSuite properties should be `properties` not `property`, we can't
unmarshal some junits in the job run uploader currently, it errors out
like this:
```
time="2022-07-06T08:01:16Z" level=fatal msg="Command failed"
error="[jobrun/release-openshift-ocp-osd-aws-nightly-4.11/1544457393197289472
failed to upload to bigquery: error parsing junit for
jobrun/release-openshift-ocp-osd-aws-nightly-4.11/1544457393197289472
\"logs/release-openshift-ocp-osd-aws-nightly-4.11/1544457393197289472/artifacts/install/junit_0zg9j.xml\":
testsuiteError=expected element type <testsuite> but have <testsuites>
testsuitesError=expected element type <property> but have <properties>,
jobrun/release-openshift-ocp-osd-aws-nightly-4.10/1544448209282142208
failed …
```
=> junit: fix xml.Name for testsuite properties

cmd/pj-rehearse/server.go
I've noticed a couple of PRs recently which were opened with a merge conflict or some other issue causing `pj-rehearse` to not give usage detail on the initial comment. We should make sure that the `/pj-rehearse refresh` command also shows the usage details.
=> `pj-rehearse`: add usage details to the response from refresh command

pkg/util/testgrid.go
[TRT-794](https://issues.redhat.com//browse/TRT-794)
This adds
periodic-ci-openshift-cluster-control-plane-machine-set-operator-* to testgrid and sippy for data collection. It also alphabetizes the list.
=> Add cluster-control-plane-machine-set-operator to sippy/testgrid

cmd/promoted-image-governor/main.go
It would be useful to log the `err` when the client failed to delete the ImageStream.
It helps troubleshooting [this sort of failures](https://storage.googleapis.com/origin-ci-test/logs/periodic-promoted-image-governor/1618873998358089728/build-log.txt)
=> promoted-image-governor: log err when unable to delete an IS

cmd/promoted-image-governor/main.go
https://prow.ci.openshift.org/view/gs/origin-ci-test/logs/periodic-promoted-image-governor/1618988937689174016#1:build-log.txt%3A70425
```
{"component":"promoted-image-governor","file":"/go/src/github.com/openshift/ci-tools/cmd/promoted-image-governor/main.go:538","func":"main.main","level":"info","msg":"deleting tag","severity":"info","tag":"cnv/4.10:src-upgrade-ci","time":"2023-01-27T15:11:13Z"}
{"component":"promoted-image-governor","file":"/go/src/github.com/openshift/ci-tools/cmd/promoted-image-governor/main.go:549","func":"main.main","level":"info","msg":"image stream tag is deleted","severity":"info","tag":"cnv/4.10:src-upgrade-ci","time":"2023-01-27T15:11:13Z"}
{"component":"promoted-image-governor","file":"/go/src/github.com/openshift/ci-tools/cmd/promoted-image-governor/main.go:5 …
```
=> promoted-image-governor: do not log succecss deleting on errors

pkg/steps/release/promote.go, pkg/steps/release/testdata/zz_fixture_TestGetPromotionPod_basic_case.yaml
```console
oc get istag -n ocp 4.12:cli
NAME       IMAGE REFERENCE                                                                                                                     UPDATED
4.12:cli   image-registry.openshift-image-registry.svc:5000/ocp/4.12@sha256:f93a29f8d7455a5067ecde85394835bda877174193ab693b2b010d96c8cd9183   6 weeks ago
```
=> Use ocp/4.12:cli to promote images

pkg/branchcuts/bumper/release-controller-config-bumper.go, pkg/jobrunaggregator/jobrunaggregatorapi/types_row_jobrun.go, pkg/jobrunaggregator/jobrunaggregatorlib/ci_data_client.go, pkg/jobrunaggregator/jobrunaggregatorlib/gcs_client.go, pkg/jobrunaggregator/jobrunaggregatorlib/retrying_ci_data_client.go, pkg/jobrunaggregator/jobrunbigqueryloader/alert.go, pkg/jobrunaggregator/jobrunbigqueryloader/cmd.go, pkg/jobrunaggregator/jobrunbigqueryloader/disruption.go, pkg/jobrunaggregator/jobrunbigqueryloader/test_run_uploader.go, pkg/jobrunaggregator/jobrunbigqueryloader/uploader.go, pkg/jobrunaggregator/jobruntestcaseanalyzer/cidataclient_test.go
After on-going problems with deadlocks, we decided to rewrite the top layer of the importers for alert, disruption, and test run data that is being uploaded into bigquery. 
This PR replaces all the concurrency code, and switches from discovering job runs via scanning GCS buckets to instead querying the bigquery table testplatform uploads all prowjobs to. 
We limit to 10 concurrent goroutines, each of which can be pulling from GCS or inserting in bigquery. 
The change relies on job run end times now, we lookup the last job run end time we inserted at the start, then query the testplatform prowjobs for any that ended since then, plus a 30 minute buffer. The code additinally lists all the prowjobs we already uploaded since that 30 minute buffer time, to avoid duplicate detection. (we do …
=> Use Testplatform BigQuery for ProwJobs to upload alert/disruption/test data from

cmd/payload-testing-ui/server.go
First PR for this task. Where I changed names of jobs to more readable form. Added requestor without link for now.
Added link for docs, release controller and its config.
I will continue with link comment to Requestor: [like here](https://github.com/openshift/ci-tools/pull/2902/commits/4050b31e6f14e984ee85c691d58fef062fb0fbb7)
[DPTP-2641](https://issues.redhat.com/browse/DPTP-2641)
/cc @bbguimaraes
=> payload-testing: renamed jobs name, add requestor, link to docs, links for release controller and its config

cmd/image-graph-generator/main.go, pkg/image-graph-generator/images.go, pkg/image-graph-generator/manifests.go, pkg/image-graph-generator/mirror_mappings.go, pkg/image-graph-generator/operator.go
The tool now gets only the release repo path as a flag and hardcodes the required subdir that we need to operate on. We now read all YAML files in `clusters/app.ci` directory and load all `ImageStream` and `BuildConfigs`. 
/cc @danilo-gemoli @openshift/test-platform 
=> Include operating on manifests and create the corresponding images to the graph

pkg/jobrunaggregator/jobrunaggregatorapi/types_row_historical_data.go, pkg/jobrunaggregator/jobrunaggregatorlib/ci_data_client.go
- Include JobRuns count in alerts query results
- Stop limiting the alerts we send to origin for testing
- Send alert namespace and level in data file for origin
- Fix alert comparisons when generating the weekly PR
I think this will actually work ok in origin even as it is now, but I do expect to have the origin PR up well before the Friday update, so I think this is safe to merge any time. The origin PR will include a new copy of query_results.json so it works.
[TRT-769](https://issues.redhat.com//browse/TRT-769)
=> Update alert data to include more alerts, namespaces and levels, and the number of job runs that hit that combo

cmd/entrypoint-wrapper/main.go, pkg/steps/multi_stage/gen.go, pkg/steps/multi_stage/testdata/zz_fixture_TestGenerateObservers.yaml, pkg/steps/multi_stage/testdata/zz_fixture_TestGeneratePods.yaml
Installer could make multiple updates to kubeconfig during the install process. Some steps like observers will like to get the kubeconfig as soon as it is minimally functioning. In https://github.com/openshift/release/pull/35992, the install step will copy the minimally functioning kubeconfig to kubeconfig-minimal and export KUBECONFIGMINIMAL for pods. I did not create a temporary kubeconfig-minimal for each pod as I do not expect this to be modified. But if it is needed, I can update the PR with that. 
[TRT-761](https://issues.redhat.com/browse/TRT-761)
=> Copy kubeconfig-minimal as soon as it is available for observers

cmd/entrypoint-wrapper/main.go, pkg/steps/multi_stage/gen.go, test/integration/entrypoint-wrapper.sh
Newer versions of Git refuse to interact with a repository owned by another
user, independently of file permissions.  This is a problem in CI since
source code is usually cloned by UID 0 and read by unprivileged users.
With this change, `entrypoint-wrapper` creates a Git configuration file in
the home directory if it does not already exist (n.b.: this directory is
already provided as a temporary `EmptyDir` volume to `entrypoint-wrapper`
in multi-stage tests).  This file will disable the ownership verification
using the following entry:
[safe]
directory = *
Tests which want to have better control over their configuration can
rewrite this file or use one of the other configuration methods in Git:
- https://git-scm.com/docs/git-config.html#FILES
- …
=> entrypoint-wrapper: create Git configuration

cmd/entrypoint-wrapper/main.go, test/integration/entrypoint-wrapper.sh
This was missed in https://github.com/openshift/ci-tools/pull/3292 since CI was
not working at that time and these tests pass locally.
e.g.: https://prow.ci.openshift.org/view/gs/origin-ci-test/pr-logs/pull/openshift_ci-tools/3282/pull-ci-openshift-ci-tools-master-integration/1625502343464226816
Unit tests will fail as expected, this only corrects integration tests.
=> Fix `entrypoint-wrapper` integration tests

pkg/steps/multi_stage/testdata/zz_fixture_TestGenerateObservers.yaml, pkg/steps/multi_stage/testdata/zz_fixture_TestGeneratePods.yaml, pkg/steps/testdata/zz_fixture_TestPodStepExecution_Pod_run_by_PodStep_fails_so_PodStep_terminates_and_returns_an_error.yaml, pkg/steps/testdata/zz_fixture_TestPodStepExecution_Pod_run_by_PodStep_succeeds_so_PodStep_terminates_and_returns_no_error.yaml, pkg/steps/testdata/zz_fixture_TestPodStepExecution_Successful_pod_with_cloning.yaml, pkg/steps/testdata/zz_fixture_envTestGetPodObjectMounts_with_cluster_claim.yaml
This corrects the test failures after the changes introduced in
https://github.com/openshift/ci-tools/pull/3293, when CI was not functioning to
block it.
=> pkg/steps: fix unit tests

pkg/jobrunaggregator/jobrunaggregatorapi/types_row_historical_data.go, pkg/jobrunaggregator/jobrunaggregatorlib/ci_data_client.go, pkg/jobrunaggregator/jobrunhistoricaldataanalyzer/util.go
We recently expanded the alert data file to include namespace and level. 
Origin is being updated to skip anything in the data file with less than 100 job runs, but previously we actually filtered them out entirely via the query, at least for disruption. 
This change makes disruption include them as well, to be consistent. It will be up to origin to decide what to enforce.
This also updates the PR message to show the new data for alerts, and hide rows from the tables with less than 100 runs, as we do not care to see whether they are up or down.
[TRT-769](https://issues.redhat.com//browse/TRT-769)
=> remove disrupt 100 run filter

test/integration/entrypoint-wrapper.sh
While I cannot make this test fail on my machine even after executing it
continuously for hours, _everything_ is possible in CI: we see cases where
apparently one process does not get scheduled quickly enough and the existing
error margin is not enough:
- https://prow.ci.openshift.org/view/gs/origin-ci-test/pr-logs/pull/openshift_ci-tools/3282/pull-ci-openshift-ci-tools-master-integration/1625825839356579840
- https://prow.ci.openshift.org/view/gs/origin-ci-test/pr-logs/pull/openshift_ci-tools/3282/pull-ci-openshift-ci-tools-master-integration/1625841861811769344
This change makes the failure case more explicit and very scientifically
increases the timeout to five seconds.
=> entrypoint-wrapper: make int. test more reliable

.gitignore, cmd/testgrid-config-generator/main.go
This change adds support to `testgrid-config-generator` to provide the ability to auto create dashboards in test grid for OpenShift layered product interoperability testing. For every OpenShift release throughout the development/testing phases, layered products verify their interoperability on the unreleased OpenShift release. This testing ensures we maintain a healthy Red Hat portfolio of products on top of OpenShift. Reducing bugs customers may face when they upgrade their OpenShift cluster to the next available version (allowing their running layered products to be unaffected).
The change to testgrid-config-generator adds new case statements checking prow job names for a unique string `lp-interop` which indicate jobs are layered product interop testing.
Since there are 30+ layered …
=> Support creating testgrid dashboards automatically for openshift layered product interop testing

pkg/jobrunaggregator/jobrunaggregatoranalyzer/pass_fail.go
This will result in higher required passes for aggregated disrution tests.
[TRT-867](https://issues.redhat.com/browse/TRT-867)
=> Change adjustment for required passes from -2 to -1

test/e2e/simple/dynamic-releases.yaml
This is currently causing tests to fail, e.g.:
```
INFO[2023-03-02T09:48:30Z] Requesting a release from https://amd64.origin.releases.ci.openshift.org/api/v1/releasestream/4.3.0-0.okd/latest
INFO[2023-03-02T09:48:30Z] Ran for 0s
ERRO[2023-03-02T09:48:30Z] Some steps failed:
ERRO[2023-03-02T09:48:30Z]
* failed to generate steps from config: failed to resolve release initial: failed to request latest release: server responded with 404: no release configuration exists with the requested name
```
https://prow.ci.openshift.org/view/gs/origin-ci-test/pr-logs/pull/openshift_ci-tools/3281/pull-ci-openshift-ci-tools-master-e2e/1631222115392819200
```console
$ curl -sS https://amd64.origin.releases.ci.openshift.org/api/v1/releasestream/4.3.0-0.okd/latest
no release configuration exists with the …
```
=> test/e2e: use latest OCP releases

pkg/api/types.go
The MSI (managed services integration) team requires a dedicated cluster profile for spinning up openshift clusters using our AWS account.  The profile will be used for add-ons, services, and layered products testing on ROSA and Hypershift.
=> Create a dedicated aws cluster profile for managed aws cspi qe

cmd/ci-operator/main.go, pkg/defaults/defaults.go, pkg/defaults/defaults_test.go, pkg/steps/build_client.go, pkg/steps/bundle_source.go, pkg/steps/git_source.go, pkg/steps/index_generator.go, pkg/steps/index_generator_test.go, pkg/steps/project_image.go, pkg/steps/rpm_injection.go, pkg/steps/source.go, pkg/steps/source_test.go
/cc @openshift/test-platform @bbguimaraes 
1. Add the node architectures in the build client
2. We now add a nodeSelector to every build to specify the node with the desired architecture. E.x `kubernetes.io/arch: amd64` 
3. Spawn a build for each architecture for each image.
=> Operate on builds based on the list of architectures supported in the cluster

pkg/rehearse/jobs.go
We have this warning in our logs, but now that this is a plugin it shouldn't be warning level.
=> `pj-rehearse`: downgrade useless warning to debug

pkg/api/types.go
Specific vSphere jobs must run in the IBM vSphere 7 environment.  This cluster profile will allow those jobs to be specifically scheduled in that environment.
=> SPLAT-980: introduce vSphere IBM 7 dedicated lease slice

cmd/config-change-trigger/main.go, pkg/config/release.go, pkg/rehearse/rehearse.go
We were logging errors from loading the release configuration, but not actually bubbling them up so that the user could see them. This change throws errors instead of just logging them. The existing error commenting logic will take it from there.
I also cleaned up some of the areas where we were mistakenly wrapping a nil error.
For: https://issues.redhat.com/browse/DPTP-3311
=> `pj-rehearse`: properly bubble up errors from loading configuration

pkg/api/types.go, pkg/defaults/defaults.go, pkg/defaults/defaults_test.go, pkg/validation/config.go, pkg/validation/config_test.go, pkg/webreg/zz_generated.ci_operator_reference.go
Reverts openshift/ci-tools#3327
It seems that the steps are smart enough to skip the index build if it is not needed.
https://prow.ci.openshift.org/view/gs/origin-ci-test/pr-logs/pull/openshift_release/37236/rehearse-37236-pull-ci-rh-ecosystem-edge-kernel-module-management-main-e2e-in-cluster-build/1635371934931750912
We do not need to specify it explicitly at all.
/cc @smg247
=> Revert "oo-testing: opt out building index image"

cmd/pod-scaler/admission.go, cmd/pod-scaler/admission_test.go
Makes the workload name used in the `pod_scaler_admission_high_determined_resource` prometheus metric more meaningful in case the workload is a prowjob.
Before, the workload name would be something like `a06d0538-c4dd-11ed-9b5b-0a580a8005dc-test`. Now it will provide the actual name of the prowjob, using the `prow.k8s.io/job` label.
=> Pod-scaler admission: Better prow job names

pkg/jobrunaggregator/jobrunhistoricaldataanalyzer/analyzer.go, pkg/jobrunaggregator/jobrunhistoricaldataanalyzer/cmd.go
We'd always assumed that branch point became permanent for disruption data, but this did not hold up for 4.13 when we had to merge a known regression after branching.
This adds support for a --target-release option on the command to override the normal lookup of the most recent release.
I have not updated the dev focused local hack/job-run-aggregator-analyzer.sh as it would cause logic explosion the way it's currently working and I don't know enough bash to avoid that. This would be used with a direct invocation today or manually hacking up the script locally.
[TRT-911](https://issues.redhat.com//browse/TRT-911)
=> Add support for updating alert/disruption data for a past release.

pkg/api/types.go
- Fix the dedicated quota slice for AWS Local Zones introduced on https://github.com/openshift/ci-tools/pull/3336 and https://github.com/openshift/release/pull/37543
- Remove the ConfigMap (not expected to be used)
Periodic that will be used in this profile: https://github.com/openshift/release/pull/36911
=> SPLAT-728: fix/adding dedicated quota slice to the aws-local-zones

pkg/controller/prpqr_reconciler/prpqr_reconciler.go, pkg/controller/prpqr_reconciler/testdata/zz_fixture_prowjobs_TestReconcile_basic_aggregated_case.yaml
There is no guarantee that this will actually work, but we are unsure of a decent way to test this idea without merging it and trying to run one. The possible consequence could be that each test overwrites the last, and only one actual test is run. We will merge this and find out if that happens, or if it functions as desired.
/hold to rollout when we can test
=> Remove index from input-hash to facilitate a single build for aggregated jobs

pkg/controller/prpqr_reconciler/prpqr_reconciler.go, pkg/controller/prpqr_reconciler/testdata/zz_fixture_prowjobs_TestReconcile_basic_aggregated_case.yaml
Didn't quite work, we need to find a way to differentiate the individual tests still.
Reverts openshift/ci-tools#3340
=> Revert "Remove index from input-hash to facilitate a single build for aggregated jobs"

pkg/controller/prpqr_reconciler/prpqr_reconciler.go, pkg/controller/prpqr_reconciler/testdata/zz_fixture_prowjobs_TestReconcile_basic_aggregated_case.yaml
Attempt number 2 of testing this out. The issue with the original attempt is that the job names were all the same and they weren't able to run in the same namespace. This will ensure that they are different. We could still face issues with resolving the jobs in the aggregator job, but this trial will show us exactly where those issues are.
/cc @jmguzik
=> One build for aggregate payload jobs

pkg/jobrunaggregator/jobtableprimer/generate_jobnames.go, pkg/jobrunaggregator/jobtableprimer/generated_job_names.txt
This auto generation job fails due to changes in some file names. Updating the existing file name, and added recent release versions.
- Updating the file names for `generate-jobnames` subcommand.
- Ran subcommand to update current file names.
/assign @stbenjam 
/cc @deads2k @xueqzhan
=> Update generated jobnames files

cmd/pj-rehearse/server.go
The [error](https://github.com/openshift/release/pull/37779#issuecomment-1488826394) still doesn't quite look right. We need a new line after closing the pre-formatted block.
=> `pj-rehearse`: fix error comment format

pkg/prowgen/podspec.go, pkg/prowgen/podspec_test.go, pkg/prowgen/testdata/zz_fixture_TestTargetAdditionalSuffix_target_additional_suffix_is_added.yaml
Follow up to: https://github.com/openshift/ci-tools/pull/3354. We need a function to help us actually set this argument.
=> `ci-operator`: Add helper to set target-additional-suffix

pkg/controller/prpqr_reconciler/prpqr_reconciler.go, pkg/controller/prpqr_reconciler/testdata/zz_fixture_prowjobs_TestReconcile_basic_aggregated_case.yaml, pkg/prowgen/podspec.go, pkg/prowgen/podspec_test.go, pkg/prowgen/testdata/zz_fixture_TestTargetAdditionalSuffix_target_additional_suffix_is_added.yaml
The third attempt at a solution for this. This time we will use a newly added `ci-operator` option to add a suffix to the in-process target for each test. This will allow them to be differentiated so that secrets (and other things) don't collide. Hopefully, this will get us past that part and we can discover any other problems we may have here.
/hold require https://github.com/openshift/ci-tools/pull/3355
=> One build for aggregate jobs (v. 3)

pkg/steps/release/import_release.go
bee450bd5d (#1098) taught `assembleReleaseStep` to consume the `release.openshift.io/config` annotation on an ImageStream to find a version prefix that actually reflects the 4.y release branch (instead of using `0.0.1-0` as the prefix).  Those annotations are set on the `app.ci` ImageStreams, for example:
```console
$ oc whoami -c
default/api-ci-l2s4-p1-openshiftapps-com:6443/wking
$ oc -n ocp get -o json imagestream 4.13 | jq -r '.metadata.annotations["release.openshift.io/config"] | fromjson | .name'
4.13.0-0.ci
```
But they are not set in ImageStreams contained within release images:
```console
$ oc adm release info -o json registry.ci.openshift.org/ocp/release:4.13.0-0.ci-2023-03-29-224346 | jq '.references | {kind, metadata}'
{
"kind": "ImageStream",
"metadata": {
"name": …
```
=> OTA-925: pkg/steps/release/import_release: Set release.openshift.io/config name annotation

pkg/api/types.go
Added two new leases for Power VS. Once they're present in openshift/release, we should be able to proceed with updating our jobs to use these, and then follow up with the removal of the old lease via https://github.com/openshift/ci-tools/pull/3352.
=> Add new Power VS leases to control zoning

pkg/jobrunaggregator/jobtableprimer/generate_jobnames.go, pkg/jobrunaggregator/jobtableprimer/generated_job_names.txt
Reverts openshift/ci-tools#3344
This has picked up new jobs that are not getting tracked properly, and started throwing off our disruption graphs at a time when we're chasing a number of disruption problems.
While nothing technically wrong with this PR, the problem is really in the ingestion code, we need to revert to stay focused on our current issues.
=> Revert "Update generated jobnames files"

pkg/jobrunaggregator/jobtableprimer/generate_jobnames.go, pkg/jobrunaggregator/jobtableprimer/generated_job_names.txt
release hypershift no longer contains https://raw.githubusercontent.com/openshift/release/master/ci-operator/jobs/openshift/hypershift/openshift-hypershift-main-periodics.yaml due to name change, this PR updates the reference and job names to point to new 4.13 and 4.14 periodics files.
See https://issues.redhat.com/browse/TRT-947 For reference
/assign @dgoodwin
=> fix: update to ref 4.13 and 4.14 hypershift file

pkg/jobrunaggregator/jobrunaggregatoranalyzer/analyzer_disruption.go
Reverts openshift/ci-tools#3317
We are past the point of needing to allow azure disruption to pass through unchecked.  Reverting.
=> Revert "Skip disruption aggregation for azure jobs for now"

pkg/api/types.go
Recently, we switched from powervs to powervs-1
and powervs-2.  Now we need to cleanup the old
powervs.
=> PowerVS: remove old powervs

pkg/api/types.go
nutanix disconnected profile missed to add `ClusterProfileNutanixQEDis`, fix it.
=> fix nutanix disconnected profile

pkg/controller/prpqr_reconciler/prpqr_reconciler.go, pkg/controller/prpqr_reconciler/prpqr_reconciler_test.go, pkg/controller/prpqr_reconciler/testdata/zz_fixture_prowjobs_TestReconcile_basic_aggregated_case.yaml, pkg/controller/prpqr_reconciler/testdata/zz_fixture_prowjobs_TestReconcile_basic_case.yaml, pkg/controller/prpqr_reconciler/testdata/zz_fixture_prowjobs_TestReconcile_basic_case_with_metal_override.yaml, pkg/controller/prpqr_reconciler/testdata/zz_fixture_prowjobs_TestReconcile_basic_case_with_variant.yaml, pkg/controller/prpqr_reconciler/testdata/zz_fixture_prowjobs_TestReconcile_basic_case_with_vsphere_override.yaml, pkg/controller/prpqr_reconciler/testdata/zz_fixture_prowjobs_TestReconcile_multiple_case__one_of_the_prowjobs_already_exists.yaml
This time we will be sure to add the aggregate index to the cluster-profile secret to avoid the following error:
```
could not run steps: step e2e-aws-sdn-serial-1 failed: could not get cluster profile secret "e2e-aws-sdn-serial-1-cluster-profile": secrets "e2e-aws-sdn-serial-1-cluster-profile" not found
```
/cc @jmguzik
=> One build for payload aggregate command (v.5)

cmd/pj-rehearse/main.go, cmd/pj-rehearse/server.go
There is actually an event (synchronize) for a new push to a PR. We can utilize it to perform the refreshing of the affected job list automatically when a PR is pushed to. This will also remove the `rehearsals-ack` label if it is present and there is a new push (mimicking the `lgtm` functionality). Additionally, it will now delete any older job list comments so there is always only one on a PR.
There will be a follow up PR to remove the info about `/pj-rehearse refresh` from the docs, and I will announce this functionality change prior to merging.
For: [DPTP-3393](https://issues.redhat.com/browse/DPTP-3393)
=> `pj-rehearse` use the synchronize event to auto refresh job list

pkg/api/domain.go, pkg/api/domain_test.go, pkg/api/types.go
After https://github.com/openshift/release/pull/37563 the `multi01` cluster is now in the CI farm. 
This PR allows `dptp-controller` to resolve the registry domain for `multi01` cluster
=> include multi01 cluster on registry domain resolving

cmd/ci-operator/main.go, pkg/defaults/defaults.go, pkg/defaults/defaults_test.go, pkg/steps/multi_stage/gen_test.go, pkg/steps/multi_stage/multi_stage.go, pkg/steps/multi_stage/multi_stage_test.go, pkg/steps/multi_stage/run_test.go
The additional suffix is currently part of the cluster profile secret name when present. This secret needs to be shared among all iterations of the test, and should not be duplicated. Therefore, the suffix should be trimmed off to resolve the secret. This will prevent errors like the following when using the `target-additional-suffix` param:
```
could not run steps: step e2e-aws-sdn-serial-1 failed: could not get cluster profile secret "e2e-aws-sdn-serial-1-cluster-profile": secrets "e2e-aws-sdn-serial-1-cluster-profile" not found
```
=> `ci-operator`: trim target-additional-suffix from profile secret name

pkg/steps/source.go, pkg/steps/source_test.go
It can be difficult to identify when builds are reused based on the main
output:
```
…
INFO[2023-04-20T13:18:59Z] Building failure
INFO[2023-04-20T13:19:31Z] Build failure failed, printing logs:
…
STEP 3/5: RUN false
error: build error: error building at STEP "RUN false": error while running runtime: exit status 1
INFO[2023-04-20T13:19:32Z] Ran for 44s
ERRO[2023-04-20T13:19:32Z] Some steps failed:
ERRO[2023-04-20T13:19:32Z]
* could not run steps: step failure failed: error occurred handling build failure: the build failure failed after 32s with reason DockerBuildFailed: Dockerfile build strategy has failed.
…
```
Other than a few accidental log messages from the build environment, there is
no temporal information in the build logs.  This is especially problematic for
permanent failures …
=> pkg/steps: emit detailed build errors in debug log

images/private-org-sync/Dockerfile
This is an attempt to solve errors like:
remote: fatal: did not receive expected object XXXXXXXX
error: remote unpack failed: index-pack failed
see https://deck-internal-ci.apps.ci.l2s4.p1.openshiftapps.com/?job=periodic-openshift-release-private-org-sync 
/cc @openshift/test-platform @smg247 
=> apply global git configuration to private-org-sync Dockerfile

cmd/private-org-sync/main.go
Fixes the periodic-openshift-release-private-org-sync job.
The tool has a way to determine when it should try to fetch a deeper commit history. Newer git versions seem to generate more errors that we didn't include in the cases. This PR just adds the case we are hitting in the job and allows the tool to retry with a deeper commit history.
=> [private-org-sync] update potential errors to try to fetch a deeper history

pkg/jobrunaggregator/jobrunaggregatorapi/types_row_backenddisruption.go, pkg/jobrunaggregator/jobrunaggregatorlib/disruption.go, pkg/jobrunaggregator/jobrunbigqueryloader/disruption.go
Includes MasterNodesUpdated flag in BackendDisruptionRow uploaded to BigQuery to differentiate between jobs that triggered node updates and those that don't.
=> trt-945: support MasterNodesUpdated indicator

pkg/jobrunaggregator/jobrunaggregatorapi/types_row_backenddisruption.go, pkg/jobrunaggregator/jobrunaggregatorlib/disruption.go, pkg/jobrunaggregator/jobrunbigqueryloader/disruption.go
Reverts openshift/ci-tools#3397
Seeing:
time="2023-04-28T12:01:01.916Z" level=error msg="error encountered during upload" error="jobrun/periodic-ci-openshift-release-master-nightly-4.13-e2e-aws-sdn-upgrade/1651882596604317696 failed to upload to bigquery: 22 row insertions failed (insertion of row [insertID: \"LlXlxhtRMFdmGlr6pZAxTddc97V\"; insertIndex: 0] failed with error: {Location: \"MasterNodesUpdated\"; Message: \"no such field: MasterNodesUpdated.\"; Reason: \"invalid\"}, insertion of row [insertID: \"A0fmGF69DgvRbcPpxzsVhhnw2ME\"; insertIndex: 1] failed with error: {Location: \"MasterNodesUpdated\"; Message: \"no such field: MasterNodesUpdated.\"; Reason: \"invalid\"}, insertion of row [insertID: \"pvs6R4NaOVmRFWU9diwXBTcNzZ7\"; insertIndex: 2] failed with error: {Location: …
=> Revert "trt-945: support MasterNodesUpdated indicator"

test/e2e/multi-stage/e2e_test.go
This test is meant to cause a pending timeout using a non-existent image.  It
works as intended, but it intentionally uses a short timeout period so that it
executes quickly.  It may happen that the timeout happens for other reasons
(this is after all what the actual verification is meant to detect), leading to
test failures such as the one seen here:
https://github.com/openshift/ci-tools/pull/3390#issuecomment-1520443642
Since the reason for the delay is not relevant for this test, only that it be
detected and properly reported, this change relaxes the error message searched
in the logs such that any pending situation satisfies the test.
=> test/e2e: relax pending test check

pkg/api/types.go
The CSPI QE team would like to create a new cluster profile to attempt using the [VPN capabilities built in to OpenShift CI](https://docs.google.com/document/d/1mPjrHVS1EvmLdq4kGhRazTpGu6xVZDyGpVAphVZhX4w/edit?resourcekey=0-KA-qXXq1J2bTR7o6Kit9Vw#heading=h.x9snb54sjlu9)
**Related PRs**
- [openshift/release #38901](https://github.com/openshift/release/pull/38901)
=> [LPTOCPCI-210] Add New aws-cspi-qe-vpn Cluster Profile

Makefile, cmd/sync-rover-groups/ldap.go, cmd/sync-rover-groups/ldap_test.go, cmd/sync-rover-groups/main.go
This is the first step of https://issues.redhat.com/browse/DPTP-3436
Uploading data to bigquery will be within another tool since `sync-rover-groups` runs on psi.
We need to keep things simple as before: output a file and create CM with the file on `app.ci`.
/cc @jupierce
=> sync-rover-groups: collect users' cost center

pkg/controller/prpqr_reconciler/prpqr_reconciler.go
just like any job with `metal` in the name, the `telco5g` jobs need to run on `build05` in order to have any chance at succeeding.
=> `payload-testing`: force telco5g jobs to build05

cmd/github-ldap-user-group-creator/main.go, cmd/sync-rover-groups/ldap.go, cmd/sync-rover-groups/main.go, pkg/rover/bigquery.go, pkg/rover/types.go
https://issues.redhat.com/browse/DPTP-3436
I modify the table schema: `created`: Mode (`NULLABLE`) with a default value of `CURRENT_DATETIME()`.
It was `REQUIRED`.
We do not need to specify the value upon inserting.
---
Update: Redefined table schema. `created` is back to Required but as type TIMESTAMP which seems more GoLang friendly.
Tested with running the tool locally for 2 batches: `created` is the same `now` for every record in the batch. "This is for trivial pruning".
/hold
Need to change the job spec accordingly.
/cc @jupierce
=> github-ldap-user-group-creator: upload users to bigquery

pkg/controller/prpqr_reconciler/prpqr_reconciler.go, pkg/controller/prpqr_reconciler/prpqr_reconciler_test.go, pkg/controller/prpqr_reconciler/testdata/zz_fixture_prowjobs_TestReconcile_basic_aggregated_case.yaml, pkg/controller/prpqr_reconciler/testdata/zz_fixture_prowjobs_TestReconcile_basic_case.yaml, pkg/controller/prpqr_reconciler/testdata/zz_fixture_prowjobs_TestReconcile_basic_case_with_metal_override.yaml, pkg/controller/prpqr_reconciler/testdata/zz_fixture_prowjobs_TestReconcile_basic_case_with_variant.yaml, pkg/controller/prpqr_reconciler/testdata/zz_fixture_prowjobs_TestReconcile_basic_case_with_vsphere_override.yaml, pkg/controller/prpqr_reconciler/testdata/zz_fixture_prowjobs_TestReconcile_multiple_case__one_of_the_prowjobs_already_exists.yaml
With the additional-suffix changes, it is likely that we don't need to actually add the index to the job name itself. I confirmed this theory by manually triggering some jobs with the same name in the same namespace. They all succeeded as the pods were named differently due to the additional suffix on the target. Let's try this out for real now. If this works, there will be no need to change the aggregator itself.
/cc @jmguzik
=> one build for aggregate jobs (V7)

pkg/jobrunaggregator/jobrunaggregatorapi/types_row_jobrun.go, pkg/jobrunaggregator/jobrunbigqueryloader/types.go
bigquery: NULL values cannot be read into structs
=> trt-945: fix to use NullString for MasterNodesUpdated

pkg/prowgen/podspec_test.go
Hit this issue after upgrade `golangci-lint` to the following version:
(I did the upgrade for other issues)
```
$ golangci-lint --version                                                         
golangci-lint has version 1.52.2 built with go1.20.2 from da04413a on 2023-03-25T18:11:28Z
$ make lint 
./hack/lint.sh
+ echo 'Running golangci-lint'
Running golangci-lint
+ [[ /Users/hongkliu = \/ ]]
+ [[ -n '' ]]
+ golangci-lint run --build-tags e2e,e2e_framework,optional_operators
WARN [runner] The linter 'deadcode' is deprecated (since v1.49.0) due to: The owner seems to have abandoned the linter. Replaced by unused. 
pkg/prowgen/podspec_test.go:158:33: loopclosure: loop variable tc captured by func literal (govet)
g.Add(TargetAdditionalSuffix(tc.input))
^
make: *** [lint] Error 1
```
Stole …
=> Fix a lint issue

cmd/sync-rover-groups/ldap.go, cmd/sync-rover-groups/main.go
We do not use it any more.
https://github.com/openshift/release/pull/38974/files#diff-ed413ba53b67d2df6c1895585d183e7f54b62d6f2b8a5df53ed0027029507c25R22
It has been replaced by the `users.yaml`.
https://issues.redhat.com/browse/DPTP-3436
=> sync-rover-group: remove flag/mapping-file

cmd/sippy-config-generator/main.go
[TRT-1011](https://issues.redhat.com//browse/TRT-1011)
We're getting multiple PR's to sippy that just slightly changes the order of informing and blocking jobs in the config.
=> Ensure sippy-config-generator is deterministic

cmd/payload-testing-prow-plugin/server.go, cmd/payload-testing-prow-plugin/server_test.go
Similarly to `pj-rehearse`, this will add a way to comment `/payload-abort` to abort all currently running payload testing jobs for a specific PR.
For: https://issues.redhat.com/browse/DPTP-3322
=> `payload-testing`: allow for aborting all payload jobs for a PR with a command

cmd/payload-testing-prow-plugin/server.go
We should not try to update the prowjob if we have an unsuccessful fetch.
Follow up to https://github.com/openshift/ci-tools/pull/3424.
=> `payload-testing`: continue on failure to get prowjob

cmd/autoconfigbrancher/main.go
To update the golang version of o/etcd we need to disable the bot, which seems to revert the golang changes.
=> ignore etcd

pkg/jobrunaggregator/jobruntestcaseanalyzer/analyzer.go, pkg/jobrunaggregator/jobruntestcaseanalyzer/cmd.go
Follow-up to https://github.com/openshift/ci-tools/pull/3423, there's multiple places where we generate the title.  The junit test cases were missing the additional include/exclude information.
This makes it one place and plumbs it through to the aggregator and the test case analyzer.
=> Improve test case analyzer titles, part 2

pkg/jobrunaggregator/jobrunaggregatorlib/util.go
On install analysis pages[1], all but the first HTML lens file's accordion is opened. This is because the lens uses the filename as the ID, and all job-run-summary.html files are named the same.
This adds a timestamp suffix to the filename, which will work now that https://github.com/openshift/release/pull/39387 is merged.
[1] https://prow.ci.openshift.org/view/gs/origin-ci-test/logs/periodic-ci-openshift-release-master-nightly-4.14-install-analysis-all/1658711214819119104
=> Append timestamp to job-run-summary HTML

pkg/controller/prpqr_reconciler/prpqr_reconciler.go, pkg/controller/prpqr_reconciler/testdata/zz_fixture_prowjobs_TestReconcile_basic_aggregated_case.yaml
There are errors in certain cases with creating resources.
Reverts openshift/ci-tools#3415
=> Revert "`payload-testing`: One build for aggregate jobs"

pkg/jobrunaggregator/jobrunaggregatorlib/util.go
Reverts openshift/ci-tools#3434
I didn't realize the aggregator writes the file out multiple times: https://prow.ci.openshift.org/view/gs/origin-ci-test/logs/aggregated-azure-ovn-upgrade-4.14-micro-release-openshift-release-analysis-aggregator/1659049262366855168
I think I'll just try to fix this in prow.
=> Revert "Append timestamp to job-run-summary HTML"

cmd/sprint-automation/README.md, cmd/sprint-automation/main.go
As discussed in the retro, we no longer require these roles and they aren't providing us value. Removing them from the daily digest. I will clean up the schedules in PagerDuty post-merge.
=> `sprint-automation`: remove secondary triage roles

pkg/api/metadata.go, pkg/api/metadata_test.go, pkg/jobconfig/files.go, pkg/jobconfig/files_test.go
We are splitting `main` from `master` in the CMs. More details can be found in: https://github.com/openshift/release/pull/39565.
/hold this change will need to be coordinated with https://github.com/openshift/release/pull/39565
For: https://issues.redhat.com/browse/DPTP-3430
=> split the job-config-master-* config maps into master and main

pkg/controller/prpqr_reconciler/prpqr_reconciler.go, pkg/controller/prpqr_reconciler/testdata/zz_fixture_prowjobs_TestReconcile_basic_aggregated_case.yaml, pkg/controller/prpqr_reconciler/testdata/zz_fixture_prowjobs_TestReconcile_basic_case.yaml, pkg/controller/prpqr_reconciler/testdata/zz_fixture_prowjobs_TestReconcile_basic_case_with_metal_override.yaml, pkg/controller/prpqr_reconciler/testdata/zz_fixture_prowjobs_TestReconcile_basic_case_with_variant.yaml, pkg/controller/prpqr_reconciler/testdata/zz_fixture_prowjobs_TestReconcile_basic_case_with_vsphere_override.yaml, pkg/controller/prpqr_reconciler/testdata/zz_fixture_prowjobs_TestReconcile_multiple_case__one_of_the_prowjobs_already_exists.yaml, pkg/jobrunaggregator/jobrunaggregatoranalyzer/analyzer.go
This reverts commit 166eb633c628ef33da553b8129704d2c5e077648 (https://github.com/openshift/ci-tools/pull/3373)
This is complimentary to https://github.com/openshift/release/pull/39572
/assign @stbenjam @jmguzik
=> Revert "Increase timeouts for payload jobs to land k8s 1.27"

pkg/config/load.go, pkg/prowgen/podspec.go, pkg/prowgen/prowgen.go, pkg/prowgen/prowgen_test.go, pkg/prowgen/testdata/zz_fixture_TestGeneratePostSubmitForPromotion_default_cluster_only.yaml, pkg/prowgen/testdata/zz_fixture_TestGeneratePostSubmitForPromotion_spawn_on_multi01_and_arm01.yaml, pkg/prowgen/testdata/zz_fixture_TestGeneratePostSubmitForPromotion_spawn_on_multi01_cluster.yaml
`prowgen` generates one additional promotion job on `multi01` when the configuration flag `multi_arch` is set.
~~This new configuration replaces the old `additional_architectures`, therefore the following PRs have been reverted:~~
- ~~[Prowgen: multiarch postsubmit images #3053](https://github.com/openshift/ci-tools/pull/3053)~~  
- ~~[[prowgen] merge additional_architectures when repo defines them #3153](https://github.com/openshift/ci-tools/pull/3153)~~  
More details here: [DPTP-3463](https://issues.redhat.com/browse/DPTP-3463)
/cc @droslean @deepsm007
=> `prowgen`: promote on `multi01`

pkg/steps/multi_stage/run.go, pkg/steps/pod.go, pkg/steps/release/create_release.go, pkg/steps/release/import_release.go, pkg/steps/template.go, pkg/util/pods.go, pkg/util/util.go
Now that pod deletion events are properly reported as a result of
https://github.com/openshift/ci-tools/pull/3281, the output log for jobs which
use observer pods contains unnecessary warnings when they are cancelled, e.g.:
```
INFO[2023-05-16T08:37:20Z] Running multi-stage phase post
INFO[2023-05-16T08:37:20Z] Signalling observers to terminate...
INFO[2023-05-16T08:37:20Z] Running step e2e-telco5g-ptp-gather-must-gather.
WARN[2023-05-16T08:37:20Z] Pod e2e-telco5g-ptp-observers-resource-watch is being unexpectedly deleted
```
https://prow.ci.openshift.org/view/gs/origin-ci-test/logs/periodic-ci-openshift-release-master-nightly-4.13-e2e-telco5g-ptp/1658390573033197568#1:build-log.txt%3A26-29
This is done via a `DELETE` call, as is normal in Kubernetes, so these changes
suppress logging in …
=> ci-operator: do not log cancelled observers

pkg/api/constant.go, pkg/util/builds.go, pkg/util/pods.go
https://github.com/openshift/ci-tools/pull/2876
https://issues.redhat.com/browse/DPTP-2836
=> pkg/steps: add error reason for pending pods

cmd/ci-operator/main.go, go.mod
After the changes in the `controllerruntime` library that have been made in https://github.com/kubernetes-sigs/controller-runtime/pull/2317 it makes it necessary to pass a logger/
This change fixes the logged tracebacks in jobs. e.x https://prow.ci.openshift.org/view/gs/origin-ci-test/logs/branch-ci-openshift-cluster-node-tuning-operator-release-4.11-images/1663911500558897152#1:build-log.txt%3A20-48
=> [ci-operator] pass a null logger to controllerruntime when the verbose option is false

cmd/cluster-init/update_bootstrap_secrets.go, test/integration/cluster-init/create/expected/core-services/ci-secret-bootstrap/_config.yaml, test/integration/cluster-init/update/expected/core-services/ci-secret-bootstrap/_config.yaml
This PR fixes that `sa.ci-chat-bot.build08.token.txt` is missing from `core-services/ci-secret-bootstrap/_config.yaml`.
=> Fix issue DPTP-3484 Fix ci-chat-bot section

pkg/api/types.go
Create a new cluster profile "oci-assisted" which will hold credentials
to create resources in Oracle Cloud.
It will be used to test OCP installations using the assisted installer
(in the same way we have "packet-assisted").
=> MGMT-14816: Create new cluster profile for OCI

pkg/util/pods.go, pkg/util/pods_test.go
The error message emitted when a pod stays pending for too long, while correct,
can be misleading, since it includes only the first container which failed the
verification.  E.g.:
```
INFO[2023-06-06T02:21:07Z] pod pending for more than 30m0s: container "sidecar" has not started in 30m0.000680857s:
```
https://prow.ci.openshift.org/view/gs/origin-ci-test/logs/periodic-ci-openshift-assisted-service-release-ocm-2.8-e2e-ai-operator-ztp-3masters-periodic/1665871399811551232#1:build-log.txt%3A105
These changes instead list all containers so that the message presents a more
accurate idea of the state of the pod.
Before:
```
* could not run steps: step pending failed: "pending" test steps failed: "pending" pod "pending-test" failed: pod pending for more than 1s: container "place-entrypoint" has …
```
=> pkg/util: list all pending containers in errors

cmd/cluster-init/update_bootstrap_secrets.go, test/integration/cluster-init/create/expected/core-services/ci-secret-bootstrap/_config.yaml, test/integration/cluster-init/update/expected/core-services/ci-secret-bootstrap/_config.yaml
https://issues.redhat.com/browse/DPTP-3452
The credentials have been stored in Vault.
=> cluster-init: add push credentials for quay.io/openshift/ci

cmd/pod-scaler/frontend/.npmrc
Unable to build with the new `centos:9` build root. The following error is present:
```
Error: error:0308010C:digital envelope routines::unsupported
at new Hash (node:internal/crypto/hash:71:19)
at Object.createHash (node:crypto:130:10)
at BulkUpdateDecorator.hashFactory (/go/src/github.com/openshift/ci-tools/cmd/pod-scaler/frontend/node_modules/webpack/lib/util/createHash.js:145:18)
at BulkUpdateDecorator.update (/go/src/github.com/openshift/ci-tools/cmd/pod-scaler/frontend/node_modules/webpack/lib/util/createHash.js:46:50)
at SourceMapSource.updateHash (/go/src/github.com/openshift/ci-tools/cmd/pod-scaler/frontend/node_modules/webpack/node_modules/webpack-sources/lib/SourceMapSource.js:231:8)
at NormalModule._initBuildHash (/go/src/github.com/openshift/ci-tools/cmd/pod-scaler/frontend/no …
```
=> Add workaround for https://github.com/webpack/webpack/issues/14532

cmd/ci-operator/main.go, cmd/ci-operator/main_test.go, pkg/api/job_spec.go, pkg/api/job_spec_test.go, pkg/defaults/defaults.go, pkg/defaults/defaults_test.go, pkg/steps/multi_stage/gen.go, pkg/steps/multi_stage/testdata/zz_fixture_TestGenerateObservers.yaml, pkg/steps/multi_stage/testdata/zz_fixture_TestGeneratePods.yaml
There were reported errors with aggregate jobs like the following, found in this [log](https://prow.ci.openshift.org/view/gs/origin-ci-test/logs/openshift-origin-27894-ci-4.14-upgrade-from-stable-4.13-e2e-azure-sdn-upgrade/1658692416556765184):
```
Error: A resource with the ID "/subscriptions/72e3a972-58b0-4afc-bd4f-da89b39ccebd/resourceGroups/os4-common/providers/Microsoft.Network/dnsZones/ci2.azure.devcluster.openshift.com/CNAME/api.ci-op-iz4zs9r6-12383" already exists - to be managed via Terraform this resource needs to be imported into the State. Please see the resource documentation for "azurerm_dns_cname_record" for more information.
```
These jobs install the cluster utilizing configuration like the following, found in this …
=> `ci-operator`: add new UNIQUE_HASH env var which includes jobName and targetAdditionalSuffix when available

pkg/slack/events/helpdesk/helpdesk-message.go
Slack moved the workflows, users are already confused. I updated the daily reminder already, but we need to note the new location in this response as well.
=> `slack-bot`: update the auto response to use workflows to note the new location

pkg/util/pods.go
This makes it easier to determine which event is responsible when the pending
timeout expires:
```
INFO[2023-06-07T17:49:40Z] Running step pending-test.
INFO[2023-06-07T17:49:48Z] pod pending for more than 5s: containers have not started in 5.001088214s: test:
* Container test is not ready with reason ImagePullBackOff and message Back-off pulling image "image-registry.openshift-image-registry.svc:5000/bbguimaraes/stable:404"
Found 19 events for Pod pending-test:
* 0001-01-01T00:00:00Z 0x : Successfully assigned bbguimaraes/pending-test to ip-10-0-164-197.ec2.internal
* 2023-06-07T17:49:42Z 1x multus: Add eth0 [10.129.18.96/23] from openshift-sdn
* 2023-06-07T17:49:42Z 1x kubelet: Pulling image "registry.ci.openshift.org/ci/entrypoint:latest"
* 2023-06-07T17:49:42Z 1x kubelet: Successfully …
```
=> pkg/util: include time stamp in logged events

pkg/steps/release/promote.go, pkg/steps/release/promote_test.go, pkg/steps/release/testdata/zz_fixture_TestGetPromotionPod_tag_by_commit_is_true.yaml
Reported by @cjeanner 
https://redhat-internal.slack.com/archives/CBN38N3MW/p1686661568593859?thread_ts=1686658797.038549&cid=CBN38N3MW
```
INFO[2023-06-13T14:00:29Z] Logs for container promotion in pod promotion: 
INFO[[20](https://prow.ci.openshift.org/view/gs/origin-ci-test/logs/branch-ci-openstack-k8s-operators-ci-framework-main-images/1668618533803659264#1:build-log.txt%3A20)23-06-13T14:00:29Z] error: each destination tag may only be specified once: quay.io/openshift/ci:20230613_sha256_285bb49158ee4149465db685334cf3ce10f2da71a17994405a8eef67b46c7e18 
INFO[2023-06-13T14:00:31Z] Ran for 3m10s
```
With the promotion pod:
https://gcsweb-ci.apps.ci.l2s4.p1.openshiftapps.com/gcs/origin-ci-test/logs/branch-ci-openstack-k8s-operators-ci-framework-main-images/1668618533803659264/artifacts/buil …
=> Remove duplicated mirror upon tag_by_commit

pkg/jobrunaggregator/jobrunaggregatoranalyzer/analyzer.go, pkg/jobrunaggregator/jobrunaggregatorlib/ci_data_client.go, pkg/jobrunaggregator/jobrunaggregatorlib/jobrun_locator.go, pkg/jobrunaggregator/jobrunaggregatorlib/retrying_ci_data_client.go, pkg/jobrunaggregator/jobrunaggregatorlib/util.go, pkg/jobrunaggregator/jobruntestcaseanalyzer/analyzer.go, pkg/jobrunaggregator/jobruntestcaseanalyzer/cidataclient_test.go
Discovered the involved queries are running 380k a day, and while small, adding up to processing almost 40TB daily.
- Only select the job run name when querying before/after time. (50%)
- Poll every 10 min for aggregated jobs to finish instead of 2 (80%)
- Wait 2 hours before beginning to poll for aggregated sub-job completion (50-75%)
Reductions should pile onto one another, this may cut costs dramatically.
=> reduce job run query size

pkg/jobrunaggregator/jobrunaggregatoranalyzer/analyzer.go, pkg/jobrunaggregator/jobrunaggregatorlib/ci_data_client.go, pkg/jobrunaggregator/jobrunaggregatorlib/jobrun_locator.go, pkg/jobrunaggregator/jobrunaggregatorlib/retrying_ci_data_client.go, pkg/jobrunaggregator/jobrunaggregatorlib/util.go, pkg/jobrunaggregator/jobruntestcaseanalyzer/analyzer.go, pkg/jobrunaggregator/jobruntestcaseanalyzer/cidataclient_test.go
Reverts openshift/ci-tools#3482
Observing aggregated jobs indicating they are not completing when they appear to have actually completed.
Putting up revert since this change is directly related to aggregated jobs.
=> Revert "reduce job run query size"

pkg/jobrunaggregator/jobrunaggregatoranalyzer/analyzer.go, pkg/jobrunaggregator/jobrunaggregatorapi/gcs_jobrun.go, pkg/jobrunaggregator/jobrunaggregatorlib/ci_data_client.go, pkg/jobrunaggregator/jobrunaggregatorlib/jobrun_locator.go, pkg/jobrunaggregator/jobrunaggregatorlib/retrying_ci_data_client.go, pkg/jobrunaggregator/jobrunaggregatorlib/util.go, pkg/jobrunaggregator/jobruntestcaseanalyzer/analyzer.go, pkg/jobrunaggregator/jobruntestcaseanalyzer/cidataclient_test.go
Reverts openshift/ci-tools#3484
Seems we may still be breaking most aggregated jobs :( https://issues.redhat.com/browse/TRT-1094
This is a revert to a known working state.
=> Revert "Revert "Revert "reduce job run query size"""

pkg/jobrunaggregator/jobrunaggregatoranalyzer/analyzer.go, pkg/jobrunaggregator/jobrunaggregatorlib/ci_data_client.go, pkg/jobrunaggregator/jobrunaggregatorlib/jobrun_locator.go, pkg/jobrunaggregator/jobrunaggregatorlib/retrying_ci_data_client.go, pkg/jobrunaggregator/jobrunaggregatorlib/util.go, pkg/jobrunaggregator/jobruntestcaseanalyzer/analyzer.go, pkg/jobrunaggregator/jobruntestcaseanalyzer/cidataclient_test.go
- Only select the job run name when querying before/after time.
- Poll every 10 min for aggregated jobs to finish instead of 2
- Wait 2 hours before beginning to poll for aggregated sub-job completion
=> slow bigquery queries

pkg/jobrunaggregator/jobrunaggregatoranalyzer/analyzer_disruption.go
[TRT-1095](https://issues.redhat.com//browse/TRT-1095)
The new backends are enumerated in the [backend_disruption...json](https://gcsweb-ci.apps.ci.l2s4.p1.openshiftapps.com/gcs/origin-ci-test/logs/periodic-ci-openshift-release-master-nightly-4.14-e2e-aws-sdn-upgrade/1670859884670750720/artifacts/e2e-aws-sdn-upgrade/openshift-e2e-test/artifacts/junit/backend-disruption_20230619-190241.json) file and not present in the older backend_disruption...json files like [this](https://gcsweb-ci.apps.ci.l2s4.p1.openshiftapps.com/gcs/origin-ci-test/logs/periodic-ci-openshift-release-master-nightly-4.14-e2e-aws-sdn-upgrade/1666971942701240320/artifacts/e2e-aws-sdn-upgrade/openshift-e2e-test/artifacts/junit/backend-disruption_20230609-012950.json).
To get the list of new ones, I did this and compared …
=> Exclude new backends to avoid failing in aggregated jobs

Makefile, cmd/pod-scaler/consumer.go, test/e2e/pod-scaler/run/consumer.go
Adding a new log line to diagnose why the `pod-scaler-ui` readiness probe always seems to be throwing a `404`. I think this may have something to do with the memory leaks. I also made some changes to try this locally, but it does become ready there eventually.
=> `pod-scaler consumer`: add logging to diagnose readiness issue

pkg/steps/release/import_release.go
Since OCP 4.13, the internal registry supports the PreserveOriginal import mode for ImageStreamTags when the ReferencePolicy is set to local.
Using the PreserveOriginal import mode for the ImageStreamTags of the imported release payload will allow testing the non-amd64 control plane cluster scenarios when installing via the multi-arch payload.
This will only affect tests importing a multi-arch release payload and is harmless otherwise.
cc @tvardema @jaypoulz @Prashanth684
=> Update the importReleaseStep to use the PreserveOriginal import mode

cmd/pod-scaler/consumer.go
The logging added in: https://github.com/openshift/ci-tools/pull/3496 has illuminated a major issue with the `pod-scaler` consumers. They take 25-30 minutes to load new data due to the scale of data that we now have, but they then attempt to reload that data every 10 minutes. I believe this is causing the high memory usage as they are just constantly reloading data. I bumped the reload time up to 1 hour to monitor this for a bit, but we may find that we should change it to 2 or 3 hours even to further reduce costs. The producer only produces new data every 2 hours, but I still have a hunch that this constant churn is the culprit here.
=> `pod-scaler consumers`: don't reload as often

cmd/ci-operator-checkconfig/main.go
This parameter has had no effect since 8cb7bf0a5.  Even then, it was mostly
useless since the majority of the runtime is spent loading the configuration
files, not processing them, and that already happens in parallel
unconditionally.
=> ci-operator-checkconfig: remove concurrency arg.

cmd/pod-scaler/consumer.go
This had no effect on the `inactive_anon` memory consumption.
Reverts openshift/ci-tools#3470
=> Revert "`pod-scaler`: effectively undo e2e race fix to determine if it causes memory leak"

pkg/controller/prpqr_reconciler/prpqr_reconciler.go, pkg/controller/prpqr_reconciler/testdata/zz_fixture_prowjobs_TestReconcile_basic_aggregated_case.yaml
Re-enable https://github.com/openshift/ci-tools/pull/3415. I have fixed the issue by adding a new `UNIQUE_HASH`: https://github.com/openshift/ci-tools/pull/3437, and utilizing it everywhere: https://github.com/openshift/release/pull/40229. 
This reverts commit 8980f0e1
=> `payload-testing`: One build for aggregate jobs

pkg/jobrunaggregator/jobrunaggregatorapi/types_row_alert.go, pkg/jobrunaggregator/jobrunaggregatorapi/types_row_backenddisruption.go, pkg/jobrunaggregator/jobrunaggregatorapi/types_row_testrun.go, pkg/jobrunaggregator/jobrunbigqueryloader/alert.go, pkg/jobrunaggregator/jobrunbigqueryloader/alert_test.go, pkg/jobrunaggregator/jobrunbigqueryloader/disruption.go, pkg/jobrunaggregator/jobrunbigqueryloader/test_run_uploader.go, pkg/jobrunaggregator/jobrunbigqueryloader/types.go, pkg/jobrunaggregator/jobrunbigqueryloader/uploader.go
This table is over 200GB dating back more than 2 years. It's costing us
roughly 20$ a day to query it for our test run summary table which powers
test aggregation.
We want to move to partitioned tables which must be done delicately.
Firstly however we need a time column to partition on, which was not
present on TestRows previously.
I've added the four new columns already to the table, they are empty for
all past rows.
I also have a query ready that builds a new partitioned table with all
the current data.
The plan is to:
- merge this change and start updating these columns when we upload
- when the test run uploader is NOT running:
- build the new table with a different name
- rename TestRuns to TestRuns_OLD
- rename new table to TestRuns
All columns will then be populated, and new …
=> Prepare for partitioned TestRuns table in BigQuery

pkg/jobrunaggregator/jobrunaggregatorapi/types_row_alert.go, pkg/jobrunaggregator/jobrunaggregatorapi/types_row_backenddisruption.go, pkg/jobrunaggregator/jobrunaggregatorapi/types_row_testrun.go, pkg/jobrunaggregator/jobrunbigqueryloader/alert.go, pkg/jobrunaggregator/jobrunbigqueryloader/alert_test.go, pkg/jobrunaggregator/jobrunbigqueryloader/disruption.go, pkg/jobrunaggregator/jobrunbigqueryloader/types.go
Similar to yesterday, we're working to join less and deduplicate the job run tables entirely which all hold the same data
=> Store MasterNodesUpdated and JobRunStatus with every result as well

cmd/testgrid-config-generator/main.go
We are now extending layered product interop efforts to cover rosa hypershift testing. Since we are testing many layered products, manually submitting PRs to test-infra or adding to the _allow-list.yml is time consuming/error prone if forgetting to add a job when its being created.
This change updates the testgrid config generator command to create dashboards for layered product rosa-hypershift interop testing based on jobs containing a unique string 'lp-rosa-hypershift'.
These dashboards will provide easy insight/visibility into the health of the red hat portfolio on top of openshift releases.
This change will allow a dashboard to be created like the following:
* redhat-openshift-lp-rosa-hypershift-release-4.13-informing
=> Auto create layered product rosa-hypershift interop testing test grid dashboard.

pkg/jobrunaggregator/jobrunaggregatorlib/ci_data_client.go
on ambiguous MasterNodesUpdated
This column was added to BackendDisruption yesterday, and now this query
is broken. To fix we specify the table to use, which is an alias defined
in both queries that call this function.
=> Fix aggregated disruption tests being silently skipped

pkg/jobrunaggregator/jobrunaggregatorapi/types_row_historical_data.go, pkg/jobrunaggregator/jobrunaggregatorlib/ci_data_client.go
We now use 30 days instead of 21, we believe things are stable enough to
move up and this may help smooth out some of the weekly variance in the
data in this file.
Switched to use the latest daily report instead of a separate copy of
the same query, which was left behind when MasterNodesUpdated was
handled elsewhere.
We now use MasterNodesUpdated != N for the P99 limits, which implies
either Y or null for past releases. We want to use the worst case for
now as we recently did with aggregation.
=> Update historical disruption query

pkg/jobrunaggregator/jobrunaggregatoranalyzer/pass_fail.go, pkg/jobrunaggregator/jobrunaggregatoranalyzer/pass_fail_test.go
Adds a second check for aggregated disruption.
Made the fuzzy matching optional and disabled for the `zero-disruption should not be worse` tests
Diffs the expected number of passes from the actual passes in the first pass.  Uses that as a multiplier, the close we were to passing the lower the multiplier.
Diffs the historical disruption value from the actual disruption and multiplies this by the multiplier to create a fuzz value
Creates a fuzzThreshold based on the historical disruption value,  currently 4 and under  = 1, 5-9 = 2, 10-14 = 3, etc.
Checks to see if the fuzz value is less than or equal to the fuzzThreshold and if so considers it a pass.
We should be able to adjust the calculation for the fuzzThreshold to increase / decrease as needed.
=> TRT-1091: Add second pass for disruption checks with fuzzy comparison

pkg/api/helper/imagestreamtag.go, pkg/api/types.go, pkg/config/load.go, pkg/controller/promotionreconciler/reconciler.go, pkg/controller/promotionreconciler/reconciler_test.go, pkg/prowgen/prowgen.go, pkg/prowgen/prowgen_test.go, pkg/steps/index_generator.go, pkg/steps/index_generator_test.go, pkg/steps/source.go
Similar to 
https://github.com/openshift/ci-tools/pull/3521
that handles the istag in OO-Testing,
we make the promotionreconciler ready for istags with manifests.
Currently we do not hit the issue because CI does not build those isTags (openshift-build does not support multi-arch at the moment). But it might happen in the future.
=> promotionreconciler considers isTag with manifests

pkg/steps/artifacts.go, pkg/steps/multi_stage/gen_test.go, pkg/steps/multi_stage/testdata/zz_fixture_TestGenerateObservers.yaml, pkg/steps/multi_stage/testdata/zz_fixture_TestGeneratePods.yaml, pkg/steps/pod.go, pkg/steps/pod_test.go, pkg/steps/testdata/zz_fixture_TestPodStepExecution_Pod_run_by_PodStep_fails_so_PodStep_terminates_and_returns_an_error.yaml, pkg/steps/testdata/zz_fixture_TestPodStepExecution_Pod_run_by_PodStep_succeeds_so_PodStep_terminates_and_returns_no_error.yaml, pkg/steps/testdata/zz_fixture_TestPodStepExecution_Successful_pod_with_cloning.yaml, pkg/steps/testdata/zz_fixture_envTestGetPodObjectMounts_with_cluster_claim.yaml, pkg/util/util.go, test/e2e/simple/e2e_test.go
Reverts openshift/ci-tools#3319
This PR breaks existing jobs, including Cluster Bot.
Ref: https://redhat-internal.slack.com/archives/CBN38N3MW/p1688573508473129
@bbguimaraes
=> Revert "ci-operator: optionally decorate test pods"

pkg/api/ocpbuilddata/types.go
We have another stream that we need to ignore the `mirror: false` config on: `etcd_golang-1.19`. The following error was found in the latest auto-config-brancher [log](https://prow.ci.openshift.org/view/gs/origin-ci-test/logs/periodic-prow-auto-config-brancher/1676682589462597632):
```
failed to load ocp build data configs: failed dereferencing config for images/ose-etcd.yml: [failed to replace .from.0.stream: stream.yaml.etcd_golang-1.19.mirror is set to false, can not dereference, failed to dereference from.builder.0
``` 
I have now added all the other streams preemptively from the original commit that sets mirror to false: https://github.com/openshift-eng/ocp-build-data/commit/f75a59a27a17ae4cf716901acedeed3363915b67.
Follow up to https://github.com/openshift/ci-tools/pull/3511
=> add etcd_golang-1.19 to streams to ignore mirror=false from

pkg/release/official/client.go
OTA maintains staging (identical to production) and integration (running on engineering candidate OCP clusters) Cincinnati instances. We are searching for traffic that we could route to especially the integration one, so that we can find possible problems with engineering candidate early.
All the instances are serving identical data (up to some minimal skew coming from when individual instance scrape their source data) so we should be able to easily use the integration instance first, then the staging one, and if needed, use the production one as a backstop.
After:
```console
$ ci-operator --org stackrox --repo stackrox --branch master --target=[images] --git-ref=stackrox/stackrox@master
...
INFO[2023-06-26T16:11:20+02:00] Requesting 4.12 from …
```
=> OTA-905: cincinnati client: query integration & staging instances

pkg/util/pods.go
As introduction, `SkipLogs` is used by the implementation of some steps when
they require a pod in the test namespace to perform some action.  This is the
case for:
- promotion
- release image import
- release image creation
Note that in the case of the latter two, a single pod is created and potentially
watched by several `ci-operator` instances.
---
These changes are motivated by search results for pods which are unexpectedly
deleted showing primarily `release-*` pods:
https://search.ci.openshift.org/?type=build-log&name=&excludeName=&maxAge=24h&maxMatches=5&maxBytes=20971520&groupBy=job&context=1&search=pod+.%2A+is+being+unexpectedly+deleted
The first hint as to what the cause is is that these are all aborted jobs (or
would be, if they hadn't failed due to this problem).  These happen …
=> pkg/util: demote msg. to debug log when skipped

pkg/defaults/defaults.go, pkg/steps/release/import_release.go, pkg/steps/release/source.go, test/e2e/multi-stage/e2e_test.go
These changes remove the pull-spec for the release payload image of the cluster
pool used by a test from the inputs used to determine the temporary test
namespace.
---
When a test requests a cluster from a pool (i.e. it has a `cluster_claim`), the
release payload configured for the pool, along with its images, is imported into
the test namespace (see https://github.com/openshift/ci-tools/pull/2074).  This
is done so that tests can use these images in the same way as they would other
types of releases.
---
The original implementation had a problem: since only tests with a
`cluster_claim` are given the Hive `kubeconfig`, other tests in the same
configuration would fail to obtain this information (see
https://github.com/openshift/ci-tools/pull/2092). …
=> ci-operator: remove claim release image from input

pkg/defaults/defaults.go, pkg/defaults/defaults_test.go
https://prow.ci.openshift.org/view/gs/origin-ci-test/pr-logs/pull/openstack-k8s-operators_install_yamls/401/pull-ci-openstack-k8s-operators-install_yamls-main-images/1679343679455629312
As usual, at the bottom of an outage there is a comment such as this one:
https://github.com/openshift/ci-tools/blob/978b7cfb65f0775bdaf2ddda00c3811f1c553b63/pkg/defaults/defaults.go#L178-L179
In this case, since we now always add the `ImportReleaseStep` corresponding to a
test which has a cluster claim, we always set `hasReleaseStep` to `true`, and so
never add a `StableImagesTagStep` to the graph.
However, that `ImportReleaseStep` is specific to the test: it creates its own
`stable-${test_name}` `ImageStream` and not `stable`, which `hasReleaseStep`
implies.  This is fine for the job which executes the …
=> pkg/defaults: correct release steps for claims

cmd/ci-operator-checkconfig/main.go, cmd/ci-operator-configresolver/main.go, cmd/dptp-controller-manager/main.go, cmd/payload-testing-prow-plugin/filetestresolver_test.go, cmd/payload-testing-prow-plugin/main.go, pkg/config/load.go, pkg/load/agents/configAgent.go, pkg/load/agents/registryAgent.go, pkg/load/agents/utils.go, pkg/load/load.go
This PR was supposed to solve failures during the initialization and runtime of the `ci-operator-configresolver`. Instead, it was figured out, that the issue is mostly connected to the `agents` and touches also other services (`dptp-conotroller-manager`). In this PR is implemented channeled error forwarding for the `ConfigAgent` and `RegistryAgent`.
=> `agents`: initialization failures do not result in an error

pkg/jobrunaggregator/jobrunaggregatoranalyzer/analyzer.go, pkg/jobrunaggregator/jobrunaggregatorapi/gcs_jobrun.go, pkg/jobrunaggregator/jobrunaggregatorapi/interfaces.go, pkg/jobrunaggregator/jobrunaggregatorapi/jobruninfo_mock.go, pkg/jobrunaggregator/jobrunaggregatorlib/gcs_client.go, pkg/jobrunaggregator/jobrunbigqueryloader/uploader.go
- Simplifies finding / loading prowjob.json by looking specifically for the file and not a full scan.
- Delays the full scan until specifically called or artifacts are requested
- Caches artifact names so we don't have to perform multiple scans for different resources
=> TRT-1120: Support single pass to collect gcs files

pkg/util/testgrid.go
The Cloud Credential Operator has added support for STS-enabled clusters. We have a weekly e2e test that runs on an STS workflow and exercises creating a CredentialsRequest with correct parameters such that a Secret should be created.
We'd like to see this tracked with sippy.
Below is a link to a run of the test:
https://prow.ci.openshift.org/view/gs/origin-ci-test/logs/periodic-ci-openshift-cloud-credential-operator-master-e2e-aws-manual-oidc-cron/1680366890351857664
=> Add CCO prefix to testgrid informing

test/e2e/pod-scaler/kubernetes/kubernetes.go
Example sporadic failure: https://prow.ci.openshift.org/view/gs/origin-ci-test/pr-logs/pull/openshift_ci-tools/3491/pull-ci-openshift-ci-tools-master-e2e/1678797589270499328#1:build-log.txt%3A35
Reproducible with:
```console
$ git diff --unified=1
diff --git a/test/e2e/pod-scaler/kubernetes/kubernetes.go b/test/e2e/pod-scaler/kubernetes/kubernetes.go
index 39d9894f0..394aa1db4 100644
--- a/test/e2e/pod-scaler/kubernetes/kubernetes.go
+++ b/test/e2e/pod-scaler/kubernetes/kubernetes.go
@@ -11,2 +11,3 @@ import (
"net/http"
+       "time"
@@ -94,2 +95,3 @@ func Fake(t testhelper.TestingTInterface, tmpDir string, options ...Option) stri
go func() {
+               time.Sleep(10 * time.Second)
if err := server.ListenAndServe(); !errors.Is(err, http.ErrServerClosed) {
$ make local-e2e …
```
=> test/e2e: wait for fake Kubernetes server

cmd/testgrid-config-generator/main.go
This PR updates the testgrid-config-generator command to include Managed OpenShift (OSD, ROSA Classic, ROSA HCP) jobs within their corresponding test grid dashboards (informing or blocking). These jobs have been renamed as they are being refactored to be prowgen step registry style jobs. They no longer include the keyword `-ocp-` and would not be picked up for the correct test grid dashboards.
- https://github.com/openshift/release/pull/41245
- [SDCICD-1058](https://issues.redhat.com//browse/SDCICD-1058)
=> Include Renamed Managed OpenShift Jobs To TestGrid Dashboards

pkg/steps/multi_stage/init.go
https://github.com/openshift/ci-tools/pull/1684 added an extra role binding to
the `ServiceAccount` used by each multi-stage test.  However, the name it uses
is not unique, meaning a single binding will be created (`util.CreateRBACs`
ignores already-existing bindings with the same name).
This problem went unnoticed for this long because the jobs which depend on this
functionality usually get their own namespace.  This was discovered while
investigating a test which abuses this (very abusable) mechanism to look at
parts of the temporary namespace it should have no business looking at:
https://redhat-internal.slack.com/archives/CBN38N3MW/p1687185233834439
While not meant to make that particular case work, this is a legitimate
correctness problem.
=> multi-stage: properly name role binding

cmd/ci-operator/main.go
Our current setup results in ambiguous `PodDisruptionBudget` objects:
```
Warning	MultiplePodDisruptionBudgets	2m43s			controllermanager	Pod "ci-op-z7dvfmlm"/"slack-bot-build" matches multiple PodDisruptionBudgets.  Chose "ci-operator-created-by-ci" arbitrarily.
Warning	Failed				2m43s			kubelet			Error: Kubelet may be retrying requests that are timing out in CRI-O due to system load: context deadline exceeded: error reserving ctr name k8s_docker-build_slack-bot-build_ci-op-z7dvfmlm_fb72dce6-359a-4292-956a-31a4f138883e_0 for id 3aca8a54def6d6a407e2634c57cb16193567801d295b6ab74c92a2f2e06b979c: name is reserved
Warning	Failed				43s (x4 over 8m45s)	kubelet			Error: context deadline exceeded
Warning	MultiplePodDisruptionBudgets	42s (x15 over 50m)	controllermanager	Pod …
```
=> ci-operator: use a single PDB

pkg/testhelper/accessory.go
Otherwise `Log`/`Logf` calls mention the wrappers as the originating source code
location.
=> test/e2e: mark logging wrapper as helpers

cmd/ci-operator/main.go
The alert is currently not very helpful:
```
[FIRING:1] high-ci-operator-infra-error-rate (ci unknown critical)
An excessive amount of CI Operator executions are failing with unknown, which is an infrastructure issue. See CI search.
```
Reuse the same reason used for other graph building problems.
=> ci-operator: add reason for missing dependencies

pkg/jobrunaggregator/cmd.go, pkg/jobrunaggregator/jobrunaggregatorlib/ci_data_client.go
Reverts openshift/ci-tools#3523
@jupierce reached out regarding a high spike in bigquery costs.  Noted that the query against TestRuns suddenly showed up increasing costs 38x.
https://redhat-internal.slack.com/archives/C02K89U2EV8/p1691423995759719
Need to step back and review.
Justin pointed out that the JobRuns table is about 150MB, the query changed to the TestRuns table which is 252GB, explaining the huge jump in costs.
=> Revert "Replace use of JobRuns tables in ci data client"

pkg/steps/artifacts.go, pkg/steps/artifacts_test.go, pkg/steps/multi_stage/gen.go, pkg/steps/pod.go, pkg/steps/testdata/zz_fixture_TestAddPodUtils.yaml
This PR tries to solve [DPTP-3533](https://issues.redhat.com//browse/DPTP-3533). Using the new option from upstream [#30169](https://github.com/kubernetes/test-infra/pull/30169), we can propagate the exit code from observers to entrypoint and remove confusion to people when they analyze their job status.
=> `observer pods`: propagate the entrypoint's child exit code

pkg/steps/multi_stage/gen.go
Add forgotten `PropagateExitCode: genPodOpts.IsObserver` flag inside `GenerateBasePod()` to really propagate the entrypoint's child exit code for observes.
#3560 
It must have been forgotten somehow.
=> `observer pods` : propagate the entrypoint's child exit code 2

images/multi-arch-builder-controller/Dockerfile
Follow up of https://github.com/openshift/release/pull/42776
/cc @droslean
=> `multi-arch-builder-controller`: remove manifest-tool from dockerfile

cmd/autoconfigbrancher/main.go
Follow up https://redhat-internal.slack.com/archives/CHY2E1BL4/p1693418057541059?thread_ts=1693336376.195279&cid=CHY2E1BL4
/cc @openshift/test-platform @jupierce @nishant-parekh
=> autoconfigbrancher: ignore openshift/linuxptp-daemon

pkg/api/types.go
removed unused cluster profile azure-marketplace-qe based on https://github.com/openshift/release/pull/42330
Depend on https://github.com/openshift/release/pull/42718
=> remove unused cluster profile azure_marketplace_qe

pkg/jobrunaggregator/jobrunaggregatoranalyzer/analyzer_disruption.go
The situation with these backends is not yet fully known, and the
aggregation is tripping frequently. We're not confident in the data yet
and need the payloads to keep flowing. We will investigate this new
signal separately.
=> Disable aggregated testing for new disruption backends

pkg/api/types.go, pkg/dispatcher/config.go, pkg/dispatcher/config_test.go
The intention of this PR is to enable the transition of jobs from vSphere build01 to vSphere build02.  At present, all vSphere jobs are mapped to the current vSphere build01 cluster.
=> SPLAT-1175: enable vsphere02 as a target for vSphere CI jobs

cmd/sanitize-prow-jobs/main.go, cmd/sanitize-prow-jobs/main_test.go
/cc @danilo-gemoli @openshift/test-platform @aleskandro 
follow-up of https://github.com/openshift/ci-tools/pull/3613
=> [sanitize-prow-jobs] configure a different ci-operator image for the arm01 cluster in postsubmits

cmd/cluster-init/build_clusters.go, cmd/cluster-init/main.go, cmd/cluster-init/main_test.go, cmd/cluster-init/update_bootstrap_secrets.go, cmd/cluster-init/update_secret_generator.go
Add support for creating unmanaged clusters with `cluster-init`
The unmanaged clusters will:
1. not be included in `_cluster_init.yaml`
2. not update certain configs, e.g., PodScalar
=> Fix issue DPTP-3621 Add unmanaged flag to cluster-init

cmd/ci-images-mirror/main.go, hack/run-ci-images-mirror.sh, pkg/controller/quay_io_ci_images_distributor/quay_io_ci_images_distributor.go
The functions are copied (with a few modifications) from `test-images-distributor` and can be tested locally with the script `hack/run-ci-images-mirror.sh` from this PR.
I have not addressed the test coverage because
- most functions are tested already in `test-images-distributor`
- i plan to refactor to share the code between those 2 controllers AFTER PoC. If that does not happen, I will add tests by then.
https://issues.redhat.com/browse/DPTP-3529
=> ci-images-mirror: reconcile on the tags of test input

images/ci-operator-prowgen/Dockerfile
follow-up of https://github.com/openshift/release/pull/43485
Reverts openshift/ci-tools#3619
=> Revert "add the sanitize-prow-jobs binary in the ci-operator-prowgen image"

cmd/testgrid-config-generator/main.go, cmd/testgrid-config-generator/main_test.go
RedHat manages quite a large list of TestGrid configurations that are *not* derived from the release controller configuration. It's a shame that every single one of those folks need to manually configure TestGrid for their use-case and cannot take advantage of this tool and the automatic PR updates.
This is a small commit that mirrors the OSD additions added last year; in the process of working through the wrinkles for this new TestGrid config we will know how to factor the code such that other config could also be added here.
=> testgrid-config-generator: allow OLM tests

cmd/applyconfig/README.md, cmd/applyconfig/applyconfig.go, cmd/applyconfig/applyconfig_test.go
This PR introduce a flag to enable `--server-side` apply globally.
This PR also introduce a feature to use server-side apply for config files with file name starts with `SS_`.
Related to an HyperShift bug generating a large CRD which cannot be applied on client-side.
Ref: https://issues.redhat.com/browse/HOSTEDCP-985
cc. @hongkailiu
=> Fix issue DPTP-3440 Add server-side apply support

cmd/multi-arch-builder-controller/main.go, images/ci-operator/Dockerfile, pkg/controller/multiarchbuildconfig/multiarchbuildconfig.go, pkg/controller/multiarchbuildconfig/multiarchbuildconfig_test.go, pkg/manifestpusher/manifestpusher.go, pkg/steps/pipeline_image_cache.go, pkg/steps/project_image.go, pkg/steps/source.go, pkg/steps/source_test.go, test/e2e/framework/ci-operator.go
This PR:
- Migrates the manifest pusher into its own package for generalized usage.
- Transform all ci-operator builds to be architecture-specific.  
- Start using the `manifest-tool` tool in ci-operator to generate the final image with the manifest list included.
I already did some testing with the `vega-project` images. See job https://prow.ci.openshift.org/view/gs/origin-ci-test/logs/branch-ci-vega-project-ccb-operator-master-images/1695214240392024064
The final images that ended up in `apps.ci` cluster include the manifest list. 
/cc @openshift/test-platform @danilo-gemoli @jmguzik @deepsm007 @bbguimaraes 
=> Include the manifest list on the output images on all builds

cmd/ci-operator-prowgen/main.go, cmd/config-shard-validator/main.go, pkg/cmd/release/jobs.go, pkg/config/options.go, pkg/config/options_test.go, pkg/jobconfig/files.go, test/integration/ci-operator-prowgen.sh, test/integration/ci-operator-prowgen/input/jobs/infra-periodics.yaml, test/integration/ci-operator-prowgen/output/jobs/infra-periodics.yaml
We shouldn't output warnings for these files, as it confuses users and they think something is broken.
For: https://issues.redhat.com/browse/DPTP-3376
I will follow this up by adding the arguments to the call for `make jobs` in `openshift/release`
=> Ignore known infra-files in `prowgen` warnings

pkg/steps/source.go, pkg/steps/source_test.go
/cc @openshift/test-platform @petr-muller @flavianmissi 
=> respect the output image labels on all ci-operator builds

cmd/cluster-init/update_jobs.go, pkg/api/types.go
`build09` is OCP cluster, which needs the `oauth` to be set up manually.
=> Add build09 to update_jobs

cmd/config-brancher/main.go, cmd/config-brancher/main_test.go
Skip `.promotion.to[]` targets when branching a configuration. 
As an example, the following configuration on the dev branch `$ORG-$REPO-master.yaml`:
```yaml
promotion:
excluded_images:
- ci-image
- olm-bumper
name: "4.15"
namespace: ocp
to:
- additional_images:
ci-image: ci-image
olm-bumper: olm-bumper
excluded_images:
- '*'
namespace: operator-lifecycle-manager
tag: latest
```
gets two new branched configurations when `config-brancher --current-release=4.15 --future-release=4.16` is run:
```yaml
promotion:
excluded_images:
- ci-image
- olm-bumper
name: "4.15"
namespace: ocp
disabled: true
```
targeting current release `$ORG-$REPO-release-4.15.yaml` and:
```yaml
promotion:
excluded_images:
- ci-image
- olm-bumper
name: "4.16"
namespace: ocp
```
targeting the next release …
=> `config-brancher`: skip promotion targets when branching

.ci-operator.yaml, Makefile, go.mod, go.sum, hack/pr-deploy-prpqr-ui.yaml
As the title says, bump golang to 1.21.
/hold
It needs https://github.com/openshift/release/pull/42921
=> Bump Golang version to `v1.21.0`

cmd/pj-rehearse/server.go
We shouldn't eat this error. This came up in https://github.com/openshift/release/pull/44172#issuecomment-1755825288
=> `pj-rehearse`: surface specific error that caused changes to not rebase

pkg/api/types.go
It looks like one section for adding the new cluster type PowerVS-3 was missing. :(
=> PowerVS: Add missing PowerVS3

cmd/pj-rehearse/main.go, pkg/git/git.go, pkg/git/git_unit_test.go, pkg/git/options.go
`pj-rehearse` has recently started failing after we bumped prow in: https://github.com/openshift/ci-tools/commit/6d69b1df541f6bd8d06f3619725a09176edd8c40. This is due to a bug with a new feature introduced. Since then, upstream has completely removed the v1 client in: https://github.com/kubernetes/test-infra/pull/30924. The v2 git client that exists upstream is utilized only for testing purposes and due to being very stripped down, does not meet our needs. Evidently, they no longer have need to do complex local git commands like this. I have forked the v1 git client from before it was deleted and stripped it down to only include the functionality we need downstream. The additional tests for these functions have been modified long ago and are no longer easy to fork. I am going to follow …
=> fork v1 git client for use in `pj-rehearse`

pkg/jobrunaggregator/jobrunaggregatoranalyzer/analyzer.go
Sub-jobs (especially gcp rt upgrade) are running close to the current threshold of 4h15m. We also noticed that sub-jobs are not all starting the same time as the aggregator. Some jobs start 30m later.
=> Increase aggregator timeout from 4h15m to 5h15m

pkg/jobrunaggregator/jobrunhistoricaldataanalyzer/pr_message_template.md
This job has been broken for several weeks because the PR message being
generated is now too big for bash to cat in a command. We also need to
watch the Github comment limit of 64K chars.
With the inclusion of alert data, and the 4.13 rolling out due to 4.15
coming online, the list of missing data (i.e. jobs removed) has blown
up, the file was coming out 400K chars, even if we fixed reading it,
Github likely would reject.
I have removed the list of missing jobs, we can now see it can generate
too much data at boundaries of releases and it's of questionable value
regardless, we can still see the count of missing data at the top of the
template.
This allows us to continue generating the comparison table.
[TRT-1312](https://issues.redhat.com//browse/TRT-1312)
=> Remove list of missing data from origin synthetic test update PRs

pkg/jobrunaggregator/jobrunbigqueryloader/alert.go, pkg/jobrunaggregator/jobrunbigqueryloader/cmd.go, pkg/jobrunaggregator/jobrunbigqueryloader/disruption.go, pkg/jobrunaggregator/jobrunbigqueryloader/test_run_uploader.go, pkg/jobrunaggregator/jobrunbigqueryloader/uploader.go
Updated to add an uploader registry that relies on a common JobRuns table.
Prior work done in [TRT-1120](https://issues.redhat.com//browse/TRT-1120) reduces GCS enumeration to a single pass
Still need to coordinate removing the existing alert and disruption loader and removing references to those jobs tables
Updated to reference [TRT-1281](https://issues.redhat.com//browse/TRT-1281).  Current plan is to get support in place with the uploader registry and work through reducing the commands down to a single process separately.
=> TRT-1281: single command multiple uploaders 

pkg/jobrunaggregator/jobrunaggregatoranalyzer/analyzer.go, pkg/jobrunaggregator/jobrunaggregatoranalyzer/analyzer_test.go, pkg/jobrunaggregator/jobrunaggregatoranalyzer/cmd.go, pkg/jobrunaggregator/jobrunaggregatorlib/jobrun_locator.go, pkg/jobrunaggregator/jobrunaggregatorlib/util.go, pkg/jobrunaggregator/jobrunaggregatorlib/util_test.go, pkg/jobrunaggregator/jobruntestcaseanalyzer/analyzer.go, pkg/jobrunaggregator/jobruntestcaseanalyzer/cmd.go
Allows a list of JobRunIdentifier objects to be passed in for analysis bypassing bigquery lookup to reduces costs and allow external tooling to designate runs to be analyzed.
JobRunIdentifier can be passed in via the command to specify a static list of identifiers for analysis.  Additionally JobRunIdentifier is now set when using BigQueryJobRunWaiter or ClusterJobRunWaiter to skip additional / unnecessary calls to bigquery for JobRun data.
=> TRT-1204: Support static list of JobRuns

pkg/jobrunaggregator/jobrunaggregatoranalyzer/analyzer_disruption.go, pkg/jobrunaggregator/jobrunaggregatoranalyzer/pass_fail.go, pkg/jobrunaggregator/jobrunaggregatoranalyzer/pass_fail_test.go, pkg/jobrunaggregator/jobrunaggregatorlib/ci_data_client.go
- Drop the aggregated P95 should not get worse test
- Pass fixed graceseconds to aggregated percentile disruption tests
- Look at two weeks of disruption data instead of one for aggregated disruption percentile testing
- Remove the zero-disruption should not be worse aggregated test
More details on each commit and in the investigation doc shared with TRT.
=> Calm Aggregated Disruption Testing

pkg/controller/prpqr_reconciler/prpqr_reconciler.go
Following the patch https://github.com/openshift/release-controller/pull/564, the current one is required to ensure that the agent-based installer jobs will be executed on `build05` cluster, since they are using ofcir
=> Override cluster allocation for agent jobs

cmd/ci-images-mirror/main.go, pkg/controller/quay_io_ci_images_distributor/mirror.go, pkg/controller/quay_io_ci_images_distributor/oc_quay_io_image_helper.go
Found some error in the log like
```
error: unable to push manifest to quay.io/openshift/ci:edge-infrastructure_ocm-2.10_assisted-service-scripts: manifest invalid: manifest invalid
```
When I rerun it on my laptop, it succeeded.
The retries will help in those transit errors.
In addition, this PR also adds the duration for executing the mirror cmd in the log to help tune the timeout parameter if needed.
=> Enable retries on image mirroring

pkg/jobrunaggregator/jobrunaggregatoranalyzer/analyzer.go
In PR payload-aggregate case, job names are created by ci-operator and are not the same as the periodic name.
=> Name check in pr payload aggregate run is incorrect

cmd/pr-reminder/README.md, cmd/pr-reminder/main.go
Attempting to fix the error in logs like [this](https://prow.ci.openshift.org/view/gs/origin-ci-test/logs/periodic-pr-reminder/1717813475989786624) where there are invalid blocks. Set `escape` to true, because there is no good reason that it was false.
=> `pr-reminder`: escape text in slack message

cmd/ci-images-mirror/main.go, pkg/controller/quay_io_ci_images_distributor/quay_io_ci_images_distributor.go
https://issues.redhat.com/browse/DPTP-3727
Checked several such images and it seems they are imported from old streams for branching.
We should rebuild those images and see if we can reproduce the invalid manifest.
We could dig into the rebuild process on user request as it is hard to re-trigger the builds for all those images.
Instead, we ignore those images at the moment.
Otherwise, quay.io would modify the manifest version and the digest will not be the same as the source.
(Thus it would lead to wasting resources on mirroring those images.)
=> ci-images-mirror: ignore images with invalid manifest v2

pkg/controller/quay_io_ci_images_distributor/mirror.go
Found in log that more mirror tasks were executed than it is supposed to and it is caused by Not deleting the task when taking it out of the store.
=> ci-images-mirror: fix Take function of memoryMirrorStore

pkg/controller/quay_io_ci_images_distributor/quay_io_ci_images_distributor.go
```console
$ oc image mirror --keep-manifest-list --registry-config=/tmp/p.c --continue-on-error=true --max-per-registry=20 --dry-run=false registry.ci.openshift.org/openshift/release@sha256:09e51ff46de9707cab1d34b1c0d3ee40388f610de21ce30b51153a26c70473b7=quay.io/openshift/ci:openshift_release_tectonic-console-builder-v19 
...
I1030 18:22:12.293011   72990 manifest.go:550] warning: Digests are not preserved with schema version 1 images. Support for schema version 1 images will be removed in a future release
...
$ oc image info registry.ci.openshift.org/openshift/release@sha256:09e51ff46de9707cab1d34b1c0d3ee40388f610de21ce30b51153a26c70473b7 -o json -a /tmp/p.c | jq -r '.mediaType'
application/vnd.docker.distribution.manifest.v1+prettyjws
$ oc image info …
```
=> ci-images-mirror: sync images with schema version 1 only once

cmd/ci-images-mirror/main.go, pkg/controller/quay_io_ci_images_distributor/quay_io_ci_images_distributor.go
All kinds of broken images are on app.ci.
Fixed some of them but there are too many.
Let us grow a list of ignored images.
=> ci-images-mirror: ignore tags

pkg/api/types.go
Missed chaos profile for aws cluster type 
Missed this section in previous PR: https://github.com/openshift/release/pull/41590
CC: @chaitanyaenr
=> Chaos profile for aws cluster type

cmd/github-ldap-user-group-creator/main.go
The user is reserved on OSD clusters and will be recreated if deleted.
/assign @Prucek
=> Do not delete user/backplane-cluster-admin

pkg/api/types.go
The CSPI QE team would like to add a cluster profile for their IBM Cloud account. This cluster profile will be used in an effort to run interop tests for released layered products on z-stream releases of OpenShift.
=> [LPTOCPCI-992] Add ibmcloud-cspi-qe Cluster Profile

cmd/check-gh-automation/README.md, cmd/check-gh-automation/main.go, cmd/check-gh-automation/main_test.go
This PR adds functionality to verify that `openshift-cherrypick-robot` is an organization member for repositories that have the `cherrypick` external prow plugin configured. This ensures that the bot has the necessary permissions to operate correctly, aligning with the requirements outlined in JIRA TICKET.
- Added a new flag `--plugin-config` for specifying the plugin configuration file.
- Extended the `options` struct to include `PluginConfigPath`.
- Modified `checkRepos` function to check for `cherrypick` plugin and verify `openshift-cherrypick-robot` org membership.
- Adjusted `main_test.go` to include a fake ConfigAgent for testing and added `openshift-cherrypick-robot` to the test organization members.
- Updated README to reflect the new changes.
This PR aims to resolve the issue of …
=> Add openshift-cherrypick-robot org membership verification for cherrypick plugin

pkg/registry/server/server.go
We can't reasonably handle all `raw_steps` when merging configs for multi-pr payload testing, but there are a few scenarios that are simple substitutions that may get us some useful functionality.
For: https://issues.redhat.com/browse/DPTP-3685
/cc @danilo-gemoli
=> `ci-operator-configresolver`: handle a few simple `raw_step` ref substitutions

pkg/controller/multiarchbuildconfig/mirror.go, pkg/controller/multiarchbuildconfig/mirror_test.go, pkg/controller/multiarchbuildconfig/multiarchbuildconfig.go
=> [multiarchbuildconfig] treat the image targetRef as the default location for all external registries

pkg/api/types.go, pkg/steps/multi_stage/gen.go, pkg/steps/multi_stage/testdata/zz_fixture_TestGenerateObservers.yaml, pkg/steps/multi_stage/testdata/zz_fixture_TestGeneratePods.yaml
When creating a `hypershift-hostedcluster` we want to know, what `ClusterProfile` it was created with and add it to the [annotations](https://github.com/openshift/release/blob/master/ci-operator/step-registry/hypershift/hostedcluster/create/hostedcluster/hypershift-hostedcluster-create-hostedcluster-commands.sh#L82), so it can be properly deleted with the [cleaner](https://github.com/openshift/ci-tools/blob/master/images/dptp-3312-hypershift-leaks-cleaner/cleanup-hypershift-leaks.sh).
=> `ClusterProfiles`: add Name() method

test/validate-checkconfig.sh
Fixes the broken [checkconfig](https://prow.ci.openshift.org/view/gs/origin-ci-test/pr-logs/pull/openshift_ci-tools/3757/pull-ci-openshift-ci-tools-master-checkconfig/1722677415177621504) test.
=> add cluster-profiles-config to validate-checkconfig.sh

pkg/defaults/defaults.go, pkg/defaults/defaults_test.go
`cluster-bot` sets the `path_alias` [here](https://github.com/openshift/ci-chat-bot/blob/af9a327dc8ceaef8cf17654894322eb5542159dc/pkg/manager/prow.go#L788), and it doesn't interact well with the standard codeMountPath that is defined. We don't need to generate an absolute path when we are only cloning one ref anyways, so there is no need to run through this logic in those scenarios.
=> `ci-operator`: only determine the absolute path to `.ci-operator.yaml` when a ref has been defined

cmd/qci-appci/main.go
This PR init the work for https://issues.redhat.com/browse/DPTP-3749
It creates a proxy of quay.io and currently has no other logic implemented.
With this PR merged (and another one from the release), I can set up build, and start my iteration on the tool, such as certs, routes, deployment with it.
=> Init QCI-APPCI

cmd/check-gh-automation/main.go, cmd/check-gh-automation/main_test.go, hack/local-check-gh-automation.sh
This mode allows bots to not be checked, but rather checking only the app installation IFF tide is configured for the repo. This will be used in a new presubmit and periodic to check `openshift-merge-bot`'s installation across our onboarded repos. There will be minimal changes needed for the existing checks. https://github.com/openshift/release/pull/45521 will update existing checks and add new ones.
/hold so I can coordinate the rollout
=> `check-gh-automation`: introduce 'tide' mode 

pkg/registry/server/server.go, test/integration/ci-operator-configresolver/configs/master/openshift-console-master.yaml, test/integration/ci-operator-configresolver/expected/openshift-installer-console-merged-release-4.2-injected.json
The naive way we were handling the '*' entry in the merged resources map was causing issues in certain scenarios. We cannot have `limits` set when merging as this can result in a configuration where the request is lower than the limit. We should also use the higher of the request values in order to always request enough of the resource.
=> `ci-operator-configresolver`: merge '*' resources when merging configs, and remove limits

cmd/qci-appci/main.go
Before this PR, we check the validity of the token periodically.
There is a chance that a client gets an invalid token between the interval.
Now, we ensure the returned token is always valid by checking it more diligently.
Consulting the quay team https://redhat-internal.slack.com/archives/C7WH69HCY/p1700487847591749 about the token validity.
We might revert this PR if a better solution comes out the discussion.
=> qci-appci: ensure to get a valid token

cmd/branchingconfigmanagers/rpm-deps-mirroring-services/README.md
A small fix. Noticed this as I was executing before branching procedures, so I renamed it for clarity.
/cc danilo-gemoli
=> Update script name in README

cmd/payload-testing-prow-plugin/server.go, cmd/payload-testing-prow-plugin/server_test.go
Update the plugin to use the new list to provide the singular PR in the spec. Eventually, it will be possible to supply additional PRs here, but for now we will simply use the new list to make it easier to remove the, now deprecated, `PullRequest` singular field.
=> `payload-testing-prow-plugin`: use new `PullRequests` list

pkg/steps/bundle_source.go, pkg/steps/git_source.go, pkg/steps/index_generator.go, pkg/steps/pipeline_image_cache.go, pkg/steps/pod.go, pkg/steps/project_image.go, pkg/steps/rpm_injection.go, pkg/steps/rpm_server.go, pkg/steps/source.go, pkg/steps/source_test.go, pkg/steps/testdata/zz_fixture_TestBuildFromSource_ref_specified.yaml
The generated `build` should contain the proper labels for: `org`, `repo`, and `branch` when a `ref` is defined. Not having this doesn't cause anything to break, but it doesn't allow `pod-scaler` to properly determine the resource requests, and it adds to confusion when viewing the `build` itself on the cluster.
For: https://issues.redhat.com/browse/DPTP-3519
=> `ci-operator`: add labels for specific ref to the build when provided

pkg/api/types.go
* Remove the Kuryr profile, we are not using it anymore and
`openshift/release` doesn't have any occurence of it.
* Create new profile for our new IBM OpenStack cloud.
=> Update OpenStack cluster profiles

cmd/payload-testing-ui/server.go
This allows the `payload-testing-ui` to display both the singular and multiple pullRequests. This will only apply in the ~6 week period that both of these options are present. Eventually, we will only display the list.
The result looks like the the following screenshot:
=> `payload-testing-ui`: properly display pull requests list

cmd/qci-appci/main.go
When the repo is private, we need the scope when applying for the token.
=> qci-appci: get token with the scope param

pkg/controller/prpqr_reconciler/prpqr_reconciler.go, pkg/controller/prpqr_reconciler/testdata/zz_fixture_prowjobs_TestReconcile_basic_case_with_multiple_PRs_from_different_repositories.yaml
I have noticed a few instances in my testing where 4 hours isn't enough to build from multiple sources **and** complete the tests and post steps prior to hitting the timeout. We can increase it to 6 hours for these as a first try, I think it should be enough.
=> increase default timeout for multi-pr payload tests

pkg/api/multiarchbuildconfig/v1/types.go, pkg/controller/multiarchbuildconfig/multiarchbuildconfig.go, pkg/controller/multiarchbuildconfig/multiarchbuildconfig_test.go
Add some logs for clarity and perform a deep copy every type a `mabc` is retrieved.
Objects are pulled by the client from a shared internal cache, the controllers documentation [here](https://github.com/kubernetes/community/blob/master/contributors/devel/sig-api-machinery/controllers.md#:~:text=Never%20mutate%20original%20objects!) states that we are supposed to modify those only after a deep copy. 
/cc @droslean 
=> `multi-arch-builder-controller`: Improve logs and add deep copy

pkg/manifestpusher/manifestpusher.go, pkg/manifestpusher/manifestpusher_test.go
The `manifest-tools` gets invoked with the wrong arguments so it ends up bundling a manifest-list in which every manifest refers to the same image, regardless of the architecture (notice the same `.manifests[].digest` value):
```bash
skopeo inspect --raw 'docker://registry.multi-build01.arm-build.devcluster.openshift.com/ci/managed-clonerefs:latest' | jq
{
"schemaVersion": 2,
"mediaType": "application/vnd.docker.distribution.manifest.list.v2+json",
"manifests": [
{
"mediaType": "application/vnd.docker.distribution.manifest.v2+json",
"size": 1240,
"digest": "sha256:d67dc219cd8ea0e51c5f9e855b8d4963a693e996141b9a5e401a8eaf4c327e5d",
"platform": {
"architecture": "arm64",
"os": "linux"
}
},
{
"mediaType": "application/vnd.docker.distribution.manifest.v2+json",
"size": 1240,
"digest": …
```
=> `manifest-pusher`: fix push args

pkg/api/types.go
Add separate AWS and GCP cluster profiles for Telco jobs in openshift-kni org.
=> Add cluster profile for OCP Telco group

pkg/controller/prpqr_reconciler/prpqr_reconciler.go, pkg/controller/prpqr_reconciler/testdata/zz_fixture_prowjobs_TestReconcile_basic_aggregated_case.yaml, pkg/controller/prpqr_reconciler/testdata/zz_fixture_prowjobs_TestReconcile_basic_case.yaml, pkg/controller/prpqr_reconciler/testdata/zz_fixture_prowjobs_TestReconcile_basic_case_with_metal_override.yaml, pkg/controller/prpqr_reconciler/testdata/zz_fixture_prowjobs_TestReconcile_basic_case_with_variant.yaml, pkg/controller/prpqr_reconciler/testdata/zz_fixture_prowjobs_TestReconcile_basic_case_with_vsphere_override.yaml, pkg/controller/prpqr_reconciler/testdata/zz_fixture_prowjobs_TestReconcile_multiple_case__one_of_the_prowjobs_already_exists.yaml, pkg/jobrunaggregator/jobrunaggregatoranalyzer/analyzer.go
This reverts commit 642090c9ea047b63cddfac8471618d6cb498efad.
cc: @soltysh
=> OCPNODE-1888: Increase timeouts for payload jobs to land k8s 1.29

cmd/dptp-controller-manager/main.go, hack/run-dptp-controller-manager.sh, pkg/controller/promotionreconciler/reconciler.go, pkg/controller/promotionreconciler/reconciler_test.go
The controller `promotionreconciler` is a best-effort to trigger the promotion job in case the merge-triggered post-submit  did not go thro for any reason.
`dptp-cm` got restarted too often and as a result of slow consumption of the work queue, some request might be starved forever.
With this PR, we give an flag, opting in istags within certain age. It results in that old tags are staled which seems more acceptable than random tags are.
https://issues.redhat.com/browse/DPTP-3780
=> dptp-cm: add flag promotionReconcilerOptions.since

pkg/api/types.go
1. Because ibmcloud only us-east region support full private endpoints, have to run disconnected install in the specific region, so create a new cluster profile for it.
2. Fix nutanix-qe cluster profile return correct cluster type.
=> add a new ibmcloud-qe cluster profile and fix nutanix-qe cluster profile type

pkg/registry/server/server.go
`injectTest` returns a nil configuration when it fails to inject a test. The code that runs right after didn't check whether it is nil or not, therefore a `panic`.
FYI: @bradmwilliams
=> `ci-operator-configresolver`: fix nil pointer when injecting a test

cmd/cluster-init/update_bootstrap_secrets.go
The registry url for the multi01 cluster is different than the others. This PR fixes the validation and is depended upon by openshift/release#46574
=> multi01: fix registry url

pkg/jobrunaggregator/jobrunaggregatorapi/gcs_jobrun.go
If any junit file isn't valid XML then it fails the entire aggregation, even if it's a small number. We should just log it, but still try to do the aggregation.
If too many fail, the aggregator will fail at a higher level informing us it doesn't have enough results.
=> Don't fail aggregation if junit isn't parseable

pkg/jobrunaggregator/jobtableprimer/job_typer.go, pkg/jobrunaggregator/jobtableprimer/jobs.go, pkg/jobrunaggregator/jobtableprimer/jobs_test.go
[TRT-1414](https://issues.redhat.com//browse/TRT-1414)
Because of this, we didn't get 4.16 Job data which prevented us from getting 4.16 disruption/alerting data (as the Release was set to 'unknown'.  This PR makes it so that we panic to avoid this happening in the future in case we forgot to update the code with the branch after a new 4.n release is created.
=> Panic if we unable to determine Release from a job name

pkg/api/types.go
We are increasing the CCO automation ratio, and this includes test scenarios using AWS Service Control Policy (SCP).
Submit this commit to add aws-scp-qe cluster profile.
[OCPQE-17832: Add a aws-scp-qe Cluster Profile.](https://issues.redhat.com/browse/OCPQE-17832)
=> [OCPQE-17832] Add a aws-scp-qe cluster profile.

cmd/ci-secret-bootstrap/main.go, cmd/ci-secret-bootstrap/main_test.go
```
{"component":"ci-secret-bootstrap","error":"config[0].to[1]: failed to find cluster context \"arm01\" in the kubeconfig","file":"/go/src/github.com/openshift/ci-tools/cmd/ci-secret-bootstrap/main.go:907","func":"main.main","level":"error","msg":"Failed to complete options.","severity":"error","time":"2023-12-20T13:38:13Z"}
```
=> secret-bootstrap: fix completeOptions function

cmd/ci-secret-bootstrap/main.go, cmd/ci-secret-bootstrap/main_test.go
Previously, it ignored the dptp-defined secrets.
The tool handles the user-defined secrets too. 
We need to ignore them as well.
=> secret-bootstrap: ignore user secrets on disabled clusters

pkg/api/types.go
Introduces a new cluster profile 'libvirt-s390x-amd64', since the new resources are not interchangeable with the existing libvirt resources ('libvirt-s390x-...').
=> add cluster profile for multi-arch compute on libvirt s390x + amd64

cmd/payload-testing-ui/server.go
The field is no longer in the spec and the reference must be removed from the UI. I also needed to update the runs list to allow it to function with multiple pull requests:
For: https://issues.redhat.com/browse/DPTP-3689
=> `payload testing ui`: remove deprecated pullRequest field from UI

cmd/github-ldap-user-group-creator/main.go
```
{"component":"github-ldap-user-group-creator","file":"/go/src/github.com/openshift/ci-tools/cmd/github-ldap-user-group-creator/main.go:406","func":"main.makeGroups","ignoredOpenshiftPrivAdminNames":["openshift-cherrypick-robot"],"level":"error","msg":"These logins are members of openshift-priv but have no mapping to RH login.","severity":"error","time":"2024-01-03T19:46:14Z"}
```
Found it in the log above.
=> github-ldap-user-group-creator: recognize a new rebot Id

cmd/check-gh-automation/main.go, cmd/check-gh-automation/main_test.go, hack/local-check-gh-automation.sh
This PR addresses [DPTP-3481](https://issues.redhat.com/browse/DPTP-3481), enhancing the `check-gh-automation` tool. The primary focus is to ensure that the `openshift-merge-robot` has proper admin access to repositories when branch-protection is configured.
- **Hardcoded Admin Bot**: The `openshift-merge-robot` is now hardcoded in the tool for admin access checks in repositories with branch protection.
- **Branch Protection Verification**: Updated logic in `checkRepos` to verify if branch protection is enabled for a repository.
- **Admin Access Check**: Implemented a check within `checkRepos` to ensure `openshift-merge-robot` has admin access in repositories with branch protection.
- **Logging Enhancements**: Updated logging for better clarity on the branch protection status and bot …
=> DPTP 3481 - Enhance check-gh-automation with Admin Bot Access Verification

cmd/ci-operator-configresolver/main.go, cmd/ci-operator/main.go, pkg/controller/prpqr_reconciler/prpqr_reconciler.go, pkg/controller/prpqr_reconciler/prpqr_reconciler_test.go, pkg/defaults/defaults.go, pkg/defaults/defaults_test.go, pkg/registry/server/client.go, pkg/registry/server/server.go
This solves issues where multiple images share the same name as the endpoint to merge configs appends a suffix to each of them. With this change we will be able to run payload tests with `hypershift` and in the `installer` repo, which currently fail during graph resolution due to duplicate image names.
For: https://issues.redhat.com/browse/DPTP-3751
=> merge ci-operator configs for all payload tests

cmd/pipeline-controller/config_data_provider.go, cmd/pipeline-controller/config_data_provider_test.go, cmd/pipeline-controller/reconciler.go
This is enabling `pipeline_run_if_changed` setting for optional jobs and not adding them to override list. Mostly to further optimize costs.
=> Enable pipeline_run_if_changed for optional jobs

pkg/jobrunaggregator/jobrunaggregatorlib/spyglass_summary.go
[TRT-1428](https://issues.redhat.com//browse/TRT-1428)
job-run-summary for an aggregated job looks like this:
```
[periodic-ci-openshift-release-master-ci-4.16-e2e-azure-ovn-upgrade/1743954212951166976](https://prow.ci.openshift.org/view/gs/origin-ci-test/logs/periodic-ci-openshift-release-master-ci-4.16-e2e-azure-ovn-upgrade/1743954212951166976) failure after 5m45s
...
[periodic-ci-openshift-release-master-ci-4.16-e2e-azure-ovn-upgrade/1743954219666247680](https://prow.ci.openshift.org/view/gs/origin-ci-test/logs/periodic-ci-openshift-release-master-ci-4.16-e2e-azure-ovn-upgrade/1743954219666247680) failure after 4h0m10s
```
This PR adds the build cluster and a little bar chart to show relative duration:
```
[periodic-ci-openshift-release-master-ci-4.16-upgrade-from-stable-4.15-e2e-gcp-ov …
```
=> Add build cluster and asterisks for relative duration in aggregated jobs

pkg/controller/prpqr_reconciler/prpqr_reconciler.go, pkg/controller/prpqr_reconciler/testdata/zz_fixture_prowjobs_TestReconcile_basic_aggregated_case.yaml, pkg/controller/prpqr_reconciler/testdata/zz_fixture_prowjobs_TestReconcile_basic_case.yaml, pkg/controller/prpqr_reconciler/testdata/zz_fixture_prowjobs_TestReconcile_basic_case_with_metal_override.yaml, pkg/controller/prpqr_reconciler/testdata/zz_fixture_prowjobs_TestReconcile_basic_case_with_variant.yaml, pkg/controller/prpqr_reconciler/testdata/zz_fixture_prowjobs_TestReconcile_basic_case_with_vsphere_override.yaml, pkg/controller/prpqr_reconciler/testdata/zz_fixture_prowjobs_TestReconcile_multiple_case__one_of_the_prowjobs_already_exists.yaml, pkg/jobrunaggregator/jobrunaggregatoranalyzer/analyzer.go
Reverts openshift/ci-tools#3788
Reverting the timeout changes as the k8s v1.29 has been landed successfully
/assign @soltysh
=> OCPNODE-1897: Revert "OCPNODE-1888: Increase timeouts for payload jobs to land k8s 1.29"

cmd/prcreator/main.go, pkg/github/prcreation/prcreation.go
We want certain automated PRs to get assigned to multiple people instead of just one.  This allows the assignee to be a comma separated list; one assignee should still work.
TODO:
=> TRT-1440: Allow prcreator to have comma separated assignee list

pkg/defaults/defaults.go, pkg/steps/multi_stage/gen_test.go, pkg/steps/multi_stage/multi_stage.go, pkg/steps/multi_stage/multi_stage_test.go, pkg/steps/multi_stage/run_test.go
Natural consequence of https://github.com/openshift/ci-tools/pull/3895, this approach is way simpler than what I proposed with https://github.com/openshift/ci-tools/pull/3465.
The main source of pain, as well as the lines of code I had to write to unit test the thing, was due the observers being concurrently executed and torn down alongside a regular step. That was also the cause of sporadic deadlocks.
In this PR I give a test the faculty not to abruptly terminate an observer but therefore wait for it to complete, regardless of the result. By doing so the code requires no other synchronization than what there is already existing [here](https://github.com/openshift/ci-tools/blob/230178ef7f7e15dcc835314f7fde578ad88cb46d/pkg/steps/multi_stage/multi_stage.go#L235).
What follow is an example …
=> `ci-operator`: simplify observer pods unit test

cmd/payload-testing-prow-plugin/server.go, cmd/payload-testing-prow-plugin/server_test.go, pkg/release/config/config.go, pkg/release/config/config_test.go
This adds a new command to the plugin to support triggering a payload job with additional PRs built into the payload: `payload-job-with-prs`. As an example, the command `/payload-job-with-prs some-job-name openshift/kubernetes#1234 openshift/installer#999` would include the PR that the command was issued on as well as the 2 mentioned PRs in the generated `PRPQR` CR. I will follow this up with an update to the documentation.
For: https://issues.redhat.com/browse/DPTP-3689
=> `payload-testing-prow-plugin`: add the ability to support multiple PRs

cmd/payload-testing-prow-plugin/server.go
You can see the issue with the current field [here](https://pr-payload-tests.ci.openshift.org/runs/ci/04b4f1b0-b6e4-11ee-9042-a34fde72eb6c-0)
=> `payload-testing-prow-plugin`: use correct field for author on additional PRs

cmd/payload-testing-prow-plugin/server.go, cmd/payload-testing-prow-plugin/server_test.go
Each PR that the user requested to be included in the payload will be commented on with a link to the `PRPQR` run, and a reference to the originating PR. This will allow users to get a better understanding of all tests run for a PR.
For: https://issues.redhat.com/browse/DPTP-3689
=> `payload-testing-prow-plugin`: comment made on each additional PR included in payload test

cmd/payload-testing-prow-plugin/server.go, cmd/payload-testing-prow-plugin/server_test.go
Adds a `/payload-with-prs` command to allow the inclusion of additional PRs in the built payload for standard payload tests.
Also fixes minor bug where username isn't correctly populated in the comment from: https://github.com/openshift/ci-tools/pull/3907
For: https://issues.redhat.com/browse/DPTP-3689
=> `payload-testing-prow-plugin`: allow additional PRs to be included with "payload" command

pkg/api/multiarchbuildconfig/v1/types.go, pkg/controller/multiarchbuildconfig/mirror_test.go, pkg/controller/multiarchbuildconfig/multiarchbuildconfig.go, pkg/controller/multiarchbuildconfig/multiarchbuildconfig_test.go
I had hard time trying to understand what was going wrong with a failing build and I have realized we could have done much better with logs.
/cc @droslean
=> `multi-arch-builder-controller`: Better logging and tests

cmd/payload-testing-prow-plugin/server.go
Fixes a bug discovered in https://github.com/openshift/ci-tools/pull/3912 where the additional PRs would be duplicated when building the `PRPQR` CR. Each `job` had the same `WithPRs` set, by design. The list would then get duplicated values and create a CR that was invalid. Since all jobs triggered by one `*-with-prs` command must include the same PRs, we can resolve them after the jobs loop.
Also, adds plugin help for this command.
=> `payload-testing-prow-plugin`: only add each distinct pr to the PRPQR once

cmd/entrypoint-wrapper/main_test.go
- `cmd/entrypoint-wrapper/main_test.go`
1. **TestManageCLI**: Added unit tests to verify the behavior of the `manageCLI` function. Tests include:
- Appending CLI directory to the `PATH` environment variable when CLI directory is set.
- Leaving `PATH` unchanged if CLI directory is not set.
2. **TestManageHome**: Implemented unit tests for `manageHome` function. These tests cover:
- Ensuring no change when the home environment variable is set.
- Assigning a default home directory if the home environment variable is not set.
- Handling scenarios where the home environment is set but not writable.
https://issues.redhat.com/browse/DPTP-3847
=> Add Unit Tests for manageHome + manageCLI

cmd/registry-replacer/replacement_test.go
This PR introduces comprehensive unit tests for the `replacement.go` file in the `/cmd/registery-replacer/` directory.
- Implemented unit tests for the functions in `replacement.go`.
- The tests cover crucial functionalities and scenarios, including:
- **Replace Last FROM Image**: 
- Tests that the last `FROM` instruction in a Dockerfile is correctly replaced with a specified base image.
- **Multi-Stage Dockerfile Handling**: 
- Ensures that only the last `FROM` instruction is replaced in a multi-stage Dockerfile, leaving earlier stages unaltered.
- **Handling of Dockerfiles Without FROM Instructions**: 
- Verifies that Dockerfiles without any `FROM` instructions remain unchanged.
- **Node Reference Extraction in Dockerfile**: 
- Tests the ability to correctly identify and extract the …
=> Add Unit Tests for replacement.go in registery-replacer

cmd/gpu-scheduling-webhook/README.md, cmd/gpu-scheduling-webhook/main.go, cmd/gpu-scheduling-webhook/main_test.go, images/gpu-scheduling-webhook/Dockerfile
Add a mutating admission controller that adds a toleration on pods that request an Nvidia GPU.
Our clusters host some nodes that feature an Nvidia GPU. They are expensive to run workload on so
by using a mutating webhook we ensure that only the pods requesting a GPU actually run on those
nodes, leaving out everything else.
Check out `README.md` for a more detailed description.
/cc @bear-redhat @openshift/test-platform
=> `gpu-scheduling-webhook`: First implementation

pkg/defaults/defaults.go, pkg/defaults/defaults_test.go, pkg/steps/utils/env.go, pkg/steps/utils/env_test.go
This adds a new pattern for env vars to `ci-operator`: `OVERRIDE_IMAGE_*`. The remaining part of the var name relates to the image name, and the value is the tag to override it with in the `ocp` namespace. This will be used for payload-testing in a follow up PR.
For: https://issues.redhat.com/browse/DPTP-3688
=> `ci-operator`: Add env var `OVERRIDE_IMAGE_*` to override component images with provided name

cmd/autoconfigbrancher/main.go
Follow up https://redhat-internal.slack.com/archives/CHY2E1BL4/p1707428803154829?thread_ts=1707422678.970149&cid=CHY2E1BL4
A uncovered case of this tool showed up.
Instead of fixing the tool, we stop running it because we might not need it any more as "most repos contributing to OCP would already be using `build_root.from_repository: true` ".
/assign @jupierce
=> Disable ci-operator-yaml-creator

pkg/api/ocpbuilddata/types.go, pkg/api/ocpbuilddata/types_test.go
Tools (like `registry-replacer`) need to be aware of the `aliases` in the streams in order to work properly now that the `ocp-build-data` contains these.
For: https://issues.redhat.com/browse/DPTP-3871
=> Handle `ocp-build-data` stream aliases

pkg/defaults/defaults.go, pkg/defaults/defaults_test.go
My testing with this was all done on `app.ci`, but the real payload tests are largely run on `build01` so when verifying the functionality I ran into an issue with the `ist` not being available. I borrowed this idea from https://github.com/openshift/ci-tools/blob/d0b031bfd62188d3064639354f77fdd55474f1de/pkg/defaults/defaults.go#L993-L997
For: https://issues.redhat.com/browse/DPTP-3688
/cc @danilo-gemoli @openshift/test-platform
=> `ci-operator`: ensure ist is available on the build cluster for image tag override

pkg/api/ocpbuilddata/types.go
We only want to operate on "yaml" ("yml") files, so we don't load disabled configs
To fix errors like:
```
time="2024-02-12T12:01:57Z" level=fatal msg="Failed to construct promotion target to dockerfile mapping" error="failed to read image configs from ocp-build-data: [failed dereferencing config for images/ci-openshift-golang-builder-extra.rhel9.disabled: [failed to replace .from.stream: streamMap has no replacement for stream rhel-9-golang-{GO_EXTRA}, failed to find replacement for .from.stream], failed dereferencing config for images/ci-openshift-build-root-extra.rhel9.disabled: [failed to replace .from.member: no config images/ci-openshift-golang-builder-extra.rhel9.yml found, failed to find replacement for .from.stream]]"
```
For: https://issues.redhat.com/browse/DPTP-3871
=> `registry-replacer`: Don't use disabled configs

pkg/api/types.go
Added a new cluster profile to be used for ODF, i.e., projects under `red-hat-storage` org.
I had to create the PR by copying from here https://github.com/openshift/ci-tools/pull/3937 as Nikhil is on PTO and we are approaching the deadline for the new profile.
=> DPTP-3826: Adding ODF cluster profile

pkg/github/prcreation/prcreation.go
Seeing [failure](https://prow.ci.openshift.org/view/gs/test-platform-results/logs/periodic-update-origin-disruption-alert-data/1755758537033650176)  due to `couldn't find remote ref no-issue`
[PR](https://github.com/openshift/release/pull/48460/files) added `NO-ISSUE:` for automated updates not requiring JIRA.
prTitle is used for sourceBranchName, need to remove `:` as well as spaces 
Could use a regex if preferred:
```golang 
m1 := regexp.MustCompile(`[:\s]`)
sourceBranchName = m1.ReplaceAllString(prArgs.matchTitle, "-")
```
[playground](https://go.dev/play/p/TVdZE8Au1yp)
=> trt-1400: replace : in branch name

pkg/jobrunaggregator/jobrunaggregatoranalyzer/analyzer_disruption.go
This allows us to exclude all network liveness backends.
For example, we will exclude the `{gcp|aws|azure}-network-liveness-{new|reused}-connections` backends.
=> TRT-1476: Exclude all network liveness backends

cmd/ci-operator-prowgen/main.go, cmd/image-graph-generator/types.graphql, pkg/config/load.go, pkg/image-graph-generator/images.go, pkg/image-graph-generator/images_test.go, pkg/image-graph-generator/operator.go
Adding the multiArch field to the graph scheme. Populate the field based on the prowgen's configuration
Follow-ups: I will update the scheme after this merges.
=> include the multi_arch field on images for the graph generation

pkg/registry/server/server.go, test/integration/ci-operator-configresolver/expected/openshift-installer-console-merged-release-4.2-injected.json
Now that we allow PRs from the same repo to be tested together, we have situations where we are merging multiple of the same configs together. In practice, this appears to be okay with `ci-operator`, but it is a waste of time and resources. Instead, we should not merge duplicated metadata.
For: https://issues.redhat.com/browse/DPTP-3691
=> `ci-operator-configresolver`: guarantee unique metadata when merging configs from multiple sources

cmd/payload-testing-prow-plugin/server.go, cmd/payload-testing-prow-plugin/server_test.go
Due to the various, complex, regexs that this command acts upon, it is difficult to inform users when they have made a mistake in the command. This will catch any comments that start with "/payload", but we don't find any actionable command for, and provide a blanket response asking them to see the docs.
For: https://issues.redhat.com/browse/DPTP-3868
=> `payload-testing-prow-plugin`: add blanket response when user has mis-formatted payload command

pkg/api/types.go
The lease type was wrong and jobs would fail with:
failed to acquire lease for "openstack-nerc-dev": resources not found
=> Fix lease type for openstack-nerc-dev

cmd/ci-operator/main.go
The image job on ci-tools had been failing on b05 with the error indicating timeout on waiting for a pod to schedule.
https://github.com/openshift/release/pull/48778
indeed showed a difference on the successful rate.
We may add an option into ci-op's config if we see it is not flexible enough for all jobs.
/assign @smg247
=> ci-op: increase the default pod-pending-timeout to 60m

cmd/payload-testing-ui/server.go
Now that we don't require an actual PR to be passed for each `pullRequest` in the `PRPQR` spec, we need to display something reasonable in the UI when this is utilized.
This results in the following when a `PRPQR` is created using one base without a PR, and a couple with them:
For: https://issues.redhat.com/browse/DPTP-3686
=> `payload-testing-ui`: handle base commits rather than assume PRs

cmd/ci-operator-checkconfig/README.md
Since implementing the private cluster profile feature, the script needs a new arg to be run, as now it is also checking the cluster profiles config file to validate the configs in the release repository.
=> Add cluster-profiles-config arg to README

pkg/api/types.go
https://issues.redhat.com/browse/SRVCOM-2903
This is to enable starting AWS clusters from an AWS account owned by Serverless development team.
=> Create aws-serverless cluster profile

Makefile
=> local-e2e: specify context when getting LOCAL_REGISTRY_DNS

cmd/pj-rehearse/main.go, cmd/pj-rehearse/server.go, images/pj-rehearse/Dockerfile, pkg/rehearse/jobs.go, pkg/rehearse/jobs_test.go, pkg/rehearse/rehearse.go, pkg/rehearse/rehearse_test.go
This PR implements the mirroring of images to quay.io introduced by a PR in the rehearsals. 
Resolves: [DPTP-3746](https://issues.redhat.com/browse/DPTP-3746)
Deployment change: https://github.com/openshift/release/pull/48638
=> `rehearsals`: Add image mirroring to quay

pkg/api/types.go, pkg/prowgen/podspec_test.go
We don't use that profile anymore, and want to get rid of it.
=> remove ClusterProfileOpenStack (not used)

pkg/steps/multi_stage/gen.go, test/e2e/multi-stage/assembled-release-no-injection.yaml, test/e2e/multi-stage/assembled-release.yaml, test/e2e/multi-stage/dependencies.yaml, test/e2e/multi-stage/e2e_test.go
This PR basically mimics the same approach done in https://github.com/openshift/ci-tools/pull/3535 to bump release version from 4.13 to 4.15 to achieve what is being tried in https://github.com/openshift/ci-tools/pull/3914
=> NO-JIRA: Use RHEL8 oc explicitly

pkg/api/types.go
https://steps.ci.openshift.org/reference/ipi-install-install step fails for preflight tests using rh-openshift-ecosystem as the CLUSTER_TYPE when building the install-config.yaml and attempting to create find the cloud credentials. It is my understanding that resources will still be created using the rh-openshift-ecosystem-quota-slice
=> Use aws as the CLUSTER_TYPE

pkg/api/domain.go, pkg/api/promotion.go, pkg/steps/input_image_tag.go, pkg/steps/input_image_tag_test.go, pkg/steps/release/create_release.go, pkg/steps/release/release_images.go, pkg/steps/release/snapshot.go, pkg/util/imagestream.go, test/e2e/multi-stage/dependencies.yaml, test/e2e/observer/e2e_test.go, test/e2e/simple/e2e_test.go
This PR handles two cases (probably the only two?) where a CI job imports images from a local cluster.
- the images from a ref on a tag in ci-op's config, such as base_images,
- the images from a release that snapshots the integration streams, i.e., there is `tag_specification` or `releases.integration` as described in https://docs.ci.openshift.org/docs/internals/steps/#releaseimagestagstep
Those images are distributed by the controller `test-images-distributor` in `dptp-controller-manager` https://github.com/openshift/ci-tools/tree/master/pkg/controller/test-images-distributor from app.ci to build-farms.
As planed, we want the Job imports those images from QCI-APPCI, instead of the one cluster that the job is running on.
There is a commit for each of the case above. ~The 3rd commit is …
=> ci-op: pipeline imports images from QCI-APPCI

pkg/registry/resolver.go, pkg/registry/resolver_test.go
We've discovered that overriding only when declared is disruptive if teams want to share steps but only one team is setting an override. This change makes it the responsibility of workflow and job authors to set dnsConfig only when they're sure they want to override all steps contained by those higher-order objects.
https://redhat-internal.slack.com/archives/CBN38N3MW/p1709743581114759?thread_ts=1709667080.103889&cid=CBN38N3MW
=> MULTIARCH-4510: Updated dnsConfig to always overwrite from highest order set value (job > workflow > step).

images/dptp-3312-hypershift-leaks-cleaner/cleanup-hypershift-leaks.sh
The `dptp-3312-hypershift-leaks-cleaner` is not working properly, this PR is trying to address this issue.
/cc @bear-redhat
=> cleaner: add AWS_SHARED_CREDENTIALS_FILE ENV

pkg/steps/release/snapshot.go
https://redhat-internal.slack.com/archives/CNHC2DK2M/p1709925913590499?thread_ts=1709924590.729349&cid=CNHC2DK2M
The namespace for the integration steam is given by an env. var with the value `ci-ln-<hash>` (without any suffixed).
The stream `stable` in `ci-ln-<hash>` is populated by `ci-op` with `RELEASE_IMAGE_LATEST`.
/cc @openshift/test-platform @jupierce @bradmwilliams
=> snapshot: use ImageStreamImage for cluster-bot jobs

cmd/check-gh-automation/main.go, cmd/check-gh-automation/main_test.go
Lots of failures in this [run](https://prow.ci.openshift.org/view/gs/test-platform-results/logs/periodic-check-gh-automation/1764485958339661824) due to this case.
Branch protection is enabled by default unless there is configuration stating unmanaged=true.
The unit tests were also incorrectly passing without actually looking at branch protection. I fixed those as well.
=> `check-gh-automation`: fix branch-protection determination logic

pkg/api/types.go
All the aws arm64 jobs are using aws-2 cluster profile.
=> Removing unused cluster-profile

pkg/api/helper/imageextraction.go, pkg/api/helper/imageextraction_test.go, pkg/controller/quay_io_ci_images_distributor/quay_io_ci_images_distributor.go, pkg/controller/test-images-distributor/test_images_distributor.go, pkg/rehearse/jobs.go
Follow up https://redhat-internal.slack.com/archives/CBN38N3MW/p1710169725703149?thread_ts=1710168229.675879&cid=CBN38N3MW
I believe this bug has been there since the beginning.
As it shown in the PR, `TestInputImageStreamTagsFromResolvedConfig` is used by other tools too.
However, it is not outstanding in other tools is because of the difference on `testInputImageStreamTagFilterFactory`.
https://github.com/openshift/ci-tools/blob/0a9b4d7a2992f110a4569f92a9c5690e9e3d7406/pkg/controller/test-images-distributor/test_images_distributor.go#L583
For example, the tag `openshift/release:rhel-8-release-golang-1.20-openshift-4.16` is not mirrored to QCI.
But the dptp-controller still distritubtes the image to build farms (the component has logs on the request).
=> Fix TestInputImageStreamTagsFromResolvedConfig function

cmd/check-gh-automation/main.go
Follow up to https://github.com/openshift/ci-tools/pull/4018, we need to add this to the failing list in order to get the correct output for our users to know how to fix the problem.
=> `check-gh-automation`: add org/repo to failing list when branch-protection reqs are not met

images/dptp-3312-hypershift-leaks-cleaner/cleanup-hypershift-leaks.sh
The `dptp-3312-hypershift-leaks-cleaner` is not working properly, this PR is trying to address this issue.
/cc @bear-redhat
=> cleaner: fix aws credential issue

cmd/ci-images-mirror/main.go, hack/run-ci-images-mirror.sh, pkg/controller/quay_io_ci_images_distributor/mirror.go, pkg/controller/quay_io_ci_images_distributor/quay_io_ci_images_distributor.go
We will start to migrate mirroring external images to CI with this tool.
https://docs.ci.openshift.org/docs/how-tos/external-images/ will be updated accordingly after this PR.
Note that this PR does not impact how the images are mirrored out of CI: We may do it later in this tool too if needed.
https://docs.ci.openshift.org/docs/how-tos/mirroring-to-quay/
The user will fill in the config file of this tool such as
```yaml
supplementalCIImages:
openshift/boilerplate:image-v0.1.1:
image: quay.io/app-sre/boilerplate:image-v0.1.1
openshift/boilerplate:image-v5.0.0:
image: quay.io/app-sre/boilerplate:image-v5.0.0
ci/hongkliu-test:supplemental-ci-images-test:
namespace: ci
name: hongkliu-test
tag: speical-tag-for-proxy-testing
```
The keys such as `openshift/boilerplate:image-v0.1.1` are the …
=> Mirror CI supplemental images

cmd/ci-images-mirror/main.go
=> ci-images-mirror: add a log when mirroring supplemental CI images

cmd/helpdesk-faq/main.go, images/helpdesk-faq/Dockerfile
This is the first step in a 3-ish part processes. This PR contains the `helpdesk-faq` server that simply responds with the FAQ items in the ConfigMap. There are currently some example items in the [CM](https://console-openshift-console.apps.ci.l2s4.p1.openshiftapps.com/k8s/ns/ci/configmaps/helpdesk-faq).
For: [DPTP-3521](https://issues.redhat.com/browse/DPTP-3521)
=> `helpdesk-faq`: server that provides an endpoint with a list of all faq items

cmd/check-gh-automation/main.go, cmd/check-gh-automation/main_test.go
this check is too heavy handed to use in the periodic version. we will only use this one on the presubmit. We have [dozens](https://redhat-internal.slack.com/archives/CHY2E1BL4/p1710756614008279?thread_ts=1710749128.779799&cid=CHY2E1BL4) of currently onboarded repos that are failing this check, despite the branch protection job passing just fine. The reasons vary, but are not worth making the repo owners grant us access, for example:
- “konveyor/tackle-ui-tests” it seems that the branch protection matches the policy. So there is no need to have admin rights as nothing is changing.
- Others, like “kiegroup/kie-cloud-operator” have “protect=false”, and it also matches the settings, so no admin required there either.
This check will only be used in the presubmit version of the tool. This …
=> `check-gh-automation`: create an option to skip the branch protection access check. 

pkg/steps/multi_stage/gen.go, test/e2e/multi-stage/assembled-release-no-injection.yaml, test/e2e/multi-stage/assembled-release.yaml, test/e2e/multi-stage/dependencies.yaml, test/e2e/multi-stage/e2e_test.go
Previous PR https://github.com/openshift/ci-tools/pull/4000 was reverted in https://github.com/openshift/ci-tools/pull/4002 because changes were not backwards compatible and caused cascading failures.
This PR reintroduces same approach additionally supporting backwards compatibility. Firstly, it checks the path of `oc.rhel8`. If binary is found, it will copy. If binary is not found like releases older than 4.15, it falls back to current behavior.
Thanks to this change, maintainers of this repository can change rhel version of oc and also supports multiple architecture versions (i.e. linux_arm64).
Edited: I'd like to note the reason of this change is that we are going to change the base image of oc from RHEL8 to RHEL9 and oc compiled in RHEL9 does not work on RHEL8 clusters. Therefore, we …
=> OCPBUGS-20097: Use RHEL8 oc explicitly

pkg/release/candidate/client.go, pkg/release/prerelease/client.go, pkg/steps/release/promote.go, pkg/steps/release/promote_test.go
We use the service provided by the release controller to determine the version so that we do not need to manually bump the hardcoded version.
It is the latest Y-stream for 4-stable.
https://amd64.ocp.releases.ci.openshift.org/#4-stable
Currently it is 4.15.
=> Determine the cli version in the promotion pod

cmd/ci-images-mirror/main.go, cmd/pj-rehearse/main.go, cmd/pj-rehearse/server.go, pkg/controller/quay_io_ci_images_distributor/supplemental_images.go, pkg/rehearse/rehearse.go, pkg/rehearse/rehearse_test.go
Add the option to supplemental images config: https://github.com/openshift/release/blob/master/core-services/image-mirroring/_config.yaml and ignore the targeting images defined there.
=> `rehearsal`: add supplemental images config

cmd/publicize/server.go
/cc @openshift/test-platform @smg247 
=> publicize: construct the user credentials while reloving the external remote

cmd/pj-rehearse/server.go
It is increasingly confusing users with the time it takes to process requests. add an acknowledgment of the request to let them know we are processing.
=> `pj-rehearse`: acknowledge that a request is being processed

cmd/ci-scheduling-webhook/mutation.go
`ci-scheduling-webhook` should be gentle and add only its own stuff into the map instead of replacing it entirely.
/cc @bear-redhat @droslean
=> ci-scheduling-webhook: don't overwrite `.spec.nodeSelector`

cmd/pj-rehearse/main.go, cmd/pj-rehearse/server.go, pkg/rehearse/jobs.go, pkg/rehearse/jobs_test.go, pkg/rehearse/rehearse.go
There is no reason to wait and constantly poll for job success in standard workflows. It appears that doing so makes it so the temporary git repo checkout doesn't get pruned until all jobs are complete. This causes the `inactive_anon` memory space to be filled up, and results in the plugin using significantly more memory than necessary. We still need to wait in `auto-ack` mode in order to ack when jobs succeed only.
For: https://issues.redhat.com/browse/DPTP-3933
=> `pj-rehearse`: don't wait for job success on standard rehearsal runs

pkg/steps/release/import_release.go
Follow up https://redhat-internal.slack.com/archives/CBN38N3MW/p1712580650489229?thread_ts=1712481700.619319&cid=CBN38N3MW
[This job](https://prow.ci.openshift.org/view/gs/test-platform-results/logs/periodic-ci-openshift-assisted-installer-agent-release-ocm-2.10-subsystem-test-periodic/1777124438580400128) ends up with
```
ERRO[2024-04-08T00:16:06Z] 
* could not run steps: step [release:latest] failed: failed to get CLI image: unable to wait for the 'cli' image in the stable stream to populate (waited for 5m5.027192371s): timed out waiting for the condition 
```
and the stream.json in artifacts does not have the values at the time of checking.
So we add the logs for debugging.
=> import_release: add more debug logs

pkg/config/load.go, pkg/prowgen/prowgen.go, pkg/prowgen/prowgen_test.go, pkg/prowgen/testdata/zz_fixture_TestGenerateJobs_multiarch_branch_filtered__cluster_change.yaml, pkg/prowgen/testdata/zz_fixture_TestGenerateJobs_multiarch_branch_filtered__no_cluster_change.yaml
Introduces the `multi_arch_branch_filter` field that if exists, only the specified branches will be included in the multi-arch image builds.
Example config
```yaml
multi_arch: true
multi_arch_branch_filter:
- main
- release-4.15
- release-4.14
```
https://issues.redhat.com/browse/DPTP-3958
/cc @deepsm007 @danilo-gemoli @openshift/test-platform 
=> prowgen: introduce the multi-arch branch filtering configuration

cmd/ci-secret-bootstrap/main.go, cmd/ci-secret-bootstrap/main_test.go
An attempt to fix https://issues.redhat.com/browse/DPTP-3955
=> ci-secret-bootstrap: fix nil pointer on missing cluster

cmd/cluster-display/main.go
One difference between hive and hosted-mgmt is that OSD vs OCP.
The former has route for image registry out of the box but the former does not.
Tested locally:
```console
$ curl -s http://localhost:8090/api/v1/clusters | jq '.data[]|select(.cluster=="hosted-mgmt")'
{
"cloud": "AWS",
"cluster": "hosted-mgmt",
"consoleHost": "console-openshift-console.apps.hosted-mgmt.ci.devcluster.openshift.com",
"hypershiftSupportedVersions": "[\"4.16\",\"4.15\",\"4.14\",\"4.13\"]",
"product": "OCP",
"registryHost": "unset",
"version":
```
=> cluster-display: no resolving image registry host on hosted-mgmt

cmd/cluster-display/main.go
This is to reduce the delay between the values on the cluster and the information returned to the client.
1 hour is good for the cluster information, such as cluster version or hostnames of some routes. They are very static.
But the values on cluster pools change quickly.
=> cluster-display: set cache duration 1m

pkg/jobrunaggregator/jobrunaggregatoranalyzer/analyzer.go, pkg/jobrunaggregator/jobruntestcaseanalyzer/analyzer.go
Aggregator retry mechanism depends on release-controller to set the job start time each time it is retried. release-controller sets the start time to the current time when the job is started. When aggregator is retried the third time, most of the sub jobs already finished. But aggregator still wait for two hours before it event tries to check on sub jobs.
I am reducing the initial wait from 2h to 10m. This means the maximum time we wait is 10m. Since we are using incluster prowjob watch mechanism now, this should not increase any resource usage. One can even argue that we can remove initial wait. I am leaving the implementation as it is since we still keep the fallback gcs based wait mechanism.
=> TRT-1621: Reduce initial aggregator wait 

cmd/ci-operator-configresolver/main.go, cmd/ci-operator-configresolver/main_test.go
Follow up https://redhat-internal.slack.com/archives/CHY2E1BL4/p1714643460138379
Allow the integrated steams for private jobs, such as `ocp-private/4.16-priv`.
=> configresolver: allow the integrated steams for private jobs

cmd/ci-operator-configresolver/main.go, cmd/ci-operator-configresolver/main_test.go, cmd/ci-operator/main.go, pkg/api/configresolver/configresolver.go, pkg/api/configresolver/configresolver_test.go, pkg/defaults/defaults.go, pkg/defaults/defaults_test.go, pkg/registry/server/client.go, pkg/steps/release/create_release.go, pkg/steps/release/release_images.go, pkg/steps/release/snapshot.go
Follow up https://redhat-internal.slack.com/archives/CHY2E1BL4/p1714644855129709?thread_ts=1714643460.138379&cid=CHY2E1BL4
For the cluster-bot jobs, we get the tags from the stream in the local cluster, as we did before.
/hold
Will verify with the built image
=> releaseSnapshotStep: no dependencies on isTags of the local cluster

cmd/registry-replacer/main.go, cmd/registry-replacer/main_test.go
Slack [thread](https://redhat-internal.slack.com/archives/GB7NB0CUC/p1714674628936099) that backs this decision up .
=> registry-replacer: consider image aliases when pruning ci-operator replacements

cmd/ci-operator-configresolver/main.go
Found log in the compoment:
```json
{
"component": "ci-operator-configresolver",
"file": "/go/src/github.com/openshift/ci-tools/vendor/k8s.io/test-infra/prow/simplifypath/simplify.go:48",
"func": "k8s.io/test-infra/prow/simplifypath.(*simplifier).Simplify",
"level": "debug",
"msg": "Path not handled. This is a bug, please open an issue against the kubernetes/test-infra repository with this error message.",
"path": "/integratedStream",
"severity": "debug",
"time": "2024-05-06T12:44:40Z"
}
```
=> ci-operator-configresolver: fix simplifypath

pkg/api/leases.go, pkg/api/leases_test.go, pkg/defaults/defaults.go
We can't take advantage of these on versions older than 4.16. We shouldn't lease them out if they won't be used.
=> `ci-operator`: limit ip pool leases on the aws profile to "master"/"main" or greater than "4.16"

cmd/gpu-scheduling-webhook/main.go, cmd/gpu-scheduling-webhook/main_test.go, pkg/api/constant.go, pkg/validation/config.go, pkg/validation/config_test.go
This is a follow up of https://github.com/openshift/ci-tools/pull/3927
Allow `nvidia.com/gpu` to be specified in both `requests:` and `limits:` stanzas.
=> ci-operator: validate `nvidia.com/gpu` resource

pkg/jobrunaggregator/jobruntestcaseanalyzer/analyzer.go, pkg/jobrunaggregator/jobruntestcaseanalyzer/cmd.go
Adds a test group to the job analyzer that verifies an upgrade completes cleanly.
=> TRT-1662: jobruntestcaseanalyzer: add test group to verify upgrade success

pkg/api/types.go
This lease pool will be used in cordination
with:
https://github.com/openshift-splat-team/vsphere-capacity-manager To better utlize our vSphere environments
and provider easier configuration
in ci steps.
=> vSphere - Add elastic lease pool

pkg/jobrunaggregator/jobrunaggregatoranalyzer/pass_fail.go, pkg/jobrunaggregator/jobrunaggregatorapi/bypass_linter.go, pkg/jobrunaggregator/jobrunaggregatorapi/types_row_aggregatedtestrun.go, pkg/jobrunaggregator/jobrunaggregatorapi/types_row_alert.go, pkg/jobrunaggregator/jobrunaggregatorapi/types_row_backenddisruption.go, pkg/jobrunaggregator/jobrunaggregatorapi/types_row_job.go, pkg/jobrunaggregator/jobrunaggregatorapi/types_row_jobrun.go, pkg/jobrunaggregator/jobrunaggregatorapi/types_row_testrun.go, pkg/jobrunaggregator/jobrunaggregatorlib/big_query.go, pkg/jobrunaggregator/jobrunaggregatorlib/ci_data_client.go, pkg/jobrunaggregator/jobrunaggregatorlib/ci_data_client_mock.go, pkg/jobrunaggregator/jobrunaggregatorlib/retrying_ci_data_client.go, pkg/jobrunaggregator/jobrunbigqueryloader/alert.go, pkg/jobrunaggregator/jobrunbigqueryloader/uploader.go, pkg/jobrunaggregator/jobruntestcaseanalyzer/analyzer.go, pkg/jobrunaggregator/jobruntestcaseanalyzer/analyzer_test.go, pkg/jobrunaggregator/jobtableprimer/job_typer.go, pkg/jobrunaggregator/jobtableprimer/jobs.go, pkg/jobrunaggregator/jobtableprimer/jobs_test.go, pkg/jobrunaggregator/tablescreator/cmd.go, pkg/jobrunaggregator/tablescreator/table_creator.go
Reverts openshift/ci-tools#4096
Seeing errors from job-table-updater
```
Creating jobs from releases
Priming jobs
Inserting 54 jobs
time="2024-05-16T18:30:06.673Z" level=fatal msg="Command failed" error="54 row insertions failed (insertion of row [insertID: \"zRq7MrrxXwJCZAY6gKhNxXx8aha\"; insertIndex: 0] failed with error: {Location: \"\"; Message: \"Missing required fields: Msg_0_CLOUD_QUERY_TABLE.architecture, Msg_0_CLOUD_QUERY_TABLE.fromrelease, Msg_0_CLOUD_QUERY_TABLE.ipmode, Msg_0_CLOUD_QUERY_TABLE.network, Msg_0_CLOUD_QUERY_TABLE.platform, Msg_0_CLOUD_QUERY_TABLE.release, Msg_0_CLOUD_QUERY_TABLE.runse2eparallel, Msg_0_CLOUD_QUERY_TABLE.runse2eserial, Msg_0_CLOUD_QUERY_TABLE.runsupgrade, Msg_0_CLOUD_QUERY_TABLE.topology.\"; Reason: \"invalid\"}, insertion of row [insertID: …
```
=> Revert "TRT-1627: Use variant registry for disruption and remove some outdated half implemented view management"

pkg/defaults/defaults.go, pkg/steps/ip_pool.go, pkg/steps/ip_pool_test.go
BYOIP automatically leases `13` ip-pool addresses in the appropriate region when using one of the (for now, hardcoded) relevant cluster profiles. In many cases, less than `13` addresses are actually needed. In order to maximize the savings from these ip pools we must provide a way to release unused leases ASAP. There aren't really many ways to do this without a significant re-architecture of `ci-operator`, but this represents the least intrusive way I could imagine. We look for the presence of an `UNUSED_IP_COUNT` item in the shared-dir secret, and if it is populated by an int, we release that number of leases immediately. If this item isn't found within fifteen minutes, then we stop checking for it. The workflow step will have to be updated to store the proper number in a file with the …
=> `ci-operator`: Allow for the release of unused BYOIP leases

pkg/api/leases.go, pkg/api/types.go, pkg/steps/ip_pool.go, pkg/steps/ip_pool_test.go
Originally, this was hardcoded to only work on the `aws` cluster-profile. This configuration change will make it possible for others to be added as desired. I will be working on adding documentation for this in the cluster-profile area. There is an, in progress, change to cluster-profile configuration that we will be reworking these configs into once it lands.
Also fixed a flaky race condition with the, previously added, unit tests.
=> `BYOIP`: simplify configurations for other cluster-profiles to utilize

pkg/api/types.go
https://docs.ci.openshift.org/docs/how-tos/adding-a-cluster-profile/
I added the aws credentials to vault under `selfservice/stackrox-cluster-profile/credentials`
as `aws_access_key_id` and `aws_secret_access_key` alongside the key: `  "secretsync/target-name": "cluster-secrets-aws-stackrox",`
=> add aws-stackrox cluster profile

cmd/ci-operator-config-mirror/main.go, cmd/ci-operator-config-mirror/main_test.go
Follow up of https://github.com/openshift/ci-tools/pull/3858. I have lost count how many times I have been reworking it.
`Automate config brancher` ([here](https://github.com/openshift/release/pull/52309)) is failing because of two duplicate promotion targets.
The test `pull-ci-openshift-release-master-ci-operator-config` fails with the following error (check [here](https://prow.ci.openshift.org/view/gs/test-platform-results/pr-logs/pull/openshift_release/52309/pull-ci-openshift-release-master-ci-operator-config/1793251806369812480)):
```
time="2024-05-22T12:06:51Z" level=info msg="Configs reloaded" duration=937.032692ms
time="2024-05-22T12:06:53Z" level=error error="output tag hypershift/hypershift:latest is promoted from more than one place: openshift-priv/hypershift@main, …
```
=> ci-operator-config-mirror: disable non ocp promotions

cmd/pj-rehearse/main.go
Follow up https://github.com/openshift/ci-tools/pull/4108
/hold
Require https://github.com/openshift/release/pull/51888
and
Let it soak in production for a whole.
=> pj-rehearse: remove flags for image mirroring

cmd/pr-reminder/main.go
Follow up https://github.com/openshift/release/pull/52523#discussion_r1617818481
The doc should at least be not conflicting to what we used in the configuration.
=> pr-reminder: fix a comment/doc

cmd/dptp-controller-manager/main.go
https://issues.redhat.com/browse/DPTP-3998
/hold
Will watch the rolling.
=> dptp-cm: disable test_images_distributor by default

pkg/steps/rpm_server_test.go
I tried to fix this in https://github.com/openshift/ci-tools/pull/4136, but only applied this method to the ip_pool_lease test. That seemed to clear it up, but it still happens occasionally. Let's do the same thing with the test reporting the race.
=> create the fakectrlruntimeclient within the Run block to avoid flaky datarace

pkg/controller/quay_io_ci_images_distributor/oc_quay_io_image_helper.go
```json
{
"args": "image info quay.io/openshift/ci:ocp-private_4.7-priv_tools --filter-by-os=linux/amd64 --registry-config=/etc/push/.dockerconfigjson --output=json",
"client": "/usr/bin/oc",
"component": "ci-images-mirror",
"error": "exit status 1",
"file": "/go/src/github.com/openshift/ci-tools/pkg/controller/quay_io_ci_images_distributor/oc_quay_io_image_helper.go:49",
"func": "github.com/openshift/ci-tools/pkg/controller/quay_io_ci_images_distributor.(*ocExecutor).Run",
"kubernetes": {
"container_id": "cri-o://39abd267e18e7ca6905a2bfdf328e076b73862ca0f3300246a5de2feed19cc0c",
"container_image": "image-registry.openshift-image-registry.svc:5000/ci/ci-images-mirror@sha256:f5f78246a759d4ac4acd956b15beefb3cf9fa2df24c70e6fb1322a51131f6aec",
"container_name": "ci-images-mirror", …
```
=> quay_io_ci_images_distributor: fix the isNotFound function

pkg/api/types.go
release [openshift/release/pull/52749](https://github.com/openshift/release/pull/52749)
Profile | Profile String | Cloud Type
-- | -- | --
ClusterProfileGCPAutoReleaseQE | gcp-autorelease-qe | gcp
=> OCPQE-22599: Create QE dedicated GCP cluster profile "gcp-autorelease-qe"

cmd/helpdesk-faq/main.go, cmd/slack-bot/main.go, hack/local-slack-bot.sh, pkg/helpdesk-faq/client.go, pkg/helpdesk-faq/types.go, pkg/slack/events/helpdesk/helpdesk-faq.go, pkg/slack/events/helpdesk/helpdesk-message.go, pkg/slack/events/router/router.go
Adds the ability for `slack-bot` to add and remove items from the `helpdesk-faq` (currently a ConfigMap on app.ci) based on emoji reactions on messages in `#forum-ocp-testplatform`
=> `helpdesk-faq`: slack handler to add FAQ items

cmd/pr-reminder/main.go, cmd/pr-reminder/main_test.go
The current design of the configuration for this tool doesn't validate that the same user/repo combination is only provided by one configuration item, so it's not really possible to filter DMs for bot activity, since we would need a different factoring to know which configuration we were using.
/assign @smg247
=> pr-reminder: allow omitting bots

images/ci-operator-minimal/Dockerfile
Adding a new image for smooth transition from centos:stream9 to ubi-minimal
/cc @danilo-gemoli @openshift/test-platform
=> Adding new image for ci-operator with ubi base image

cmd/qci-appci/main.go
Follow up https://redhat-internal.slack.com/archives/CBN38N3MW/p1717668160958539?thread_ts=1717430173.655359&cid=CBN38N3MW
The user `dmanor ` from `group/infrastructure-operator` cannot access QCI.
The group is on the cluster and the user is included.
I think this is the cause:
https://github.com/openshift/release/blob/master/clusters/app.ci/assets/admin_qci-image-puller_rbac.yaml
The reference role is namespaced (`ocp`) and 
```console
$ oc adm policy who-can get imagestreams -n ocp --as system:admin --subresource layers | grep infrastructure-operator
infrastructure-operator
$ oc adm policy who-can get imagestreams --as system:admin --subresource layers | grep infrastructure-operator
```
=> qci-appci: fix SubjectAccessReviewSpec for human users

pkg/helpdesk-faq/types.go, pkg/slack/events/helpdesk/helpdesk-faq.go
This couples us to the formatting of our workflow in Slack, but it also provides a much better user experience for viewing the FAQ items. The workflow changes very infrequently, so it is worth the coupling.
=> `helpdesk-faq`: add: topic, subject, and body fields to question

pkg/steps/input_image_tag.go, pkg/steps/utils/image.go
Saw the error in [this job](https://prow.ci.openshift.org/view/gs/test-platform-results/pr-logs/pull/openshift_release/53047/rehearse-53047-pull-ci-openshift-hypershift-main-e2e-aws/1800525084801110016).
```
{"level":"info","msg":"Running [input:root], [input:ocp_4.16_base-rhel9], [input:ocp_builder_rhel-9-golang-1.22-openshift-4.17], [input:openshift_release_rhel-9-release-golang-1.22-openshift-4.17], [input:cli], [input:ocp-4.16-hypershift-operator], [input:ocp-4.14-hypershift-operator], [release:initial], [release-inputs:latest], src, hypershift, hypershift-operator, [output:stable:hypershift-operator], [output:stable:hypershift], [images], test-bin, [release:latest], e2e-aws","time":"2024-06-11T13:48:09Z"}
...
{"level":"info","msg":"Tagging ocp/4.14:hypershift-operator into …
```
=> ci-op: waitForTagInSpec

pkg/slack/events/helpdesk/helpdesk-faq.go, pkg/slack/events/helpdesk/helpdesk-faq_test.go
Slack [adds](https://api.slack.com/reference/surfaces/formatting#escaping) a "<" and ">" around links from their api. We don't want this formatting, and must remove it prior to saving down the question or answer.
=> `helpdesk-faq`: remove special slack formatting from links

pkg/release/candidate/client.go, pkg/release/prerelease/client.go
```
INFO[2024-06-13T09:47:26Z] Promoting tags to registry.ci.openshift.org/ocp/4.17:${component}: openshift-controller-manager  name=promotion
INFO[2024-06-13T09:47:26Z] Requesting a release from https://amd64.ocp.releases.ci.openshift.org/api/v1/releasestream/4-stable/latest 
INFO[2024-06-13T09:47:31Z] Promoting tags to quay.io/openshift/ci:ocp_4.17_${component}: openshift-controller-manager  name=promotion-quay
INFO[2024-06-13T09:47:[31](https://prow.ci.openshift.org/view/gs/test-platform-results/logs/branch-ci-openshift-openshift-controller-manager-master-images/1801189505684738048#1:build-log.txt%3A31)Z] Requesting a release from https://amd64.ocp.releases.ci.openshift.org/api/v1/releasestream/4-stable/latest 
INFO[2024-06-13T09:48:22Z] Ran for 57s …
```
=> Improve logging for promotion

pkg/util/testgrid.go
Jobs will be added in https://github.com/openshift/release/pull/53236
We will remove the old locations as a follow-up.
=> OSASINFRA-3477: openstack: Add new location for OpenStack periodics to Sippy

cmd/helpdesk-faq/main.go, cmd/slack-bot/main.go, hack/local-slack-bot.sh, pkg/helpdesk-faq/client.go, pkg/helpdesk-faq/types.go, pkg/helpdesk-faq/types_test.go, pkg/slack/events/helpdesk/helpdesk-faq.go, pkg/slack/events/helpdesk/helpdesk-faq_test.go, pkg/slack/events/router/router.go
Contributing info will be used for replies to the thread that add context, rather than answer it.
Also, makes it possible to run locally using the `ci-staging` ns.
=> `helpdesk-faq`: add contributing-info to faq-items

cmd/helpdesk-faq/main.go, cmd/slack-bot/main.go, hack/local-slack-bot.sh, pkg/helpdesk-faq/client.go, pkg/helpdesk-faq/client_test.go, pkg/helpdesk-faq/types.go, pkg/helpdesk-faq/types_test.go, pkg/slack/events/helpdesk/helpdesk-faq.go, pkg/slack/events/helpdesk/helpdesk-faq_test.go, pkg/slack/events/router/router.go
Answers and Contributing Info should be sorted ascending by timestamp. I took the approach of sorting them when the faq-item is added or modified.
/hold Builds on https://github.com/openshift/ci-tools/pull/4180, merge this after
=> `helpdesk-faq`: sort replies on upload

images/job-run-aggregator/Dockerfile
The latest [weekly PR run](https://prow.ci.openshift.org/view/gs/test-platform-results/logs/periodic-update-origin-disruption-alert-data/1801419585887408128) shows:
```
failed to check for changes: running command git [status --porcelain]: exec: \"git\": executable file not found in $PATH
```
indicating the `git` executable needs to be installed.
=> install git for job-run-aggregator for weekly disruption PR

pkg/api/types.go
Removing possibly deprecated gcp-40 cluster profile.
/cc @droslean @vrutkovs 
/hold
Associated config map in relese repo is being removed in: https://github.com/openshift/release/pull/53299
=> Remove gcp-40 cluster profile

pkg/helpdesk-faq/client.go, pkg/helpdesk-faq/client_test.go
Since a cache is used here, the method only gets called once every 15 minutes. A little extra time to sort it won't hurt us.
Also, added unit tests for the entire client.
=> `helpdesk-faq`: sort items when returning a serialized list

pkg/api/types.go
These cluster profiles are derivatives (same Secret and Lease) of gcp cluster profile, and they are not used anywhere.
/cc @droslean @jmguzik
=> Remove gcp-logging-journald, gcp-logging-json-file, gcp-logging-crio profiles

images/ci-operator/Dockerfile
The clusterbot runs custom `ci-operator` scripts that utilize a handful of commands that were lost with: https://github.com/openshift/ci-tools/pull/4160.  
For reference:
https://prow.ci.openshift.org/view/gs/test-platform-results/logs/release-openshift-origin-installer-launch-aws-modern/1804072048717205504
This PR adds the commands that should allow our scripts to run again.
=> Adding missing commands

pkg/api/types.go
This cluster profile is not used anywhere.
A part of the initiative to clean up possibly deprecated derivative cluster profiles (profiles which share both secret and leases with the original aws/gcp/vsphere cluster profile).
/cc @AsherShoshan @droslean
=> Remove aws-outpost cluster profile

images/pr-reminder/Dockerfile
`ubi-minimal` doesn't contain tar or gzip. I tested this by using a locally built image to run the job.
=> add tools to `pr-reminder` image

cmd/autoowners/main.go, cmd/autoowners/main_test.go
Some upstream files include this in front of usernames. It makes it so that the file cannot be loaded as yaml as there are no quotes around the names. We can just remove the symbol to make the files valid.
Note: the ignore-repo logic still attempts to load the file in one confusing case even if it is set to ignore all 3 directories for the repo. I am going to look into fixing and simplifying this logic in a follow up.
For: https://issues.redhat.com/browse/DPTP-4061
=> `autoowners`: prune '@' from OWNERS file contents

pkg/api/types.go, pkg/validation/test_test.go
Related PRs for release repo:
- aws-centos: https://github.com/openshift/release/pull/53666
- aws-atomic & aws-gluster: https://github.com/openshift/release/pull/53571
This PR is a part of the initiative to clean up possibly deprecated derivative cluster profiles (profiles which share both secret and leases with the original aws/gcp/vsphere cluster profile).
=> Remove aws-atomic, aws-centos, aws-gluster cluster profiles

pkg/util/testgrid.go
A follow-up to https://github.com/openshift/ci-tools/pull/4182
Depends on https://github.com/openshift/release/pull/53236
=> OSASINFRA-3477: openstack: Remove legacy location for OpenStack periodics from Sippy

cmd/slack-bot/main.go, pkg/slack/events/helpdesk/helpdesk-message.go, pkg/slack/events/helpdesk/helpdesk-message_test.go, pkg/slack/events/router/router.go
The bot ID changed recently. Since this can change, we should make it configurable while updating the default to the new ID.
=> `slack-bot`: fix review request workflow response

.golangci.yml, cmd/qci-appci/main.go
It looks like the linter isn't sophisticated enough to handle this one as is:
```
cmd/qci-appci/main.go:393:99: defers: call to time.Since is not deferred (govet)
defer s.logger.WithField("username", username).WithField("validated", ret).WithField("duration", time.Since(t)).Debug("Validated token")
```
Also, removes the deprecated 'deadcode' linter whose existence is throwing an error message, and updates to use the new 'timeout' param
=> fix linter issue

pkg/api/types.go, pkg/load/load.go, pkg/load/load_test.go
Implemented new logic; when loading cluster profiles from their [config file](https://github.com/openshift/release/blob/master/ci-operator/step-registry/cluster-profiles/cluster-profiles-config.yaml), we autogenerate the secret name for each cluster profile. If a profile had the secret field defined in the config, we will use that one (this is mainly for keeping backwards compatibility with a few  derivative cluster profiles that don't follow the naming convention; I added those to the config file in https://github.com/openshift/release/pull/53787). 
The result of this is that `config-resolver` will be able to provide the secret for each cluster profile. 
Now:
```
$ curl "https://config.ci.openshift.org/clusterProfile?name=packet"
{
"profile": "packet"
}
```
After this PR merges:
```
$ …
```
=> Add default secret logic for cluster profiles

pkg/defaults/defaults.go, pkg/defaults/defaults_test.go, pkg/steps/multi_stage/multi_stage.go, pkg/steps/multi_stage/multi_stage_test.go
This is necessary so steps can use the original values when `RELEASE_IMAGE_INITIAL` and/or `RELEASE_IMAGE_LATEST` env vars are provided. These values get overwritten when resolving the release, so we must provide alternatives to use in the steps.
For: https://issues.redhat.com/browse/DPTP-4070
=> `ci-operator`: pass `ORIGINAL_*` env vars to the multi-stage steps

pkg/config/load.go, pkg/config/load_test.go, pkg/jobconfig/files.go, pkg/prowgen/jobbase.go, pkg/prowgen/jobbase_test.go, pkg/prowgen/testdata/zz_fixture_TestNewProwJobBaseBuilderForTest_simple_with_slack_reporter_config.yaml, test/integration/ci-operator-prowgen/input/config/slack-report/duper/.config.prowgen, test/integration/ci-operator-prowgen/input/config/slack-report/duper/slack-report-duper-master.yaml, test/integration/ci-operator-prowgen/output/jobs/slack-report/duper/slack-report-duper-master-periodics.yaml, test/integration/ci-operator-prowgen/output/jobs/slack-report/duper/slack-report-duper-master-postsubmits.yaml, test/integration/ci-operator-prowgen/output/jobs/slack-report/duper/slack-report-duper-master-presubmits.yaml
This also allows the ability to use the slack reporter functionality for postsubmits and periodics. It leaves the possibility for existing slack reporter configs in periodics to behave as they currently do, with the option to remove that later once configs are migrated.
The new integration test case showcases an example of how this can be used, but I will be following this up with a change to the docs and an announcement.
Example usage in `.prowgen.config`, this would generate slack_reporter configs in the `unit`, `upload-results`, and `lint` jobs.
```
slack_reporter:
- channel: "#slack-channel"
job_states_to_report:
- success
- failure
- error
report_template: '{{if eq .Status.State "success"}} :rainbow: Job *{{.Spec.Job}}*
ended with *{{.Status.State}}*. <{{.Status.URL}}|View logs> …
```
=> `prowgen`: allow the ability to configure the slack reporter config

pkg/config/load.go, pkg/config/load_test.go, pkg/prowgen/jobbase.go, test/integration/ci-operator-prowgen/input/config/slack-report/duper/.config.prowgen, test/integration/ci-operator-prowgen/input/config/slack-report/duper/slack-report-duper-master__exclude.yaml, test/integration/ci-operator-prowgen/output/jobs/slack-report/duper/slack-report-duper-master-periodics.yaml, test/integration/ci-operator-prowgen/output/jobs/slack-report/duper/slack-report-duper-master-postsubmits.yaml, test/integration/ci-operator-prowgen/output/jobs/slack-report/duper/slack-report-duper-master-presubmits.yaml
The intention here is that specific variants can be excluded from having the config added, despite sharing the same test name. This will be useful for having older release jobs no longer report, for instance.
Follows up on: https://github.com/openshift/ci-tools/pull/4217
For: https://issues.redhat.com/browse/DPTP-3366
=> `prowgen`: add the option to exclude variants from having a slack reporter config added

cmd/ci-operator/main.go, pkg/defaults/defaults.go
This is some low-hanging fruit for `images` jobs' performance improvements. Publishing images to `quay.io` and the internal registry can be done in parallel with no concerns.
The changes to `defaults.go` are just to make it more clear that the `postSteps` we are referring to here are specifically `promotion` steps.
I have done a few [runs](https://prow.ci.openshift.org/job-history/gs/test-platform-results/logs/branch-ci-openshift-ci-tools-master-images-sgoeddel) of this now (with an image built on my machine), and it is showing a speed-up of _at least_ 20 mins over the best times in the production image.
=> `ci-operator`: promote to all registries in parallel

cmd/ci-operator/main.go
Follows up on https://github.com/openshift/ci-tools/pull/4220
Uses buffered channels to make sure that we don't have a goroutine leak. In practice, this would not be a big deal as this is the end of the process anyways, but we should fix this bug.
=> `ci-operator`: fix potential goroutine leak when one of the promotion steps fails

Makefile, hack/build-and-push.sh
I have been using a less generic version of this script for awhile. It's usage is as follows:
```
TOOL=autoowners QUAY_ACCOUNT=sgoeddel make build-and-push-image
```
This will build the `autoowners` cmd and publish it to my quay account. It can build any cmd that has a DOCKERFILE in the `/images` directory (most of the complex ones). DOCKERFILES can be added there when needed. Useful for trying out WIP changes.
=> adds a new script to help build and push a ci-tools cmd image to the requested quay account

pkg/helpdesk-faq/client.go, pkg/helpdesk-faq/client_test.go
It is more useful to have the recently asked questions appear higher in the listing
=> `helpdesk-faq`: sort serialized FAQ items most recent first

pkg/api/types.go
Adding profile to create jobs on AWS account owned by SPLAT team, authorizing the OPCT projects to run on it.
OPCT project is a tool used by partners to orchestrate conformance workflows executed by openshift-tests utility.
The CI jobs is used to get signals from existing OCP payloads, currently it is already have periodics in vSPhere, it is required to introduce in AWS to collect from a public cloud, as the main goal of partners is to validate their cloud provider installations.
References:
- https://issues.redhat.com/browse/OPCT-231
- https://redhat-internal.slack.com/archives/CBN38N3MW/p1721761510597799
=> OPCT-231: Add profile for OPCT projects on AWS team account

cmd/ci-images-mirror/main.go
We do this for logging.
It used to work (at least for the logs uploaded to CloudWatch) without it but not any more.
Tested the PR locally, it does the job:
```
{"component":"ci-images-mirror","file":"/Users/hongkliu/repo/openshift/ci-tools/cmd/ci-images-mirror/main.go:322","func":"main.main","level":"info","msg":"Process ended gracefully","severity":"info","time":"2024-07-31T10:14:13-04:00"}
```
=> ci-images-mirror: set version.Name

pkg/api/types.go, pkg/steps/project_image.go, pkg/steps/source.go, pkg/steps/source_test.go, pkg/webreg/zz_generated.ci_operator_reference.go
Add the `multi_arch` configuration to the `images` stanza. It defaults to false which is a breaking change.
[DPTP-4093](https://issues.redhat.com/browse/DPTP-4093)
/cc @openshift/test-platform @smg247 
=> [DPTP-4093] [ci-operator] introduce a configuration to control the multi arch builds for single images

pkg/steps/project_image.go, pkg/steps/source.go
Follow-up of https://github.com/openshift/ci-tools/pull/4231
All base ci-operator image builds should be multi-arch. This change respects the images stanza configuration to allow the user to choose which images should be built for multi arch.  
/cc @openshift/test-platform @deepsm007 
=> enable multi-arch builds by default but respect the configuration from the images stanza

pkg/jobrunaggregator/jobrunaggregatorlib/ci_data_client.go, pkg/jobrunaggregator/jobrunaggregatorlib/util.go
Reverts openshift/ci-tools#4244
Seeing failures like
```
time="2024-08-08T12:05:43.517Z" level=info msg="listing prow jobs since" since="2024-08-07 19:27:46 +0000 UTC"
time="2024-08-08T12:05:43.617Z" level=fatal msg="Command failed" error="error listing uploaded job run IDs: failed to query job table with \"SELECT JobRunName as JobRunID \\nFROM openshift-ci-data-analysis.ci_data.Alerts\\nWHERE JobRunEndTime >= @Since\\n AND JobRunStartTime >= TIMESTAMP_SUB(@Since, INTERVAL 12 HOUR)\\nORDER BY JobRunEndTime ASC\\n\": googleapi: Error 400: Label value \"aggregator-job-run-IDs-since-time\" has invalid characters., invalid"
```
=> Revert "TRT-1706: Use big query labels with aggregator"

pkg/jobrunaggregator/jobrunaggregatoranalyzer/analyzer_disruption.go
Kubeapiserver in-cluster monitors now watch external/internal lb, service network and localhost. Localhost disruptions are informational only, so they should not cause tests to fail
=> jobaggregator: exclude disruption if backend is localhost

cmd/pod-scaler/main.go
This will remove the disabled cluster(s) from the client, resulting in not attempting to query their prometheus data. This allows the tool to function even when a cluster is unreachable
=> `pod-scaler`: honor prow's `disabled_clusters` configuration

pkg/jobrunaggregator/jobrunaggregatoranalyzer/analyzer_disruption.go
There is no way for us to differentiate between "real" internal LB in the cloud or fake one in SNO, so this disruption is not being alerted upon.
Ref: https://github.com/openshift/origin/pull/28982
=> jobdisruption: exclude internal-lb

pkg/controller/quay_io_ci_images_distributor/supplemental_images.go, pkg/controller/quay_io_ci_images_distributor/supplemental_images_test.go
Follow up https://redhat-internal.slack.com/archives/CBN38N3MW/p1723581480388669?thread_ts=1723578729.523639&cid=CBN38N3MW
=> ci-images-mirror: sync rhel-coreos images for ART

cmd/payload-testing-prow-plugin/server.go, cmd/payload-testing-prow-plugin/server_test.go
This validation is added to ensure that commands that are only possible to execute once per comment are not requested multiple times.
There was previously documentation stating that this wasn't possible, but it is easy for people to miss. The error message returned in this case was cryptic, and it was unclear what the problem with the comment was.
=> `payload-testing-prow-plugin`: add validation for singular commands

cmd/prow-job-dispatcher/gob.go, cmd/prow-job-dispatcher/main.go, cmd/prow-job-dispatcher/main_test.go, cmd/prow-job-dispatcher/prometheus_volumes.go, cmd/prow-job-dispatcher/prometheus_volumes_test.go, cmd/prow-job-dispatcher/prowjobs.go, cmd/prow-job-dispatcher/server.go, go.mod, go.sum, vendor/github.com/robfig/cron/v3/.gitignore, vendor/github.com/robfig/cron/v3/.travis.yml, vendor/github.com/robfig/cron/v3/LICENSE, vendor/github.com/robfig/cron/v3/README.md, vendor/github.com/robfig/cron/v3/chain.go, vendor/github.com/robfig/cron/v3/constantdelay.go, vendor/github.com/robfig/cron/v3/cron.go, vendor/github.com/robfig/cron/v3/doc.go, vendor/github.com/robfig/cron/v3/logger.go, vendor/github.com/robfig/cron/v3/option.go, vendor/github.com/robfig/cron/v3/parser.go, vendor/github.com/robfig/cron/v3/spec.go, vendor/modules.txt
Dispatcher reworked to operate as _daemon_ as well, keeping all it's previous functionalities intact. Old tests should pass. Added some helpers like:
1. mutexed struct for prometheus data
2. mutexed struct for prowjobs/cluster information
3.  io for gob file (as a permanent database)
4. REST server
Configuration that holds cluster assignments (`yaml`):
```
aws:
- build01
- build05
- build09
- build03
- build11
gcp:
- build02
- build04
blocked:
- build10
```
`blocked` clusters will be **totally** blocked. That means even if jobs are manually assigned in the config to be bound to certain cluster, if this cluster is blocked, job will be relocated forcefully, either to cluster which is similar to the most jobs from the file, or _default_ cluster. 
How to invoke:
```
./prow-job-dispatcher …
```
=> Daemonized prowjob dispatcher to serve as backend for the scheduler

cmd/pod-scaler/admission.go, cmd/pod-scaler/admission_test.go, cmd/pod-scaler/consumer.go, cmd/pod-scaler/frontend.go, cmd/pod-scaler/frontend_test.go, cmd/pod-scaler/main.go, cmd/pod-scaler/resources.go, cmd/pod-scaler/v2/producer.go, cmd/pod-scaler/v2/storage.go, test/e2e/pod-scaler/e2e_test.go, test/e2e/pod-scaler/prometheus/backfill.go
After some time of v2 data gathering, it will be time to utilize that data with the consumers. This is a fairly simple change as we just need to swap out `v1` for `v2` in many places. The only significant difference here is accessing the `fingerprint` within the `fingerprintTime` struct. Once we confirm this is working correctly, all `v1` logic will be removed entirely and the data will be purged. 
For: https://issues.redhat.com/browse/DPTP-4069
/hold to merge when we have sufficient v2 data available
=> `pod-scaler`: update consumers and e2e tests to use v2 data

pkg/api/types.go
'local-zones' profile was initially used in the development phase to
support AWS Local Zones on installer on supported regions filtered by
quota-slice.
Currently the jobs have been moved to default AWS CI Account, we need to
rename the quota slice to 'edge-zones' as for now it isn't testing only
Local Zones, but also Wavelength Zone.
The release repo cleanup is addressed in this PR: https://github.com/openshift/release/pull/54784
=> SPLAT-1715: remove unused profile 'local-zones'

pkg/controller/prpqr_reconciler/prpqr_reconciler.go, pkg/controller/prpqr_reconciler/testdata/zz_fixture_prowjobs_TestReconcile_basic_aggregated_case.yaml, pkg/controller/prpqr_reconciler/testdata/zz_fixture_prowjobs_TestReconcile_basic_aggregated_case_with_scheduling.yaml, pkg/controller/prpqr_reconciler/testdata/zz_fixture_prowjobs_TestReconcile_basic_case.yaml, pkg/controller/prpqr_reconciler/testdata/zz_fixture_prowjobs_TestReconcile_basic_case_with_cluster_override.yaml, pkg/controller/prpqr_reconciler/testdata/zz_fixture_prowjobs_TestReconcile_basic_case_with_metal_override.yaml, pkg/controller/prpqr_reconciler/testdata/zz_fixture_prowjobs_TestReconcile_basic_case_with_scheduling.yaml, pkg/controller/prpqr_reconciler/testdata/zz_fixture_prowjobs_TestReconcile_basic_case_with_variant.yaml, pkg/controller/prpqr_reconciler/testdata/zz_fixture_prowjobs_TestReconcile_basic_case_with_vsphere_override.yaml, pkg/controller/prpqr_reconciler/testdata/zz_fixture_prowjobs_TestReconcile_basic_case_without_PR__testing_specified_base.yaml, pkg/controller/prpqr_reconciler/testdata/zz_fixture_prowjobs_TestReconcile_multiple_case__one_of_the_prowjobs_already_exists.yaml, pkg/controller/prpqr_reconciler/testdata/zz_fixture_prowjobs_TestReconcile_override_initial_and_base_payload_pullspecs.yaml, pkg/jobrunaggregator/jobrunaggregatoranalyzer/analyzer.go
Complimentary to https://github.com/openshift/release/pull/55094
=> Increase timeouts for payload jobs to land k8s 1.31

cmd/ci-secret-bootstrap/main.go, cmd/ci-secret-bootstrap/main_test.go, cmd/cluster-init/cmd/onboard/update_bootstrap_secrets.go, pkg/api/domain.go, test/integration/cluster-init/create/expected/core-services/ci-secret-bootstrap/_config.yaml, test/integration/cluster-init/update/expected/core-services/ci-secret-bootstrap/_config.yaml
Until https://issues.redhat.com/browse/OCPBUGS-38737 is fixed, there is no way we can make both happy unless we fully qualify both repos under openshift/ that the bot needs access to. That is, '[quay.io/openshift/ci](http://quay.io/openshift/ci)' and '[quay.io/openshift/network-edge-testing](http://quay.io/openshift/network-edge-testing)' explicitly in the pull-secret
=> Support Network-edge-testing repo for pull token

pkg/api/ocpbuilddata/types.go
`image configs from ocp-build-data: error validating images/okd-only-upi-installer.yml: [.from.5 failed validation: both stream and member were unset, .from.6 failed validation: both stream and member were unset, .from.7 failed validation: both stream and member were unset, .from.8 failed validation: both stream and member were unset]"
`
=> Fix validation for ocp-build-data from.builder.image

cmd/prow-job-dispatcher/main.go, cmd/prow-job-dispatcher/main_test.go, cmd/prow-job-dispatcher/prometheus_volumes.go, cmd/prow-job-dispatcher/prowjobs.go, cmd/prow-job-dispatcher/testdata/TestDispatchJobs/basic_case/xyz-operator-presubmits.yaml, cmd/sanitize-prow-jobs/main.go, go.mod, pkg/dispatcher/config.go, pkg/sanitizer/determinize.go, pkg/sanitizer/determinize_test.go
- remove multithreading to boost determinism of the algorithm
- until 75% of per cluster capacity try to assign to previous cluster (if existing)
- above 75% or if cluster disabled/blocked, take cluster with lowest amount of volumes (as it was before)
- take files to process from largest to smallest (assumption: it will allow larger test groups to be reassigned to the same cluster as before)
- honor exceptions and e2e colocation per test
**Note**: https://github.com/openshift/ci-tools/pull/4275 has to be merged.
=> Changes in dispatching algorithm

cmd/ci-operator/main.go, pkg/api/graph.go, pkg/api/graph_test.go, pkg/defaults/defaults.go, pkg/steps/bundle_source.go, pkg/steps/git_source.go, pkg/steps/index_generator.go, pkg/steps/pipeline_image_cache.go, pkg/steps/project_image.go, pkg/steps/rpm_injection.go, pkg/steps/rpm_server.go, pkg/steps/source.go
These changes introduce the multi-arch property in the step graph. The steps that are building images will include all architecture if the image is needed by another step that is marked as multi-arch. 
Currently, the only step the user controls is the `ProjectDirectoryImageBuildStep`, which is the images stanza in the ci-operator configuration. If the user marks a specific image as multi-arch, all image build steps that are dependencies will also be built for multi-arch.  
=> [ci-operator] resolve the multi-arch dependencies in the image tree graph

Makefile
we increased this from 1 to 25 runs to decrease flakes, but 10 times should be sufficient while taking less time to complete.
=> integration tests are taking too long, reduce to 10 iterations

cmd/ci-operator/main.go, cmd/ci-operator/main_test.go, pkg/api/graph.go, pkg/api/graph_test.go, pkg/steps/cluster_claim.go, pkg/steps/clusterinstall/clusterinstall.go, pkg/steps/images_ready.go, pkg/steps/input_env.go, pkg/steps/input_image_tag.go, pkg/steps/ip_pool.go, pkg/steps/ip_pool_test.go, pkg/steps/lease.go, pkg/steps/lease_test.go, pkg/steps/multi_stage/multi_stage.go, pkg/steps/output_image_tag.go, pkg/steps/pod.go, pkg/steps/project_image.go, pkg/steps/release/create_release.go, pkg/steps/release/import_release.go, pkg/steps/release/promote.go, pkg/steps/release/release_images.go, pkg/steps/release/snapshot.go, pkg/steps/rpm_server.go, pkg/steps/run_test.go, pkg/steps/template.go, pkg/steps/write_params.go
- Remove the MultiArchStep wrapper to avoid refactoring the whole StepNode graph resolution.
- Add the necessary methods to all steps for multi-arch.
- Change the multi-arch resolution to the partial graph instead
- Update the tests
- For the test steps, we treat them as multi-arch if their `nodeArchitecture` is non AMD64
/cc @openshift/test-platform @deepsm007 
=> DPTP-4147 fix resolving multi-arch for all steps nodes in the graph

pkg/jobrunaggregator/jobrunaggregatoranalyzer/analyzer_test.go, pkg/jobrunaggregator/jobrunaggregatorlib/disruption.go
This adds several tests checking that jobrun aggregator is correctly throwing errors on disruption tests
=> Jobrunaggregator analyzer: add unit tests

cmd/ci-images-mirror/main.go, pkg/controller/quay_io_ci_images_distributor/quay_io_ci_images_distributor.go, pkg/controller/quay_io_ci_images_distributor/supplemental_images.go
This PR adds the option to validate the ci-images-mirror config: [core-services/image-mirroring/_config.yaml](https://github.com/openshift/release/blob/master/core-services/image-mirroring/_config.yaml)
Issue: [DPTP-3915](https://issues.redhat.com/browse/DPTP-3915)
=> ci-images-mirror: add --validate-config-only option

pkg/registry/server/server.go, test/integration/ci-operator-configresolver.sh, test/integration/ci-operator-configresolver/expected/openshift-installer-console-merged-release-4.2-installer-as-base.json
This only applies when the requested injected test belongs to a config that is being merged. This allows for the entire config containing the injected test to be trivially included in the output without the need for the refs. It simplifies the logic for multi-pr presubmit testing in ci-operator without compromising functionality from payload testing.
For: https://issues.redhat.com/browse/DPTP-2894
=> `ci-operator-configresolver`: base output off of config that requested test is injected from

cmd/ci-operator/main.go, pkg/defaults/defaults.go, pkg/labeledclient/client.go, pkg/steps/multi_stage/testdata/zz_fixture_TestGenerateObservers.yaml, pkg/steps/multi_stage/testdata/zz_fixture_TestGeneratePods.yaml, pkg/steps/pod.go, pkg/steps/rpm_server.go, pkg/steps/source.go, pkg/steps/testdata/zz_fixture_TestBuildFromSource_build_args.yaml, pkg/steps/testdata/zz_fixture_TestBuildFromSource_ref_specified.yaml, pkg/steps/testdata/zz_fixture_TestCreateBuild_basic_options_for_a_presubmit.yaml, pkg/steps/testdata/zz_fixture_TestCreateBuild_title_in_pull_gets_squashed.yaml, pkg/steps/testdata/zz_fixture_TestCreateBuild_with_OAuth_token.yaml, pkg/steps/testdata/zz_fixture_TestCreateBuild_with_a_path_alias.yaml, pkg/steps/testdata/zz_fixture_TestCreateBuild_with_a_pull_secret.yaml, pkg/steps/testdata/zz_fixture_TestCreateBuild_with_extra_refs.yaml, pkg/steps/testdata/zz_fixture_TestCreateBuild_with_extra_refs_setting_workdir_and_path_alias.yaml, pkg/steps/testdata/zz_fixture_TestCreateBuild_with_ssh_key.yaml, pkg/steps/testdata/zz_fixture_TestPodStepExecution_Pod_run_by_PodStep_fails_so_PodStep_terminates_and_returns_an_error.yaml, pkg/steps/testdata/zz_fixture_TestPodStepExecution_Pod_run_by_PodStep_succeeds_so_PodStep_terminates_and_returns_no_error.yaml, pkg/steps/testdata/zz_fixture_TestPodStepExecution_Successful_pod_with_cloning.yaml
This PR adds:
- LabeledClient wrapper for labeling all resources ci-operator creates
- ProwJob information labels to the already existing labels
Resolves: [DPTP-4117](https://issues.redhat.com/browse/DPTP-4117)
=> ci-operator: label all resources it creates

cmd/ci-operator/main.go, pkg/defaults/defaults.go, pkg/defaults/defaults_test.go
Since https://github.com/openshift/ci-tools/pull/4311 has merged, the `ci-operator-configresolver` now will not include the ref information for the primary ref. That is due to it being the ref that the requested test comes from. In order to support multi-pr presubmit testing, `ci-operator` needs to be slightly modified to generate build steps for the primary ref that don't include the ref suffixes, etc..
For: https://issues.redhat.com/browse/DPTP-2894
=> `ci-operator`: treat building the primary ref differently from the extra_refs

test/validate-generation-breaking-changes.sh
The `cluster-init` tool needs now a valid set of kubeconfigs.
I will follow this up in `o/release`.
=> Fix `check-breaking-changes` integration test

cmd/payload-testing-prow-plugin/main.go
> The logs show that the config agent is constantly reloading configs. As soon as the reload is complete, it starts another. I believe this may be due to improper error handling. It also seems that the plugin is behaving non-deterministically in finding matching jobs, and I think this might have something to do with it.
Tested this out, and no errors popped up. Everything seemed to be working properly. Once this change lands we will monitor it, and if something goes wrong, we will notice the restarts and can investigate the error.
For: https://issues.redhat.com/browse/DPTP-4172
=> `payload-testing-prow-plugin`: handle errors from config reload

pkg/api/types.go
new cluster profile for the ARO (managed Openshift on Azure) team
also see https://github.com/openshift/release/pull/56644
=> Add new cluster profile aro-redhat-tenant

cmd/ci-operator/main.go, pkg/prowgen/jobbase.go
We will use template to create the firewall object when NS creates. `ci-operator` just need to delete those created object on-demand.
=> Fix issue DPTP-4032 Delete firewall when RH intranet access is desired

cmd/payload-testing-prow-plugin/main.go
Adds the argument, and populates with the proper default value for the symlink watcher. I thought that we could use the "ci-op-config-dir" for this, but that results in the following error:
```json
{"component":"payload-testing-prow-plugin","error":"readlink /var/repo/release/ci-operator/config: invalid argument","file":"/go/src/github.com/openshift/ci-tools/pkg/load/agents/utils.go:137","func":"github.com/openshift/ci-tools/pkg/load/agents.(*UniversalSymlinkWatcher).GetWatcher.func1","level":"error","msg":"couldn't read the destination link of /var/repo/release/ci-operator/config","severity":"error","time":"2024-09-18T22:20:51Z"}
```
This follows the same pattern as the other tools using the symlink watcher.
=> `payload-testing-prow-plugin`: add "release-repo-git-sync-path"

cmd/ci-operator/main.go, pkg/defaults/defaults.go, pkg/labeledclient/client.go, pkg/labeledclient/client_test.go, pkg/steps/multi_stage/testdata/zz_fixture_TestGenerateObservers.yaml, pkg/steps/multi_stage/testdata/zz_fixture_TestGeneratePods.yaml, pkg/steps/pod.go, pkg/steps/rpm_server.go, pkg/steps/source.go, pkg/steps/testdata/zz_fixture_TestBuildFromSource_build_args.yaml, pkg/steps/testdata/zz_fixture_TestBuildFromSource_ref_specified.yaml, pkg/steps/testdata/zz_fixture_TestCreateBuild_basic_options_for_a_presubmit.yaml, pkg/steps/testdata/zz_fixture_TestCreateBuild_title_in_pull_gets_squashed.yaml, pkg/steps/testdata/zz_fixture_TestCreateBuild_with_OAuth_token.yaml, pkg/steps/testdata/zz_fixture_TestCreateBuild_with_a_path_alias.yaml, pkg/steps/testdata/zz_fixture_TestCreateBuild_with_a_pull_secret.yaml, pkg/steps/testdata/zz_fixture_TestCreateBuild_with_extra_refs.yaml, pkg/steps/testdata/zz_fixture_TestCreateBuild_with_extra_refs_setting_workdir_and_path_alias.yaml, pkg/steps/testdata/zz_fixture_TestCreateBuild_with_ssh_key.yaml, pkg/steps/testdata/zz_fixture_TestPodStepExecution_Pod_run_by_PodStep_fails_so_PodStep_terminates_and_returns_an_error.yaml, pkg/steps/testdata/zz_fixture_TestPodStepExecution_Pod_run_by_PodStep_succeeds_so_PodStep_terminates_and_returns_no_error.yaml, pkg/steps/testdata/zz_fixture_TestPodStepExecution_Successful_pod_with_cloning.yaml
This PR resolves issues:
`{  could not create RPM repo server deployment: Deployment.apps "rpm-repo" is invalid: [spec.selector.matchLabels: Invalid value: "[images]": a valid label must be an empty string or consist of alphanumeric characters, '-', '_' or '.', and must start and end with an alphanumeric character (e.g. 'MyValue',  or 'my_value',  or '12345', regex used for validation is '(([A-Za-z0-9][-A-Za-z0-9_.]*)?[A-Za-z0-9])?'), spec.selector: Invalid value: v1.LabelSelector{MatchLabels:map[string]string{"OPENSHIFT_CI":"true", "app":"rpm-repo", "ci.openshift.io/jobid":"a48ae780-8696-4a50-9c09-c173d61e75ad", "ci.openshift.io/jobname":"branch-ci-openshift-kubernetes-release-4.17-images", "ci.openshift.io/jobtype":"postsubmit", "ci.openshift.io/metadata.branch":"release-4.17", …
=> ci-operator: label all resources it creates (2nd attempt)

cmd/prow-job-dispatcher/main.go, pkg/dispatcher/client.go, pkg/dispatcher/gob.go, pkg/dispatcher/prowjobs.go, pkg/dispatcher/server.go, pkg/dispatcher/server_test.go
This moves the server and necessary logic into the `pkg/dispatcher`, and adds a `client`. This is necessary for tools like `payload-testing's` `prpqr_reconciller` and `multi-pr-prow-plugin` to be able to know which `cluster` to set on job's they create.
/cc @jmguzik @openshift/test-platform
=> `prowjob-dispatcher`: refactor dispatcher and create a client for use by other tools

pkg/load/agents/utils.go
`payload-testing-prow-plugin` is being periodically restarted when it reloads configs. This is due to the recent [introduction](https://github.com/openshift/ci-tools/pull/4330) of the `universalSymlinkWatcher`. The plugin only needs a `ConfigAgent`, and doesn't require a `RegistryAgent`. The watcher assumes that both have been configured, while it is possible that either have been left off. The error in the logs looks like:
```
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x1e1470c]
goroutine 45 [running]:
github.com/openshift/ci-tools/pkg/load/agents.startWatchers.func1({0x2bcf0a0, 0xc0078b3630})
/go/src/github.com/openshift/ci-tools/pkg/load/agents/utils.go:37 +0x1cc …
```
=> Allow for either of the configAgentFn or registryAgentFn to be nil

cmd/config-change-trigger/main.go, cmd/pj-rehearse/main.go, cmd/pj-rehearse/server.go, pkg/diffs/diffs.go, pkg/diffs/diffs_test.go, pkg/rehearse/jobs.go, pkg/rehearse/jobs_test.go, pkg/rehearse/rehearse.go, test/integration/pj-rehearse/candidate/ci-operator/config/super/trooper/super-trooper-master.yaml
This is done to disallow rehearsing any test that bypasses the firewall without first having someone reviewed the configuration.
Iff we find other cases where specific fields being changed should disable the entire rehearsal, we could make this logic more general. For now, this is sufficient.
For: https://issues.redhat.com/browse/DPTP-4171
=> `pj-rehearse`: Disable rehearsals on tests where the 'restrict_network_access' config is toggled to 'false'

cmd/cluster-init/cmd/onboard/buildclusterdir/update.go, cmd/cluster-init/cmd/onboard/generateconfig.go, cmd/cluster-init/main.go, pkg/clustermgmt/onboard/certificate.go, pkg/clustermgmt/onboard/certificate_test.go, pkg/clustermgmt/onboard/types.go, pkg/clustermgmt/types.go, pkg/util/yaml/yaml.go, pkg/util/yaml/yaml_test.go, test/integration/cluster-init.sh, test/integration/cluster-init/create-ocp/expected/clusters/build-clusters/newCluster/cert-manager/certificate.yaml, test/integration/cluster-init/create/expected/clusters/build-clusters/newCluster/cert-manager/certificate.yaml, test/integration/cluster-init/update-ocp/expected/clusters/build-clusters/existingCluster/cert-manager/certificate.yaml, test/integration/cluster-init/update/expected/clusters/build-clusters/existingCluster/cert-manager/certificate.yaml, test/validate-generation-breaking-changes.sh
Generate `certificates.cert-manager.io` manifests into `assets/cert-manager` directory.
`cluster-init` extracts the following information at runtime:
- DNS base domain: get from the `baseDomain` stanza of `cluster-install.yaml` stored into `oc -n kube-system get cm/cluster-config-v1` 
- Image Registry public host: get from the `publicDockerImageRepository` stanza of any IS from the `openshift` namespace. I didn't come up with this idea, I've stolen from [here](https://github.com/openshift/oc/blob/e75d922ae2a2af65a647dd6c094be9e78d49f7d4/pkg/cli/registry/info/info.go#L1), thanks `oc` guys!
[Check this out](https://github.com/openshift/release/blob/b9355499f2cbcba18f7d90b9bca44bbc0cbbbe59/clusters/build-clusters/build11/cert-manager/certificate.yaml) as an example.
=> cluster-init: generate Certificates

cmd/pj-rehearse/server.go
Otherwise, the table gets formatted like the following with the next line as part of the table:
=> `pj-rehearse`: add empty line for formatting

cmd/registry-replacer/main_test.go, pkg/api/config_test.go, pkg/api/types.go, pkg/defaults/defaults.go, pkg/defaults/defaults_test.go, pkg/diffs/diffs.go, pkg/steps/project_image.go
Bundle images are not multi-arch by design. Spawn a single build instead when the image build configuration comes from the operator bundles stanza.
/cc @deepsm007 @aleskandro @openshift/test-platform
=> [DPTP-4192] adjust bundle image builds to exclude manifest list

cmd/config-brancher/main.go, cmd/config-brancher/main_test.go
The config-brancher is missing few configuration eg [installer configs](https://github.com/openshift/release/blob/master/ci-operator/config/openshift/installer/openshift-installer-master.yaml#L249-L260) which uses candidate stream along with integration stream. Adding support eliminates the need for manual update during branching https://github.com/openshift/release/commit/4cb16b04945e7e56f0bca37b3efecea5c933c710#diff-92fb8761a3401342e7a5678fa916ff7f552fe64f9fa412105c354e691c76a736L212 
/hold
=> DPTP-4183: Fix automation to include candidate release

cmd/pj-rehearse/main.go, cmd/pj-rehearse/server.go, pkg/diffs/diffs.go, pkg/diffs/diffs_test.go, pkg/rehearse/jobs.go, pkg/rehearse/rehearse.go
> Any rehearsal of any job with the `restrict_network_access` field set to false will require the PR to have the `network-access-rehearsals-ok` label. This label will only be allowed to be applied via the plugin, and only by an 'openshift' org member who is not the author of the PR. The label will be removed on a new push. The PR will also have to be labeled 'approved' for the job to be rehearsable.
For: https://issues.redhat.com/browse/DPTP-4195
=> `pj-rehearse`: allow the ability to rehearse tests with `network_access_restricted`: 'false'

pkg/api/types.go
Create two distinct cluster profiles: one for HA jobs and one for all other jobs.
=> OCPQE-26170: Add cluster profiles for Azure HCP QE

cmd/ci-operator/main.go, cmd/ci-operator/main_test.go, pkg/api/types.go
Use config-resolver to get the name of cluster profile secret we need, instead of mounting it to the job and then reading it locally along with the other user-defined secrets.
Next steps:
- create a presubmit job to check the cluster profile secret (defined in the test config) exists in the ci namespace
- edit prowgen so it doesn't add the cluster profile volume to the job yaml, as it won't be needed anymore & regenerate all jobs
/cc @droslean
=> Update how ci-operator gets cluster profile secrets

cmd/pj-rehearse/server.go
This mimics what happens with regular jobs, and should save on costs. There is no reason to keep the rehearsals active when the HEAD has changed
=> `pj-rehearse`: abort active rehearsal jobs when new commit is pushed

pkg/controller/prpqr_reconciler/prpqr_reconciler.go, pkg/controller/prpqr_reconciler/testdata/zz_fixture_prowjobs_TestReconcile_basic_aggregated_case.yaml, pkg/controller/prpqr_reconciler/testdata/zz_fixture_prowjobs_TestReconcile_basic_aggregated_case_with_scheduling.yaml, pkg/controller/prpqr_reconciler/testdata/zz_fixture_prowjobs_TestReconcile_basic_case.yaml, pkg/controller/prpqr_reconciler/testdata/zz_fixture_prowjobs_TestReconcile_basic_case_with_cluster_override.yaml, pkg/controller/prpqr_reconciler/testdata/zz_fixture_prowjobs_TestReconcile_basic_case_with_metal_override.yaml, pkg/controller/prpqr_reconciler/testdata/zz_fixture_prowjobs_TestReconcile_basic_case_with_scheduling.yaml, pkg/controller/prpqr_reconciler/testdata/zz_fixture_prowjobs_TestReconcile_basic_case_with_variant.yaml, pkg/controller/prpqr_reconciler/testdata/zz_fixture_prowjobs_TestReconcile_basic_case_with_vsphere_override.yaml, pkg/controller/prpqr_reconciler/testdata/zz_fixture_prowjobs_TestReconcile_basic_case_without_PR__testing_specified_base.yaml, pkg/controller/prpqr_reconciler/testdata/zz_fixture_prowjobs_TestReconcile_multiple_case__one_of_the_prowjobs_already_exists.yaml, pkg/controller/prpqr_reconciler/testdata/zz_fixture_prowjobs_TestReconcile_override_initial_and_base_payload_pullspecs.yaml, pkg/jobrunaggregator/jobrunaggregatoranalyzer/analyzer.go
This reverts commit afdf41af560bb893326af53cec1186f1c1584c58.
Reverting https://github.com/openshift/ci-tools/pull/4246
Complimentary to https://github.com/openshift/release/pull/57656
=> WRKLDS-1449: Revert "Increase timeouts for payload jobs to land k8s 1.31"

pkg/defaults/defaults.go, pkg/defaults/defaults_test.go, pkg/steps/release/import_release.go
Originally, we were only setting these variables when the pullspecs were provided via an env var. It is actually more useful (and simpler) to set them _anytime_ a release is resolved. Unfortunately, there is no good/simple way to write unit or e2e tests for this functionality, but it is simple enough that I believe that is fine.
For: https://issues.redhat.com/browse/DPTP-4212
=> set ORIGINAL_* env vars whenever a release is resolved

cmd/multi-pr-prow-plugin/README.md
This is useful, but is mostly to test out how tide behaves with the check_runs.
/hold until ready
=> `multi-pr-prow-plugin`: add a readme

pkg/api/ocpbuilddata/types.go
As part of ART pipelines, we want the ability to onboard images which are 
unconventional. They may not always have from/stream/member images defined. (example https://github.com/openshift-eng/ocp-build-data/pull/5511/files)
We mark these images as disabled, so skip operating on these.
Right now the command errors out because of the unconventional config
https://prow.ci.openshift.org/view/gs/test-platform-results/logs/periodic-prow-auto-config-brancher/1846521743284375552
=> [registry-replacer] Skip disabled configs

pkg/api/types.go
The s390x resources are failing with conflicting resource issues. To alleviate the pressure, we want to segregate the different leases-per-host as separate quota slices than the other leases on that host.  This will potentially remove some of the resource contention.
=> Update s390x quota slice definitions for lease groupings

cmd/ci-operator/main.go
Not needed now that https://github.com/openshift/release/pull/58275 merged.
=> Remove TODO from `ci-operator`

pkg/config/load.go, pkg/image-graph-generator/operator.go, pkg/prowgen/prowgen.go, pkg/prowgen/prowgen_test.go
Until the prowjob cluster is determined by the prowjob dispatcher, this is just a workaround to keep the job configuration aligned.
Also, deprecate the `multi_arch` and the `multi_arch_branch_filter` fields in the prowgen configuration.
Also, this will allow us to deprecate the multi_arch field in the prowgen configuration.
/cc @openshift/test-platform @deepsm007
=> force the build10 clusters on jobs for additional architecture configuration on images and node architectures for tests

cmd/multi-pr-prow-plugin/server.go, cmd/multi-pr-prow-plugin/server_test.go, cmd/multi-pr-prow-plugin/testdata/zz_fixture_TestHandle_abort_multi_pr_jobs.yaml
This mimics what we do in `pj-rehearse` and `payload-testing-prow-plugin`. It will allow the user to comment `/testwith abort` to abort all active multi-pr jobs that have been triggered from that PR.
=> `multi-pr-prow-plugin`: add the ability to abort active multi-pr jobs for the origin PR

pkg/controller/prpqr_reconciler/prpqr_reconciler.go, pkg/controller/prpqr_reconciler/prpqr_reconciler_test.go, pkg/controller/prpqr_reconciler/testdata/zz_fixture_prowjobs_TestReconcile_basic_aggregated_case.yaml, pkg/controller/prpqr_reconciler/testdata/zz_fixture_prowjobs_TestReconcile_basic_aggregated_case_with_scheduling.yaml, pkg/controller/prpqr_reconciler/testdata/zz_fixture_prowjobs_TestReconcile_basic_case.yaml, pkg/controller/prpqr_reconciler/testdata/zz_fixture_prowjobs_TestReconcile_basic_case_with_metal_override.yaml, pkg/controller/prpqr_reconciler/testdata/zz_fixture_prowjobs_TestReconcile_basic_case_with_scheduling.yaml, pkg/controller/prpqr_reconciler/testdata/zz_fixture_prowjobs_TestReconcile_basic_case_with_vsphere_override.yaml, pkg/controller/prpqr_reconciler/testdata/zz_fixture_prowjobs_TestReconcile_basic_case_without_PR__testing_specified_base.yaml, pkg/controller/prpqr_reconciler/testdata/zz_fixture_prowjobs_TestReconcile_multiple_PRs_from_different_repositories.yaml, pkg/controller/prpqr_reconciler/testdata/zz_fixture_prowjobs_TestReconcile_multiple_PRs_from_the_same_repository.yaml, pkg/controller/prpqr_reconciler/testdata/zz_fixture_prowjobs_TestReconcile_multiple_case__one_of_the_prowjobs_already_exists.yaml, pkg/controller/prpqr_reconciler/testdata/zz_fixture_prowjobs_TestReconcile_override_initial_and_base_payload_pullspecs.yaml, pkg/controller/prpqr_reconciler/testdata/zz_fixture_prowjobs_TestReconcile_url_not_found_in_created_job.yaml, pkg/controller/prpqr_reconciler/testdata/zz_fixture_prpqr_TestReconcile_basic_aggregated_case.yaml, pkg/controller/prpqr_reconciler/testdata/zz_fixture_prpqr_TestReconcile_basic_aggregated_case_with_scheduling.yaml, pkg/controller/prpqr_reconciler/testdata/zz_fixture_prpqr_TestReconcile_basic_case.yaml, pkg/controller/prpqr_reconciler/testdata/zz_fixture_prpqr_TestReconcile_basic_case_with_metal_override.yaml, pkg/controller/prpqr_reconciler/testdata/zz_fixture_prpqr_TestReconcile_basic_case_with_variant.yaml, pkg/controller/prpqr_reconciler/testdata/zz_fixture_prpqr_TestReconcile_basic_case_with_vsphere_override.yaml, pkg/controller/prpqr_reconciler/testdata/zz_fixture_prpqr_TestReconcile_basic_case_without_PR__testing_specified_base.yaml, pkg/controller/prpqr_reconciler/testdata/zz_fixture_prpqr_TestReconcile_multiple_PRs_from_different_repositories.yaml, pkg/controller/prpqr_reconciler/testdata/zz_fixture_prpqr_TestReconcile_multiple_PRs_from_the_same_repository.yaml, pkg/controller/prpqr_reconciler/testdata/zz_fixture_prpqr_TestReconcile_multiple_case__one_of_the_prowjobs_already_exists.yaml, pkg/controller/prpqr_reconciler/testdata/zz_fixture_prpqr_TestReconcile_override_initial_and_base_payload_pullspecs.yaml, pkg/controller/prpqr_reconciler/testdata/zz_fixture_prpqr_TestReconcile_url_not_found_in_created_job.yaml
Not doing this can result in statuses on the PRPQR that don't have a URL to the spyglass page until after the job is complete. This has been brought on by the new `Scheduling` state. No URL will exist until the job is actually in `Triggered`, but rather than check that specifically, we can just check for the existence of a URL. The `20` second poll period is a guess that we may have to tune later.
For: https://issues.redhat.com/browse/DPTP-4174
=> `PRPQR`: wait for the job status to contain a URL after creating the job

pkg/controller/prpqr_reconciler/pjstatussyncer/pjstatussyncer.go
Without this change the UI incorrectly displays that all jobs are finished
=> `Payload Testing`: add scheduling state to statuses that are still active

cmd/pj-rehearse/main.go, cmd/pj-rehearse/server.go, pkg/config/release.go, pkg/config/release_test.go, pkg/rehearse/configmaps_test.go, pkg/rehearse/jobs.go, pkg/rehearse/jobs_test.go, pkg/rehearse/rehearse.go, test/integration/pj-rehearse.sh, test/integration/pj-rehearse/candidate/cluster/test-deploy/test-profile/vars-origin.yaml, test/integration/pj-rehearse/candidate/cluster/test-deploy/test-profile/vars.yaml, test/integration/pj-rehearse/expected.yaml, test/integration/pj-rehearse/master/cluster/test-deploy/test-profile/vars-origin.yaml, test/integration/pj-rehearse/master/cluster/test-deploy/test-profile/vars.yaml
With the deprecation `cluster/test-deploy` in the release repo, removing related code also in ci-tools repo.
=> Remove code related to `cluster/test-deploy`

cmd/ci-operator/main.go, pkg/rehearse/jobs.go, pkg/rehearse/jobs_test.go, pkg/rehearse/rehearse.go
Following up on https://github.com/openshift/ci-tools/pull/4402, we now upload the config-spec to GCS and add the _full_ URL to the `CONFIG_SPEC_GCS_URL` env var.
The `prNumber` argument that was previously passed around everywhere is now replaced by looking in the `refs` where it will always be located anyways.
This also includes a change to `ci-operator` to expect the full GCS location, rather than just the file name. This is to make it easier to move it to a new bucket if desired in the future.
The existing `CONFIG_SPEC` env var logic still exists as it is simpler for the integration test, so I have put it behind the `dryRun` flag. I also filed https://issues.redhat.com/browse/DPTP-4243 to redesign the integration test entirely, as it is getting to be outdated.
For: …
=> `pj-rehearse` upload the ci-operator config-spec to GCS 

cmd/ci-operator/main.go, pkg/registry/server/server.go, pkg/validation/config.go, pkg/validation/config_test.go
Creates a new `mergedConfig` bool based on the presence of an injected test (which **always** means we are merging the configs. This bool is used to trigger specific validation rather than relying on the absence of metadata. This improves our validation, while still allowing for the proper logic to occur when we are running multi-pr presubmit tests for multiple PRs on the same repo.
For: https://issues.redhat.com/browse/DPTP-4246
=> `multi-pr`: fix mergedConfig validation

cmd/job-trigger-controller-manager/main.go, pkg/controller/prpqr_reconciler/prpqr_reconciler.go, pkg/controller/prpqr_reconciler/prpqr_reconciler_test.go
It appears that the `prow-controller-manager` can get a little behind sometimes and `20s` isn't always enough. This value is now configurable with the default being `60s`.
=> `payload-testing`: allow for a configurable wait time for the triggered job's URL to appear

pkg/controller/prpqr_reconciler/pjstatussyncer/pjstatussyncer.go, pkg/controller/prpqr_reconciler/pjstatussyncer/pjstatussyncer_test.go, pkg/controller/prpqr_reconciler/prpqr_reconciler.go, pkg/controller/prpqr_reconciler/testdata/zz_fixture_prpqr_TestReconcile_basic_aggregated_case_with_scheduling.yaml, pkg/controller/prpqr_reconciler/testdata/zz_fixture_prpqr_TestReconcile_basic_case_with_scheduling.yaml
Follows up on https://github.com/openshift/ci-tools/pull/4399 adding the `Scheduling` state to **all** areas that were previously only checking for `Triggered` and `Pending`. This fixes a bug where the UI incorrectly reports that all jobs are finished.
=> `Payload Testing`: consolidate logic to determine if any jobs are still running

pkg/api/types.go
Add a new cluster profile to support OCP clusters on a RHOSO cloud.
The `rhoso-giant28-quota-slice` is requested in this PR https://github.com/openshift/release/pull/59014
=> OSASINFRA-3649: Add cluster profile for RHOSO

cmd/check-gh-automation/main.go, cmd/check-gh-automation/main_test.go
Repos participating in [automated branching](https://docs.ci.openshift.org/docs/architecture/branching/#how-do-i-opt-my-repository-into-automated-branching) need to have github issues enabled and need to be public in order for the [blocking-issue-creator](https://prow.ci.openshift.org/?job=periodic-openshift-release-merge-blockers) to succeed. There is currently no precheck for this.
=> [DPTP-3546] Verify if the repo is public for branch protection

cmd/cluster-display/main.go, cmd/cluster-display/main_test.go, go.mod
Fetch disabled clusters from Prow on demand instead of getting the list at startup.
This handles the problem of a new cluster being disabled and `cluster-display` not being able to notice it unless restarted.
=> cluster-display: fetch disabled clusters on demand

pkg/api/types.go
The RHOAI QE team requires a dedicated cluster profile for spinning up Openshift clusters using our AWS account as well as creating S3 buckets for internal testing config.
=> Adding AWS RHOAI QE Cluster Profile

pkg/prowgen/prowgen.go, pkg/prowgen/prowgen_test.go, pkg/prowgen/testdata/zz_fixture_TestGenerateJobs_images_job_is_configured_for_slack_reporting.yaml
It was previously made possible to add the slack reporter config for all other postsubmits and periodics. This allows the `images` postsubmit to use this functionality as well.
I will follow this up with a documentation change, and trying it out in `ci-tools`.
For: https://issues.redhat.com/browse/DPTP-4213
=> `prowgen`: ability to add slack reporting to "images" postsubmits

pkg/api/types.go
release [openshift/release/pull/59154](https://github.com/openshift/release/pull/59154)
Profile | Profile String | Cloud Type
-- | -- | --
ClusterProfileGCPQEC3Metal | gcp-qe-c3-metal | gcp
=> Create dedicated GCP cluster profile 'gcp-qe-c3-metal' for GCP C3 bare metal testing (OCPSTRAT-1278)

pkg/api/types.go
The RHOAI QE team requires a dedicated cluster profile for spinning up Openshift clusters using our AWS managed rosa account as well as creating S3 buckets for internal testing config.
=> Adding AWS managed ROSA RHOAI QE Cluster Profile

pkg/api/types.go
The RHOAI QE team requires a dedicated cluster profile for spinning up Openshift clusters using our AWS managed osd account as well as creating S3 buckets for internal testing config.
=> Adding AWS managed OSD RHOAI QE Cluster Profile

pkg/api/types.go
This pr clear the profile aws-perf-qe created by https://github.com/openshift/ci-tools/pull/3541, which is replaced by aws-perfscale-lrc-qe created by https://github.com/openshift/ci-tools/pull/3537.
Related PR in release repo: https://github.com/openshift/release/pull/50779
=> clear profile aws-perfscale

cmd/check-gh-automation/main.go
Otherwise, it is hard for the user to tell what made the check fail
=> `check-gh-automation`: log on error level when repo doesn't give the cherrypick-bot the proper perms

pkg/api/types.go
Create a new cluster profile, `oci-agent-qe`, which will hold the credentials for creating resources in Oracle Cloud.
This profile will be used to test OCP installations using the agent installer.
=> AGENT-1045: Add OCI Agent QE Cluster Profile

cmd/check-gh-automation/main.go, cmd/check-gh-automation/main_test.go, hack/local-check-gh-automation.sh
Repos participating in [automated branching](https://docs.ci.openshift.org/docs/architecture/branching/#how-do-i-opt-my-repository-into-automated-branching) need to have github issues enabled to succeed. There is currently no precheck for this. It should be added as a check in check-gh-automation.
This PR depends on https://github.com/openshift/ci-tools/pull/4442
=> [DPTP-3546] Verifying if issues are enable for automated branching

pkg/config/release.go
There is nothing to rehearse based on the change, and not ignoring this file results in The following error:
```
could not determine changed registry steps: could not get step registry differences: invalid step registry filename: cluster-profiles-config.yaml
```
Since this file isn't _real_ step-registry content, I am not sure that it belongs in that directory at all, but that will be addressed in a follow up if necessary.
=> `pj-rehearse`: ignore the cluster-profile-config.yaml file when attempting to get changed registry content

pkg/config/release.go
Follows up on https://github.com/openshift/ci-tools/pull/4448 to only use the base name. We are only passing the base, rather than the full path.
=> `pj-rehearse`: fix the check to only look for the 'cluster-profile-config.yaml' base

cmd/check-gh-automation/main.go, cmd/check-gh-automation/main_test.go, hack/local-check-gh-automation.sh
Follows up on https://github.com/openshift/ci-tools/pull/4442 to modify the check for the organizations "plan" to only occur when the repo is actually owned by an organization. We will just blanket ban repos that are private and user-owned. The unit tests are also simplified with this effort. This also modifies the local script to expect the candidate-path to be passed as an env arg.
=> `check-gh-automation`: allow functionality for user owned repos

pkg/api/types.go, pkg/validation/release.go, pkg/validation/release_test.go
This is related to this PR: https://github.com/openshift/ci-tools/pull/4456
Tests are failing since `okd-scos` is not a valid product.
=> Added product okd-scos

cmd/autoowners/main.go, cmd/job-runtime-analyzer/main.go, cmd/ldap-users-from-github-owners-files/main.go, cmd/repo-init/api.go, cmd/result-aggregator/main.go, cmd/vault-secret-collection-manager/index.ts, pkg/util/secret.go
This update is to solve some problems in our security test.
Despite all my modifications, Snyk still consider a possible Server-Side Request Forgery (SSRF) in `cmd/job-runtime-analyzer/main.go:32` - **I am accepting ideas s2**
About javascript, basically everything that is `innerHTML` but only renders text can be replaced with `innerText`.
When HTML is needed, in simple cases we can use `appendChild` with `document.createTextNode` and `document.createElement`.
To erase elements inside another one we use the following code to avoid `innerHTML`, manipulating DOM directly:
```
while(element.firstChild)
element.removeChild(element.firstChild);
```
Since this is `TypeScript` there is better ways to render HTML.
Some errors was fixed with `filepath.Clean`, but @smg247 noticed that …
=> Some security tweaks

pkg/release/candidate/client.go, pkg/validation/release.go, test/e2e/multi-stage/assembled-release-no-injection.yaml, test/e2e/multi-stage/assembled-release.yaml, test/e2e/multi-stage/dependencies.yaml, test/e2e/multi-stage/e2e_test.go
Looks like images based on CentOS 8 stream are failing because of the outdated repositories.
The newer releses of OKD have the suffix `-scos`:
[https://amd64.origin.releases.ci.openshift.org/api/v1/releasestream/4.17.0-0.okd-scos/latest](https://amd64.origin.releases.ci.openshift.org/api/v1/releasestream/4.17.0-0.okd-scos/latest)
Waiting for: https://github.com/openshift/ci-tools/pull/4458
=> [DPTP-4282] Bump e2e test image versions to 4.17 from 4.15

cmd/pj-rehearse/main.go
Mistakenly removed in https://github.com/openshift/ci-tools/pull/4462
=> `pj-rehearse`: add back flag that was accidentally removed

cmd/cluster-init/cmd/onboard/config/config.go, pkg/clusterinit/clusterinstall/clusterinstall.go, pkg/clusterinit/onboard/certificate.go, pkg/clusterinit/onboard/certificate_test.go, pkg/clusterinit/onboard/cisecretbootstrap.go, pkg/clusterinit/onboard/dex.go, pkg/clusterinit/onboard/dex_test.go, pkg/clusterinit/onboard/multiarchbuildercontroller.go, pkg/clusterinit/onboard/multiarchbuildercontroller_test.go, pkg/clusterinit/onboard/oauthtemplate.go, pkg/clusterinit/onboard/oauthtemplate_test.go, pkg/clusterinit/onboard/quayiopullthroughcache.go, pkg/clusterinit/onboard/quayiopullthroughcache_test.go, test/integration/cluster-init/update-build99/expected/core-services/ci-secret-bootstrap/_config.yaml
Two changes:
The `struct`s that generate the following manifests:
- `Certificate`
- `Dex`
- `MultiarchBuilderController`
- `OAuth`
- `ImageContentSourcePolicy`
have been refactored into `*Generator`s, so that they can be used, and enhanced by  the `manifestGeneratorStep`.
Secrets for `pj-rehearse` are not generated anymore, see https://github.com/openshift/release/pull/60440.
=> cluster-init: refactor some steps into manifest generators

pkg/clusterinit/onboard/buildcluster.go
When someone execute `cluster-init onboard config generate` more than once, the cluster name will be appended to the list despite already being there.
I added a simple verification to see if that value is already present before `append`.
=> Added a verification to avoid duplicated clusters

cmd/check-gh-automation/main.go
I suppose that:
```golang
if ignore.Has(org) || ignore.Has(orgRepo) {
repoLogger.Infof("skipping ignored repo")
continue
}
```
should stay at the top of the `for` as it was intended [here](https://github.com/openshift/ci-tools/pull/2847/files).
Hopefully this will solve the problems we are facing [here](https://redhat-internal.slack.com/archives/CBN38N3MW/p1736933034912959).
/cc @smg247
=> check-gh-automation: move `ignore` at the right place

cmd/private-org-sync/main.go, cmd/private-prow-configs-mirror/main_test.go, cmd/publicize/server_test.go, pkg/backporter/backporter.go, pkg/diffs/diffs_test.go, pkg/jobrunaggregator/jobruntestcaseanalyzer/analyzer_test.go, pkg/results/report.go, pkg/retester/retester_test.go, pkg/steps/multi_stage/gen.go, pkg/steps/run_test.go, pkg/steps/source.go, pkg/testhelper/accessory.go, pkg/validation/test.go
Addressing errors that are showing up [here](https://github.com/openshift/release/pull/60836).
The vast majority of the adjustments deal with bad formatted strings.
=> Fix lint errors from golangci-lint v1.63.4

pkg/controller/prpqr_reconciler/prpqr_reconciler.go, pkg/controller/prpqr_reconciler/testdata/zz_fixture_prpqr_TestReconcile_url_not_found_in_created_job.yaml
There is reason to believe that this is causing jobs to be double triggered in some instances. I will remove this for a couple of days, and check if this problem is no longer occurring. If that is the case, I will figure out a different way to ensure the URL exists.
=> `prpqr_reconciller`: temporarily remove the wait for the URL to be present

cmd/multi-pr-prow-plugin/server.go, cmd/multi-pr-prow-plugin/server_test.go
This message ends up as a comment on the PR when this is hit. This only happens when the user has entered an invalid command, so we can provide more info about what was incorrect.
=> `multi-pr-plugin`: clarify error message that is bubbled up to the user

pkg/steps/source.go
Temporarily I am removing the `PushImageToRegistryFailed` as a failure reason to retry the build.
https://search.dptools.openshift.org/?search=+unable+to+retrieve+auth+token%3A+invalid+username%2Fpassword%3A+authentication+required&maxAge=12h&context=1&type=build-log&name=&excludeName=&maxMatches=5&maxBytes=20971520&groupBy=job
The problem is that after retrying the failed build artifacts are gone. In order to at least investigate the issue and try to reduce the amount of flakes, let's don't rerun at all and give some noise to that flake. 
=> remove PushImageToRegistryFailed infra failure reason for retrying the builds

pkg/steps/multi_stage/gen.go
When a pod using the `inject-cli` container is scheduled on non-amd64 nodes (e.g., multi-arch payload or arm64 payload), it should extract the proper `oc` binary based on the architecture of the node where the pod is running.
=> Fix inject-cli for non-amd64 runs

cmd/cluster-init/cmd/onboard/config/config.go, pkg/clusterinit/clusterinstall/clusterinstall.go, pkg/clusterinit/manifest/patch.go, pkg/clusterinit/onboard/manifestgenerator.go, pkg/clusterinit/onboard/passthrough.go, pkg/clusterinit/onboard/passthrough_test.go
As per title, the `passthrough` step now implements the `ManifestGenerator` interface.
This means this step is no longer being considered "different" from the others, and yaml patches can now be applied to static manifests as well (see `pkg/clusterinit/clusterinstall/clusterinstall.go`).
=> cluster-init: passthrough implements ManifestGenerator

cmd/repo-init/main.go
This is related to [DPTP-4310](https://issues.redhat.com/browse/DPTP-4310), since `Orgs` are just appended to an array, if there is a duplication in any `_prowconfig.yaml` it will not affect the new repo.
The `prowconfig.TideQueries[x].Orgs` will be cleaned almost the same way as `prowconfig.TideQueries[x].Repos`, avoiding unexpected organizations on generated configuration.
Tide queries are "de-duplicated" - squashed/compressed is probably a better definition - after calling the `queries.ForRepo` line on https://github.com/openshift/ci-tools/blob/master/cmd/repo-init/main.go#L524 that will trigger `deduplicateTideQueries` on https://github.com/kubernetes-sigs/prow/blob/main/pkg/config/config.go#L3544-L3572.
The queries are squashed based on the following fields:
- Author
- …
=> [DPTP-4310] Clean orgs array on repo-init

pkg/api/types.go
Rename cluster profile to support OCP clusters on a RHOSO cloud to something more meaningful to something more meaningful.
Changes in release repository on https://github.com/openshift/release/pull/61521
=> Rename cluster profile for RHOSO

pkg/prowgen/prowgen_test.go, pkg/prowgen/testdata/zz_fixture_TestGenerateJobs_periodic_presubmit_with_capabilities.yaml, pkg/prowgen/testdata/zz_fixture_TestGenerateJobs_periodic_with_capabilities.yaml
Thanks to https://github.com/openshift/ci-tools/pull/4491, periodics will now have capabilities as well. This PR just adds some unit tests to cover the feature.
=> ci-operator-prowgen: add more unit tests for capabilities

cmd/branchingconfigmanagers/tide-config-manager/main.go, cmd/determinize-prow-config/main_test.go, test/integration/repo-init/expected/core-services/prow/02_config/_config.yaml, test/integration/repo-init/expected/core-services/prow/02_config/openshift/ci-tools/_prowconfig.yaml, test/integration/repo-init/expected/core-services/prow/02_config/openshift/cluster-version-operator/_prowconfig.yaml, test/integration/repo-init/expected/core-services/prow/02_config/org/other/_prowconfig.yaml, test/integration/repo-init/expected/core-services/prow/02_config/org/repo/_prowconfig.yaml, test/integration/repo-init/expected/core-services/prow/02_config/org/third/_prowconfig.yaml, test/integration/repo-init/input/core-services/prow/02_config/_config.yaml, test/integration/repo-init/input/core-services/prow/02_config/openshift/ci-tools/_prowconfig.yaml, test/integration/repo-init/input/core-services/prow/02_config/openshift/cluster-version-operator/_prowconfig.yaml
We have some PR's from openshift-bot like https://github.com/openshift/csi-external-snapshotter/pull/172 that did not automatically merge because they are missing the `jira/valid-bug` label. The bot adds `bugzilla/valid-bug` but we no longer check that label in our [prow config](https://github.com/openshift/release/blob/3fc58d801c90cc49be50af02746b4cb0bc92296d/core-services/prow/02_config/openshift/csi-external-snapshotter/_prowconfig.yaml#L9).
This PR updates tide-config-manager to use `jira/valid-bug` and `jira/invalid-bug` instead of the bugzilla labels.
=> tide-config-manager: replace bugzilla/valid-bug with jira/valid-bug

pkg/clusterinit/onboard/cischedulingwebhook/aws.go, test/integration/cluster-init/update-build99/expected/clusters/build-clusters/build99/ci-scheduling-webhook/ci-longtests-worker-aarch64.yaml, test/integration/cluster-init/update-build99/expected/clusters/build-clusters/build99/ci-scheduling-webhook/ci-longtests-worker-amd64.yaml, test/integration/cluster-init/update-build99/expected/clusters/build-clusters/build99/ci-scheduling-webhook/ci-prowjobs-worker-aarch64.yaml, test/integration/cluster-init/update-build99/expected/clusters/build-clusters/build99/ci-scheduling-webhook/ci-prowjobs-worker-amd64.yaml, test/integration/cluster-init/update-build99/expected/clusters/build-clusters/build99/ci-scheduling-webhook/ci-tests-worker-aarch64.yaml, test/integration/cluster-init/update-build99/expected/clusters/build-clusters/build99/ci-scheduling-webhook/ci-tests-worker-amd64.yaml
/cc @danilo-gemoli @openshift/test-platform 
https://github.com/openshift/release/pull/61640
=> Update ci-scheduling-webhook for volumeSize based on workload types

pkg/api/pullrequestpayloadqualification/v1/ci.openshift.io_pullrequestpayloadqualificationruns.yaml, pkg/api/pullrequestpayloadqualification/v1/types.go, pkg/controller/prpqr_reconciler/pjstatussyncer/testdata/zz_fixture_prpqr_TestReconcile_basic_case.yaml, pkg/controller/prpqr_reconciler/pjstatussyncer/testdata/zz_fixture_prpqr_TestReconcile_job_is_still_running.yaml, pkg/controller/prpqr_reconciler/pjstatussyncer/testdata/zz_fixture_prpqr_TestReconcile_previous_condition_exists.yaml, pkg/controller/prpqr_reconciler/prpqr_reconciler.go, pkg/controller/prpqr_reconciler/prpqr_reconciler_test.go, pkg/controller/prpqr_reconciler/testdata/zz_fixture_prowjobs_TestReconcile_basic_case_with_no_PRs_included__testing_determined_base.yaml, pkg/controller/prpqr_reconciler/testdata/zz_fixture_prpqr_TestReconcile_basic_case_with_no_PRs_included__testing_determined_base.yaml
When no PRs are included, the complex part is determining the base metadata. We can use the metadata from the injected test.
This represents the first requirement in: https://issues.redhat.com/browse/DPTP-4278
=> `prpqr_reconciller`: allow for the absence of any PRs in the PRPQR spec

pkg/dispatcher/config_test.go, pkg/dispatcher/helpers_test.go, pkg/prowgen/prowgen_test.go, pkg/prowgen/testdata/zz_fixture_TestGenerateJobs_periodic_presubmit_with_capabilities.yaml, pkg/prowgen/testdata/zz_fixture_TestGeneratePeriodicForTest_periodic_with_capabilities.yaml, pkg/prowgen/testdata/zz_fixture_TestGeneratePostSubmitForTest_postsubmit_with_capabilities.yaml, pkg/prowgen/testdata/zz_fixture_TestGeneratePresubmitForTest_capabilities_added.yaml
Adding 2 more capabilities
1. **rce** (release-controller-eligible) - all the jobs triggered by release-controller will be marked by this capability
2. **sshd-bastion** - Multiarch P/Z libvirt jobs which connect to IBM h/w are required to be on a dedicated cluster which has direct access. This capability will move away once the h/w is accessible by redhat intranet
=> Configuring 2 more capabilities

cmd/payload-testing-prow-plugin/rcjobresolver.go, cmd/payload-testing-prow-plugin/rcjobresolver_test.go
This ability is based on a couple of new environment variables of the form: "SKIP_JOB_REGEX_xyz" and "SKIP_JOB_EXPIRE_xyz". The jobs with names matching the provided regex will be skipped on *all* PRPQR runs until the provided expire time.
This functionality will allow us to skip arbitrary jobs matched by any regex in the future, and will not be enabled at all until a corresponding change is made to add the proper env vars to the plugin deployment. I will add that in a followup PR.
For: https://issues.redhat.com/browse/DPTP-4335
=> `payload-testing`: add the ability to skip jobs when running payload tests from a PR

pkg/config/load.go, pkg/prowgen/jobbase.go, pkg/prowgen/jobbase_test.go, pkg/prowgen/podspec.go, pkg/prowgen/testdata/zz_fixture_TestNewProwJobBaseBuilderForTest_multi_stage_test_with_CSI_enabled.yaml, pkg/prowgen/testdata/zz_fixture_TestNewProwJobBaseBuilderForTest_simple_test_with_CSI_enabled.yaml
Related to https://github.com/openshift/ci-tools/pull/4507
`enable_secrets_store_csi_driver` is a temporary option for ci-operator to enable us to test out the new CSI Secrets mechanism. This PR allows us to toggle it using the `.config.prowgen` files (which are in the release repo ci-operator/config dirs)
=> `prowgen`: Add enable_secrets_store_csi_driver field

cmd/repo-init/main.go, test/integration/repo-init/expected/ci-operator/config/openshift/origin/openshift-origin-main.yaml, test/integration/repo-init/expected/ci-operator/config/org/repo/org-repo-main.yaml, test/integration/repo-init/expected/ci-operator/jobs/openshift/origin/openshift-origin-main-postsubmits.yaml, test/integration/repo-init/expected/ci-operator/jobs/openshift/origin/openshift-origin-main-presubmits.yaml, test/integration/repo-init/expected/ci-operator/jobs/org/repo/org-repo-main-presubmits.yaml, test/integration/repo-init/expected/core-services/sanitize-prow-jobs/_config.yaml, test/integration/repo-init/input/ci-operator/config/openshift/origin/openshift-origin-main.yaml, test/integration/repo-init/input/core-services/sanitize-prow-jobs/_config.yaml
It is failing after the branch name change.
Also have 'main' as the default branch in new repos.
=> `repo-init`: update origin 'master' -> 'main'

cmd/ci-operator/main.go, pkg/api/pullrequestpayloadqualification/v1/ci.openshift.io_pullrequestpayloadqualificationruns.yaml, pkg/api/pullrequestpayloadqualification/v1/types.go, pkg/api/types.go, pkg/controller/prpqr_reconciler/prpqr_reconciler.go, pkg/controller/prpqr_reconciler/prpqr_reconciler_test.go, pkg/controller/prpqr_reconciler/testdata/zz_fixture_prowjobs_TestReconcile_override_tag.yaml, pkg/controller/prpqr_reconciler/testdata/zz_fixture_prpqr_TestReconcile_override_tag.yaml, pkg/defaults/defaults.go, pkg/defaults/defaults_test.go, pkg/prowgen/podspec.go, pkg/steps/input_image_tag.go, pkg/validation/config.go, pkg/validation/config_test.go, pkg/validation/graph.go, pkg/webreg/zz_generated.ci_operator_reference.go
> It is uncommon for users to have the permission necessary to push test images to the ocp namespace or established imagestreams. Instead, permit payload tags to reference arbitrary images.
```
spec:
payload:
tags:
- name: "machine-os-content"
image: quay.io/openshift-release-dev/.... (arbitrary pullspec)
```
Note that this PR includes both changes for `ci-operator` and `prpqr_reconciller` as they need to merge together, and they are relatively simple on their own.
For: https://issues.redhat.com/browse/DPTP-4278
=> rework payload testing image tag overrides to allow for an aritrary pullspec override

pkg/steps/release/promote.go, pkg/steps/release/testdata/zz_fixture_TestGetPromotionPod_basic_case.yaml, pkg/steps/release/testdata/zz_fixture_TestGetPromotionPod_basic_case__arm64_only.yaml, pkg/steps/release/testdata/zz_fixture_TestGetPromotionPod_basic_case__multi_architecture.yaml, pkg/steps/release/testdata/zz_fixture_TestGetPromotionPod_promotion_quay.yaml
- Label `ci-operator.openshift.io/save-container-logs: "true"` was added to the promotion pods to allow the pod logs to be uploaded to the GCS bucket.
- Remove `--continue-on-error=true` flag on the `oc image mirror` commands.
- Add the `--loglevel=10` flag to generate debug logs while mirroring the images.
Log level 10 will generate descriptive logs for the whole image mirroring process. While testing this to make sure we won't leak any sensitive data, I confirm that the oc tool will mask any credentials are being used to push the image to the destination registry. (`-H "Authorization: Bearer <masked>"`)
/cc @openshift/test-platform @deepsm007
=> DPTP-4369 Enable debug logs on promotion pods, upload promotion artifacts to the gcs bucket

pkg/steps/release/create_release.go
Bash sucks:
```console
$ if /bin/false; then echo "false"; fi; echo $?
0
$ if /bin/false; then echo "false"; else echo $?; fi
1
```
I discovered this by actually breaking `oc adm release new` in https://github.com/openshift/oc/pull/1998, where I saw tests failing in multi-stage step consuming `RELEASE_IMAGE_LATEST`:
```
ERRO[2025-03-26T15:39:33Z] Some steps failed:
ERRO[2025-03-26T15:39:33Z]
* could not run steps: step e2e-aws-ovn-serial failed: could not lazily evaluate deferred parameter "RELEASE_IMAGE_LATEST": image stream "release" has no tag "latest" in spec or status
```
But the preceding release build step was actually pretending to be successful:
```
INFO[2025-03-26T15:25:26Z] Creating release image registry.build01.ci.openshift.org/ci-op-7i976kdw/release:latest. …
```
=> ci-operator: fix failure detection in release build

pkg/clusterinit/onboard/cischedulingwebhook/aws.go, pkg/clusterinit/onboard/machineset/aws.go, pkg/clusterinit/onboard/manifests/supplemental-ci-images/001_managed-clonerefs_mabc.yaml, test/integration/cluster-init/update-build99/expected/clusters/build-clusters/build99/supplemental-ci-images/001_managed-clonerefs_mabc.yaml
Security groups returned by the AWS API call are not stable. It seems that, despite the values staying the same, ordering is not guaranteed. This may cause flakes for `ci/prow/breaking-changes`.
=> cluster-init: sort aws security groups

pkg/config/gcs.go, pkg/rehearse/jobs.go, pkg/rehearse/jobs_test.go, pkg/rehearse/rehearse.go
Move `gcsConfigSpecUploader` into `pkg/config/gcs.go` and make it public.
I might need to reuse the code elsewhere and I don't want to duplicate it.
=> Refactor GCS Config Spec Uploader

pkg/api/types.go
Add a new cluster profile to collect job results from OpenStack on OpenShift RHOS CI  to PROW
=> SOSQE-2418: Add cluster profile for RHOS CI

pkg/api/ephemeralcluster/v1/types.go, pkg/controller/ephemeralcluster/reconciler.go, pkg/controller/ephemeralcluster/reconciler_test.go
The `EphemeralCluster` has been requested, and the controller spawned a `ci-operator` instance that is provisioning an ephemeral cluster.
As soon as the cluster is ready, `ci-operator` stores an admin kubeconfig into `secret/wait-test-complete`, as per design.
This reconciler will then retrieve it by following these steps in the `func fetchKubeconfig`:
- Identify the cluster in which `ci-operator` is running by looking at the `.spec.cluster` stanza on the ProwJob.
- Identify the `ci-op-xxxx` test NS by matching any namespace against this label: `ci.openshift.io/jobid == <PJ_ID_HERE>`.
- Get the `kubeconfig` from the `wait-test-complete` and store it into the `EphemeralCluster`'s `.status.kubeconfig` field.
=> Konflux: Fetch EphemeralCluster kubeconfig

pkg/steps/release/create_release.go
The current version format is 4.19.0-0.ci.2025-04-10-162714-test-ci-op-w42f90jc-latest,
but all official OCP version formats use 4.19.0-0.ci-2025-04-10-105124.
The separator between ci and the date should be a hyphen `-`, not a dot `.`
=> fix: change separator in release version format

pkg/api/types.go
The PR adds GCP ClusterProfile for OpenShift Observability group.
=> Register new Observability GCP ClusterProfile

pkg/api/types.go
added edge enablement equinix cluster profile for the time being to move metal sno workloads off of other teams accounts, this is a short term solution for now until we fully migrate all jobs off of equinix later this year.
=> OCPEDGE-1741: feat: add edge enablement equinix profile

pkg/api/types.go, pkg/api/zz_generated.deepcopy.go, pkg/prowgen/podspec.go, pkg/prowgen/prowgen.go, pkg/prowgen/prowgen_test.go, pkg/prowgen/testdata/zz_fixture_TestGenerateJobs_sharded_presubmit.yaml, pkg/validation/graph.go, pkg/webreg/zz_generated.ci_operator_reference.go, test/integration/ci-operator-prowgen/input/config/sharded/repo/sharded-repo-main.yaml, test/integration/ci-operator-prowgen/output/jobs/sharded/repo/sharded-repo-main-presubmits.yaml
If provided, this configuration will result in multiple jobs being generated for the ci-op config test. Each job will receive unique SHARD_ARGS values that will flow to the workflow.
This will simplify the sharding of jobs. Currently, we must do something like https://github.com/openshift/release/pull/64180, and duplicate the test configuration.
There will be follow-up PR(s) to `release` that will begin to utilize the `SHARD_ARGS` in the necessary workflow(s).
For: https://issues.redhat.com/browse/TRT-2086
=> `prowgen`: add `shard_count` field to the test step configuration

pkg/api/metadata.go, pkg/api/metadata_test.go
This is necessary to allow the slack-bot to properly link the ci-operator config, and for rehearsals to run for sharded jobs.
=> TRT-2090: When determining the testname for a given jobname, we must trim the shard suffix

cmd/ci-operator/main.go, cmd/ci-operator/main_test.go, pkg/prowgen/podspec.go, test/integration/ci-operator-prowgen/output/jobs/sharded/repo/sharded-repo-main-presubmits.yaml
The args for sharding tests will be passed directly to `openshift-tests` in the workflow, and contain spaces. Consequently, they must be quoted when passed to `ci-operator`. These quotation marks must not be part of the value passed to the mult-stage test, however.
This also changes passing the arg to put the quotes around _only_ the value.
Note, I think we could also quote the entire line, and not have to trim off quotation marks, but I think this is more explicit.
=> TRT-2090: quotation mark handling for multi-stage-param override values

pkg/steps/source.go, pkg/steps/source_test.go, pkg/steps/testdata/zz_fixture_TestBuildFromSource_ref_containing_underscore_specified.yaml
When building from a ref that contains `_` in the repo name, we must replace it in order to name the build resource. The name of the build itself doesn't affect anything that relies on it, as it still has the same `Output` configured.
I have tested this by firing off a manual [job](https://prow.ci.openshift.org/view/gs/test-platform-results/logs/openshift-node_exporter-165-ci-4.19-upgrade-from-stable-4.18-e2e-aws-ovn-upgrade/1917627205832151040) using a locally built image.
=> `ci-operator`: replace underscore in build name 

pkg/api/types.go
After redeploying mecha-z0, mecha-central and hwoffload with the same ci-config (general.yaml) to populate the OSP 17.1.4 cloud for general job purposes.
I'd like to allow PROW to redistribute the jobs across those 3 baremetal clouds with the following configuration: 
```
'openstack-vh-bm-rhos-quota-slice': {
'openstack-hwoffload': 3,
'openstack-vh-mecha-central': 3,
'openstack-vh-mecha-az0': 3,
},
```
=> OSASINFRA-3795: Add a cluster pofile for Vexxhost BM RHOS Clouds

cmd/dptp-controller-manager/main.go, pkg/controller/ephemeralcluster/reconciler.go
By design any `EphemeralCluster` object coming from a Konflux pipeline is supposed to be created into a well defined namespace only. This PR makes sure the reconciler will reconcile only those objects.
=> Konflux: Force the reconciler to watch a single namespace

cmd/dptp-controller-manager/main.go, pkg/controller/ephemeralcluster/reconciler.go
Until I figure out why this is happening
```json
{
"component": "dptp-controller-manager",
"error": "failed to construct manager for cluster app.ci: failed to determine if *v1.EphemeralCluster is namespaced: no kind is registered for the type v1.EphemeralCluster in scheme \"k8s.io/client-go/kubernetes/scheme/register.go:83\"",
"file": "/go/src/github.com/openshift/ci-tools/cmd/dptp-controller-manager/main.go:432",
"func": "main.main",
"level": "fatal",
"msg": "Failed to construct cluster managers",
"severity": "fatal",
"time": "2025-05-07T20:12:25Z"
}
```
=> Revert "feat(ecc): reconcile objs from one namespace only"

cmd/dptp-controller-manager/main.go, pkg/api/types.go, pkg/controller/ephemeralcluster/reconciler.go, pkg/controller/ephemeralcluster/reconciler_test.go, pkg/controller/ephemeralcluster/testdata/zz_fixture_build01_TestReconcile_Kubeconfig_not_ready.yaml, pkg/controller/ephemeralcluster/testdata/zz_fixture_build01_TestReconcile_Kubeconfig_ready.yaml, pkg/controller/ephemeralcluster/testdata/zz_fixture_build01_TestReconcile_Test_completed__create_secret.yaml, pkg/controller/ephemeralcluster/testdata/zz_fixture_build01_TestReconcile_Test_completed__secret_exists_do_nothing.yaml, pkg/controller/ephemeralcluster/testdata/zz_fixture_pj_TestCreateProwJob_An_EphemeralCluster_request_creates_a_ProwJob.yaml, pkg/controller/ephemeralcluster/wait-test-complete.sh, pkg/steps/multi_stage/init.go
Various improvements:
- Install the `EphemeralCluster` CRD on the `dptp-controller-manager` schema
- `wait-test-complete.sh` is more robust
- `ci-operator` allows a test step pod to read the `test-done-signal` secret
- The `EphemeralCluster` reconciler filter objects by namespace
=> Konflux: Controller Improvements

pkg/api/types.go, pkg/controller/ephemeralcluster/reconciler.go, pkg/controller/ephemeralcluster/reconciler_test.go, pkg/controller/ephemeralcluster/testdata/zz_fixture_pj_TestCreateProwJob_An_EphemeralCluster_request_creates_a_ProwJob.yaml, pkg/controller/ephemeralcluster/wait-test-complete.sh, pkg/steps/multi_stage/init.go
Follow up of https://github.com/openshift/ci-tools/pull/4578, fix secret name from `cluster-provisioning` to `test-done-signal`.
=> Konflux: Fix RBAC to read test-done-signal secret

cmd/repo-brancher/main.go
The tool reports an aggregate error at the end of the procedure but it's not quite clear what the problematic ci-operator configuration were, at least not without reviewing tons of lines of log.
The problematic configurations are now collected in a `sets.Set` and logged at the end of the execution.
=> repo-brancher: Improve error handling

pkg/controller/ephemeralcluster/testdata/zz_fixture_pj_TestCreateProwJob_An_EphemeralCluster_request_creates_a_ProwJob.yaml, pkg/controller/ephemeralcluster/wait-test-complete.sh
`ci-operator` is already prepending the following:
```sh
#!/bin/bash
set -eu
```
but this scripts handles pipeline's error on its own, therefore I will disable that shell option.
=> Konflux: `wait-test-signal.sh` doesn't give up too early

pkg/api/types.go
The PR adds Azure ClusterProfile for OpenShift Observability group.
=> Register new Observability Azure Cluster Profile

pkg/api/promotion.go, pkg/promotion/promotion.go, pkg/steps/release/promote.go, pkg/steps/release/promote_test.go
Documenting the new feature with an example: https://github.com/openshift/ci-docs/pull/538.
It is now possible to use `*` in the `promotion.exclude_images` stanza to exclude all images from being promoted.
=> ci-operator: Use * to exclude images from promotion

cmd/sippy-config-generator/OWNERS, cmd/sippy-config-generator/main.go
Also update the OWNERS while I'm in there.
<strike>This is only on the ci-tools side, variant registry generator needs a similar update.</strike> Nevermind that, it's already using v3
=> TRT-1734: sort jobs consistently in sippy-config-generator

pkg/slack/events/helpdesk/helpdesk-message.go, pkg/slack/events/helpdesk/testdata/zz_fixture_TestGetContactedHelpdeskResponse_empty_botId.yaml, pkg/slack/events/helpdesk/testdata/zz_fixture_TestGetContactedHelpdeskResponse_random_botId.yaml
Adds info about our helpdesk FAQ and notebookLM to the automatic message sent when user creates a workflow in [#forum-ocp-testplatform](https://redhat.enterprise.slack.com/archives/CBN38N3MW).
=> Update helpdesk message with FAQ and AI links

pkg/validation/test.go, pkg/validation/test_test.go
This change allows for the same mount path if credentials are in the same collection and have different names. With the new GCP mechanism, this is an allowed use case:
```
credentials:
- collection: team1
name: name
mount_path: /var/run
- collection: team1
name: diff-name
mount_path: /var/run
```
We still enforce that mount paths be different for different collections, to avoid possible collisions of file names.
=> Update credentials `mount_path` verification

pkg/api/ephemeralcluster/v1/types.go, pkg/controller/ephemeralcluster/reconciler.go, pkg/controller/ephemeralcluster/reconciler_test.go, pkg/controller/ephemeralcluster/testdata/zz_fixture_build01_TestReconcile_Succeeded_ProwJob_maps_to_ProwJobCompleted_condition.yaml
This is an attempt to simplify the reconcile logic.
Apart from `.status.prowJobId`, the `.status` stanza is now computed at every cycle. From an high level perspective, the reconcile loop accomplishes the following actions:
- Create a `ProwJob` if not exist, then re-queue the reconcile request
- Fetch the kubeconfig
- Tear the ephemeral cluster down if `.spec.tearDownCluster` is set
- Check the ProwJob status:
- If a final status is reached (`aborted`, `error`, `completed`, etc.), then update the `EphemeralCluster` object and exit
- Otherwise update the `EphemeralCluster` object and re-queue the reconcile request
This would hopefully ensure that the `.status` is properly constructed from what the reconciler observes on the clusters.
=> Konflux: Compute the EphemeralCluster status from scratch

pkg/steps/multi_stage/csi_utils.go, pkg/steps/multi_stage/csi_utils_test.go, pkg/steps/multi_stage/gen.go, pkg/steps/multi_stage/gen_test.go, pkg/steps/multi_stage/init.go, pkg/steps/multi_stage/init_test.go, pkg/steps/multi_stage/multi_stage.go, pkg/steps/multi_stage/multi_stage_test.go
As of now, the new CSI mutli-stage step credential system creates one SecretProviderClass (SPC) per credential, mounted to the test pod in as a CSI `volumeMount`. Since we need to shard the existing credential secrets, like this:
```
credentials:
- collection: team1
name: name
mount_path: /var/run
- collection: team1
name: diff-name
mount_path: /var/run
```
the existing system resulted in Kubernetes's `Invalid value: "<mount_path>": must be unique` errors (see e.g. [this test run](https://prow.ci.openshift.org/view/gs/test-platform-results/pr-logs/pull/openshift_release/65850/rehearse-65850-periodic-ci-stackrox-stackrox-master-ocp-4-12-merge-qa-e2e-tests-psalajov-test/1941045013337083904#1:build-log.txt%3A202)), because even if this results in a volumeMount with different name, the …
=> Fix CSI credentials naming mechanism

cmd/github-ldap-user-group-creator/main.go, cmd/github-ldap-user-group-creator/main_test.go
This PR exists to ease the resolution of the following error coming from `periodic-github-ldap-user-group-creator`:
```json
{
"component": "github-ldap-user-group-creator",
"file": "/go/src/github.com/openshift/ci-tools/cmd/github-ldap-user-group-creator/main.go:406",
"func": "main.makeGroups",
"ignoredOpenshiftPrivAdminNames": [
"openshift-art-build-bot"
],
"level": "error",
"msg": "These logins are members of openshift-priv but have no mapping to RH login.",
"severity": "error",
"time": "2025-07-15T01:33:16Z"
}
```
As of today the list of ignored admins is hardcoded. This PR introduces a new flag `skip-ocp-priv-admin` that makes it easier to add a new admin name without modifying and rebuilding the tool.
=> github-ldap-user-group-creator: add skip-ocp-priv-admin flag

pkg/jobconfig/files.go, pkg/prowgen/prowgen.go, pkg/prowgen/testdata/zz_fixture_TestGeneratePresubmitForTest_optional_presubmit.yaml, test/integration/ci-operator-prowgen/input/jobs/super/duper/super-duper-master-presubmits.yaml, test/integration/ci-operator-prowgen/output/jobs/super/duper/super-duper-master-presubmits.yaml
Basically I added the `optional` option that was being ignored during presubmit creation of the image jobs.
https://github.com/openshift/ci-tools/blob/4db4a5296ec405bc353a459a3a6edef3bdd53bd6/pkg/prowgen/prowgen.go#L124-L145
```
jobBaseGen.PodSpec.Add(Targets(presubmitTargets...))
presubmits[orgrepo] = append(presubmits[orgrepo], *generatePresubmitForTest(jobBaseGen, imagesTestName, info, func(options *generatePresubmitOptions) {
options.optional = optional
}))
```
And cleaned some priorities based on previous `release/ci-operator/jobs` for some fields.
=> [DPTP-4313] Respecting always_run from config file

pkg/slack/events/helpdesk/helpdesk-message.go
In the [#forum-ocp-testplatform](https://redhat.enterprise.slack.com/archives/CBN38N3MW) channel, messages that are generated by users through workflows (Question, PR review, etc) have automatically links and media previews under the message itself, e.g. like this:
In my opinion this creates a lot of visual clutter, so this PR toggles off the unfurling of links (which is automatically set to `true` in Slack API).
=> Disable link unfurling in helpdesk messages

pkg/group/config.go
Using "sigs.k8s.io/yaml" is actually enough for all yaml operations
=> Use sigs.k8s.io/yaml for all yaml operations

pkg/api/types.go
Add new azure-oadp-qe cluster profile to enable OADP QE testing on Azure.
Changes:
- Add ClusterProfileAzureOADPQE constant definition
- Register azure-oadp-qe in ClusterProfiles() list
- Map cluster profile to Azure cluster type (azure4)
- Configure lease type as azure-oadp-qe-quota-slice
Generated by: Claude (AI Assistant)
=> api: register azure-oadp-qe cluster profile

cmd/pr-reminder/main.go, cmd/pr-reminder/main_test.go
[Log](https://prow.ci.openshift.org/view/gs/test-platform-results/logs/periodic-pr-reminder/1951191286190968832) that show a message with 44 PRs works, and [log](https://prow.ci.openshift.org/view/gs/test-platform-results/logs/periodic-pr-reminder/1952278418158522368) with 47 PRs and above does not work.
=> Send via multiple messages when with large PR numbers

pkg/controller/multiarchbuildconfig/mirror.go, pkg/controller/multiarchbuildconfig/mirror_test.go
This adds a hack into our `MultiArchBuildConfig` to specify mirrors to QCI.
```yaml
apiVersion: ci.openshift.io/v1
kind: MultiArchBuildConfig
metadata:
name: managed-clonerefs
namespace: ci
spec:
build_spec:
output:
to:
kind: ImageStreamTag
name: managed-clonerefs:latest
namespace: ci
external_registries:
- registry.ci.openshift.org
- quay.io/openshift/ci
```
Some unit tests were modified because `targetImageRef` always have a `namespace` attached to it, even if it doesn't, registries expect the pattern `registry.url/project/image:tag`:
https://github.com/openshift/ci-tools/blob/890a9c32585a0327824f81f9f28306d771d0651f/pkg/controller/multiarchbuildconfig/multiarchbuildconfig.go#L169
=> Added a logic to chose the name of the mirrored image

cmd/vault-secret-collection-manager/main.go, cmd/vault-secret-collection-manager/main_test.go
This feature is creating secrets with . as name and . as value.
Since we are doing efforts on removing secrets with less than 3 characters, renaming this ones will allow us to see less noise on our investigations.
=> Rename dummy index secret creation on selfservice

cmd/prow-job-dispatcher/main.go, pkg/controller/ephemeralcluster/reconciler.go, pkg/controller/ephemeralcluster/reconciler_test.go, pkg/controller/ephemeralcluster/testdata/zz_fixture_ec_TestCreateProwJob_Handle_invalid_prow_config.yaml, pkg/controller/ephemeralcluster/testdata/zz_fixture_pj_TestCreateProwJob_An_EphemeralCluster_request_creates_a_ProwJob.yaml, pkg/dispatcher/ephemeralcluster.go, pkg/dispatcher/ephemeralcluster_test.go, pkg/dispatcher/server.go
Allow the possibility to properly dispatch any `ProwJob` originated by `EphemeralCluster` requests.
Prior to this, each PJ was statically assigned to `build01`, but now the dispatcher will use a new scheduling mechanism for every PJ whose name starts with the `ephemeralcluster` prefix.
The scheduling algorithm is a simple round-robin across the enabled clusters and, once a PJ is assigned to a cluster, the dispatcher remembers its decision for `24h`, that is the `TTL` for any NS created by ci-operator.
The PJ to cluster mapping is accomplished by using the human readable PJ name rather than the `metadata.name` stanza.
These two design decisions would ensure that any PJ gets dispatched to the same cluster and `ci-operator` will possibly reuse the same test NS. This means that `ci-operator` …
=> Dispatch EphemeralCluster requests coming from Konflux

pkg/defaults/defaults.go, pkg/steps/input_image_tag.go, pkg/steps/input_image_tag_test.go
- base_images & build_root will have `referencePolicy=Source`
- cluster-claimed releases will have `referencePolicy=Source`
=> referencePolicy= Source for base_images & cluster_claim releases

cmd/dptp-controller-manager/main.go, pkg/controller/ephemeralcluster/reconciler.go, pkg/controller/ephemeralcluster/reconciler_test.go, pkg/controller/ephemeralcluster/testdata/zz_fixture_ec_TestCreateProwJob_Failed_to_pull_PR_metadata.yaml, pkg/controller/ephemeralcluster/testdata/zz_fixture_ec_TestCreateProwJob_Inject_missing_PR_metadata.yaml, pkg/controller/ephemeralcluster/testdata/zz_fixture_pj_TestCreateProwJob_Failed_to_pull_PR_metadata.yaml, pkg/controller/ephemeralcluster/testdata/zz_fixture_pj_TestCreateProwJob_Inject_missing_PR_metadata.yaml
The `EphemeralCluster` object carries some metadata about the PR it has originated from. In some cases the metadata information doesn't contain the `pull_request` stanza, that is needed by Prow to properly create a `ProwJob`. When such a case occurs, we try to work around it and pull the metadata from the GitHub REST API endpoint `api.github.com`.
=> Konflux: Retrieve PR Metadata

pkg/group/config.go, pkg/gsm-secrets/config.go, pkg/gsm-secrets/diff_test.go, pkg/gsm-secrets/execution.go, pkg/gsm-secrets/execution_test.go, pkg/gsm-secrets/gcp.go, pkg/gsm-secrets/testdata/basic-config.yaml, pkg/gsm-secrets/testdata/zz_fixture_bindings_TestGetDesiredState_basic_config.yaml, pkg/gsm-secrets/testdata/zz_fixture_bindings_TestGetDesiredState_complex_config.yaml, pkg/gsm-secrets/testdata/zz_fixture_bindings_TestGetDesiredState_one_secret_collection.yaml, pkg/gsm-secrets/testdata/zz_fixture_collections_TestGetDesiredState_basic_config.yaml, pkg/gsm-secrets/testdata/zz_fixture_sa_TestGetDesiredState_basic_config.yaml, pkg/gsm-secrets/testdata/zz_fixture_sa_TestGetDesiredState_complex_config.yaml, pkg/gsm-secrets/testdata/zz_fixture_sa_TestGetDesiredState_one_secret_collection.yaml, pkg/gsm-secrets/testdata/zz_fixture_secrets_TestGetDesiredState_basic_config.yaml, pkg/gsm-secrets/types.go, pkg/gsm-secrets/types_test.go
GCP service account IDs have a strict 30-character limit, but our GSM SecretSync tool was using collection names directly as service account IDs (as each secret collection has a Service Account associated with it, that has update permissions to the collection). This would cause problems when users configured collection names longer than ~22 characters (accounting for the "-updater" suffix). We could enforce collection names be at max 22 characters, but 
a) it would be quite restrictive, 
b) it wouldn't solve the initial migration from Vault to GSM, where a lot of collection names are much longer than 22 characters.
Implement a smart service account ID generation strategy:
- **Short collection names**: Use the collection name directly (e.g., `alpha-secrets-updater`)
- **Long collection …
=> gsm-secrets: Implement hash-based SA IDs

cmd/autoperibolossync/README.md, cmd/autoperibolossync/main.go, cmd/private-org-peribolos-sync/README.md, cmd/private-org-peribolos-sync/main.go, cmd/private-org-peribolos-sync/main_test.go, cmd/private-org-sync/README.md, cmd/private-org-sync/main.go, cmd/private-org-sync/main_test.go
Private org tools now default to including org names
in target-org destination repos unless the org
is flattened with "--flatten-org". Legacy orgs
are defaulted to flattened to prevent substantial
changes to existing openshift-priv repos.
=> Eliminate non-openshift org naming collisions for private org synchronization
